### ISSUE TITLE
I cloned the latest code, but the compilation error!

### ISSUE THREAD

**Issue by hefengliang** [microsoft/vcpkg#8804]
**Describe the bug**
I cloned the latest code, but the compilation error!

**Environment**
- OS: Windows
- Compiler: vs2017

**To Reproduce**
1. ./bootstrap-vcpkg.bat
2. See error

**Failure logs** 
e:\vcpkg\vcpkg\vcpkg\toolsrc\src\vcpkg\base\hash.cpp(744): error C2065: “ENOENT”: 未声明的标识符 [E:\vcpkg\vcpkg\vcpkg\toolsrc
\vcpkglib\vcpkglib.vcxproj]

E:\vcpkg\vcpkg\vcpkg\scripts\bootstrap.ps1 : Building vcpkg.exe failed. Please ensure you have installed Visual Studio
with the Desktop C++ workload and the Windows SDK for Desktop C++.
所在位置 行:1 字符: 4
+ & {& 'E:\vcpkg\vcpkg\vcpkg\scripts\bootstrap.ps1' }
+    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,bootstrap.ps1

**Comment by JackBoosY** [comment]
@hefengliang, please install **English language package** using Visual Studio Installer first.
![image](https://user-images.githubusercontent.com/47264268/67838385-1f134480-fb2c-11e9-819f-f4bc18f631b0.png)

Thanks.

**Comment by hefengliang** [comment]
@JackBoosY,  I have installed the English package, but this seems to have no effect.

I know that this may be caused by my computer environment problem, because my current "vcpkg install glog" is also compiled incorrectly. In order not to reset my development environment, I still hope to find the cause of the problem.

vcpkg install glog
The following packages will be built and installed:
    glog[core]:x86-windows
Starting package 1/1: glog:x86-windows
Building package glog[core]:x86-windows...
-- Using cached E:/work/Tools/VcPkg/vcpkg/downloads/google-glog-v0.4.0.tar.gz
-- Using source at E:/work/Tools/VcPkg/vcpkg/buildtrees/glog/src/v0.4.0-46ccbc49a4
-- Configuring x86-windows
-- Building x86-windows-dbg
CMake Error at scripts/cmake/vcpkg_prettify_command.cmake:25 (list):
  list does not recognize sub-command JOIN
Call Stack (most recent call first):
  scripts/cmake/vcpkg_execute_build_process.cmake:135 (vcpkg_prettify_command)
  scripts/cmake/vcpkg_build_cmake.cmake:96 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/glog/portfile.cmake:26 (vcpkg_install_cmake)
  scripts/ports.cmake:74 (include)


Error: Building package glog:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: glog:x86-windows
  Vcpkg version: 2019.07.18-nohash

**Comment by JackBoosY** [comment]
From this error
> list does not recognize sub-command JOIN
I guess you installed cmake manually, please remove it or upgrade to latest version.

**Comment by hefengliang** [comment]
After I upgraded VS2017 to 2019, the problem was solved, thank you very much for your support.
