### ISSUE TITLE
[opencolorio] build with Python 3 support

### ISSUE THREAD

**Issue by kangstarr** [microsoft/vcpkg#8814]
****

**Is your feature request related to a problem? Please describe.**
Python 2 will be EOL'ed soon.

**Proposed solution**
It would be great to have OpenColorIO built with Python 3 support

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered if applicable.

**Additional context**

**Comment by LilyWangL** [comment]
Thanks for posting this issue. This issue has been fixed. So I am closing this issue for now.
