### ISSUE TITLE
[openMVG] Incorrect relative path in openMVG.config

### ISSUE THREAD

**Issue by bjornpiltz** [microsoft/vcpkg#8818]
**Describe the bug**
Installing openMVG generates a faulty openMVG.config.

**Environment**
- OS: Windows
- Compiler: MSVC 2019

**To Reproduce**
1. ./vcpkg install openmvg
2. ./vcpkg export openmvg
3. Create a cmake project which calls  find_package(openMVG REQUIRED)
4. Call cmake -DCMAKE_TOOLCHAIN_FILE=... ...

**Failure logs** 
```
CMake Error at <export>/installed/<triplet>/share/openMVG/OpenMVGConfig.cmake:42 (message):
  Failed to find OPENMVG - OpenMVG install root:
  <export>/installed/<triplet>/share/openMVG.
  Cannot find openMVG include files.
Call Stack (most recent call first):
  <export>/installed/<triplet>/share/openMVG/OpenMVGConfig.cmake:74 (OPENMVG_REPORT_NOT_FOUND)
  <export>/scripts/buildsystems/vcpkg.cmake:263 (_find_package)
```

**Additional context**
The problem is [this line](https://github.com/openMVG/openMVG/blob/develop/src/cmakeFindModules/OpenMVGConfig.cmake.in#L63-L64):
You have to replace `${CMAKE_MODULE_PATH}/../../../ ABSOLUTE` with `${CMAKE_MODULE_PATH}/../../ ABSOLUTE`

**Comment by JackBoosY** [comment]
Confirmed, we need to fix it.

**Comment by JackBoosY** [comment]
Hi @bjornpiltz, thanks for reporting this issue!
I've fixed it, please update vcpkg and rebuild openmvg.

Thanks.
