### ISSUE TITLE
Missing integration between vcpkg and CMake open folder?

### ISSUE THREAD

**Issue by simonowen** [Microsoft/vcpkg#882]
Short version:  I'm using Open Folder to work with a CMake files in Visual Studio, but find_package does not find libraries I installed using vcpkg.

Long version:

I have vcpkg installed and integrated, and see there are two main use cases on your examples page:

1. Use the installed libraries directly with a normal Visual Studio solution, simply including headers with automatic linking.  This works great with existing VS solutions.
2. With CMake, by running the generation step manually from the command-line to tell it the location of the vcpkg.cmake script. This works, but only creates a single build configuration.  It also requires a separate cmake installation to run, or digging out the path to the portable version used by vcpkg.

I'm using Open Folder in VS2017 to generate and manage CMake files.  This gives all the Debug/Release and Win32/x64 configurations, with easy debugging and individual settings for each.  However, find_package in the generation step is not finding vcpkg files.

I was hoping to be able to download a project that uses CMake, use Open Folder on it, and (as long as the dependencies are already present in vcpkg) just build and run it.  No command-line use, almost all the functionality of a solution file.

A work-around seems to be to edit CMakeSettings.json and add the -DCMAKE_TOOLCHAIN_FILE=... entry to the 'cmakeCommandArgs' settings, and force the generation to re-run.  Shouldn't this happen automatically for systems that have run the vcpkg integration?  Are there any future plans to do that?

**Comment by fuocor** [comment]
I cannot get the DCMAKE_TOOLCHAIN_FILE workaround working...
My CMakeSettings.json has
`      {
        "name": "x86-Debug",
        "generator": "Visual Studio 15 2017",
        "configurationType": "Debug",
        "buildRoot": "${env.LOCALAPPDATA}\\CMakeBuild\\${workspaceHash}\\build\\${name}",
        "cmakeCommandArgs": "-DCMAKE_TOOLCHAIN_FILE=\"C:\\git\\microsoft\\vcpkg\\scripts\\buildsystems\\vcpkg.cmake\"",
        "buildCommandArgs": "-m -v:minimal"
      },

and it CMAKE outputs:

1> Command line: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe  -G "Visual Studio 15 2017" -DCMAKE_INSTALL_PREFIX:PATH="C:\Users\rfuoco\AppData\Local\CMakeBuild\57c7776a-9a94-3b3c-8d40-e85c736b9e01\build\install" -DCMAKE_TOOLCHAIN_FILE="C:\git\microsoft\vcpkg\scripts\buildsystems\vcpkg.cmake" --DCMAKE_BUILD_TYPE="Debug" "C:\Users\rfuoco\Documents\Visual Studio 2017\Projects\LinuxProject2\LinuxProject2"
1> Working directory: C:\Users\rfuoco\AppData\Local\CMakeBuild\57c7776a-9a94-3b3c-8d40-e85c736b9e01\build\x86-Debug
1> -- The C compiler identification is MSVC 19.10.25017.0
1> -- The CXX compiler identification is MSVC 19.10.25017.0
1> -- Check for working C compiler: c:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.10.25017/bin/HostX86/x86/cl.exe
1> -- Check for working C compiler: c:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.10.25017/bin/HostX86/x86/cl.exe -- works
1> -- Detecting C compiler ABI info
1> -- Detecting C compiler ABI info - done
1> -- Check for working CXX compiler: c:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.10.25017/bin/HostX86/x86/cl.exe
1> -- Check for working CXX compiler: c:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.10.25017/bin/HostX86/x86/cl.exe -- works
1> -- Detecting CXX compiler ABI info
1> -- Detecting CXX compiler ABI info - done
1> -- Detecting CXX compile features
1> -- Detecting CXX compile features - done
1> CMake Error at C:\Users\rfuoco\Documents\Visual Studio 2017\Projects\LinuxProject2\LinuxProject2\CMakeLists.txt:8 (find_package):
1>   By not providing "Findrxcpp.cmake" in CMAKE_MODULE_PATH this project has
1>   asked CMake to find a package configuration file provided by "rxcpp", but
1>   CMake did not find one.
1> 
1>   Could not find a package configuration file provided by "rxcpp" with any of
1>   the following names:
1> 
1>     rxcppConfig.cmake
1>     rxcpp-config.cmake
1> 
1>   Add the installation prefix of "rxcpp" to CMAKE_PREFIX_PATH or set
1>   "rxcpp_DIR" to a directory containing one of the above files.  If "rxcpp"
1>   provides a separate development package or SDK, be sure it has been
1>   installed.
1> 
1> 
1> -- Configuring incomplete, errors occurred!
1> See also "C:/Users/rfuoco/AppData/Local/CMakeBuild/57c7776a-9a94-3b3c-8d40-e85c736b9e01/build/x86-Debug/CMakeFiles/CMakeOutput.log".
1> C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe  -G "Visual Studio 15 2017" -DCMAKE_INSTALL_PREFIX:PATH="C:\Users\rfuoco\AppData\Local\CMakeBuild\57c7776a-9a94-3b3c-8d40-e85c736b9e01\build\install" -DCMAKE_TOOLCHAIN_FILE="C:\git\microsoft\vcpkg\scripts\buildsystems\vcpkg.cmake" --DCMAKE_BUILD_TYPE="Debug" "C:\Users\rfuoco\Documents\Visual Studio 2017\Projects\LinuxProject2\LinuxProject2" returned with exit code: 1

Even if I run the cmake command-line and fixing the '--DCMAKE_BUILD_TYPE' to '-DCMAKE_BUILD_TYPE', I get the error.

My question is how does the vcpkg resolve the triplet for the build configuration.

**Comment by eco** [comment]
I've at least documented how to do this in #997.
