### ISSUE TITLE
 Package: msmpi:x86-windows   Vcpkg version: 2019.09.12-nohash

### ISSUE THREAD

**Issue by thierleft** [microsoft/vcpkg#8821]
**Host Environment**
- OS: Windows 10

**To Reproduce**
`./vcpkg install msmpi`

**Comment by JackBoosY** [comment]
Hi @thierleft, thanks for reporting this issue.
I cannot repro it on my machine now, please provide the failure logs in _VCPKG_PATH/buildtrees/msmpi_.

Thanks.

**Comment by JackBoosY** [comment]
If this issue is still not resolved, please reopen it.
