### ISSUE TITLE
How do I add a new port

### ISSUE THREAD

**Issue by ig-or** [microsoft/vcpkg#8823]
Hello, I  have a quite general question. I was thinking about adding a port to some library. But since this library is not supported on all the platforms/configurations, I added a number of "vcpkg_fail_port_install" in the portfile.cmake file, as was suggested  [https://github.com/microsoft/vcpkg/issues/8602#issuecomment-543033779](https://github.com/microsoft/vcpkg/issues/8602#issuecomment-543033779)  

Now this port tells "Some checks were not successful" : [https://github.com/microsoft/vcpkg/pull/8628l](https://github.com/microsoft/vcpkg/pull/8628)

Is this an expected behavior? Should the port pass all the checks in order to be integrated? Should every port support all the platforms/configurations? If it is possible not to support all the configurations, then then what is the correct way to handle this? 

Best regards, Igor

**Comment by JackBoosY** [comment]
Hi @ig-or, thanks join us as our contributor! We already have [documentation](https://github.com/microsoft/vcpkg/blob/master/docs/examples/packaging-github-repos.md) and [examples](https://github.com/microsoft/vcpkg/tree/master/scripts/templates), please see these link.
And we will pay attention on you PR.

Thanks.

**Comment by JackBoosY** [comment]
Does this issue still bother you?

**Comment by ig-or** [comment]
Will be able to check again after January 2, sorry..
Happy new year!!

**Comment by JackBoosY** [comment]
If this issue is still not resolved, please reopen it.
