### ISSUE TITLE
Can I delete packages folder?

### ISSUE THREAD

**Issue by dzmunk** [microsoft/vcpkg#8826]
https://docs.microsoft.com/en-us/cpp/build/vcpkg?view=vs-2019

**Comment by ChaoJia** [comment]
I think `packages` folder can be safely removed to save disk space, as suggested in the [documentation](https://vcpkg.readthedocs.io/en/latest/about/faq/#how-can-i-remove-temporary-files).  
vcpkg keeps track of installed files in `${vcpkg_root}/installed/vcpkg/info/${port_name}_${port_version}_${triplet}.list` and of installed ports in `${vcpkg_root}/installed/vcpkg/info/status`

**Comment by cbezault** [comment]
If you don't need to export ports you can delete it. Otherwise don't.

**Comment by ChaoJia** [comment]
Good to know. Thanks!
