### ISSUE TITLE
What is the policy on SIMD(SSE41,AVX, AVX2) etc?

### ISSUE THREAD

**Issue by bjornpiltz** [microsoft/vcpkg#8838]
I wonder if there is an official policy on SIMD extensions. I tried vcpkg to build a slew of static libraries and noticed that the following have compiled in AVX ~~primitives~~ instructions (which is a no-go for my use case):

- jpeg.lib: avx2
- turbojpeg.lib: avx2
- vlsift.lib: avx
- webp.lib: avx
- webpdecoder.lib: avx
- openMVG_*.lib: avx[2]

There are several more which use sse2 and sse4.1, which isn't a problem for me personally.

The only port which enables AVX as a feature seems to be `fftw3`. Furthermore `libjpeg-turbo` does a heuristic based on `VCPKG_TARGET_ARCHITECTURE`. The others listed above seem to do the equivalent of `-march=native` and base the decision on the capabilities of the build node.

I would like a clarification on this.

**Comment by NancyLi1013** [comment]
Hi @bjornpiltz thanks for posting this issue. Could you please give an example to describe this issue?
I cannot make sense this issue clearly now according to the above info. Such as what's the meaning of "AVX primitives" here?
Could you please help provide more info about this issue?

**Comment by Neumann-A** [comment]
@NancyLi1013: He probably means intrinsics instead of primitives e.g. https://software.intel.com/sites/landingpage/IntrinsicsGuide/

but he needs to specify the triplet. I think some of those ports have internal checks to see which instruction set they are able to use on the host machine or are using the compilers default but there is probably a way to overwrite that behavior (but don't ask me how).

**Comment by bjornpiltz** [comment]
@NancyLi1013 
Oh, sure I was a bit sloppy writing the question. By primitives I meant instructions.

For example, run the following in a powershell:
```
dumpbin.exe  /disasm:nobytes openMVG_features.lib | where { $_ -match "vpbroadcast*"}
  00000000000000B4: vpbroadcastd ymm1,xmm1
  00000000000000B4: vpbroadcastd ymm1,xmm1
  00000000000000D1: vpbroadcastd ymm0,xmm0
  00000000000000F0: vpbroadcastd ymm1,xmm1
  0000000000000117: vpbroadcastd ymm0,xmm0
```
You see that the code includes the AVX2 instruction `vpbroadcastd`. Same goes for `vextracti128`

This means that running this code on a processor not listed [here](https://en.wikipedia.org/wiki/Advanced_Vector_Extensions#CPUs_with_AVX2) will lead to a hard crash.

To be clear, I'm not worried by libraries which put the AVX* code in conditional branches. libjpeg might have been a false positive in this respect, since it does a runtime determination whether to execute AVX2 code.
See: https://github.com/libjpeg-turbo/libjpeg-turbo/blob/6d8caa9f88184ad1698e91c94b37acb9506dacf0/simd/x86_64/jsimd.c#L53
and: https://github.com/libjpeg-turbo/libjpeg-turbo/blob/6d8caa9f88184ad1698e91c94b37acb9506dacf0/simd/x86_64/jsimd.c#L973

In the case of OpenMVG, this issue can be addressed with the CMake option `-DTARGET_ARCHITECTURE=none|core`. The default for TARGET_ARCHITECTURE is `auto` which is the equivalent of `-march=native`. Look [here](https://github.com/openMVG/openMVG/blob/db92617fea420363abcbad1cb3773706f75012ad/src/cmakeFindModules/OptimizeForArchitecture.cmake#L204
).

I don't know how many other libraries are affected by this, since I only installed and tested a small subset.

@Neumann-A 
My triplet looks like this:
```cmake
set(VCPKG_TARGET_ARCHITECTURE x64)
 
# Always use the dynamic CRT.
set(VCPKG_CRT_LINKAGE dynamic)
 
# Prefer to build static libs.
set(VCPKG_LIBRARY_LINKAGE static)
```
But the problem should be the same for `x64-windows-*`

**Comment by Neumann-A** [comment]
@bjornpiltz: try adding  the required compiler flag for your target architecture into `VCPKG_C_FLAGS` or `VCPKG_CXX_FLAGS`. Visual studio has /arch:none as the default. I don't know about gcc's or clang's default flag so maybe setting it into those variables will overwrite their default behavior. But be aware that those flags might only be in used in CMake based ports. Alternatively you could try supplying an environment with the correct variables being set

**Comment by bjornpiltz** [comment]
@Neumann-A Thanks,that could help for some ports!

In the case of openMVG, though,  you can only do it by adding the option `-DTARGET_ARCHITECTURE=(core|none|...)` See [here](https://github.com/openMVG/openMVG/blob/db92617fea420363abcbad1cb3773706f75012ad/src/cmakeFindModules/OptimizeForArchitecture.cmake#L292).

The more general question is, what are ports supposed to do?

1.   Is there an instruction set which is so old as too be considered safe, or
2.  are ports allowed to - as the openMVG one is doing - too utilize all CPU features found on the build node?

**Comment by heydojo** [comment]
_For MSVC:_
**/arch:none** is the default.
**/arch:avx** is probably safe to set but there is always the 1% who insist upon compiling software on a potato.
**/arch:avx2** can be set if you are happy to alienate some users on older systems but just be sure to offer out information about minimum system requirements.

For maximum compatibility, ports should not need to set avx or avx2 in vcpkg (any that do should be fixed to patch the directive out.) Video encoders especially should not solely rely on hardware instructions but I can understand why for optimal performance (especially during encoding that avx2, etc are important to them.)
As already mentioned, you can set the flags yourself if need be, if you need either instruction set via the `VCPKG_CXX_FLAGS` or `VCPKG_C_FLAGS` variables inside of a triplet.

Maybe if a port requires a hardware instruction flag set at compile time, it would be great if it was not a default but something which is set inside a control file using the `Feature: ` declaration.
