### ISSUE TITLE
boost build failure

### ISSUE THREAD

**Issue by TheVeryDarkness** [microsoft/vcpkg#8841]
My command in cmd: vcpkg install boost-compatibility[core]:x64-windows

The following packages will be built and installed:
    boost-compatibility[core]:x64-windows
Starting package 1/1: boost-compatibility:x64-windows
Building package boost-compatibility[core]:x64-windows...
-- Using cached D:/1853308/Documents/GitHub/vcpkg/vcpkg/downloads/boostorg-compatibility-boost-1.71.0.tar.gz
-- Using source at D:/1853308/Documents/GitHub/vcpkg/vcpkg/buildtrees/boost-compatibility/src/ost-1.71.0-d69e2f6205
-- Packaging headers
-- Packaging headers done
-- Downloading https://raw.githubusercontent.com/boostorg/boost/boost-1.71.0/LICENSE_1_0.txt...
-- Downloading https://raw.githubusercontent.com/boostorg/boost/boost-1.71.0/LICENSE_1_0.txt... Failed. Status: 7;"Couldn't connect to server"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:175 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  installed/x64-windows/share/boost-vcpkg-helpers/boost-modular-headers.cmake:17 (vcpkg_download_distfile)
  ports/boost-compatibility/portfile.cmake:14 (boost_modular_headers)
  scripts/ports.cmake:94 (include)

Error: Building package boost-compatibility:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-compatibility:x64-windows
  Vcpkg version: 2019.09.12-nohash

Additionally, attach any relevant sections from the log files above.

**Comment by NancyLi1013** [comment]
Hi @TheVeryDarkness thanks for posting this issue. This should be a proxy issue on your local internet.
I can download this` LICENSE` file successfully on my local.
You can put this file on your machine here
[boost_LICENSE_1_0.txt](https://github.com/microsoft/vcpkg/files/3796557/boost_LICENSE_1_0.txt)
 
`D:/1853308/Documents/GitHub/vcpkg/vcpkg/downloads`

Then try to install this port again.

Thanks.
