### ISSUE TITLE
How to specify customized naming schema for ACE libraries

### ISSUE THREAD

**Issue by Lewis123d** [microsoft/vcpkg#8847]
Hi,
I am a vcpkg junior.
Now I need to integrate ACE libraries, but I have to rename them in my case.
For example, ACEd.dll and ACEd.lib(default) -->ace_vc141_x64-d.dll/lib.
Is there any way that I can easily rename these libraries by vcpkg?

Thanks.

**Comment by Lewis123d** [comment]
> Hi,
> I am a vcpkg junior.
> Now I need to integrate ACE libraries, but I have to rename them in my case.
> For example, ACEd.dll and ACEd.lib(default) -->ace_vc141_x64-d.dll/lib.
> Is there any way that I can easily rename these libraries by vcpkg?
> 
> Thanks.

**Comment by JackBoosY** [comment]
Hi @Lewis123d, you can modify _VCPKG_PATH/ports/ace/portfile.cmake_ line 61 from:
`set(LIB_DEBUG_SUFFIX d.lib)` to `set(LIB_DEBUG_SUFFIX _vc141_x64-d.lib)`,
modify line 60 from:
`set(LIB_RELEASE_SUFFIX .lib)` to `set(LIB_RELEASE_SUFFIX _vc141_x64.lib)`

Thanks.

**Comment by Lewis123d** [comment]
Hi @JackBoosY ,
I apologize for not making my points clear.
These scripts you modified seems that it JUST "RENAME" the libraries.

And I want the result is like following scripts(I tried before but failed): 
`set(LIB_DEBUG_SUFFIX d.lib) to set(LIB_DEBUG_SUFFIX _vc141_x64-d.lib)`
vcpkg builds with this scripts, and finally output files(libs/dlls) are as I expected. 

By the way, I also tried sqlite3 and it seems to work fine.
I modify VCPKG_PATH/ports/sqlite3/portfile.cmake, line26
`
vcpkg_configure_cmake(
    SOURCE_PATH ${SOURCE_PATH}
    PREFER_NINJA
    OPTIONS
        -DSQLITE3_SKIP_TOOLS=${SQLITE3_SKIP_TOOLS}
    OPTIONS_RELEASE
		-DCMAKE_RELEASE_POSTFIX=-vc_141_x64
	OPTIONS_DEBUG
        -DSQLITE3_SKIP_TOOLS=ON
		-DCMAKE_DEBUG_POSTFIX=-vc_141_x64-d
)
`
Thanks.

**Comment by Lewis123d** [comment]
Hi @JackBoosY ,
Is any news about this question?
If you need more information, please let me know.

Thanks.

**Comment by JackBoosY** [comment]
@Lewis123d I will give you a patch to resolve your request later.

**Comment by Lewis123d** [comment]
@JackBoosY 
Thank you for your reply.
Yes. I need to generate the library name adding some other postfix(maybe prefix) fields.

**Comment by JackBoosY** [comment]
We cannot add `"/property:TargetName=ace-${TARGET_TRIPLET}"` and `"/property:OutputFile=ace-${TARGET_TRIPLET}"` as `vcpkg_build_msbuild` options because it's build several targets, and I didn't find the option in `.pl`.

Unzip and replace this file with _VCPKG_PATH/ports/ace/portfile.cmake_
[portfile.zip](https://github.com/microsoft/vcpkg/files/3803314/portfile.zip)

Then rebuild ace.

You can modify ${TARGET_TRIPLET} in _VCPKG_PATH/ports/ace/portfile.cmake_ as needed.

Thanks.

**Comment by Lewis123d** [comment]
Hi @JackBoosY 
I also add a script to modfiy PDB files following above rule: 
`string(REPLACE "ACEd_dll.pdb<\/ProgramDatabaseFile>" "ACE_${GVD_POST_FIX}-d.pdb<\/ProgramDatabaseFile>" ACE_PRJ_FILE "${ACE_PRJ_FILE}")`
And it works!. Thank you for your help. :)

By the way, another question in this ACE case. I need to manually assign include and library path in the CmakeList for my own project, am I right? In other words, Can  I  use simple scripts like `find_package(ace CONFIG REQUIRED)` and `target_link_libraries(main PRIVATE ace)` and let vcpkg assign path automatically?

Thanks.

**Comment by JackBoosY** [comment]
When using `find_package`, the port should export `${PORT}Config.cmake` or `${PORT}-config.cmake` files, which means we need to build it with cmake and use `install(EXPORT)`. Or we can use `Find${PORT}.cmake` provided by cmake. Obviously this port does not support this method.

However, we can still use `find_library` and `find_path` to use this port in cmake.

And I considered to make a `vcpkg_cmake_wrapper.cmake` to solve this problem.

**Comment by Lewis123d** [comment]
Hi @JackBoosY,
I can not find this file in whole directory of vcpkg: vcpkg_cmake_wrapper.cmake.

**Comment by JackBoosY** [comment]
@Lewis123d Yep, because we didn't add it yet.
Please use `find_path(ace_INCLUDES ACE.h PATH_SUFFIXES ace)` and `find_library(ace ACE_x86-windows REQUIRED)` first.

**Comment by jimwang118** [comment]
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.
