### ISSUE TITLE
How to ensure that each developer has the same version of dependencies?

### ISSUE THREAD

**Issue by nickaleks** [microsoft/vcpkg#8849]
As I understand, vcpkg's philosophy is to have a singular snapshot of all the dependecies which work together (to avoid diamond problem). I like that approach a lot, however I am interested in how to perform package's upgrade in a controllable way:
1. Each developer must have the same version of packages.
2. Package upgrades are performed either manually by developer, or automatically by CI system.
3. Specific version of source code (e.g. commit) is always built against the same version of packages, regardless of when the project is built. So even after upgrade was performed, old code is built against old dependencies (reproducibility).

Since vcpkg does not allow configuration of the version, the only way to manage that seems to be checking out vcpkg into source control, and each upgrade would result in a commit which alters vcpkg state. This way the developer can just clone the repo, and all the deps will be already present.

The other alternative is to ditch reproducibility of the build and always build against latest available version. However, this requires some level of robustness for the infrastructure, development practices and library authors (as abseil does for example).

the question is whether checking out vcpkg into the source repository is a good practice, or if there are any different approaches to ensure reproducibility of the environment. I would appreciate opinions of the developers as well as people who use vcpkg for dependency management.

**Comment by Laro88** [comment]
I have the same issue - how to handle "more than one" teams? It is crucial to get a specific version of vcpkg & and all packages inside to be able to reproduce problems & ensure that all developers are on the same level.
Presently we have a small mqtt-paho issue, and it can be resolved by upgrading, however should anything go wrong it would be nice to be able to downgrade.

A "git checkout tags/2019-05" or something like that & and some official recommendations from Microsoft on how to address these issues.

**Comment by JackBoosY** [comment]
@Laro88 You can use the command `vcpkg x-history ${PORT}` to view the port history and use `git reset ${HASH}` to reset to a specific version of the code.

**Comment by JackBoosY** [comment]
@nickaleks For repeatable builds, you can follow the steps below for parallel development:
1. Use `vcpkg x-history` to see the last modified commit ID for the desired version.
2. Use `git reset ${commit_ID}` to backtracking the port to the specified version each time.
3. Build vcpkg.
4. Build the port.
5. Build your private project.

For non-repeatable builds:
1. Use `vcpkg x-history` to see the last modified commit ID for the desired version.
2. Use `git reset ${commit_ID}` to backtracking the port to the specified version each time.
3. Build vcpkg.
4. Build the port.
5. Use `vcpkg export ${PORT}` to export the generated libraries and header files.
6. Distribute the exported package to individual developers.
7. Import the package using `vcpkg import`.
8. Build your private project.

**Comment by nickaleks** [comment]
> @Laro88 You can use the command `vcpkg x-history ${PORT}` to view the port history and use `git reset ${commit_ID}` to reset to a specific version of the code.

This works, when we need to rollback to the specified version of a single port. However I am more interested in how to keep the whole environment (all dependencies) reproducible for each commit to my project.

I guess the answer is to keep the commit id of the vcpkg against which the given commit was built in my project's repo, and then build that commit of vcpkg to reproduce the specific environment. I would want to build vcpkg itself, as well as the changed deps. The workflow I have in mind:
1. Use vcpkg's commit hash stored in my project's repository
2. `git pull` vcpkg if necessary
2. `git reset` vcpkg to that commit id
3. Build vcpkg
4. `vckpg upgrade` to build updated deps (not all of them)
5. Build my private project

The key here is that I want to have a  single vcpkg repo, which I should be able to upgrade/downgrade when switching to different commits of my own project.  @JackBoosY Do you know if vcpkg allows me to do that out of the box, or how to achieve the same outcome?

**Comment by JackBoosY** [comment]
@nickaleks You can fork vcpkg and create a new branch to do this.

**Comment by nickaleks** [comment]
I think everything's clear for now. Thank you!
