### ISSUE TITLE
[libepoxy] fails to build 

### ISSUE THREAD

**Issue by navidR** [Microsoft/vcpkg#885]
> C:\Program Files (x86)\Microsoft Visual C++ Build Tools>vcpkg install libepoxy
> -- CURRENT_INSTALLED_DIR=C:/Users/navid/AppData/Local/Lib/vcpkg/installed/x86-windows
> -- DOWNLOADS=C:/Users/navid/AppData/Local/Lib/vcpkg/downloads
> -- CURRENT_PACKAGES_DIR=C:/Users/navid/AppData/Local/Lib/vcpkg/packages/libepoxy_x86-windows
> -- CURRENT_BUILDTREES_DIR=C:/Users/navid/AppData/Local/Lib/vcpkg/buildtrees/libepoxy
> -- CURRENT_PORT_DIR=C:/Users/navid/AppData/Local/Lib/vcpkg/ports/libepoxy/.
> -- Using cached C:/Users/navid/AppData/Local/Lib/vcpkg/downloads/libepoxy-7d58fd3d47d2d69f2b1b9f08325302e4eeff9ebe.zip
> -- Testing integrity of cached file...
> -- Testing integrity of cached file... OK
> -- Extracting done
> -- Configuring x86-windows-rel
> CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:14 (message):
>     Command failed: C:/Users/navid/AppData/Local/Lib/vcpkg/downloads/tools/python/python.exe;C:/Users/navid/AppData/Local/Lib/vcpkg/downloads/tools/meson/meson-0.38.1/meson.py;--buildtype;plain;--backend;ninja;--default-library;shared;--prefix;C:/Users/navid/AppData/Local/Lib/vcpkg/packages/libepoxy_x86-windows;C:/Users/navid/AppData/Local/Lib/vcpkg/buildtrees/libepoxy/src/libepoxy-7d58fd3d47d2d69f2b1b9f08325302e4eeff9ebe
>     Working Directory: C:/Users/navid/AppData/Local/Lib/vcpkg/buildtrees/libepoxy/x86-windows-rel
>     See logs for more information:
>       C:\Users\navid\AppData\Local\Lib\vcpkg\buildtrees\libepoxy\config-x86-windows-rel-out.log
>       C:\Users\navid\AppData\Local\Lib\vcpkg\buildtrees\libepoxy\config-x86-windows-rel-err.log
> 
> Call Stack (most recent call first):
>   scripts/cmake/vcpkg_configure_meson.cmake:51 (vcpkg_execute_required_process)
>   ports/libepoxy/portfile.cmake:20 (vcpkg_configure_meson)
>   scripts/ports.cmake:73 (include)
> 
> 
> Error: Building package libepoxy:x86-windows failed with: BUILD_FAILED
> Please ensure you're using the latest portfiles with `.\vcpkg update`, then
> submit an issue at https://github.com/Microsoft/vcpkg/issues including:
>   Package: libepoxy:x86-windows
>   Vcpkg version: 0.0.76-c433841ef5bcb42b460b95b48c2d425ebd746e1a
> 
> Additionally, attach any relevant sections from the log files above.
> 
> C:\Program Files (x86)\Microsoft Visual C++ Build Tools>

**Comment by navidR** [comment]
> The Meson build system
> Version: 0.38.1
> Source dir: C:\Users\navid\AppData\Local\Lib\vcpkg\buildtrees\libepoxy\src\libepoxy-7d58fd3d47d2d69f2b1b9f08325302e4eeff9ebe
> Build dir: C:\Users\navid\AppData\Local\Lib\vcpkg\buildtrees\libepoxy\x86-windows-rel
> Build type: native build
> Project name: libepoxy
> 
> Meson encountered an error in file meson.build, line 1, column 0:
> Unknown compiler(s): "cl, cc, gcc, clang"
> The follow exceptions were encountered:
> Running "gcc --version" gave "[WinError 2] The system cannot find the file specified"
> Running "clang --version" gave "[WinError 2] The system cannot find the file specified"
> Running "cc --version" gave "[WinError 2] The system cannot find the file specified"
> Running "cl /?" gave "[WinError 2] The system cannot find the file specified"


FWIW I do have cl on my path and I do compile and use many packages from my Visual C++ 2015 x86 native build tools command prompt. It seems meson cannot find cl.

**Comment by ras0219-msft** [comment]
Hi again!

In order to maximize the robustness of Vcpkg, we completely sanitize the environment that packages are built in. Unless there's a bug, you should get the exact same experience inside and outside a VS developer prompt.

> Vcpkg version: 0.0.76-c433841ef5bcb42b460b95b48c2d425ebd746e1a

The commit https://github.com/Microsoft/vcpkg/commits/c433841 is about 2 weeks old -- could you re-run bootstrap and verify again?

Possibly related to #829.

**Comment by navidR** [comment]
Sorry, I completely forget about updating vcpkg, But after updating it last commit, same error happened.

**Comment by ras0219-msft** [comment]
Ok, I've added an internal command `vcpkg env` which will drop you into a cmd that looks exactly like the environment in which we build packages.

Could you pull, rebuild, then run
```
>vcpkg env
>where cl
>cl /?
```

**Comment by navidR** [comment]
```
C:\Program Files (x86)\Microsoft Visual C++ Build Tools>vcpkg install libepoxy
-- CURRENT_INSTALLED_DIR=C:/Users/navid/AppData/Local/Lib/vcpkg/installed/x86-windows
-- DOWNLOADS=C:/Users/navid/AppData/Local/Lib/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=C:/Users/navid/AppData/Local/Lib/vcpkg/packages/libepoxy_x86-windows
-- CURRENT_BUILDTREES_DIR=C:/Users/navid/AppData/Local/Lib/vcpkg/buildtrees/libepoxy
-- CURRENT_PORT_DIR=C:/Users/navid/AppData/Local/Lib/vcpkg/ports/libepoxy/.
-- Using cached C:/Users/navid/AppData/Local/Lib/vcpkg/downloads/libepoxy-7d58fd3d47d2d69f2b1b9f08325302e4eeff9ebe.zip
-- Testing integrity of cached file...
-- Testing integrity of cached file... OK
-- Extracting done
-- Configuring x86-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:14 (message):
    Command failed: C:/Users/navid/AppData/Local/Lib/vcpkg/downloads/tools/python/python.exe;C:/Users/navid/AppData/Local/Lib/vcpkg/downloads/tools/meson/meson-0.38.1/meson.py;--buildtype;plain;--backend;ninja;--default-library;shared;--prefix;C:/Users/navid/AppData/Local/Lib/vcpkg/packages/libepoxy_x86-windows;C:/Users/navid/AppData/Local/Lib/vcpkg/buildtrees/libepoxy/src/libepoxy-7d58fd3d47d2d69f2b1b9f08325302e4eeff9ebe
    Working Directory: C:/Users/navid/AppData/Local/Lib/vcpkg/buildtrees/libepoxy/x86-windows-rel
    See logs for more information:
      C:\Users\navid\AppData\Local\Lib\vcpkg\buildtrees\libepoxy\config-x86-windows-rel-out.log
      C:\Users\navid\AppData\Local\Lib\vcpkg\buildtrees\libepoxy\config-x86-windows-rel-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_meson.cmake:51 (vcpkg_execute_required_process)
  ports/libepoxy/portfile.cmake:20 (vcpkg_configure_meson)
  scripts/ports.cmake:73 (include)


Error: Building package libepoxy:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libepoxy:x86-windows
  Vcpkg version: 0.0.78-d9a403453904261c6b34c5d33557134b9fe3a8a0

Additionally, attach any relevant sections from the log files above.

C:\Program Files (x86)\Microsoft Visual C++ Build Tools>vcpkg env
Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\Users\navid\AppData\Local\Lib\vcpkg>where cl
INFO: Could not find files for the given pattern(s).

C:\Users\navid\AppData\Local\Lib\vcpkg>cl /?
'cl' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\navid\AppData\Local\Lib\vcpkg>

```

**Comment by navidR** [comment]
Content of config-x86-windows-rel-out : 

```
The Meson build system
Version: 0.38.1
Source dir: C:\Users\navid\AppData\Local\Lib\vcpkg\buildtrees\libepoxy\src\libepoxy-7d58fd3d47d2d69f2b1b9f08325302e4eeff9ebe
Build dir: C:\Users\navid\AppData\Local\Lib\vcpkg\buildtrees\libepoxy\x86-windows-rel
Build type: native build
Project name: libepoxy

Meson encountered an error in file meson.build, line 1, column 0:
Unknown compiler(s): "cl, cc, gcc, clang"
The follow exceptions were encountered:
Running "gcc --version" gave "[WinError 2] The system cannot find the file specified"
Running "cc --version" gave "[WinError 2] The system cannot find the file specified"
Running "clang --version" gave "[WinError 2] The system cannot find the file specified"
Running "cl /?" gave "[WinError 2] The system cannot find the file specified"

```

**Comment by ras0219-msft** [comment]
Ok, great, thanks! It looks like whatever vcvarsall.bat we found and ran doesn't result in a functional developer prompt.

We've added some further debugging capabilities in the latest versions, so if you pull+bootstrap and run `vcpkg env --debug`, we'll print out the full command line used to initialize the inner environment. On my machine, it looks like:
```
[DEBUG] _wspawnlpe(cmd.exe /c ""C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x86 >nul 2>&1 && cmd")
```

It would also be useful to run `scripts\findAnyMSBuildWithCppPlatformToolset.ps1 -verbose` which will print out a bunch of debug information about all the toolsets we can locate on your machine.

What do those two say?

**Comment by navidR** [comment]
```
C:\Users\navid\AppData\Local\Lib\vcpkg > vcpkg env --debug
[DEBUG] _wspawnlpe(cmd.exe /c ""C:\Program Files (x86)\VC\vcvarsall.bat" x86  2>&1 && cmd")
Error in script usage. The correct usage is:
    "C:\Program Files (x86)\VC\vcvarsall.bat" [option]
  or
    "C:\Program Files (x86)\VC\vcvarsall.bat" [option] store
  or
    "C:\Program Files (x86)\VC\vcvarsall.bat" [option] [version number]
  or
    "C:\Program Files (x86)\VC\vcvarsall.bat" [option] store [version number]
where [option] is: x86 | amd64 | arm | x86_amd64 | x86_arm | amd64_x86 | amd64_arm
where [version number] is either the full Windows 10 SDK version number or "8.1" to use the windows 8.1 SDK
:
The store parameter sets environment variables to support
  store (rather than desktop) development.
:
For example:
    "C:\Program Files (x86)\VC\vcvarsall.bat" x86_amd64
    "C:\Program Files (x86)\VC\vcvarsall.bat" x86_arm store
    "C:\Program Files (x86)\VC\vcvarsall.bat" x86_amd64 10.0.10240.0
    "C:\Program Files (x86)\VC\vcvarsall.bat" x86_arm store 10.0.10240.0
    "C:\Program Files (x86)\VC\vcvarsall.bat" x64 8.1
    "C:\Program Files (x86)\VC\vcvarsall.bat" x64 store 8.1
:
Please make sure either Visual Studio or C++ Build SKU is installed.
Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

```

**Comment by navidR** [comment]
```
C:\Users\navid\AppData\Local\Lib\vcpkg > scripts\findAnyMSBuildWithCppPlatformToolset.ps1 -verbose
VERBOSE: Executing findAnyMSBuildWithCppPlatformToolset.ps1 with DisableVS2017=False, DisableVS2015=False
VERBOSE:

VERBOSE: Checking for MSBuild from VS2017 instances...
VERBOSE: Examining C:\Users\navid\AppData\Local\Lib\vcpkg\scripts for .vcpkg-root
VERBOSE: Examining C:\Users\navid\AppData\Local\Lib\vcpkg for .vcpkg-root - Found
VERBOSE: Examining C:\Users\navid\AppData\Local\Lib\vcpkg\scripts for .vcpkg-root
VERBOSE: Examining C:\Users\navid\AppData\Local\Lib\vcpkg for .vcpkg-root - Found
VERBOSE: VS2017 Candidates:
VERBOSE:

VERBOSE: Checking for MSBuild from VS2015 in Program Files...
VERBOSE: Program Files Candidate locations: C:\Program Files (x86),C:\Program Files
VERBOSE: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\cl.exe - Found
VERBOSE: Found @{msbuildExePath=C:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe; toolsetVersion=v140}
VERBOSE: C:\Program Files\Microsoft Visual Studio 14.0\VC\bin\cl.exe - Not Found
VERBOSE:

VERBOSE: Checking for MSBuild from VS2015 through the registry...
VERBOSE: Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\visualstudio\14.0 - Not Found
VERBOSE: Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\visualstudio\14.0 - Not Found
VERBOSE:


VERBOSE: The following MSBuild instances were found:
VERBOSE: @{msbuildExePath=C:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe; toolsetVersion=v140}
C:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe
v140
```

There is something strange, I do have both  "HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\VisualStudio\14.0" "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\VisualStudio\14.0" key, But it says Not Found.

**Comment by ras0219-msft** [comment]
Thanks for the logs!

>[DEBUG] _wspawnlpe(cmd.exe /c ""C:\Program Files (x86)\VC\vcvarsall.bat" x86  2>&1 && cmd")

It looks like, at some point in the past, VS2015 was installed directly into your program files directory. The installer set the `%VS140COMNTOOLS%` environment variable to point at `C:\Program Files (x86)\Common7\Tools` and you still have enough files available at that location to confuse us.

We currently pick up your VS2015 instance when building ports from the `%VS140COMNTOOLS%` variable, but we use findAnyMSBuildWithCppPlatformToolset when bootstrapping vcpkg itself, so that explains the difference you experienced there. You should be able to immediately fix the issue by setting it to be `C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\`:
```powershell
$env:VS140COMNTOOLS = "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\"
```
```cmd
set VS140COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\
```
I highly recommend editing your system environment variables to permanently change VS140COMNTOOLS to the above path since it looks like the current value is incomplete.

> There is something strange, I do have both "HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\VisualStudio\14.0" "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\VisualStudio\14.0" key, But it says Not Found.

The output is a bit misleading here; we're actually looking for the InstallDir property inside that registry key.

**Comment by navidR** [comment]
It works now. I think Microsoft should carefully redesign the whole "path" system it does have for its compiler.

What you said is completely true, I did have VS 2015 at some point.

I am closing this bug.
