### ISSUE TITLE
Add chromium base port

### ISSUE THREAD

**Issue by iHuahua** [microsoft/vcpkg#8850]
Please add port for `Chromium Base`, thank goodness. 
URL at:
```
https://chromium.googlesource.com/chromium/src/base/
```
It doesn't supported for cmake, i try to write a CMakeLists.txt for it, but always failed, SOS!

各位大大请支持一下Chrome Base库，我试过自己写cmake文件，可总是失败，那个gyp文件不好读，总是翻译失败，想把chromium base作为基础库，用cmake链接

**Comment by JackBoosY** [comment]
@iHuahua Any chrome library needs tool `depot-tools`, we need to add it first.
> 这段时间会尝试添加这个工具。

**Comment by Voskrese** [comment]
@JackBoosY 
why not add? almost all capacious **google** projects are tied to **GYP** or newer **GN**

**Comment by JackBoosY** [comment]
Related: #6184.

**Comment by Voskrese** [comment]
maybe for starters add `depot-tools`
and then everything else

**Comment by iHuahua** [comment]
@JackBoosY @Voskrese thank for reply. I'm waiting for u. If something i can do, please call me.

**Comment by JackBoosY** [comment]
@iHuahua In fact, I really need your help, please see [here](https://github.com/microsoft/vcpkg/issues/357#issuecomment-545828348).

**Comment by iHuahua** [comment]
> @iHuahua In fact, I really need your help, please see [here](https://github.com/microsoft/vcpkg/issues/357#issuecomment-545828348).

**Comment by iHuahua** [comment]
抱歉，手误关了，最近比较忙，没时间上来看消息，我找个时间尝试看看能不能解决这个问题

**Comment by mpsuzuki** [comment]
@JackBoosY 
Sorry for delayed participation to this discussion. Now I'm manually building Chromium for Windows by myself (since 3 days ago, clang + ninja), to learn how to do that, and my slow machine is still running.

If the escaping of the argument (--args='cc=... cxx=...') to "gn" is broken by CMake, my idea is "how about using a Python script to invoke gn?". I'm afraid that some experts might have tried such already, and if it's already tried and known to be "does not work", please let me know.

**Comment by mpsuzuki** [comment]
I have another question, how to retrieve the source code? If I'm understanding current situation correctly, Google no longer release the source code tarball, they instruct their special tools to download the source of Chromium and related libraries. In my case, it takes so long time (20 hours or so). Also, it's hard to keep the availability of the past sources.
In the case of Ubuntu and other GNU/Linux distributions, they keep the source tarball in their package distribution system to stabilize this issue. Should we do like that?

**Comment by JackBoosY** [comment]
@mpsuzuki In #8963, first we will download depot-tools, and download the basic source code, call the sync command to download the latest code, and use gn to build the port. However, I found that the entire chromium is built no matter which port is built, and it is not clear to me what went wrong, using cmake to pass in compilation options is also a challenge.

**Comment by iHuahua** [comment]
> @iHuahua In fact, I really need your help, please see [here](https://github.com/microsoft/vcpkg/issues/357#issuecomment-545828348).

亲，我自己改gn脚本把chromium base部分提取出来了，但是我不知道怎么接到cmake里

**Comment by iHuahua** [comment]
@JackBoosY sorry，这么久才来回复。我自己改脚本和依赖通过python把chromium base部分提取出来了，但是我不知道怎么接到vcpkg里，需要的话我可以我改的脚本共享给你。目前是通过删除deps/.gn等方式减少下载内容数据，已经调通了windows/MacOS/linux/android/iOS，脚本支持3个桌面平台，安卓和iOS是另外单写的两个脚本，只是发现里面还指定libcxx，这个需要重写cmake的时候注意，不知道是否是由于内存优化模块导致的强制依赖

**Comment by JackBoosY** [comment]
@iHuahua 你可以先提一个空的CONTROL和portfile.cmake，顺带把脚本传上去，我帮你修改。

**Comment by iHuahua** [comment]
> @iHuahua 你可以先提一个空的CONTROL和portfile.cmake，顺带把脚本传上去，我帮你修改。

好的，我试试

**Comment by iHuahua** [comment]
@JackBoosY https://github.com/microsoft/vcpkg/pull/12280
亲，有空看看怎么弄
