### ISSUE TITLE
Unable to install gsl

### ISSUE THREAD

**Issue by write2sahin** [microsoft/vcpkg#8855]
The gsl path is wrong. I can install other packages. Can you guys please take a look?

C:\vcpkg\vcpkg.exe install gsl
The following packages will be built and installed:
    gsl[core]:x86-windows
Starting package 1/1: gsl:x86-windows
Building package gsl[core]:x86-windows...
-- Downloading **ftp://ftp.gnu.org/gnu/gsl/gsl-2.4.tar.gz**...
-- Downloading ftp://ftp.gnu.org/gnu/gsl/gsl-2.4.tar.gz... Failed. Status: 7;"Couldn't connect to server"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:172 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  ports/gsl/portfile.cmake:5 (vcpkg_download_distfile)
  scripts/ports.cmake:71 (include)

Error: Building package gsl:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: gsl:x86-windows
  Vcpkg version: 2018.11.23-nohash

Additionally, attach any relevant sections from the log files above.

**Comment by ehsan-mohammadi** [comment]
@write2sahin I tested the GNU FTP site (ftp://ftp.gnu.org). I think it might be temporarily down and after a time this problem solved.

**Comment by JackBoosY** [comment]
@write2sahin Please download the source code package from other link and put it into _VCPKG_PATH/downloads_ then rebuild gsl.

Thanks.

**Comment by ehsan-mohammadi** [comment]
@write2sahin @JackBoosY Now, the GNU FTP site is up and seems the problem solved. I think this issue can be closed.

**Comment by write2sahin** [comment]
@ehsan-mohammadi . I still could not use gsl ftp site.
However I followed suggestion from @JackBoosY . I downloaded the gsl 2.4 from gnu http site and installed it with --no-downloads option. It worked.
Thank you both!!
