### ISSUE TITLE
VS2019 replaces dependecies dll's with dll's from vcpkg during build process

### ISSUE THREAD

**Issue by mightywill** [microsoft/vcpkg#8856]
I have vcpkg with zlib package installed 
My project uses custom zlib implementation and I put corresponding dll to the output folder of the project

But when I build the project, VS (or some of its components) replaces my zlib with the one from the vcpkg package despite the fact that the project does not have any references to any of vcpkg files.

Is it normal behavior?  If so then how and where to control that?

As temp workaround I've renamed vcpkg root directory to make it unavailable for any application/service

**Comment by PhoebeHui** [comment]
@mightywill, does this still be a question for you? you can set the 'using vcpkg' to No in your project property, it will not use any dlls from vcpkg.
