### ISSUE TITLE
boost build failure

### ISSUE THREAD

**Issue by TheVeryDarkness** [microsoft/vcpkg#8857]
I've downloaded a boostcpp.jam in D:/1853308/Documents/GitHub/vcpkg/vcpkg/downloads/, but this time it doesn't work. And thanks for you quick reply last time I reported a issue.

Starting package 1/130: boost-build:x64-windows
Building package boost-build[core]:x64-windows...
-- Using cached D:/1853308/Documents/GitHub/vcpkg/vcpkg/downloads/boostorg-build-boost-1.70.0.tar.gz
-- Using source at D:/1853308/Documents/GitHub/vcpkg/vcpkg/buildtrees/boost-build/src/ost-1.70.0-ad28c1be18
-- Using cached D:/1853308/Documents/GitHub/vcpkg/vcpkg/downloads/boost_LICENSE_1_0.txt
-- Downloading https://raw.githubusercontent.com/boostorg/boost/boost-1.70.0/boostcpp.jam...
-- Downloading https://raw.githubusercontent.com/boostorg/boost/boost-1.70.0/boostcpp.jam... Failed. Status: 7;"Couldn't connect to server"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:175 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  ports/boost-build/portfile.cmake:30 (vcpkg_download_distfile)
  scripts/ports.cmake:94 (include)

Error: Building package boost-build:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-build:x64-windows
  Vcpkg version: 2019.09.12-nohash

Additionally, attach any relevant sections from the log files above.

**Comment by JackBoosY** [comment]
@TheVeryDarkness Please download the source code package from other link and put it into _VCPKG_PATH/downloads_ then rebuild boost.

Thanks.

**Comment by TheVeryDarkness** [comment]
> @TheVeryDarkness Please download the source code package from other link and put it into VCPKG_PATH/downloads then rebuild boost.
> Thanks.

I've put it to "D:\1853308\Documents\GitHub\vcpkg\vcpkg\downloads" with a name "boostcpp.jam", but it doesn't work.

**Comment by ehsan-mohammadi** [comment]
@TheVeryDarkness After download `boostcpp.jam`, put it into `vcpkg\downloads` path and rename it to `boost-1.70.0-boostcpp.jam`. Then try to rebuild boost.

**Comment by TheVeryDarkness** [comment]
It works!Thanks for all of you!
