### ISSUE TITLE
io2d: Can't generate project using CMake

### ISSUE THREAD

**Issue by mmichal9** [microsoft/vcpkg#8865]
I am trying to use io2d with cmake however I cannot get it to correctly generate the solution
Any suggestions, what am I missing? 

**vcpkg version:**
2019.09.12-nohash

**io2d versions:** 
io2d:x64-windows 2019-07-11-1
io2d:x86-windows 2019-07-11-1

**CMakeLists.txt:**
cmake_minimum_required(VERSION 3.0)
project(hello CXX)
add_executable(hello hello.cpp)
find_package(io2d CONFIG REQUIRED)
target_link_libraries(hello PRIVATE io2d::io2d io2d::io2d_core io2d::io2d_cairo io2d::io2d_cairo_win32)

**Cmake Output after pressing Generate (Confgure works filne with no errors):**
Configuring done
CMake Warning (dev) at E:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:166 (_add_executable):
  Policy CMP0028 is not set: Double colon in target name means ALIAS or
  IMPORTED target.  Run "cmake --help-policy CMP0028" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  Target "hello" links to target "Cairo::Cairo" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:5 (add_executable)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at E:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:166 (_add_executable):
  Policy CMP0028 is not set: Double colon in target name means ALIAS or
  IMPORTED target.  Run "cmake --help-policy CMP0028" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  Target "hello" links to target "Cairo::Cairo" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:5 (add_executable)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at E:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:166 (_add_executable):
  Policy CMP0028 is not set: Double colon in target name means ALIAS or
  IMPORTED target.  Run "cmake --help-policy CMP0028" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  Target "hello" links to target "Cairo::Cairo" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:5 (add_executable)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at E:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:166 (_add_executable):
  Policy CMP0028 is not set: Double colon in target name means ALIAS or
  IMPORTED target.  Run "cmake --help-policy CMP0028" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  Target "hello" links to target "Cairo::Cairo" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:5 (add_executable)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at E:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:166 (_add_executable):
  Policy CMP0028 is not set: Double colon in target name means ALIAS or
  IMPORTED target.  Run "cmake --help-policy CMP0028" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  Target "hello" links to target "Cairo::Cairo" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:5 (add_executable)
This warning is for project developers.  Use -Wno-dev to suppress it.

Generating done

**Comment by LilyWangL** [comment]
Thanks for posting this issue. This issue has been fixed. So I am closing this issue for now.
