### ISSUE TITLE
libstk generates huge static lib

### ISSUE THREAD

**Issue by stekyne** [microsoft/vcpkg#8866]
**Describe the bug**
I noticed when linking libstk to my application that it seems to fail due to Runtime library mismatch (MD vs MT). Anyway, when I was investigating the VCPKG folder, I saw that the libstk.lib is much bigger than than any other lib in that directory (~45megs). This library shouldn't be as large as this surely? Is there some kind of packaging/build issue?

**Environment**
- OS: Windows 10
- Compiler: VS2019

**To Reproduce**
1. ./vcpkg install libstk:x64-windows-static
2. Check output directory for binaries. 

**Expected behavior**
The library is small and the binary shouldn't be as big as it is.

**Comment by JackBoosY** [comment]
In fact, libstk's `CMakeLists.txt` is written by a contributor, and its official build is to use `makefile`. In `CMakeLists.txt` we build all the source files into a library, we don't know if this is reasonable.

**Comment by stekyne** [comment]
It seems after linking with the STK static lib, the resulting binary isn't as inflated as expected and a lot of the contents must be discarded. The static STK lib in my case (in release) is 27 megs but the resulting binary is only 270kb. Can probably just ignore this issue I'd say. Thanks
