### ISSUE TITLE
VERSION.txt file

### ISSUE THREAD

**Issue by ehsan-mohammadi** [microsoft/vcpkg#8867]
The **2019.10** updates of vcpkg released. And in the `toolsrc/VERSION.txt` I saw this line:

https://github.com/microsoft/vcpkg/blob/08e74979df124d9360343751cefcae615c2ec5ed/toolsrc/VERSION.txt#L1

Is this different from update version? Can anyone describe me?

**Comment by vicroms** [comment]
We only update `toolsrc/VERSION.txt` when there are significant changes to the vcpkg tool itself (the C++ code), e.g.: new vcpkg commands or options. It is our way to tell users to bootstrap vcpkg again.

**Comment by ehsan-mohammadi** [comment]
@vicroms Many thanks for your comment and helping me!
