### ISSUE TITLE
MSVCP140.dll

### ISSUE THREAD

**Issue by TerensTare** [microsoft/vcpkg#8868]
**Describe the bug**
I have been using vcpkg with Visual Studio 2019 since august 2019 (i guess).
When I ran vcpkg yesterday, I saw this message:
![image](https://user-images.githubusercontent.com/37905314/68083512-90534000-fe29-11e9-87b0-03f9bc4cc842.png)

**Environment**
- OS: [e.g. Windows/Linux etc...] Windows
- Compiler: revision - Microsoft Visual Studio 16.3.7 - C++ build tools v142

**To Reproduce**
1. vcpkg
2. See error
Repro code when

**Expected behavior**
Run vcpkg normally

**Failure logs** 
-(please attached failure logs)

**Additional context**

**Comment by Voskrese** [comment]
call CMD env msvc 2019

where msvcp140.dll ?

**Comment by TerensTare** [comment]
It say that msvcp140.dll is in System32, I should probably check my path

**Comment by Voskrese** [comment]
Compiler has its own library, despite the name 140, 2019 uses its dll/msvcp140.dll

**Comment by Voskrese** [comment]
?
echo %PATH%

**Comment by TerensTare** [comment]
I fixed it.
Just called vsdevcmd.bat and worked.
Thanks for all.
