### ISSUE TITLE
Portaudio static build error

### ISSUE THREAD

**Issue by stekyne** [microsoft/vcpkg#8869]
**Describe the bug**
Attempting to use static/x64 portaudio fails with error:
```
CMake Error at G:/Programming/GitHub/vcpkg/installed/x64-windows-static/share/portaudio/portaudioTargets.cmake:72 (message):
  The imported target "portaudio" references the file

     "G:/Programming/GitHub/vcpkg/installed/x64-windows-static/debug/lib/portaudio_x64.lib"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "G:/Programming/GitHub/vcpkg/installed/x64-windows-static/share/portaudio/portaudioTargets.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  G:/Programming/GitHub/vcpkg/installed/x64-windows-static/share/portaudio/portaudioConfig.cmake:1 (include)
  G:/Programming/GitHub/vcpkg/scripts/buildsystems/vcpkg.cmake:263 (_find_package)
```
The library is called "portaudio.lib" on the system and not "portaudio_x64.lib". The port file for this package does rename the lib and dll to "portaudio" from "portaudio_x64". This looks like some kind of error with the package I guess?

**Environment**
- OS: Windows
- Compiler: VS2019 

**To Reproduce**
1. ./vcpkg install portaudio:x64-windows-static
2. Use package in a project using the cmake code provided by VCPKG

**Expected behavior**
Cmake should run without error and should build project successfully.

**Failure logs** 
As above.

**Additional context**

**Comment by NancyLi1013** [comment]
Hi @stekyne , thanks for posting this issue. I have submitted a PR to fix this issue. Could you help try to confirm whether it work for you?
