### ISSUE TITLE
[wt:x64-windows] build failure

### ISSUE THREAD

**Issue by Lewis123d** [microsoft/vcpkg#8875]
Environment:
- OS: Windows 7 SP1
- Compiler: VS2017

Reproduce
`./vcpkg install wt:wt-vc141-x64-windows`

wt-vc141-x64-windows.cmake
```
set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)
```
Failure logs
- [config-wt-vc141-x64-windows-out.log](https://pastebin.com/fVPtTV17)

**Comment by JackBoosY** [comment]
```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
SQLITE3_LIBRARY_DEBUG
    linked by target "wtdbosqlite3" in directory E:/git/vcpkg/buildtrees/wt/src/4.0.5-97cc9b1895/src/Wt/Dbo/backend
```
Could you edit _E:/git/vcpkg/buildtrees/wt/src/4.0.5-97cc9b1895/src/Wt/Dbo/backend/CMakeLists.txt_ line 8 to:
`FIND_PACKAGE( Sqlite3 CONFIG REQUIRED)`
then try to rebuild wt?

Thanks.

**Comment by Lewis123d** [comment]
It still occurs errors.
```
E:\git\vcpkg>vcpkg.exe install wt:wt-vc141-x64-windows > log.txt
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: E:/git/vcpkg/downloads/tools/cmake-3.14.0-windows/cmake-3.14.0-win32-x86/bin/cmake.exe --build . --config Debug --target install -- -v
    Working Directory: E:/git/vcpkg/buildtrees/wt/wt-vc141-x64-windows-dbg
    See logs for more information:
      E:\git\vcpkg\buildtrees\wt\install-wt-vc141-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:96 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/wt/portfile.cmake:50 (vcpkg_install_cmake)
  scripts/ports.cmake:94 (include)
```
Failure logs:
- [log.txt](https://pastebin.com/mgZkFgbh)
- [install-wt-vc141-x64-windows-dbg-out.log](https://www.codepile.net/pile/RNe65pLj)

Thanks.

**Comment by JackBoosY** [comment]
@Lewis123d Could you provide the log _E:/git/vcpkg/buildtrees/wt/config-wt-vc141-x64-windows-out.log_ ?

Thanks.

**Comment by Lewis123d** [comment]
Sure. Please go to following link and see details.
- [config-wt-vc141-x64-windows-out.log](https://www.codepile.net/pile/wLJ3w5Ab)
Thanks.

**Comment by JackBoosY** [comment]
In your provided logs:
```
** Enabling advanced font support using DirectWrite
** Wt::Dbo: building SQLite3 backend.
```
Here is my log:
```
** Enabling advanced font support using DirectWrite
-- Found Sqlite3 header file in F:/vcpkg/installed/wt-vc141-x64-windows/include
-- Found Sqlite3 libraries: optimized;F:/vcpkg/installed/wt-vc141-x64-windows/lib/sqlite3.lib;debug;F:/vcpkg/installed/wt-vc141-x64-windows/lib/sqlite3.lib
** Wt::Dbo: building SQLite3 backend.
```

I think the sqlite3 was not found. Please make sure _VCPKG_PATH/installed/wt-vc141-x64-windows/lib/sqlite3.lib_ and _VCPKG_PATH/installed/wt-vc141-x64-windows/lib/sqlite3.lib_ are exist, or remove sqlite3, then rebuild wt.

Thanks.

**Comment by Lewis123d** [comment]
It was my mistake. I forgot I have already renamed sqlite3.lib.
So I remove it and rebuild wt. Finally, it succeeds.
Thanks for your help. :)
