### ISSUE TITLE
[boost-build:x86-windows] build failure

### ISSUE THREAD

**Issue by lzm-cn** [microsoft/vcpkg#8876]
**Host Environment**
- OS: [Windows]
- Compiler: revision

**To Reproduce**
`./vcpkg install boost`

**Failure logs** 
Downloading https://raw.githubusercontent.com/boostorg/boost/boost-1.70.0/boostcpp.jam... Failed. Status: 7;"Couldn't connect to server"

**Additional context**
The url "[](https://raw.githubusercontent.com/boostorg/boost/boost-1.70.0/boostcpp.jam... )" is invalid.

**Comment by Voskrese** [comment]
update cmake  3.15.+
https://gitlab.kitware.com/cmake/cmake/merge_requests/3763

**Comment by lzm-cn** [comment]
> update cmake 3.15.+
> https://gitlab.kitware.com/cmake/cmake/merge_requests/3763

thanks!! it works.
