### ISSUE TITLE
[zeromq]How do I specify preprocessors to enable optional features of a package?

### ISSUE THREAD

**Issue by kakyoism** [microsoft/vcpkg#8879]
Some libs have conditional builds that enable optional features. I haven't found a way to specify such `#define` preprocessors while installing vcpkg packages. My current lib of interest is `cppzmq` where `ZMQ_BUILD_DRAFT_API` is required for enabling certain API implementations. 

I checked vcpkg command line switches and found no related options. 
Does this mean that I must compile from source to enable those?

Please help. Thanks.

**Comment by kakyoism** [comment]
**progress:** 

I now found that ZMQ_BUILD_DRAFT_API didn't take effect for my libzmq dependency build, which is weird, because I've included it in the `portfile.cmake` file of zeromq package like this

```cmake
vcpkg_configure_cmake(
    SOURCE_PATH ${SOURCE_PATH}
    PREFER_NINJA
    OPTIONS
        -DZMQ_BUILD_TESTS=OFF
        -DPOLLER=select
        -DZMQ_BUILD_DRAFT_API=ON
        -DBUILD_STATIC=${BUILD_STATIC}
        -DBUILD_SHARED=${BUILD_SHARED}
        -DWITH_PERF_TOOL=OFF
        -DWITH_DOCS=OFF
        -DWITH_NSS=OFF        
        ${FEATURE_OPTIONS}
    OPTIONS_DEBUG
        "-DCMAKE_PDB_OUTPUT_DIRECTORY=${CURRENT_BUILDTREES_DIR}/${TARGET_TRIPLET}-dbg"
)
```

**Comment by JackBoosY** [comment]
For common situation:
We need to find the macro in the source `CMakeLists.txt` and `*.cmake` to find the option, then set it to an option of `vcpkg_configure_cmake` using `-D${OPTION_NAME}=ON`.
For special situation:
We need to make a patch to fix the source `CMakeListst.txt` and `*.cmake` and pass the parameters into `vcpkg_configure_cmake`.

For this issue:
I found the macro `ZMQ_BUILD_DRAFT_API` defined when `ENABLE_DRAFTS` is ON[1], so you can add `-DENABLE_DRAFTS=ON` to `portfile.cmake` line 33 to enable it.

[1]. _SOURCE_PATH/CMakeLists.txt_ line 174.
