### ISSUE TITLE
How to integrate multiple customized packages in CMakeLists.txt for a VC++ project?

### ISSUE THREAD

**Issue by Lewis123d** [microsoft/vcpkg#8886]
OS:Windows 7 SP1
Compiler: VS2017
CMake Version: 3.12.1

1. I add two cmake files, sqlite3-vc141-x64-windows.cmake and  boost-vc141-x64-windows.cmake in triplets directory.
```
set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)
set(VCPKG_PLATFORM_TOOLSET v141)
```
```
set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)
set(VCPKG_PLATFORM_TOOLSET v141)
```
2. I execute following two commands, and vcpkg generates sqlite3 and boost libraries successfully.
`./vcpkg install sqlite3:sqlite3-vc141-x64-windows.cmake`
`./vcpkg install boost:boost-vc141-x64-windows.cmake`

3.
How to modify this CMakeList in my test_vcpkg project to integrate these two libraries, and let main function work fine?
```
cmake_minimum_required(VERSION 3.0)
SET(CMAKE_TOOLCHAIN_FILE "$ENV{VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake")
project(test_vcpkg)

find_package(sqlite3 REQUIRED)
find_package(Boost REQUIRED)
add_executable(main main.cpp)
```
```
// main.cpp
#include <stdio.h>
#include <sqlite3.h>
#include <boost/lexical_cast.hpp>

int main()
{
    printf("test sqlite3:%s\n", sqlite3_libversion());
    printf("test boost:%s\n", boost::lexical_cast<std::string>(123).c_str());
	
    return 0;
}
```

Thanks.

**Comment by vicroms** [comment]
Hi @Lewis123d 

You need to set the `VCPKG_TARGET_TRIPLET`, you can do it by either:

1) setting it in your CMakeLists.txt
```
set(VCPKG_TARGET_TRIPLET sqlite3-vc141-x64-windows)
```

2) by passing the value in the command line
```
cmake .. 
  -DCMAKE_TOOLCHAIN_FILE=<path_to_vcpkg>/scripts/buildsystems/vcpkg.cmake
  -DVCPKG_TARGET_TRIPLET=sqlite3-vc141-x64-windows
```

**Comment by Lewis123d** [comment]
Hi @vicroms 
I need to use two different libraries simultaneously(sqlite3 and boost).
Can VCPKG_TARGET_TRIPLET set two variables?

**Comment by Neumann-A** [comment]
@Lewis123d 
`VCPKG_TARGET_TRIPLET` can only be set to one value and I fail to see why you require two different triplets.

**Comment by Lewis123d** [comment]
> OS:Windows 7 SP1
> Compiler: VS2017
> CMake Version: 3.12.1
> 
> 1. I add two cmake files, sqlite3-vc141-x64-windows.cmake and  boost-vc141-x64-windows.cmake in triplets directory.
> 
> ```
> set(VCPKG_TARGET_ARCHITECTURE x64)
> set(VCPKG_CRT_LINKAGE dynamic)
> set(VCPKG_LIBRARY_LINKAGE dynamic)
> set(VCPKG_PLATFORM_TOOLSET v141)
> ```
> 
> ```
> set(VCPKG_TARGET_ARCHITECTURE x64)
> set(VCPKG_CRT_LINKAGE dynamic)
> set(VCPKG_LIBRARY_LINKAGE dynamic)
> set(VCPKG_PLATFORM_TOOLSET v141)
> ```
> 
> 1. I execute following two commands, and vcpkg generates sqlite3 and boost libraries successfully.
>    `./vcpkg install sqlite3:sqlite3-vc141-x64-windows.cmake`
>    `./vcpkg install boost:boost-vc141-x64-windows.cmake`
> 
> How to modify this CMakeList in my test_vcpkg project to integrate these two libraries, and let main function work fine?
> 
> ```
> cmake_minimum_required(VERSION 3.0)
> SET(CMAKE_TOOLCHAIN_FILE "$ENV{VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake")
> project(test_vcpkg)
> 
> find_package(sqlite3 REQUIRED)
> find_package(Boost REQUIRED)
> add_executable(main main.cpp)
> ```
> 
> ```
> // main.cpp
> #include <stdio.h>
> #include <sqlite3.h>
> #include <boost/lexical_cast.hpp>
> 
> int main()
> {
>     printf("test sqlite3:%s\n", sqlite3_libversion());
>     printf("test boost:%s\n", boost::lexical_cast<std::string>(123).c_str());
> 	
>     return 0;
> }
> ```
> 
> Thanks.

Hi @Neumann-A 
Please see the above quote.
I need to integrate more one library in my project.
I have no idea to write CMakeLists in my project and vcpkg can assign lib/include path automatically. 

Thanks.

**Comment by Neumann-A** [comment]
Then you use one triplet and install both libraries using that triplet. There is no need to separate them into two differently named triplets (with exactly the same code.....)
If you need a port depending customization's use something like:
```
if(PORT MATCHES "hdf5|clapack|boost|fftw|gsl|xerces-c|szip|zlib|zstd|openblas|bzip2|lodepng|qcustomplot")
    set(VCPKG_LIBRARY_LINKAGE static)
endif()
```
in your triplet.

**Comment by vicroms** [comment]
@Lewis123d 

As @Neumann-A explained you don't need to create a triplet file for each library, you just need to create a single one, e.g.:

Create a `vc141-x64-windows.cmake` file with the following contents:

```
set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)
set(VCPKG_PLATFORM_TOOLSET v141)
```

Then you would use the same triplet to build all the libraries you need:

` ./vcpkg install boost sqlite3 --triplet vc141-x64-windows`

If you do it right the libraries will be installed in `<vcpkg_root>/installed/vc141-x64-windows/` and you can use `VCPKG_TARGET_TRIPLET=vc141-x64-windows` to use all libraries build with that triplet.

**Comment by Lewis123d** [comment]
Thanks for your suggestion.
I'll follow the discussion and modify corresponding files.

**Comment by PhoebeHui** [comment]
@Lewis123d, please reopen this if it still be an problem for you.
