### ISSUE TITLE
boost compiled *.libs have incorrect toolset version and missing boost version

### ISSUE THREAD

**Issue by timautry** [microsoft/vcpkg#8897]
**Describe the bug**
The boost compiled *.lib files found in the x64-windows/installed/lib, x64-windows/installed/debug/lib and corresponding packages folders have the incorrect vc toolset version (all have v140) and are missing the boost version (current is 1.71) although the x64-windows/bin, x64-windows/installed/debug/bin and corresponding packages folders *.pdb and *.dll files have the correct toolset (v141 or v142) and boost version.

Reviewing the corresponding build folders for each the build and stage files all have the correct toolset and boost version.

It seems somewhere in the copy process from the build folder to the installed and packages folder the *.lib files all get the toolset changed to v140 even though they have been compiled with v141 in VS 2017 and v142 in VC 2019.

**Environment**
- OS: Windows 10 Pro 1903 (OS Build 18362.449) x64
- Compiler: VC 2017 v15.9.17 Toolset v141 and VC 2019 16.3.7 Toolset v142

**To Reproduce**
1. ./vcpkg install boost-atomic (or any boost library that creates a dll)
2. No errors - compiles cleanly
Repro code when

**Expected behavior**
The lib files should be copied from the build folder to the installed and packages folders with their filenames intact and not altered. 

**Failure logs** 
No failure logs during the vcpkg install process, but the lib files have the incorrect filenames no longer matching their counterpart in the bin folders.

**Additional context**
From the build folder for boost-atomic:
 Directory of D:\Git\vs2017\buildtrees\boost-atomic\x64-windows-dbg\boost\build\3b5884c1d1f69371a4c182d85379c63c

11/04/2019  17:00    <DIR>                       BUILTIN\Administrators .
11/04/2019  17:00    <DIR>                       BUILTIN\Administrators ..
11/04/2019  17:00            16,384              BUILTIN\Administrators boost_atomic-vc141-mt-gd-x64-1_71.dll
11/04/2019  17:00               381              BUILTIN\Administrators boost_atomic-vc141-mt-gd-x64-1_71.dll.manifest
11/04/2019  17:00               119              BUILTIN\Administrators boost_atomic-vc141-mt-gd-x64-1_71.dll.rsp
11/04/2019  17:00             1,703              BUILTIN\Administrators boost_atomic-vc141-mt-gd-x64-1_71.exp
11/04/2019  17:00             3,576              BUILTIN\Administrators boost_atomic-vc141-mt-gd-x64-1_71.lib
11/04/2019  17:00           348,160              BUILTIN\Administrators boost_atomic-vc141-mt-gd-x64-1_71.pdb

From installed bin for boost-atomic:
 Directory of D:\Git\vs2017\installed\x64-windows\bin

11/04/2019  17:00             9,728              BUILTIN\Administrators boost_atomic-vc141-mt-x64-1_71.dll
11/04/2019  17:00           307,200              BUILTIN\Administrators boost_atomic-vc141-mt-x64-1_71.pdb

From install lib for boost-atomic:
 Directory of D:\Git\vs2017\installed\x64-windows\lib

11/04/2019  17:00             3,530              BUILTIN\Administrators boost_atomic-vc140-mt.lib

The same is true for the debug versions and the corresponding packages folders.

**Comment by timautry** [comment]
I created a fresh/clean vcpkg, clone from website, bootstrap with -win64 option, and then 'vcpkg install libzip' with the same result.

"GIT" did upgrade itself to v2.24.0-64-bit earlier today.

Here is all the console output - nothing was installed at the time.

SYSTEM@ANDROMEDA 11/04/2019 21:11:42 D:\Git\vs2017
->vcpkg install libzip
The following packages will be built and installed:
  * bzip2[core]:x64-windows
    libzip[bzip2,core,openssl]:x64-windows
  * openssl[core]:x64-windows
  * openssl-windows[core]:x64-windows
  * zlib[core]:x64-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/5: zlib:x64-windows
Building package zlib[core]:x64-windows...
-- Using cached E:/Git/vcpkg.downloads/zlib1211.tar.gz
-- Extracting source E:/Git/vcpkg.downloads/zlib1211.tar.gz
-- Applying patch cmake_dont_build_more_than_needed.patch
-- Using source at D:/Git/vs2017/buildtrees/zlib/src/1.2.11-f690224aeb
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Installing: D:/Git/vs2017/packages/zlib_x64-windows/share/zlib/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package zlib[core]:x64-windows... done
Installing package zlib[core]:x64-windows...
Installing package zlib[core]:x64-windows... done
Elapsed time for package zlib:x64-windows: 12.33 s
Starting package 2/5: openssl-windows:x64-windows
Building package openssl-windows[core]:x64-windows...
-- Using cached E:/Git/vcpkg.downloads/openssl-1.0.2s.tar.gz
-- Extracting source E:/Git/vcpkg.downloads/openssl-1.0.2s.tar.gz
-- Applying patch ConfigureIncludeQuotesFix.patch
-- Applying patch STRINGIFYPatch.patch
-- Applying patch EnableWinARM32.patch
-- Applying patch EmbedSymbolsInStaticLibsZ7.patch
-- Applying patch EnableWinARM64.patch
-- Using source at D:/Git/vs2017/buildtrees/openssl-windows/src/openssl-1-c41872ef97
-- Copying openssl release source files...
-- Copying openssl release source files... done
-- Configure x64-windows-rel
-- Configure x64-windows-rel done
-- Build x64-windows-rel
-- Build x64-windows-rel done
-- Copying openssl debug source files...
-- Copying openssl debug source files... done
-- Configure x64-windows-dbg
-- Configure x64-windows-dbg done
-- Build x64-windows-dbg
-- Build x64-windows-dbg done
-- Installing: D:/Git/vs2017/packages/openssl-windows_x64-windows/share/openssl-windows/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package openssl-windows[core]:x64-windows... done
Installing package openssl-windows[core]:x64-windows...
Installing package openssl-windows[core]:x64-windows... done
Elapsed time for package openssl-windows:x64-windows: 5.885 min
Starting package 3/5: openssl:x64-windows
Building package openssl[core]:x64-windows...
-- Installing: D:/Git/vs2017/packages/openssl_x64-windows/share/openssl//usage
-- Performing post-build validation
-- Performing post-build validation done
Building package openssl[core]:x64-windows... done
Installing package openssl[core]:x64-windows...
Installing package openssl[core]:x64-windows... done
Elapsed time for package openssl:x64-windows: 31.55 s
Starting package 4/5: bzip2:x64-windows
Building package bzip2[core]:x64-windows...
-- Using cached E:/Git/vcpkg.downloads/bzip2-1.0.6.tar.gz
-- Extracting source E:/Git/vcpkg.downloads/bzip2-1.0.6.tar.gz
-- Applying patch fix-import-export-macros.patch
-- Using source at D:/Git/vs2017/buildtrees/bzip2/src/1.0.6-8d81d2ad2b
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Performing post-build validation
-- Performing post-build validation done
Building package bzip2[core]:x64-windows... done
Installing package bzip2[core]:x64-windows...
Installing package bzip2[core]:x64-windows... done
Elapsed time for package bzip2:x64-windows: 20.31 s
Starting package 5/5: libzip:x64-windows
Building package libzip[bzip2,core,openssl]:x64-windows...
-- Using cached E:/Git/vcpkg.downloads/nih-at-libzip-rel-1-5-2.tar.gz
-- Extracting source E:/Git/vcpkg.downloads/nih-at-libzip-rel-1-5-2.tar.gz
-- Applying patch avoid_computation_on_void_pointer.patch
CMake Error at scripts/cmake/vcpkg_apply_patches.cmake:52 (message):
  Applying patch failed.  Patch needs to be updated to work with source being
  used by vcpkg!
Call Stack (most recent call first):
  scripts/cmake/vcpkg_extract_source_archive_ex.cmake:134 (vcpkg_apply_patches)
  scripts/cmake/vcpkg_from_github.cmake:114 (vcpkg_extract_source_archive_ex)
  ports/libzip/portfile.cmake:2 (vcpkg_from_github)
  scripts/ports.cmake:94 (include)


Error: Building package libzip:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libzip:x64-windows
  Vcpkg version: 2019.09.12-nohash

Additionally, attach any relevant sections from the log files above.

**Comment by timautry** [comment]
@JackBoosY @ras0219  - FYI - I think I found where this happens, but not sure why it happens - in the boost-modular-build.cmake file, starting at line 346 thru 369, there is manipulation of the boost library filenames. 
Since I'm far from being an expert, I wouldn't begin to rationalize why only the filename libs and not the  symbol and link libraries are not?
Thanks and have a wonderful day/evening.

**Comment by PhoebeHui** [comment]
@timautry , see the [background ](https://github.com/microsoft/vcpkg/issues/601#issuecomment-276220946) why the lib rename to '-vc140'.

**Comment by timautry** [comment]
Ok, thanks for the information, but I'm not sure they are all the same, as even MS says there are differences in how the code is interpreted and handled between VC versions and toolsets for the building, compiling and linking. 
I myself have compared output files from stand-alone builds of boost libraries, specifying VS2015, VS2017 and VS2019 and their respective toolsets vc140, vc141 and vc142 and there is obvious file differences in the dlls, libs and pdbs.
I may just maintain those either outside of vcpkg or in a custom triplet of my own.
Thank you for the hard work :)
