### ISSUE TITLE
clblas build failure - Mismatching number of debug and release binaries

### ISSUE THREAD

**Issue by timautry** [microsoft/vcpkg#8898]
**Host Environment**
- OS: Windows 10 Pro 1903 (OS Build 18362.449) x64
- Compiler: Compiler: VC 2017 v15.9.17 Toolset v141 and VC 2019 16.3.7 Toolset v142

**To Reproduce**
`./vcpkg install clblas`

**Failure logs** 
-Cut and past the appropriate build messages from the console output.
Starting package 2/2: clblas:x64-windows
Building package clblas[core]:x64-windows...
-- Using cached E:/Git/vcpkg.downloads/clMathLibraries-clBLAS-v2.12.tar.gz
-- Extracting source E:/Git/vcpkg.downloads/clMathLibraries-clBLAS-v2.12.tar.gz
-- Applying patch cmake.patch
-- Using source at D:/Git/vs2017/buildtrees/clblas/src/v2.12-4e832e5dde
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Warning: Could not find a matching pdb file for:
    D:/Git/vs2017/packages/clblas_x64-windows/debug/bin/vcruntime140_1d.dll

-- Installing: D:/Git/vs2017/packages/clblas_x64-windows/share/clblas/copyright
-- Performing post-build validation
Mismatching number of debug and release binaries. Found 2 for debug but 1 for release.
Debug binaries

    D:/Git/vs2017/packages/clblas_x64-windows/debug/bin/clBLAS.dll
    D:/Git/vs2017/packages/clblas_x64-windows/debug/bin/vcruntime140_1d.dll

Release binaries

    D:/Git/vs2017/packages/clblas_x64-windows/bin/clBLAS.dll

Found 1 error(s). Please correct the portfile:
    D:\Git\vs2017\ports\clblas\portfile.cmake
-- Performing post-build validation done
Error: Building package clblas:x64-windows failed with: POST_BUILD_CHECKS_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: clblas:x64-windows
  Vcpkg version: 2019.09.12-nohash

-Additionally, attach any relevant sections from the log files above.
[portfile.cmake.txt](https://github.com/microsoft/vcpkg/files/3806679/portfile.cmake.txt)
(portfile.cmake for clblas added .txt extension to allow upload)

-Please attach any additional failure logs mentioned in the console output.
[install-x64-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/3806674/install-x64-windows-rel-out.log)
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/3806675/install-x64-windows-dbg-out.log)

**Additional context**
installing as x64-windows with booststrap run with -win64 option.

**Comment by JackBoosY** [comment]
From the log:
```
-- Installing: D:/Git/vs2017/packages/clblas_x64-windows/debug/bin/msvcp140d.dll
-- Installing: D:/Git/vs2017/packages/clblas_x64-windows/debug/bin/vcruntime140_1d.dll
-- Installing: D:/Git/vs2017/packages/clblas_x64-windows/debug/bin/vcruntime140d.dll
-- Installing: D:/Git/vs2017/packages/clblas_x64-windows/debug/bin/concrt140d.dll
```
These 4 dlls should not be installed.

**Comment by timautry** [comment]
They do not exist in the build/clblas/x64-windows-(dbg/rel)/ staging folders, so I don't know where they may be coming from?
The vcruntime140_1d.dll exists in the packages/clblas_x64-windows/debug/bin folder, but I don't know where it is copying it from or why it would be there at all, as I'm building with VS2017/VS2019 which should be v141/v142 vc runtimes?

Note: this is a fresh install (clone of vcpkg from website), bootstrap with -win64 option, then downloading and rebuilding  all packages from scratch.

**Comment by JackBoosY** [comment]
@timautry Yes, I think it's a bug, and we will fix it later.

**Comment by LilyWangL** [comment]
Thanks for posting this issue. This issue has been fixed, so I am closing this issue for now.
