### ISSUE TITLE
New Hash command

### ISSUE THREAD

**Issue by peters** [Microsoft/vcpkg#89]
Instead of using Powershell in order to obtain a SHA512 hash for a given file, it would be nice if `vcpkg` provided a built-in command. Ref: https://github.com/Microsoft/vcpkg/issues/61#issuecomment-249750985

`vcpkg hash filename`

**Comment by alexkaratarakis** [comment]
`vcpkg hash` command is now available.

**Comment by peters** [comment]
👍
