### ISSUE TITLE
OpenSSL library with static CRT linkage

### ISSUE THREAD

**Issue by jozefizso** [Microsoft/vcpkg#890]
I want to build OpenSSL dynamic libraries with CRT statically linked.

My triplet:
```
set(VCPKG_TARGET_ARCHITECTURE x86)
set(VCPKG_CRT_LINKAGE static)
set(VCPKG_LIBRARY_LINKAGE dynamic)
```

The libeay32.dll and ssleay32.dll are still compiled with dynamic runtime tough.

**Comment by ras0219-msft** [comment]
This is unfortunately really hard to fix because of OpenSSL's custom perl-based build. The best option is probably to build the static/static version, then generate a `.def` file from the symbols list and create a DLL that way.

Could you provide a bit more information about your scenario where DLLs with statically-linked CRTs makes sense?

**Comment by jozefizso** [comment]
We distribute debug version of the application internally to other dev and QA team members. It's easier to have Debug CRT statically linked as the application would not run otherwise.

For production releases it's easier and more maintainable to link CRT statically.

**Comment by KindDragon** [comment]
You can distribute locally Debug CRT dll's with app

**Comment by KindDragon** [comment]
> I want to build OpenSSL dynamic libraries with CRT statically linked.

You can patch `Configurations\10-main.conf` for that
```
    "VC-noCE-common" => {
        inherit_from     => [ "VC-common" ],
        template         => 1,
        cflags           => add(picker(default => "-DUNICODE -D_UNICODE",
                                       debug   =>
                                       sub {
                                           ($disabled{shared} ? "" : "/MDd")
                                               ." /Od -DDEBUG -D_DEBUG";
                                       },
                                       release =>
                                       sub {
                                           ($disabled{shared} ? "" : "/MD")
                                               ." /O2";
                                       })),
```

**Comment by JackBoosY** [comment]
Hi @jozefizso , thanks for reporting this issue!
Please open a new issue if this is still a problem for you.
Thx.
