### ISSUE TITLE
How to use installed libraries with CMake  in ubutun 18.04?

### ISSUE THREAD

**Issue by Aaricis** [microsoft/vcpkg#8900]
I try to install libraries with cmake by adding cmake command line `cmake -DCMAKE_TOOLCHAIN_FILE='/home/zkg/vcpkg/scripts/buildsystems/vcpkg.cmake'`, but it failed. I donot know how to fix it!

![2019-11-05 11-24-38 的屏幕截图](https://user-images.githubusercontent.com/35218694/68176233-ee655c00-ffbe-11e9-9719-e64cc4fa13c8.png)

**Comment by vicroms** [comment]
Hi @Aaricis 

It looks like your command line is missing the project's source directory (the path where your project and its CMakeLists.txt is located). 

You usually call CMake from a `build` sub-directory inside of your project's directory, e.g.:

Given this folder structure:
```
my_project/
    source.cpp
    CMakeLists.txt
```

you would run the following commands:

```
mkdir build
cd build
cmake .. -DCMAKE_TOOLCHAIN_FILE=<path_to_vcpkg>/scripts/buildsystems/vcpkg.cmake
cmake --build .
```

**Comment by Aaricis** [comment]
Thanks for your reply！
Should I write the `CMakeLists.txt`for `DCMAKE_TOOLCHAIN_FILE=<path_to_vcpkg>/scripts/buildsystems/vcpkg.cmake`first and then execute `cmake .. -DCMAKE_TOOLCHAIN_FILE=<path_to_vcpkg>/scripts/buildsystems/vcpkg.cmake`?

I am not farmilar with `CMakeLists.txt`. I do not know how to write this file.

**Comment by JackBoosY** [comment]
@Aaricis Here is a template:
```
#Set the required cmake version
cmake_minimum_required(VERSION 3.5)

#Set the current library name
project(PROJ_NAME (C或CXX))

#(optional) add some options
options(PROJ_EXAMPLE_OPT OFF)

#Set the header file list of the current library
set(PROJ_HDRS
"include\...")
#Or use the glob command to generate a list
file(GLOB_RECURSE PROJ_HDRS "${CMAKE_CURRENT_SOURCE_DIR}\include")

#Set the source file to be compiled
set(PROJ_SRCS
"source\")
#Or use the glob command to generate a list
file(GLOB_RECURSE PROJ_SRCS "${CMAKE_CURRENT_SOURCE_DIR}\source")

#Declare the creation of the library
add_library(${PROJECT} ${PROJ_SRCS})

#(Optional) Set the path to the included header file
target_include_directories(${PROJECT} PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}\include")
#Or use the following command to add a global header file path
include_directories("${CMAKE_CURRENT_SOURCE_DIR}\include")

#(optional) add some preprocessing commands
if (BUILD_SHARED_LIBS)
    target_compile_definitions(${PROJECT} PRIVATE -DPROJECT_EXPOTS -D...)
else()
    target_compile_definitions(${PROJECT} PRIVATE -DPROJECT_STATIC -D...)
endif()
#Or use the following command to add a global preprocessing command
add_definitions(-DXXX)

#(Optional) Add some different compilation options depending on the system
if (WIN32)
    target_compile_options(${PROJECT} PRIVATE /W4)
elseif (UNIX)
    target_compile_options(${PROJECT} PRIVATE -std=c++17)
elseif (APPLE)
    target_compile_options(${PROJECT} PRIVATE -otherOsxOpts)
endif()

#(optional) look up the port if there is a dependency port
find_package(DEPEND_PORT_NAME CONFIG REQUIRED)
#Or use the following command to find it manually
find_library(DEPEND_PORT_NAME NAMES PORT_NAME REQUIRED)

#(Optional) Add a library name that requires a link
target_include_directories(${PROJECT} PRIVATE DEPEND_PORT_LIBRARY)

#(Optional) Configure to generate config.cmake
configure_file("cmake\project_config.cmake.in" "project_config.cmake")

#(Optional) Generate different cmake configurations for debug/release
export(TARGETS project_config DESTINATION share\${PROJECT})

#Install headers
install(FILES ${PROJ_HDRS} DESTINATION include)

#Install library files and other executable files
install(TARGETS ${PROJECT}
  RUNTIME DESTINATION bin
  LIBRARY DESTINATION lib
  ARCHIVE DESTINATION lib
)

```

**Comment by vicroms** [comment]
@Aaricis 

Sorry about that, I'm not sure I'm understanding your problem correctly.

Are you having problems to install libraries using vcpkg? Or integrating the libraries installed via vcpkg in your project?

1) To install libraries with vcpkg:

```
cd <path_to_vpckg>
./vcpkg install <library>    # e.g.: ./vcpkg install sqlite3 
```

2) To use libraries installed via vcpkg when building your CMake project:

```
cd <your_project_folder>    # Should contain a CMakeLists.txt to build your project
mkdir build
cd build
cmake .. -DCMAKE_TOOLCHAIN_FILE=<path_to_vcpkg>/scripts/buildsystems/vcpkg.cmake
cmake --build .
 ```

Inside CMakeLists.txt you would use the standard CMake machinery to load dependencies, see:

[`find_package`](https://cmake.org/cmake/help/v3.15/command/find_package.html?highlight=find_package): **Recommended** for libraries that offer CMake integration (Config files or Find modules)

If a library doesn't offer CMake integration you would need to use [`find_library`](https://cmake.org/cmake/help/v3.15/command/find_library.html) and [`find_path`](https://cmake.org/cmake/help/v3.15/command/find_path.html?highlight=find_path) to link the libraries and add the include paths manually.

Example CMakeLists.txt

```
project(my_project)

# Project depends on ZLIB, it will be found if installed with vcpkg
find_package(ZLIB REQUIRED)

add_executable(my_project my_source.cpp)
target_link_libraries(my_project PRIVATE ZLIB::ZLIB)
```

**Comment by JackBoosY** [comment]
Hi @Aaricis, does this issue still bother you?

**Comment by JackBoosY** [comment]
If this issue is still not resolved, please reopen it.
