### ISSUE TITLE
SDL2 build doesn't support Vulkan

### ISSUE THREAD

**Issue by manhnt9** [microsoft/vcpkg#8905]
**Describe the bug**
SDL2 installed by vcpkg doesn't support Vulkan, our build with msvc and vcpkg can not run.

**Environment**
- OS: Windows 10
- Compiler:

**To Reproduce**
1. ./vcpkg install sdl2 --triplet x64-windows
2. Build project [Saga3D](https://gitlab.com/InnerPieceOSS/Saga3D/) master branch (Windows instructions included in repo)
3. Run the application samples

**Expected behavior**
The app runs and has the look like one of these [screenshots](https://gitlab.com/InnerPieceOSS/Saga3D/tree/master/samples).

**Failure logs** 
Crash logs
```
Saga3D\build\install\bin> .\03_mesh.exe
DEBUG: SDL initialized
INFO: Basic systems initialized
DEBUG: SDL version 2.0.10
DEBUG: Vulkan support is either not configured in SDL or not available in current SDL video driver (windows) or platform
INFO: Graphics device: GeForce GTX 670
DEBUG: Invalid window
DEBUG: Invalid window
ERROR: Platform surface creation failed
CRITICAL: Failed to initialize Vulkan driver
```

**Additional context**
MSYS2's SDL2 version builds and runs fine, you may want to take a look at its source code or patches.

**Comment by manhnt9** [comment]
Duplicate of: https://github.com/Microsoft/vcpkg/issues/3435

Will try if we can get it run.

**Comment by timautry** [comment]
I see the command line used was:
./vcpkg install sdl2 --triplet x64-windows

Have you tried?
./vcpkg install sdl2[vulkan] --triplet x64-windows

I'm sure the things shown in brackets would be additional optional functionality to the core package.

I believe there are several ways to install optional functionality:
1 ./vcpkg install sdl2[*] --triplet x64-windows
2 ./vcpkg install sdl2[all] --triplet x64-windows
3 ./vcpkg install sdl2[core,vulkan] --triplet x64-windows
4 ./vcpkg install sdl2[vulkan] --triplet x64-windows
5 /.vcpkg install sdl2 --triplet x64-windows

Options 1 and 2 do the same thing, installs the core functionality and any additional optional functionality the port has.

Options 3, and 4 will install the core functionality and only the additional vulkan functionality the port has.

Option 5 will install only the core functionality of the port.

There are times where you may not want to use '*' or 'all' as some of the additional optional functionality may be mutually exclusive to each other, as in 'samples' or 'tools' can be installed but not both 'samples' and 'tools', or the functionality is not ported for the triplet you are using.

Hope this helps, and if I'm incorrect in my thinking let me know.

**Comment by vicroms** [comment]
Hi @manhnt9 

@timautry you are correct that's how features in vcpkg work. The [instructions for Saga3D](https://gitlab.com/InnerPieceOSS/Saga3D/#building-on-windows-with-visual-studio) mention that you need to install SDL2 with the `vulkan` feature enabled:

> 
> Building on Windows with Visual Studio
> Install vcpkg
> Install Vulkan SDK
> Use vcpkg to install: assimp, **sdl2[vulkan]**, glm, vulkan
> Add additional parameters to CMake call: -G "Visual Studio 15 2017 Win64" -DCMAKE_TOOLCHAIN_FILE=_VCPKG_INSTALL_PATH_/scripts/buildsystems/vcpkg.cmake
> Build
> Execute Visual Studio target INSTALLL (right click on INSTALL -> Debug -> Start new instance)
> Pay attention you should specify platform you have been working on while installing packages into vcpkg!
> The default is x86, so you you have to type vcpkg install [package] --triplet x64-windows.

**Comment by manhnt9** [comment]
Hi, thanks @timautry and @vicroms. I updated the Saga3D's readme about Vulkan feature because I think it's the correct solution. However I'm still waiting for the guy who reported the error to confirm on his environment (Windows 10 + MSVC).

**Comment by manhnt9** [comment]
It's working fine now! Thanks everyone and sorry for causing a little bit of noise.
