### ISSUE TITLE
vcpkg.targets not imported automatically into MSBuild based port projects during build 

### ISSUE THREAD

**Issue by 4creators** [Microsoft/vcpkg#891]
Playing with guetzli JPEG encoder port (it's exe, so there is another problem to discuss) I have encountered a problem with using already installed vcpkg packages. vcpkg MSBuild implementation did not pick it up unless explicitly asked for doing so with OPTIONS /p:ForceImportBeforeCppTargets=${VCPKG_ROOT_DIR}/scripts/buildsystems/msbuild/vcpkg.targets inside vcpkg_build_msbuild. In my opinion every new package should use installed vcpkg packages by default without the need to explicitly set it during packaging in port file.

**Comment by ras0219-msft** [comment]
Related: #828

**Comment by researcher2** [comment]
Hello. I'm trying to create a portfile for my library and this is still happening. Not sure if it makes a difference but I'm trying to build using static CRT linkage. Adding "OPTIONS /p:ForceImportBeforeCppTargets=${VCPKG_ROOT_DIR}/scripts/buildsystems/msbuild/vcpkg.targets" to "vcpkg_build_msbuild" fixes the problem as mentioned above.
