### ISSUE TITLE
[zeromq] Building package zeromq:x86-windows failed with: BUILD_FAILED 

### ISSUE THREAD

**Issue by mawdis2** [microsoft/vcpkg#8910]
OS: Windows 10
When trying to install the zeromq package the build fails with the following console output:

C:\DM\vcpkg-2019.10>.\vcpkg install zeromq
The following packages will be built and installed:
    zeromq[core]:x86-windows
Starting package 1/1: zeromq:x86-windows
Building package zeromq[core]:x86-windows...
-- Using cached C:/DM/vcpkg-2019.10/downloads/zeromq-libzmq-8d34332ff2301607df0fc9971a2fbe903c0feb7c.tar.gz
-- Using source at C:/DM/vcpkg-2019.10/buildtrees/zeromq/src/903c0feb7c-34456404d0
-- Configuring x86-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: ninja -v
    Working Directory: C:/DM/vcpkg-2019.10/buildtrees/zeromq/x86-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\DM\vcpkg-2019.10\buildtrees\zeromq\config-x86-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:296 (vcpkg_execute_required_process)
  ports/zeromq/portfile.cmake:22 (vcpkg_configure_cmake)
  scripts/ports.cmake:94 (include)

Error: Building package zeromq:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: zeromq:x86-windows
  Vcpkg version: 2019.09.12-nohash

[config-x86-windows-out.log](https://github.com/microsoft/vcpkg/files/3810416/config-x86-windows-out.log)

I cloned the "vcpkg-master" file which gave me this issue. So I downloaded the newest version I could find "vcpkg-2019.10" and the build still failed.

**Comment by JackBoosY** [comment]
Error:
```
CMake Error at CMakeLists.txt:2 (project):
  No CMAKE_C_COMPILER could be found.
```

Please provide your Visual Studio version.

Thanks.

**Comment by mawdis2** [comment]
I was originally using Visual Studio 2019 but that was giving me this same problem. So I reverted back to Visual Studio 2017 version 15.0.0. I only have this version installed on my machine. Both gave me the same issue.

**Comment by mawdis2** [comment]
I noticed a `needs-repro` tag was added. Is more clarification needed from my end?

**Comment by JackBoosY** [comment]
@mawdis2 Yes, I still cannot repro it, and I have no idea where goes wrong, we need a discussion before you provide more information.

**Comment by mawdis2** [comment]
@JackBoosY  These are the exact steps I took to get to this point. I hope this helps:

1. Download and unzip "vcpkg-2019.06.zip" from here:(https://github.com/microsoft/vcpkg/releases/tag/2019.06 )

2.  Run the command prompt and CD to `vcpkg-2019.06`

3. Build vcpkg using: `.\bootstrap-vcpkg.bat` (Build was successful)

4. Apply user-wide integration: `.\vcpkg integrate install`

5. Attempt to install zeromq: `.\vcpkg install zeromq` (Build Fails here)

6. The build fails with the following cmd output:
<img width="717" alt="Capture" src="https://user-images.githubusercontent.com/29983353/68531059-fcbfba80-02d3-11ea-9a19-50d2cf78228a.PNG">

7. I then made sure that the packages were all up to date: `.\vcpkg update` (No packages needed updates)

[config-x86-windows-out.log](https://github.com/microsoft/vcpkg/files/3827442/config-x86-windows-out.log)

**Comment by JackBoosY** [comment]
@mawdis2 Could you use powershell instead of Visual Stdio command prompt and try again?

Thanks.

**Comment by mawdis2** [comment]
@JackBoosY I still get the same error using powershell:
<img width="676" alt="Capture" src="https://user-images.githubusercontent.com/29983353/69010250-8817fc00-0923-11ea-9043-f8bf04ec888b.PNG">

**Comment by JackBoosY** [comment]
@vicroms I don't know what's wrong here, it should recognize the compiler.

**Comment by JackBoosY** [comment]
@mawdis2 Could you update vcpkg and try again?
Is there anything special about your environment?

**Comment by JackBoosY** [comment]
We haven't been able to repro this; if more information comes up, or this issue appears again, please reopen.
