### ISSUE TITLE
[boost-regex:x86-windows] build failure

### ISSUE THREAD

**Issue by Guoqifeng** [microsoft/vcpkg#8915]
**Host Environment**
- OS: [Windows]
- Compiler: Vcpkg version: 2019.09.12-nohash

**To Reproduce**
`./vcpkg install boost` or `./vcpkg install boost-regex`

**Failure logs** 
```
The following packages will be built and installed:
    boost-regex[core]:x86-windows
Starting package 1/1: boost-regex:x86-windows
Building package boost-regex[core]:x86-windows...
-- Using cached D:/repos/pkg/vcpkg/downloads/boostorg-regex-boost-1.71.0.tar.gz
-- Using source at D:/repos/pkg/vcpkg/buildtrees/boost-regex/src/ost-1.71.0-0c1b0890fe
-- Building x86-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: D:/repos/pkg/vcpkg/installed/x86-windows/tools/boost-build/b2.exe --stagedir=D:/repos/pkg/vcpkg/buildtrees/boost-regex/x86-windows-rel/stage --build-dir=D:/repos/pkg/vcpkg/buildtrees/boost-regex/x86-windows-rel --user-config=D:/repos/pkg/vcpkg/buildtrees/boost-regex/x86-windows-rel/user-config.jam -j12 --debug-configuration --debug-building --debug-generators --disable-icu --ignore-site-config --hash -q -sZLIB_INCLUDE=D:/repos/pkg/vcpkg/installed/x86-windows/include -sBZIP2_INCLUDE=D:/repos/pkg/vcpkg/installed/x86-windows/include threading=multi threadapi=win32 runtime-link=shared link=shared address-model=32 architecture=x86 toolset=msvc -sZLIB_BINARY=zlib -sZLIB_LIBPATH=D:/repos/pkg/vcpkg/installed/x86-windows/lib -sBZIP2_BINARY=bz2 -sBZIP2_LIBPATH=D:/repos/pkg/vcpkg/installed/x86-windows/lib variant=release debug-symbols=on
    Working Directory: D:/repos/pkg/vcpkg/buildtrees/boost-regex/src/ost-1.71.0-0c1b0890fe/build
    Error code: 1
    See logs for more information:
      D:\repos\pkg\vcpkg\buildtrees\boost-regex\build-x86-windows-rel-out.log

Call Stack (most recent call first):
  installed/x86-windows/share/boost-build/boost-modular-build.cmake:278 (vcpkg_execute_required_process)
  ports/boost-regex/portfile.cmake:20 (boost_modular_build)
  scripts/ports.cmake:94 (include)


Error: Building package boost-regex:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-regex:x86-windows
  Vcpkg version: 2019.09.12-nohash

Additionally, attach any relevant sections from the log files above.
```
[build-x86-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/3811894/build-x86-windows-rel-out.log)

**Comment by Guoqifeng** [comment]
I ran the command manually, it seems lost a dir setting in the cmd.
![微信图片_20191106202222](https://user-images.githubusercontent.com/11657961/68297964-337ab280-00d3-11ea-94eb-2b8c68c6b134.png)

**Comment by JackBoosY** [comment]
@Guoqifeng Have you built the boost manually?

**Comment by Guoqifeng** [comment]
not yet

**Comment by Guoqifeng** [comment]
Should I download and build boost manually?

**Comment by Guoqifeng** [comment]
Can you reproduce the issue in your environment？

**Comment by JackBoosY** [comment]
@Guoqifeng Nop, I cannot repro it on my machine.

**Comment by paulcleggSIG** [comment]
I have the same or similar issue with boost-regex that @Guoqifeng reports:

`13:18:20 C:\dev\vcpkg> C:/dev/vcpkg/_vcpkg/installed/x64-windows-static-lib-dynamic-crt-v141/tools/boost-build/b2.exe --stagedir=C:/dev/vcpkg/_vcpkg/buildtrees/boost-regex/x64-windows-static-lib-dynamic-crt-v141-rel/stage --build-dir=C:/dev/vcpkg/_vcpkg/buildtrees/boost-regex/x64-windows-static-lib-dynamic-crt-v141-rel --user-config=C:/dev/vcpkg/_vcpkg/buildtrees/boost-regex/x64-windows-static-lib-dynamic-crt-v141-rel/user-config.jam -j20 --debug-configuration --debug-building --debug-generators --disable-icu --ignore-site-config --hash -q -sZLIB_INCLUDE=C:/dev/vcpkg/_vcpkg/installed/x64-windows-static-lib-dynamic-crt-v141/include -sBZIP2_INCLUDE=C:/dev/vcpkg/_vcpkg/installed/x64-windows-static-lib-dynamic-crt-v141/include threading=multi threadapi=win32 runtime-link=shared link=static address-model=64 architecture=x86 toolset=msvc -sZLIB_BINARY=zlib -sZLIB_LIBPATH=C:/dev/vcpkg/_vcpkg/installed/x64-windows-static-lib-dynamic-crt-v141/lib -sBZIP2_BINARY=bz2 -sBZIP2_LIBPATH=C:/dev/vcpkg/_vcpkg/installed/x64-windows-static-lib-dynamic-crt-v141/lib variant=release debug-symbols=on
Unable to load Boost.Build: could not find "boost-build.jam"
---------------------------------------------------------------
BOOST_ROOT must be set, either in the environment, or
on the command-line with -sBOOST_ROOT=..., to the root
of the boost installation.

Attempted search from C:\dev\vcpkg up to the root
at C:/dev/vcpkg/_vcpkg/installed/x64-windows-static-lib-dynamic-crt-v141/tools/share/boost-build

Please consult the documentation at 'http://www.boost.org'.`

**Comment by paulcleggSIG** [comment]
The only recent change in the boost ports is #8606 . That commit (boost 1.70 => boost 1.71) lines up with when the boost-regex port began faling with this error.

**Comment by paulcleggSIG** [comment]
Disregard the #8606 link as I repro'd the same issue when checking out a prior commit. 

I am able to build and install boost-regex as long as I export the parent dir of vcpkg.exe into the shell PATH. @Guoqifeng try 1) clearing your downloads directory of any boost* files 2) exporting to the path and reinstalling boost-regex.

**Comment by JackBoosY** [comment]
@ras0219-msft Can you take a look?

Thanks.

**Comment by JackBoosY** [comment]
Hi @Guoqifeng, does this issue still exist?

**Comment by Guoqifeng** [comment]
> Hi @Guoqifeng, does this issue still exist?

I just reset my os system and it seems worked.
