### ISSUE TITLE
How do I get x86-linux libraries?

### ISSUE THREAD

**Issue by yzz-ihep** [microsoft/vcpkg#8917]
When asking a question please also include where you looked for an answer (so we can update the documentation if needed).

**Comment by JackBoosY** [comment]
Hi @yzz-ihep, thanks for reporting this issue!
You can create a cmake file named `x86-linux.cmake` in _VCPKG_PATH/triplets_ and put these code in it:
```
set(VCPKG_TARGET_ARCHITECTURE x86)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)

set(VCPKG_CMAKE_SYSTEM_NAME Linux)
```

Then build port with command `./vcpkg install port:x86-linux`.

Thanks.

**Comment by yzz-ihep** [comment]
It's helpful! thanks!
