### ISSUE TITLE
VCPKG not installing any packages

### ISSUE THREAD

**Issue by vinot19** [Microsoft/vcpkg#892]
After successfully running the first two steps .\bootstrap-vcpkg.bat and .\vcpkg integrate install
I tried to install .\vcpkg install sdl2 curl, and I got the error below.

Error: Building package sdl2:x86-windows failed with: BUILD_FAILED
Package: sdl2:x86-windows
Vcpkg version: 0.0.78-unknownhash

Please advise how to fix this.

**Comment by ras0219-msft** [comment]
Hi @vinot19,

Could you please post the error message and log files printed in your console above those lines? They should look like `path\to\vcpkg\buildtrees\sdl2\build-x86-windows-rel-out.log`.

**Comment by vinot19** [comment]
Hi @ras0219-msft ,

Thank you very much for looking into this issue. Here I added all the code I have entered and got.  Please see that below.

C:\src\vcpkg>.\bootstrap-vcpkg.bat
Build succeeded.
    0 Warning(s)
    0 Error(s)
Time Elapsed 00:00:28.22

C:\src\vcpkg>.\vcpkg integrate install
Applied user-wide integration for this vcpkg root.
All MSBuild C++ projects can now #include any installed libraries.
Linking will be handled automatically.
Installing new libraries will make them instantly available.

CMake projects should use -DCMAKE_TOOLCHAIN_FILE=C:/src/vcpkg/scripts/buildsystems/vcpkg.cmake

C:\src\vcpkg> .\vcpkg install sdl2 curl
Error: Building package sdl2:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: sdl2:x86-windows
  Vcpkg version: 0.0.78-unknownhash

Additionally, attach any relevant sections from the log files above.

Thank you.

**Comment by ras0219-msft** [comment]
>C:\src\vcpkg> .\vcpkg install sdl2 curl
Error: Building package sdl2:x86-windows failed with: BUILD_FAILED

Are there no messages between those two lines? If not, we must be having trouble launching cmake.

What version(s) of CMake do you have installed on your machine? Did we download cmake for you locally (you can check in the `downloads\` folder for a `cmake-3.8.0-...` folder)?

**Comment by vinot19** [comment]
Yes, there are no message between the two lines.

I have installed 3.8.0( cmake-3.8.0-rc4-win64-x64). Yes, I downloaded the .msi file, and installed.

Do we have to look into this line? Please advise.
CMake projects should use -DCMAKE_TOOLCHAIN_FILE=C:/src/vcpkg/scripts/buildsystems/vcpkg.cmake

Thank you.

**Comment by ras0219-msft** [comment]
Ok, I've added some additional debugging capabilities which should help diagnose the problem here.

Could you pull the latest, run bootstrap, then do `vcpkg install sdl2 --debug` and let me know what it says? You should get a long debug message like `[DEBUG] _wspawnlpe(cmd.exe /c ""C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x86 >nul 2>&1 && "C:\Program Files\CMake\bin\cmake.exe" "-DCMD=BUILD" "-DPORT=sdl2" "-DCURRENT_PORT_DIR=D:/src/vcpkg/ports/sdl2/." "-DTARGET_TRIPLET=x86-windows" "-DVCPKG_PLATFORM_TOOLSET=v141" "-DGIT=C:/Program Files/Git/cmd/git.exe" -P "D:/src/vcpkg/scripts/ports.cmake"")`

**Comment by vinot19** [comment]
Thank you. I run the latest bootstrap, and I got the below message. Please see that.

C:\src\vcpkg> vcpkg install sdl2 --debug

[DEBUG] _wspawnlpe(cmd.exe /c ""C:\Program Files (x86)\MSVS15\VC\vcvarsall.bat" x86 >nul 2>&1 && "C:\Program Files (x86)\CMake\bin\cmake.exe" "-DCMD=BUILD" "-DPORT=sdl2" "-DCURRENT_PORT_DIR=C:/src/vcpkg/ports/sdl2/." "-DTARGET_TRIPLET=x86-windows" "-DVCPKG_PLATFORM_TOOLSET=v140" "-DGIT=C:/Program Files/Git/cmd/git.exe" -P "C:/src/vcpkg/scripts/ports.cmake"")
[DEBUG] _wspawnlpe() returned -1

Error: Building package sdl2:x86-windows failed with: BUILD_FAILED

**Comment by alexkaratarakis** [comment]
@vinot19 
OK, we are getting closer. It is possible that vcvarsall.bat does not exist OR fails to execute.
Can you verify that `C:\Program Files (x86)\MSVS15\VC\vcvarsall.bat` (which is where we are detecting your `vcvarsall.bat` to be) exists and you can run it?

I have further modified (0d65de2aa9da31ba6264b25038da2b14028b0419) --debug to give a bit more info and fixed an issue with the environment (bb7cccc2acbcd8e5b7a4d20a1ba8bc27146f96d1). Can you try bootstrapping and see if it has fixed the issue?

**Comment by vinot19** [comment]
@alexkaratarakis 
Thank you for your instructions. vcvarsall.bat exists but it fails to execute when I run that.
I used your modified files and there is no change in the result. I am still getting the Error: Building package sdl2:x86-windows failed with: BUILD_FAILED.

**Comment by alexkaratarakis** [comment]
@vinot19 
> but it fails to execute when I run that.

Do you mean it doesn't run at all? Does it show any error messages?
Can you try `vcpkg env --debug` and paste the output here? (this command runs `vcvarsall.bat` for you)

**Comment by vinot19** [comment]
I made a mistake, and it's running now. Thank you.
