### ISSUE TITLE
[New Port Request] libproxy

### ISSUE THREAD

**Issue by vicroms** [microsoft/vcpkg#8927]
Library name: `libproxy`

Library description: A library that provides automatic proxy configuration management. 

Source repository URL: https://github.com/libproxy/libproxy 

Project homepage (if different from the source repository): http://libproxy.github.io/libproxy/

Required for `Microsoft/proxywrapper` (PR #8916)

**Comment by JackBoosY** [comment]
Related: #8916.

**Comment by vicroms** [comment]
Hi @JackBoosY 

That PR needs `libproxy` to be ported first, but the submitter doesn't have the time to work on the port at the moment.

**Comment by NancyLi1013** [comment]
Since this port has been added, I'm closing this issue for now.
