### ISSUE TITLE
BUILD_FAILED: boost:x86-uwp & boost:x64-uwp [MSVStudio 2015 Update 3]

### ISSUE THREAD

**Issue by AJIOB** [Microsoft/vcpkg#893]
**Console out**:

	vcpkg install mongo-cxx-driver:x64-windows mongo-cxx-driver:x86-windows mongo-cxx-driver:x86-uwp mongo-cxx-driver:x64-uwp
	Package mongo-cxx-driver:x64-windows is already installed
	Package mongo-cxx-driver:x86-windows is already installed
	-- CURRENT_INSTALLED_DIR=D:/Alex/Documents/SourceTree/vcpkg/installed/x86-uwp
	-- DOWNLOADS=D:/Alex/Documents/SourceTree/vcpkg/downloads
	-- CURRENT_PACKAGES_DIR=D:/Alex/Documents/SourceTree/vcpkg/packages/boost_x86-uwp
	-- CURRENT_BUILDTREES_DIR=D:/Alex/Documents/SourceTree/vcpkg/buildtrees/boost
	-- CURRENT_PORT_DIR=D:/Alex/Documents/SourceTree/vcpkg/ports/boost/.
	-- Downloading https://sourceforge.net/projects/boost/files/boost/1.63.0/boost_1_63_0.tar.bz2...
	-- Downloading https://sourceforge.net/projects/boost/files/boost/1.63.0/boost_1_63_0.tar.bz2... OK
	-- Testing integrity of downloaded file...
	-- Testing integrity of downloaded file... OK
	-- Extracting done
	-- Downloading https://github.com/boostorg/range/commit/e7ebe14707130cda7b72e0ae5e93b17157fdb6a2.diff...
	-- Downloading https://github.com/boostorg/range/commit/e7ebe14707130cda7b72e0ae5e93b17157fdb6a2.diff... OK
	-- Testing integrity of downloaded file...
	-- Testing integrity of downloaded file... OK
	-- Downloading https://github.com/boostorg/thread/commit/bd0379af57fa294df310221492da618844182658.diff...
	-- Downloading https://github.com/boostorg/thread/commit/bd0379af57fa294df310221492da618844182658.diff... OK
	-- Testing integrity of downloaded file...
	-- Testing integrity of downloaded file... OK
	-- Applying patch D:/Alex/Documents/SourceTree/vcpkg/buildtrees/boost/src/boost-range-has_range_iterator-hotfix_e7ebe14707130cda7b72e0ae5e93b17157fdb6a2.diff.fixed
	-- Applying patch failed. This is expected if this patch was previously applied.
	-- Applying patch D:/Alex/Documents/SourceTree/vcpkg/buildtrees/boost/src/boost-range-has_range_iterator-hotfix_e7ebe14707130cda7b72e0ae5e93b17157fdb6a2.diff.fixed done
	-- Applying patch D:/Alex/Documents/SourceTree/vcpkg/buildtrees/boost/src/boost-thread-on_tls_callback-bd0379af57fa294df310221492da618844182658.diff.fixed
	-- Applying patch failed. This is expected if this patch was previously applied.
	-- Applying patch D:/Alex/Documents/SourceTree/vcpkg/buildtrees/boost/src/boost-thread-on_tls_callback-bd0379af57fa294df310221492da618844182658.diff.fixed done
	-- Bootstrapping done
	-- Building x86-uwp-rel
	CMake Error at scripts/cmake/vcpkg_execute_required_process_repeat.cmake:21 (message):
		Command failed: D:/Alex/Documents/SourceTree/vcpkg/buildtrees/boost/src/boost_1_63_0/b2.exe;--stagedir=D:/Alex/Documents/SourceTree/vcpkg/buildtrees/boost/x86-uwp-rel/stage;--build-dir=D:/Alex/Documents/SourceTree/vcpkg/buildtrees/boost/x86-uwp-rel;-sZLIB_INCLUDE="D:/Alex/Documents/SourceTree/vcpkg/installed/x86-uwp\include";-sBZIP2_INCLUDE="D:/Alex/Documents/SourceTree/vcpkg/installed/x86-uwp\include";-j8;--debug-configuration;--hash;-q;--without-python;threading=multi;runtime-link=shared;link=shared;windows-api=store;toolset=msvc-14.0;-sZLIB_BINARY=zlib;-sZLIB_LIBPATH="D:/Alex/Documents/SourceTree/vcpkg/installed/x86-uwp\lib";-sBZIP2_BINARY=bz2;-sBZIP2_LIBPATH="D:/Alex/Documents/SourceTree/vcpkg/installed/x86-uwp\lib";variant=release;debug-symbols=on
		Working Directory: D:/Alex/Documents/SourceTree/vcpkg/buildtrees/boost/src/boost_1_63_0
		See logs for more information:
		  D:\Alex\Documents\SourceTree\vcpkg\buildtrees\boost\build-x86-uwp-rel-out.log
		  D:\Alex\Documents\SourceTree\vcpkg\buildtrees\boost\build-x86-uwp-rel-err.log

	Call Stack (most recent call first):
	  ports/boost/portfile.cmake:135 (vcpkg_execute_required_process_repeat)
	  scripts/ports.cmake:73 (include)

	Error: Building package boost:x86-uwp failed with: BUILD_FAILED
	Please ensure you're using the latest portfiles with `.\vcpkg update`, then
	submit an issue at https://github.com/Microsoft/vcpkg/issues including:
	  Package: boost:x86-uwp
	  Vcpkg version: 0.0.78-db73e73c562a00228dd8c01ee2a03f03012023fc

	Additionally, attach any relevant sections from the log files above.

Logs you can find here:
[build-x86-uwp-rel-err.log](https://github.com/Microsoft/vcpkg/files/890795/build-x86-uwp-rel-err-2.log.txt)
[build-x86-uwp-rel-out.log](https://github.com/Microsoft/vcpkg/files/890796/build-x86-uwp-rel-out-2.log.txt)

Simple output you can find, if you want to install boost:x64-uwp version

**Comment by ras0219-msft** [comment]
I believe this is caused by a hardcoded path of "C:\program files (x86)" inside our user-config.jam file for UWP -- you're on a 32-bit system, right?

If so, you should be able to locally patch this by editing the `ports\boost\uwp\user-config.jam` and changing `Program Files (x86)` to just `Program Files`. We'll get it fixed upstream as soon as possible as well.

**Comment by AJIOB** [comment]
@ras0219-msft 
I have a Windows 10 Pro x64 version.
I install my VisualStudio to D:/ drive ("D:\Program Files (x86)\Microsoft Visual Studio 14.0").
I'm trying change <compileflags> in `user-config.jam` to 
> "\"/AID:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\LIB\\store\\references\""
> "\"/AID:\\Program Files\\Microsoft Visual Studio 14.0\\VC\\LIB\\store\\references\""
> "\"/AIC:\\Program Files\\Microsoft Visual Studio 14.0\\VC\\LIB\\store\\references\""

but have the same experience.  
Of course, when I try to install boost lib, I have the error:
`This app can't run on your PC. To find a version for your PC, check with the software publisher`.
I see that error about 10 times of each install.

**Comment by AJIOB** [comment]
It builds nice, if you try to build it from dev/.../boost-uwp branch. Thank you.
P.S. It is about x86 and x64 uwp versions

**Comment by AJIOB** [comment]
Commit 35749685c353ba55550055c900f6f2fdeab1743f  fixed my problem
