### ISSUE TITLE
How to use a library after installation

### ISSUE THREAD

**Issue by bizehao** [microsoft/vcpkg#8933]
After using vcpkg install libxxx successfully, the method of how to use will be output under the CMD, but later I forget that I want to find out how to use libxxx 。
such as  When I install a leveldb successfully，After success, he will say 

     The package leveldb:x64-windows provides CMake targets:
     find_package(leveldb CONFIG REQUIRED)
     target_link_libraries(main PRIVATE leveldb::leveldb)
I'll use the installed package later, but I forget about it

**Comment by JackBoosY** [comment]
See [documentation](https://github.com/microsoft/vcpkg/blob/master/docs/examples/installing-and-using-packages.md).

**Comment by bizehao** [comment]
ok thanks
