### ISSUE TITLE
any changes in toolchain file? CatchLib stoped working

### ISSUE THREAD

**Issue by amigo421** [Microsoft/vcpkg#894]
this attempt to include CatchLib into the project, taken from your documentation
```
find_file(CATCH_INCLUDE_DIR "catch.hpp")
include_directories(${INCLUDE_DIRECTORIES} ${CATCH_INCLUDE_DIR})

```
doesn't work 
![image](https://cloud.githubusercontent.com/assets/3259933/24622970/8edde160-18af-11e7-94f7-b03e102a2d1f.png)

with a settings: 

![image](https://cloud.githubusercontent.com/assets/3259933/24622861/2eb474e8-18af-11e7-89ec-691aa4194dd1.png)

![image](https://cloud.githubusercontent.com/assets/3259933/24622915/5b7f9142-18af-11e7-9baa-1ee10034ccd4.png)

this file really exists and if I'll add PATH of HINT parameter to find_path with absolute path to this,
this will work, but I'd prefer to rely on toolchain file
![image](https://cloud.githubusercontent.com/assets/3259933/24623046/d6341ba6-18af-11e7-84bc-251011248e12.png)

any changes in TOOLCHAIN file? because , as I remember, earlier it was working... probably I forgot real thing...

**Comment by tobiaskohlbau** [comment]
Looks like you've mistaken the function `find_file` from CMake it searches for the file. If you look at your second screenshot it states that `CATCH_INCLUDE_DIR=C:/dev/cxx/vcpkg/installed/x64-windows/include/catch.hpp`. If I'm not mistaken you want to use `find_path` to find the path from the `catch.hpp` and append this with `include_directories(${CATCH_INCLUDE_DIR})`. Notice it's not necessary to include `${INCLUDE_DIRECTORIES}` within cmake call to `include_directories`, as the documentation states it appends to the existing include directories.

**Comment by amigo421** [comment]
so sorry for my inattention, of course you right.
