### ISSUE TITLE
[suitesparse[metis]] build failure

### ISSUE THREAD

**Issue by xarthurx** [microsoft/vcpkg#8942]
**Host Environment**
- OS: Windows
- Compiler: revision

**To Reproduce**
`./vcpkg install suitesparse[metis] --recurse`

**Failure logs** 
```
The following packages will be built and installed:
  * metis[core]:x64-windows
    suitesparse[core,metis]:x64-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/2: metis:x64-windows
Building package metis[core]:x64-windows...
-- Note: metis only supports static library linkage. Building static library.
-- Downloading http://glaros.dtc.umn.edu/gkhome/fetch/sw/metis/metis-5.1.0.tar.gz...
-- Downloading http://glaros.dtc.umn.edu/gkhome/fetch/sw/metis/metis-5.1.0.tar.gz... Failed. Status: 6;"Couldn't resolve host name"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:175 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  ports/metis/portfile.cmake:8 (vcpkg_download_distfile)
  scripts/ports.cmake:94 (include)


Error: Building package metis:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: metis:x64-windows
  Vcpkg version: 2019.09.12-nohash
```

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by xarthurx** [comment]
related to: https://github.com/microsoft/vcpkg/issues/8336

**Comment by timautry** [comment]
@xarthurx Normally this error means either they are behind a proxy or the download site vcpkg is trying to download the file from is unavailable...
I just tried to contact the download site "http://glaros.dtc.umn.edu/gkhome/fetch/sw/metis/metis-5.1.0.tar.gz" to see if it would download the file to my pc but I get an error:

This site can't be reached
glaros.dtc.umn.edu's server IP address could not be found.
ERR_NAME_NOT_RESOLVED

So the site may indeed be down or has been taken offline.

**Comment by JackBoosY** [comment]
Seems it's site has problem. Please download this package and put it into _VCPKG_PATH/downloads_ then rebuild suitesparse.
[metis-5.1.0.tar.gz](https://github.com/microsoft/vcpkg/files/3822715/metis-5.1.0.tar.gz)

Thanks.

**Comment by JackBoosY** [comment]
@xarthurx Does this  issue solved?

**Comment by xarthurx** [comment]
@JackBoosY Yes. I'll close it now. Thanks for the help.

**Comment by SallySoul** [comment]
I think we can still fix this issue long term though. (I just had this failure again since this site seems to be down again.)

METIS is now distributed via github:
https://github.com/KarypisLab/METIS

However, the previously included GKLib library is not a sub module, so that would also need to be added:
https://github.com/KarypisLab/GKlib

Some changes have been made so the patches we currently have will not apply anymore. I will try and get a PR together, but wanted to make sure this was in a comment somewhere.
