### ISSUE TITLE
[gdal] linux build does not get dependencies from vcpkg

### ISSUE THREAD

**Issue by pwm1234** [microsoft/vcpkg#8943]
**Is your feature request related to a problem? Please describe.**
The linux vcpkg build of gdal does not get its dependencies from vcpkg.  The ``configure`` command needs to refer to the vcpkg install path so it finds its dependencies there. For example, xerces-c or tiff. They are found in ``/usr`` not in the vcpkg install path.

I am not sure how to change to portfile, but here is how I built gdal using the vcpkg install directory as ``$vcpkg``

    LDFLAGS=-L$vcpkg/lib \
        CFLAGS=-I$vcpkg/include \
        ./configure \
            --prefix=$pkg \
            --disable-shared \
            --enable-static \
            --with-pic \
            --with-curl=$vcpkg \
            --with-expat=$vcpkg \
            --with-geos=yes \
            --with-geotiff=$vcpkg \
            --with-hdf5=$vcpkg \
            --with-libkml=$vcpkg \
            --with-liblzma=yes \
            --with-libtiff=$vcpkg\
            --with-libz=$vcpkg\
            --with-openjpeg=$vcpkg \
            --with-png=$vcpkg \
            --with-proj=$vcpkg \
            --with-proj=$vcpkg \
            --with-spatialite=$vcpkg \
            --with-sqlite3=$vcpkg \
            --with-webp=$vcpkg \
            --with-xerces=$vcpkg \
            --with-xml2=$vcpkg 

(I am not sure if the gdal build is using the vcpkg ``geos`` -- there is some strange behavior regarding the [missing] geos config file.)

**Comment by jumpinjackie** [comment]
I believe #6752 is somewhat blocking this effort in that making vcpkg symlink `debug/include` is better than an invasive patch for gdal's `./configure` script and m4 macros to distinguish between the various vcpkg paths.

Not familiar with the vcpkg source though to try adding support for this.

**Comment by lakinwecker** [comment]
I am also currently running into this issue. If I have netcdf/gdal installed from the arch repositories, then gdal will attempt to compile and link against them, and then I run into compatibility issues because arch linux includes newer versions.

**Comment by pwm1234** [comment]
Yes, these problems with gdal have made me give up using vcpkg with linux. I have found vcpkg works great on windows, but on linux where it is rather difficult to exclude pre-installed packages in /usr, I am encountering inconsistencies with packages that sometimes get dependencies from vcpkg and sometimes from what has been apt-get installed.

**Comment by dg0yt** [comment]
This issue should be fixed now.

**Comment by JackBoosY** [comment]
Please reopen this issue if it still exist.
