### ISSUE TITLE
PR failed in CL on Linux And Windows

### ISSUE THREAD

**Issue by longhuan2018** [microsoft/vcpkg#8945]
I found that the recently uploaded PR in the CL test, linux and windows will return an error, only osx is successful.
The errors in linux are "##[error]Artifact raw xml results not found for build ***. Please ensure you have published artifacts in any previous phases of the current build."
In the Test modified ports section, tips:
```
Time to determine pass/fail: 25.26 s
Starting package 1/368: ***:x64-linux
Building package ***[core]:x64-linux...
Using cached binary package: 
Error: while parsing the Binary Paragraph for ***:x64-linux
Error: There are invalid fields in the control file of ***:x64-linux
The following fields were not expected:

    Type

This is the list of valid fields (case-sensitive): 

    Source
    Version
    Description
    Maintainer
    Build-Depends
    Homepage
    Type

Different source may be available for vcpkg. Use .\bootstrap-vcpkg.bat to update.

Test complete
```

**Comment by JackBoosY** [comment]
@longhuan2018 Thanks for reporting this issue.

This is a CI system error and we are fixing this now.

**Comment by JackBoosY** [comment]
See #8949.
