### ISSUE TITLE
[New Port Request] xapian

### ISSUE THREAD

**Issue by feverzsj** [microsoft/vcpkg#8946]
Library name: xapian

Library description: an Open Source Search Engine Library

Source repository URL: https://git.xapian.org/xapian

Project homepage: https://xapian.org/

Anything else that is useful to know when adding:

xapian is possibly the only viable and mature IR and Full Text Search framework for the c++ world. It would be great to have it in vcpkg.

It supports msvc via msys, and depends on zlib, and optionally, icu.

[ref]

https://github.com/xapian/xapian/blob/master/xapian-core/INSTALL

https://github.com/xapian/xapian/blob/master/xapian-core/configure.ac for other useful flag

**Comment by NancyLi1013** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
