### ISSUE TITLE
VCPKG Root Folder Moving - Packages don't get found afterwards | CMake

### ISSUE THREAD

**Issue by gameanimation3d** [microsoft/vcpkg#8947]
**Describe the bug**

For Compiling an Github Repo i had to move the VCPKG Repo folder to another directory. 
And now the packages which got found before by CMake don't get found anymore

after moving the folder i called again:

> vcpkg integrate install

to fix an path issue
i aswell deinstalled all packages and removed the folders buildtrees,packages and installed. And kept the downloads.
After reinstalling the corresponding packages nothing changed.

**Environment**
- OS: [e.g. Windows/Linux etc...] Windows 10, 64bit
- Compiler: revision Visual Studio 2019 MSVC v142 | CMake 3.15.4 | Latest Master df4773c

**To Reproduce**
1. ./vcpkg install xxxx
git clone https://github.com/Microsoft/vcpkg.git
cd vcpkg
.\bootstrap-vcpkg.bat
.\vcpkg integrate install

"install Instruction from AliceVision Repo to build https://github.com/alicevision/AliceVision/blob/develop/INSTALL.md

> cd VCPKG Root
> set VCPKG_ROOT=%cd%
> 
> .\vcpkg install boost-algorithm boost-accumulators boost-atomic boost-container boost-date-time boost-exception boost-filesystem boost-graph boost-log boost-program-options boost-property-tree boost-ptr-container boost-regex boost-serialization boost-system boost-test boost-thread boost-timer lz4 openexr openimageio[libraw] alembic geogram eigen3 ceres[suitesparse] cuda --triplet x64-windows
> 
> cd /path/to/aliceVision/

> mkdir build && cd build

> cmake .. -DCMAKE_TOOLCHAIN_FILE= %VCPKG_ROOT%\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows -G "Visual Studio 16 2019" -A x64 -T host=x64 

2. See error

> CMake Error at C:/Program Files/CMake/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/CMake/share/cmake-3.15/Modules/FindZLIB.cmake:115 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  src/cmake/FindOpenEXR.cmake:22 (find_package)
  src/CMakeLists.txt:285 (find_package)

vcpkg list tell me that for triplet x64-windows everything is installed
**Expected behavior**

**Failure logs** 
CMD Output
https://gist.github.com/gameanimation3d/5cbd82d9350255c99a815bec4fd166f2
-(please attached failure logs)

CMakeError File:
https://gist.github.com/gameanimation3d/5b72fa84634f741f92ae3792b9b96f34
CMake Output:
https://gist.github.com/gameanimation3d/83685585beed6b5aa90a20b3f834d971

**Additional context**

Would be amazing if somebody could help me

**Comment by Voskrese** [comment]
some script is causing a crash
try migrating these two files
and try again

> C:/Program Files/CMake/share/**cmake-3.15/Modules**/FindZLIB.cmake
> /path/to/**aliceVision**/src/cmake/FindOpenEXR.cmake

**Comment by gameanimation3d** [comment]
Hey,
thanks 

> C:/Program Files/CMake/share/cmake-3.15/Modules/FindZLIB.cmake

they can't find the ZLIB Package with find_package. 

>  /path/to/aliceVision/src/cmake/FindOpenEXR.cmake


> find_package (ZLIB REQUIRED)

requires the ZLIB to be found. and therefore crashes

Where does vcpkg stores the path for cmake to search for the find_packages call?

**Comment by Voskrese** [comment]
search in
vcpkg\installed\x64-windows\share\ <<--

**Comment by PhoebeHui** [comment]
If you are interest in building AliceVision with VCPKG, you can try https://github.com/microsoft/vcpkg/pull/8829, feel free to help review the changes. 
Please make sure zlib:x64-windows installed, and we will try to repro your issue next week, It need some time to build the dependency.

**Comment by Neumann-A** [comment]
Just a side note: `vcpkg integrate install` does nothing/ is not required if you use CMake. The integration is only necessary if you only use MSBuild but i strongly suggest not using it at all due to its lazy linking behavior.

**Comment by gameanimation3d** [comment]
thank you very much guys for the help

the issue was that the CMAKE_TOOLCHAIN_FILE variable was curiously empty. when printet it out with:

>  message(STATUS "CMAKE_TOOLCHAIN_FILE: ${CMAKE_TOOLCHAIN_FILE}")

I solved it by passing no longer the %VCPKG_ROOT% env variable and using the full path. And having no space between argument (-DCMAKE_TOOLCHAIN_FILE=) and the path. 

Wrong:
-DCMAKE_TOOLCHAIN_FILE= M:\Repo\ ..
Good:
-DCMAKE_TOOLCHAIN_FILE=M:\Repo\ ..

**Comment by PhoebeHui** [comment]
@gameanimation3d, glad to hear that you solved this issue!
