### ISSUE TITLE
libsodium build script not properly detect CPU feature

### ISSUE THREAD

**Issue by valbendan** [microsoft/vcpkg#8956]
**Describe the bug**
When I  (static) link my program with the libsodium.a library,  running my program lead to core dump.

**Environment**
- OS: Ubuntu 18.04.3 LTS
- Compiler: gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0

**To Reproduce**
1. ./vcpkg install libsodium

**Expected behavior**

**Failure logs** 
Illegal instruction (core dumped)

core dump stack:
  >│0x562887b92931  vmovdqa 0x464ad7(%rip),%xmm0        # 0x562887ff7410                │

**Additional context**
```bash
cat /proc/cpuinfo

processor	: 19
vendor_id	: GenuineIntel
cpu family	: 15
model		: 6
model name	: Common KVM processor
stepping	: 1
microcode	: 0x1
cpu MHz		: 2297.338
cache size	: 16384 KB
physical id	: 1
siblings	: 10
core id		: 9
cpu cores	: 10
apicid		: 25
initial apicid	: 25
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx lm constant_tsc nopl xtopology cpuid tsc_known_freq pni cx16 x2apic hypervisor lahf_lm cpuid_fault pti
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs
bogomips	: 4594.67
clflush size	: 64
cache_alignment	: 128
address sizes	: 40 bits physical, 48 bits virtual
power management:
```

**Comment by JackBoosY** [comment]
@valbendan Could you provide the sample code?

Thanks.

**Comment by valbendan** [comment]
https://github.com/valbendan/LibsodiumVcpkg

**Comment by myd7349** [comment]
This might be the same as https://github.com/microsoft/vcpkg/issues/7308 . A quick fix for this is using `vcpkg_*_make` functions on *nix.

**Comment by JackBoosY** [comment]
@myd7349 Maybe we missed something in CMakeLists.txt.
