### ISSUE TITLE
vcpkg install cuda:x64-windows does not work

### ISSUE THREAD

**Issue by Dredok** [Microsoft/vcpkg#896]
see attached log:

> vcpkg install cuda:x64-windows
-- CURRENT_INSTALLED_DIR=C:/src/3rdParty/vcpkg/installed/x64-windows
-- DOWNLOADS=C:/src/3rdParty/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=C:/src/3rdParty/vcpkg/packages/cuda_x64-windows
-- CURRENT_BUILDTREES_DIR=C:/src/3rdParty/vcpkg/buildtrees/cuda
-- CURRENT_PORT_DIR=C:/src/3rdParty/vcpkg/ports/cuda/.
CMake Error at ports/cuda/portfile.cmake:22 (string):
  string sub-command REGEX, mode MATCH needs at least 5 arguments total to
  command.
Call Stack (most recent call first):
  scripts/ports.cmake:73 (include)

Error: Building package cuda:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: cuda:x64-windows
  Vcpkg version: 0.0.78-8d9766200eed7ef5327fd65ed129c2176df62738

Additionally, attach any relevant sections from the log files above.

**Comment by alexkaratarakis** [comment]
@Dredok 
This should be fixed with 846471c8f234e80303a8a945f71b93e1529f6440. 
Please try again with the latest vcpkg (v.0.0.79 and above).

Let me know if it still doesn't work for you!
