### ISSUE TITLE
[New Port Request] https://gitlab.gnome.org/GNOME/gobject-introspection/

### ISSUE THREAD

**Issue by ChameleonRed** [microsoft/vcpkg#8961]
Library name: gobject-introspection

Library description: required for pygobject on Windows 10

Source repository URL: https://gitlab.gnome.org/GNOME/gobject-introspection/s

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by ChameleonRed** [comment]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MT -DPY_SSIZE_T_CLEAN -IT:\Temp\pip-install-uftz8zdv\pygobject -IT:\Temp\pip-install-uftz8zdv\pygobject\gi "-Ic:\users\cezary wagner\pycharmprojects\cw_chess_training_positions\venv\include" -IC:\root\Python\Python37\include -IC:\root\Python\Python37\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" -IC:\root\vcpkg\buildtrees\glib\src\2.52.3-34a15219ec -IC:\root\vcpkg\packages\zlib_x64-windows\include -IC:\root\vcpkg\packages\pixman_x64-windows\include -IC:\root\vcpkg\packages\pcre_x64-windows\include -IC:\root\vcpkg\packages\libpng_x64-windows\include -IC:\root\vcpkg\packages\libiconv_x64-windows\include -IC:\root\vcpkg\packages\libffi_x64-windows\include -IC:\root\vcpkg\packages\glib_x64-windows\include -IC:\root\vcpkg\packages\gettext_x64-windows\include -IC:\root\vcpkg\packages\freetype_x64-windows\include -IC:\root\vcpkg\packages\fontconfig_x64-windows\include -IC:\root\vcpkg\packages\expat_x64-windows\include -IC:\root\vcpkg\packages\dirent_x64-windows\include -IC:\root\vcpkg\packages\cairo_x64-windows\include -IC:\root\vcpkg\packages\bzip2_x64-windows\include -IC:\root\vcpkg\packages\zlib_x64-windows\include -IC:\root\vcpkg\packages\pixman_x64-windows\include -IC:\root\vcpkg\packages\pcre_x64-windows\include -IC:\root\vcpkg\packages\libpng_x64-windows\include -IC:\root\vcpkg\packages\libiconv_x64-windows\include -IC:\root\vcpkg\packages\libffi_x64-windows\include -IC:\root\vcpkg\packages\glib_x64-windows\include -IC:\root\vcpkg\packages\gettext_x64-windows\include -IC:\root\vcpkg\packages\freetype_x64-windows\include -IC:\root\vcpkg\packages\fontconfig_x64-windows\include -IC:\root\vcpkg\packages\expat_x64-windows\include -IC:\root\vcpkg\packages\dirent_x64-windows\include -IC:\root\vcpkg\packages\cairo_x64-windows\include -IC:\root\vcpkg\packages\bzip2_x64-windows\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /Tcgi\gimodule.c /Fobuild\temp.win-amd64-3.7\Release\gi\gimodule.obj -FImsvc_recommended_pragmas.h
  gimodule.c
  T:\Temp\pip-install-uftz8zdv\pygobject\gi\pygi-repository.h(24): fatal error C1083: Nie moľna otworzy† pliku do\x88Ącz: 'girepository.h': No such file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.23.28105\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
  ----------------------------------------
  ERROR: Failed building wheel for pygobject
  Running setup.py clean for pygobject
Failed to build pygobject
ERROR: Could not build wheels for pygobject which use PEP 517 and cannot be installed directly

**Comment by ChameleonRed** [comment]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MT -DPY_SSIZE_T_CLEAN -IT:\Temp\pip-install-uftz8zdv\pygobject -IT:\Temp\pip-install-uftz8zdv\pygobject\gi "-Ic:\users\cezary wagner\pycharmprojects\cw_chess_training_positions\venv\include" -IC:\root\Python\Python37\include -IC:\root\Python\Python37\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" -IC:\root\vcpkg\buildtrees\glib\src\2.52.3-34a15219ec -IC:\root\vcpkg\packages\zlib_x64-windows\include -IC:\root\vcpkg\packages\pixman_x64-windows\include -IC:\root\vcpkg\packages\pcre_x64-windows\include -IC:\root\vcpkg\packages\libpng_x64-windows\include -IC:\root\vcpkg\packages\libiconv_x64-windows\include -IC:\root\vcpkg\packages\libffi_x64-windows\include -IC:\root\vcpkg\packages\glib_x64-windows\include -IC:\root\vcpkg\packages\gettext_x64-windows\include -IC:\root\vcpkg\packages\freetype_x64-windows\include -IC:\root\vcpkg\packages\fontconfig_x64-windows\include -IC:\root\vcpkg\packages\expat_x64-windows\include -IC:\root\vcpkg\packages\dirent_x64-windows\include -IC:\root\vcpkg\packages\cairo_x64-windows\include -IC:\root\vcpkg\packages\bzip2_x64-windows\include -IC:\root\vcpkg\packages\zlib_x64-windows\include -IC:\root\vcpkg\packages\pixman_x64-windows\include -IC:\root\vcpkg\packages\pcre_x64-windows\include -IC:\root\vcpkg\packages\libpng_x64-windows\include -IC:\root\vcpkg\packages\libiconv_x64-windows\include -IC:\root\vcpkg\packages\libffi_x64-windows\include -IC:\root\vcpkg\packages\glib_x64-windows\include -IC:\root\vcpkg\packages\gettext_x64-windows\include -IC:\root\vcpkg\packages\freetype_x64-windows\include -IC:\root\vcpkg\packages\fontconfig_x64-windows\include -IC:\root\vcpkg\packages\expat_x64-windows\include -IC:\root\vcpkg\packages\dirent_x64-windows\include -IC:\root\vcpkg\packages\cairo_x64-windows\include -IC:\root\vcpkg\packages\bzip2_x64-windows\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /Tcgi\gimodule.c /Fobuild\temp.win-amd64-3.7\Release\gi\gimodule.obj -FImsvc_recommended_pragmas.h
  gimodule.c
  T:\Temp\pip-install-uftz8zdv\pygobject\gi\pygi-repository.h(24): fatal error C1083: Nie moľna otworzy† pliku do\x88Ącz: 'girepository.h': No such file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.23.28105\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
  ----------------------------------------
  ERROR: Failed building wheel for pygobject
  Running setup.py clean for pygobject
Failed to build pygobject
ERROR: Could not build wheels for pygobject which use PEP 517 and cannot be installed directly

**Comment by ChameleonRed** [comment]
See that is related to https://github.com/microsoft/vcpkg/issues/8968

**Comment by ChameleonRed** [comment]
Probably here is some helpful information how to make it fully working (packages versions and references):

You can learn how to do package from https://packages.msys2.org/updates. They do some compilation of this library but not with MSVC https://pygobject.readthedocs.io/en/latest/getting_started.html.

**Comment by Voskrese** [comment]
msvc

https://github.com/wingtk/gvsbuild/blob/28f78f60f7760ad136fb47b6805579dd037c503b/gvsbuild/projects.py#L1742

**Comment by NancyLi1013** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
