### ISSUE TITLE
Should I have Visual studio installed ?

### ISSUE THREAD

**Issue by medilies** [microsoft/vcpkg#8967]
I'm trying to use VCPKG for VScode and I'm stuck in setting up VCPKG 

c:\Users\yo\Desktop\yo\vcpkg\bootstrap-vcpkg.bat
Could not find Visual Studio. VS2015 or VS2017 (with C++) needs to be installed.
Au caractère C:\Users\yo\Desktop\yo\vcpkg\scripts\bootstrap.ps1:143 : 9
+         throw "Could not find Visual Studio. VS2015 or VS2017 (with C++) needs t ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Could not find ...o be installed.:String) [], RuntimeException
    + FullyQualifiedErrorId : Could not find Visual Studio. VS2015 or VS2017 (with C++) needs to be installed.

**Comment by JackBoosY** [comment]
Yes, at least we need Visual Studio to compile vcpkg in Windows.

**Comment by medilies** [comment]
well this is desapointing for :/
I choosed VCS over VS for its light weight. downloading VS would be a nightmare for because of my internet speed. I hope that the developpers will make an alternative for compiling it :)

**Comment by PhoebeHui** [comment]
@medilies, thanks for the suggestion!

BTW, you can install some needed components, that will not take too much time, you can try following steps if you interest.

Download and install VS2017 installer, and open visual studio 2017 installer:
1, In Workloads tab, check 'Desktop development with C++'.
2. In Workloads tab, check 'Universal windows Platform development' for building UWP.
3, In Individual components, check additional components:
ARM:
Visual C++ compilers and libraries for ARM
Visual C++ compilers and libraries for ARM64
ATL/MFC:
Visual C++ ATL for x86 and x64
Visual C++ MFC for x86 and x64
Windows SDK:
Windows 10 SDK(10.0.17763.0)
