### ISSUE TITLE
[New Port Request] https://gitlab.gnome.org/GNOME/pygobject

### ISSUE THREAD

**Issue by ChameleonRed** [microsoft/vcpkg#8968]
Library name: https://gitlab.gnome.org/GNOME/pygobject

Library description: This very nice GUI for Python

Source repository URL: https://gitlab.gnome.org/GNOME/pygobject

Project homepage (if different from the source repository): https://gitlab.gnome.org/GNOME/pygobject

Anything else that is useful to know when adding (such as optional features the library may have that should be included): You can learn how to do package from https://packages.msys2.org/updates. They do some compilation of this library but not with MSVC https://pygobject.readthedocs.io/en/latest/getting_started.html.

I can not use MSVC for it.

**Comment by NancyLi1013** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
