### ISSUE TITLE
vcpkg_install_msbuild.script ARM64 update/correction

### ISSUE THREAD

**Issue by qz3fwd** [microsoft/vcpkg#8971]
**Describe the bug**
It appears ARM64 is not properly supported, only ARM (32).

vcpkg_install_msbuild.script contains at line 114:
        elseif(VCPKG_TARGET_ARCHITECTURE STREQUAL ARM)
            set(_csc_PLATFORM  ARM)

it appears this should be:
        elseif(VCPKG_TARGET_ARCHITECTURE STREQUAL arm)
            set(_csc_PLATFORM  ARM)
        elseif(VCPKG_TARGET_ARCHITECTURE STREQUAL arm64)
            set(_csc_PLATFORM  ARM64)
it appears case makes a difference?

**Environment**
- OS: Win 10 x64 Pro 1903 18362.418
  Compiler: revision

**To Reproduce**
0.  Change portfile.cmake at line 11 to:
vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO libusb/libusb
    REF v1.0.23
    SHA512 9801a98f23b339946e11cd16256b06482a9d572e941b3875cd2b3ee00d1ea860a2bd421b4c94a0fc55b2ca0df8d62aa124c55c0b9096794df79c3fdb6da10b74
    HEAD_REF master
)
This pulls in the latest libusb which supports arm64 in the vcproj.

1. ./vcpkg install libusb:arm64-windows 
2. Unsupported target architecture
3. Patch vcpkg_install_msbuild.script as in the above and build:
C:\Users\qz3fwd\vcpkg>vcpkg install libusb:arm64-windows
The following packages will be built and installed:
    libusb[core]:arm64-windows
Starting package 1/1: libusb:arm64-windows
Building package libusb[core]:arm64-windows...
-- Using cached C:/Users/qz3fwd/vcpkg/downloads/libusb-libusb-v1.0.23.tar.gz
-- Using source at C:/Users/qz3fwd/vcpkg/buildtrees/libusb/src/v1.0.23-a350a0e3e1
-- Building msvc/libusb_dll_2017.vcxproj for Release
-- Building msvc/libusb_dll_2017.vcxproj for Debug
-- Installing: C:/Users/qz3fwd/vcpkg/packages/libusb_arm64-windows/share/libusb/copyright
-- Installing: C:/Users/qz3fwd/vcpkg/packages/libusb_arm64-windows/include/libusb-1.0/libusb.h
-- Up-to-date: C:/Users/qz3fwd/vcpkg/packages/libusb_arm64-windows/share/libusb/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package libusb[core]:arm64-windows... done
Installing package libusb[core]:arm64-windows...
Installing package libusb[core]:arm64-windows... done
Elapsed time for package libusb:arm64-windows: 16.43 s

Total elapsed time: 16.43 s
**Expected behavior**
Building package libusb[core]:arm64-windows... done
Installing package libusb[core]:arm64-windows...
Installing package libusb[core]:arm64-windows... done

**Failure logs** 
-(please attached failure logs)

**Additional context**
Seems like a fairly straightforward adjustment. Maybe I missed something being new to vcpkg/cmake/scripts

Thank you
Boyd

**Comment by PhoebeHui** [comment]
@qz3fwd, the PR has been merged, please get latest source and try again.
