### ISSUE TITLE
libusb update to >= v1.0.23

### ISSUE THREAD

**Issue by qz3fwd** [microsoft/vcpkg#8972]
Library name: libusb

New version number: v1.0.23

This is for ARM64 windows support.
Builds successfully for me as noted after modifying vcpkg_install_msbuild.script as noted in my other issue post. Please keep supporting ARM64 ports.

Thank you
Boyd

**Comment by PhoebeHui** [comment]
@qz3fwd, the PR has been merged, please get latest source and try again.
