### ISSUE TITLE
vcpkg cannot use the installed version of powershell

### ISSUE THREAD

**Issue by neko-para** [microsoft/vcpkg#8975]
**Describe the bug**
I have installed powershell v6.2.2 at the default location(C:\Program Files\Powershell\6). But vcpkg still report that it cannot find a suitable version of powershell. I've tried to link the pwsh.exe to powershell.exe, but it doesn't work either.

**Environment**
- OS: Windows 10 Home Edition x64
- Compiler: Visual Studio 2019

**To Reproduce**
1. ./vcpkg integrate install
or
1. ./vcpkg  install [any packages]
2. See error

**Expected behavior**
I hope vcpkg could locate the installed version of powershell so that it doesn't need to download one.

**Failure logs**
A suitable version of powershell-core was not found (required v6.2.1). Downloading portable powershell-core v6.2.1...
Downloading powershell-core...
  https://github.com/PowerShell/PowerShell/releases/download/v6.2.1/PowerShell-6.2.1-win-x86.zip -> C:\vcpkg\downloads\PowerShell-6.2.1-win-x86.zip
Extracting powershell-core...

**Additional context**
I removed the system preinstalled powershell v2.0 and move the path C:\Windows\System32\WindowsPowerShell under the powershell 6.0 install path.

**Comment by JackBoosY** [comment]
Hi @neko-para, thanks for reporting this issue.
Since vcpkg internally uses some version-related features of powershell, vcpkg now uses the internal version of powershell to replace the system powershell.

**Comment by neko-para** [comment]
Thanks

**Comment by patrikhuber** [comment]
A bit annoying that vcpkg can't use the system powershell, if its version is high enough. For example I've got 6.2.4-64, only for vcpkg to install its own local 6.2.1-32.......
