### ISSUE TITLE
freetype-gl POST_BUILD_CHECKS_FAILED failure on OS X

### ISSUE THREAD

**Issue by gundermanc** [microsoft/vcpkg#8981]
**Host Environment**
- OS: Mac OS X 10.15 Catalina
- Compiler: Apple Clang 11.0.0

**To Reproduce**
`./vcpkg install freetype-gl --triplet x64-osx`

**Failure logs** 
```
Error: Building package freetype-gl:x64-osx failed with: POST_BUILD_CHECKS_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: freetype-gl:x64-osx
  Vcpkg version: 2019.09.12-unknownhash
```

**Additional context**
Package appears to be building correctly but failing to copy the libs to the packages subtree because the portfile is [trying to copy all _*.lib_ files](https://github.com/microsoft/vcpkg/blob/master/ports/freetype-gl/portfile.cmake#L41-L50), and on Mac with my compiler, I'm getting _.a_ libraries.

**Comment by NancyLi1013** [comment]
Hi @gundermanc thanks for posting this issue.
This issue has been fixed now. Please update vcpkg and try it again.
