### ISSUE TITLE
build jemalloc failed with error "No such file or directory"

### ISSUE THREAD

**Issue by soft-way** [microsoft/vcpkg#8982]
**Describe the bug**
When I tried to install jemalloc It reported error in command output:
```
The following packages will be built and installed:
    jemalloc[core]:x86-windows
Starting package 1/1: jemalloc:x86-windows
Building package jemalloc[core]:x86-windows...
-- Using cached D:/vcpkg/downloads/jemalloc-jemalloc-cmake-jemalloc-cmake.4.3.1.tar.gz
-- Using source at D:/vcpkg/buildtrees/jemalloc/src/make.4.3.1-c0500eb0e6
-- Configuring x86-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: D:/Apps/CMake/bin/cmake.exe D:/vcpkg/buildtrees/jemalloc/src/make.4.3.1-c0500eb0e6 -DGIT_FOUND=OFF -DCMAKE_DISABLE_FIND_PACKAGE_Git=ON -Dwithout-export=OFF "-DCMAKE_MAKE_PROGRAM=C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" -DBUILD_SHARED_LIBS=ON -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=D:/vcpkg/scripts/toolchains/windows.cmake -DVCPKG_TARGET_TRIPLET=x86-windows -DVCPKG_SET_CHARSET_FLAG=ON -DVCPKG_PLATFORM_TOOLSET=v142 -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON -DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE -DCMAKE_VERBOSE_MAKEFILE=ON -DVCPKG_APPLOCAL_DEPS=OFF -DCMAKE_TOOLCHAIN_FILE=D:/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON -DVCPKG_CXX_FLAGS= -DVCPKG_CXX_FLAGS_RELEASE= -DVCPKG_CXX_FLAGS_DEBUG= -DVCPKG_C_FLAGS= -DVCPKG_C_FLAGS_RELEASE= -DVCPKG_C_FLAGS_DEBUG= -DVCPKG_CRT_LINKAGE=dynamic -DVCPKG_LINKER_FLAGS= -DVCPKG_TARGET_ARCHITECTURE=x86 -DCMAKE_INSTALL_LIBDIR:STRING=lib -DCMAKE_INSTALL_BINDIR:STRING=bin -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=D:/vcpkg/packages/jemalloc_x86-windows/debug
    Working Directory: D:/vcpkg/buildtrees/jemalloc/x86-windows-dbg
    Error code: 1
    See logs for more information:
      D:\vcpkg\buildtrees\jemalloc\config-x86-windows-dbg-out.log
      D:\vcpkg\buildtrees\jemalloc\config-x86-windows-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:305 (vcpkg_execute_required_process)
  ports/jemalloc/portfile.cmake:22 (vcpkg_configure_cmake)
  scripts/ports.cmake:94 (include)
```
I checkout the config-x86-windows-dbg-err.log. It said that below error:
CMake Error: Remove failed on file: D:/vcpkg/buildtrees/jemalloc/x86-windows-dbg/GetPageSize/CMakeFiles/CMakeTmp/cmTC_40595.exe: System Error: No such file or directory
But I can find the file:
 /cygdrive/d/vcpkg
$ find . |grep cmTC_40595
./buildtrees/jemalloc/x86-windows-dbg/GetPageSize/CMakeFiles/CMakeTmp/cmTC_40595.exe

**Environment**
- OS: [cygwin under Windows 10 Enterprise 1809]
- Compiler: VS 2019

**To Reproduce**
1.  ./vcpkg install jemalloc:x86-windows
2. See error in command line output and err log file

**Expected behavior**
Install is successful.

**Failure logs** 
-(please attached failure logs)
[
[config-x86-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/3834929/config-x86-windows-dbg-out.log)
[config-x86-windows-dbg-err.log](https://github.com/microsoft/vcpkg/files/3834932/config-x86-windows-dbg-err.log)

](url)
**Additional context**

**Comment by soft-way** [comment]
[
[CMakeError.log](https://github.com/microsoft/vcpkg/files/3834980/CMakeError.log)
[CMakeOutput.log](https://github.com/microsoft/vcpkg/files/3834981/CMakeOutput.log)

](url)

Add CMake output and error log

**Comment by JackBoosY** [comment]
In _SOURCE_PATH/include/jemalloc/internal/jemalloc_internal.h.in_ line 351:
```
#if __STDC_VERSION__ < 199901L
#  ifdef _MSC_VER
#    include <malloc.h>
#    define alloca _alloca
#  else
#    ifdef JEMALLOC_HAS_ALLOCA_H
#      include <alloca.h>
#    else
#      include <stdlib.h>
#    endif
#  endif
#  define VARIABLE_ARRAY(type, name, count) \
	type *name = alloca(sizeof(type) * (count))
#else
#  define VARIABLE_ARRAY(type, name, count) type name[(count)]
#endif
```
The `alloca.h` should not be included in Windows.

**Comment by soft-way** [comment]
yes, I installed latest cmake version 3.15.5

**Comment by LilyWangL** [comment]
Hi @soft-way, please install jemalloc again following these steps:

1. Uninstalling your cmake 3.15.5, vcpkg will use its own cmake.
2. Install jemalloc again.
3. If building failed, please use this file instead of the source file and install again.
4. Attach your build log.

Thanks.

The file: [Utilities.zip](https://github.com/microsoft/vcpkg/files/3839739/Utilities.zip)
The file path: vcpkg\buildtrees\jemalloc\src\make.4.3.1-c0500eb0e6\Utilities.cmake

**Comment by soft-way** [comment]
Hi @LilyWangL, If I used vcpkg's cmake-3.14.0, same issue happened.
It seems that anti-virus software McAfee resulted this error.
After checking the cmake code:

In cmCoreTryCompile.cxx: line 998 - 1015
#ifdef _WIN32
          // Sometimes anti-virus software hangs on to new files so we
          // cannot delete them immediately.  Try a few times.
          cmSystemTools::WindowsFileRetry retry =
            cmSystemTools::GetWindowsFileRetry();
          while (!cmSystemTools::RemoveFile(fullPath) && --retry.Count &&
                 cmSystemTools::FileExists(fullPath)) {
            cmSystemTools::Delay(retry.Delay);
          }
          if (retry.Count == 0)
#else
          if (!cmSystemTools::RemoveFile(fullPath))
#endif
          {
            std::string m = "Remove failed on file: " + fullPath;
            cmSystemTools::ReportLastSystemError(m.c_str());
          }
        }

In cmSystemTools.cxx: line 879-909
#ifdef _WIN32
cmSystemTools::WindowsFileRetry cmSystemTools::GetWindowsFileRetry()
{
  static WindowsFileRetry retry = { 0, 0 };
  if (!retry.Count) {
    unsigned int data[2] = { 0, 0 };
    HKEY const keys[2] = { HKEY_CURRENT_USER, HKEY_LOCAL_MACHINE };
    wchar_t const* const values[2] = { L"FilesystemRetryCount",
                                       L"FilesystemRetryDelay" };
    for (int k = 0; k < 2; ++k) {
      HKEY hKey;
      if (RegOpenKeyExW(keys[k], L"Software\\Kitware\\CMake\\Config", 0,
                        KEY_QUERY_VALUE, &hKey) == ERROR_SUCCESS) {
        for (int v = 0; v < 2; ++v) {
          DWORD dwData, dwType, dwSize = 4;
          if (!data[v] &&
              RegQueryValueExW(hKey, values[v], 0, &dwType, (BYTE*)&dwData,
                               &dwSize) == ERROR_SUCCESS &&
              dwType == REG_DWORD && dwSize == 4) {
            data[v] = static_cast<unsigned int>(dwData);
          }
        }
        RegCloseKey(hKey);
      }
    }
    retry.Count = data[0] ? data[0] : 5;
    retry.Delay = data[1] ? data[1] : 500;
  }
  return retry;
}
#endif_

cmake did several retry to delete file, retry.Count and retry.Delay was from register.
After I added below two items into Windows register. It does work.
Computer\HKEY_CURRENT_USER\Software\Kitware\CMake\Config\FilesystemRetryCount 10
Computer\HKEY_CURRENT_USER\Software\Kitware\CMake\Config\FilesystemRetryDelay 1000

Can we write down this kind of issue somewhere?
Thank you so much,

**Comment by PhoebeHui** [comment]
The anti-virus software also cause some unknown issues, we haven't encountered this issue again. I think it's good to have this issue and a possiable solution here, we can search this kind of issue with 'anti-virus' in vcpkg, instead of adding a docs to vcpkg.
