### ISSUE TITLE
How to install the old version of the library

### ISSUE THREAD

**Issue by dzz10** [microsoft/vcpkg#8983]
How do I install the old version of the library?

For example: tesseract3.0.5 tesseract4.1.0.

I want to use 3.0.5, which was available before, but it has been updated to 4.1.0 recently.

**Comment by drescherjm** [comment]
You can do this with your own port overlay and duplicating the old port.

**Comment by NancyLi1013** [comment]
Hi @dzz10 thanks for posting this issue. 
Currently vcpkg doesn't support several versions of one library. The similar issue is here #1681.
@drescherjm thanks for your above comments.

**Comment by dzz10** [comment]
@NancyLi1013 @drescherjm thanks

Hope you can support it in the future
