### ISSUE TITLE
[tesseract] Master Build Failed

### ISSUE THREAD

**Issue by zhao-lun** [microsoft/vcpkg#8991]
Hi, im trying to build the latest master branch of Tesseract. However, it didnt go smoothly. 

Package: tesseract:x64-windows-static
VCPKG version: 2019.09.12-nohash

Thing i did
1) Added line in tesseract/portfile.cmake
`HEAD_REF master` at 
vcpkg_from_github
`vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO tesseract-ocr/tesseract
    REF 4.1.0
    SHA512 d617f5c5b826640b2871dbe3d7973bcc5e66fafd837921a20e009d683806ed50f0f258aa455019d99fc54f5cb65c2fa0380e3a3c92b39ab0684b8799c730b09d
	HEAD_REF master
    PATCHES
        fix-tiff-linkage.patch
        fix-text2image.patch
)`
2) Build Command line 
vcpkg install tesseract:x64-windows-static --head

Error 
`-- Purging cached C:/vcpkg/downloads/tesseract-ocr-tesseract-master.tar.gz to fetch latest (use --no-downloads to suppress)
-- Downloading https://api.github.com/repos/tesseract-ocr/tesseract/git/refs/heads/master...
-- Skipping hash check for C:/vcpkg/downloads/temp/tesseract-ocr-tesseract-master.tar.gz.version.
-- Downloading https://github.com/tesseract-ocr/tesseract/archive/master.tar.gz...
-- Skipping hash check for C:/vcpkg/downloads/temp/tesseract-ocr-tesseract-master.tar.gz.
-- Extracting source C:/vcpkg/downloads/tesseract-ocr-tesseract-master.tar.gz
-- Using source at C:/vcpkg/buildtrees/tesseract/src/head/master-56a84ac15a
-- Configuring x64-windows-static
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: ninja -v
    Working Directory: C:/vcpkg/buildtrees/tesseract/x64-windows-static-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\vcpkg\buildtrees\tesseract\config-x64-windows-static-out.log`

From the Log file (buildtrees\tesseract\config-x64-windows-static-out.llog)
I found out the error was related to 
`CMake Error at C:/vcpkg/scripts/buildsystems/vcpkg.cmake:263 (_find_package):
  By not providing "FindSW.cmake" in CMAKE_MODULE_PATH this project has asked
  CMake to find a package configuration file provided by "SW", but CMake did
  not find one.`

Any clue?

**Comment by NancyLi1013** [comment]
Hi @zhao-lun thanks for posting this issue. 
I noticed that the source code from latest master branch needs to depend on `SW `to build. 
`SW `is not available in vcpkg now.
Maybe you can try to set `SW_BUILD `as `OFF` now and then built it again.

**Comment by zhao-lun** [comment]
Hi @NancyLi1013 , 
I noticed there're something missing from the build. I'll look on that.
Thank you.
