### ISSUE TITLE
[New Port Request] <opencascade>

### ISSUE THREAD

**Issue by silentmissile** [microsoft/vcpkg#8994]
Library name: opencascade

Library description: a CAD geometry kernel library

Source repository URL: https://git.dev.opencascade.org/gitweb/?p=occt.git;a=snapshot;h=fd47711d682be943f0e0a13d1fb54911b0499c31;sf=zip

Project homepage (if different from the source repository): https://www.opencascade.com/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

opencascade has some dependencies

    ffmpeg
    freeimage
    freetype
    tcl/tk
    vtk
    qt5-base

**Comment by traversaro** [comment]
Related issue: https://github.com/microsoft/vcpkg/issues/4968 .

**Comment by traversaro** [comment]
Related issue: https://github.com/microsoft/vcpkg/issues/4968 .

**Comment by NancyLi1013** [comment]
Hi @silentmissile thanks for posting this request.
It's duplicated with #4968. Let's track this issue here.
@traversaro thanks for your info.
