### ISSUE TITLE
[New Port Request] <open scene graph>

### ISSUE THREAD

**Issue by silentmissile** [microsoft/vcpkg#8995]
Library name: OpenSceneGraph

Library description: The OpenSceneGraph is an open source high performance 3D graphics toolkit, used by application developers in fields such as visual simulation, games, virtual reality, scientific visualization and modelling

Source repository URL: https://github.com/openscenegraph/OpenSceneGraph/tree/OpenSceneGraph-3.6.4

Project homepage (if different from the source repository): http://www.openscenegraph.org/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by silentmissile** [comment]
sorry, my fault, it's already included.

**Comment by giantdig** [comment]
> sorry, my fault, it's already included.

I do not find it …

**Comment by giantdig** [comment]
> > sorry, my fault, it's already included.
> 
> I do not find it …

I find it, it called osg, not openscenegraph.
