### ISSUE TITLE
Make OSX vcpkg binary self-contained

### ISSUE THREAD

**Issue by jherico** [microsoft/vcpkg#8999]
****

**Is your feature request related to a problem? Please describe.**
OK, strap in.  In ym use case I need to be able to run `vcpkg` on Mac-based CI machines running OSX 10.14 and XCode 10.x.  These systems _do not_ have any recent version of gcc on them either.  

As such I can't bootstrap `vcpkg` on the target systems, since it's currently impossible to bootstrap using any version of XCode less than 11 and targeting any version of OSX less than 10.15 (if you're using XCode to build)

I get around similar issues with bootstrapping on other platforms by building a binary manually and uploading it to S3.  However, when I tried to do this using an OSX 10.14 machine and gcc9 from homebrew, the resulting binary wouldn't run on the target machine because it was trying to use a shared version of `libstdc++`.  

I eventually was able to work around this by adding the following line to the `toolsrc/CMakeLists.txt`

    link_libraries(-static-libgcc -static-libstdc++)

This forced static linkage to the C++ runtime, which made the binary completely portable.

**Proposed solution**
Prefer static linkage to the C++ runtime for the vcpkg binary, especially if building with gcc on OSX

**Describe alternatives you've considered**
Alternatively, much as I hate to say it, the reliance on the `<filesystem>` API is a huge pain in the ass because it's poorly supported on XCode versions < 11 and OSX versions < 10.15.  Perhaps consider adding `#ifdef` logic to either use api-compatible wrappers on OSX or simply revert to using older filesystem interaction APIs until the ecosystem is more homogenous in supporting `<filesystem>`

**Comment by NancyLi1013** [comment]
Hi @jherico 
Thanks for posting this issue.
I noticed there are many changes about this in current master branch.

Could you please update vcpkg to the latest version and try it again? Please help confirm if it can work for you now?

**Comment by Farwaykorse** [comment]
Just tried it a few days ago, using the environment variable `MACOSX_DEPLOYMENT_TARGET=10.12`  
*Building with Xcode*  
On MacOS 10.15 with Xcode 12.0  ([test on TravisCI](https://travis-ci.com/github/Farwaykorse/fwkSudoku/jobs/387172285#L210))
It seems the filesystem api on 10.15 does not support older MacOS releases. (It works fine if you only deploy to MacOS 10.15.)  
*Building with GCC*  
jherico's solution for using GCC with static libraries I can still build vcpkg (on MacOSX 10.14, with Xcode 10.3 and GCC-9) and deploy it to OSX 10.12 to 10.15.
Without manually setting `-static-libgcc -static-libstdc++` vcpkg cannot be deployed to different MacOS versions. ([test](https://travis-ci.com/github/Farwaykorse/fwkSudoku/jobs/388984705#L338))

My conclusion, the situation has not changed.

**Comment by JackBoosY** [comment]
Related: https://github.com/microsoft/vcpkg/discussions/17794.

**Comment by JackBoosY** [comment]
Ping @strega-nil-ms for response.

**Comment by strega-nil-ms** [comment]
We are doing work on this, but it hasn't come to completion yet. Pre-10.15, we expect that people will set up their compilers to do the right thing. We don't ship binaries on macOS for this exact reason.

**Comment by JackBoosY** [comment]
I confirmed we published osx vcpkg binary now.
