### ISSUE TITLE
macOS Catalina Qt Latest

### ISSUE THREAD

**Issue by sbrown89** [microsoft/vcpkg#9000]
**Describe the bug**
When running ./vcpkg --triplet x64-osx install qt5[latest] or ./vcpkg --triplet x64-osx install qt5-base[latest] i get the following error: zsh: no matches found: qt5[latest]

When i run ./vcpkg --triplet x64-osx install qt5 it starts compiling qt 5.9 not LTS 5.12.5 as it states in search. The control file under ports -> qt5 states LTS is 5.12.5 and [latest] is 5.13.1.

**Environment**
- OS: macOS Catalina 10.15.1
- Compiler: AppleClang 11.0.0.11000033

**To Reproduce**
1. /vcpkg --triplet x64-osx install qt5[latest] or ./vcpkg --triplet x64-osx install qt5-base[latest]
2. zsh: no matches found: qt5[latest]

Tried latest release as well as master branch and same issue.

**Comment by TheScarfix** [comment]
@sbrown89 zsh interprets the [ and ] as special characters, you either need to escape them or write it as a string like "qt[latest]"

**Comment by sbrown89** [comment]
Shoot! ... not used to the new zsh shell yet .. that fixed it .. stupid me. Thanks!
