### ISSUE TITLE
[gtk] Error: Building package libepoxy:x86-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by Pagana0709** [microsoft/vcpkg#9005]
### Describe the bug
I can't install gtk, error compiling libepoxy for x86

### Steps to reproduce
I tried to follow the installation guide for gtk in windows:
[https://www.gtk.org/download/windows.php](https://www.gtk.org/download/windows.php)

Instead of this:

    vcpkg install gtk:x64-windows

I execute this in console:

    vcpkg install gtk:x86-windows

Because my system is x86, not x64.

Download is fine, when vcpkg is compiling dependencies
that error appears.

### Environment
- OS: Windows 7 Starter (x86)
- Compiler: Visual Studio 2017 community edition

### Extra info:
I installed visual studio with the following command for an online process from [https://docs.microsoft.com/en-us/visualstudio/install/create-an-offline-installation-of-visual-studio?view=vs-2017](https://docs.microsoft.com/en-us/visualstudio/install/create-an-offline-installation-of-visual-studio?view=vs-2017) (with c++ components only):
`vs_community__1004384057.1573466675.exe --layout C:\Users\MyUser\Desktop\vs2017tmp --add Microsoft.VisualStudio.Workload.NativeDesktop --includeRecommended --lang en-US`

### Failure logs:
*From console*

    Q:\vcpkg>vcpkg install gtk:x86-windows
    The following packages will be built and installed:
      * atk[core]:x86-windows
      * bzip2[core]:x86-windows
      * cairo[core]:x86-windows
      * dirent[core]:x86-windows
      * expat[core]:x86-windows
      * fontconfig[core]:x86-windows
      * freetype[core]:x86-windows
      * gdk-pixbuf[core]:x86-windows
      * gettext[core]:x86-windows
      * glib[core]:x86-windows
        gtk[core]:x86-windows
      * harfbuzz[core,glib,ucdn]:x86-windows
      * libepoxy[core]:x86-windows
      * libffi[core]:x86-windows
      * libiconv[core]:x86-windows
      * libpng[core]:x86-windows
      * pango[core]:x86-windows
      * pcre[core]:x86-windows
      * pixman[core]:x86-windows
      * ragel[core]:x86-windows
      * zlib[core]:x86-windows
    Additional packages (*) will be modified to complete this operation.
    Starting package 1/21: libepoxy:x86-windows
    Building package libepoxy[core]:x86-windows...
    -- Using cached Q:/vcpkg/downloads/anholt-libepoxy-1.5.3.tar.gz
    -- Extracting source Q:/vcpkg/downloads/anholt-libepoxy-1.5.3.tar.gz
    -- Using source at Q:/vcpkg/buildtrees/libepoxy/src/1.5.3-d7b9d32fcb
    -- Configuring x86-windows-rel
    CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
        Command failed: Q:/vcpkg/downloads/tools/python/python-3.7.3/python.exe Q:/v
    cpkg/downloads/tools/meson/meson-0.52.0/meson.py -Denable-glx=no -Denable-egl=no
     -Dcmake_prefix_path=Q:/vcpkg/installed/x86-windows --buildtype plain --backend
    ninja --wrap-mode nodownload --default-library shared --prefix Q:/vcpkg/packages
    /libepoxy_x86-windows Q:/vcpkg/buildtrees/libepoxy/src/1.5.3-d7b9d32fcb
        Working Directory: Q:/vcpkg/buildtrees/libepoxy/x86-windows-rel
        Error code: 2
        See logs for more information:
          Q:\vcpkg\buildtrees\libepoxy\config-x86-windows-rel-out.log
          Q:\vcpkg\buildtrees\libepoxy\config-x86-windows-rel-err.log
    
    Call Stack (most recent call first):
      scripts/cmake/vcpkg_configure_meson.cmake:58 (vcpkg_execute_required_process)
      ports/libepoxy/portfile.cmake:14 (vcpkg_configure_meson)
      scripts/ports.cmake:94 (include)
    
    
    Error: Building package libepoxy:x86-windows failed with: BUILD_FAILED
    Please ensure you're using the latest portfiles with `.\vcpkg update`, then
    submit an issue at https://github.com/Microsoft/vcpkg/issues including:
      Package: libepoxy:x86-windows
      Vcpkg version: 2019.09.12-nohash
    
    Additionally, attach any relevant sections from the log files above.

*Q:\vcpkg\buildtrees\libepoxy\config-x86-windows-rel-err.log*

    Traceback (most recent call last):
      File "Q:\vcpkg\downloads\tools\meson\meson-0.52.0\mesonbuild\mesonmain.py", line 129, in run
        return options.run_func(options)
      File "Q:\vcpkg\downloads\tools\meson\meson-0.52.0\mesonbuild\msetup.py", line 245, in run
        app.generate()
      File "Q:\vcpkg\downloads\tools\meson\meson-0.52.0\mesonbuild\msetup.py", line 159, in generate
        self._generate(env)
      File "Q:\vcpkg\downloads\tools\meson\meson-0.52.0\mesonbuild\msetup.py", line 215, in _generate
        intr.backend.generate(intr)
      File "Q:\vcpkg\downloads\tools\meson\meson-0.52.0\mesonbuild\backend\ninjabackend.py", line 288, in generate
        self.ninja_command = environment.detect_ninja(log=True)
      File "Q:\vcpkg\downloads\tools\meson\meson-0.52.0\mesonbuild\environment.py", line 146, in detect_ninja
        p, found = Popen_safe([n, '--version'])[0:2]
      File "Q:\vcpkg\downloads\tools\meson\meson-0.52.0\mesonbuild\mesonlib.py", line 1061, in Popen_safe
        return Popen_safe_legacy(args, write=write, stdout=stdout, stderr=stderr, **kwargs)
      File "Q:\vcpkg\downloads\tools\meson\meson-0.52.0\mesonbuild\mesonlib.py", line 1072, in Popen_safe_legacy
        stdout=stdout, stderr=stderr, **kwargs)
      File "D:\obj\Windows-Release\37win32_Release\msi_python\zip_win32\subprocess.py", line 775, in __init__
      File "D:\obj\Windows-Release\37win32_Release\msi_python\zip_win32\subprocess.py", line 1178, in _execute_child
    OSError: [WinError 216] This version of %1 is not compatible with the version of Windows you're running. Check your computer's system information to see whether you need a x86 (32-bit) or x64 (64-bit) version of the program, and then contact the software publisher

*Q:\vcpkg\buildtrees\libepoxy\config-x86-windows-rel-out.log*

    The Meson build system
    Version: 0.52.0
    Source dir: Q:\vcpkg\buildtrees\libepoxy\src\1.5.3-d7b9d32fcb
    Build dir: Q:\vcpkg\buildtrees\libepoxy\x86-windows-rel
    Build type: native build
    WARNING: Unknown options: "enable-egl, enable-glx"
    Project name: libepoxy
    Project version: 1.5.3
    Appending CFLAGS from environment: ' /DWIN32 /D_WINDOWS /W3 /utf-8  /MD /O2 /Gy /DNDEBUG /Z7'
    Appending LDFLAGS from environment: ['/DEBUG', '/INCREMENTAL:NO', '/OPT:REF', '/OPT:ICF']
    Appending CPPFLAGS from environment: ' '
    Appending CFLAGS from environment: ' /DWIN32 /D_WINDOWS /W3 /utf-8  /MD /O2 /Gy /DNDEBUG /Z7'
    Appending LDFLAGS from environment: ['/DEBUG', '/INCREMENTAL:NO', '/OPT:REF', '/OPT:ICF']
    Appending CPPFLAGS from environment: ' '
    C compiler for the host machine: cl (msvc 19.16.27034)
    C linker for the host machine: link 19.16.27034
    Host machine cpu family: x86
    Host machine cpu: x86
    Has header "KHR/khrplatform.h" : NO 
    Compiler for C supports arguments -we4002: YES 
    Compiler for C supports arguments -we4003: YES 
    Compiler for C supports arguments -w14010: YES 
    Compiler for C supports arguments -we4013: YES 
    Compiler for C supports arguments -w14016: YES 
    Compiler for C supports arguments -we4020: YES 
    Compiler for C supports arguments -we4021: YES 
    Compiler for C supports arguments -we4027: YES 
    Compiler for C supports arguments -we4029: YES 
    Compiler for C supports arguments -we4033: YES 
    Compiler for C supports arguments -we4035: YES 
    Compiler for C supports arguments -we4045: YES 
    Compiler for C supports arguments -we4047: YES 
    Compiler for C supports arguments -we4049: YES 
    Compiler for C supports arguments -we4053: YES 
    Compiler for C supports arguments -we4071: YES 
    Compiler for C supports arguments -we4819: YES 
    Library dl found: NO
    Did not find pkg-config by name 'pkg-config'
    Found Pkg-config: NO
    Run-time dependency gl found: YES 
    Found CMake: C:\Program Files\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.EXE (3.12.18081601-MSVC_2)
    Run-time dependency egl found: NO (tried pkgconfig and cmake)
    Run-time dependency x11 found: NO (tried pkgconfig and cmake)
    Run-time dependency glesv2 found: NO (tried pkgconfig and cmake)
    Library libGLESv2 found: NO
    Run-time dependency glesv1_cm found: NO (tried pkgconfig and cmake)
    Library libGLESv1_CM found: NO
    Library opengl32 found: YES
    Library gdi32 found: YES
    DEPRECATION: Project targetting '>= 0.47.0' but tried to use feature deprecated since '0.48.0': python3 module
    Configuring config.h using configuration
    Library dl found: NO
    Checking for function "dlvsym" with dependency -ldl: NO 
    Build targets in project: 13
    WARNING: Deprecated features used:
     * 0.48.0: {'python3 module'}
    Option buildtype is: plain [default: debugoptimized]

*Q:\vcpkg\buildtrees\libepoxy\x86-windows.vcpkg_abi_info.txt*

    tool-meson 1f27fe1fbc681a853d74ed02a7de05d674d54921
    portfile.cmake 0330984f8f19e30d496dc7b2c844300da11f38a1
    CONTROL 89722f6aa8265b32cd146ee6ae72933c00fb2a8b
    cmake 3.14.0
    powershell ab1effc926b000a6adc12198a1886514ec203621a53b0cd7ec1cd9a8225dccda7e857feaabcfba4004bea73129b986abaad777c4573f44e0af70411226ce08b0
    vcpkg_fixup_cmake_targets 0ddb96472da00d45d10e0b0bf037bfb744164d0a
    triplet e8dc96fd479b53bb0e6748625827c8268017e35a
    features core

**Comment by JackBoosY** [comment]
Hi @Pagana0709, thanks for reporting this issue!
It seems that the use of x64 programs during the build process has caused this issue.

**Comment by Pagana0709** [comment]
> 
> 
> Hi @Pagana0709, thanks for reporting this issue!
> It seems that the use of x64 programs during the build process has caused this issue.

Oh yes, I noticed, but this is the first time I use vcpkg and I don't know how to fix it manually.

**Comment by JackBoosY** [comment]
@Pagana0709 I don't know which program to use is x64 type, I think the best solution is to use x64 Windows, after all, x86 Windows has memory limit.

**Comment by Pagana0709** [comment]
> 
> 
> @Pagana0709 I don't know which program to use is x64 type, I think the best solution is to use x64 Windows, after all, x86 Windows has memory limit.

With gtk-x64 can I create x86-compatible executables?

**Comment by JackBoosY** [comment]
@Pagana0709 Sure, you can build x86 gtk using `./vcpkg install gtk:x86-windows`.

**Comment by Pagana0709** [comment]
Hey man, I found the bug.

Seems that the problem comes from the visual studio itself which is the one that brings x64 ninja, not vcpkg. I copied ninja from `C:\Program Files\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja` to my `desktop` folder, I run it and shows that same as in the logs:

![IMG-3](https://user-images.githubusercontent.com/14947289/68919981-770b9700-0739-11ea-9466-063c58fb99b3.png)

This is one solution:

- You must download the ninja code from [https://github.com/ninja-build/ninja](https://github.com/ninja-build/ninja)
- Then compile it this [way](https://github.com/ninja-build/ninja/issues/1285)
- And at the end copy compiled file to `C:\Program Files\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja`
