### ISSUE TITLE
alut

### ISSUE THREAD

**Issue by GPn-G** [microsoft/vcpkg#9009]
Library name:
alut

Library description:
  A Haskell binding for the OpenAL Utility Toolkit, which makes managing of OpenAL contexts, loading sounds in various formats and creating waveforms very easy. You can find the required ALUT library e.g. here on GitHub.
Source repository URL:
https://github.com/vancegroup/freealut.git

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by JackBoosY** [comment]
@GPn-G Is this port a C/C++ library? How to build it?

**Comment by GPn-G** [comment]
> @GPn-G Is this port a C/C++ library? How to build it?

yes, it is C++. The build method is according to this website https://github.com/vancegroup/freealut/blob/master/README

**Comment by NancyLi1013** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
