### ISSUE TITLE
How do I just download source packages?

### ISSUE THREAD

**Issue by neko-para** [microsoft/vcpkg#9015]
I want to download all the source packages needed by a certain target before build them for network reasons. Is there a possible way to do so?

**Comment by JackBoosY** [comment]
We did not provide the `download` command, you can run `install` command, get the download url and just cancel build process.

**Comment by neko-para** [comment]
But if you don't build the base package, vcpkg won't try to download the package depending on it.
eg. If I want qscintilla, I have to build qt5-base first, or it just trying to do so, but not show the download url of qscintilla.

**Comment by timautry** [comment]
You may want to try .\vcpkg.exe install <package> <package> <etc> --only-downloads
It will download the package and extract it to the buildtree and any dependent packages...

**Comment by heydojo** [comment]
I cannot recommend using vcpkg without a net connection capable of downloading the archives in good time. Qt is an especially good example of a port which you really, really need a working net connection to build.

I will also say that if you do not have a choice about the availability or speed of the net connection, that you should find a friend or family member who can allow you the bandwidth you need and politely ask to use their connection to build everything you need in one go (then make a copy of vcpkg's downloads folder for when you are offline.) This assumes that you have a laptop or other Linux, Windows or OSX portable device.

**Comment by neko-para** [comment]
In fact, the reason why I don't want to build them is that when I'm using a free wifi, my computer is not charge. when my computer is charged, the network is not free. And building package consumes electricities rapidly.
