### ISSUE TITLE
 pugixml build failure

### ISSUE THREAD

**Issue by syeap** [microsoft/vcpkg#9017]
**Host Environment**
- OS: Windows 10 Enterprise Version 1809 Build 17763.805

**To Reproduce**
`./vcpkg install pugixml`

**Failure logs** 
The following packages will be built and installed:
    pugixml[core]:x86-windows
Starting package 1/1: pugixml:x86-windows
Building package pugixml[core]:x86-windows...
-- Downloading https://github.com/zeux/pugixml/archive/v1.10.tar.gz...
-- Downloading https://github.com/zeux/pugixml/archive/v1.10.tar.gz... Failed. Status: 7;"Couldn't connect to server"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:175 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_github.cmake:108 (vcpkg_download_distfile)
  ports/pugixml/portfile.cmake:3 (vcpkg_from_github)
  scripts/ports.cmake:94 (include)

Error: Building package pugixml:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: pugixml:x86-windows
  Vcpkg version: 2019.09.12-nohash

**Additional context**
Tried all the following:
- `\.vcpkg update`
- setting HTTP/HTTPS_PROXY env

Directly downloading the tar from a browser works just fine.
https://github.com/zeux/pugixml/archive/v1.10.tar.gz

**Comment by ehsan-mohammadi** [comment]
@syeap I tried to install `pugixml` and it successfully installed. Make sure that you don't use any proxy and then try to reinstall it. Also, make sure that you have the latest version of vcpkg.

**Comment by syeap** [comment]
Thanks @ehsan-mohammadi ! Your reply prompted me to hunt down the proxy issue.

Tried a couple of things. And it finally worked.

What finally worked for me was:
- Launch a cmd as Admin
- set HTTP/HTTPS_PROXY and NO_PROXY env

I was use PowerShell previously. And did not realize that I couldn't do a "set" env in there.
