### ISSUE TITLE
CMake not correctly finding the configuration package

### ISSUE THREAD

**Issue by SeanOMik** [microsoft/vcpkg#9018]
**Describe the bug**
cmake find-package is not correctly finding the nlohmann_json package installed from vcpkg

**Environment**
- OS: Windows
- Compiler: Not sure, when using CMake, I get this info: `Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.23.28105/bin/Hostx64/x64/cl.exe`

**To Reproduce**
1. Run `vcpkg install nlohmann-json`
      -  It gets installed in `vcpkg\packages\nlohmann-json_x86-windows\share` with two different 
         folders.
            - `nlohmann-json` only has two files, `copyright` and `vcpkg_abi_info.txt`
            - `nlohmann_json` has a few cmake files and `nlohmann_json.natvis` file
                  - `nlohmann_jsonConfig.cmake`
                  - `nlohmann_jsonConfigVersion.cmake`
                  - `nlohmann_jsonTargets.cmake`
2. Use find_package in a CMakeLists.txt file
```find_package(nlohmann_json CONFIG REQUIRED)```

**Expected behavior**
CMake finds nlohmann-json

**Failure logs** 
```
CMake Error at C:/Users/se1028304/Desktop/messingAround/vcpkg/scripts/buildsystems/vcpkg.cmake:263 (_find_package):
  Could not find a configuration file for package "nlohmann_json" that is
  compatible with requested version "".

  The following configuration files were considered but not accepted:

    C:/Users/se1028304/Desktop/messingAround/vcpkg/installed/x86-windows/share/nlohmann_json/nlohmann_jsonConfig.cmake, version: 3.7.0 (32bit)

Call Stack (most recent call first):
  CMakeLists.txt:19 (find_package)```

**Comment by heydojo** [comment]
Hi @SeanOMik are you performing a generator step using cmake? If so, I imagine that you need to pass something like `-Dnlohmann_json:PATH="vcpkg\packages\nlohmann-json_x86-windows\share\nlohmann-json"` to it.
You listed the same folder twice (nlohmann-json) in your comment but also said that there were two different folders. So I may have added the incorrect path to the variable. You likely want the nlohmann_json variable to point to the directory where the nlohmann_jsonConfig.cmake file is.

If you are not calling cmake from the command line and are instead using vcpkg to create a port which builds something against nlohmann-json then you can take a look at the existing ports to see examples of how to add it's path to the build environment.
Often, simply adding the package to the CONTROL file isn't enough.

Using [AstroGrep](https://www.majorgeeks.com/files/details/astrogrep.html) (if you are on Windows - or just grep anywhere else) to search for `set(ENV` on the vcpkg ports folder within the vcpkg tree will show plenty of examples.

```
vcpkg_find_acquire_program(PYTHON3)
get_filename_component(PYTHON3_DIR "${PYTHON3}" DIRECTORY)
set(ENV{PATH} "$ENV{PATH};${PYTHON3_DIR}")
```
Will add the special tool the python3 executable and it's path to the vcpkg build environment when building a vcpkg port, for example.

**Comment by NancyLi1013** [comment]
Hi @SeanOMik  thanks for posting this request.
I can not reproduce this issue on my local.
Could you help provide your complete configure log and your `CMakelists.txt` file?

Thanks.

**Comment by NancyLi1013** [comment]
Please feel free to reopen this issue if it is still a problem for you.

**Comment by vpaladino778** [comment]
Hello, i was able to reproduce this issue in a minimal example. I'll create a new issue and link to it here

**Comment by anttijuu** [comment]
**Doesn't work** if done like this from nlohmann::json directory:
```
cmake -DCMAKE_INSTALL_PREFIX=C:\bin ..
cmake --build . --target install
```
And then this fails from application directory:

```
cmake -DCMAKE_PREFIX_PATH=C:\bin ..
```

Resulting in errors that nlohmann_json was found but could not be used:

> CMake Error at CMakeLists.txt:30 (find_package):
  Could not find a configuration file for package "nlohmann_json" that is
  compatible with requested version "3.7.0".
>  The following configuration files were considered but not accepted:
>    C:/bin/lib/cmake/nlohmann_json/nlohmann_jsonConfig.cmake, version: 3.7.3 (64bit)

**However**, when using Ninja build, everything is OK -- first the nlohmann::json:

```
cmake -GNinja -DCMAKE_INSTALL_PREFIX=C:\bin ..
ninja
ninja install
```
And then building the app using Ninja:

```
cmake -GNinja -DCMAKE_PREFIX_PATH=C:\bin ..
ninja
```
With no errors.
