### ISSUE TITLE
[New Port Request] Gloox, Glooxd

### ISSUE THREAD

**Issue by nathan130200** [microsoft/vcpkg#9020]
Library name: Gloox, Glooxd

Library description: XMPP client, component, and server library.

Source repository URL: 
- Gloox: svn://svn.camaya.net/gloox/trunk 
- Glooxd: svn://svn.camaya.net/glooxd/trunk

Project homepage (if different from the source repository): https://camaya.net/

Dependencies required
- OpenSSL
- LibIDN
- Zlib

**Comment by NancyLi1013** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.

**Comment by nathan130200** [comment]
I tried to port, but i don't have enough knowledge for porting c++ library in vcpkg

**Comment by NancyLi1013** [comment]
@nathan130200 
Thanks for your update. 
This [doc ](https://github.com/microsoft/vcpkg/blob/master/docs/examples/packaging-github-repos.md) might help you some. Or you can read these docs [here](https://github.com/microsoft/vcpkg/tree/master/docs) and refer to other ports.

We can’t reopen this issue until a PR is opened, unfortunately; consider making a pull request!
