### ISSUE TITLE
vcpkg does not really build VTK Qt 

### ISSUE THREAD

**Issue by ArtemKotovsky** [microsoft/vcpkg#9023]
command: vcpkg install vtk[qt]:x64-windows 
env: Visual Studion 2017, build x64, Windows 10 x64, the latest vcpkg installed from scratch (13 Nov 2017 )

vcpkg installs vtk without errors, however, include, lib, bin folders do not have VTK Qt files
Really vcpkg has required sources in the port folder but does not build them (does not build VTK Qt folder)

**Comment by drescherjm** [comment]
There is a feature flag to enable that

**Comment by ArtemKotovsky** [comment]
I used `vcpkg install vtk[qt]:x64-windows`
could you please explain?

**Comment by drescherjm** [comment]
Sorry for the confusion, that is the correct feature flag. I deleted my comment

**Comment by JackBoosY** [comment]
Confirmed.

**Comment by jsutes** [comment]
I am also experiencing this issue after getting the latest vcpkg and upgrading.  I saw the message about variable VTK_WITH_QT not being used by the project, but I didn't notice any other red flags.

**Comment by Neumann-A** [comment]
@JackBoosY real reason is that `vcpkg_check_features` is currently broken and not working as intended

**Comment by JackBoosY** [comment]
@Neumann-A Thanks, I'll take a look.

**Comment by JackBoosY** [comment]
@aditya369007 See #9778.

**Comment by aditya369007** [comment]
Thank you. Will check it out.

**Comment by Andyjk1406** [comment]
This QT/VTK problem seems to still exist. I tried adding set(VTK_WITH_QT ON) in the portfile but no luck. None of the QVTKWidgets are built.
I'm happy to download and build VTK with QT separately (outside of vcpkg), but is there then a neat way to use vcpkg for Pointcloudlibrary (PCL), without vcpkg then building VTK again as a dependency? Thanks

**Comment by soroush-rabiei** [comment]
I am having same issue. QVTKOpenGLWidget.h is not found, though vcpkg reports vtk[qt] installed. Any workaround before merge?

**Comment by Andyjk1406** [comment]
This seems like a difficult issue to solve.
My workaround was to build a second identical version of VTK (using cmake and visual studio) from the identical source in the vcpkg repo.
Then just manually point my project to the qvtk widgets built in my non-vcpkg build of VTK, while using the the vcpkg build of VTK for everything else. This seems to work.
