### ISSUE TITLE
libbson:x86-uwp & x64-uwp. Build failed

### ISSUE THREAD

**Issue by AJIOB** [Microsoft/vcpkg#903]
I want to build mongo-cxx-driver for uwp. When I try this, I get this error:

    -- CURRENT_INSTALLED_DIR=D:/Alex/Documents/SourceTree/vcpkg/installed/x86-uwp
    -- DOWNLOADS=D:/Alex/Documents/SourceTree/vcpkg/downloads
    -- CURRENT_PACKAGES_DIR=D:/Alex/Documents/SourceTree/vcpkg/packages/libbson_x86-uwp
    -- CURRENT_BUILDTREES_DIR=D:/Alex/Documents/SourceTree/vcpkg/buildtrees/libbson
    -- CURRENT_PORT_DIR=D:/Alex/Documents/SourceTree/vcpkg/ports/libbson/.
    -- Using cached D:/Alex/Documents/SourceTree/vcpkg/downloads/libbson-1.5.1.tar.gz
    -- Testing integrity of cached file...
    -- Testing integrity of cached file... OK
    -- Extracting done
    -- Configuring x86-uwp-rel
    -- Configuring x86-uwp-rel done
    -- Configuring x86-uwp-dbg
    -- Configuring x86-uwp-dbg done
    -- Package x86-uwp-rel
    CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:14 (message):
        Command failed: D:/Program Files/CMake/bin/cmake.exe;--build;.;--config;Release;--target;install;--;/p:VCPkgLocalAppDataDisabled=true;/p:UseIntelMKL=No;/m
        Working Directory: D:/Alex/Documents/SourceTree/vcpkg/buildtrees/libbson/x86-uwp-rel
        See logs for more information:
        D:\Alex\Documents\SourceTree\vcpkg\buildtrees\libbson\package-x86-uwp-rel-out.log
        D:\Alex\Documents\SourceTree\vcpkg\buildtrees\libbson\package-x86-uwp-rel-err.log

    Call Stack (most recent call first):
    scripts/cmake/vcpkg_install_cmake.cmake:27 (vcpkg_execute_required_process)
    ports/libbson/portfile.cmake:17 (vcpkg_install_cmake)
    scripts/ports.cmake:73 (include)

    Error: Building package libbson:x86-uwp failed with: BUILD_FAILED
    Please ensure you're using the latest portfiles with `.\vcpkg update`, then
    submit an issue at https://github.com/Microsoft/vcpkg/issues including:
    Package: libbson:x86-uwp
    Vcpkg version: 0.0.78-db73e73c562a00228dd8c01ee2a03f03012023fc

    Additionally, attach any relevant sections from the log files above.

I have cmake 3.8.0 rc4 x64 version installed. I have VS 2015 Update 3, Windows 10 Pro x64.
P.S. Visual Studio was installed on D:\ drive (`D:\Program Files (x86)\Microsoft Visual Studio 14.0`)
P.P.S. I have the similar error trying to build x64-uwp version or when I build this lib with integrated cmake 3.8.0 rc2

**Comment by ras0219-msft** [comment]
Thanks for reporting this! It should be fixed in 4765c58, though I haven't tested your original objective (mongo-cxx-driver).
