### ISSUE TITLE
Is vcpkg resetting the CRT option?

### ISSUE THREAD

**Issue by xarthurx** [microsoft/vcpkg#9034]
```
LNK2038	mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in StripeMeshDecomposition.obj	xxxProject C:\xxx\libspqrd.lib(SuiteSparseQR.cpp.obj	
```

I encounter this issue when trying to use `suitesparse` installed from vcpkg.
my triplet is: `x64-windows`.

Clearly, in my VS project settings, the Code Generation is set to "MT/MTd" by default, and if I changed it to "MD/MDd", things will work fine.

However, when I tried to set the cmake generation to `MD/MDd` with information from here:
https://cmake.org/cmake/help/latest/variable/CMAKE_MSVC_RUNTIME_LIBRARY.html#variable:CMAKE_MSVC_RUNTIME_LIBRARY

It doens't work. The settings in VS is always "MT/MTd" though cmake-gui shows the `cxx_flag` is `MD/MDd`. 

Then I'm confused that it seems the only possibility is `vcpkg` is setting these commands internally, and don't allow users to change it.

But the default `x64-windows` triplet file shows:
```
set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)
```

So why VS is always showing `MT/MTd` by default? Everytime I re-run cmake, I need to reset those parts from inside VS and this became very annoying....

Would someone give some hint please?

**Comment by Neumann-A** [comment]
`set(VCPKG_CRT_LINKAGE dynamic)` -> means dynamic runtime which is always MD
use 
`set(VCPKG_CRT_LINKAGE static)` -> to change it to MT
see also `scripts/toolchains/windows.cmake`

`CMAKE_MSVC_RUNTIME_LIBRARY` only matters for your personal projects.

**Comment by xarthurx** [comment]
Yes, I understand this part.
The problem is even when I use `x64-windows` and setting `CMAKE_MSVC_RUNTIME_LIBRARY` to `dynamic` or not set at all, all my own projects will still be set to `MT(d)` by default and conflicts with some lib compiled with vcpkg (`suitesparse` in my case).

**Comment by JackBoosY** [comment]
@xarthurx Please create a new triple file (eg x64-windows-md.cmake) in _VCPKG_PATH / triplets_ and write the following code:
```
set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE static)
set(VCPKG_LIBRARY_LINKAGE dynamic)
```

Then build port using command `./vcpkg install suitesparse:x64-windows-md`.

Thanks.

**Comment by xarthurx** [comment]
@JackBoosY Thanks for the commends.
Will vcpkg search automatically for the newly added triplet file? Or I need to modify some port files for the support? Cos I remember last time I tried to do sth like this and need to manually change one by one in the cmake-gui for the correct folder.

**Comment by xarthurx** [comment]
And one more question, is vcpkg related to the problem that all my projects created with vcpkg will have a `MT(d)` by default no matter how I modify the cmakelist file?

**Comment by Neumann-A** [comment]
>And one more question, is vcpkg related to the problem that all my projects created with vcpkg will have a MT(d) by default no matter how I modify the cmakelist file?

as far as I know the toolchain file `vcpkg.cmake` is not doin anything to compiler flags. But you might want to take a look yourself. 

Did you set `CMAKE_MSVC_RUNTIME_LIBRARY` before any project() call in your CMakeLists.txt?

**Comment by xarthurx** [comment]
@Neumann-A Thanks for the reply.

1. Yes, I tried various positions to place that command, but none of them works as expected, so I guess there must be sth that I miss.

2. I'm using newest cmake (3.15.5).

**Comment by Neumann-A** [comment]
>Note Call the cmake_minimum_required() command at the beginning of the top-level CMakeLists.txt file even before calling the project() command. It is important to establish version and policy settings before invoking other commands whose behavior they may affect. See also policy CMP0000.

If you do net use `cmake_minimum_required` as a first line in your main cmakelists.txt it will not behave like 3.15.5

**Comment by JackBoosY** [comment]
@xarthurx You need to create a new triplet file. We must declare the CRT linkage type(`VCPKG_CRT_LINKAGE`[1]) in triplet file.

[1]. VCPKG_CRT_LINKAGE STREQUAL dynamic -> MD/MDd, static -> MT/MTd.

**Comment by JackBoosY** [comment]
@xarthurx You need to create a new triplet file. We must declare the CRT linkage type(`VCPKG_CRT_LINKAGE`[1]) in triplet file.

[1]. VCPKG_CRT_LINKAGE STREQUAL dynamic -> MD/MDd, static -> MT/MTd.

**Comment by xarthurx** [comment]
Thank you everyone, problem solved by increasing the `cmake_mininum_required` version... 
Closing this issue.
