### ISSUE TITLE
[macos 10.14.5] build failure

### ISSUE THREAD

**Issue by DougStoker** [microsoft/vcpkg#9037]
[Terminal Saved Output3.txt](https://github.com/microsoft/vcpkg/files/3860129/Terminal.Saved.Output3.txt)

**Comment by DougStoker** [comment]
im not upgrading to catalina until all my 32 bit apps have been updated
freaking apple

**Comment by adam4813** [comment]
@DougStoker I certainly hope the issue I referenced above didn't confuse you. The issue above is from another repo, I just wanted to link it to here. vcpkg does build on 10.14 with a small workaround, but it feels very hacky.

**Comment by mellery451** [comment]
I'm having this same issue - what specifically is the small, hacky workaround referenced above?

**Comment by adam4813** [comment]
@mellery451 https://github.com/trillek-team/tec/issues/146#issuecomment-557361276

**Comment by PhoebeHui** [comment]
@DougStoker  @mellery451, this should be fixed, please open a new issue if it still be a problem for you.
