### ISSUE TITLE
use boost-python,but error LNK2001

### ISSUE THREAD

**Issue by yezilaoda** [microsoft/vcpkg#9038]
system:win10+vs2019+newest vcpkg
cmd:vcpkg.exe install boost-python:x86-windows-static
lib:boost_python37-vc140-mt.lib(15573k)

use in win32 console project.error info:

test.obj : error LNK2001: 无法解析的外部符号 "__declspec(dllimport) public: __thiscall boost::python::handle<struct _object>::~handle<struct _object>(void)" (__imp_??1?$handle@U_object@@@python@boost@@QAE@XZ)
1>test.obj : error LNK2001: 无法解析的外部符号 "__declspec(dllimport) class boost::python::api::object __cdecl boost::python::api::getattr(class boost::python::api::object const &,char const *)" (__imp_?getattr@api@python@boost@@YA?AVobject@123@ABV4123@PBD@Z)
1>test.obj : error LNK2001: 无法解析的外部符号 "__declspec(dllimport) void __cdecl boost::python::throw_error_already_set(void)" (__imp_?throw_error_already_set@python@boost@@YAXXZ)
1>test.obj : error LNK2001: 无法解析的外部符号 "__declspec(dllimport) public: __thiscall boost::python::api::object::object(class boost::python::handle<struct _object> const &)" (__imp_??0object@api@python@boost@@QAE@ABV?$handle@U_object@@@23@@Z)

fatal error LNK1120: 4 个无法解析的外部命令

**Comment by AlvinZhangH** [comment]
After add def `BOOST_NUMPY_STATIC_LIB` and set CRT linkage to MT/MTD, it still fails.

**Comment by AlvinZhangH** [comment]
Please feel free to reopen this issue if it is still a problem for you.

**Comment by JackBoosY** [comment]
We need to keep this issue open until it is resolved.

**Comment by PhoebeHui** [comment]
I can't repro this issue with latest source. @yezilaoda, please create a new issue with full repro code if this still be a problem for you.

**Comment by Yecgaa1** [comment]
我出现了相同的错误，解决方式就是要链接Boost::python，我使用cmake，其中最好的方式就是使用如下语句：
```cmake
target_link_libraries(${PROJECT_NAME} PRIVATE  ${Boost_LIBRARIES})
```
我使用这个语句解决了该问题
