### ISSUE TITLE
[New Port Request] <vld>

### ISSUE THREAD

**Issue by guan78001** [microsoft/vcpkg#9039]
Library name:vld

Library description:A library to detect leak memory on windows.

Source repository URL:https://github.com/derickr/vld.git

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
