### ISSUE TITLE
[libbson, mongo-c-driver] Should not rename headers

### ISSUE THREAD

**Issue by ras0219-msft** [Microsoft/vcpkg#904]
The libbson port currently renames its headers to be `include\bson.h` instead of `include\libbson-1.0\bson.h`. While this would be more convenient, it's clear that the consensus is to install into the `libbson-1.0` directory [1].

A similar argument follows for mongo-c-driver (and likely mongo-cxx-driver).

[1] https://www.archlinux.org/packages/community/i686/libbson/
[2] https://github.com/Microsoft/vcpkg/blob/6947f0aea15e5e422bf4e972d0e3c4554b76f1dc/ports/mongo-c-driver/bson.patch

**Comment by codicodi** [comment]
I think the idea with the versioned subdirectory is to install incompatible versions of a library on a system. Users still should use simply `<bson.h>` (see [here](https://github.com/mongodb/libbson/blob/master/examples/hello_bson.c#L18)) and set up appropriate include directories (in case of Arch that would be `/usr/include/libbson-1.0/`) with the help of [cmake ](https://github.com/mongodb/libbson/blob/master/examples/cmake/find_package/CMakeLists.txt#L31 )or [pkg-config](https://github.com/mongodb/libbson/blob/master/examples/compile-with-pkg-config.sh#L4). I'm not sure how we could follow these conventions with the MSBuild integration support.
Note that there are other libraries using this technique in native installations, mostly gtk+ and family.

**Comment by ras0219-msft** [comment]
Thanks for the explanation. I've added a comment to the portfile to refer back to this issue so any future onlookers will know the situation :).
