### ISSUE TITLE
[libpqxx] Library are built with unexpected filename under `x64-linux`

### ISSUE THREAD

**Issue by gnaggnoyil** [microsoft/vcpkg#9040]
**Describe the bug**
When installing under `x64-linux`, current libpqxx's portfile builds pqxx's static library with a filename `liblibpqxx_static.a` instead of `libpqxx_static.a`

**Environment**
- OS: Archlinux-20191109 and Ubuntu 18.04
- Compiler: GCC 9.2.0 and GCC 7.4.0

**To Reproduce**
1. `./vcpkg install libpqxx`
2. `ls ./vcpkg/packages/libpqxx_x64-linux/lib | grep pqxx`

**Expected behavior**
The `ls | grep` command outputs `libpqxx_static.a` or `libpqxx.a`

**Failure logs** 
The `ls | grep` command outputs `liblibpqxx_static.a`

**Additional context**
Did the original `ports/CMakeLists.txt` miss a `set(CMAKE_STATIC_LIBRARY_PREFIX)` command?

**Comment by AlvinZhangH** [comment]
Hi @gnaggnoyil  Since PR has been merged.
I close this issue now, please update vcpkg and rebuild it.
Thanks.
