### ISSUE TITLE
Could not detect a Windows SDK / TargetPlatformVersion

### ISSUE THREAD

**Issue by 03128crz** [microsoft/vcpkg#9044]
Win7 X64
```
(base) D:\vcpkg-master>bootstrap-vcpkg.bat
Could not detect a Windows SDK / TargetPlatformVersion
所在位置 D:\vcpkg-master\scripts\bootstrap.ps1:327 字符: 10
+     throw <<<<  "Could not detect a Windows SDK / TargetPlatformVersion"
    + CategoryInfo          : OperationStopped: (Could not detec...PlatformVersion:String) [], RuntimeException
    + FullyQualifiedErrorId : Could not detect a Windows SDK / TargetPlatformVersion

````

**Comment by NancyLi1013** [comment]
Hi @03128crz  thanks for posting this issue.
Could you help confirm whether you have installed Windows SDK in your visual studio?

**Comment by 03128crz** [comment]
> Hi @03128crz thanks for posting this issue.
> Could you help confirm whether you have installed Windows SDK in your visual studio?

Hi, How to confirm whether installed Windows SDK ? if not install and which version of SDK I need to installed

**Comment by NancyLi1013** [comment]
You can check this on your local and confirm whether there are Windows SDK.

`C:\Program Files (x86)\Windows Kits\`

If you don't install them before, you can open your Visual Studio Installer and enter Individual Components page to install. Generally, we install the latest version.

**Comment by Lekja00160612** [comment]
I installed the SDK but it does not seem to work

**Comment by NancyLi1013** [comment]
@Lekja00160612 
Please help confirm if you met the same error as this issue.

**Comment by badushaebrahim** [comment]
**_Could not detect a Windows SDK / TargetPlatformVersion
At C:\vcpkg\scripts\bootstrap.ps1:327 char:5
+     throw "Could not detect a Windows SDK / TargetPlatformVersion"
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Could not detec...PlatformVersion:String) [], RuntimeException
    + FullyQualifiedErrorId : Could not detect a Windows SDK / TargetPlatformVersion_**


this is the error i got any idea how to fix this ??

**Comment by sfhacker** [comment]
I wonder what the meaning of 'meet an error' is? It seems to be a very popular expression here.
I reckon we should either change our translator or take an English course or BOTH!
Have a look at this blog: http://english-for-chinese.blogspot.com/2008/06/and-meet-problem.html
