### ISSUE TITLE
Allow more transports (e.g. ssh, http) for vcpkg_from_git()

### ISSUE THREAD

**Issue by Jauler** [microsoft/vcpkg#9046]
**Is your feature request related to a problem? Please describe.**
Since commit d2b3ef9e88 `vcpkg_from_git()` [forbids](https://github.com/microsoft/vcpkg/blob/f5c732b40d43f062278f247036b773477823813b/scripts/cmake/vcpkg_from_git.cmake#L52) any transport other than `https`. This prevents using any non-https (e.g. ssh-only) repositories with `vcpg_from_git()`. Is there some specific reason for this? The commit itself seems to refer to some issues with SHA256 hashes on downloaded repos, but normally transport should not have an effect on the content... 

**Proposed solution**
Allow `ssh` traffic, also preferably `http` (with maybe some warning about unencrypted traffic).

Edit: some clarifications.

**Comment by JackBoosY** [comment]
Close this issue via #9446 merged.
