### ISSUE TITLE
mongo-c-driver:x86-uwp & x64-uwp BUILD_FAILED

### ISSUE THREAD

**Issue by AJIOB** [Microsoft/vcpkg#905]
I'm trying to build mongo-cxx-driver to UWP and have such error with it's dependence: mongo-c-driver version 1.5.1

	-- CURRENT_INSTALLED_DIR=D:/Alex/Documents/SourceTree/vcpkg/installed/x86-uwp
	-- DOWNLOADS=D:/Alex/Documents/SourceTree/vcpkg/downloads
	-- CURRENT_PACKAGES_DIR=D:/Alex/Documents/SourceTree/vcpkg/packages/mongo-c-driver_x86-uwp
	-- CURRENT_BUILDTREES_DIR=D:/Alex/Documents/SourceTree/vcpkg/buildtrees/mongo-c-driver
	-- CURRENT_PORT_DIR=D:/Alex/Documents/SourceTree/vcpkg/ports/mongo-c-driver/.
	-- Downloading https://github.com/mongodb/mongo-c-driver/archive/1.5.1.tar.gz...
	-- Downloading https://github.com/mongodb/mongo-c-driver/archive/1.5.1.tar.gz... OK
	-- Testing integrity of downloaded file...
	-- Testing integrity of downloaded file... OK
	-- Extracting done
	-- Applying patch D:/Alex/Documents/SourceTree/vcpkg/ports/mongo-c-driver/bson.patch
	-- Applying patch failed. This is expected if this patch was previously applied.
	-- Applying patch D:/Alex/Documents/SourceTree/vcpkg/ports/mongo-c-driver/bson.patch done
	-- Configuring x86-uwp-rel
	-- Configuring x86-uwp-rel done
	-- Configuring x86-uwp-dbg
	-- Configuring x86-uwp-dbg done
	-- Package x86-uwp-rel
	CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:14 (message):
		Command failed: D:/Program Files/CMake/bin/cmake.exe;--build;.;--config;Release;--target;install;--;/p:VCPkgLocalAppDataDisabled=true;/p:UseIntelMKL=No;/m
		Working Directory: D:/Alex/Documents/SourceTree/vcpkg/buildtrees/mongo-c-driver/x86-uwp-rel
		See logs for more information:
		  D:\Alex\Documents\SourceTree\vcpkg\buildtrees\mongo-c-driver\package-x86-uwp-rel-out.log
		  D:\Alex\Documents\SourceTree\vcpkg\buildtrees\mongo-c-driver\package-x86-uwp-rel-err.log

	Call Stack (most recent call first):
	  scripts/cmake/vcpkg_install_cmake.cmake:27 (vcpkg_execute_required_process)
	  ports/mongo-c-driver/portfile.cmake:25 (vcpkg_install_cmake)
	  scripts/ports.cmake:73 (include)

	Error: Building package mongo-c-driver:x86-uwp failed with: BUILD_FAILED
	Please ensure you're using the latest portfiles with `.\vcpkg update`, then
	submit an issue at https://github.com/Microsoft/vcpkg/issues including:
	  Package: mongo-c-driver:x86-uwp
	  Vcpkg version: 0.0.78-db73e73c562a00228dd8c01ee2a03f03012023fc

	Additionally, attach any relevant sections from the log files above.

I have cmake 3.8.0 rc4 x64 version installed. I have VS 2015 Update 3, Windows 10 Pro x64.
P.S. Visual Studio was installed on D:\ drive (D:\Program Files (x86)\Microsoft Visual Studio 14.0)
P.P.S. I have the similar error trying to build x64-uwp version

**Comment by ras0219-msft** [comment]
Ok, I think I've fixed both mongo-c-driver and mongo-cxx-driver in e7ad48b. Let me know if you still have issues!
