### ISSUE TITLE
[boost:x86-windows-static] build failure

### ISSUE THREAD

**Issue by youngqqcn** [microsoft/vcpkg#9052]
-- Using cached D:/vcpkg-2019.10/downloads/boostorg-numeric_conversion-boost-1.7
1.0.tar.gz
-- Using source at D:/vcpkg-2019.10/buildtrees/boost-numeric-conversion/src/ost-
1.71.0-12d108d8f1
-- Packaging headers
-- Packaging headers done
-- Using cached D:/vcpkg-2019.10/downloads/boost_LICENSE_1_0.txt
-- Installing: D:/vcpkg-2019.10/packages/boost-numeric-conversion_x86-windows-st
atic/share/boost-numeric-conversion/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package boost-numeric-conversion[core]:x86-windows-static... done
Installing package boost-numeric-conversion[core]:x86-windows-static...
Installing package boost-numeric-conversion[core]:x86-windows-static... done
Elapsed time for package boost-numeric-conversion:x86-windows-static: 1.031 s
Starting package 29/148: boost-build:x86-windows-static
Building package boost-build[core]:x86-windows-static...
-- Using cached D:/vcpkg-2019.10/downloads/boostorg-build-boost-1.70.0.tar.gz
-- Using source at D:/vcpkg-2019.10/buildtrees/boost-build/src/ost-1.70.0-ad28c1
be18
-- Using cached D:/vcpkg-2019.10/downloads/boost_LICENSE_1_0.txt
-- Using cached D:/vcpkg-2019.10/downloads/boost-1.70.0-boostcpp.jam
-- Installing: D:/vcpkg-2019.10/packages/boost-build_x86-windows-static/share/bo
ost-build/copyright
-- Installing: D:/vcpkg-2019.10/packages/boost-build_x86-windows-static/tools/bo
ost-build/boostcpp.jam
-- Bootstrapping...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: D:/vcpkg-2019.10/packages/boost-build_x86-windows-static/too
ls/boost-build/bootstrap.bat msvc
    Working Directory: D:/vcpkg-2019.10/packages/boost-build_x86-windows-static/
tools/boost-build
    Error code: 2
    See logs for more information:
      D:\vcpkg-2019.10\buildtrees\boost-build\bootstrap-x86-windows-static-out.l
og
      D:\vcpkg-2019.10\buildtrees\boost-build\bootstrap-x86-windows-static-err.l
og

Call Stack (most recent call first):
  ports/boost-build/portfile.cmake:58 (vcpkg_execute_required_process)
  scripts/ports.cmake:94 (include)

Error: Building package boost-build:x86-windows-static failed with: BUILD_FAILED

Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-build:x86-windows-static
  Vcpkg version: 2019.09.12-nohash

Additionally, attach any relevant sections from the log files above.

D:\vcpkg-2019.10>

- bootstrap-x86-windows-static-err.log

```

:cl: 命令行 error D8000 :cl: 命令行 error D8000 :cl: 命令行 error D8000 :cl: 命令行 error D8000 :cl: 命令行 error D8000 :cl: 命令行 error D8000 :cl: 命令行 error D8000 :C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64_x86\cl.exe 中有内部编译器错误。系统将会提示你稍后向 Microsoft 发送错误报告。
“C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64_x86\cl.exe”中的内部编译器错误

```

-  windows 7 SP1    x64
-  vs2015 Community contains udpates

**Comment by NancyLi1013** [comment]
Hi @youngqqcn thanks for posting this issue.
It's similar to #6334. Could you please refer to these info in #6334 and check the environment on your machine?
I cannot reproduce this issue on my local with VS2017, Windows7, Win10-Chinese.

**Comment by timautry** [comment]
What version of the Windows SDK do you have installed? 
I believe you need at least Windows SDK 8.1 and include both the x86 and x64 components, as you're building x86 on a x64 machine. I don't remember what SDK vs2015 contains, but I believe vs2015 with update 3 needs to be installed.
Hope this helps.

**Comment by youngqqcn** [comment]
> What version of the Windows SDK do you have installed?
> I believe you need at least Windows SDK 8.1 and include both the x86 and x64 components, as you're building x86 on a x64 machine. I don't remember what SDK vs2015 contains, but I believe vs2015 with update 3 needs to be installed.
> Hope this helps.

Thanks  !  I  built successfully on another machine ( Win10-Chinese , VS2017 latest version)  .
