### ISSUE TITLE
request: be able to mix static and dynamic libraries

### ISSUE THREAD

**Issue by Dredok** [Microsoft/vcpkg#906]
its very common to mix static and dynamic libraries in an application. 

Thats imposible with current VCPKG version, everything will be complied according to VCPKG_TARGET_TRIPLET. 

In my use case I need to compile and link all libraries static but Qt dynamic. Currently I have to do workarounds to make it work.

**Comment by ras0219-msft** [comment]
This is definitely supported, though not very documented!

The files inside `triplets\` are run immediately before every portfile and have access to the name of the port as `PORT`. These can be modified or extended (say, by creating `triplets\x86-windows-dredok.cmake`) with port-dependent decisions like:

```cmake
set(VCPKG_TARGET_ARCHITECTURE x86)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)

if(PORT STREQUAL "qt5")
    set(VCPKG_LIBRARY_LINKAGE dynamic)
endif()
```

Here's a real-life example of that in action: https://github.com/Intelight/vcpkg/blob/master/triplets/x86-windows-mixed.cmake

**Comment by Dredok** [comment]
great! thank you very much.

**Comment by ras0219-msft** [comment]
I've moved this into our main documentation with https://github.com/Microsoft/vcpkg/commit/76b754e52ddcb2d2a6958e4a913d0371c00279d8.

**Comment by Zingam** [comment]
@ras0219-msft Is it possible to set the linkage from the project's CMakeLists.txt instead of modifying a triplet?
We would like to have all settings inside of our repository without messing with vcpkg.

**Comment by Danielmelody** [comment]
Using a triplet file can also cause hash changed every time editing that file, which defeats binary caching,

**Comment by Sammot** [comment]
> @ras0219-msft Is it possible to set the linkage from the project's CMakeLists.txt instead of modifying a triplet? We would like to have all settings inside of our repository without messing with vcpkg.

Any update on this? I share your need.

**Comment by Zingam** [comment]
> > @ras0219-msft Is it possible to set the linkage from the project's CMakeLists.txt instead of modifying a triplet? We would like to have all settings inside of our repository without messing with vcpkg.
> 
> Any update on this? I share your need.

I recommend to create a new feature request.

**Comment by commonbreed** [comment]
@ras0219-msft Not sure this deserved to be closed. There is still no way to mix static and dynamic dependencies without messing with the internals of vcpkg - which is kind of crazy... this is a pretty basic feature. Stuff like this can be a huge turn-off for an entire ecosystem.

**Comment by Holt59** [comment]
> @ras0219-msft Not sure this deserved to be closed. There is still no way to mix static and dynamic dependencies without messing with the internals of vcpkg - which is kind of crazy... this is a pretty basic feature. Stuff like this can be a huge turn-off for an entire ecosystem.
> 
> Making a custom triplet is complete overkill. It's not a different platform or ABI (which is what a triplet is for). You should be able to specify this in your project's CMake.
> 
> In my mind, installing a port should give you both static and dynamic artifacts by default, providing an option to use either in the CMake link target. Unless of course, the port file explicitly declares it cannot be built a certain way.

This is 100% true. 

I have multiple projects that depends on Boost, with a big one that depends on 7z + many boost components. 7z is a pain to use as a static library, so I just want to move 7z as dynamic. Problem? I need a custom triplet for the big project, meaning I need to rebuild every boost library because of the custom triplets...

That triplet solution is clearly not viable unless there is a way to properly do it. Having to rebuild 75 boost components because 7z needs to be dynamically linked does not make sense.

And yes, I could create a custom overlay port for 7z, but that's even overkill looking at the official 7z port.

**Comment by sweemer** [comment]
I also vote for reopening this issue and finding a solution that doesn't involve creating a custom triplet.
