### ISSUE TITLE
[embree3:x64-osx] build failure

### ISSUE THREAD

**Issue by xelatihy** [microsoft/vcpkg#9072]
**Host Environment**
- OS: MacOS Catalina
- Compiler: Apple Clang 11

**To Reproduce**
`./vcpkg install embree3`

There should be no bin\ directory in a static build, but /Users/fabio/Documents/Work/projects/vcpkg/packages/embree3_x64-osx/bin is present.
There should be no debug\bin\ directory in a static build, but /Users/fabio/Documents/Work/projects/vcpkg/packages/embree3_x64-osx/debug/bin is present.
If the creation of bin\ and/or debug\bin\ cannot be disabled, use this in the portfile to remove them

    if(VCPKG_LIBRARY_LINKAGE STREQUAL static)
        file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/bin ${CURRENT_PACKAGES_DIR}/debug/bin)
    endif()

There should be no empty directories in /Users/fabio/Documents/Work/projects/vcpkg/packages/embree3_x64-osx
The following empty directories were found:

    /Users/fabio/Documents/Work/projects/vcpkg/packages/embree3_x64-osx/bin
    /Users/fabio/Documents/Work/projects/vcpkg/packages/embree3_x64-osx/debug/bin

If a directory should be populated but is not, this might indicate an error in the portfile.
If the directories are not needed and their creation cannot be disabled, use something like this in the portfile to remove them:

    file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/a/dir ${CURRENT_PACKAGES_DIR}/some/other/dir)

The following files are placed in
/Users/fabio/Documents/Work/projects/vcpkg/packages/embree3_x64-osx:

    /Users/fabio/Documents/Work/projects/vcpkg/packages/embree3_x64-osx/uninstall.command

Files cannot be present in those directories.

The following files are placed in
/Users/fabio/Documents/Work/projects/vcpkg/packages/embree3_x64-osx/debug:

    /Users/fabio/Documents/Work/projects/vcpkg/packages/embree3_x64-osx/debug/uninstall.command

Files cannot be present in those directories.

Found 4 error(s). Please correct the portfile:
    /Users/fabio/Documents/Work/projects/vcpkg/ports/embree3/portfile.cmake
-- Performing post-build validation done
Error: Building package embree3:x64-osx failed with: POST_BUILD_CHECKS_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: embree3:x64-osx
  Vcpkg version: 2019.09.12-unknownhash

Additionally, attach any relevant sections from the log files above.

**Comment by xelatihy** [comment]
In case it helps, #9073 might be fixing the problem and passes CI.

**Comment by PhoebeHui** [comment]
@xelatihy, https://github.com/microsoft/vcpkg/pull/9073 has been merged, could you double confirm if it still be a problem for you?

**Comment by xelatihy** [comment]
It seems the problem persists. I'll look into it more closely.

**Comment by xelatihy** [comment]
I created PR #9555 that should cleanup this issue. Not sure why the previous one passed CI though.

**Comment by JackBoosY** [comment]
In _SOURCE_PATH/common/cmake/package.cmake_ line 94:
```
IF (APPLE AND NOT EMBREE_ZIP_MODE)
  CONFIGURE_FILE(scripts/install_macosx/uninstall.command uninstall.command @ONLY)
  INSTALL(PROGRAMS "${PROJECT_BINARY_DIR}/uninstall.command" DESTINATION ${CMAKE_INSTALL_BINDIR}/.. COMPONENT lib)
ENDIF()
```

We don't need it, vcpkg can manage install and uninstall process, so we must remove it.

**Comment by xelatihy** [comment]
I though I remove it in the PR but I did it only for the case that failed the build for me. For changes like patching a file in the sources, I guess I am not the right person for this since I am neither the Embree author nor a vcpkg expert. Sorry.

**Comment by JackBoosY** [comment]
@xelatihy I think you did a good job! Thanks!

**Comment by PhoebeHui** [comment]
@xelatihy, the PR has been merged, and I double confirmed it works well on OSX, thanks for your contribution!
