### ISSUE TITLE
Access is denied

### ISSUE THREAD

**Issue by djgaare** [microsoft/vcpkg#9079]
I get this error when running ./vcpkg install cpprestsdk cpprestsdk:x64-windows from windows powershell running as administrator.

buildtrees\boost-thread\x86-windows-dbg\boost\build\87059d94cd50f8a5e66b81fe4f6950ae\boost_thread-vc141-mt-gd-x32-1_71.dll". Access is denied

Additional information in the log after it suggests to report this to GitHub.com/Microsoft/vcpkg/issues is 
  Package: boost-thread:x86-windows
  Vcpkg version: 2019.09.12-nohash

**Comment by NancyLi1013** [comment]
Hi @djgaare thanks for posting this issue.
Could you please provide the steps to reproduce and the completed log?
I also noticed that you tried to install cpprestsdk:x64-windows, but access is denied here:
`buildtrees\boost-thread\x86-windows-dbg\boost\build\87059d94cd50f8a5e66b81fe4f6950ae\boost_thread-vc141-mt-gd-x32-1_71.dll`
I'm sorry that I am confused about this issue. Could you supplement more info to make this issue more clear?

**Comment by djgaare** [comment]
This issue has been resolved.  We needed to open up some bit defender settings in order to gain access to some of the .dll’s.

**Comment by NancyLi1013** [comment]
Thanks for your update. Please open a new issue if you have other problems.
