### ISSUE TITLE
Cannot update vcpkg

### ISSUE THREAD

**Issue by mateka** [Microsoft/vcpkg#908]
After git pull, executing bootstrap-vcpkg.bat ends with an error:

> fatal error C1083: Cannot open include file: 'shlobj.h': No such file or directory

**Comment by ras0219-msft** [comment]
Hi @mateka,

You may need to reinstall the Windows SDK. It looks like an outdated 8.1 SDK is often the source of these issues [1].

For example, on my machine, this file is at:
`C:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\um\ShlObj.h`
`C:\Program Files (x86)\Windows Kits\8.1\Include\um\ShlObj.h`

[1] http://stackoverflow.com/questions/9538509/why-am-i-receiving-this-error-when-i-attempt-to-build-qt-from-source-in-visual-s

**Comment by mateka** [comment]
Althought the files were present on my system, I could not build vcpkg. Today, I had pulled changes from git and reinstalled Windows 10 SDK from Visual Studio installer (Windows 8 SDK was deleted from my system way back, when I have deinstalled Visual Studio 2015) and now everything works! Thank You very much! :)
