### ISSUE TITLE
MSVC release configurations use /Z7

### ISSUE THREAD

**Issue by heydojo** [microsoft/vcpkg#9084]
****
**Description**
Is there a debug flag being set incorrectly here?

https://github.com/microsoft/vcpkg/blob/7ca7db5285a628ef7be3661f5a152c1ab7168bf4/scripts/toolchains/windows.cmake#L26

https://github.com/microsoft/vcpkg/blob/7ca7db5285a628ef7be3661f5a152c1ab7168bf4/scripts/toolchains/windows.cmake#L27

The flag **/Z7** appears to be (incorrectly imo) set for release configurations.
https://docs.microsoft.com/en-us/cpp/build/reference/z7-zi-zi-debug-information-format?view=vs-2019

Same applies:

- https://github.com/microsoft/vcpkg/blob/7ca7db5285a628ef7be3661f5a152c1ab7168bf4/scripts/cmake/vcpkg_configure_meson.cmake#L15
- https://github.com/microsoft/vcpkg/blob/7ca7db5285a628ef7be3661f5a152c1ab7168bf4/scripts/cmake/vcpkg_configure_meson.cmake#L16
- https://github.com/microsoft/vcpkg/blob/7ca7db5285a628ef7be3661f5a152c1ab7168bf4/scripts/cmake/vcpkg_configure_meson.cmake#L21
- https://github.com/microsoft/vcpkg/blob/7ca7db5285a628ef7be3661f5a152c1ab7168bf4/scripts/cmake/vcpkg_configure_meson.cmake#L22

**Proposed solution**
The **/Z7** flag is removed from the variables highlighted above.

**Additional context**
I am interested to find out if there is a genuine reason for setting **/Z7** in release configurations as my general understanding is that it is not required and would appear arbitrary.

Thanks!

**Comment by here-mikelley** [comment]
I think we should have the ability to override `/Z7`.  Unfortunately there's no `strip` function in Windows, so you're stuck with debug information in static libraries.

**Comment by here-mikelley** [comment]
Whoops, looks like I accidentally unassigned @grdowns from this issue. @NancyLi1013  or @grdowns - can you fix my mistake?

**Comment by KindDragon** [comment]
> I am interested to find out if there is a genuine reason for setting /Z7 in release configurations as my general understanding is that it is not required and would appear arbitrary.

Without it, we won't have debugging information.

**Comment by NancyLi1013** [comment]
@BillyONeal 
Could you please help take a look about this issue?

Thanks.

**Comment by BillyONeal** [comment]
What @KindDragon said. There's no reason to remove debugging information; we believe CMake's default setting which includes not even stripped symbols in release mode is an incorrect default. Notably, Windows turning on debug information never increases the size of the resulting program, only in the worst case some intermediate files. All our debugging bits end up going into a PDB, and you always want PDBs even in release builds so that you can interpret stack traces etc. later.

**Comment by NancyLi1013** [comment]
Thanks for your explanation to this issue. @BillyONeal

**Comment by bucurb** [comment]
According to the [documentation ](https://docs.microsoft.com/en-us/cpp/build/reference/z7-zi-zi-debug-information-format?view=msvc-160)for /Z7 /Zi, it looks like there would be no difference between /Z7 and /Zi in terms of debugging information generated, it's just about where this information is stored. If using /Z7 the debug info is stored directly in the executable / library, while /Zi would produce a separate pdb file. If I were to create nuget packages with just the binary libs and have my pdbs packed in another nuget package, I would not be able to do so with the /Z7 option, only with /Zi. So, why is this not a bug?

**Comment by BillyONeal** [comment]
> According to the [documentation ](https://docs.microsoft.com/en-us/cpp/build/reference/z7-zi-zi-debug-information-format?view=msvc-160)for /Z7 /Zi, it looks like there would be no difference between /Z7 and /Zi in terms of debugging information generated, it's just about where this information is stored. If using /Z7 the debug info is stored directly in the executable / library, while /Zi would produce a separate pdb file. If I were to create nuget packages with just the binary libs and have my pdbs packed in another nuget package, I would not be able to do so with the /Z7 option, only with /Zi. So, why is this not a bug?

This is technically true, but 'executable / binary' means '.obj' or '.lib', not something you ship to end user machines. When you build what you ship to customers (a DLL or EXE), the linker generates a PDB using the information from all the /Z7'd content.

The big problem with /Zi for vcpkg purposes is that it embeds a name of a PDB into the static library or .obj which cannot be renamed, or the linker can't find it, which means we have no means of separating libraries from each other, and that it reduces available parallelism. /Zi made a lot more sense when the average dev box only had 1 or 2 cores (when that MSDN doc was written) and the potential perf improvement gained by being able to reuse type information in different translation units was a bigger savings on average than the loss of parallelism incurred by needing to synchronize compilers' access to the shared PDB.

**Comment by bucurb** [comment]
You're right about .libs not being shipped to end user machines. However, they get shipped to build agents and developers, and with the working from home and flaky internet connections, it makes sense to minimize the amount we need to download. This way we can get just the libs and if everything runs fine we never need to fetch the pdbs. If this were configurable we could have the choice that for release, for certain platforms, we turn off debug completely.

**Comment by BillyONeal** [comment]
>  If this were configurable we could have the choice that for release, for certain platforms, we turn off debug completely.

Again though, vcpkg doesn't have a means in general to get the resulting PDB to have the right name, and it can't be renamed after creation. The default name is something like `vc142.pdb` which every library would stomp on.

It is more than a desire for a policy recommendation here, it's a hard requirement for how vcpkg deploys libs to users.

**Comment by jasonz88** [comment]
Billy,

I don't fully understand the challenge you mentioned.
https://learn.microsoft.com/en-us/cpp/build/reference/pdb-use-program-database?view=msvc-170
isn't the pdb output filename configurable?

**Comment by BillyONeal** [comment]
>isn't the pdb output filename configurable?

Yes, but by and large people don't. Without patching every port would stomp on every other port.

**Comment by GregorySech** [comment]
My department uses Visual Studio heavily for C++ development and we just dropped the idea of migrating to vcpkg as a dependency manager due to not being able to keep intermediate project artifact to a sane size when using various static libraries.
gRPC 20GB+ build artifacts literally broke the camel's back.

The integration in VS22 is quite nice but if you use static libraries, it's just not worth it.
