### ISSUE TITLE
[pmdk : x64-windows] build failure

### ISSUE THREAD

**Issue by sunshineffmx** [microsoft/vcpkg#9086]
**Host Environment**
- OS: [ Windows Server 2019]
- Compiler: Vcpkg version: 2019.09.12-nohash
-Visual Studio 2017, English version

**To Reproduce**
`./vcpkg install pmdk:x64-windows

**Failure logs** 
The following packages will be built and installed:
    pmdk[core]:x64-windows
Starting package 1/1: pmdk:x64-windows
Building package pmdk[core]:x64-windows...
-- Using cached D:/install/vcpkg/downloads/pmem-pmdk-bc5e309485df61c452d08367e4b13ba9dfed5071.tar.gz
-- Using source at D:/install/vcpkg/buildtrees/pmdk/src/a9dfed5071-0e9bfe8f54
-- Building D:/install/vcpkg/buildtrees/pmdk/src/a9dfed5071-0e9bfe8f54/src/PMDK.sln for Release
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: msbuild D:/install/vcpkg/buildtrees/pmdk/src/a9dfed5071-0e9bfe8f54/src/PMDK.sln /p:Configuration=Release /p:SRCVERSION=1.7 "/t:Solution Items\libpmem,Solution Items\libpmemlog,Solution Items\libpmemblk,Solution Items\libpmemobj,Solution Items\libpmempool,Solution Items\libvmem,Solution Items\Tools\pmempool" /p:Platform=x64 /p:PlatformToolset=v141 /p:VCPkgLocalAppDataDisabled=true /p:UseIntelMKL=No /p:WindowsTargetPlatformVersion=10.0.16299.0 /m
    Working Directory: D:/install/vcpkg/buildtrees/pmdk/x64-windows-rel
    Error code: 1
    See logs for more information:
      D:\install\vcpkg\buildtrees\pmdk\build-x64-windows-rel-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_msbuild.cmake:119 (vcpkg_execute_required_process)
  ports/pmdk/portfile.cmake:22 (vcpkg_build_msbuild)
  scripts/ports.cmake:94 (include)

Error: Building package pmdk:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: pmdk:x64-windows
  Vcpkg version: 2019.09.12-nohash

Additionally, attach any relevant sections from the log files above.

[build-x64-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/3882476/build-x64-windows-rel-out.log)

I have tried the following method, but it didn't worked.
![image](https://user-images.githubusercontent.com/33800571/69479278-5a0c4d80-0e36-11ea-9107-32c968512193.png)

**Comment by PhoebeHui** [comment]
@sunshineffmx, thanks for reporting this issue.

It failed due to 'd:\install\vcpkg\buildtrees\pmdk\src\a9dfed5071-0e9bfe8f54\src\libpmemobj\critnib.c : warning C4819: The file contains a character that cannot be represented in the current code page (936). Save the file in Unicode format to prevent data loss', 

I submitted a PR to fix this issue.

**Comment by PhoebeHui** [comment]
The PR has been merged. Please get latest source and try again.
