### ISSUE TITLE
[boost.date_time] link failure

### ISSUE THREAD

**Issue by acgetchell** [microsoft/vcpkg#9087]
**Host Environment**
- OS: Windows
- Compiler: Visual Studio 2017 with clang-cl 9.0.0

**To Reproduce**
Use Boost.Date_Time:
https://github.com/acgetchell/CDT-plusplus/commit/ece069b7bf8b66c34ecd4404fd801d3a3346cf0b

Configure on AppVeyor:
https://github.com/acgetchell/CDT-plusplus/blob/develop/.appveyor.yml

**Failure logs** 
https://ci.appveyor.com/project/acgetchell/cdt-plusplus/builds/29066845#L1213

**Additional context**
It works on Ubuntu 18.04, gcc-9 and clang-7

https://travis-ci.org/acgetchell/CDT-plusplus/builds/615900365

It also works locally on macOS 10.15, but there is a general regression which prevents vcpkg from building on earlier versions of macOS.

https://github.com/microsoft/vcpkg/issues/8627

**Comment by yurybura** [comment]
@PhoebeHui Could you check and close this issue?

**Comment by PhoebeHui** [comment]
I confirmed this issue with VS2019+clang-cl 12, it builds fine with the repro code.

```
#include <iostream>
#include <boost/date_time.hpp>

inline std::string currentDateTime()
{
	using namespace boost::posix_time;
	ptime              now = microsec_clock::local_time();
	std::ostringstream result_s;
	result_s << now;
	std::string result = result_s.str();
	return result;
}
```
