### ISSUE TITLE
Add command to show post-install CMake usage instructions.

### ISSUE THREAD

**Issue by paul-reilly** [microsoft/vcpkg#9091]
vcpkg shows helpful usage instructions for CMake after installing a package, however there isn't a command to show these instructions at a later date, afaik.

I think it would be helpful to add such a command.

**Comment by adam4813** [comment]
If you run the install again, it won't do the work again, but it will display the instructions. I know this isn't what you want directly, but it is a short term.

**Comment by paul-reilly** [comment]
@adam4813 : that's good news, I did not know that. Now fingers crossed for forgetting the correct triplet with a giant library. :) Thanks!

**Comment by NancyLi1013** [comment]
Hi @paul-reilly 
Thanks for posting this issue.
Does this can meet your demands if you run install again to show the usage instructions?

**Comment by paul-reilly** [comment]
Yes for me it's fine, now that I know! :)

**Comment by NancyLi1013** [comment]
Thanks for your update. In my opinion. the current status might be enough. 
So I'm closing this issue for now.

**Comment by atimholt** [comment]
I'm trying to find the usage instructions for the cairomm package, but "re-installing" only outputs a message stating that the package is already installed, rather than any information on linking or otherwise using it.
