### ISSUE TITLE
What can be the reasons that Dll are not copied in post build step?

### ISSUE THREAD

**Issue by YuryBrodskiy** [microsoft/vcpkg#9095]
Hi,
 I have been using vcpkg for more than a year now. It is a fantastic tool, thank you.
I have encountered a small problem after the last update  ~11/20/2019.  
Normally vcpkg copies all dependent dll into OUTPUT_DIRECTORY.  However, it is no longer the case. I have failed to find a cause for it.
I know that this behavior is controlled with `VCPKG_APPLOCAL_DEPS`  flag.
I have used `set(VCPKG_APPLOCAL_DEPS ON)`. I have also verified that  VS2019 Project generated using cmake contains build step with `applocal.ps1`
It is also clear that it is executed (running verbose build). 
DLLs are not copied and there is not fail message of any kind.
Can you please help me to resolve the issue?
Or suggest another way to package together all dependent dlls.

**Comment by JackBoosY** [comment]
Vcpkg will get the ports that the custom project needs to copy according to the log information generated by the msvc link. I think there are some bugs here.

**Comment by YuryBrodskiy** [comment]
Yes, that had no effect. The behavior changed after the upgrade of vcpkg, not after the VS upgrade.

**Comment by JackBoosY** [comment]
@grdowns Could you have a look?

**Comment by YuryBrodskiy** [comment]
When I try to run applocal.ps1 in cmd. i.e. trying to replicate manually post-build step, I see the following error 
'
dumpbin : The term 'dumpbin' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\git\vcpkg\scripts\buildsystems\msbuild\applocal.ps1:60 char:12
+     $a = $(dumpbin /DEPENDENTS $targetBinary | ? { $_ -match "^    [^ ...
+            ~~~~~~~
    + CategoryInfo          : ObjectNotFound: (dumpbin:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
'

**Comment by YuryBrodskiy** [comment]
Ok. I have found the problem. It seems that CMake incorrectly identifies VCPKG_TARGET_TRIPLET.
To replicate the problem:
+ install clean vcpkg
+ install whatever libraries only for x64-windows triplet
+ make cmake project that uses those libraries **(See note in the end)
+ run `cmake -G"Visual Studio 16 2019" ..` to generate visual studio solution
At this point, two outcomes are possible dependent libraries are not found or dll will not be copied (it is not completely clear for me how did I get to that state, may be something with cmake cache).
The cause  line 48 in \vcpkg\scripts\buildsystems\vcpkg.cmake
```
  elseif(CMAKE_GENERATOR MATCHES "^Visual Studio 16 2019$")
        set(_VCPKG_TARGET_TRIPLET_ARCH x86)
```
it should read instead
```
  elseif(CMAKE_GENERATOR MATCHES "^Visual Studio 16 2019$")
        set(_VCPKG_TARGET_TRIPLET_ARCH x64)
```
x64 is default architecture for VS 16 2019,

alternatively  VCPKG_TARGET_TRIPLET should be read from  environmental variable VCPKG_DEFAULT_TRIPLET.

I hope you can use this to improve vcpkg. Thank you for help

** I use the following structure in my cmake to detect vcpkg
```
cmake_minimum_required(VERSION 3.16)

if(DEFINED ENV{VCPKG_ROOT})
#NOTE has to be defined before project command
    set(CMAKE_TOOLCHAIN_FILE "$ENV{VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake")
endif()

project(FEBundle VERSION 0.1 LANGUAGES CXX)
set(VCPKG_APPLOCAL_DEPS ON)

if((MSVC) AND (NOT DEFINED ENV{VCPKG_ROOT}))
    message("Windows port depends on VCPKG.")
    message("VCPKG can be installed from https://github.com/Microsoft/vcpkg")
    message("Set  VCPKG_DEFAULT_TRIPLET=x64-windows")
    message(FATAL_ERROR "VCPKG_ROOT has point to root of VCPKG to ensure that all required packages can be found automatically")
endif()
```

**Comment by PhoebeHui** [comment]
@YuryBrodskiy, you can also use following command to generate visual studio solution, note to replace the toolchain file path.

cmake.exe -DCMAKE_TOOLCHAIN_FILE=F:/vcpkg/src/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows -DVCPKG_BUILD_TYPE=debug  -G "Visual Studio 16 2019" ..

**Comment by YuryBrodskiy** [comment]
Agreed, but I have expected VCPKG_DEFAULT_TRIPLET have the same effect, also may be a message about it would be nice.

**Comment by JackBoosY** [comment]
Hi @YuryBrodskiy, does this issue still bother you?

**Comment by JackBoosY** [comment]
If this issue is still not resolved, please reopen it.

**Comment by CrossroadW** [comment]
env: visual studio2022 vcpkg  2024-09-18-5f5da308dd1dd3cc49641c60eafff176e248a9dd
dll not found also

**Comment by dg0yt** [comment]
> dll not found also

Open a new issue will full information.
