### ISSUE TITLE
[New Port Request] ffms2.dll

### ISSUE THREAD

**Issue by no-trom** [microsoft/vcpkg#9105]
Library name: ffmpeg source

Library description: ffmpeg based decoding for AviSynth and VapourSynth

Source repository URL: https://github.com/FFMS/ffms2

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included): thanks for considering this!

**Comment by NancyLi1013** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
