### ISSUE TITLE
[New Port Request] xtensor-python

### ISSUE THREAD

**Issue by KarolTrojanowskiDL** [microsoft/vcpkg#9106]
Library name: xtensor-python

Library description:
Python bindings for the xtensor C++ multi-dimensional array library.

Source repository URL:
https://github.com/xtensor-stack/xtensor-python

Project homepage (if different from the source repository):
https://xtensor-python.readthedocs.io/en/latest/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):
Requires pybind11 (already in vcpkg) and NumPy headers, e.g. discovered by FindPython.cmake.

**Comment by NancyLi1013** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
