### ISSUE TITLE
Boost build doesn't find ICU

### ISSUE THREAD

**Issue by josuegomes** [Microsoft/vcpkg#911]
ICU is required for Boost.Locale (while not mandatory)

Steps to reproduce (Windows 7 Pro, Visual Studio 2015 Pro Upd 3)

1. cd c:\
2. git ... vcpkg
3. cd vcpkg
4. bootstrap-vcpkg.bat
5. vcpkg install icu boost

In the build log (attached) you will see:

```
    - has_icu builds           : no
    - icu                      : no

```

[boost-x86-windows.zip](https://github.com/Microsoft/vcpkg/files/905784/boost-x86-windows.zip)

**Comment by josuegomes** [comment]
Attaching icu build logs
[icu-x86-windows.zip](https://github.com/Microsoft/vcpkg/files/905808/icu-x86-windows.zip)

**Comment by josuegomes** [comment]
This code with ICU

```
#include <iostream>
#include <boost/locale.hpp>

int main()
{
	setlocale(LC_ALL,"");

	using namespace boost::locale;

	generator gen;
	std::cout.imbue(gen("de_DE.windows-1252"));

	double value = 12345.67;

	std::cout << as::spellout << value << "\n\n";
}

```

Is expected to output

`zwölf-­tausend­-drei­-hundert­-fünf­-und-­vierzig Komma sechs sieben`

**Comment by josuegomes** [comment]
The issue is with the way Boost tries to detect ICU. I could overcome this issue by setting both ICU_PATH and ICU_LINK in the bjam command line.
It is working for x86:windows. I didn't tested yet for static or x64.

Is there any interested on a PR for this?

**Comment by codicodi** [comment]
ICU support would certainly be nice to have in Boost.Locale (and in Boost.Regex too!).
One issue I see here is that Boost doesn't seem to support ICU when compiling with `/MT`:
https://github.com/boostorg/locale/blob/develop/build/has_icu_test.cpp#L19
I'm guessing the main rationale here is that _usually_ ICU on Windows is built as DLLs, in which case linking Boost with static runtime would indeed be problematic. Our ICU port however supports all of the (desktop) build combinations so maybe we could simply patch out this assertion.

**Comment by josuegomes** [comment]
@codicodi by "compiling with /MT" you mean the static triplets?

**Comment by codicodi** [comment]
That's correct

**Comment by josuegomes** [comment]
OK, thanks.

ICU detection fails with x86-windows-static but not because of that assertion.

It seems that Boost is not honoring the "variant=release" and "runtime-link=static" options when building has_icu_test.

I'm getting these errors (release build):

`icuin.lib(coll.ao) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in has_icu_test.obj`

`icuin.lib(coll.ao) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MDd_DynamicDebug' in has_icu_test.obj
`

Debug build has:

`icuind.lib(coll.ao) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in has_icu_test.obj
` 

I'm not familiar with Bjam. I don't know how to fix Regex and Locale jam files.
Any idea?

**Comment by josuegomes** [comment]
This is fixed after Boost port redesign.
