### ISSUE TITLE
connecting libusb in cmake

### ISSUE THREAD

**Issue by Roman-Koshelev** [microsoft/vcpkg#9112]
I am using cmake. How can I include libusb in the assembly? (without cmake everything works)

**Comment by JackBoosY** [comment]
Hi @Roman-Koshelev, libusb doesn't export cmake files, so we can only use `find_path` and `find_library` to solve this issue. Example:
```
find_path(LIBUSB_INCLUDES libusb.h PATH_SUFFIXES libusb-1.0)
find_library(libusb libusb-1.0 REQUIRED)

target_include_directories(... PRIVATE ${LIBUSB_INCLUDES})
target_link_libraries(... PRIVATE ${libusb})
```

**Comment by Roman-Koshelev** [comment]
thanks

**Comment by Roman-Koshelev** [comment]
And where is the libusb finder implemented (which is needed for find_library ())?
