### ISSUE TITLE
Failed to do post-extract rename-in-place. during install of Opencv4

### ISSUE THREAD

**Issue by wsvdyk** [microsoft/vcpkg#9113]
**Describe the bug**
During the installation of OpenCV4 in Powershell (started with administrator rights) I get the following issue:
`Failed to do post-extract rename-in-place.
fs.rename(D:\vcpkg\downloads\tools\powershell-core-6.2.1-windows.partial.11488, D:\vcpkg\downloads\tools\powershell-core-6.2.1-windows, operation not permitted)`

A temporary workaround is to rename this folder manually.

**Environment**
- OS: Windows 10 64 bit
- Compiler: revision

**To Reproduce**
1. .\vcpkg install OpenCV4
2. See error
Repro code when

**Expected behavior**
To rename the folder in question.

**Failure logs** 
PS D:\vcpkg> .\vcpkg install opencv4
The following packages will be built and installed:
  * libjpeg-turbo[core]:x86-windows
  * liblzma[core]:x86-windows
  * libpng[core]:x86-windows
  * libwebp[core]:x86-windows
    opencv4[core,dnn,jpeg,opengl,png,tiff,webp]:x86-windows
  * opengl[core]:x86-windows
  * protobuf[core]:x86-windows
  * tiff[core]:x86-windows
  * zlib[core]:x86-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/9: zlib:x86-windows
Building package zlib[core]:x86-windows...
A suitable version of powershell-core was not found (required v6.2.1). Downloading portable powershell-core v6.2.1...
Extracting powershell-core...
Failed to do post-extract rename-in-place.
fs.rename(D:\vcpkg\downloads\tools\powershell-core-6.2.1-windows.partial.11488, D:\vcpkg\downloads\tools\powershell-core-6.2.1-windows, operation not permitted)

**Comment by rjhuckins** [comment]
Exactly the same thing happened to me on the first attempt to install a package; environment is Windows 10 as administrator:

    C:\Git\vcpkg>vcpkg install 7zip
    Your feedback is important to improve Vcpkg! Please take 3 minutes to complete our survey by running: vcpkg contact --survey
    The following packages will be built and installed:
        7zip[core]:x86-windows
    Starting package 1/1: 7zip:x86-windows
    Building package 7zip[core]:x86-windows...
    A suitable version of powershell-core was not found (required v6.2.1). Downloading portable powershell-core v6.2.1...
    Extracting powershell-core...
    Failed to do post-extract rename-in-place.
    fs.rename(C:\Git\vcpkg\downloads\tools\powershell-core-6.2.1-windows.partial.52064, C:\Git\vcpkg\downloads\tools\powershell-core-6.2.1-windows, operation not permitted)

Just like the OP, after renaming the .partial file manually, the install proceeded without error. If it's any help, some clues:

1. This is a corporate computer and at least some uses of Powershell are disabled.

1. vcpkg is built with telemetry disabled, otherwise McAfee AV deletes it.

**Comment by JackBoosY** [comment]
I think this is a vcpkg bug, and duplicate with #9132.
The current workaround is download and rename it manually.
