### ISSUE TITLE
[rapidstring[core]:x64-windows] build failure - download failed appears the site doesn't exist any longer

### ISSUE THREAD

**Issue by timautry** [microsoft/vcpkg#9115]
**Host Environment**
- OS: [Windows 10 1909 H2 18363.476]
- Compiler: VS2019 v16.3.10 
                   VCToolsInstallDir=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\
                    VCToolsRedistDir=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Redist\MSVC\14.23.27820\
                     VCToolsVersion=14.23.28105

**To Reproduce**

_Note: I am not behind a proxy - I tried going directly to the download location using browser with http 404 page not found - it appears the user has removed his/her github page???_

SYSTEM@ANDROMEDA 11/27/2019 11:28:08 D:\Git\vs2019
->vcpkg install rapidstring
The following packages will be built and installed:
    rapidstring[core]:x64-windows
Starting package 1/1: rapidstring:x64-windows
Building package rapidstring[core]:x64-windows...
-- Downloading https://github.com/boyerjohn/rapidstring/archive/ee433955c1e9cacfaecbf53c0a13318ab5825bd4.tar.gz...
-- Downloading https://github.com/boyerjohn/rapidstring/archive/ee433955c1e9cacfaecbf53c0a13318ab5825bd4.tar.gz... Failed. Status: 22;"HTTP response code said error"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:175 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_github.cmake:132 (vcpkg_download_distfile)
  ports/rapidstring/portfile.cmake:3 (vcpkg_from_github)
  scripts/ports.cmake:94 (include)

Error: Building package rapidstring:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: rapidstring:x64-windows
  Vcpkg version: 2019.09.12-nohash

Additionally, attach any relevant sections from the log files above.

**Failure logs** 
No Additional logs created

**Additional context**
I found another location on github "https://github.com/cenit/rapidstring" but I don't know how to change the portfile.cmake in order to download/build/compile it? I'm technically challenged on this and trying to learn but it seems to elude me?? :(

If someone has the correct version/sha checksum of the rapidstring tar.gz file, please could you email/send it to me so I can drop into my download directory/folder to install it.

**Comment by AlvinZhangH** [comment]
Duplicated to #3205, #5856.

**Comment by timautry** [comment]
This is not a **PROXY ISSUE** and not a duplicate of #3205 or #5856 as they are working with **PROXIES**.

The site no longer exists on github, click on the link in a browser (chrome, edge, ie, firefox, waterfox, opera, etc etc etc.) and you get **Not Found**.

I figured out how to get the file by changing the portfile.cmake as follows:

From:
include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
   **REPO boyerjohn/rapidstring**
    **REF ee433955c1e9cacfaecbf53c0a13318ab5825bd4**
    **SHA512 89e0656323d53dc3c47ba24ad9a032445b0985f21aaace05ea5bdbfb0ade5291193ac06145faf5984bcdff67c2a07a500109ce938174dbf1339fea2d79a6bd10**
    HEAD_REF master
    **PATCHES**
        **fix-cmake-install.patch**
)

To:
include(vcpkg_common_functions)

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    **REPO cenit/rapidstring**
    **REF 2a5fa4a42b37b00e1388f4161b1a96876e25b555**
    **SHA512 dcf93f29fede867ca87830cb5cb77bdb468bb572ff8bbe35e6ce7ddad343dd561276a137e5cf91fbbad079660ccda96857c2b962918b8ad619921a0e420c2a3f**
    HEAD_REF master
    **# PATCHES**
        **# fix-cmake-install.patch**
)

_and applying the patch fix-cmake-install.patch **manually**._

**Comment by NancyLi1013** [comment]
Hi @timautry thnaks for posting this issue and detail description about this issue.
We will investigate this port and try to fix this issue as soon as possible.

**Comment by PhoebeHui** [comment]
@timautry, thanks for reporting this issue!

The author of rapidstring delete their Github repro, we might delete this port as well, however, cenit has a clone of the repo, we will consider if still keep maintain this port in vcpkg.

Background:
https://github.com/microsoft/vcpkg/pull/8912#issuecomment-551969108
https://github.com/microsoft/vcpkg/pull/8912#issuecomment-558246277

**Comment by PhoebeHui** [comment]
This port removed now, see the reason in https://github.com/microsoft/vcpkg/pull/9143#issuecomment-562420725.
