### ISSUE TITLE
[shiva-sfml[core]:x64-windows] build failure - missing sol/xxxxx include files

### ISSUE THREAD

**Issue by ghost** [microsoft/vcpkg#9116]
**Host Environment**
- OS: [Windows 10 1909 H2 18363.476]
- Compiler: revision VS2019 v16.3.10
                                VCToolsInstallDir=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105
                                VCToolsRedistDir=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Redist\MSVC\14.23.27820
                                VCToolsVersion=14.23.28105

**To Reproduce**
SYSTEM@ANDROMEDA 11/27/2019 11:54:13 D:\Git\vs2019
->vcpkg install shiva-sfml
The following packages will be built and installed:
    shiva-sfml[core]:x64-windows
Starting package 1/1: shiva-sfml:x64-windows
Building package shiva-sfml[core]:x64-windows...
-- Using cached E:/Git/vcpkg.downloads/Milerius-shiva-1.0.tar.gz
-- Using source at D:/Git/vs2019/buildtrees/shiva-sfml/src/1.0-2860004d47
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v
    Working Directory: D:/Git/vs2019/buildtrees/shiva-sfml/x64-windows-dbg
    See logs for more information:
      D:\Git\vs2019\buildtrees\shiva-sfml\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:91 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/shiva-sfml/portfile.cmake:18 (vcpkg_install_cmake)
  scripts/ports.cmake:94 (include)

Error: Building package shiva-sfml:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: shiva-sfml:x64-windows
  Vcpkg version: 2019.09.12-nohash

Additionally, attach any relevant sections from the log files above.
**Failure logs** 

-Please attach any additional failure logs mentioned in the console output.
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/3897937/install-x64-windows-dbg-out.log)

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.
The above mentioned log file has 4 fatal errors - 2 missing sol/xxxx include files and 2 with errors over 100, most likely due to the missing include files.
D:\Git\vs2019\buildtrees\shiva-sfml\src\1.0-2860004d47\modules\lua\shiva/lua/lua_helpers.hpp(12): fatal error C1083: Cannot open include file: 'sol/state.hpp': No such file or directory
D:\Git\vs2019\buildtrees\shiva-sfml\src\1.0-2860004d47\modules\sfml\shiva\sfml\inputs\system-sfml-inputs.cpp(92): fatal error C1003: error count exceeds 100; stopping compilation
D:\Git\vs2019\buildtrees\shiva-sfml\src\1.0-2860004d47\modules\sfml\shiva\sfml\graphics\system-sfml-graphics.cpp(22): fatal error C1003: error count exceeds 100; stopping compilation
D:\Git\vs2019\buildtrees\shiva-sfml\src\1.0-2860004d47\modules\sfml\shiva/sfml/resources/sfml-resources-registry.hpp(17): fatal error C1083: Cannot open include file: 'sol/resolve.hpp': No such file or directory

**Comment by NancyLi1013** [comment]
Hi @timautry thanks for posting this issue.
I try to reproduce this issue on my local. It is blocked by `shiva`, it failed with this:
`Python config failure: Python is 32-bit, chosen compiler is 64-bit`
Due to that python currently cannot support 64 bit.  Related PR #7964
So I am unable to process this issue now.

**Comment by timautry** [comment]
I would elaborate, but vcpkg (I hope you meant vcpkg instead of python as VS has both 32/64 bit versions of python2/3) can support 64 bit versions of most tools, providing you either don't use x86 triplets or create a separate vcpkg instance for each architecture and bitness. It also helps to create a test/dev/prod instance so you can push the boundaries of the software one is using to develop with.

**Comment by NancyLi1013** [comment]
@timautry we  will continue to investigate this issue after python issue is solved.

**Comment by JackBoosY** [comment]
Please keep this issue open before we resolve it.

**Comment by timautry** [comment]
I close, I no longer use product.

**Comment by dg0yt** [comment]
Is this still an active issue?
