### ISSUE TITLE
mongo-c-driver build failure

### ISSUE THREAD

**Issue by sbrown89** [microsoft/vcpkg#9118]
**Fedora 31 fresh install**
- OS: Fedora 31
- Compiler: gcc version 9.2.1 20190827 (Red Hat 9.2.1-1) (GCC)

**To Reproduce**
`./vcpkg --triplet x64-linux install mongo-c-driver`

**Failure logs** 
[224/225] : && /usr/lib64/ccache/cc -fPIC -g -rdynamic
src/libmongoc/CMakeFiles/mongoc-stat.dir//tools/mongoc-stat.c.o -o src/libmongoc/mongoc-stat
-Wl,-rpath,/media/psf/lib/vcpkg/buildtrees/mongo-c-driver/x64-linux-dbg/src/libmongoc:/media/psf/lib
/vcpkg/buildtrees/mongo-c-driver/x64-linux-dbg/src/libbson src/libmongoc/libmongoc-1.0.so.0.0.0
/media/psf/lib/vcpkg/installed/x64-linux/debug/lib/libssl.a
/media/psf/lib/vcpkg/installed/x64-linux/debug/lib/libcrypto.a -lrt -lresolv
/media/psf/lib/vcpkg/installed/x64-linux/debug/lib/libz.a src/libbson/libbson-1.0.so.0.0.0 -pthread
&& :
FAILED: src/libmongoc/mongoc-stat
: && /usr/lib64/ccache/cc -fPIC -g -rdynamic
src/libmongoc/CMakeFiles/mongoc-stat.dir//tools/mongoc-stat.c.o -o src/libmongoc/mongoc-stat
-Wl,-rpath,/media/psf/lib/vcpkg/buildtrees/mongo-c-driver/x64-linux-dbg/src/libmongoc:/media/psf/lib
/vcpkg/buildtrees/mongo-c-driver/x64-linux-dbg/src/libbson src/libmongoc/libmongoc-1.0.so.0.0.0
/media/psf/lib/vcpkg/installed/x64-linux/debug/lib/libssl.a
/media/psf/lib/vcpkg/installed/x64-linux/debug/lib/libcrypto.a -lrt -lresolv
/media/psf/lib/vcpkg/installed/x64-linux/debug/lib/libz.a src/libbson/libbson-1.0.so.0.0.0 -pthread
&& :
/usr/bin/ld: src/libmongoc/libmongoc-1.0.so.0.0.0: undefined reference to dlsym
/usr/bin/ld: src/libmongoc/libmongoc-1.0.so.0.0.0: undefined reference to dlerror
/usr/bin/ld: src/libmongoc/libmongoc-1.0.so.0.0.0: undefined reference to dladdr
/usr/bin/ld: src/libmongoc/libmongoc-1.0.so.0.0.0: undefined reference to dlopen
/usr/bin/ld: src/libmongoc/libmongoc-1.0.so.0.0.0: undefined reference to dlclose
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

**Additional context**
Can build manually with no issues.

**Comment by NancyLi1013** [comment]
Hi @sbrown89 thanks for posting this issue.
It seems that there is no linkage to `dl`.
Could you please add  `link_libraries(-ldl)` in _src/libmongoc/CMakeLists.txt_ file?

**Comment by sbrown89** [comment]
For a quick test, I added the -ldl linker to line 647 in src/libmongoc/CMakeLists.txt and it did fix the issue on Fedora.
`target_link_libraries (mongoc_shared ${LIBRARIES} ${BSON_LIBRARIES} "-ldl")`

**Comment by sbrown89** [comment]
Second test, i removed -ldl from line 647 and placed `link_libraries(-ldl)` at line 31 in src/libmongoc/CMakeLists.txt. Both compile and link properly.

**Comment by NancyLi1013** [comment]
@sbrown89 thanks for your test and feedback. 
It should be related with your environment workaround. Since this issue has been solved. I close it now.
Please open a new issue if you have other problems.
