### ISSUE TITLE
 Gtk-WARNING **: Could not find the icon 'window-minimize-symbolic-ltr'.

### ISSUE THREAD

**Issue by SoumenKunduTantra** [microsoft/vcpkg#9127]
I am having the same issue https://github.com/Microsoft/vcpkg/issues/4417#issue-367426244.

![image](https://user-images.githubusercontent.com/51443098/69796928-e632c200-11f4-11ea-9140-ed75583d3b88.png)

I followed the solutions also https://github.com/Microsoft/vcpkg/issues/4417#issuecomment-524171005. Still I am not getting minimize, maximize and close icon.

**Comment by itayzafrir** [comment]
Same here, solution proposed in https://github.com/microsoft/vcpkg/issues/4417#issuecomment-524171005 didn't work for me either. 

I installed GTK via vcpkg

**Comment by JackBoosY** [comment]
Duplicate with #6554.

**Comment by SoumenKunduTantra** [comment]
Thanks @itayzafrir . Your solution https://github.com/microsoft/vcpkg/issues/9127#issuecomment-559525463 worked.

**Comment by madcdevelop** [comment]
Thanks @itayzafrir . I modified your https://github.com/microsoft/vcpkg/issues/9127#issuecomment-559525463 solution. I copied the `Adwaita` and `hicolor` folders from `C:\msys64\mingw64\share\icons\` to `C:\gtk-build\gtk\x64\release\share\icons`
I created the icons folder to make it work.
