### ISSUE TITLE
nanodbc nanodbc error LNK2019: unresolved external symbol

### ISSUE THREAD

**Issue by Charles-lee** [microsoft/vcpkg#9128]
**Describe the bug**
I am unable to use nanodbc which was built using vcpkg.
I get error LNK2019: unresolved external symbol error on every method call.

It related to the closed issue #6157 but not resolved as  I think.

**Environment**
- OS: Windows10
- Compiler: Visual Studio 2019

**To Reproduce**
1. Install nanodbc
2. Create a console project and add the code of https://github.com/nanodbc/nanodbc/blob/master/example/example_unicode_utils.h and https://github.com/nanodbc/nanodbc/blob/master/example/usage.cpp
3. Build and see error
It can be rerpoduced when build debug or release mode on x86 or x64.

**Expected behavior**
No build error.

**Failure logs** 
error LNK2019: unresolved external symbol "public: __cdecl nanodbc::connection::connection(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,long)" (??0connection@nanodbc@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@00J@Z) referenced in function main

**Additional context**
[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/3901085/config-x64-windows-out.log)
[config-x86-windows-out.log](https://github.com/microsoft/vcpkg/files/3901088/config-x86-windows-out.log)

**Comment by LilyWangL** [comment]
Thanks for posting this issue. This issue has been fixed. So I am closing this issue for now.
