### ISSUE TITLE
Failed to rename files using fs.rename

### ISSUE THREAD

**Issue by james-frezz** [microsoft/vcpkg#9132]
Dear developers,

I have cloned a repo today and built+configured vcpkg according to the doc of the README provided, which went fine. The problem is that this command `vcpkg install giflib:x86-windows-static` (I launched it from powershell as well as all the prior commands) fails with the following output:
```
Failed to do post-extract rename-in-place.
fs.rename(C:\tools\vcpkg\downloads\tools\powershell-core-6.2.1-windows.partial.2044, C:\tools\vcpkg\downloads\tools\powershell-core-6.2.1-windows, operation not permitted)
```
No additional information about any crashlog is specified.
I'm using Windows 10 Pro 1803, locale: ru_RU

How can I get over this?
Best regards

**Comment by james-frezz** [comment]
Installation of other libs also fails. The errors resemble each other and all point at `fs.rename`.

**Comment by timautry** [comment]
@james-frezz seems like a permissions issue, does the userid/login being used have rights to rename files/folders in the vcpkg folder(s)?

**Comment by james-frezz** [comment]
Sure. I run as admin.

**Comment by james-frezz** [comment]
I should mention that I actually needed to build `tesseract`. At first, I tried to do this according to this [man](https://github.com/charlesw/tesseract/wiki/Compiling-Tesseract-and-Libleptonica-(using-vcpkg)). This didn't go smooth and I got the error like the above. So, I went for [this](https://github.com/tesseract-ocr/tesseract/wiki/Compiling#windows) and chose the way "For visual studio project using tesseract". It also gave me errors, but I've managed to circumvent them, following these steps:
1) During installation process I had to delete some folders, which couldn't be renamed by `fs.rename` – the function kept throwing `operation not permitted` error.
2) I had to delete `PREFER NINJA` directive manually from each and every `portfile.cmake`. (as advised [here](https://github.com/microsoft/vcpkg/issues/2895#issuecomment-368913846)
3) I had to replace `vcpkg_get_windows_sdk(WINDOWS_SDK)` with `set(WINDOWS_SDK "<I opened up one of my Visual Studio solutions and pasted the target SDK-version here>")` for OpenGL package. Probably, not the wisest thing to do but it worked still.

These steps helped me to apply `vcpkg install tesseract:x64-windows`.

**Comment by james-frezz** [comment]
On my home machine it works like a charm without these steps, though... Probably, some restrictions of the enterprise... Pity, there's no log available, though.

**Comment by james-frezz** [comment]
If you have Visual Studio 2017, consider updating it. As of build 15.9.17 the problems (2) and (3) were gone, but problem (1) persists - `fs.rename` keeps throwing errors. What are the prerequisities for `vcpkg`, conisdering folder rights?

**Comment by JackBoosY** [comment]
@vicroms Can you have a look?

Thanks.

**Comment by chrisfromwork** [comment]
Is there any progress/update on this bug?

**Comment by JackBoosY** [comment]
@strega-nil Could you have a look?

**Comment by strega-nil** [comment]
I have no idea where to even start; could you put in the ACLs for `C:\tools\vcpkg`?

**Comment by etheory** [comment]
I'm still getting this, and it basically makes vcpkg useless. It previously worked fine. This seems to have started happening after updating to the latest version, but unfortunately I don't know what version I had previously that was working.

**Comment by JackBoosY** [comment]
The reason is that the function `fs.rename` seems to have a bug, temporary workaround is to manually rename the file or folder and try again.

**Comment by etheory** [comment]
That's not a practical work-around. In my case that's happening for basically every package, which, when you are trying to install openimageio, is too many to reasonably do manually.

**Comment by JackBoosY** [comment]
Ping @dan-shaw.

**Comment by swilson314** [comment]
I've run into this problem a number of times and have always been able to rename the file and restart. However, now I'm trying to run: vcpkg upgrade --no-dry-run. After renaming the file I again try to run upgrade, but I get the following response: All installed packages are up-to-date with the local portfiles.

It's unclear to me how I can proceed....

**Comment by BillyONeal** [comment]
Most likely it isn't a permissions issue but the target file being locked/open

**Comment by BillyONeal** [comment]
@swilson314 

> I've run into this problem a number of times [,,,]

That report sounds more like https://github.com/microsoft/vcpkg/issues/11457 -- vcpkg probably tried to install those prerequisite tools before even determining that changes needed to be applied.

**Comment by etheory** [comment]
From a fresh install of vcpkg today, this is STILL happening. How long is it going to take before vcpkg is actually usable? Is anyone even actually able to use vcpkg?

**Comment by JackBoosY** [comment]
@etheory I confirm that's a std experimental filesystem bug.

**Comment by etheory** [comment]
> @etheory I confirm that's a std experimental filesystem bug.

Is someone looking at fixing it? I'm quite surprised that it was on the 24th of March that I first reported this and I've come back to see if I can finally use vcpkg, and it still doesn't work :stuck_out_tongue_winking_eye:

**Comment by BillyONeal** [comment]
> @etheory I confirm that's a std experimental filesystem bug.

I'm not sure what you mean by this.... if it were a `std::experimental::filesystem` bug we would be having all users seeing it rather than the small minority in this issue.

> Is someone looking at fixing it?

`std::experimental::filesystem` will not ever be changed, it will be left in a bug for bug compatible state until it is removed. vcpkg should not be trying to use `std::experimental::filesystem` unless it is built with VS2015.

**Comment by strega-nil** [comment]
@BillyONeal I believe we use experimental::filesystem for all bootstraps; this is the problem with building with MSBuild.

**Comment by etheory** [comment]
I really really want to be able to use vcpkg, but it quite simply doesn't work.

Can I please just get a clear answer as to what the timeframe is for someone to fix this?
I don't accept that it can't be worked around at the code level.
If there really is some issue with std::experimental::filesystem then don't use it.
If someone can show me the part of the code that fails, I'll fix it myself if I have to.

I'm just looking for a clear answer as to how to get this to work.
It's very frustrating waiting for a clear answer and a fix.

Again, are people actually able to use vcpkg, or is it literally broken for everyone?

**Comment by JackBoosY** [comment]
@etheory I will fix this bug as soon as possible.

**Comment by JackBoosY** [comment]
@etheory Could you please test #12774?
Thanks.

**Comment by BillyONeal** [comment]
@etheory Yes, people are able to use it. The problem hasn't been fixed because we have had difficulty reproing it

**Comment by etheory** [comment]
> @etheory Could you please test #12774?
> Thanks.

Thanks @JackBoosY I'm testing it now....

**Comment by strega-nil** [comment]
@etheory it should compile now.

**Comment by etheory** [comment]
Thanks, it's compiling ;-). I'm adding notes here: https://github.com/microsoft/vcpkg/pull/12774.
Really really appreciate it! Testing now if it can install something. Fingers crossed!
