### ISSUE TITLE
Warp speed Data Transfer (WDT)

### ISSUE THREAD

**Issue by sspurgeon** [microsoft/vcpkg#9134]
Library name: Warp speed Data Transfer (WDT)

Library description: Warp speed Data Transfer (WDT) is an embeddedable library (and command line tool) aiming to transfer data between 2 systems as fast as possible over multiple TCP paths

Source repository URL: https://github.com/facebook/wdt

Project homepage (if different from the source repository): https://en-gb.facebook.com/WdtOpenSource/

Anything else that is useful to know when adding (such as optional features the library may have that should be included): thanks for considering this!

**Comment by NancyLi1013** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
