### ISSUE TITLE
[liblzma] exports incorrect targets

### ISSUE THREAD

**Issue by invy** [microsoft/vcpkg#9136]
CMakeLists.txt in liblzma is buggy and exports incorrect definitions, like:
https://github.com/microsoft/vcpkg/blob/e4524f656b885e76f9adf2356758b0ac994732e1/ports/liblzma/CMakeLists.txt#L145

Which causes build failure in downstream packages and applicatioins, because PUBLIC adds -DHAVE_CONFIG_H everywhere, where target_link_libraries( .... LibLZMA::LibLZMA) is used!

**Comment by PhoebeHui** [comment]
@invy, thanks for reporting this issue! Would you like to provide us sample code to repro the failures?

**Comment by invy** [comment]
Something like this:
CMakeLists.txt:
```
find_package(LibLZMA REQUIRED)
add_executable(test main.cpp)
target_link_libraries(test PRIVATE LibLZMA::LibLZMA)
```

main.cpp:
```
#ifdef HAVE_CONFIG_H
I am invalid code, or non existant header
#endif
main()
{
  std::cout << "hello world\n";
}

```

**Comment by PhoebeHui** [comment]
@invy, thanks for sharing the sample with us! Above PR should address this issue.

**Comment by PhoebeHui** [comment]
@invy, the PR has been merged, please get vcpkg latest source and try again.
