### ISSUE TITLE
Fatal error building activemq-cpp windows-static

### ISSUE THREAD

**Issue by rotrida** [microsoft/vcpkg#9138]
We are facing problems building activemq-cpp for windows (x86 static)

LINK : fatal error LNK1181: cannot open input file 'libapr-1.lib' [C:\DEV\vcpkg\buildtrees\activemq-cpp\src\-library-3-dac1f8e3f5\vs2010-build\activemq-cpp.vcxproj]

Package: activemq-cpp:x86-windows-static
Vcpkg version: 2019.09.12-nohash

**Comment by AlvinZhangH** [comment]
Hi, @rotrida libapr-1.lib should not be generated in a static version, so can not build activemq-cpp for windows (x86 static).

**Comment by AlvinZhangH** [comment]
Please feel free to reopen this issue if it is still a problem for you.

**Comment by rotrida** [comment]
It's fine Alvin,

Thank you for answering.

Rodrigo.

**Comment by JackBoosY** [comment]
We need to keep this issue open until it is resolved.
