### ISSUE TITLE
vcpkg integrate install does not work on win7sp1 with vs2015 professional update3

### ISSUE THREAD

**Issue by principality** [Microsoft/vcpkg#914]
- The machine environment: win7sp1, locale: zh-cn.
- Step:
   - .\bootstrap-vcpkg.bat. Done!
   - .\vcpkg integrate install. Done! with 
> Applied user-wide integration for this vcpkg root.
> All MSBuild C++ projects can now #include any installed libraries.
> Linking will be handled automatically.
> Installing new libraries will make them instantly available.
> CMake projects should use -DCMAKE_TOOLCHAIN_FILE=d:/project/c++/vcpkg/scripts/buildsystems/vcpkg.cmake

- Outcome expected: open a project (uWebsocket) in vs2015 pro update3 with all vcpkg packages work well
- Outcome actually: vs2015 pro prompts it can not find external include header files, but if I create a CMakeLists.txt with -DCMAKE_TOOLCHAIN_FILE=d:/project/c++/vcpkg/scripts/buildsystems/vcpkg.cmake, it works.

**Comment by ras0219-msft** [comment]
Thanks for the expected/actually!

As a first sanity check -- does the architecture of the project match the architecture of the packages you've installed? A common mistake is to install the default (x86-windows) versions of packages but try to build x64 projects.

**Comment by principality** [comment]
Yes. This problem is caused by the architecture mis-match. Sorry for reporting this.
