### ISSUE TITLE
Support for tensorflow 2.0 (and 1.15)

### ISSUE THREAD

**Issue by trade-commander1** [microsoft/vcpkg#9141]
Dear Ladies and Gentlemen,
when do you support tensorflow 2.0 ß

The current version available through vcpkg is 1.14.
The latest official tensorflow  1.xx versions is 1.15. (APIr1)

The latest version is 2.0.

Thank you for comments.

**Comment by cloudhan** [comment]
tensorflow, pytorch, mxnet, these deep learning libraries, you name it, do not deserve a port in vcpkg. They are simply too huge, too complex to be supported at this level. tensorflow and pytorch both have arcane build system, tensorflow use google's inhouse build system Bazel. pytorch building involves 3~5 stages, IIRC, code generation with python script as its generator. All of them have huge amount of flags for customization and enormous amount of dependencies (usually as submodules). Also, all of them requires hours to build when cuda is enabled. They just don't deserve the engineer  effort.

**Comment by photex** [comment]
@cloudhan libtorch, and the onnx-runtime projects have binary releases available these days. Would those be suitable for inclusion?

**Comment by cloudhan** [comment]
vcpkg is a building and management system that builds libraries from source, currently libtorch and onnx-runtime has many customization flags that does not work well when mixed up, the ecosystem is quiet complex also, e.g. quantization and backends. Treat them as frameworks, instead of libraries. So I don't think they are suitable for inclusion at the moment.

**Comment by photex** [comment]
OpenCV shouldn't be included then by this logic. :shrug: Or Boost. Probably some other examples in the ports collection.

Anyway, sorry to add to the noise.

**Comment by cloudhan** [comment]
you are welcome to contribute a port ;)

**Comment by jgehw** [comment]
I think you can close this, as I upgraded tensorflow to 2.3 in #13028.

**Comment by JonLiu1993** [comment]
Solved by #13028
