### ISSUE TITLE
[absl] link failure for StrCat with >4 arguments

### ISSUE THREAD

**Issue by matled** [microsoft/vcpkg#9142]
**Host Environment**
- OS: Windows 10
- Compiler: MSVC 19.23.28107.0 (same happened with clang-cl)

**To Reproduce**
`vcpkg install abseil:x64-windows` and try to compile a binary calling `absl::StrCat(1, 2, 3, 4, 5);` using this [CMakeLists.txt](https://github.com/microsoft/vcpkg/files/3903281/CMakeLists.txt) (I tried to keep it as simple as possible).
See the transcript below for the exact steps I took to observe the issue.

**Failure logs** 
[transcript.txt](https://github.com/microsoft/vcpkg/files/3903280/transcript.txt)
```
fail.obj : error LNK2019: unresolved external symbol "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl absl::strings_internal::CatPieces(class std::initializer_list<class std::basic_string_
view<char,struct std::char_traits<char> > >)" (?CatPieces@strings_internal@absl@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$initializer_list@V?$basic_string_view@DU?$char_traits@D@std@@@std@@@4@@Z) referenced i
n function "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl absl::StrCat<>(class absl::AlphaNum const &,class absl::AlphaNum const &,class absl::AlphaNum const &,class absl::AlphaNum const
 &,class absl::AlphaNum const &)" (??$StrCat@$$V@absl@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBVAlphaNum@0@0000@Z) [C:\Users\matled\source\strcat\build\fail.vcxproj]
```

**Additional context**
[absl::StrCat](https://github.com/abseil/abseil-cpp/blob/master/absl/strings/str_cat.h#L340) is overloaded and uses a variadic for >4 arguments.

Note: I'm very much unfamiliar with the Windows build system/ABI but collected a bit more information:

Running dumpbin on the absl library shows CatPieces, but the symbol name differs a bit from the one above:
```
> dumpbin /SYMBOLS absl_strings.lib |grep CatPieces
215 00000000 SECT78 notype ()    External     | ?CatPieces@strings_internal@absl@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$initializer_list@Vstring_view@absl@@@4@@Z (class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl absl::strings_internal::CatPieces(class std::initializer_list<class absl::string_view>))
```

Checking out abseil-cpp into the directory containing the `CMakeLists.txt` and replacing `find_package` with `add_subdirectory(abseil-cpp)` compiles (surprisingly to me) without any issues.

**Comment by NancyLi1013** [comment]
Hi @matled thanks for posting this issue.
It seems that this issue is related with `set(CMAKE_CXX_STANDARD 17)`.
Although absl::StrCat has supported more than 4 arguments, it is different from those functions that support less than 4 arguments. So they will have different results.
I guess `std :: basic_string` has different requirements for C++ 17.
You can remove `set(CMAKE_CXX_STANDARD 17)` from your CMakeLists.txt and try it again.
I can build successfully on my local.

**Comment by matled** [comment]
Thanks a lot for looking into this. I can confirm that I can build successfully when removing the line.

Is there any good solution to this? It sounds like different C++ versions (`/std:c++14` vs `/std:c++17`) can cause ABI incompatibilities (potentially through incompatible implementations of the standard library).

Would it make sense/be possible to create a triplet configuration file that overrides the C++ standard for abseil?

**Comment by MikeGitb** [comment]
> I guess std :: basic_string has different requirements for C++ 17.

FYI: I doubt std::string is the problem. However,  abseil either uses `std::string_view` or their home grown equivalent of it depending on the chosen CXX standard.

**Comment by mbxx** [comment]
@MikeGitb makes a good point, and the variadic `StrCat` overload calls `absl::strings_internal::CatPieces`, which takes a single `std::initializer_list<absl::string_view>` parameter.  So if Abseil is being compiled with a different C++ version than the code calling `StrCat`, (which it sounds like is the case,) then this error makes sense: some code is expecting `CatPieces(std::initializer_list<absl::string_view>)` to exist while other code is expecting `CatPieces(std::initializer_list<std::string_view>)` to exist, but str_cat.cc only defined one of them.

Abseil has been strongly encouraging folks to build all code from source with the same compiler flags, which would avoid this problem.  If vcpkg wants to support building different libraries at different library versions, then it likely make sense to force `absl::string_view` and `std::string_view` to always be different types when using vcpkg.  The way to do this is to patch `ABSL_OPTION_USE_STD_STRING_VIEW` to be 0 (https://github.com/abseil/abseil-cpp/blob/12bc53e0318d80569270a5b26ccbc62b52022b89/absl/base/options.h#L159)

**Comment by NancyLi1013** [comment]
@mbxx thanks for your detail description about this issue. We will try to use the way that you provided above to fix this issue.

Thanks again for your support for vcpkg.

**Comment by gix** [comment]
A nicer thing would be the ability to set the C++ standard version via triplet. AFAIK this isn't possible currently, so locally I have updated abseil's portfile.cmake and added `-DCMAKE_CXX_STANDARD=20`.

**Comment by MikeGitb** [comment]
That would be the ideal.  

I wouldn't be surprised though,  if many libraries would ignore that setting, because they have their own - more or less proprietary - method to set the cxx standard.

**Comment by NancyLi1013** [comment]
Hi all, thanks for further investigation about this issue.
Since cxx 20 is only available on VS2019. But not everyone prefers to use  VS2019.
So it is better to define `ABSL_OPTION_USE_STD_STRING_VIEW  `0 to solve this issue currently.

**Comment by MikeGitb** [comment]
Not that I'm complaining, but what does this have to do with c++20?

**Comment by gix** [comment]
> Since cxx 20 is only available on VS2019. But not everyone prefers to use VS2019.
> So it is better to define `ABSL_OPTION_USE_STD_STRING_VIEW `0 to solve this issue currently.

No, `string_view` is available with C++17 (and since VS2017).

*If* someone modifies his local absl port he should choose the C++ standard version to match the rest of his stack.

For a *general* solution controlling `CMAKE_CXX_STANDARD` via triplet would be nice as a first step (some ports might need modification though if they use custom options for the same thing).

**Comment by NancyLi1013** [comment]
Thanks again for you joining this discussion.
This issue has been fixed now.
Please try to update vcpkg and use it.
