### ISSUE TITLE
Building package opengl:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by asglglgl** [microsoft/vcpkg#9145]
Error: Building package opengl:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: opengl:x64-windows
  Vcpkg version: 2019.09.12-nohash

**Comment by james-frezz** [comment]
@asglglgl, Try this:
replace `vcpkg_get_windows_sdk(WINDOWS_SDK)` with `set(WINDOWS_SDK "<I opened up one of my Visual Studio solutions and pasted the target SDK-version here>")` for OpenGL package portfile. Probably, not the best way, but worked for me.

**Comment by JackBoosY** [comment]
Hi @asglglgl, thanks for reporting this issue!
Please provide the error log displayed on the console.

Thanks.

**Comment by asglglgl** [comment]
> @asglglgl，您好，感谢您报告此问题！
> 请提供控制台上显示的错误日志。
> 
> 谢谢。

Starting package 1/32: opengl:x64-windows
Building package opengl[core]:x64-windows...
CMake Error at ports/opengl/portfile.cmake:16 (message):
  Portfile not yet configured for Windows SDK with version:
Call Stack (most recent call first):
  scripts/ports.cmake:94 (include)


Error: Building package opengl:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: opengl:x64-windows
  Vcpkg version: 2019.09.12-nohash

**Comment by asglglgl** [comment]
> @asglglgl，试试这个：
> 替换`vcpkg_get_windows_sdk(WINDOWS_SDK)`与`set(WINDOWS_SDK "<I opened up one of my Visual Studio solutions and pasted the target SDK-version here>")`支持OpenGL包portfile。可能不是最好的方法，但是对我有用。“ <”和“>”用于占位符-删除它们-引号之间应只包含数字和点。

think you

**Comment by james-frezz** [comment]
`> > @asglglgl，您好，感谢您报告此问题！
> > 请提供控制台上显示的错误日志。
> > 谢谢。
> 
> Starting package 1/32: opengl:x64-windows
> Building package opengl[core]:x64-windows...
> CMake Error at ports/opengl/portfile.cmake:16 (message):
> Portfile not yet configured for Windows SDK with version:
> Call Stack (most recent call first):
> scripts/ports.cmake:94 (include)
> 
> Error: Building package opengl:x64-windows failed with: BUILD_FAILED
> Please ensure you're using the latest portfiles with `.\vcpkg update`, then
> submit an issue at https://github.com/Microsoft/vcpkg/issues including:
> Package: opengl:x64-windows
> Vcpkg version: 2019.09.12-nohash`

I had the very same problem - there also was nothing after `Portfile not yet configured for Windows SDK with version:`

**Comment by james-frezz** [comment]
> > @asglglgl，试试这个：
> > 替换`vcpkg_get_windows_sdk(WINDOWS_SDK)`与`set(WINDOWS_SDK "<I opened up one of my Visual Studio solutions and pasted the target SDK-version here>")`支持OpenGL包portfile。可能不是最好的方法，但是对我有用。“ <”和“>”用于占位符-删除它们-引号之间应只包含数字和点。
> 
> think you

Did this work for you?

**Comment by asglglgl** [comment]
> > > @asglglgl，试试这个：
> > > 替换`vcpkg_get_windows_sdk(WINDOWS_SDK)`与`set(WINDOWS_SDK "<I opened up one of my Visual Studio solutions and pasted the target SDK-version here>")`支持OpenGL包portfile。可能不是最好的方法，但是对我有用。“ <”和“>”用于占位符-删除它们-引号之间应只包含数字和点。
> > 
> > 
> > think you
> 
> Did this work for you?

oh  think you  i set "set(WINDOWS_SDK "8.1""  will be success,but set 10 will be fail.

**Comment by asglglgl** [comment]
> > > @asglglgl，您好，感谢您报告此问题！
> > > 请提供控制台上显示的错误日志。
> > > 谢谢。
> > 
> > 
> > Starting package 1/32: opengl:x64-windows
> > Building package opengl[core]:x64-windows...
> > CMake Error at ports/opengl/portfile.cmake:16 (message):
> > Portfile not yet configured for Windows SDK with version:
> > Call Stack (most recent call first):
> > scripts/ports.cmake:94 (include)
> > Error: Building package opengl:x64-windows failed with: BUILD_FAILED
> > Please ensure you're using the latest portfiles with `.\vcpkg update`, then
> > submit an issue at https://github.com/Microsoft/vcpkg/issues including:
> > Package: opengl:x64-windows
> > Vcpkg version: 2019.09.12-nohash
> 
> I had the very same problem - there also was nothing after `Portfile not yet configured for Windows SDK with version:`

**Comment by asglglgl** [comment]
> > > > @asglglgl，您好，感谢您报告此问题！
> > > > 请提供控制台上显示的错误日志。
> > > > 谢谢。
> > > 
> > > 
> > > Starting package 1/32: opengl:x64-windows
> > > Building package opengl[core]:x64-windows...
> > > CMake Error at ports/opengl/portfile.cmake:16 (message):
> > > Portfile not yet configured for Windows SDK with version:
> > > Call Stack (most recent call first):
> > > scripts/ports.cmake:94 (include)
> > > Error: Building package opengl:x64-windows failed with: BUILD_FAILED
> > > Please ensure you're using the latest portfiles with `.\vcpkg update`, then
> > > submit an issue at https://github.com/Microsoft/vcpkg/issues including:
> > > Package: opengl:x64-windows
> > > Vcpkg version: 2019.09.12-nohash
> > 
> > 
> > I had the very same problem - there also was nothing after `Portfile not yet configured for Windows SDK with version:`

you can use james-frezz's function  try  ,i use the function the problem is slove

**Comment by asglglgl** [comment]
> > > > @asglglgl，试试这个：
> > > > 替换`vcpkg_get_windows_sdk(WINDOWS_SDK)`与`set(WINDOWS_SDK "<I opened up one of my Visual Studio solutions and pasted the target SDK-version here>")`支持OpenGL包portfile。可能不是最好的方法，但是对我有用。“ <”和“>”用于占位符-删除它们-引号之间应只包含数字和点。
> > > 
> > > 
> > > think you
> > 
> > 
> > Did this work for you?
> 
> oh think you i set "set(WINDOWS_SDK "8.1"" will be success,but set 10 will be fail.

the problem is slove ,think you vevy much

**Comment by JackBoosY** [comment]
Please re-install Windows SDK 10 using Visual Studio Installer.

Thanks.

**Comment by asglglgl** [comment]
> Please re-install Windows SDK 10 using Visual Studio Installer.
> 
> Thanks.

 think you,

**Comment by james-frezz** [comment]
> Please re-install Windows SDK 10 using Visual Studio Installer.
> 
> Thanks.

This helps to overcome some problems, but some still persist - as described [here](https://github.com/microsoft/vcpkg/issues/9132).

**Comment by JackBoosY** [comment]
@james-frezz I think these are two different issues.
