### ISSUE TITLE
Rebuilding package second time fails, because patches cannot be applied by vcpkg_apply_patches command

### ISSUE THREAD

**Issue by invy** [microsoft/vcpkg#9147]
Scenario:
I'm building a package, then either build fails or I uninstall the package and install it again.
The copy of sources in buildtrees however has patches applied from the first time I've (tried) to build the package. Second time patches cannot be applied and build fails.
Workaround: remove corresponding package from buildtree.

This happens when I use vcpkg_apply_patches directly and not when patches are applied using vcpkg_from_github.

**Comment by vicroms** [comment]
`vcpkg_apply_patches` is deprecated, we don't recommend its use precisely because of the situation you described. 

When patches are specified in the `vcpkg_from_*` or `vcpkg_extract_source_archives_ex` functions, the patch files contents are used to calculate a hash used in the directory name where the sources are extracted. This ensures that patches are always applied to a fresh copy of the sources.

**Comment by invy** [comment]
Thank you for clarification. So what would be the proper way to apply patches conditionally (if such need araises)?
Also please update documentation accordingly, as it doesn't inform about deprecation:
https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/vcpkg_apply_patches.md

**Comment by vicroms** [comment]
You should check your conditions before calling `vcpkg_from_*` or `vcpkg_extract_source_archive_ex`.

```
if (condition)
    vcpkg_from_github(
        ...
       PATCHES "patch1.patch"
    )
else()    
    vcpkg_from_github(
        ...
       # PATCHES -- no patches
    )
endif()
```

**Comment by Neumann-A** [comment]
Better:
Introduce a variable called `PATCHES` and conditionally `list(APPEND)` to it. This reduces the amount of written code and does not duplicate the function call.

**Comment by fabienfl-orc** [comment]
> Also please update documentation accordingly, as it doesn't inform about deprecation:
> https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/vcpkg_apply_patches.md

Yes please

**Comment by PhoebeHui** [comment]
The docs has been updated, so this issue can be closed now.
