### ISSUE TITLE
How do I keep an installation up to date without needing to completely re-clone and recompile

### ISSUE THREAD

**Issue by PhilipOakley** [microsoft/vcpkg#9148]
The Git vcbuild [script ](https://github.com/git-for-windows/git/blob/master/compat/vcbuild/vcpkg_install.bat)(for building Git on Visual studio) will detect the installation of vckpg directory clone, or clone and compile the vcpkg.

However if over the months the vcpkg latest has fixed bugs or improves etc, there is no indicated method of detecting that there has been any update. The user has to wait until failure, get frustrated, maybe [determine the vcpkg cause](https://lore.kernel.org/git/0b2124b5-6d40-08bb-6cc5-a8cef2b7a9b1@syntevo.com/), finally delete/rename the old clone and start again. The re-compile can be long and the clone takes a while (e.g. three quarters of an hour it felt like).

What are the instructions for keeping a user's vcpkg up to date, so that only fixes etc are fetched/pulled, and only those fixes need re-compiling, so that automatically they can get the best upstream experience?

**Comment by vicroms** [comment]
@PhilipOakley 

To update your local sources use `git pull`, this will also update your port recipes. If there has been any changes to vcpkg, you will get a message to re-bootstrap each time you run a command.

After pulling the new sources you can also update your installed packages by running:

```
./vcpkg update
./vcpkg upgrade --no-dry-run
```

**Comment by PhoebeHui** [comment]
@PhilipOakley , feel free to reopen this issue if this still be a problem for you.

**Comment by PhilipOakley** [comment]
Will the documentation be updated to include the advice?

At the moment the initial the Git for Windows automation is left with a hidden manual step, so being able to point to a reference document when updating that automation would be useful.
