### ISSUE TITLE
[libqglviewer] update to 2.7.2

### ISSUE THREAD

**Issue by bjornpiltz** [microsoft/vcpkg#9149]
Library name: libqglviewer

New version number: 2.7.2

This is a minor Release, but there are two small fixes that would be very useful.
* "Fix includes in camera.h" (A compile error when including <QGLViewer>)
* "Fix deprecated message in constructor" (an unnecessary qWarning())

See http://libqglviewer.com/changeLog.html

**Comment by AlvinZhangH** [comment]
@bjornpiltz , the PR has been merged, please get latest source and try again.
