### ISSUE TITLE
[libpq & libpqxx] PostgreSQL link static library failure

### ISSUE THREAD

**Issue by NIKEA-SOFT** [microsoft/vcpkg#9150]
**Host Environment**
- OS: [Windows 7]
- Compiler: VS2019 x64

**To Reproduce**
`./vcpkg install libpqxx:x64-windows-static`

**Failure logs** 
1>libpqd.lib(fe-connect.c.obj) : error LNK2019: ссылка на неразрешенный внешний символ __imp_FreeCredentialsHandle в функции closePGconn
1>libpqd.lib(fe-connect.c.obj) : error LNK2019: ссылка на неразрешенный внешний символ __imp_DeleteSecurityContext в функции closePGconn
1>libpqd.lib(fe-auth.c.obj) : error LNK2019: ссылка на неразрешенный внешний символ AcquireCredentialsHandleA в функции pg_SSPI_startup
1>libpqd.lib(fe-auth.c.obj) : error LNK2019: ссылка на неразрешенный внешний символ InitializeSecurityContextA в функции pg_SSPI_continue
1>libpqd.lib(fe-auth.c.obj) : error LNK2019: ссылка на неразрешенный внешний символ FreeContextBuffer в функции pg_SSPI_continue
1>libeay32.lib(e_capi.obj) : error LNK2019: ссылка на неразрешенный внешний символ __imp_CertOpenStore в функции capi_open_store
1>libeay32.lib(e_capi.obj) : error LNK2019: ссылка на неразрешенный внешний символ __imp_CertCloseStore в функции capi_find_key
1>libeay32.lib(e_capi.obj) : error LNK2019: ссылка на неразрешенный внешний символ __imp_CertEnumCertificatesInStore в функции capi_find_cert
1>libeay32.lib(e_capi.obj) : error LNK2019: ссылка на неразрешенный внешний символ __imp_CertFindCertificateInStore в функции capi_find_cert
1>libeay32.lib(e_capi.obj) : error LNK2019: ссылка на неразрешенный внешний символ __imp_CertDuplicateCertificateContext в функции capi_load_ssl_client_cert
1>libeay32.lib(e_capi.obj) : error LNK2019: ссылка на неразрешенный внешний символ __imp_CertFreeCertificateContext в функции capi_find_key
1>libeay32.lib(e_capi.obj) : error LNK2019: ссылка на неразрешенный внешний символ __imp_CertGetCertificateContextProperty в функции capi_cert_get_fname

**Additional context**
I had to spend some time figuring out which static libraries are missing to properly link libpqxx and libpq to my project.
As it turned out, in addition to the .lib files that are obtained by installing vcpkg: 

> libeay32.lib, libpq.lib, libpqxx_static.lib, ssleay32.lib

You also need to link other libraries:

> crypt32.lib, secur32.lib, ws2_32.lib

As a result, we get the following list:

> libpqd.lib
> libpqxx_staticd.lib
> libeay32.lib
> ssleay32.lib
> secur32.lib
> crypt32.lib
> ws2_32.lib

Accordingly, libpq and libpqxx have a file name according to the build configuration.

**Comment by NancyLi1013** [comment]
Hi @NIKEA-SOFT thanks for posting this issue. 
Does this issue appear when you install this port or use it?
I cannot reproduce it on my local with VS2019 Windows 10 and VS2017 Windows 7.

**Comment by NIKEA-SOFT** [comment]
> Hi @NIKEA-SOFT thanks for posting this issue.
> Does this issue appear when you install this port or use it?
> I cannot reproduce it on my local with VS2019 Windows 10 and VS2017 Windows 7.

Sorry that I did not answer earlier, I completely forgot that I posted my request.
About libpqxx, latest version use OpenSSL 1.0.2p
In addition, vcpkg does not allow you to configure the "Runtime" type. For this reason, vcpkg did not fit me, I had to use conan.
You can use conan, use this command for download libpq and libpqxx

> conan install libpq/11.5@bincrafters/stable
> conan install libpqxx/6.4.5@bincrafters/stable

After install you can open dir: **C:\Users\Username\.conan\data** and build libpq and libpqxx from build folder.
After build you can link static or dynamic library with your project.

If conan throws an error, then try adding the argument **--build=missing** so that conan can find the missing libraries and set them automatically, example:
**conan install libpqxx/6.4.5@bincrafters/stable --build=missing**

**Comment by NancyLi1013** [comment]
Thanks for your detail description.
If you need Runtim MD, you can add a custom triplet named as` x64-windows-custom.cmake` and put it in _triplets/_ directory. The content included these:
```
set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)
```
Then try to install it use the command:
`./vcpkg install libpqxx:x64-windows-custom`

**Comment by NancyLi1013** [comment]
Does this problem exist now?

**Comment by NancyLi1013** [comment]
Since there is no response in a long time.
I close this issue now.
Please feel free to reopen this or open a new issue if this is still a problem for you.
