### ISSUE TITLE
boost-locale:x64 file RENAME failed to rename vcpkg/buildtrees/boost-locale/src/TEMP/locale-boost-1.71.0

### ISSUE THREAD

**Issue by dickreuter** [microsoft/vcpkg#9151]
**Host Environment**
- Windows 64
- VS C++ 19

**To Reproduce**
./vcpkg install boost-locale:x64-windows

**Failure logs** 
CMake Error at scripts/cmake/vcpkg_extract_source_archive_ex.cmake:140 (file):
  file RENAME failed to rename

    C:/Users/dickr/git/vcpkg/buildtrees/boost-locale/src/TEMP/locale-boost-1.71.0

  to

    C:/Users/dickr/git/vcpkg/buildtrees/boost-locale/src/ost-1.71.0-ce04fa497f

  because: No such file or directory

**Comment by LilyWangL** [comment]
Hi @dickreuter, I can't reproduce it locally. I installed boost-locale:x64-windows successfully with vcpkg latest code. I noticed your log has this information:
```
C:/Users/dickr/git/vcpkg/buildtrees/boost-locale/src/TEMP/locale-boost-1.71.0
```
The directory TEMP should not exist. Could you delete the directory VCPKG_path/buildtrees/boost-locale/src and rebuild it?
