### ISSUE TITLE
python3: Version mismatch

### ISSUE THREAD

**Issue by emmedve1** [microsoft/vcpkg#9164]
> $ git describe --tags HEAD
> 2019.10-170-ge4524f656
> $ git diff HEAD ports/python3
> $ sls Version ports/python3/CONTROL
ports\python3\CONTROL:2:Version: 3.7.4
> $ sls PYTHON_VERSION ports/python3/portfile.cmake | select -f 3
ports\python3\portfile.cmake:6:set(PYTHON_VERSION_MAJOR  3)
ports\python3\portfile.cmake:7:set(PYTHON_VERSION_MINOR  7)
ports\python3\portfile.cmake:8:set(PYTHON_VERSION_PATCH  3)

**Comment by AlvinZhangH** [comment]
Close this issue via #9173 merged.
