### ISSUE TITLE
Package: azure-storage-cpp:x86-windows-static   fails to build

### ISSUE THREAD

**Issue by fuocor** [Microsoft/vcpkg#917]
Package: azure-storage-cpp:x86-windows-static
  vcpkg version: 0.0.78-a312cb493959055e13fc5376fff66d46c25c5c59

[package-x86-windows-static-rel-out.zip](https://github.com/Microsoft/vcpkg/files/906287/package-x86-windows-static-rel-out.zip)

**Comment by ras0219-msft** [comment]
Hi @fuocor!

Looking through the log, it seems you don't have ATL installed. I've added a check to the azure-storage-cpp portfile (7135c5fc83e) which should catch this in the future.

Could you try installing ATL in your VS2017 ("Visual C++ ATL support" optional feature underneath the Desktop C++ workload) and rebuild the package?

**Comment by ras0219-msft** [comment]
After the above change, there was a still a bug in static builds which I've fixed in package version 3.0.0-1. Please try it out and let us know if you still have any issues!
