### ISSUE TITLE
[New Port Request] <open3d>

### ISSUE THREAD

**Issue by libChan** [microsoft/vcpkg#9172]
Library name: open3d

Library description: Open3D is an open-source library that supports rapid development of software that deals with 3D data. 

Source repository URL: https://github.com/intel-isl/Open3D

Project homepage (if different from the source repository): http://www.open3d.org/

I have tried to add open3d but failed and meet so many problems. And there is a same request at#6158. Would you please add open3d to vcpkg, can't be more appreciate!!!

**Comment by AlvinZhangH** [comment]
Same request at#6158

**Comment by haimingZZ** [comment]
I have met the same question. I can build open3d with vcpkg, but some linking problems happens when using open3d in VS2017. 

Please add open3d, can't be more appreciate!!!
