### ISSUE TITLE
[New Port Request] CGNS

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#9181]
Library name: CGNS

Library description: The CFD General Notation System (CGNS) provides a standard for recording and recovering computer data associated with the numerical solution of fluid dynamics equations.

Source repository URL: https://github.com/CGNS/CGNS

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

```

(a)The path to the HDF5 library should be specified with CMAKE_PREFIX_PATH=$HDF_DIR for linking with a specific HDF5 version.

If HDF5 is built with parallel-IO support via MPI, the 'HDF5_NEEDS_MPI' flag must be set to true.

If HDF5 is built with zlib and szip support, these need to be flagged with 'HDF5_NEEDS_ZLIB' and 'HDF5_NEEDS_SZIP' as well as the paths for those libraries.

(b)Fortran can be enabled by toggling the 'CGNS_ENABLE_FORTRAN' variable.

A view of the attempt to autodetect the correct interface between Fortran and C is show, setting the value of 'FORTRAN_NAMING'.

For gfortran and pgf90 the value of 'FORTRAN_NAMING' shoud be 'LOWERCASE_'.
```

required by #9180

**Comment by NancyLi1013** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.

**Comment by Neumann-A** [comment]
@NancyLi1013 this port has been added by the paraview pr so closing this is fine.

**Comment by NancyLi1013** [comment]
Thanks for your kindly reminder.
