### ISSUE TITLE
[New Port Request] nats.c

### ISSUE THREAD

**Issue by qqrm** [microsoft/vcpkg#9182]
Library name:
nats.c

Library description:
C client for nats

Source repository URL:
https://github.com/nats-io/nats.c

Project homepage (if different from the source repository):
https://nats.io/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by NancyLi1013** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
