### ISSUE TITLE
Ask your questions on Slack!

### ISSUE THREAD

**Issue by dan-shaw** [microsoft/vcpkg#9184]
Slack: https://cpplang.now.sh/, the #vcpkg channel

**Comment by soroshsabz** [comment]
I think this project must use Microsoft Teams :)

**Comment by pdeitel** [comment]
I tried to join the slack channel and got back "no_perms". Any idea what I should do?

**Comment by johannesstricker** [comment]
Having the same problem, also getting "no_perms".

**Comment by ondrej008** [comment]
I am also having this issue, we're supposed to put our e-mail address into the you@yourdomain.com?

**Comment by ondrej008** [comment]
I could get the e-mail through https://cpplang-inviter.cppalliance.org/

**Comment by pdeitel** [comment]
Looks like it's been fixed

**Comment by yamcenutzer** [comment]
wtf is manifest mode? and what problem does it solve?

**Comment by jozefizso** [comment]
The website is no longer available.

> ### This deployment is no longer available.
> ZEIT Now 1.0 has been shut down. As part of this, all ZEIT Now 1.0 Deployments are now inaccessible.
> 
> If you are the owner of this ZEIT Now 1.0 Project, click here to learn more →


![image](https://user-images.githubusercontent.com/287778/90315082-ce34d700-df18-11ea-96c7-af5b258ac7ed.png)

**Comment by dan-shaw** [comment]
Closing this issue as the Slack invite is in the readme.
