### ISSUE TITLE
mongoose[x86-windows-static] build failure

### ISSUE THREAD

**Issue by jimellert** [microsoft/vcpkg#9197]
**Host Environment**
- OS: windows10
- Compiler: Visual Studio Community

**To Reproduce**
1. Create overlay-ports CONTROL file, in c:\projects\build\vcpkg-ports, for mongoose to add:
`Build-Depends: openssl-windows`
2. Add new triplets file for mongoose:    x86-windows-static-mongoose  to add:
```
set(VCPKG_C_FLAGS /DMG_ENABLE_SSL)
set(VCPKG_CXX_FLAGS /DMG_ENABLE_SSL)
```
3.  Execute install command:
`vcpkg install mongoose:x86-windows-static-mongoose --overlay-ports=c:\projects\build\vcpkg-ports`

**Failure logs** 
```
Error: Building package mongoose:x86-windows-static-mongoose failed with: BUILD_FAILED
-----------------File install-x86-windows-static-mongoose-dbg-out.log---------------------
[1/3] C:\PROGRA~2\MICROS~1\2019\COMMUN~1\VC\Tools\MSVC\1423~1.281\bin\Hostx64\x86\cl.exe    -I. -IC:\Projects\github\microsoft\vcpkg\buildtrees\mongoose\src\6.15-61160b4ed7 /DWIN32 /D_WINDOWS /W3 /utf-8 /MP /DMG_ENABLE_SSL /D_DEBUG /MTd /Z7 /Ob0 /Od /RTC1 /showIncludes /FoCMakeFiles\mongoose.dir\mongoose.c.obj /FdCMakeFiles\mongoose.dir\mongoose.pdb /FS -c C:\Projects\github\microsoft\vcpkg\buildtrees\mongoose\src\6.15-61160b4ed7\mongoose.c
FAILED: CMakeFiles/mongoose.dir/mongoose.c.obj 
C:\PROGRA~2\MICROS~1\2019\COMMUN~1\VC\Tools\MSVC\1423~1.281\bin\Hostx64\x86\cl.exe    -I. -IC:\Projects\github\microsoft\vcpkg\buildtrees\mongoose\src\6.15-61160b4ed7 /DWIN32 /D_WINDOWS /W3 /utf-8 /MP /DMG_ENABLE_SSL /D_DEBUG /MTd /Z7 /Ob0 /Od /RTC1 /showIncludes /FoCMakeFiles\mongoose.dir\mongoose.c.obj /FdCMakeFiles\mongoose.dir\mongoose.pdb /FS -c C:\Projects\github\microsoft\vcpkg\buildtrees\mongoose\src\6.15-61160b4ed7\mongoose.c
Microsoft (R) C/C++ Optimizing Compiler Version 19.23.28106.4 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

C:\Projects\github\microsoft\vcpkg\buildtrees\mongoose\src\6.15-61160b4ed7\mongoose.c(4670): fatal error C1083: Cannot open include file: 'openssl/ssl.h': No such file or directory
ninja: build stopped: subcommand failed.
---------------------------------------End File----------------------------------------------
```

**Additional context**
I am trying to build mongoose with it's compiler define MG_ENABLE_SSL, so I can listen and handle secure https.  This creates a dependency on openssl.   Obviously it would be better if mongoose had a feature to all building with SSL but I've been unable to figure that out.   I do not understand why the mongoose build is failing to find openssl/ssl.h.

**Comment by JackBoosY** [comment]
Hi @jimellert, thanks for reporting this issue!
We need to add `find_package (OpenSSL)` to `CMakeLists.txt` to find the openssl includes and libraries.
Please see #9209.

Thanks.

**Comment by JackBoosY** [comment]
I've solved this issue. Please update vcpkg and try to build mongoose[ssl].

Thanks.
