### ISSUE TITLE
I did not find any way to change the preprocessor defination~

### ISSUE THREAD

**Issue by what951006** [microsoft/vcpkg#9208]
Can somebody tell me whether vcpkg works out fine or I need to think about another way~

**Comment by PhoebeHui** [comment]
@what951006 , could you provide us more details? eg, port name and the which definition that you want to change?

**Comment by what951006** [comment]
> @what951006 , could you provide us more details? eg, port name and the which definition that you want to change?
openvpn3 has a preprocessor command line which is  "TAP_WIN_COMPONENT_ID=tap0901", while I want to change it, I realized vcpkg don't have any option to change it before building stage

**Comment by PhoebeHui** [comment]
@what951006 , for openvpn3, it seems that option added by https://github.com/microsoft/vcpkg/blob/master/ports/openvpn3/CMakeLists.txt#L29, however, it does not enabled, so you should not see that definition when build openvpn3,  you can simply update  and enable it in CMakeLists.txt.

**Comment by what951006** [comment]
> @what951006 , for openvpn3, it seems that option added by https://github.com/microsoft/vcpkg/blob/master/ports/openvpn3/CMakeLists.txt#L29, however, it does not enabled, so you should not see that definition when build openvpn3, you can simply update and enable it in CMakeLists.txt.

much obliged!!! a least I know much deeper in vcpkg

**Comment by PhoebeHui** [comment]
Great!
