### ISSUE TITLE
[realsense2] update to 2.30

### ISSUE THREAD

**Issue by davidbun** [microsoft/vcpkg#9214]
Library name: RealSense2

New version number:2.30

Other information that may be useful (release notes, etc...)
https://github.com/IntelRealSense/librealsense/wiki/Release-Notes

The version currently supported by vcpkg is 2.22
There are critical bug fixes including the crashes in the last versions, drivers updates and more and more
It looks as critical to make a support to this one
thx in advance
https://github.com/IntelRealSense/librealsense/wiki/Release-Notes

**Comment by AlvinZhangH** [comment]
Hi @davidbun  Since PR has been merged.
I close this issue now, please update vcpkg and rebuild it.
Thanks.
