### ISSUE TITLE
[New Port Request] proxygen

### ISSUE THREAD

**Issue by stevezhou6** [microsoft/vcpkg#9218]
Library name:Proxygen

Library description:Proxygen: Facebook's C++ HTTP Libraries

Source repository URL:https://github.com/facebook/proxygen

Project homepage (if different from the source repository):https://github.com/facebook/proxygen

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by PhoebeHui** [comment]
Duplicated to https://github.com/microsoft/vcpkg/issues/1495.
