### ISSUE TITLE
Missing \toolsrc\Release\vcpkg.exe and 460 more error after run bat file

### ISSUE THREAD

**Issue by GospodinNoob** [Microsoft/vcpkg#922]
Missing \toolsrc\Release\vcpkg.exe and 460 more error after run bat file.

Repositry isn't full? A lot of missing files.

**Comment by ras0219-msft** [comment]
Hi Gospodin,

Hmm, what git commit are you on (`git branch -v`) and does git status say anything about deleted files?

Could you try re-cloning the repository?

If none of that provides any useful information, could you send us the full error log at vcpkg@Microsoft.com?

Thanks for reporting this issue!

**Comment by AuroraDysis** [comment]
My latest Windows SDK 10.0.15063.0 don't have shlobj.h, so it failed

**Comment by AuroraDysis** [comment]
I'm successful when I manually changed bootstrap.ps1
```
$windowsSDK = '10.0.14393.0'
```

**Comment by wangli28** [comment]
Please open a new issue if this is still a problem for you.
