### ISSUE TITLE
[vcpkg] False negative: -- Restarting Build without parallelism because memory exceeded

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#9223]
see #9222

**Comment by JackBoosY** [comment]
I confirmed this.

**Comment by adamgranthendry** [comment]
I'm confused. Is this a false negative?

**Comment by JackBoosY** [comment]
Ping @BillyONeal

**Comment by BillyONeal** [comment]
> I'm confused. Is this a false negative? I have more than plenty of RAM on my machine (192 GB), but please let me know. I receive this message when running

That message is generated by grepping the output of the build of a port after a build fails:

https://github.com/microsoft/vcpkg/blob/025e564979cc01d0fbc5c920aa8a36635efb01bb/scripts/cmake/vcpkg_execute_build_process.cmake#L37-L50

->

https://github.com/microsoft/vcpkg/blob/025e564979cc01d0fbc5c920aa8a36635efb01bb/scripts/cmake/vcpkg_execute_build_process.cmake#L86-L87

Perhaps the port in question is choosing a 32 bit toolset?

**Comment by LilyWangLL** [comment]
Fixed by PR #22417

**Comment by Neumann-A** [comment]
I dont think this is fixed.

**Comment by LilyWangLL** [comment]
> I dont think this is fixed.

I couldn't reproduce this issue locally, there are no message about memory exceeded when installing `vtk` and `itk`. And this behvior has been changed to warning message in PR #22417.

**Comment by dg0yt** [comment]
IIUC this issue is about a restart actually triggered from `LINK : fatal error LNK1104: cannot open file 'pugixml.lib`. 
(It is not really obvious from the initial post.)
