### ISSUE TITLE
What kind of testing is done by the project

### ISSUE THREAD

**Issue by MikeGitb** [Microsoft/vcpkg#923]
As there is no visible ci going on I was wondering if the MS Team actually checks if all the portfiles work correctly (on which platform / with which compiler / are you running any tests / any test projects?). And if the library versions in the master branch play "nice" together or if there are any incompatibilities.

Especially when less experienced people like me are trying to write a non-trivial portfile or upgrading an existing one it would be nice to have more feedback than just: "It seems to work on my machine"

**Comment by KindDragon** [comment]
It's not possible to compile all ports in the reasonable time. We had discussion about that in issue #72

**Comment by MikeGitb** [comment]
@KindDragon: Thank you for the link.
I understand that a "classic" public github CI (e.g. via appveyor) doesn't work here or is at least difficult to implement. However, MS should have more than enough ressources to internally build all libraries e.g. once a day and report any failures.

Also from the FAQ (under *"Why not Conan?"*):

> We believe this will result in a set of high quality packages **that are heavily tested with each other** and form a fantastic base for any private modifications you need. 

Of course this testing will - to a large degree - happen organically by the users but relying on the users of your SW as the **only/primary** means of testing is imho not really a situation one should be content with.

**Comment by KindDragon** [comment]
I agree with you. It would be nice to automatically test changed ports in PR.

I think better continue discussion in the old issue

**Comment by ras0219-msft** [comment]
Continued in #72 -- thanks for deduplicating, @KindDragon!
