### ISSUE TITLE
[qt5-svg 5.12.5] build failure: "qmake: could not find a Qt installation of ''"

### ISSUE THREAD

**Issue by jepessen** [microsoft/vcpkg#9239]
**Host Environment**
- OS: Kubuntu 19.10 64 bit
- Compiler: revision

**To Reproduce**

- `./vcpkg install qt5`

**Failure logs** 
The file `buildtrees/qt5-svg/config-x64-linux-rel-err.log` reports only the following text:

```
qmake: could not find a Qt installation of ''
```

**Comment by Neumann-A** [comment]
The other qt5 ports work? Is there a qt.conf in `<buildtrees>/qt5-svg/x86-windows-(rel|dbg)/` ? Does it have the expected paths in it? Do you have another `qmake` installation on the path?

**Comment by jepessen** [comment]
Yes. Since I've Kubuntu with Qt installed I had a qmake in /usr/bin. I've renamed it and now it seems to build again. Is there a way to force to use the vcpkg qmake instead of the default one? It can be a problem if I need to work with different versions of qt.

**Comment by Neumann-A** [comment]
ah probably the bug is in `vcpkg_configure_qmake`

```
    # Find qmake executable
    set(_triplet_hostbindir ${CURRENT_INSTALLED_DIR}/tools/qt5/bin)
    find_program(QMAKE_COMMAND NAMES qmake PATHS ${VCPKG_QT_HOST_TOOLS_ROOT_DIR}/bin ${_triplet_hostbindir})
```

since `VCPKG_QT_HOST_TOOLS_ROOT_DIR` is not set it will probably first look in /bin

teh call should probably look like this:
```
if(VCPKG_QT_HOST_TOOLS_ROOT_DIR)
  find_program(QMAKE_COMMAND NAMES qmake PATHS ${VCPKG_QT_HOST_TOOLS_ROOT_DIR}/bin ${_triplet_hostbindir})
else()
  find_program(QMAKE_COMMAND NAMES qmake PATHS ${_triplet_hostbindir})
endif()
```

**Comment by jepessen** [comment]
Ok I'll try to make a pull request asap.

**Comment by Neumann-A** [comment]
@JackBoosY: close since it should be fixed
