### ISSUE TITLE
[New Port Request] gperf tool

### ISSUE THREAD

**Issue by matwey** [microsoft/vcpkg#9243]
Library name:

gperf tool

Library description: 

GNU gperf is a perfect hash function generator. For a given list of strings, it produces a hash function and hash table, in form of C or C++ code, for looking up a value depending on the input string. The hash function is perfect, which means that the hash table has no collisions, and the hash table lookup needs a single string comparison only. 

Source repository URL:

https://git.savannah.gnu.org/gitweb/?p=gperf.git

Project homepage

https://www.gnu.org/software/gperf/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

gperf is a code-generating tool. It produces C code file function from a given list of strings.

**Comment by JackBoosY** [comment]
Hi @matwey, thanks for reporting this issue!
`gperf` has been added as a tool in vcpkg, you can use` vcpkg_find_acquire_program (GPERF) `to use gperf or find it in _VCPKG_PATH/downloads/tools/gperf_.

Thanks.

**Comment by matwey** [comment]
Thank you for the response.

As far as I understand, `vcpkg_find_acquire_program (GPERF)` supposes that I develop vcpkg port and use `portfile.cmake`. In my project's `CMakeLists.txt` I have the following plain line:

`find_program(GPERF NAMES gperf)`

I would like to have a simple one-line way to install this binary in my development environment. Maybe `scripts/buildsystems/vcpkg.cmake` could substitute `find_program` as It does for `find_package(boost)`?

**Comment by JackBoosY** [comment]
These tools are used in the port construction process and cannot be used directly outside of vcpkg. 
vcpkg's principle of adding ports is to support build generation and not allow download of binary usage.
So you can set `CMAKE_PROGRAM_PATH` to _VCPKG_PATH/downloads/tools/gperf_ and use` find_program` to use gperf.

**Comment by matwey** [comment]
Would it be ok, if there were `gperf` port building the tool from the source codes?

**Comment by JackBoosY** [comment]
@matwey Yes, If you do find a way to build gperf, you can add it to vcpkg as a port.
