### ISSUE TITLE
[pdal:x64-windows-static] build failure

### ISSUE THREAD

**Issue by GoldenswordYJF** [microsoft/vcpkg#9249]
**Host Environment**
- OS: [Microsoft Windows [ver. 10.0.18362.476]]
- Compiler: MSVC 19.0.24215.1

**To Reproduce**
`.\vcpkg install pdal:x64-windows-static`

**Failure logs** 
D:\Work\vcpkg-master>.\vcpkg install pdal:x64-windows-static
The following packages will be built and installed:
    pdal[core]:x64-windows-static
Starting package 1/1: pdal:x64-windows-static
Building package pdal[core]:x64-windows-static...
-- Using cached D:/Work/vcpkg-master/downloads/PDAL-1.7.1-src.tar.gz
-- Using source at D:/Work/vcpkg-master/buildtrees/pdal/src/PDAL-1-776c53624b
-- Configuring x64-windows-static
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: ninja -v
    Working Directory: D:/Work/vcpkg-master/buildtrees/pdal/x64-windows-static-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      D:\Work\vcpkg-master\buildtrees\pdal\config-x64-windows-static-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:293 (vcpkg_execute_required_process)
  ports/pdal/portfile.cmake:42 (vcpkg_configure_cmake)
  scripts/ports.cmake:94 (include)

Error: Building package pdal:x64-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: pdal:x64-windows-static
  Vcpkg version: 2019.09.12-nohash

Additionally, attach any relevant sections from the log files above.
**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.
[config-x64-windows-static-out.log](https://github.com/microsoft/vcpkg/files/3937946/config-x64-windows-static-out.log)

**Comment by JackBoosY** [comment]
Hi @GoldenswordYJF, thanks for reporting this issue!
I've fixed this issue, please update vcpkg and rebuild pdal.

Thanks.
