### ISSUE TITLE
[New Port Request]mysql++

### ISSUE THREAD

**Issue by liquidmonkeyCH** [microsoft/vcpkg#9251]
https://tangentsoft.com/mysqlpp/home

**Comment by vpaladino778** [comment]
I'll take a stab at this

**Comment by vpaladino778** [comment]
According to the build information [here](https://github.com/tangentsoft/mysqlpp#building-the-library), they use autoconf, and they also have Visual studio project files. I've only ever worked with CMake projects in the past. How would one go about creating a portfile for autoconf?

**Comment by myd7349** [comment]
> 
> 
> According to the build information [here](https://github.com/tangentsoft/mysqlpp#building-the-library), they use autoconf, and they also have Visual studio project files. I've only ever worked with CMake projects in the past. How would one go about creating a portfile for autoconf?

https://github.com/microsoft/vcpkg/blob/master/scripts/cmake/vcpkg_configure_make.cmake

**Comment by NancyLi1013** [comment]
Hi all,
Thanks for posting this request and joining this discussion.
But now we're closing it for now. If you wish to add this port in the future, you can reopen this issue,
