### ISSUE TITLE
How do I use Windows triplets on Linux?

### ISSUE THREAD

**Issue by morth** [microsoft/vcpkg#9257]
I don't really know whether this is a bug or not and I haven't found many documentation resources covering **cross compilation**.

I'm trying to build my app for multiple host platforms (including x86 and x64 Windows) on Ubuntu 18.04 as a common build platform. I'm running into multiple issues when it comes to using Windows triplets:

- CMake builds fail due to a missing `powershell` executable. This is because `$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake` adds a post build step that executes a PowerShell script when detecting Windows as the triplet's target platform (not regarding the build platform).
- Some port installs fail on Linux when using a Windows triplet. E.g. running `./vcpkg install openssl:x86-windows` on a Linux machine says "This port is only for building openssl on Windows Desktop".

Is cross compiling from Linux to Windows even supported?

**Comment by NancyLi1013** [comment]
Hi @morth thanks for posting this issue.
Currently, VCPKG doesn't support cross compiling between Linux and Windows. We can only build the related triplets that the platform supported.

**Comment by NancyLi1013** [comment]
Since current behavior is expected. 
So I will close this issue now. Please open a new issue if you have other problems.
