### ISSUE TITLE
[check] Cannot find check config

### ISSUE THREAD

**Issue by matwey** [microsoft/vcpkg#9262]
Hi, 

I am installed `check` via vcpkg and try to build a project inside Visual Studio.
Unfortunately, CMake generation is failed at the line:

`find_package(check REQUIRED CONFIG NAMES Check check)`

```
1> [CMake] CMake Error at C:/Users/User/source/repos/vcpkg/scripts/buildsystems/vcpkg.cmake:263 (_find_package):
1> [CMake]   Could not find a package configuration file provided by "check" with any of
1> [CMake]   the following names:
1> [CMake] 
1> [CMake]     CheckConfig.cmake
1> [CMake]     check-config.cmake
1> [CMake]     checkConfig.cmake
1> [CMake]     check-config.cmake
1> [CMake] 
1> [CMake]   Add the installation prefix of "check" to CMAKE_PREFIX_PATH or set
1> [CMake]   "check_DIR" to a directory containing one of the above files.  If "check"
1> [CMake]   provides a separate development package or SDK, be sure it has been
1> [CMake]   installed.
```

`check-config.cmake` is present in `\vcpkg\installed\x64-windows\share\check\check`

**Comment by Neumann-A** [comment]
thats one folder too deep for CMake copy the files into `\share\check`

**Comment by NancyLi1013** [comment]
Hi @matwey thanks for posting this issue.
This issue has been fixed now. Please try to update vcpkg and rebuild it.
