### ISSUE TITLE
[New Port Request] Tracy

### ISSUE THREAD

**Issue by AMS21** [microsoft/vcpkg#9269]
Library name: Tracy

Library description: A real time, nanosecond resolution, remote telemetry frame profiler for games and other applications.

Source repository URL: https://bitbucket.org/wolfpld/tracy/src/master/

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included): Source includes the actual library which the user must link with and the profiling application which is used to view the profiler reports.

**Comment by NancyLi1013** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.

**Comment by s9w** [comment]
Not sure if this is the right place, but I want to give another vote for this. Tracy is getting very popular. I could understand if the reason for not doing this is the separation of the client and the library. But no reason was given and so of that's not the case I believe this should absolutely make the cut.

Tracy lives on GitHub now: https://github.com/wolfpld/tracy

**Comment by NancyLi1013** [comment]
Hi @s9w 
Thanks for bringing up this request again. 
If you want `tracy `to be added, please open a pull request.
We won't open this issue unless there is a pull request opened for `tracy`.

Thanks.

**Comment by s9w** [comment]
I respect if that's the way things work. But FYI: Almost all users lack the interest and/or knowledge to do such thing, me (and possibly OP) included. It seems odd to place the burden of adding ports on end-users.
