### ISSUE TITLE
[Libevent] include headers fails on x64-windows, using CMAKE

### ISSUE THREAD

**Issue by blizardxsi** [microsoft/vcpkg#9275]
I'm doing a minimum test using libevent on WIN10 x64 with VS2017. What I've done is just
1. add fowlling to the CMakeSettings.json
>       "variables": [
>         {
>           "name": "CMAKE_TOOLCHAIN_FILE",
>           "value": "[vcpkg]/scripts/buildsystems/vcpkg.cmake"
>         }
>       ]

2. tell CMAKE to find libevent package, in CMakeLists.txt
>       find_package(Libevent CONFIG REQUIRED)
>       include_directories(${LIBEVENT_INCLUDE_DIRS})
>       add_executable (hello ...)
>       target_link_libraries(hello PRIVATE event_shared event_core_shared event_extra_shared)

When I include <event2/event.h> in the main.cpp, and build the project, Visual Studio reports a failure to open the header file. So I go to the [vcpkg]\installed\x64-windows\share\libevent\LibeventConfig.cmake to find out. And I made a little change from:
>     set(LIBEVENT_INCLUDE_DIRS "${LIBEVENT_CMAKE_DIR}/${CMAKE_CURRENT_LIST_DIR}/../../include")
to:
>     set(LIBEVENT_INCLUDE_DIRS "${LIBEVENT_CMAKE_DIR}/../../include")

So in this way the everything works fine.

My question is that is it a bug, that the package gave me the wrong LIBEVENT_INCLUDE_DIRS, or I'm using it in a wrong way?

**Comment by JackBoosY** [comment]
Hi @blizardxsi, thanks for reporting this issue!
It's definitely a bug, we need to fix it.

Thanks.

**Comment by AlvinZhangH** [comment]
Hi @blizardxsi  Since PR has been merged.
I close this issue now, please update vcpkg and rebuild it.
Thanks.
