### ISSUE TITLE
[grpc:x64-windows] build failure

### ISSUE THREAD

**Issue by Horoprime** [microsoft/vcpkg#9282]
**Host Environment**
- OS: [Windows 10 x64]
- Compiler: revision

**To Reproduce**
`.\vcpkg.exe install grpc:x64-windows`

**Failure logs** 

```
The following packages will be built and installed:
    grpc[core]:x64-windows
Starting package 1/1: grpc:x64-windows
Building package grpc[core]:x64-windows...
-- Note: grpc only supports static library linkage. Building static library.
-- Using cached D:/Workspace/GRPCPlayground/vcpkg/downloads/grpc-grpc-v1.23.1.tar.gz
-- Using source at D:/Workspace/GRPCPlayground/vcpkg/buildtrees/grpc/src/v1.23.1-ebfd5c51df
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: D:/Workspace/GRPCPlayground/vcpkg/downloads/tools/cmake-3.14.0-windows/cmake-3.14.0-win32-x86/bin/cmake.exe --build . --config Debug --target install -- -v
    Working Directory: D:/Workspace/GRPCPlayground/vcpkg/buildtrees/grpc/x64-windows-dbg
    See logs for more information:
      D:\Workspace\GRPCPlayground\vcpkg\buildtrees\grpc\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:91 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/grpc/portfile.cmake:77 (vcpkg_install_cmake)
  scripts/ports.cmake:94 (include)


Error: Building package grpc:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: grpc:x64-windows
  Vcpkg version: 2019.09.12-nohash
```

**Additional context**
x86 version is successfully installed. Also tried to install static version - but anyway got the error.
vcpkg is up-to-date

**Comment by jozefizso** [comment]
Can you post the **install-x64-windows-dbg-out.log** file?

**Comment by Horoprime** [comment]
> Can you post the **install-x64-windows-dbg-out.log** file?


[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/3950711/install-x64-windows-dbg-out.log)
[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/3950712/config-x64-windows-out.log)

**Comment by jozefizso** [comment]
```
   Creating library grpc_csharp_ext.lib and object grpc_csharp_ext.exp
grpc.lib(ssl_transport_security.cc.obj) : error LNK2019: unresolved external symbol sk_num referenced in function "enum tsi_result __cdecl peer_from_x509(struct x509_st *,int,struct tsi_peer *)" (?peer_from_x509@@YA?AW4tsi_result@@PEAUx509_st@@HPEAUtsi_peer@@@Z)
grpc.lib(ssl_transport_security.cc.obj) : error LNK2019: unresolved external symbol sk_value referenced in function "enum tsi_result __cdecl add_subject_alt_names_properties_to_peer(struct tsi_peer *,struct stack_st_GENERAL_NAME *,unsigned __int64)" (?add_subject_alt_names_properties_to_peer@@YA?AW4tsi_result@@PEAUtsi_peer@@PEAUstack_st_GENERAL_NAME@@_K@Z)
grpc.lib(ssl_transport_security.cc.obj) : error LNK2019: unresolved external symbol sk_new_null referenced in function "enum tsi_result __cdecl x509_store_load_certs(struct x509_store_st *,char const *,unsigned __int64,struct stack_st_X509_NAME * *)" (?x509_store_load_certs@@YA?AW4tsi_result@@PEAUx509_store_st@@PEBD_KPEAPEAUstack_st_X509_NAME@@@Z)
grpc.lib(ssl_transport_security.cc.obj) : error LNK2019: unresolved external symbol sk_pop_free referenced in function "enum tsi_result __cdecl peer_from_x509(struct x509_st *,int,struct tsi_peer *)" (?peer_from_x509@@YA?AW4tsi_result@@PEAUx509_st@@HPEAUtsi_peer@@@Z)
grpc.lib(ssl_transport_security.cc.obj) : error LNK2019: unresolved external symbol sk_push referenced in function "enum tsi_result __cdecl x509_store_load_certs(struct x509_store_st *,char const *,unsigned __int64,struct stack_st_X509_NAME * *)" (?x509_store_load_certs@@YA?AW4tsi_result@@PEAUx509_store_st@@PEBD_KPEAPEAUstack_st_X509_NAME@@@Z)
grpc.lib(ssl_transport_security.cc.obj) : error LNK2019: unresolved external symbol CRYPTO_num_locks referenced in function "void __cdecl init_openssl(void)" (?init_openssl@@YAXXZ)
grpc.lib(ssl_transport_security.cc.obj) : error LNK2019: unresolved external symbol CRYPTO_set_locking_callback referenced in function "void __cdecl init_openssl(void)" (?init_openssl@@YAXXZ)
grpc.lib(ssl_transport_security.cc.obj) : error LNK2019: unresolved external symbol CRYPTO_get_locking_callback referenced in function "void __cdecl init_openssl(void)" (?init_openssl@@YAXXZ)
grpc.lib(ssl_transport_security.cc.obj) : error LNK2019: unresolved external symbol CRYPTO_set_id_callback referenced in function "void __cdecl init_openssl(void)" (?init_openssl@@YAXXZ)
grpc.lib(ssl_transport_security.cc.obj) : error LNK2019: unresolved external symbol OPENSSL_add_all_algorithms_noconf referenced in function "void __cdecl init_openssl(void)" (?init_openssl@@YAXXZ)
grpc.lib(ssl_transport_security.cc.obj) : error LNK2019: unresolved external symbol SSL_load_error_strings referenced in function "void __cdecl init_openssl(void)" (?init_openssl@@YAXXZ)
grpc.lib(ssl_transport_security.cc.obj) : error LNK2019: unresolved external symbol SSL_library_init referenced in function "void __cdecl init_openssl(void)" (?init_openssl@@YAXXZ)
grpc.lib(ssl_transport_security.cc.obj) : error LNK2019: unresolved external symbol SSL_state referenced in function "enum tsi_result __cdecl ssl_handshaker_get_result(struct tsi_ssl_handshaker *)" (?ssl_handshaker_get_result@@YA?AW4tsi_result@@PEAUtsi_ssl_handshaker@@@Z)
grpc.lib(ssl_transport_security.cc.obj) : error LNK2019: unresolved external symbol SSL_CTX_get_ex_new_index referenced in function "void __cdecl init_openssl(void)" (?init_openssl@@YAXXZ)
grpc_csharp_ext.dll : fatal error LNK1120: 14 unresolved externals
```

**Comment by Horoprime** [comment]
> ```
>    Creating library grpc_csharp_ext.lib and object grpc_csharp_ext.exp
> grpc.lib(ssl_transport_security.cc.obj) : error LNK2019: unresolved external symbol sk_num referenced in function "enum tsi_result __cdecl peer_from_x509(struct x509_st *,int,struct tsi_peer *)" (?peer_from_x509@@YA?AW4tsi_result@@PEAUx509_st@@HPEAUtsi_peer@@@Z)
> grpc.lib(ssl_transport_security.cc.obj) : error LNK2019: unresolved external symbol sk_value referenced in function "enum tsi_result __cdecl add_subject_alt_names_properties_to_peer(struct tsi_peer *,struct stack_st_GENERAL_NAME *,unsigned __int64)" (?add_subject_alt_names_properties_to_peer@@YA?AW4tsi_result@@PEAUtsi_peer@@PEAUstack_st_GENERAL_NAME@@_K@Z)
> grpc.lib(ssl_transport_security.cc.obj) : error LNK2019: unresolved external symbol sk_new_null referenced in function "enum tsi_result __cdecl x509_store_load_certs(struct x509_store_st *,char const *,unsigned __int64,struct stack_st_X509_NAME * *)" (?x509_store_load_certs@@YA?AW4tsi_result@@PEAUx509_store_st@@PEBD_KPEAPEAUstack_st_X509_NAME@@@Z)
> grpc.lib(ssl_transport_security.cc.obj) : error LNK2019: unresolved external symbol sk_pop_free referenced in function "enum tsi_result __cdecl peer_from_x509(struct x509_st *,int,struct tsi_peer *)" (?peer_from_x509@@YA?AW4tsi_result@@PEAUx509_st@@HPEAUtsi_peer@@@Z)
> grpc.lib(ssl_transport_security.cc.obj) : error LNK2019: unresolved external symbol sk_push referenced in function "enum tsi_result __cdecl x509_store_load_certs(struct x509_store_st *,char const *,unsigned __int64,struct stack_st_X509_NAME * *)" (?x509_store_load_certs@@YA?AW4tsi_result@@PEAUx509_store_st@@PEBD_KPEAPEAUstack_st_X509_NAME@@@Z)
> grpc.lib(ssl_transport_security.cc.obj) : error LNK2019: unresolved external symbol CRYPTO_num_locks referenced in function "void __cdecl init_openssl(void)" (?init_openssl@@YAXXZ)
> grpc.lib(ssl_transport_security.cc.obj) : error LNK2019: unresolved external symbol CRYPTO_set_locking_callback referenced in function "void __cdecl init_openssl(void)" (?init_openssl@@YAXXZ)
> grpc.lib(ssl_transport_security.cc.obj) : error LNK2019: unresolved external symbol CRYPTO_get_locking_callback referenced in function "void __cdecl init_openssl(void)" (?init_openssl@@YAXXZ)
> grpc.lib(ssl_transport_security.cc.obj) : error LNK2019: unresolved external symbol CRYPTO_set_id_callback referenced in function "void __cdecl init_openssl(void)" (?init_openssl@@YAXXZ)
> grpc.lib(ssl_transport_security.cc.obj) : error LNK2019: unresolved external symbol OPENSSL_add_all_algorithms_noconf referenced in function "void __cdecl init_openssl(void)" (?init_openssl@@YAXXZ)
> grpc.lib(ssl_transport_security.cc.obj) : error LNK2019: unresolved external symbol SSL_load_error_strings referenced in function "void __cdecl init_openssl(void)" (?init_openssl@@YAXXZ)
> grpc.lib(ssl_transport_security.cc.obj) : error LNK2019: unresolved external symbol SSL_library_init referenced in function "void __cdecl init_openssl(void)" (?init_openssl@@YAXXZ)
> grpc.lib(ssl_transport_security.cc.obj) : error LNK2019: unresolved external symbol SSL_state referenced in function "enum tsi_result __cdecl ssl_handshaker_get_result(struct tsi_ssl_handshaker *)" (?ssl_handshaker_get_result@@YA?AW4tsi_result@@PEAUtsi_ssl_handshaker@@@Z)
> grpc.lib(ssl_transport_security.cc.obj) : error LNK2019: unresolved external symbol SSL_CTX_get_ex_new_index referenced in function "void __cdecl init_openssl(void)" (?init_openssl@@YAXXZ)
> grpc_csharp_ext.dll : fatal error LNK1120: 14 unresolved externals
> ```

So, what should I do about it?
I didn't touch transport_security

**Comment by jozefizso** [comment]
I would try to recompile openssl.

**Comment by NancyLi1013** [comment]
Hi @Horoprime thanks for posting this issue.
From the error log you provided above, It seems that there is something wrong with `openssl`.
So would you like to remove `openssl `and try to build it again? or clone a clean branch and then install `grpc`?

**Comment by Horoprime** [comment]
> From the error log you provided above, It seems that there is something wrong with `openssl`.
> So would you like to remove `openssl `and try to build it again? or clone a clean branch and then install `grpc`?

Hi, tried removeing all packages and reistall. It worked! Thank you!
