### ISSUE TITLE
[openexr] OpenEXR_IEXMATH_LIBRARY_DEBUG-NOTFOUND

### ISSUE THREAD

**Issue by LaurensVoerman** [microsoft/vcpkg#9283]
****

**Is your feature request related to a problem? Please describe.**
After configure cmake reports OpenEXR_IEXMATH_LIBRARY_DEBUG-NOTFOUND;
and uses the release version. As the library is not used this does not actually cause a problem, only confusion. I did not find any package that really uses the IexMath dll.
**Proposed solution**
Add the underscore so the file will be found. As proposed in PR9255

**Describe alternatives you've considered**
As the library is not actually used, there seems to be no problem in linking the release version, so leaving this as-is is a real option. This might give a conflict about the runtime library in the static build, but I did not check.

**Additional context**
My solution triggers a bug in AlembicIlmBase.cmake in Alembic, a fix is added.

**Comment by NancyLi1013** [comment]
Hi @LaurensVoerman thanks for posting this issue.
The PR has been merged to master now. So I close this issue.
Thanks again.
