### ISSUE TITLE
live555:x86-windows-static build failure

### ISSUE THREAD

**Issue by Silphium** [microsoft/vcpkg#9284]
**Host Environment**
- OS: Windows 10
- Compiler: revision : VS2019

.\vcpkg.exe install live555:x86-windows-static --head                                  Your feedback is important to improve Vcpkg! Please take 3 minutes to complete our survey by running: vcpkg contact --survey
The following packages will be built and installed:
    live555[core]:x86-windows-static (from HEAD)
Starting package 1/1: live555:x86-windows-static
Building package live555[core]:x86-windows-static from HEAD...
Warning: abi keys are missing values:
    head

-- Using cached C:/Art/Library/vcpkg/downloads/live555-latest.tar.gz
-- Skipping hash check for C:/Art/Library/vcpkg/downloads/live555-latest.tar.gz.
-- Using source at C:/Art/Library/vcpkg/buildtrees/live555/src/555-latest-9d23023a24
-- Configuring x86-windows-static
-- Building x86-windows-static-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: C:/Art/Library/vcpkg/downloads/tools/cmake-3.14.0-windows/cmake-3.14.0-win32-x86/bin/cmake.exe --build . --config Debug --target install -- -v
    Working Directory: C:/Art/Library/vcpkg/buildtrees/live555/x86-windows-static-dbg
    See logs for more information:
      C:\Art\Library\vcpkg\buildtrees\live555\install-x86-windows-static-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:91 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/live555/portfile.cmake:32 (vcpkg_install_cmake)
  scripts/ports.cmake:94 (include)

Error: Building package live555:x86-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: live555:x86-windows-static
  Vcpkg version: 2019.09.12-nohash

Additionally, attach any relevant sections from the log files above.
C:\art\Library\vcpkg [master ≡]>            

I was wondering if anybody could help me with this issue?

**Comment by AlvinZhangH** [comment]
Hi @Silphium thanks for posting this issue.
This issue has been fixed now. Please try to update vcpkg and rebuild it.
