### ISSUE TITLE
Cannot install Qt5 on Windows 10 x64

### ISSUE THREAD

**Issue by ArtemKotovsky** [microsoft/vcpkg#9286]
I use the latest vcpkg 

> Building package qt5-base[core]:x64-windows...
> -- Figuring out qt target mkspec. Target arch x64
> -- Target mkspec set to: win32-msvc
> -- Host mkspec not set. Qt's own buildsystem will try to figure out the host system
> -- Downloading http://download.qt.io/official_releases/qt/5.12/5.12.5/submodules/qtbase-everywhere-src-5.12.5.tar.xz...
> -- Extracting source C:/1/vcpkg/downloads/qtbase-everywhere-src-5.12.5.tar.xz
> -- Applying patch patches/winmain_pro.patch
> -- Applying patch patches/windows_prf.patch
> -- Applying patch patches/qt_app.patch
> -- Applying patch patches/gui_configure.patch
> -- Using source at C:/1/vcpkg/buildtrees/qt5-base/src/5.12.5-0f870116d4
> -- Configuring x64-windows-dbg
> -- Configuring x64-windows-dbg done
> -- Configuring x64-windows-rel
> -- Configuring x64-windows-rel done
> -- NUMBER_OF_PROCESSORS is 8
> -- Downloading https://www.python.org/ftp/python/3.7.3/python-3.7.3-embed-win32.zip...
> -- Downloading https://sourceforge.net/projects/winflexbison/files/winflexbison-2.5.16.zip/download...
> -- Downloading https://sourceforge.net/projects/winflexbison/files/winflexbison-2.5.16.zip/download... Failed. Status: 7;"Couldn't connect to server"
> CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:175 (message):
> 
>       Failed to download file.
>       If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
>       variables to "https://user:password@your-proxy-ip-address:port/".
>       Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues
> 
> Call Stack (most recent call first):
>   scripts/cmake/vcpkg_find_acquire_program.cmake:298 (vcpkg_download_distfile)
>   ports/qt5-base/cmake/install_qt.cmake:44 (vcpkg_find_acquire_program)
>   ports/qt5-base/portfile.cmake:219 (install_qt)
>   scripts/ports.cmake:94 (include)
> 
> 
> Error: Building package qt5-base:x64-windows failed with: BUILD_FAILED
> Please ensure you're using the latest portfiles with `.\vcpkg update`, then
> submit an issue at https://github.com/Microsoft/vcpkg/issues including:
>   Package: qt5-base:x64-windows
>   Vcpkg version: 2019.09.12-nohash
> 
> Additionally, attach any relevant sections from the log files above.

**Comment by Neumann-A** [comment]
The download simply failed. Did you try again? How often did you try? Did you have enough disk space?

**Comment by ArtemKotovsky** [comment]
I have enough disk space, I tried a lot of times, but always had the same error.
Windows reboot helped :)

Thanks a lot!
