### ISSUE TITLE
A Suspected Bug in vcpkg curl

### ISSUE THREAD

**Issue by realaltffour** [microsoft/vcpkg#9290]
**Describe the bug**
Building a project with cmake and curl with vcpkg as a package manager would output this weird error:
```
C:\Users\altffour\Desktop\Projects\ContractNotifier\build>cmake .. -DCMAKE_TOOLCHAIN_FILE=C:\vcpkg\scripts\buildsystems\vcpkg.cmake
-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.17763.
CMake Error at C:/vcpkg/installed/x86-windows/share/curl/vcpkg-cmake-wrapper.cmake:5 (_find_package):
  Could not find a configuration file for package "CURL" that is compatible
  with requested version "".

  The following configuration files were considered but not accepted:

    C:/vcpkg/installed/x86-windows/share/curl/CURLConfig.cmake, version: 7.66.0-DEV (32bit)
```

**Environment**
- OS: Windows 10 Home (virtual machine)
- Compiler: Microsoft Visual Studio 2019

**To Reproduce**
1. Install the curl library: ```vcpkg.exe install curl:x86-windows```
2. Build a project with this cmake snippet:
```
# curl
find_package(CURL CONFIG REQUIRED)
include_directories(${CURL_INCLUDE_DIR})

file(GLOB_RECURSE hdrs "src/*.h")
file(GLOB_RECURSE srcs "src/*.cpp")
file(GLOB_RECURSE ui "src/*.ui")
include_directories("." "src/")
add_executable(contractNotifier ${ui} ${hdrs} ${srcs})
target_link_libraries(contractNotifier Qt5::Core Qt5::Widgets Boost::serialization ${CMAKE_THREAD_LIBS_INIT} CURL::libcurl)
```
3. Would result in an error, of "incompatible version" even without specifying one.

**Expected behavior**
To produce a visual studio solution.

**Comment by cenit** [comment]
It usually means that you are building an x64-windows executable but you are trying to link with an x86-windows library (or vice-versa!)

**Comment by Neumann-A** [comment]
Call cmake with  `-DVCPKG_TARGET_TRIPLET=x64-windows` . The reason that happens is because the default arch vor the vs2019 generator is x64 and vcpkg defaults to x86. Maybe someone should fix that automatic setting of the triplet in the toolchain file

**Comment by realaltffour** [comment]
Thanks for the help! The problem was as @Neumann-A said. Compiling all required packages with ```:x64-windows``` argument passed to vcpkg AND calling cmake with ```-DVCPKG_TARGET_TRIPLET=x64-windows``` compiles successfully!
