### ISSUE TITLE
Why is linux triplet configured to build static libraries?

### ISSUE THREAD

**Issue by invy** [microsoft/vcpkg#9295]
Why are libraries has to be built statically for Linux?
https://github.com/microsoft/vcpkg/blob/16fdd22565330b5b20162b194ae77eeb10166fa2/triplets/x64-linux.cmake#L3

Two obrious problems:
1. It produces huge executables, especially if you are building multiple programs towards same set of libraries.
2. It causes licensing issues with LGPL libraries.

**Comment by cbezault** [comment]
It's just the default that we test you can change it in the triplet to build all shared libraries or to build shared libraries on a case by case basis.

**Comment by invy** [comment]
The question is rather why it's default. Of course we've changed it and use overlay-triplets, but IMO it would be nice if default would be shared.

**Comment by mbeutel** [comment]
I wish both `x64-linux-static` and `x64-linux` (producing dynamic libraries) were available in the default distribution.

**Comment by jakoch** [comment]
Yes.. this is very confusing.

`x64-linux` with `set(VCPKG_LIBRARY_LINKAGE static)` is basically `x64-linux-static` and should be renamed.

While `x64-linux-dynamic.cmake` is this (referencing [docs]( https://vcpkg.readthedocs.io/en/latest/examples/overlay-triplets-linux-dynamic/)):
```
set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic) # <------------- static to dynamic (.so)

set(VCPKG_CMAKE_SYSTEM_NAME Linux)
```

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
