### ISSUE TITLE
Error: Building package fmi4cpp:x64-windows

### ISSUE THREAD

**Issue by dieggar** [microsoft/vcpkg#9304]
**Host Environment**
- OS: windows 10
- Compiler: --

**To Reproduce**
vcpkg install fmi4cpp:x64-windows

**Failure logs** 

Error: Building package fmi4cpp:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: fmi4cpp:x64-windows
  Vcpkg version: 2019.09.12-nohash

Additionally, attach any relevant sections from the log files above.

**Comment by JackBoosY** [comment]
Hi @dieggar, thanks for reporting this issue!
I cannot repro this issue on my machine, please provide your failure logs. You can find them in _VCPKG_PATH/buildtrees/fmi4cpp_.

Thanks.

**Comment by dieggar** [comment]
[fmi4cpp.zip](https://github.com/microsoft/vcpkg/files/3977288/fmi4cpp.zip)
Hello @JackBoosY,

I attach my failure logs compressed in a zip file.

Best regards.

Diego.

**Comment by JackBoosY** [comment]
Can you add `#include <iterator> ` on top of _J:\FMI-FMU\vcpkg\vcpkg\buildtrees\fmi4cpp\src\v0.7.0-85bef849b4\include\fmi4cpp/driver/driver_options.hpp_ and try again?

Thanks.

**Comment by dieggar** [comment]
Ok,

the package could be installed with this change!

Thank you very much.
