### ISSUE TITLE
Why can't I install opencv[core,eigen,ffmpeg,flann,jpeg,opengl,png,tiff]:x64-windows

### ISSUE THREAD

**Issue by dzz10** [microsoft/vcpkg#9310]
>vcpkg install darknet[opencv]:x64-windows

The following packages will be built and installed:
    darknet[core,opencv,weights]:x64-windows
  * opencv[core,eigen,ffmpeg,flann,jpeg,opengl,png,tiff]:x64-windows
  * pthreads[core]:x64-windows
  * stb[core]:x64-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/4: opencv:x64-windows
Building package opencv[core,eigen,ffmpeg,flann,jpeg,opengl,png,tiff]:x64-windows...
-- Using cached E:/setup/vcpkg/vcpkg-master/downloads/opencv-opencv-3.4.3.tar.gz
-- Using source at E:/setup/vcpkg/vcpkg-master/buildtrees/opencv/src/3.4.3-6bc372f345
**-- Using cached E:/setup/vcpkg/vcpkg-master/downloads/opencv-cache/ffmpeg/fa5a2a4e2f37defcb95bde8ed145c2b3-opencv_ffmpeg.dll
-- Downloading https://raw.githubusercontent.com/opencv/opencv_3rdparty/8041bd6f5ad37045c258904ba3030bb3442e3911/ffmpeg/opencv_ffmpeg_64.dll...**

**Comment by cenit** [comment]
What's happening is very strange. Looks like you are using a very old vcpkg repository 

git pull
./bootstrap-vcpkg.bat
Delete the buildtrees folder
./vcpkg install darknet[opencv]

**Comment by AlvinZhangH** [comment]
Hi, @dzz10 Thanks for reporting this issue.
`opencv` is not a feature of package `darknet`
run ".\vcpkg install darknet[core,opencv,weights]:x64-windows",
should prompt "Error: `opencv` is not a feature of package `darknet`".

`flann` is not a feature of package `opencv`.
run ".\vcpkg install opencv[core,eigen,ffmpeg,flann,jpeg,opengl,png,tiff]:x64-windows",
should prompt "Error: `flann` is not a feature of package `opencv`".

run "./vcpkg install darknet[opencv-base]", install ok.

**Comment by JackBoosY** [comment]
I think your vcpkg is too old, please follow @cenit's suggestion to resolve your issue.

Thanks.

**Comment by AlvinZhangH** [comment]
@dzz10  Is this issues solved?

**Comment by AlvinZhangH** [comment]
Please feel free to reopen it if this is still a problem for you.
