### ISSUE TITLE
[New Port Request] opendnp3

### ISSUE THREAD

**Issue by OOPMan** [microsoft/vcpkg#9312]
Library name: opendnp3

Library description: DNP3 (IEEE-1815) protocol stack. Modern C++ with bindings for .NET and Java

Source repository URL: https://github.com/dnp3/opendnp3/

Project homepage (if different from the source repository): https://dnp3.github.io

Anything else that is useful to know when adding (such as optional features the library may have that should be included): TLS support should be enabled

**Comment by NancyLi1013** [comment]
Hi @OOPMan 
Thanks for posting this request and also for your pull request.
Since this port has been added, I'm closing this issue for now.
