### ISSUE TITLE
[New Port Request] <Xpdf>

### ISSUE THREAD

**Issue by mamadymadan** [microsoft/vcpkg#9316]
Library name: xpdf

Library description: The Xpdf is an open source project that extract pdf to all its constituents same as text and font and image and etc.

Source repository URL: https://xpdfreader-dl.s3.amazonaws.com/xpdf-4.02.tar.gz

Project homepage (if different from the source repository): https://www.xpdfreader.com/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by NancyLi1013** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
