### ISSUE TITLE
[New Port Request] function2

### ISSUE THREAD

**Issue by gjasny** [microsoft/vcpkg#9318]
Library name: function2

Library description: Improved drop-in replacement to std::function

Source repository URL: https://github.com/Naios/function2

Our soon-to-be-open-sourced library uses function2 as a moveable C++ function pointer implementation. For CI runs on GitHub we need a CMake package manager and decided to use pretty well working and convenient vcpkg.

PR #9246 adds the function2 port.

**Comment by NancyLi1013** [comment]
Hi @gjasny 
Thanks for posting this request and also for your pull request.
Since this port has been added, I'm closing this issue for now.
