### ISSUE TITLE
[Simpleini] build failure on travis CI

### ISSUE THREAD

**Issue by AMS21** [microsoft/vcpkg#9320]
**Host Environment**
- OS: Linux/Ubuntu Xenial on travis
- Compiler: g++-9

**To Reproduce**
`git clone https://github.com/Microsoft/vcpkg.git`
`cd vcpkg`
`./bootstrap-vcpkg.sh`
`./vcpkg integrate install`
`./vcpkg update`
`./vcpkg install simpleini`

**Failure logs** 
> Starting package 2/3: simpleini:x64-linux
Building package simpleini[core]:x64-linux...
-- Downloading https://github.com/brofield/simpleini/archive/fe082fa81f4a55ddceb55056622136be616b3c6f.tar.gz...
-- Extracting source /home/travis/build/AMS21/OpenEast/deps/vcpkg/downloads/brofield-simpleini-fe082fa81f4a55ddceb55056622136be616b3c6f.tar.gz
-- Using source at /home/travis/build/AMS21/OpenEast/deps/vcpkg/buildtrees/simpleini/src/be616b3c6f-d6d01d7f61
CMake Error at ports/simpleini/portfile.cmake:12 (file):
  file COPY cannot find
  "/home/travis/build/AMS21/OpenEast/deps/vcpkg/buildtrees/simpleini/src/be616b3c6f-d6d01d7f61/Simpleini.h".
Call Stack (most recent call first):
  scripts/ports.cmake:94 (include)
Error: Building package simpleini:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: simpleini:x64-linux
  Vcpkg version: 2019.09.12-unknownhash

[Full build log](https://travis-ci.com/AMS21/OpenEast/jobs/267275121#L400)

**Additional context**
Already tried the same build with sudo.

**Comment by AMS21** [comment]
Just checked and using `./vcpkg install simpleini` no longer causes the build to fail on Linux. 
But on non windows Platforms another problem arises. But thats only true, when compiling on Windows or using ICC on all other platforms SimpleIni includes "ConvertUTF.h" and "ConvertUTF.c". Which is not copied to inside the portfile and thus will lead to an compiler error when using SimpleIni on Linux for example.
Also it could be argued that SimpleIni is not strictly a header only library.
See documentation of the SI_CONVERT_GENERIC macro https://github.com/brofield/simpleini/blob/master/SimpleIni.h#L2670
Build log from travis: https://travis-ci.com/AMS21/OpenEast/jobs/269515919#L1498

**Comment by JackBoosY** [comment]
Hi @AMS21, thanks for reporting this issue!
I've fixed it in #9429, please update vcpkg and rebuild it.

Thanks.
