### ISSUE TITLE
[VTK] build failure

### ISSUE THREAD

**Issue by larshg** [microsoft/vcpkg#9322]
**Host Environment**
- OS: Windows 10
- Compiler: VS2019 16.4.1

**To Reproduce**
`./vcpkg install vtk`

**Failure logs** 
Call stack in powershell:
```
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: ninja -v
    Working Directory: D:/libraries/vcpkg/buildtrees/vtk/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      D:\libraries\vcpkg\buildtrees\vtk\config-x64-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:293 (vcpkg_execute_required_process)
  ports/vtk/portfile.cmake:91 (vcpkg_configure_cmake)
  scripts/ports.cmake:94 (include)
```

Callstack in cmake output:
```
CMake Error at D:/libraries/vcpkg/scripts/buildsystems/vcpkg.cmake:263 (_find_package):
  Could not find a configuration file for package "PROJ4" that is compatible
  with requested version "6".

  The following configuration files were considered but not accepted:

    D:/libraries/vcpkg/installed/x64-windows/share/proj4/proj4-config.cmake, version: 6.2.0 (_MSC_VER = 1923)

Call Stack (most recent call first):
  CMake/FindLibPROJ.cmake:8 (find_package)
  D:/libraries/vcpkg/scripts/buildsystems/vcpkg.cmake:263 (_find_package)
  CMake/vtkModuleMacros.cmake:891 (find_package)
  ThirdParty/libproj/CMakeLists.txt:1 (vtk_module_third_party)


-- Configuring incomplete, errors occurred!
```

**Additional context**
It seems to have found Proj4 version 6.20 (_MSC_VER = 1923), but it isn't accepted as the log says.

**Comment by JackBoosY** [comment]
Hi @larshg, thanks for reporting this issue!
Can you modify _SOURCE_PATH/CMake/FindLibPROJ.cmake_ line 8 to:
`find_package(PROJ4 CONFIG REQUIRED)`
and try again?

Thanks.

**Comment by larshg** [comment]
Hi @JackBoosY 

I tried with both empty and 6.2.0, but the error message is the same (except the version matches what I request, ie "" or "6.2.0".

**Comment by JackBoosY** [comment]
@larshg Sorry to hear that, could you provide output again?

Thanks.

**Comment by larshg** [comment]
Here is the config output: [config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/3984242/config-x64-windows-out.log)

**Comment by JackBoosY** [comment]
@larshg Sorry for late.
Could you add `VERSION CONFIG` to _SOURCE_PATH/Thirdparty/libproj/CMakeLists.txt_ line 3 and try again?

Thanks.

**Comment by larshg** [comment]
Hi @JackBoosY 

Np. its hollidays time I guess :)

When I add `VERSION CONFIG` it shows the following:

```
CMake Error at D:/libraries/vcpkg/scripts/buildsystems/vcpkg.cmake:263 (_find_package):
  Could not find a package configuration file provided by "LibPROJ" with any
  of the following names:

    LibPROJConfig.cmake
    libproj-config.cmake

  Add the installation prefix of "LibPROJ" to CMAKE_PREFIX_PATH or set
  "LibPROJ_DIR" to a directory containing one of the above files.  If
  "LibPROJ" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  CMake/vtkModuleMacros.cmake:891 (find_package)
  ThirdParty/libproj/CMakeLists.txt:1 (vtk_module_third_party)
```

I then tried to rename it to ```PROJ4``` - but then it shows this again:

```
CMake Error at D:/libraries/vcpkg/scripts/buildsystems/vcpkg.cmake:263 (_find_package):
  Could not find a configuration file for package "PROJ4" that is compatible
  with requested version "".

  The following configuration files were considered but not accepted:

    D:/libraries/vcpkg/installed/x64-windows/share/proj4/proj4-config.cmake, version: 6.2.0 (_MSC_VER = 1923)

Call Stack (most recent call first):
  CMake/vtkModuleMacros.cmake:891 (find_package)
  ThirdParty/libproj/CMakeLists.txt:1 (vtk_module_third_party)
```

**Comment by JackBoosY** [comment]
This is quite weird, but I can repro it now. I think this is due to the wrong config.cmake / target.cmake exported by proj4.
Please remove _VCPKG_PATH/buildtrees/vtk/src/_, build vtk and terminate the build process after decompressing the source code, then replace _VCPKG_PATH/buildtrees/vtk/src/v8.2.0-***/CMake/FindLibPROJ.cmake_ with [this](https://github.com/microsoft/vcpkg/files/4009062/FindLibPROJ.zip). Then rebuild vtk.

If it works, I will open a PR to fix it.

Thanks.

**Comment by larshg** [comment]
@JackBoosY it doesn't seem to do anything. It still reports the same error.

**Comment by JackBoosY** [comment]
@larshg Could you provide proj cmake files in _D:/libraries/vcpkg/installed/x64-windows/share./proj4/_ ?
After remove version number, this shouldn't happened.

**Comment by larshg** [comment]
Hi @JackBoosY Here are all the .cmake files.
[proj4.zip](https://github.com/microsoft/vcpkg/files/4025001/proj4.zip)

However, since the MSVC_VER 1923 keeps popping up, I looked it up here [MSVC Versions](https://en.wikipedia.org/wiki/Microsoft_Visual_C%2B%2B).

Where 1923 is VS 16.3.x (which was what Proj4 was build with) - and I currently have VS 16.4.x installed - which apparently was the "error".

I removed PROJ4 and reinstalled it and now its currently building VTK.

Any reason, the PROJ4 is so restrictive on the VS version used?

**Comment by JackBoosY** [comment]
@larshg  Sorry for late, I'm dealing with other issues.

In _proj4-config-version.cmake_ line 27:
```
elseif (MSVC AND NOT MSVC_VERSION STREQUAL "1923")
  # Reject if there's a mismatch in MSVC compiler versions
  set (REASON "_MSC_VER = 1923")
  set (PACKAGE_VERSION_UNSUITABLE TRUE)
```
The proj4 cmake file automatically generates "1923". And it should be the same as "MSVC_VERSION" in VTK. 
But in the configuration log you provided:
```
-- The C compiler identification is MSVC 19.24.28314.0
-- The CXX compiler identification is MSVC 19.24.28314.0
```

So I guess you are built curl before Visual Studio update, and building vtk after Visual Studio update, is that right?

Please rebuild(remove + build) curl, then try to build vtk.

Thanks.

**Comment by larshg** [comment]
Well its working now?!

I had to rebuild Proj4 - which I did after I have updated Visual studio. So I guess I'll just close this issue, as its designed to be restrictive to compiler has been used.

**Comment by JackBoosY** [comment]
@larshg I think I should fix this issue. 
Please keep this issue open until I fix it. 

Thanks.
