### ISSUE TITLE
boost python module error

### ISSUE THREAD

**Issue by how0723** [microsoft/vcpkg#9323]
**Describe the bug**
my code: 
#include <boost/filesystem.hpp>
#include <boost/python/def.hpp>
#include <boost/python/module.hpp>

const char* GetVersion()
{
      return "v1.0.0.1";
}

BOOST_PYTHON_MODULE(interface_test)
{
    using namespace boost::python;
    def("GetVersion", GetVersion);
}

A C++ Function: GetVersion
It can be exposed to Python
But vs give me : “pyconfig.h”: No such file or directory

**Environment** 
- OS: win10 64bit
- Compiler: msvc141

**To Reproduce**
1. ./vcpkg install xxxx
2. See error
Repro code when

**Expected behavior**

**Failure logs** 
-(please attached failure logs)

**Additional context**

**Comment by Neumann-A** [comment]
The file is in a subfolder called python3.7 which is not automatically added to the includes if you only use the vs integration and not cmake

**Comment by how0723** [comment]
right. is not automatically added

**Comment by PhoebeHui** [comment]
The directory need to be added to the solution mannually, I don't think we have a plan to support this now.
