### ISSUE TITLE
[New Port Request] <gperftools>

### ISSUE THREAD

**Issue by how0723** [microsoft/vcpkg#9324]
Library name: gperftools

Library description: The fastest malloc we’ve seen; works particularly well with threads
and STL. Also: thread-friendly heap-checker, heap-profiler, and cpu-profiler.
(originally Google Performance Tools)

Source repository URL: https://github.com/gperftools/gperftools

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by myd7349** [comment]
https://github.com/microsoft/vcpkg/pull/8750

**Comment by NancyLi1013** [comment]
Hi @how0723 
`gperftools `has been added to vcpkg and please try to update vcpkg and use it.

@myd7349 
Thanks for your kindly reminder.

**Comment by JamesBewley** [comment]
Excuse my ignorance but how do I include this in my `CMakeLists.txt`?

I've installed with `./vcpkg install gperftools --triplet x64-linux` which worked but there was no advice on the end of the output describing how to use it.

I tried `find_package(gperftools REQUIRED)` but that doesn't work.

Is there another standard way to include this type of port?

**Comment by jwpleow** [comment]
> Excuse my ignorance but how do I include this in my `CMakeLists.txt`?
> 
> I've installed with `./vcpkg install gperftools --triplet x64-linux` which worked but there was no advice on the end of the output describing how to use it.
> 
> I tried: `find_package(gperftools REQUIRED)`
> 
> Also tried: ` find_library(GPERFTOOOLS_LIBRARY gperftools) link_libraries(${GPERFTOOOLS_LIBRARY})`
> 
> Is there another standard way to include this type of port?

This is how I used it (probably not ideal, but works for me!):
```
  find_path(GPERFTOOLS_INCLUDE_DIR gperftools/profiler.h)
  find_library(GPERFTOOLS_LIBRARY_TEMP profiler)
  if (NOT GPERFTOOLS_LIBRARY_TEMP)
    message(FATAL_ERROR "gperftools not found!")
  endif()
  add_library(gperftools STATIC IMPORTED)
  set_target_properties(gperftools PROPERTIES INTERFACE_INCLUDE_DIRECTORIES ${GPERFTOOLS_INCLUDE_DIR})
  set_target_properties(gperftools PROPERTIES IMPORTED_LOCATION ${GPERFTOOLS_LIBRARY_TEMP})
  set(GPERFTOOLS_LIBRARY -Wl,--whole-archive gperftools -Wl,--no-whole-archive)
  
  
  add_executable(<exec> ....)
  target_link_libraries(<exec> ${GPERFTOOLS_LIBRARY})
 ```
