### ISSUE TITLE
[openal-soft] build failure

### ISSUE THREAD

**Issue by AMS21** [microsoft/vcpkg#9325]
**Host Environment**
- OS: Windows on Appveyor
- Compiler: Visual Studio 2015

**To Reproduce**
`./vcpkg install openal`

**Failure logs** 
> Starting package 7/13: openal-soft:x86-windows
Building package openal-soft[core]:x86-windows...
-- Downloading https://github.com/kcat/openal-soft/archive/openal-soft-1.19.1.tar.gz...
-- Extracting source C:/Tools/vcpkg/downloads/kcat-openal-soft-openal-soft-1.19.1.tar.gz
-- Applying patch dont-export-symbols-in-static-build.patch
-- Applying patch fix-arm-builds.patch
-- Using source at C:/Tools/vcpkg/buildtrees/openal-soft/src/oft-1.19.1-a6a4e9d99e
-- Configuring x86-windows
-- Building x86-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: "C:/Program Files (x86)/CMake/bin/cmake.exe" --build . --config Debug --target install -- /p:VCPkgLocalAppDataDisabled=true /p:UseIntelMKL=No /m
    Working Directory: C:/Tools/vcpkg/buildtrees/openal-soft/x86-windows-dbg
    See logs for more information:
      C:\Tools\vcpkg\buildtrees\openal-soft\install-x86-windows-dbg-out.log
Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:91 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/openal-soft/portfile.cmake:59 (vcpkg_install_cmake)
  scripts/ports.cmake:94 (include)
Error: Building package openal-soft:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: openal-soft:x86-windows
  Vcpkg version: 2019.09.12-nohash

[Full log](https://ci.appveyor.com/project/CppAndre/openeast/builds/29547639/job/vf5o733ul9raf99h#L604)

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.
Failes with tripplet: x86-windows, x86-windows-static, x64-windows, x64-windows-static

**Comment by JackBoosY** [comment]
Duplicate with #7790.
