### ISSUE TITLE
benchmark library complie error

### ISSUE THREAD

**Issue by how0723** [microsoft/vcpkg#9326]
**Describe the bug**
benchmark            1.5              A library to support the benchmarking of functions, similar to unit-tests.
google benchmark library complie error
error message : : error LNK2019: 无法解析的外部符号 __imp_SHGetValueA，该符号在函数 "double __cdecl benchmark::`anonymous namespace'::GetCPUCyclesPerSecond(void)" (?GetCPUCyclesPerSecond@?A0x06d4e700@benchmark@@YANXZ) 中被引用
D:\workspace\vs\function_test\google-benchmark-test\\bin\x64\Debug\google-benchmark-test.exe : fatal error LNK1120: 1 个无法解析的外部命令
Unresolved external symbol

**Environment**
- OS: win10 64bit
- Compiler: msvc141

**To Reproduce**
1. ./vcpkg install xxxx
2. See error
Repro code when

**Expected behavior**

**Failure logs** 
-(please attached failure logs)

**Additional context**

**Comment by how0723** [comment]
solved 
must link Shlwapi.lib
add :
#pragma comment ( lib, "Shlwapi.lib" )

**Comment by JackBoosY** [comment]
Seemsthe link to Shlwapi.lib is missing.

**Comment by JackBoosY** [comment]
In _SOURCE_PATH/src/CMakeLists.txt_ line 46:
```
# We need extra libraries on Windows
if(${CMAKE_SYSTEM_NAME} MATCHES "Windows")
  target_link_libraries(benchmark Shlwapi)
endif()
```

@how0723 Could you change `if(${CMAKE_SYSTEM_NAME} MATCHES "Windows")` to `if(WIN32)` and try again?

Thanks.

**Comment by JackBoosY** [comment]
Hi @how0723, does this issue still bother you?
