### ISSUE TITLE
Under win 7 and VS2017 -5.18 to download package faild

### ISSUE THREAD

**Issue by DoMissHome** [microsoft/vcpkg#9327]
Under win 7 and VS2017 -5.18  to download package faild, i gets winhttpsendrequest 12029 error why? Is it OS ?

**Comment by PhoebeHui** [comment]
@DoMissHome , could provide us more information, eg, port name and failure logs?

**Comment by DoMissHome** [comment]
> @DoMissHome , could provide us more information, eg, port name and failure logs?

when i try to install zlib curl or any library by vcpkg,it always says  winhttpsendrequest 12029 error.At the first ,i think is the problem by os,but when i install the library by vcpkg under win10 ,that error comes  out too.i really do not kown why

**Comment by PhoebeHui** [comment]
Duplicated to https://github.com/microsoft/vcpkg/issues/9064.
