### ISSUE TITLE
Could not find Visual Studio. VS2015 or VS2017 (with C++) needs to be installed. vcpkg

### ISSUE THREAD

**Issue by pbipin** [microsoft/vcpkg#9328]
Once I clone vcpkg to a directory in Windows 10, I run .\bootstrap-vcpkg.bat from Powershell. However, following error occurs:
Could not find Visual Studio. VS2015 or VS2017 (with C++) needs to be installed.
At C:\CPP\vcpkg\scripts\bootstrap.ps1:143 char:9
+         throw "Could not find Visual Studio. VS2015 or VS2017 (with C ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Could not find ...o be installed.
   :String) [], RuntimeException
    + FullyQualifiedErrorId : Could not find Visual Studio. VS2015 or VS2017 (with
    C++) needs to be installed.

I found the same issue being raised here, but could not understand the solution mentioned. Kindly help me to solve this issue.

**Comment by AlvinZhangH** [comment]
Hi, @pbipin Thanks for reporting this issue.
You need install Visual Studio 2019, link
https://visualstudio.microsoft.com/zh-hans/vs/?rr=http%3A%2F%2Fwww.baidu.com%2Flink%3Furl%3DSVTex4JDby4HUtB3gxXDHqArrMBZVveLt-rW0hhxWp2B6Yr7zThG_Oyd8vLX72rg%26wd%3D%26eqid%3De1838db7000095d9000000065de47f03
Community 2019 is free.
Professionnal 2019 and Enterprise 2019 need to pay.

**Comment by JackBoosY** [comment]
Hi @pbipin, thanks for reporting this issue!
Vcpkg requires Visual Studio to build (minimum version is 2015) [1], please install Visual Studio before building vcpkg.

Thanks.

[1]. https://github.com/microsoft/vcpkg#quick-start

**Comment by ydzh** [comment]
May be You did`t install the MSVC. Just Check the "$vspath\VC\Tools\MSVC\"

**Comment by AlvinZhangH** [comment]
@pbipin Is this issue solved?

**Comment by AlvinZhangH** [comment]
Please feel free to reopen it if this is still a problem for you.

**Comment by pbipin** [comment]
> Please feel free to reopen it if this is still a problem for you.

Thank you AlvinZhangH for the inquiry. I apologize for not responding on time. The issue is solved. Thanks again.

**Comment by ujjwaltirkey** [comment]
@pbipin  please tell me how was this issue solved
i am having the same issue....

**Comment by Lunodzo** [comment]
@ujjwaltirkey me too here, @pbipin can you help please
![image](https://user-images.githubusercontent.com/22165685/75390170-d7919f00-58f8-11ea-982e-cf3c8b815d2c.png)

**Comment by drescherjm** [comment]
Try running it from a Visual Studio command prompt. Which version of Visual Studio do you have installed?

**Comment by JackBoosY** [comment]
@Lunodzo Please use powershell to build vcpkg.

**Comment by asifsaad12** [comment]
> Please feel free to reopen it if this is still a problem for you.

i am having problem @AlvinZhangH
