### ISSUE TITLE
[New Port Request] wxSqlite3 Library should be added

### ISSUE THREAD

**Issue by sinfee** [microsoft/vcpkg#9334]
Library name:wxSqlite3

Library description: wxSQLite3 is a C++ wrapper around the public domain SQLite 3.x database and is specifically designed for use in programs based on the wxWidgets library.

Source repository URL:https://github.com/utelle/wxsqlite3

Project homepage (if different from the source repository):
http://utelle.github.io/wxsqlite3
Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by NancyLi1013** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
