### ISSUE TITLE
install pcl:x64-windows-static failed

### ISSUE THREAD

**Issue by petrasvestartas** [microsoft/vcpkg#9338]
Hi,

I just installed vcpkg by running .bat file.

No I would like to install PCL - point cloud library package.
`.\vcpkg install pcl:x64-windows-static`

I get error:

**Error: Building package pcl:x64-windows-static failed with: BUILD_FAILED**
```
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: pcl:x64-windows-static
  Vcpkg version: 2019.09.12-nohash

Additionally, attach any relevant sections from the log files above.
PS C:\libs\vcpkg> .\vcpkg update
Using local portfile versions. To update the local portfiles, use `git pull`.
No packages need updating.
PS C:\libs\vcpkg>
```

How can I solve this issue?
Did I miss something in the installation part of VCPKG?

[install-x64-windows-static-dbg-out.log](https://github.com/microsoft/vcpkg/files/3967901/install-x64-windows-static-dbg-out.log)

**Comment by jasjuang** [comment]
If you read the log file carefully, it said `No space left on device`. Trying clearing up space in your hard drive and try again.

**Comment by AlvinZhangH** [comment]
@petrasvestartas  Is this issue solved?

**Comment by petrasvestartas** [comment]
Hi,

Static did not work.

The only way I coukd make it work is by dynamic install:
.\vcpkg install pcl:x64-windows

**Comment by JackBoosY** [comment]
@petrasvestartas Does your disk have free space?

**Comment by JackBoosY** [comment]
If this issue is still not resolved, please reopen it.
