### ISSUE TITLE
vcpkg doesn't automatically use the x64 triplet with a 64-bit cmake generator & compiler?

### ISSUE THREAD

**Issue by patrikhuber** [microsoft/vcpkg#9339]
Hi,

I use cmake-gui, and select the Visual Studio 16 - 2019 generator. This generator defaults to x64. I then select the vcpkg.cmake file as toolset file, according to the vcpkg documentation.

When the configuring a project in CMake, I get a warning

```
CMake Warning at C:/Users/Patrik/vcpkg/scripts/buildsystems/vcpkg.cmake:104 (message):
  There are no libraries installed for the Vcpkg triplet x86-windows.
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.16/Modules/CMakeDetermineSystem.cmake:93 (include)
  CMakeLists.txt:5 (project)
```

and subsequently no packages are found (because indeed, I don't have any packages installed for the x86-windows triplet).

I can "fix" this by changing the `VCPKG_TARGET_TRIPLET` to `x64-windows` and re-running configure.

**However**, I believe this step has never been necessary before, or has it? Previously, vcpkg would recognise that CMake is using a 64-bit generator and has detected a 64-bit cl.exe and would then automatically set/use the x64-windows triplet.

I updated lots of things recently (vcpkg: pulled latest master, yesterday; VS: 16.4.1; cmake: 3.16.1). But I am pretty sure that previously, I never needed to manually adjust the triplet to x64-windows.

My guess is that the interaction of any of these three components introduced a bug / regression recently?

Thanks.

**Comment by NancyLi1013** [comment]
Hi @patrikhuber thanks for posting this issue.
It's duplicate to #4908. Please refer to this issue.

**Comment by NancyLi1013** [comment]
Since the current behavior is intended. I close this issue now.

**Comment by patrikhuber** [comment]
Hi @NancyLi1013,

I don't think that #4908 is a duplicate. In #4908, the poster forgets to specify the 64-bit options in the CMake generator.

However, in the VS 2019 CMake Generator, x64 is the default.

So my question to you is: Given a 64-bit CMake Generator (e.g. VS 2019 - x64), is it intended behaviour that vcpkg will select and try to use the x86 triplet, and that the user then subsequently manually has to set `VCPKG_TARGET_TRIPLET` to `x64-windows`?
Has this always been the case? It feels to me like this step is unnecessary and was not needed in the past.

**Comment by NancyLi1013** [comment]
Hi @patrikhuber thanks for your feedback.
I have known this issue now. Since VS 2019 has supported x64 by default. This case is different from that in #4908.
Sorry for my mistake.
We need to double confirm about this.

**Comment by NancyLi1013** [comment]
@dan-shaw 
Could you help take a look?

**Comment by PhoebeHui** [comment]
@patrikhuber, thanks for bringing this up!

Currently this issue fixed by PR https://github.com/microsoft/vcpkg/pull/9816, could you get latest source and try again? Let me know if it still be a problem for you.
