### ISSUE TITLE
[devil] build failure - fails to configure/link with openEXR

### ISSUE THREAD

**Issue by LaurensVoerman** [microsoft/vcpkg#9340]
**Host Environment**
- OS: Windows 10 1909 x64
- Compiler: Visual Studio Community 16.4.1

**To Reproduce**
`./vcpkg install devil`

**Failure logs** 
in buildtrees\devil\config-x64-windows-dbg-out.log:
-- Could NOT find OPENEXR (missing: OPENEXR_LIBRARIES)

**Additional context**
patched file "DevIL\src-IL\cmake\FindOpenEXR.cmake" searches for openEXR 2_2,
vcpackage has version 2_3

**Comment by JackBoosY** [comment]
Close this issue via #9341 merged.
