### ISSUE TITLE
WinhttpSendRequest faild 12092

### ISSUE THREAD

**Issue by DoMissHome** [microsoft/vcpkg#9342]
I get that error when I trying to install some library like zlib or someone else .i do  not know why

**Comment by DoMissHome** [comment]
C:\Users\zjw>D:\vcpkg\vcpkg.exe install curl
The following packages will be built and installed:
    curl[core,ssl,winssl]:x86-windows
  * zlib[core]:x86-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/2: zlib:x86-windows
Building package zlib[core]:x86-windows...
A suitable version of powershell-core was not found (required v6.2.1). Downloading portable powershell-core v6.2.1...
Extracting powershell-core...
A suitable version of 7zip was not found (required v18.1.0). Downloading portable 7zip v18.1.0...
Downloading 7zip...
  https://www.nuget.org/api/v2/package/7-Zip.CommandLine/18.1.0 -> D:\vcpkg\downloads\7-zip.commandline.18.1.0.nupkg
WinHttpSendRequest() failed: 12029
Is that i need to install powershell-core 6.2.1 and then the vcpkg install works well?

**Comment by AlvinZhangH** [comment]
Hi, @DoMissHome Thanks for reporting this issue.
Why not download "https://www.nuget.org/api/v2/package/7-Zip.CommandLine/18.1.0" manually, then put it and rename to
"D:\vcpkg\downloads\7-zip.commandline.18.1.0.nupkg", run "C:\Users\zjw>D:\vcpkg\vcpkg.exe install curl" again.

**Comment by PhoebeHui** [comment]
Duplicated to https://github.com/microsoft/vcpkg/issues/9064

**Comment by DoMissHome** [comment]
what if i install other library? it alway reports WinHttpSendRequest faild when i commit vcpkg.exe install .is vcpkg need powershell6.2.1 to download package?
