### ISSUE TITLE
Error: Building package boost-test:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by giserHacter** [microsoft/vcpkg#9345]
Hello,devs
I miss build error that is:
"Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-test:x64-windows
  Vcpkg version: 2019.09.12-nohash

Additionally, attach any relevant sections from the log files above."

**Comment by AlvinZhangH** [comment]
Hi, @giserHacter Thanks for reporting this issue.
I do not reproduce the issue in my environment.
Please check your environment.

Thanks.
[1]. https://github.com/microsoft/vcpkg#quick-start

**Comment by AlvinZhangH** [comment]
@giserHacter , could provide us failure logs?

**Comment by JackBoosY** [comment]
If this issue is still not resolved, please reopen it.

**Comment by 9and3** [comment]
Hello I do have the same problem in trying to install pcl.

Error: Building package boost-test:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-test:x64-windows
  Vcpkg version: 2020.06.15-nohash

Anyone managed to solve it? Thanks
