### ISSUE TITLE
[pbc] build failure on MacOS

### ISSUE THREAD

**Issue by decent-dcore** [microsoft/vcpkg#9348]
**Host Environment**
- OS: MacOS
- Compiler: clang

**To Reproduce**
`./vcpkg install pbc`

**Failure logs** 
- none: its a dependency problem

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by PhoebeHui** [comment]
The PR has been merged, so close this bug.
