### ISSUE TITLE
vcpkg install fails with "Install plan cannot be empty"

### ISSUE THREAD

**Issue by espresso3389** [Microsoft/vcpkg#935]
My environment:
- Windows 10 Pro 1703 (64bit,Japanese)
- Visual Studio 2017 Professional
- vcpkg 3739e8e0b998b14c0f320c21618057e50698c51d
- no user-wide integration

When I execute the following command line from PowerShell, it does not do anything but show the error:
```
PS C:\work\vcpkg> .\vcpkg.exe install curl
Install plan cannot be empty
```

What's the problem with my environment?

**Comment by ras0219-msft** [comment]
Hi @espresso3389!

It looks like we were bit by "just one more tiny commit" as we pushed the last set of changes. I was able to reproduce your issue locally and reverted the offending commit, which fixes it on my machine.

Please pull and run bootstrap again to get that change.

Thanks for reporting this, and sorry for the inconvenience!

**Comment by espresso3389** [comment]
I just pulled d193dae2ce68eaa5e3c35d0882091b1ceaf6d82b.
And it works correctly now.

Thanks!
