### ISSUE TITLE
How to find ICU in CMake

### ISSUE THREAD

**Issue by Krantz-XRF** [microsoft/vcpkg#9352]
I installed ICU with `vcpkg`, but I cannot use it in CMake. All other packages installed can be found by `find_package`, but `find_package(ICU REQUIRED)` fails the CMake configuration process, and `find_package(icu REQUIRED)` (with `icu` being lowercased) silently fails without stopping the configuration process:

    Failed to find all ICU components (missing: ICU_LIBRARY) (found version "61.1")
    Configuring done

After looking up CMake variable cache, I found that the ICU headers are found, and ICU version are somehow determined, but other ICU-related variables are all `*-NOTFOUND`.

Have anyone successfully used `vcpkg`-installed ICU in CMake?

**Comment by Krantz-XRF** [comment]
I just found a workaround for this by manually defining `ICU_ROOT` to `vcpkg/installed/x64-windows-static`. However, I believe this should have worked out of box, rather than requiring me to manually set the variable.

**Comment by myd7349** [comment]
> cmake .. -DCMAKE_TOOLCHAIN_FILE="%VCPKG_ROOT%\scripts\buildsystems\vcpkg.cmake" -DVCPKG_TARGET_TRIPLET=x64-windows-static -DCMAKE_GENERATOR_PLATFORM=x64

**Comment by NancyLi1013** [comment]
Hi @Krantz-XRF thanks for posting this issue.
Since icu has a series of components. 
So we need to add the key word `COMPONENTS `.
If we want to find` icuuc icudt icuin icuio`, we can use `find_package(ICU REQUIRED COMPONENTS uc dt in io)`.

**Comment by Krantz-XRF** [comment]
@NancyLi1013 Thanks! After adding `COMPONENTS` it worked correctly. I really should have thought of that.
