### ISSUE TITLE
 Package: angle:x64-windows   Vcpkg version: 2019.09.12-nohash

### ISSUE THREAD

**Issue by harella1** [microsoft/vcpkg#9353]
**command**
vcpkg install angle:x64-windows

**fail:**
```
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: D:/dev/vcpkg/downloads/tools/cmake-3.14.0-windows/cmake-3.14.0-win32-x86/bin/cmake.exe --build . --config Debug --target install -- -v
    Working Directory: D:/dev/vcpkg/buildtrees/angle/x64-windows-dbg
    See logs for more information:
      D:\dev\vcpkg\buildtrees\angle\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:91 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/angle/portfile.cmake:39 (vcpkg_install_cmake)
  scripts/ports.cmake:94 (include)
```
**last log line**
```
[294/447] C:\PROGRA~2\MIB055~1\2019\ENTERP~1\VC\Tools\MSVC\1424~1.283\bin\Hostx64\x64\cl.exe   /TP -DANGLE_ENABLE_D3D11 -DANGLE_ENABLE_D3D9 -DANGLE_ENABLE_DEBUG_ANNOTATIONS -DANGLE_ENABLE_ESSL -DANGLE_ENABLE_GLSL -DANGLE_ENABLE_HLSL -DANGLE_ENABLE_NULL -DANGLE_ENABLE_OPENGL -DANGLE_PRELOADED_D3DCOMPILER_MODULE_NAMES="{ \"d3dcompiler_47.dll\", \"d3dcompiler_46.dll\", \"d3dcompiler_43.dll\" }" -DANGLE_STANDALONE_BUILD -DGL_SILENCE_DEPRECATION -DLIBANGLE_IMPLEMENTATION -DNOMINMAX -D_CRT_SECURE_NO_DEPRECATE -D_HAS_EXCEPTIONS=0 -D_SCL_SECURE_NO_WARNINGS -ID:\dev\vcpkg\buildtrees\angle\src\6ed2964ffd-92f5caafbc\include -ID:\dev\vcpkg\buildtrees\angle\src\6ed2964ffd-92f5caafbc\src -Iinclude -ID:\dev\vcpkg\buildtrees\angle\src\6ed2964ffd-92f5caafbc\src\third_party\khronos -ID:\dev\vcpkg\buildtrees\angle\src\6ed2964ffd-92f5caafbc\src\common\third_party\base /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1    /d2guard4 /Wv:18 /guard:cf /permissive /bigobj /showIncludes /FoCMakeFiles\libANGLE.dir\src\libANGLE\renderer\gl\wgl\DXGISwapChainWindowSurfaceWGL.cpp.obj /FdCMakeFiles\libANGLE.dir\libANGLE.pdb /FS -c D:\dev\vcpkg\buildtrees\angle\src\6ed2964ffd-92f5caafbc\src\libANGLE\renderer\gl\wgl\DXGISwapChainWindowSurfaceWGL.cpp
Microsoft (R) C/C++ Optimizing Compiler Version 19.24.28314 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

ninja: build stopped: subcommand failed.

**ran this last commnd in vs cmd, and result is:**
D:\dev\vcpkg\buildtrees\angle\src\6ed2964ffd-92f5caafbc\src\libANGLE\renderer\gl\wgl\DXGISwapChainWindowSurfaceWGL.cpp : fatal error C1083: Cannot open compiler generated file: 'D:\dev\vcpkg\CMakeFiles\libANGLE.dir\src\libANGLE\renderer\gl\wgl\DXGISwapChainWindowSurfaceWGL.cpp.obj': No such file or directory
```

**Comment by JackBoosY** [comment]
Hi @harella1, thanks for reporting this issue!
I cannot repro it on my machine, please provide your Visual Studio version and full configure/build log.

Thanks.

**Comment by harella1** [comment]
Hello.
Microsoft Visual Studio Enterprise 2019
Version 16.4.2
VisualStudio.16.Release/16.4.2+29613.14
Microsoft .NET Framework
Version 4.8.03752
Installed Version: Enterprise
Visual C++ 2019   00435-60000-00000-AA942
Visual C++ for Cross Platform Mobile Development (Android)   16.0.29428.195
Visual C++ for Linux Development   1.0.9.29512
Visual Studio Tools for CMake   1.0

in the file: "\vcpkg\buildtrees\angle\install-x64-windows-dbg-out.log" i found this:
----------------------------------------------------
[275/447] C:\PROGRA~2\MIB055~1\2019\ENTERP~1\VC\Tools\MSVC\1424~1.283\bin\Hostx64\x64\cl.exe   /TP -DANGLE_ENABLE_DEBUG_ANNOTATIONS -DANGLE_STANDALONE_BUILD -DGL_SILENCE_DEPRECATION -DNOMINMAX -D_CRT_SECURE_NO_DEPRECATE -D_HAS_EXCEPTIONS=0 -D_SCL_SECURE_NO_WARNINGS -ID:\dev\vcpkg\buildtrees\angle\src\6ed2964ffd-92f5caafbc\include -ID:\dev\vcpkg\buildtrees\angle\src\6ed2964ffd-92f5caafbc\src -Iinclude -ID:\dev\vcpkg\buildtrees\angle\src\6ed2964ffd-92f5caafbc\src\common\third_party\base /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1    /d2guard4 /Wv:18 /guard:cf /permissive /bigobj /showIncludes /FoCMakeFiles\angle_gpu_info_util.dir\src\gpu_info_util\SystemInfo_win.cpp.obj /FdCMakeFiles\angle_gpu_info_util.dir\angle_gpu_info_util.pdb /FS -c D:\dev\vcpkg\buildtrees\angle\src\6ed2964ffd-92f5caafbc\src\gpu_info_util\SystemInfo_win.cpp
FAILED: CMakeFiles/angle_gpu_info_util.dir/src/gpu_info_util/SystemInfo_win.cpp.obj 
C:\PROGRA~2\MIB055~1\2019\ENTERP~1\VC\Tools\MSVC\1424~1.283\bin\Hostx64\x64\cl.exe   /TP -DANGLE_ENABLE_DEBUG_ANNOTATIONS -DANGLE_STANDALONE_BUILD -DGL_SILENCE_DEPRECATION -DNOMINMAX -D_CRT_SECURE_NO_DEPRECATE -D_HAS_EXCEPTIONS=0 -D_SCL_SECURE_NO_WARNINGS -ID:\dev\vcpkg\buildtrees\angle\src\6ed2964ffd-92f5caafbc\include -ID:\dev\vcpkg\buildtrees\angle\src\6ed2964ffd-92f5caafbc\src -Iinclude -ID:\dev\vcpkg\buildtrees\angle\src\6ed2964ffd-92f5caafbc\src\common\third_party\base /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1    /d2guard4 /Wv:18 /guard:cf /permissive /bigobj /showIncludes /FoCMakeFiles\angle_gpu_info_util.dir\src\gpu_info_util\SystemInfo_win.cpp.obj /FdCMakeFiles\angle_gpu_info_util.dir\angle_gpu_info_util.pdb /FS -c D:\dev\vcpkg\buildtrees\angle\src\6ed2964ffd-92f5caafbc\src\gpu_info_util\SystemInfo_win.cpp
Microsoft (R) C/C++ Optimizing Compiler Version 19.24.28314 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\combaseapi.h(383): error C2143: syntax error: missing ',' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\combaseapi.h(397): error C2143: syntax error: missing ',' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\combaseapi.h(404): error C2143: syntax error: missing ',' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\combaseapi.h(614): error C2143: syntax error: missing ',' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\combaseapi.h(632): error C2143: syntax error: missing ',' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\combaseapi.h(736): error C2143: syntax error: missing ',' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\combaseapi.h(755): error C2143: syntax error: missing ',' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\combaseapi.h(804): error C2143: syntax error: missing ',' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\combaseapi.h(818): error C2143: syntax error: missing ',' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\combaseapi.h(866): error C2143: syntax error: missing ',' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\combaseapi.h(1046): error C2143: syntax error: missing ',' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\combaseapi.h(1209): error C2143: syntax error: missing ',' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\combaseapi.h(1221): error C2143: syntax error: missing ',' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\combaseapi.h(1240): error C2143: syntax error: missing ',' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\combaseapi.h(1266): error C2143: syntax error: missing ',' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\combaseapi.h(1434): error C2143: syntax error: missing ',' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\combaseapi.h(1465): error C2143: syntax error: missing ',' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\coml2api.h(258): error C2143: syntax error: missing ',' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\coml2api.h(272): error C2143: syntax error: missing ',' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\coml2api.h(288): error C2143: syntax error: missing ',' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\coml2api.h(297): error C2143: syntax error: missing ',' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\objbase.h(85): error C2143: syntax error: missing ',' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\objbase.h(85): error C2259: 'IMalloc': cannot instantiate abstract class
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\objidlbase.h(1148): note: see declaration of 'IMalloc'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\objbase.h(85): note: due to following members:
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\objbase.h(85): note: 'HRESULT IUnknown::QueryInterface(const IID &,void **)': is abstract
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\unknwnbase.h(113): note: see declaration of 'IUnknown::QueryInterface'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\objbase.h(85): note: 'ULONG IUnknown::AddRef(void)': is abstract
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\unknwnbase.h(117): note: see declaration of 'IUnknown::AddRef'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\objbase.h(85): note: 'ULONG IUnknown::Release(void)': is abstract
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\unknwnbase.h(119): note: see declaration of 'IUnknown::Release'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\objbase.h(85): note: 'void *IMalloc::Alloc(SIZE_T)': is abstract
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\objidlbase.h(1151): note: see declaration of 'IMalloc::Alloc'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\objbase.h(85): note: 'void *IMalloc::Realloc(void *,SIZE_T)': is abstract
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\objidlbase.h(1155): note: see declaration of 'IMalloc::Realloc'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\objbase.h(85): note: 'void IMalloc::Free(void *)': is abstract
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\objidlbase.h(1161): note: see declaration of 'IMalloc::Free'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\objbase.h(85): note: 'SIZE_T IMalloc::GetSize(void *)': is abstract
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\objidlbase.h(1165): note: see declaration of 'IMalloc::GetSize'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\objbase.h(85): note: 'int IMalloc::DidAlloc(void *)': is abstract
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\objidlbase.h(1169): note: see declaration of 'IMalloc::DidAlloc'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\objbase.h(85): note: 'void IMalloc::HeapMinimize(void)': is abstract
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\objidlbase.h(1173): note: see declaration of 'IMalloc::HeapMinimize'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\objbase.h(155): error C2143: syntax error: missing ',' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\objbase.h(157): error C2143: syntax error: missing ',' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\objbase.h(158): error C2143: syntax error: missing ',' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\objbase.h(161): error C2143: syntax error: missing ',' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\objbase.h(176): error C2143: syntax error: missing ',' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\objbase.h(179): error C2143: syntax error: missing ',' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\objbase.h(224): error C2143: syntax error: missing ',' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\objbase.h(228): error C2143: syntax error: missing ',' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\objbase.h(230): error C2143: syntax error: missing ',' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\objbase.h(232): error C2143: syntax error: missing ',' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\objbase.h(233): error C2143: syntax error: missing ',' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\objbase.h(235): error C2143: syntax error: missing ',' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\objbase.h(236): error C2143: syntax error: missing ',' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\objbase.h(238): error C2143: syntax error: missing ',' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\objbase.h(240): error C2143: syntax error: missing ',' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\objbase.h(243): error C2143: syntax error: missing ',' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\objbase.h(244): error C2143: syntax error: missing ',' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\objbase.h(245): error C2143: syntax error: missing ',' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\objbase.h(246): error C2143: syntax error: missing ',' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\objbase.h(254): error C2143: syntax error: missing ',' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\urlmon.h(529): error C2143: syntax error: missing ',' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\urlmon.h(530): error C2143: syntax error: missing ',' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\urlmon.h(535): error C2143: syntax error: missing ',' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\oleauto.h(293): error C2143: syntax error: missing ',' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\oleauto.h(304): error C2143: syntax error: missing ',' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\oleauto.h(309): error C2143: syntax error: missing ',' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\oleauto.h(320): error C2143: syntax error: missing ',' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\oleauto.h(325): error C2143: syntax error: missing ',' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\oleauto.h(336): error C2143: syntax error: missing ',' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\oleauto.h(341): error C2143: syntax error: missing ',' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\oleauto.h(342): error C2143: syntax error: missing ',' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\oleauto.h(343): error C2143: syntax error: missing ',' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\oleauto.h(344): error C2143: syntax error: missing ',' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\oleauto.h(345): error C2143: syntax error: missing ',' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\oleauto.h(346): error C2143: syntax error: missing ',' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\oleauto.h(347): error C2143: syntax error: missing ',' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\oleauto.h(348): error C2143: syntax error: missing ',' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\oleauto.h(348): error C2259: 'IDispatch': cannot instantiate abstract class
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\oaidl.h(2201): note: see declaration of 'IDispatch'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\oleauto.h(348): note: due to following members:
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\oleauto.h(348): note: 'HRESULT IUnknown::QueryInterface(const IID &,void **)': is abstract
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\unknwnbase.h(113): note: see declaration of 'IUnknown::QueryInterface'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\oleauto.h(348): note: 'ULONG IUnknown::AddRef(void)': is abstract
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\unknwnbase.h(117): note: see declaration of 'IUnknown::AddRef'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\oleauto.h(348): note: 'ULONG IUnknown::Release(void)': is abstract
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\unknwnbase.h(119): note: see declaration of 'IUnknown::Release'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\oleauto.h(348): note: 'HRESULT IDispatch::GetTypeInfoCount(UINT *)': is abstract
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\oaidl.h(2204): note: see declaration of 'IDispatch::GetTypeInfoCount'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\oleauto.h(348): note: 'HRESULT IDispatch::GetTypeInfo(UINT,LCID,ITypeInfo **)': is abstract
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\oaidl.h(2207): note: see declaration of 'IDispatch::GetTypeInfo'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\oleauto.h(348): note: 'HRESULT IDispatch::GetIDsOfNames(const IID &,LPOLESTR *,UINT,LCID,DISPID *)': is abstract
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\oaidl.h(2212): note: see declaration of 'IDispatch::GetIDsOfNames'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\oleauto.h(348): note: 'HRESULT IDispatch::Invoke(DISPID,const IID &,LCID,WORD,DISPPARAMS *,VARIANT *,EXCEPINFO *,UINT *)': is abstract
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\oaidl.h(2219): note: see declaration of 'IDispatch::Invoke'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\oleauto.h(349): error C2143: syntax error: missing ',' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\oleauto.h(350): error C2143: syntax error: missing ',' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\oleauto.h(351): error C2143: syntax error: missing ',' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\oleauto.h(352): error C2143: syntax error: missing ',' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\oleauto.h(353): error C2143: syntax error: missing ',' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\oleauto.h(354): error C2143: syntax error: missing ',' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\oleauto.h(363): error C2143: syntax error: missing ',' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\oleauto.h(373): error C2143: syntax error: missing ',' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\oleauto.h(379): error C2143: syntax error: missing ',' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\oleauto.h(389): error C2143: syntax error: missing ',' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\oleauto.h(395): error C2143: syntax error: missing ',' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\oleauto.h(405): error C2143: syntax error: missing ',' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\oleauto.h(411): error C2143: syntax error: missing ',' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\oleauto.h(421): error C2143: syntax error: missing ',' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\oleauto.h(427): error C2143: syntax error: missing ',' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\oleauto.h(437): error C2143: syntax error: missing ',' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\oleauto.h(443): error C2143: syntax error: missing ',' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\oleauto.h(453): error C2143: syntax error: missing ',' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\oleauto.h(583): error C2143: syntax error: missing ',' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\oleauto.h(584): error C2143: syntax error: missing ',' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\oleauto.h(592): error C2143: syntax error: missing ',' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\oleauto.h(600): error C2143: syntax error: missing ',' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\oleauto.h(601): error C2143: syntax error: missing ',' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\oleauto.h(602): error C2143: syntax error: missing ',' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\oleauto.h(603): error C2143: syntax error: missing ',' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\oleauto.h(604): error C2143: syntax error: missing ',' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\oleauto.h(605): error C2143: syntax error: missing ',' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\oleauto.h(606): error C2143: syntax error: missing ',' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\oleauto.h(606): error C2259: 'IDispatch': cannot instantiate abstract class
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\oaidl.h(2201): note: see declaration of 'IDispatch'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\oleauto.h(606): note: due to following members:
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\oleauto.h(606): note: 'HRESULT IUnknown::QueryInterface(const IID &,void **)': is abstract
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\unknwnbase.h(113): note: see declaration of 'IUnknown::QueryInterface'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\oleauto.h(606): note: 'ULONG IUnknown::AddRef(void)': is abstract
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\unknwnbase.h(117): note: see declaration of 'IUnknown::AddRef'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\oleauto.h(606): note: 'ULONG IUnknown::Release(void)': is abstract
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\unknwnbase.h(119): note: see declaration of 'IUnknown::Release'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\oleauto.h(606): note: 'HRESULT IDispatch::GetTypeInfoCount(UINT *)': is abstract
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\oaidl.h(2204): note: see declaration of 'IDispatch::GetTypeInfoCount'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\oleauto.h(606): note: 'HRESULT IDispatch::GetTypeInfo(UINT,LCID,ITypeInfo **)': is abstract
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\oaidl.h(2207): note: see declaration of 'IDispatch::GetTypeInfo'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\oleauto.h(606): note: 'HRESULT IDispatch::GetIDsOfNames(const IID &,LPOLESTR *,UINT,LCID,DISPID *)': is abstract
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\oaidl.h(2212): note: see declaration of 'IDispatch::GetIDsOfNames'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\oleauto.h(606): note: 'HRESULT IDispatch::Invoke(DISPID,const IID &,LCID,WORD,DISPPARAMS *,VARIANT *,EXCEPINFO *,UINT *)': is abstract
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\oaidl.h(2219): note: see declaration of 'IDispatch::Invoke'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\oleauto.h(607): error C2143: syntax error: missing ',' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\oleauto.h(608): error C2143: syntax error: missing ',' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\oleauto.h(609): error C2143: syntax error: missing ',' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\oleauto.h(610): error C2143: syntax error: missing ',' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\oleauto.h(611): error C2143: syntax error: missing ',' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\oleauto.h(644): error C2733: 'VarI4FromI8': you cannot overload a function with 'extern "C"' linkage
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\oleauto.h(325): note: see declaration of 'VarI4FromI8'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\oleauto.h(645): error C2733: 'VarI4FromUI8': you cannot overload a function with 'extern "C"' linkage
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\oleauto.h(336): note: see declaration of 'VarI4FromUI8'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\ole2.h(87): error C2143: syntax error: missing ',' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\ole2.h(95): error C2143: syntax error: missing ',' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\ole2.h(115): error C2143: syntax error: missing ',' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\ole2.h(120): error C2143: syntax error: missing ',' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\ole2.h(120): fatal error C1003: error count exceeds 100; stopping compilation

if you could point me to the desired log/config files that can help?
thank you
harel

**Comment by harella1** [comment]
sorry for closing

**Comment by JackBoosY** [comment]
Seems like a Windows SDK bug, please uninstall 10.0.18362 and install 10.0.17763 then try again.

Thanks.

**Comment by shibayan** [comment]
I looked into it because it was interesting, and it seems that it was an error in the part with `FAR`.
FAR Pointer is not necessary for the current CPU, so it should be safe to ignore it.

If you modify the `gpu_info_util\SystemInfo_win.cpp` file, the build now passes. I don't know if it's a combination of compile options or a compiler problem.

```cpp
// Windows.h needs to be included first
#include <windows.h>

// Adding undef FAR
#undef FAR

#include <d3d10.h>
```

**Comment by JackBoosY** [comment]
@shibayan I suddenly thought that #7923 was solving this issue.

Duplicate with #7744.
