### ISSUE TITLE
BitDefender Antivirus vcpkg detected, quarentied and blocked access to the web

### ISSUE THREAD

**Issue by Bambofy** [microsoft/vcpkg#9354]

**Comment by NancyLi1013** [comment]
Hi @Bambofy thanks for posting this issue.
Could you please make a simple clarify or provide more info about this issue?

**Comment by NancyLi1013** [comment]
Please refer to this issue #1521.

**Comment by ThrashAbaddon** [comment]
I'm also experiencing the problem. :/

**Comment by Bambofy** [comment]
> I'm also experiencing this problem. :/
> I'm trying to install vcpkg on win10 by calling `PS C:\Users\Kusari\source\vcpkg> .\bootstrap-vcpkg.bat` with admin rights and after few seconds this is the result:
> 
> ```
>   Finished generating code
>   vcpkgmetricsuploader.vcxproj -> C:\Users\Kusari\source\vcpkg\toolsrc\msbuild.x86.release\vcpkgmetricsuploader.exe
> 
> Building vcpkg.exe... done.
> 
> Telemetry
> ---------
> vcpkg collects usage data in order to help us improve your experience. The data collected by Microsoft is anonymous. You can opt-out of telemetry by re-running bootstrap-vcpkg.bat with -disableMetrics.
> Read more about vcpkg telemetry at docs/about/privacy.md
> 
> Copy-Item : Access to the path 'C:\Users\Kusari\source\vcpkg\vcpkg.exe' is denied.
> At C:\Users\Kusari\source\vcpkg\scripts\bootstrap.ps1:425 char:1
> + Copy-Item "$vcpkgReleaseDir\vcpkg.exe" "$vcpkgRootDir\vcpkg.exe"
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : PermissionDenied: (C:\Users\Kusari...lease\vcpkg.exe:FileInfo) [Copy-Item], Unauthorized
>    AccessException
>     + FullyQualifiedErrorId : CopyFileInfoItemUnauthorizedAccessError,Microsoft.PowerShell.Commands.CopyItemCommand
> 
> Copy-Item : Access to the path 'C:\Users\Kusari\source\vcpkg\scripts\vcpkgmetricsuploader.exe' is denied.
> At C:\Users\Kusari\source\vcpkg\scripts\bootstrap.ps1:426 char:1
> + Copy-Item "$vcpkgReleaseDir\vcpkgmetricsuploader.exe" "$vcpkgRootDir\ ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : PermissionDenied: (C:\Users\Kusari...icsuploader.exe:FileInfo) [Copy-Item], Unauthorized
>    AccessException
>     + FullyQualifiedErrorId : CopyFileInfoItemUnauthorizedAccessError,Microsoft.PowerShell.Commands.CopyItemCommand
> ```
> 
> . I disabled bitdefender later on but still get this error.
> As you can see I've also excluded this specific error
> ![image](https://user-images.githubusercontent.com/7493180/71076974-dcaed100-2186-11ea-91d7-e8721fc24c35.png)
> , and also excluded the whole `vcpkg` folder because bitdefender was complaining during telemetry setting up.

Hi, the way around it is to "unblock" and "allow access" in the notifications as vcpkg tries to do things.

**Comment by beckylum0216** [comment]
Hi,

My anti-virus also detected this infection. Can we confirm if this is a false positive? 

![Annotation 2019-12-18 224451](https://user-images.githubusercontent.com/11342938/71096817-f5040780-21e9-11ea-8259-c0bf0882642f.jpg)

**Comment by NancyLi1013** [comment]
Hi all, thanks for paying attention to this issue.
I think It's duplicate to #8118.  
This is not a vcpkg issue. So I will close it now.
