### ISSUE TITLE
[SFML] build failure

### ISSUE THREAD

**Issue by AMS21** [microsoft/vcpkg#9355]
**Host Environment**
- OS: macOS 10.14.4 (Travis)
- Compiler: xcode10.3

**To Reproduce**
`./vcpkg install SFML`

**Failure logs** 
> Starting package 39/47: sfml:x64-osx
Building package sfml[core]:x64-osx...
-- Downloading https://github.com/SFML/SFML/archive/2.5.1.tar.gz...
-- Extracting source /Users/travis/build/AMS21/OpenEast/deps/vcpkg/downloads/SFML-SFML-2.5.1.tar.gz
-- Applying patch use-system-freetype.patch
-- Using source at /Users/travis/build/AMS21/OpenEast/deps/vcpkg/buildtrees/sfml/src/2.5.1-f499a1097e
-- Configuring x64-osx-dbg
-- Configuring x64-osx-rel
-- Building x64-osx-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: /Users/travis/build/AMS21/OpenEast/deps/vcpkg/downloads/tools/cmake-3.14.0-osx/cmake-3.14.0-Darwin-x86_64/CMake.app/Contents/bin/cmake --build . --config Debug --target install -- -v
    Working Directory: /Users/travis/build/AMS21/OpenEast/deps/vcpkg/buildtrees/sfml/x64-osx-dbg
    See logs for more information:
      /Users/travis/build/AMS21/OpenEast/deps/vcpkg/buildtrees/sfml/install-x64-osx-dbg-out.log
Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:91 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/sfml/portfile.cmake:32 (vcpkg_install_cmake)
  scripts/ports.cmake:94 (include)
Error: Building package sfml:x64-osx failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: sfml:x64-osx
  Vcpkg version: 2019.09.12-unknownhash
**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by AMS21** [comment]
Build failure also occurs with macOS 10.13 and XCode 10.1

**Comment by JackBoosY** [comment]
Hi @AMS21, sorry for late.
Does this issue still exist?

**Comment by JackBoosY** [comment]
We haven't been able to repro this; if more information comes up, or this issue appears again, please reopen.
