### ISSUE TITLE
BUILD_FAILED Building package grpc:x86-windows

### ISSUE THREAD

**Issue by khalprin** [microsoft/vcpkg#9356]
Using vcpkg that was cloned half an hour before this build attempt - so should be the latest available version. Built the 64-bit version successfully just prior to this attempt.

Building package grpc[core]:x86-windows...
-- Note: grpc only supports static library linkage. Building static library.
-- Using cached C:/dev/projects/vcpkg/downloads/grpc-grpc-v1.23.1.tar.gz
-- Using source at C:/dev/projects/vcpkg/buildtrees/grpc/src/v1.23.1-ebfd5c51df
-- Configuring x86-windows
-- Building x86-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: C:/dev/projects/vcpkg/downloads/tools/cmake-3.14.0-windows/cmake-3.14.0-win32-x86/bin/cmake.exe --build . --config Debug --target install -- -v
    Working Directory: C:/dev/projects/vcpkg/buildtrees/grpc/x86-windows-dbg
    See logs for more information:
      C:\dev\projects\vcpkg\buildtrees\grpc\install-x86-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:91 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/grpc/portfile.cmake:77 (vcpkg_install_cmake)
  scripts/ports.cmake:94 (include)

Error: Building package grpc:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: grpc:x86-windows
  Vcpkg version: 2019.09.12-nohash

Additionally, attach any relevant sections from the log files above.

**Comment by AlvinZhangH** [comment]
Hi, @khalprin Thanks for reporting this issue.
I can not reproduce this issue in my machine.
could provide us failure logs?

**Comment by khalprin** [comment]
[install-x86-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/3979103/install-x86-windows-dbg-out.log)

**Comment by jozefizso** [comment]
Errors are similar to the ones in the #9282

**Comment by khalprin** [comment]
I tried removing openssl from the packages folder, the download folder and the buildtrees folder. Attempting to build gRPC still failed. I then completely removed vcpkg and all of its subfolders and started from scratch again. It resulted in the same error.

I'm using Visual Studio 2017 version 15.9.18

Here is the console output:

Starting package 6/6: grpc:x86-windows
Building package grpc[core]:x86-windows...
-- Note: grpc only supports static library linkage. Building static library.
-- Downloading https://github.com/grpc/grpc/archive/v1.23.1.tar.gz...
-- Extracting source C:/dev/projects/vcpkg/downloads/grpc-grpc-v1.23.1.tar.gz
-- Applying patch 00001-fix-uwp.patch
-- Applying patch 00002-static-linking-in-linux.patch
-- Applying patch 00003-undef-base64-macro.patch
-- Applying patch 00004-link-gdi32-on-windows.patch
-- Applying patch 00005-fix-uwp-error.patch
-- Applying patch 00006-crypt32.patch
-- Applying patch 00007-disable_grpcpp_channelz.patch
-- Applying patch 00008-fix-duplicate-gettid.patch
-- Using source at C:/dev/projects/vcpkg/buildtrees/grpc/src/v1.23.1-ebfd5c51df
-- Configuring x86-windows
-- Building x86-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: C:/dev/projects/vcpkg/downloads/tools/cmake-3.14.0-windows/cmake-3.14.0-win32-x86/bin/cmake.exe --build . --config Debug --target install -- -v
    Working Directory: C:/dev/projects/vcpkg/buildtrees/grpc/x86-windows-dbg
    See logs for more information:
      C:\dev\projects\vcpkg\buildtrees\grpc\install-x86-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:91 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/grpc/portfile.cmake:77 (vcpkg_install_cmake)
  scripts/ports.cmake:94 (include)


Error: Building package grpc:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: grpc:x86-windows
  Vcpkg version: 2019.09.12-nohash

Additionally, attach any relevant sections from the log files above.





I've included logs.
[config-x86-windows-out.log](https://github.com/microsoft/vcpkg/files/3980554/config-x86-windows-out.log)
[install-x86-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/3980556/install-x86-windows-dbg-out.log)
[x86-windows.vcpkg_abi_info.txt](https://github.com/microsoft/vcpkg/files/3980557/x86-windows.vcpkg_abi_info.txt)

**Comment by jozefizso** [comment]
```
-- Found OpenSSL: optimized;C:/dev/projects/vcpkg/installed/x86-windows/debug/lib/libeay32.lib;debug;C:/OpenSSL_1.1.0f-Win32/lib/VC/libcrypto32MDd.lib (found version "1.0.2s")  

-- Found OpenSSL: optimized;C:/dev/projects/vcpkg/installed/x86-windows/lib/libeay32.lib;debug;C:/OpenSSL_1.1.0f-Win32/lib/VC/libcrypto32MDd.lib (found version "1.0.2s")  
```

It looks like there's a different OpenSSL version installed and the build tries to link against different release of OpenSSL.

**Comment by khalprin** [comment]
Ah...that's it. I had a different version of openssl on my drive. I had forgotten about that. It seems a bit strange that the build wouldn't have used the download/package path of openssl that vcpkg had created...

Thanks for finding that.
