### ISSUE TITLE
How do I get boost library that runs both mac and windows

### ISSUE THREAD

**Issue by petrasvestartas** [microsoft/vcpkg#9358]
Hi,

I would like to ask if a windows developer can compile a visual studio project, whose code is strongly based on boost and must run on windows and mac.

I only have a windows computer, and would like to run minkowski example https://www.boost.org/doc/libs/1_65_1/boost/polygon/detail/minkowski.hpp from boost on both platforms. I never had mac or ran mac operating system.

**Comment by JackBoosY** [comment]
Using WSL to build linux projects with Visual Studio is a good choice, but you have to use cmake project instead of msvc project.

**Comment by JackBoosY** [comment]
Does this issue still bother you?

**Comment by JackBoosY** [comment]
Please reopen this issue if it still bothers you.

thanks.
