### ISSUE TITLE
PCL installed, but visual studio cannot find the dependecies

### ISSUE THREAD

**Issue by petrasvestartas** [microsoft/vcpkg#9359]
Hi,

I installed PCL library typing
.\vcpkg install pcl:x64-windows
and then 
.\vcpkg integrate install

There were no errors.

But when I try to open Visual Studio project and copy paste this example file:
http://pointclouds.org/documentation/tutorials/random_sample_consensus.php#random-sample-consensus

Dependencies not found:

![Untitled](https://user-images.githubusercontent.com/18013985/71073462-1bde2180-2189-11ea-9752-4daee7594cc4.png)

I have visual studio 2015/2017/2019 version on my windows pc and all of them cannot find the libraries.

Is there any specific way to point visual studio project to the specific libraries?

**Comment by AlvinZhangH** [comment]
Hi, @petrasvestartas Thanks for reporting this issue.
Please set Solution Platform to x64, because you installed pcl:x64-windows.

**Comment by petrasvestartas** [comment]
When I choose 64bit version instead of 32bit it seems that the visual studio compiler find the dependencies but if I just copy these includes I get error:

![Errors](https://user-images.githubusercontent.com/18013985/71074711-6f516f00-218b-11ea-9ba0-b2c0c924b13a.png)

**Comment by AlvinZhangH** [comment]
Function _open should use _sopen_s instead. Error E2S24 should check file vtkSetGet.h line 927 929.

**Comment by petrasvestartas** [comment]
Thank you for the reply. I changed to _sopen_s , but new errors accumulated.
![qq](https://user-images.githubusercontent.com/18013985/71075925-8d1fd380-218d-11ea-8c63-f8d1ff356d56.png)

For the E2S24
![he](https://user-images.githubusercontent.com/18013985/71075948-9ad55900-218d-11ea-84fd-dad162a7ff19.png)


Is there any dummy PCL tutorials that I could follow and they would be up-to-date?

**Comment by AlvinZhangH** [comment]
Please install pcl:x86-windows, set Solution Platform to x86.

**Comment by petrasvestartas** [comment]
I will need to run pcl on 64 bit platform software, I really cannot change to x86.

**Comment by JackBoosY** [comment]
No need to change `_open` to `_sopen_s`.
Please add macro `_CRT_SECURE_NO_WARNINGS` to _Project Property - C/C++ - Preprocessor_ and try again.

![image](https://user-images.githubusercontent.com/47264268/71077819-21585d80-21c3-11ea-9b34-8e0c69c88778.png)

Thanks.

**Comment by petrasvestartas** [comment]
Thank you this works.

What about the E2S24 error?

**Comment by JackBoosY** [comment]
After adding _CRT_SECURE_NO_WARNINGS, the E2524 error should disappear.
Please provide the full log.

Thanks.

**Comment by petrasvestartas** [comment]
The first two errors disappear but not E2524,  do you have a suggestion to solve this:

![Ques](https://user-images.githubusercontent.com/18013985/71086418-92d3e400-21a2-11ea-9c52-278d5a783e70.png)

**Comment by JackBoosY** [comment]
Seems like some macro are not defined, I don't know about it.

**Comment by petrasvestartas** [comment]
If it does not work with simple console app, can anyone explain me how to build any sample pcl project using cmake and vcpkg? I am struggling to run any example for month... help.

**Comment by JackBoosY** [comment]
Using [sample code](http://pointclouds.org/documentation/tutorials/planar_segmentation.php) build result:
```
1>------ Build started: Project: ConsoleApplication5, Configuration: Debug x64 ------
1>ConsoleApplication5.cpp
1>The use of BOOST_*_ENDIAN and BOOST_BYTE_ORDER is deprecated. Please include <boost/predef/other/endian.h> and use BOOST_ENDIAN_*_BYTE instead
1>f:\vcpkg\installed\x64-windows\include\pcl\io\low_level_io.h(73): warning C4996: '_open': This function or variable may be unsafe. Consider using _sopen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>c:\program files (x86)\windows kits\10\include\10.0.17763.0\ucrt\corecrt_io.h(390): note: see declaration of '_open'
1>f:\vcpkg\installed\x64-windows\include\pcl\io\low_level_io.h(78): warning C4996: '_open': This function or variable may be unsafe. Consider using _sopen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>c:\program files (x86)\windows kits\10\include\10.0.17763.0\ucrt\corecrt_io.h(390): note: see declaration of '_open'
1>ConsoleApplication5.vcxproj -> C:\Users\vzay\source\repos\ConsoleApplication5\x64\Debug\ConsoleApplication5.exe
1>Done building project "ConsoleApplication5.vcxproj".
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
```

**Comment by petrasvestartas** [comment]
Build succeeded. I did the same.

Does this work only on Visual Studio 2017, but not on 2015 and 2019?

**Comment by JackBoosY** [comment]
This should also work on Visual Studio 2019. I guess this is a bug in Visual Studio, but it has been fixed in Visual Studio 2017.

You can run executable on other computers.
