### ISSUE TITLE
How do I make my port Windows only?

### ISSUE THREAD

**Issue by fsmikedev** [microsoft/vcpkg#9362]
Is there a nicer way to do this?, I've tried using VCPKG_TARGET_IS_WINDOWS but it causes issues as the install is empty: 

`The folder /include is empty or not present. This indicates the library was not correctly installed.`

Thanks.

**Comment by AlvinZhangH** [comment]
@fsmikedev, could provide us more information, eg, port name and failure logs?

**Comment by Neumann-A** [comment]
You probably want this:
```
## vcpkg_fail_port_install([MESSAGE <message>] 	[ON_TARGET <target1> [<target2> ...]]
##											  	[ON_ARCH <arch1> [<arch2> ...]] 
##											  	[ON_CRT_LINKAGE <link1> [<link2> ...]])
##											  	[ON_LIBRARY_LINKAGE <linklib1> [<linklib2> ...]])
```

**Comment by NancyLi1013** [comment]
Hi @fsmikedev thanks for posting this issue.
Is this issue solved now? If not, please make a clear description about your issue or what you need from us?

**Comment by NancyLi1013** [comment]
Please feel free to reopen it if this is still  a problem for you.
