### ISSUE TITLE
Cannot install QT

### ISSUE THREAD

**Issue by itodirel** [microsoft/vcpkg#9364]
**Describe the bug**
Installing QT with vcpkg errors out with "Unable to locate 'afxres.h'.  Ensure you have installed the ATL/MFC". ATL and MFC are installed, for x86/x64 platforms and all toolsets. 

**Environment**
- OS: Windows
- Compiler: 19.24.28314

**To Reproduce**
1. ./vcpkg install QT

c:\vcpkg>.\vcpkg.exe install qt5
The following packages will be built and installed:
  * atlmfc[core]:x86-windows
    qt5[core]:x86-windows
  * qt5-speech[core]:x86-windows
  * qt5-virtualkeyboard[core]:x86-windows
  * qt5-websockets[core]:x86-windows
  * qt5-winextras[core]:x86-windows
  * qt5-xmlpatterns[core]:x86-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/7: atlmfc:x86-windows
Building package atlmfc[core]:x86-windows...
CMake Error at ports/atlmfc/portfile.cmake:7 (message):
  Unable to locate 'afxres.h'.  Ensure you have installed the ATL/MFC
  component of Visual Studio.
Call Stack (most recent call first):
  scripts/ports.cmake:94 (include)

**Failure logs** 
I don't know where to get these from, there are no logs under buildtrees\atlmfc

**Comment by JackBoosY** [comment]
Duplicate with #9346.
