### ISSUE TITLE
qt5 build error windows 10 - 1903

### ISSUE THREAD

**Issue by plettplett** [microsoft/vcpkg#9365]
- Downloading http://download.qt.io/official_releases/qt/5.12/5.12.5/submodules/qtimageformats-everywhere-src-5.12.5.tar.xz...
-- Extracting source C:/Users/chris/vcpkg/downloads/qtimageformats-everywhere-src-5.12.5.tar.xz
-- Using source at C:/Users/chris/vcpkg/buildtrees/qt5-imageformats/src/5.12.5-7ddf5dd29e
-- Downloading https://www.python.org/ftp/python/2.7.16/python-2.7.16.msi...
-- Downloading https://www.python.org/ftp/python/2.7.16/python-2.7.16.msi... Failed. Status: 6;"Couldn't resolve host name"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:175 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_find_acquire_program.cmake:298 (vcpkg_download_distfile)
  installed/x86-windows/share/qt5/qt_build_submodule.cmake:6 (vcpkg_find_acquire_program)
  installed/x86-windows/share/qt5/qt_submodule_installation.cmake:8 (qt_build_submodule)
  ports/qt5-imageformats/portfile.cmake:28 (qt_submodule_installation)
  scripts/ports.cmake:94 (include)

Error: Building package qt5-imageformats:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: qt5-imageformats:x86-windows
  Vcpkg version: 2019.09.12-nohash

Additionally, attach any relevant sections from the log files above.

C:\Users\chris\vcpkg>

**Comment by JackBoosY** [comment]
Hi @plettplett, thanks for reporting this issue!
You can download https://www.python.org/ftp/python/2.7.16/python-2.7.16.msi  manually and put it into _VCPKG_PATH/downloads_ then rebuild qt5.

Thanks.

**Comment by JackBoosY** [comment]
Does this issue still bother you?

**Comment by plettplett** [comment]
No, QT5 now builds

Thanks. It required Python 2.7...
