### ISSUE TITLE
[czmq] build failure

### ISSUE THREAD

**Issue by winsoft666** [microsoft/vcpkg#9366]
**Host Environment**
- OS: [Windows 10]
- Compiler: 2019.09.12-nohash

**To Reproduce**
`vcpkg install czmq[tool,draft,curl,lz4,httpd,uuid]:x86-windows-static`

**Failure logs** 
-- Building x86-windows-static-dbg
see attachment
[install-x86-windows-static-dbg-out.log](https://github.com/microsoft/vcpkg/files/3982115/install-x86-windows-static-dbg-out.log)

**Comment by JackBoosY** [comment]
Needs to link with `Wldap32.lib` in Windows.

**Comment by PhoebeHui** [comment]
@winsoft666, I can't repro this issue. Could you double check if  "C:\Program Files (x86)\Windows Kits\10\Lib\xxxx\um\x86\Wldap32.Lib" exist in your machine?

**Comment by winsoft666** [comment]
yes, my pc has some Wldap32.lib

[cid:A2727D3D-3BFC-4B93-8116-2944E789519A]

江雪桥

在 2019年12月30日，15:36，Phoebe <notifications@github.com> 写道：

﻿

@winsoft666<https://github.com/winsoft666>, I can't repro this issue. Could you double check if "C:\Program Files (x86)\Windows Kits\10\Lib\xxxx\um\x86\Wldap32.Lib" exist in your machine?

**Comment by winsoft666** [comment]
![1](https://user-images.githubusercontent.com/46803815/71860317-5d7d3f00-312d-11ea-9d37-43e8688e0dfb.jpg)
several Wldap32.Lib in my machine(Win10 x64).

**Comment by Cheney-W** [comment]
Still can't reproduce this issue in the latest vcpkg, if this issue is still occur, could you please run `.\vcpkg install czmq[tool,draft,curl,lz4,httpd,uuid]:x86-windows-static --debug` and sent the output of PowerShell and the failure log to me? Thank you!

**Comment by Cheney-W** [comment]
Please feel free to reopen this issue if you still encounter it. Thank you!
