### ISSUE TITLE
[boost-build:x64-windows] build failure

### ISSUE THREAD

**Issue by bxac** [microsoft/vcpkg#9368]
**Host Environment**
- OS: Microsoft Windows [Version 10.0.18362.535]
- Compiler: VS2019 16.4.2

**To Reproduce**
`vcpkg install boost:x64-windows`

**Failure logs** 
Installing package boost-numeric-conversion[core]:x64-windows... done
Elapsed time for package boost-numeric-conversion:x64-windows: 2.471 s
Starting package 19/148: boost-build:x64-windows
Building package boost-build[core]:x64-windows...
-- Downloading https://github.com/boostorg/build/archive/boost-1.70.0.tar.gz...
-- Extracting source C:/vcpkg/downloads/boostorg-build-boost-1.70.0.tar.gz
-- Applying patch arm64msvc.patch
-- Using source at C:/vcpkg/buildtrees/boost-build/src/ost-1.70.0-ad28c1be18
-- Using cached C:/vcpkg/downloads/boost_LICENSE_1_0.txt
-- Downloading https://raw.githubusercontent.com/boostorg/boost/boost-1.70.0/boostcpp.jam...
-- Installing: C:/vcpkg/packages/boost-build_x64-windows/share/boost-build/copyright
-- Installing: C:/vcpkg/packages/boost-build_x64-windows/tools/boost-build/boostcpp.jam
-- Bootstrapping...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: C:/vcpkg/packages/boost-build_x64-windows/tools/boost-build/bootstrap.bat msvc
    Working Directory: C:/vcpkg/packages/boost-build_x64-windows/tools/boost-build
    Error code: 9009
    See logs for more information:
      C:\vcpkg\buildtrees\boost-build\bootstrap-x64-windows-out.log
      C:\vcpkg\buildtrees\boost-build\bootstrap-x64-windows-err.log

Call Stack (most recent call first):
  ports/boost-build/portfile.cmake:58 (vcpkg_execute_required_process)
  scripts/ports.cmake:94 (include)

Error: Building package boost-build:x64-windows failed with: BUILD_FAILED

bootstrap-x64-windows-out.log :
Bootstrapping the build engine

Failed to bootstrap the build engine
Please consult bootstrap.log for further diagnostics.

bootstrap-x64-windows-err.log:
'cl' is not recognized as an internal or external command,
operable program or batch file.

**Comment by JackBoosY** [comment]
Hi @bxac, thanks for reporting this issue!
Could you provide these logs?
_C:\vcpkg\buildtrees\boost-build\bootstrap-x64-windows-out.log_
_C:\vcpkg\buildtrees\boost-build\bootstrap-x64-windows-err.log_

Thanks.

**Comment by bxac** [comment]
> Could you provide these logs?
> _C:\vcpkg\buildtrees\boost-build\bootstrap-x64-windows-out.log_
> _C:\vcpkg\buildtrees\boost-build\bootstrap-x64-windows-err.log_

These logs are cited above in the original issue description.

**bootstrap-x64-windows-out.log** :
```
Bootstrapping the build engine

Failed to bootstrap the build engine
Please consult bootstrap.log for further diagnostics.

```
**bootstrap-x64-windows-err.log**:
```
'cl' is not recognized as an internal or external command,
operable program or batch file.
```
**bootstrap.log**:
```
###
### Using 'msvc' toolset.
###

C:\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine>if exist bootstrap rd /S /Q bootstrap 

C:\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine>md bootstrap 

C:\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine>cl /nologo /GZ /Zi /MLd /Fobootstrap/ /Fdbootstrap/ -DNT -DYYDEBUG kernel32.lib advapi32.lib user32.lib /Febootstrap\jam0  command.c compile.c constants.c debug.c execcmd.c execnt.c filent.c frames.c function.c glob.c hash.c hdrmacro.c headers.c jam.c jambase.c jamgram.c lists.c make.c make1.c object.c option.c output.c parse.c pathnt.c pathsys.c regexp.c rules.c scan.c search.c subst.c timestamp.c variable.c modules.c strings.c filesys.c builtins.c md5.c class.c cwd.c w32_getreg.c native.c modules/set.c modules/path.c modules/regex.c modules/property-set.c modules/sequence.c modules/order.c 

C:\vcpkg\packages\boost-build_x64-windows\tools\boost-build\src\engine>exit /b 9009 

```

(But cl.exe is installed with VisualStudio).

**Comment by PhoebeHui** [comment]
@bxac, could you get vcpkg latest source and try again? please let me know if it still be a problem for you.

**Comment by bxac** [comment]
> @bxac, could you get vcpkg latest source and try again? please let me know if it still be a problem for you.

Now it start compilation successfully, but fails in the middle:

```
[...]
Building package boost-format[core]:x64-windows... done
Installing package boost-format[core]:x64-windows...
Installing package boost-format[core]:x64-windows... done
Elapsed time for package boost-format:x64-windows: 1.798 s
Starting package 66/127: boost-serialization:x64-windows
Building package boost-serialization[core]:x64-windows...
-- Downloading https://github.com/boostorg/serialization/archive/boost-1.72.0.tar.gz...
-- Extracting source C:/vcpkg/downloads/boostorg-serialization-boost-1.72.0.tar.gz
-- Using source at C:/vcpkg/buildtrees/boost-serialization/src/ost-1.72.0-631e528f25
-- Building x64-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: C:/vcpkg/installed/x64-windows/tools/boost-build/b2.exe --stagedir=C:/vcpkg/buildtrees/boost-serialization/x64-windows-rel/stage -
-build-dir=C:/vcpkg/buildtrees/boost-serialization/x64-windows-rel --user-config=C:/vcpkg/buildtrees/boost-serialization/x64-windows-rel/user-config.j
am -j8 --debug-configuration --debug-building --debug-generators --disable-icu --ignore-site-config --hash -q -sZLIB_INCLUDE=C:/vcpkg/installed/x64-wi
ndows/include -sBZIP2_INCLUDE=C:/vcpkg/installed/x64-windows/include -sLZMA_INCLUDE=C:/vcpkg/installed/x64-windows/include -sZSTD_INCLUDE=C:/vcpkg/ins
talled/x64-windows/include threading=multi threadapi=win32 runtime-link=shared link=shared address-model=64 architecture=x86 toolset=msvc -sZLIB_BINAR
Y=zlib -sZLIB_LIBPATH=C:/vcpkg/installed/x64-windows/lib -sBZIP2_BINARY=bz2 -sBZIP2_LIBPATH=C:/vcpkg/installed/x64-windows/lib -sLZMA_BINARY=lzma -sLZ
MA_LIBPATH=C:/vcpkg/installed/x64-windows/lib -sZSTD_BINARY=zstd -sZSTD_LIBPATH=C:/vcpkg/installed/x64-windows/lib variant=release debug-symbols=on
    Working Directory: C:/vcpkg/buildtrees/boost-serialization/src/ost-1.72.0-631e528f25/build
    Error code: 1
    See logs for more information:
      C:\vcpkg\buildtrees\boost-serialization\build-x64-windows-rel-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/boost-build/boost-modular-build.cmake:286 (vcpkg_execute_required_process)
  ports/boost-serialization/portfile.cmake:14 (boost_modular_build)
  scripts/ports.cmake:90 (include)

Error: Building package boost-serialization:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-serialization:x64-windows
  Vcpkg version: 2020.02.04-nohash
```

**Comment by bxac** [comment]
[build-x64-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/4225203/build-x64-windows-rel-out.log)

    See logs for more information:
      C:\vcpkg\buildtrees\boost-serialization\build-x64-windows-rel-out.log

**Comment by PhoebeHui** [comment]
@bxac, I can't repro this issue, boost-serialization build successfully for me.

From your log, it failed with 'fatal error C1083: Cannot open include file: 'boost/core/nvp.hpp': No such file or directory', could you remove boost-core:x64-windows, and rebuild it, you can check if nvp.hpp located to C:\vcpkg\installed\x64-windows\include\boost\core?

**Comment by bxac** [comment]
> could you remove boost-core:x64-windows, and rebuild it

Yes, now it rebuilds successfully, thank you!
