### ISSUE TITLE
[UVAtlas] please update uvatlas to the latest dec2019 release

### ISSUE THREAD

**Issue by jasjuang** [microsoft/vcpkg#9370]
[UVAtlas](https://github.com/microsoft/UVAtlas) now provides some basic CMake support, but it still lacks features like `install` and `export` in it, but there are other various improvements. Can someone please update it to the latest dec2019 release? The author of the repo is quite responsive, so if there's a need to submit PR upstream in order for it works with vcpkg seamlessly please do so.

ping @sdcb

**Comment by AlvinZhangH** [comment]
@jasjuang, the PR has been merged, please get latest source and try again.
