### ISSUE TITLE
find_package CMAKE failed

### ISSUE THREAD

**Issue by buridan1999** [microsoft/vcpkg#9371]
**Describe the bug**
I try to add cpprestsdk to my project. When it tried to build cpprestsdk it can't find Zlib library, that is already installed by vcpkg.

**Environment**
- OS: [Windows]

**To Reproduce**
1. ./vcpkg install zlib
2. try to build the project from CMake file with `find_package(ZLIB REQUIRED)` 

**Expected behavior**
It must find the package and build continue build project

**Failure logs** 
[Pastebin](https://pastebin.com/Nwh99H8W)
`
CMAKE_FIND_LIBRARY_SUFFIXES
CMake Error at C:/Program Files/CMake/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find ZLIB (missing: ZLIB_LIBRARY) (found version "1.2.3")
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/CMake/share/cmake-3.16/Modules/FindZLIB.cmake:115 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:20 (find_package)
`

**Comment by JackBoosY** [comment]
`C:/Program Files/CMake/share/cmake-3.16`

The version of cmake you installed is too low, please update cmake or uninstall it to use cmake installed by vcpkg.

Thanks.

**Comment by JackBoosY** [comment]
See #6883.

**Comment by buridan1999** [comment]
> See #6883.

Sorry, but I don't understand what you want to say... I read the topic, but how does it relevant to my question.
P.S. If I add to cmake cmd these parameters it will build project. But why it doesn't find ZLIB automatically, I installed ZLIB packet.

-DZLIB_INCLUDE_DIR='F:/Sources/library_zlib/zlib
-DZLIB_LIB_DIR=F:/Sources/library_zlib/zlib
-DZLIB_LIBRARY=F:/Sources/library_zlib/bin/x86/libs

**Comment by JackBoosY** [comment]
As the cmake team keeps updating `findzlib.cmake`, the zlib built in vcpkg may not be found. We need to update the cmake version and zlib in vcpkg to solve this issue.

**Comment by JackBoosY** [comment]
Hi @buridan1999, does this issue still bother you?

**Comment by JackBoosY** [comment]
We haven't been able to repro this; if more information comes up, or this issue appears again, please reopen.
