### ISSUE TITLE
[New Port Request] <BehaviorTree.CPP>

### ISSUE THREAD

**Issue by ThrashAbaddon** [microsoft/vcpkg#9374]
- Library name: `BehaviorTree.CPP`

- Library description:
This C++ library provides a framework to create BehaviorTrees. It was designed to be flexible, easy to use, reactive and fast.
Even if our main use-case is robotics, you can use this library to build AI for games, or to replace Finite State Machines in you application.

- Source repository URL: https://github.com/BehaviorTree/BehaviorTree.CPP

- Project homepage (if different from the source repository): https://www.behaviortree.dev/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by NancyLi1013** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
