### ISSUE TITLE
field3d build failure

### ISSUE THREAD

**Issue by plettplett** [microsoft/vcpkg#9375]
**Host Environment**
windows 10, 1903
- Compiler: revision, Visual Studio 2019 Community

C:\Users\chris\vcpkg>.\vcpkg install field3d
The following packages will be built and installed:
    field3d[core]:x86-windows
  * hdf5[core]:x86-windows
  * szip[core]:x86-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/3: szip:x86-windows
Building package szip[core]:x86-windows...
-- Downloading https://support.hdfgroup.org/ftp/lib-external/szip/2.1.1/src/szip-2.1.1.tar.gz...
-- Extracting source C:/Users/chris/vcpkg/downloads/szip-2.1.1.tar.gz
-- Applying patch fix-szip-config-to-set-szip-found.patch
-- Using source at C:/Users/chris/vcpkg/buildtrees/szip/src/szip-2.1.1-6b767acfa7
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Performing post-build validation
-- Performing post-build validation done
Building package szip[core]:x86-windows... done
Installing package szip[core]:x86-windows...
Installing package szip[core]:x86-windows... done
Elapsed time for package szip:x86-windows: 16.29 s
Starting package 2/3: hdf5:x86-windows
Building package hdf5[core]:x86-windows...
-- Downloading https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.10/hdf5-1.10.5/src/CMake-hdf5-1.10.5.tar.gz...
-- Extracting source C:/Users/chris/vcpkg/downloads/CMake-hdf5-1.10.5.tar.gz
-- Applying patch hdf5_config.patch
-- Using source at C:/Users/chris/vcpkg/buildtrees/hdf5/src/hdf5-c7a3a597c4
-- Configuring x86-windows-dbg
-- Configuring x86-windows-rel
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Performing post-build validation
-- Performing post-build validation done
Building package hdf5[core]:x86-windows... done
Installing package hdf5[core]:x86-windows...
Installing package hdf5[core]:x86-windows... done
Elapsed time for package hdf5:x86-windows: 2.671 min
Starting package 3/3: field3d:x86-windows
Building package field3d[core]:x86-windows...
CMake Error at ports/field3d/portfile.cmake:4 (message):
  Windows is currently not supported.
Call Stack (most recent call first):
  scripts/ports.cmake:94 (include)

Error: Building package field3d:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: field3d:x86-windows
  Vcpkg version: 2019.09.12-nohash

Additionally, attach any relevant sections from the log files above.

**Comment by AlvinZhangH** [comment]
Hi @plettplett, field3d does not support Windows currently,

**Comment by JackBoosY** [comment]
Fixed.
