### ISSUE TITLE
Which files need to be persisted when updating vcpkg?

### ISSUE THREAD

**Issue by Bennett-Yang** [microsoft/vcpkg#9385]
I got a really simple question. I am trying to add vcpkg to a bucket of scoop (a command-line installer for Windows like homebrew for MacOS), which needs me to find out which files are persistent data. I think "installed" and "downloads" should be persisted but I am not sure.

**Comment by AlvinZhangH** [comment]
Hi, @Bennett-Yang Thanks for reporting this issue.
The new vcpkg folder not include downloads and installed, after install a port, the two folder appeared.

**Comment by Bennett-Yang** [comment]
> Hi, @Bennett-Yang Thanks for reporting this issue.
> The new vcpkg folder not include downloads and installed, after install a port, the two folder appeared.

Got it. Really appreciate your reply.
