### ISSUE TITLE
sqlite3 tool is incorrectly named "sqlite3-bin.exe"

### ISSUE THREAD

**Issue by tibogens** [microsoft/vcpkg#9387]
**Describe the bug**
sqlite3 tool is incorrectly named "sqlite3-bin.exe". Should be "sqlite3.exe", as expected by users and 3rd party tools (e.g. django's manage.py dbshell command).

**Environment**
- OS: Windows 10 
- Compiler: VS 2019, VS2017

**To Reproduce**
1. .\vcpkg.exe --triplet x64-windows install sqlite3[tool]
2. dir .\installed\x64-windows\tools\
=> executable is named "sqlite3-bin.exe"

**Expected behavior**
Executable should be named "sqlite3.exe"

**Additional context**
Commit ba3f552b67a76bc62ef4aecdee778ac47abf330c added the ability to build "sqlite3.exe". Because both the DLL and the EXE have the same name, the CMake target names are different: target "sqlite3" is the DLL, and target "sqlite3-bin" is the EXE. The original author correctly specified an alternative output name to make sure the tool is named "sqlite3.exe".

Commit e1870a91ff26c099ca92599fa7d7bb06b81fbc58 removed the output name change, claiming to fix a bug on the specific arm/uwp plaftorm. I can't judge if this actually fixed anything, but I am certain it broke the name of the exe, which becomes that of the CMake target - sqlite3-bin.exe.

I can't really attach a PR here, because I'm uncertain how the "fix" on arm/uwp works, and I don't have such a platform to test.

On other platforms at least, the original set_target_properties() should be re-introduced and slightly tweaked to avoid a warning:
`set_target_properties(sqlite3-bin PROPERTIES OUTPUT_NAME sqlite3 PDB_NAME sqlite3-bin.pdb)`

**Comment by JackBoosY** [comment]
The reason why the tool `sqlite3` was renamed `sqlite3-bin` is that its name conflicts with the name of the library, which causes errors in some cmake files generated during the build. I think we should change its name back in `portfile.cmake`.

**Comment by NancyLi1013** [comment]
This issue has been fixed now. Please update vcpkg and try to use it.

**Comment by tibogens** [comment]
Works nicely, thanks! Tested x86-windows and x64-windows.
