### ISSUE TITLE
[PCL] installation fails (Ubuntu 16.4)

### ISSUE THREAD

**Issue by Alijafr** [microsoft/vcpkg#9391]
Hello, 
I am trying to set up visual studio code with pcl using vcpkg. The installation give me error when building the pcl package. The error is: 
```
-- Using source at /home/labuser/vcpkg/buildtrees/pcl/src/pcl-1.9.1-3d424fa2ff
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: /home/labuser/vcpkg/downloads/tools/cmake-3.14.0-linux/cmake-3.14.0-Linux-x86_64/bin/cmake --build . --config Debug --target install -- -v
    Working Directory: /home/labuser/vcpkg/buildtrees/pcl/x64-linux-dbg
    See logs for more information:
      /home/labuser/vcpkg/buildtrees/pcl/install-x64-linux-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:91 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/pcl/portfile.cmake:54 (vcpkg_install_cmake)
  scripts/ports.cmake:94 (include)
```
--------------------------------------------
I used:
  Package: pcl:x64-linux
  Vcpkg version: 2019.09.12-unknownhash

Any help is appreciated. Thanks

**Comment by AlvinZhangH** [comment]
Hi, @Alijafr  Thanks for reporting this issue.
I can not reproduce this issue in my machine.
could provide us failure logs?

**Comment by Alijafr** [comment]
Thank for the reply. I think this is the log file you need. 

[install-x64-linux-dbg-out.log](https://github.com/microsoft/vcpkg/files/3994060/install-x64-linux-dbg-out.log)

Thank you

**Comment by JackBoosY** [comment]
```
/usr/include/c++/5/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support \
  ^
In file included from /home/labuser/vcpkg/installed/x64-linux/include/boost/detail/endian.hpp:9:0,
```
@Alijafr Could you provide your gcc version?
Thanks.

**Comment by Alijafr** [comment]
Thank you for your response. 
It is 9.2.1

Thank you

**Comment by AlvinZhangH** [comment]
g++ -v 
gcc version 7.4.0 
7.4.0 is latest version. Why your version is 9.2.1?

**Comment by Alijafr** [comment]
sorry, 
i did:  gcc -v
and i got 9.2.1
when i write: g++ -v 
The gcc vesrion is 5.5.0
Is this the problem ? 

Thank you for your help

**Comment by AlvinZhangH** [comment]
your should update g++ version from 5.5.0 to 7.4.0

**Comment by JackBoosY** [comment]
Could you add `add_compile_options(-std=c++11)` to _VCPKG_PATH/buildtrees/pcl/src/pcl***/CMakeLists.txt_ line 26 and try again?

Thanks.

**Comment by JackBoosY** [comment]
If this issue is still not resolved, please reopen it.
