### ISSUE TITLE
 bootstrap-vcpkg.bat can't find VISUAL STUDIO and SDK

### ISSUE THREAD

**Issue by embeddedRSA** [microsoft/vcpkg#9392]
**Issue**
When executing the bootloader, Visual studio 2019 (Community) is not found.

**Visual Studio 2019 setup**
I've installed the following packages

![billede](https://user-images.githubusercontent.com/55278801/71247466-24656200-2319-11ea-946d-6c9034d05fb6.png)

![billede](https://user-images.githubusercontent.com/55278801/71247554-48c13e80-2319-11ea-989f-b7b561afe683.png)

![billede](https://user-images.githubusercontent.com/55278801/71247572-51197980-2319-11ea-87b6-1dff0a14f49d.png)

**Setup and execution went as following:**

$ git clone https://github.com/NordicPlayground/vcpkg/
$ cd vcpkg
$ git checkout fix/temporary-fix-spdlog-until-vcpkg-release # Temporary workaround for spdlog issue
$ .\bootstrap-vcpkg.bat
 
Im using the given repository and branch because im following this tutorial: https://github.com/NordicSemiconductor/pc-ble-driver#Installing-dependencies 

**error:**
%vcpkg_PATH%\scripts\bootstrap.ps1 : Building vcpkg.exe failed. Please ensure you have installed Visual Studio with the Desktop C++ workload and the Windows SDK for Desktop C++.
At line:1 char:4

**what works**
I've tried running the master branch from https://github.com/microsoft/vcpkg, and ncpkg is installable. I however get an issue later on related to 'spdlog' , which i believe is fixed in the branch i'm having trouble installing. 

Point is that VisualStudio 19 is detected and doesn't course trouble, but i on the other hand don't gain the features i'm looking for. 

**possible fix?**
My question is how to fix this issue, perhaps there's a way to manually locate the visualstudio installation? if not then something else might help?

**Comment by JackBoosY** [comment]
@embeddedRSA Could you update vcpkg and try again?

Thanks.

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
