### ISSUE TITLE
SDL2pp release linked with SDL2 debug

### ISSUE THREAD

**Issue by longnguyen2004** [microsoft/vcpkg#9393]
PEStudio output of SDL2pp.dll release:
![image](https://user-images.githubusercontent.com/15729831/71260344-3c66d100-236d-11ea-8b58-7c6bfa728f31.png)

This bug seems to be related to #6152 as well

**Comment by JackBoosY** [comment]
Confirmed.

**Comment by JackBoosY** [comment]
Hi @longnguyen2004, thanks for reporting this issue!
I've fixed it, please update vcpkg and rebuild sdl2pp.

Thanks.
