### ISSUE TITLE
glibmm:x64-linux build failure

### ISSUE THREAD

**Issue by jon-ryan** [microsoft/vcpkg#9395]
**Host Environment**
- OS: Linux

**To Reproduce**
`./vcpkg install gtkmm`
or
`./vcpkg install glibmm`

**Failure logs** 
The following packages will be built and installed:
    glibmm[core]:x64-linux
Starting package 1/1: glibmm:x64-linux
Building package glibmm[core]:x64-linux...
-- Using cached /var/cache/vcpkg/glibmm-2.52.1.tar.xz
-- Using source at /usr/share/vcpkg/buildtrees/glibmm/src/glibmm-2-4a92f34a92
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: /usr/bin/cmake --build . --config Debug --target install -- -v
    Working Directory: /usr/share/vcpkg/buildtrees/glibmm/x64-linux-dbg
    See logs for more information:
      /usr/share/vcpkg/buildtrees/glibmm/install-x64-linux-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:91 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/glibmm/portfile.cmake:33 (vcpkg_install_cmake)
  scripts/ports.cmake:94 (include)

Error: Building package glibmm:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: glibmm:x64-linux
  Vcpkg version: 2019.09.12-unknownhash

**Comment by AlvinZhangH** [comment]
Hi, @jon-ryan Thanks for reporting this issue.
I can not reproduce this issue in my machine.
could provide us failure logs?

**Comment by jon-ryan** [comment]
Hello @AlvinZhangH 
sorry for my late response. Where do I find the failure logs?

**Comment by AlvinZhangH** [comment]
@jon-ryan  /usr/share/vcpkg/buildtrees/glibmm/install-x64-linux-dbg-out.log

**Comment by jon-ryan** [comment]
Here you go: [https://pastebin.com/rsNLaaF7](https://pastebin.com/rsNLaaF7)

**Comment by JackBoosY** [comment]
Hi @jon-ryan, could you modify _/usr/share/vcpkg/buildtrees/glibmm/src/glibmm-2-4a92f34a92/glib/glibmm/threads.h_ line 660 from:
```
GPrivate* gobj() { return gobject_; }
```
to
```
GPrivate* gobj() { return &gobject_; }
```
And try again?

Thanks.

Related: https://bugzilla.redhat.com/show_bug.cgi?id=1540795

**Comment by jon-ryan** [comment]
@JackBoosY this seems to fix the issue with glibmm but another error occured:

`-- Building /usr/share/vcpkg/buildtrees/atkmm/src/atkmm-2-de808b48b0/MSVC_Net2013/atkmm.sln for Release
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: msbuild /usr/share/vcpkg/buildtrees/atkmm/src/atkmm-2-de808b48b0/MSVC_Net2013/atkmm.sln /p:Configuration=Release /t:atkmm /p:Platform=x64 /p:PlatformToolset=external /p:VCPkgLocalAppDataDisabled=true /p:UseIntelMKL=No /p:WindowsTargetPlatformVersion= /m /p:ForceImportBeforeCppTargets=/usr/share/vcpkg/scripts/buildsystems/msbuild/vcpkg.targets /p:VcpkgTriplet=x64-linux
    Working Directory: /usr/share/vcpkg/buildtrees/atkmm/x64-linux-rel
    Error code: No such file or directory
    See logs for more information:

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_msbuild.cmake:119 (vcpkg_execute_required_process)
  ports/atkmm/portfile.cmake:25 (vcpkg_build_msbuild)
  scripts/ports.cmake:94 (include)


Error: Building package atkmm:x64-linux failed with: BUILD_FAILED
`

Seems to be an issue with atk.

_/usr/share/vcpkg/buildtrees/**atkmm**/install-x64-linux-dbg-out.log_ doesn't exist, but _/usr/share/vcpkg/buildtrees/**atk**/install-x64-linux-dbg-out.log_ does. The output is here:
[https://pastebin.com/njFuHCup](https://pastebin.com/njFuHCup)

**Comment by JackBoosY** [comment]
Port `atkmm` only support windows now, please open a new issue to report this problem.

Thanks.

**Comment by NancyLi1013** [comment]
@jon-ryan this issue should be fixed now. Please update vcpkg and try to use it.
