### ISSUE TITLE
[sdl2 curl] build failure

### ISSUE THREAD

**Issue by nowix93** [microsoft/vcpkg#9398]
**Host Environment**
- OS: [Windows]
- Compiler: Visual studio 2015/2017/2019

**To Reproduce**

> > git clone https://github.com/Microsoft/vcpkg.git
> > cd vcpkg
>  .\bootstrap-vcpkg.bat
> .\vcpkg integrate install
> .\vcpkg install sdl2 curl

and i try build this [https://github.com/otland/forgottenserver.git](url)

**Failure logs** 
first 

> C1083	Cannot open include file: 'boost/asio.hpp': No such file or directory	theforgottenserver	c:\vcpkg\forgottenserver\src\otpch.h

when i add it manually i got the same error with pugixml
then when i add it 

> C1083 Cannot open include file: 'mysql/mysql.h': No such file or directory (compiling source file ..\src\actions.cpp)

there are 63 similar errors.
i try add it manually but i sitll got the same error

**Additional context**
I use this tutorial [https://github.com/otland/forgottenserver/wiki/Compiling-on-Windows-%28vcpkg%29](url).
On consol i have everythink good but when time come to use VS i get many errors.
Firstly i dont have libraries like asio and pugixml i rly dont know why because I read and watched many tutorials and everything was added automatically there.
But its not a problem i just add it manually and there is next problem
C1083 Cannot open include file: 'mysql/mysql.h': No such file or directory (compiling source file ..\src\actions.cpp)
But why its dont work atomatically :<
I been trying to do this for 5 days , i try with vs 2015/17/19 but effect still the same.
probabbly its something wrong with path but i dont know where and how fix it i look into Cmakesettings.json but there is good path to vcpkg :<

**Comment by AlvinZhangH** [comment]
Step should be:
git clone https://github.com/Microsoft/vcpkg.git
cd vcpkg
.\bootstrap-vcpkg.bat
.\vcpkg install sdl2 curl
.\vcpkg integrate install

.\vcpkg integrate install is last

**Comment by nowix93** [comment]
i reinstall windows and problem be solved. 
thanks

**Comment by AlvinZhangH** [comment]
Great!
