### ISSUE TITLE
[zlib:x64-osx] build failure

### ISSUE THREAD

**Issue by AMS21** [microsoft/vcpkg#9399]
**Host Environment**
- OS: macOS 10.13
- Compiler: XCode 10.1

**To Reproduce**
`./vcpkg install zlib`

**Failure logs** 
> Starting package 27/47: zlib:x64-osx
Building package zlib[core]:x64-osx...
-- Downloading http://www.zlib.net/zlib-1.2.11.tar.gz...
-- Extracting source /Users/travis/build/AMS21/OpenEast/deps/vcpkg/downloads/zlib1211.tar.gz
-- Applying patch cmake_dont_build_more_than_needed.patch
-- Using source at /Users/travis/build/AMS21/OpenEast/deps/vcpkg/buildtrees/zlib/src/1.2.11-f690224aeb
-- Configuring x64-osx-dbg
-- Configuring x64-osx-rel
-- Building x64-osx-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: /Users/travis/build/AMS21/OpenEast/deps/vcpkg/downloads/tools/cmake-3.14.0-osx/cmake-3.14.0-Darwin-x86_64/CMake.app/Contents/bin/cmake --build . --config Debug --target install -- -v
    Working Directory: /Users/travis/build/AMS21/OpenEast/deps/vcpkg/buildtrees/zlib/x64-osx-dbg
    See logs for more information:
      /Users/travis/build/AMS21/OpenEast/deps/vcpkg/buildtrees/zlib/install-x64-osx-dbg-out.log
      /Users/travis/build/AMS21/OpenEast/deps/vcpkg/buildtrees/zlib/install-x64-osx-dbg-err.log
Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:91 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/zlib/portfile.cmake:32 (vcpkg_install_cmake)
  scripts/ports.cmake:94 (include)
Error: Building package zlib:x64-osx failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: zlib:x64-osx
  Vcpkg version: 2019.09.12-unknownhash

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by JackBoosY** [comment]
Hi @AMS21, sorry for late.
Does this issue still exist? I can't repro it on my machine.

Thanks.

**Comment by JackBoosY** [comment]
We haven't been able to repro this; if more information comes up, or this issue appears again, please reopen.
