### ISSUE TITLE
Support for cpprestsdk on Linux

### ISSUE THREAD

**Issue by KellyDeveloped** [Microsoft/vcpkg#940]
After installing vcpkg, I installed cpprestskd in hopes to use it for Visual Studio 2017's linux development feature. However, I noticed that cpprestsdk for Linux isn't available through vcpgk, despite the libraries documentation giving guidelines on how to compile it for Linux.

Is there planned support for Linux, or is there a way use the Windows version in VS2017 Linux templates? The Windows versions aren't automatically linked for this template.

Thanks

**Comment by KindDragon** [comment]
> Is there planned support for Linux?

We have issue #57 about that

> is there a way use the Windows version in VS2017 Linux templates?

I do not think so

**Comment by LeonineKing1199** [comment]
You don't need vcpkg on Linux.

vcpkg is basically what Linux has had for a _long_ time, namely a sane package manager.

If you're on Ubuntu, cpprestsdk is already in the repos. If you're on Arch this is also the case. You should check with the distro you're using and see if cpprestsdk is already registered with its package manager.

**Comment by ras0219-msft** [comment]
For further discussion about Vcpkg on/targeting other platforms, please follow up in #57.

For further discussion about cpprestsdk specifically, please open an issue on the Cpprestsdk GitHub page: https://github.com/Microsoft/cpprestsdk
