### ISSUE TITLE
[New Port Request] IncludeOS

### ISSUE THREAD

**Issue by AMS21** [microsoft/vcpkg#9400]
Library name: IncludeOS

Library description: IncludeOS is a minimal unikernel operating system for C++ services running in the cloud and on real hardware.

Source repository URL: https://github.com/includeos/IncludeOS

Project homepage (if different from the source repository): https://www.includeos.org/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by MikeGitb** [comment]
Doesn't include-OS require a custom toolchain?

**Comment by NancyLi1013** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
