### ISSUE TITLE
[New Port Request] websocketpp-standalone

### ISSUE THREAD

**Issue by aaslane** [microsoft/vcpkg#9404]
Library name: websocketpp-standalone

Library description:  Library that implements RFC6455 The WebSocket Protocol using standalone version of ASIO

Source repository URL: https://github.com/zaphoyd/websocketpp

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

This is effectively the same as the websocketpp package, except the build-depends has to change boost-asio -> asio

This removes the dependency on the boost libs for those that do not require them.

**Comment by NancyLi1013** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
