### ISSUE TITLE
Error: database corrupted. 

### ISSUE THREAD

**Issue by plettplett** [microsoft/vcpkg#9406]
**Describe the bug**
Error: database corrupted. Package opencv4:x86-windows is installed but dependency protobuf:x86-windows is not.

**Environment**
- OS: [windows
- Compiler: MSVC 19.16.27034.0

**To Reproduce**
1. ./vcpkg install ANY PACKAGE fails with same message

**Failure logs** 
none generated
command line: C:\Users\chris\vcpkg>vcpkg install openssl

Error: database corrupted. Package opencv4:x86-windows is installed but dependency protobuf:x86-windows is not.

**Additional context**
I re-installed vcpkg, like as in:

cis> .\bootstrap-vcpkg.bat
cis> .\vcpkg integrate install

But getting same errors. Where is the location of the  database - can it be repaired or deleted

**Comment by vicroms** [comment]
Hi @plettplett 

You can fix the corruption by deleting the `installed/` folder. Warning: this will delete all uninstalled libraries too.

**Comment by plettplett** [comment]
Yes, thanks, that worked. It seems the dB corruption occurred while 2 ports were being installed simultaneously, from 2 command line termianals

**Comment by vicroms** [comment]
Yes, that can happen, at the moment we don't support running concurrently.

**Comment by jeevankoiri10** [comment]
This is so bad about vcpkg. It doesn't support merging capability.

**Comment by ShenMian** [comment]
Remove `opencv4` and reinstall it.

**Comment by ShenMian** [comment]
Remove `opencv4` and reinstall it.

**Comment by Daniate** [comment]
It doesn't need to delete the folder, delete `vcpkg\installed\vcpkg\status` file, and install will be ok.
