### ISSUE TITLE
[New Port Request] mcpp

### ISSUE THREAD

**Issue by ZeroAbility** [microsoft/vcpkg#9415]
Library name: mcpp

Library description: Fork of mcpp, a C/C++ preprocessor

Source repository URL: https://github.com/zeroc-ice/mcpp

Project homepage (if different from the source repository): https://zeroc.com/

Anything else that is useful to know when adding (such as optional features the library may have that should be included): Required by ZeroC Ice

**Comment by NancyLi1013** [comment]
Hi @ZeroAbility  thanks for posting this request and also for your PR.
This port has been added to vcpkg. Please try to update vcpkg and use it.
