### ISSUE TITLE
Struggling to install libssh

### ISSUE THREAD

**Issue by allwrighty10** [microsoft/vcpkg#9417]
Hi there, I'm trying trying to install libssh using vcpkg as recommended by the official libssh site (https://www.libssh.org/get-it/) by using the standard command...

PS F:\Windows\Source\Libraries\vcpkg> .\vcpkg.exe install libssh

However, I keep receiving a number of errors in regards to cmake and unresolved hostname's.
Does anyone else experience this problem for this library, and what could be a solution to it?

**Comment by AlvinZhangH** [comment]
Hi, @allwrighty10 Thanks for reporting this issue.
could provide us failure logs?

Thanks.
[1]. https://github.com/microsoft/vcpkg/blob/master/docs/examples/installing-and-using-packages.md

**Comment by allwrighty10** [comment]
This was my powershell output after I reattempted to install libssh.

PS F:\Windows\Source\Libraries\vcpkg> .\vcpkg.exe install libssh
The following packages will be built and installed:
    libssh[core]:x86-windows
  \* openssl[core]:x86-windows
  \* openssl-windows[core]:x86-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/3: openssl-windows:x86-windows
Building package openssl-windows[core]:x86-windows...
-- Using cached F:/Windows/Source/Libraries/vcpkg/downloads/strawberry-perl-5.30.0.1-32bit.zip
CMake Error: Problem with archive_write_finish_entry(): Can't restore time
CMake Error: Problem extracting tar: F:/Windows/Source/Libraries/vcpkg/downloads/strawberry-perl-5.30.0.1-32bit.zip
-- Using cached F:/Windows/Source/Libraries/vcpkg/downloads/openssl-1.0.2s.tar.gz
-- Using source at F:/Windows/Source/Libraries/vcpkg/buildtrees/openssl-windows/src/openssl-1-c41872ef97
-- Using cached F:/Windows/Source/Libraries/vcpkg/downloads/jom_1_1_3.zip
CMake Error: Problem with archive_write_finish_entry(): Can't restore time
CMake Error: Problem extracting tar: F:/Windows/Source/Libraries/vcpkg/downloads/jom_1_1_3.zip
-- Copying openssl release source files...
-- Copying openssl release source files... done
-- Configure x86-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: PERL-NOTFOUND Configure enable-static-engine enable-capieng no-ssl2 -utf-8 VC-WIN32 --prefix=F:/Windows/Source/Libraries/vcpkg/packages/openssl-windows_x86-windows --openssldir=F:/Windows/Source/Libraries/vcpkg/packages/openssl-windows_x86-windows -FS
    Working Directory: F:/Windows/Source/Libraries/vcpkg/buildtrees/openssl-windows/x86-windows-rel
    Error code: The system cannot find the file specified
    See logs for more information:

Call Stack (most recent call first):
  ports/openssl-windows/portfile.cmake:97 (vcpkg_execute_required_process)
  scripts/ports.cmake:94 (include)


Error: Building package openssl-windows:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: openssl-windows:x86-windows
  Vcpkg version: 2019.09.12-nohash

Additionally, attach any relevant sections from the log files above.

**Comment by NancyLi1013** [comment]
Hi @allwrighty10 
`libssh `has been updated to 0.9.3.
Could you please try to update vcpkg and rebuild this port?

**Comment by NancyLi1013** [comment]
Looks like a cmake bug.
https://gitlab.kitware.com/cmake/cmake/issues/19132

**Comment by JackBoosY** [comment]
Hi @allwrighty10, does this issue still exist? Could you update vcpkg and repro this issue again?

**Comment by allwrighty10** [comment]
It works now, all good.
