### ISSUE TITLE
Post-build validation failed when building opencv with ffmpeg support

### ISSUE THREAD

**Issue by babu-thomas** [Microsoft/vcpkg#942]
I tried to install `opencv-3.2.0` with ffmpeg support by setting `-DWITH_FFMPEG` option to ON in `portfile.cmake` and adding `ffmpeg` to `Build-Depends` line of `CONTROL` file.

All the dependencies including ffmpeg built successfully but the installation failed with the following message - 

```
-- Performing post-build validation
Detected outdated dynamic CRT in the following files:

    D:/code/vcpkg/packages/opencv_x86-windows/debug/bin/opencv_ffmpeg320.dll: msvcrt.dll
    D:/code/vcpkg/packages/opencv_x86-windows/bin/opencv_ffmpeg320.dll: msvcrt.dll

To inspect the dll files, use:
    dumpbin.exe /dependents mydllfile.dll
Found 1 error(s). Please correct the portfile:
    D:\code\vcpkg\ports\opencv\portfile.cmake
-- Performing post-build validation done
Error: Building package opencv:x86-windows failed with: POST_BUILD_CHECKS_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: opencv:x86-windows
  Vcpkg version: 0.0.79-37b250abb8f25d95a4c4323be8860875bd1e2168
```
I am running VS 2017 on Windows 10 Anniversary Update

**Comment by lazylazypig** [comment]
@babu-thomas hi, I met the same problem with setting -DWITH_FFMPEG option to ON. have you found a solution to fix it? thanks

**Comment by babu-thomas** [comment]
@lazylazypig No. I ended up installing opencv from the [official installer](http://opencv.org/releases.html).

**Comment by UnaNancyOwen** [comment]
Please set <code>VCPKG_POLICY_ALLOW_OBSOLETE_MSVCRT</code> in triplet file.
If you enable this policy, vcpkg skip CRT check.
```cmake
set(VCPKG_POLICY_ALLOW_OBSOLETE_MSVCRT enabled)
```

**Comment by babu-thomas** [comment]
@UnaNancyOwen Nice to know its been fixed. Closing this now.
