### ISSUE TITLE
[New Port Request] <mbed-os>

### ISSUE THREAD

**Issue by adamvm** [microsoft/vcpkg#9421]
Library name: mbed-os

Library description: Arm Mbed OS is a platform operating system designed for the internet of things

Source repository URL: https://github.com/ARMmbed/mbed-os

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by NancyLi1013** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
