### ISSUE TITLE
[New Port Request] libdeflate

### ISSUE THREAD

**Issue by Jenosu** [microsoft/vcpkg#9424]
Library name: libdeflate

Library description: Heavily optimized library for DEFLATE/zlib/gzip compression and decompression

Source repository URL: https://github.com/ebiggers/libdeflate

Anything else that is useful to know when adding:

> libdeflate may be built using the Visual Studio toolchain by running `nmake /f Makefile.msc`

The resulting files are `libdeflate.dll` and `libdeflate.lib` for dynamic, and `libdeflatestatic.lib` for static.

**Comment by NancyLi1013** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
