### ISSUE TITLE
[atkmm:x64-windows] build failure 

### ISSUE THREAD

**Issue by lufflotneckar** [microsoft/vcpkg#9436]
**Host Environment**
- OS:win10 x64 home chinese 
- Compiler: Visual Studio Community 2019 (16.4.2)
- Vcpkg version: 2019.09.12-nohash-external
- cmake version 3.16.2
**To Reproduce**
`./vcpkg install atkmm:x64-windows`

**Failure logs** 
- console output:

CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: msbuild D:/vcpkg/buildtrees/atkmm/src/atkmm-2-de808b48b0/MSVC_Net2013/atkmm.sln /p:Configuration=Release /t:atkmm /p:Platform=x64 /p:PlatformToolset=v142 /p:VCPkgLocalAppDataDisabled=true /p:UseIntelMKL=No /p:WindowsTargetPlatformVersion=10.0.18362.0 /m /p:ForceImportBeforeCppTargets=D:/vcpkg/scripts/buildsystems/msbuild/vcpkg.targets /p:VcpkgTriplet=x64-windows

    See logs for more information:
     D:\vcpkg\buildtrees\atkmm\build-x64-windows-rel-out.log
   Call Stack (most recent call first):
    scripts/cmake/vcpkg_build_msbuild.cmake:119 (vcpkg_execute_required_process)
    ports/atkmm/portfile.cmake:25 (vcpkg_build_msbuild)
    scripts/ports.cmake:94 (include)
Error: Building package atkmm:x64-windows failed with: BUILD_FAILED

 
- D:\vcpkg\buildtrees\atkmm\build-x64-windows-rel-out.log :
  2>D:\vcpkg\installed\x64-windows\include\glibmm\balancedtree.h(1,1): 
 **error C4819: The file contains a character that cannot be represented in the current code page (936).** Save the file in Unicode format to prevent data loss (compiling source file ..\atk\atkmm\text.cc) [D:\vcpkg\buildtrees\atkmm\src\atkmm-2-de808b48b0\MSVC_Net2013\atkmm.vcxproj]

**Comment by AlvinZhangH** [comment]
Hi, @lufflotneckar Thanks for reporting this issue.
I can not reproduce this issue in my machine.
could provide us failure logs?

**Comment by JackBoosY** [comment]
Hi @lufflotneckar, thanks for reporting this issue!
Could you provide file _D:\vcpkg\installed\x64-windows\include\glibmm\balancedtree.h_ ?

Thanks.

**Comment by lufflotneckar** [comment]
ok,@JackBoosY 
[balancedtree.zip](https://github.com/microsoft/vcpkg/files/4004633/balancedtree.zip)
this file is downloaded and extracted automatically by vcpkg from  `http://ftp.gnome.org/pub/GNOME/sources/atkmm/2.24/atkmm-2.24.2.tar.xz`.

**Comment by JackBoosY** [comment]
@lufflotneckar Could you remove these comments in _D:\vcpkg\installed\x64-windows\include\glibmm\balancedtree.h_ and try again?
This issue may be caused by the author name of non-standard ASCII.

**Comment by lufflotneckar** [comment]
@JackBoosY ,it works!! Thanks~
