### ISSUE TITLE
Mongo-cxx-driver: need compilation with openssl

### ISSUE THREAD

**Issue by AJIOB** [Microsoft/vcpkg#944]
Hello.

I want to connect to mongoDB server from my app, but it requires ssl connection. Please, add support of openssl to mongo-cxx-driver:x86-windows & x64-windows.
By default, mongo cxx driver has ssl support (by openssl).

With regards,
Alex

**Comment by ras0219-msft** [comment]
Hi Alex, could you describe a bit more in detail the exact scenario? Specifically, what doesn't work from your code (ideally a repro!) and what versions of mongo-c-driver and mongo-cxx-driver you have.

Based on the build options available and the official build instructions[1], it looks like mongo-c-driver is responsible for providing SSL support. We're currently using the native Windows SSL support on desktop (`ENABLE_SSL=Windows`).

[1] http://mongoc.org/libmongoc/current/installing.html#native-tls-support-on-windows-secure-channel

**Comment by AJIOB** [comment]
When I try to connect with my program to official MongoDB Database-as-a-Service server (cluster), I have this error: "SSL support not available"

**Comment by AJIOB** [comment]
I was updated to newer version of driver - and it was fixed
