### ISSUE TITLE
[libpq] failure on linux due to both endian blocks being enabled

### ISSUE THREAD

**Issue by Outurnate** [microsoft/vcpkg#9440]
**Host Environment**
- OS: linux 5.3.13
- Compiler: gcc 9.2.0 (glibc 2.30)

**To Reproduce**
`./vcpkg install libpq`

**Failure logs** 

    FAILED: CMakeFiles/libpq.dir/src/interfaces/libpq/fe-connect.c.o 
    /usr/bin/cc -DENABLE_THREAD_SAFETY -DFRONTEND -DHAVE_CRYPTO_LOCK -DUSE_OPENSSL -D_CRT_SECURE_NO_WARNINGS -D_GNU_SOURCE -I. -I/usr/share/vcpkg/buildtrees/libpq/src/stgresql-9-d40671c654 -I/usr/share/vcpkg/buildtrees/libpq/src/stgresql-9-d40671c654/src/include -I/usr/share/vcpkg/buildtrees/libpq/src/stgresql-9-d40671c654/src/port -Iinclude -isystem /usr/share/vcpkg/installed/x64-linux/include -fPIC -g -MD -MT CMakeFiles/libpq.dir/src/interfaces/libpq/fe-connect.c.o -MF CMakeFiles/libpq.dir/src/interfaces/libpq/fe-connect.c.o.d -o CMakeFiles/libpq.dir/src/interfaces/libpq/fe-connect.c.o   -c /usr/share/vcpkg/buildtrees/libpq/src/stgresql-9-d40671c654/src/interfaces/libpq/fe-connect.c
    In file included from /usr/share/vcpkg/buildtrees/libpq/src/stgresql-9-d40671c654/src/interfaces/libpq/fe-connect.c:49:
    /usr/include/netinet/tcp.h:112:10: error: duplicate member ‘th_off’
      112 |  uint8_t th_off:4; /* data offset */
          |          ^~~~~~
    /usr/include/netinet/tcp.h:113:10: error: duplicate member ‘th_x2’
      113 |  uint8_t th_x2:4; /* (unused) */
          |          ^~~~~

**Additional context**
Modifying tcp.h to only enable one block allows the build to complete

**Comment by JackBoosY** [comment]
Could you provide the full build log?

Thanks.

**Comment by Outurnate** [comment]
Apologies, this was a config issue on my machine.  My compiler wasn't defining the endian symbols.  I did a full system upgrade and the package now builds
