### ISSUE TITLE
[Qt] Make target linkage against Qt5 sane

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#9442]
Unfortunally Qt5 targets do not link against system libs at all. This is why the current vcpkg_cmake_wrapper is required.

For example to make paraview build with static plugins the following is required in the wrapper:
```
    elseif(UNIX AND NOT APPLE)
      add_qt_library(Qt5::Core            
            Qt5GraphicsSupport
            Qt5ClipboardSupport
            Qt5LinuxAccessibilitySupport
            Qt5AccessibilitySupport
            Qt5ServiceSupport
            Qt5FbSupport
            Qt5EglSupport
            Qt5InputSupport
            Qt5DeviceDiscoverySupport
            Qt5EdidSupport
            Qt5KmsSupport
            Qt5GlxSupport
            Qt5EglFSDeviceIntegration
            Qt5EglFsKmsSupport
            Qt5XcbQpa
            EGL
            fontconfig expat
            Qt5Gui
            Qt5DBus
            Qt5Core)
       #find_package(X11 REQUIRED) 
       set_property(TARGET Qt5::Core APPEND PROPERTY INTERFACE_LINK_LIBRARIES
            xcb-glx X11-xcb xcb-xinput xcb-icccm xcb-image xcb-shm xcb-keysyms xcb-randr xcb-render-util 
            xcb-render xcb-shape xcb-sync xcb-xfixes xcb-xinerama xcb-xkb xcb Xrender Xext X11 
            m SM ICE mtdev input xkbcommon-x11 xkbcommon dl GL gbm udev
            OpenSSL::SSL OpenSSL::Crypto Freetype::Freetype
            dbus-1 drm gthread-2.0 glib-2.0 gtk-3 gdk-3 pangocairo-1.0 pango-1.0 atk-1.0 cairo-gobject cairo gdk_pixbuf-2.0 gio-2.0 gobject-2.0 glib-2.0 Xext X11
            )
```

Simply adding all required system libraries to core seems wrong and also incomplete. 
As such a better way to link all the required libraries is required. 
Qt luckily creates a PRL file along the library. As such the wrapper should identify all imported Qt5 targets after the find_package call, extract the library location and parse the corresponding `*.prl` file of that library to acquire the required libraries necessary for linkage and add those to the `interface_link_libraries` property of the current analyzed target. On stupid think Qt does is that plugins does not even link again their required Qt targets which makes adding those also required.

**Comment by janholt** [comment]
Seems linking with static qt from cmake has been done in qt 5.14
https://bugreports.qt.io/browse/QTBUG-38913

Looks like a parse for `prl` files
https://github.com/qt/qtbase/blob/5.14.0/mkspecs/features/data/cmake/Qt5BasicConfig.cmake.in
```
!!IF !isEmpty(CMAKE_STATIC_TYPE)
function(_qt5_$${CMAKE_MODULE_NAME}_process_prl_file prl_file_location Configuration lib_deps link_flags)
```

**Comment by Neumann-A** [comment]
@janholt:
tested it and it seems to automatically link the required libraries. Unfortunately there is a lot of mix-up with release libraries in debug builds which I am currently trying to fix in my local paraview branch updated to use qt5.14.0. 

And can somebody tell the Qt team that they should just use one function instead of n equally generated functions for the parsing of the PRL files? So much unnecessary code....

**Comment by Neumann-A** [comment]
Open: https://bugreports.qt.io/browse/QTBUG-81113

**Comment by Neumann-A** [comment]
A good thing though is that the wrapper can be removed in 5.14
