### ISSUE TITLE
[osg] does not build on non windows platforms

### ISSUE THREAD

**Issue by Outurnate** [microsoft/vcpkg#9449]
**Host Environment**
- OS: Linux 5.4.6-arch3-1 #1 SMP PREEMPT Tue, 24 Dec 2019 04:36:53 +0000
- Compiler: gcc 9.2.0

**To Reproduce**
`./vcpkg install osg` on linux

**Failure logs**

    The following packages will be built and installed:
        osg[core]:x64-linux
    Starting package 1/1: osg:x64-linux
    Building package osg[core]:x64-linux...
    -- Note: osg only supports dynamic library linkage. Building dynamic library.
    -- Using cached /var/cache/vcpkg/openscenegraph-OpenSceneGraph-OpenSceneGraph-3.6.4.tar.gz
    -- Using source at /usr/share/vcpkg/buildtrees/osg/src/raph-3.6.4-bacad88ef3
    -- Configuring x64-linux-dbg
    -- Configuring x64-linux-rel
    -- Building x64-linux-dbg
    CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
        Command failed: /usr/bin/cmake --build . --config Debug --target install -- -v
        Working Directory: /usr/share/vcpkg/buildtrees/osg/x64-linux-dbg
        See logs for more information:
          /usr/share/vcpkg/buildtrees/osg/install-x64-linux-dbg-out.log

    Call Stack (most recent call first):
      scripts/cmake/vcpkg_build_cmake.cmake:91 (vcpkg_execute_build_process)
      scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
      ports/osg/portfile.cmake:27 (vcpkg_install_cmake)
      scripts/ports.cmake:94 (include)

    Error: Building package osg:x64-linux failed with: BUILD_FAILED
    Please ensure you're using the latest portfiles with `.\vcpkg update`, then
    submit an issue at https://github.com/Microsoft/vcpkg/issues including:
      Package: osg:x64-linux
      Vcpkg version: 2019.09.12-unknownhash

    Additionally, attach any relevant sections from the log files above.

Log file [install-x64-linux-dbg-out.log](https://gist.github.com/Outurnate/41d398b005d2bbc4e9c986a2a7f52230)

**Additional context**
OSG_USE_UTF8_FILENAME is defined on all platforms, but it only works on Windows.  The symbol causes OSG to use _wfopen instead of fopen.  I've fixed this issue with #9441

**Comment by JackBoosY** [comment]
Hi @Outurnate, thanks for reporting this issue!
I couldn't find any error info in your logs, and osg should be fixed in Linux and OSX.
So please update vcpkg and rebuild it.

Thanks.
