### ISSUE TITLE
[freeimage] fails to configure on case-sensitive systems

### ISSUE THREAD

**Issue by Outurnate** [microsoft/vcpkg#9450]
**Describe the bug**
freeimage's CMakeLists.txt file calls for ZLIB, however, the file is installed as zlibConfig.cmake.  On case sensitive machines, the config file cannot be found

Additionally, fixing this issue does not fix the port.  LibRawConfig.cmake cannot be found either

**Environment**
- OS: Linux 5.4.6-arch3-1 #1 SMP PREEMPT Tue, 24 Dec 2019 04:36:53 +0000
- Compiler: gcc 9.2.0

**To Reproduce**
`./vcpkg install freeimage` on any case sensitive system (e.g. linux)

**Failure logs** 

    The following packages will be built and installed:
        freeimage[core]:x64-linux
    Starting package 1/1: freeimage:x64-linux
    Building package freeimage[core]:x64-linux...
    -- Using cached /home/joseph/eclipse/vcpkg-outurnate/vcpkg/downloads/FreeImage3180.zip
    -- Using source at /home/joseph/eclipse/vcpkg-outurnate/vcpkg/buildtrees/freeimage/src/eImage3180-2288df34d2
    -- Configuring x64-linux-dbg
    CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
        Command failed: /home/joseph/eclipse/vcpkg-outurnate/vcpkg/downloads/tools/cmake-3.14.0-linux/cmake-3.14.0-Linux-x86_64/bin/cmake /home/joseph/eclipse/vcpkg-outurnate/vcpkg/buildtrees/freeimage/src/eImage3180-2288df34d2 -DVCPKG_ROOT_DIR=/home/joseph/eclipse/vcpkg-outurnate/vcpkg -DTARGET_TRIPLET=x64-linux -DCMAKE_MAKE_PROGRAM=/usr/bin/ninja -DCMAKE_SYSTEM_NAME=Linux -DBUILD_SHARED_LIBS=OFF -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=/home/joseph/eclipse/vcpkg-outurnate/vcpkg/scripts/toolchains/linux.cmake -DVCPKG_TARGET_TRIPLET=x64-linux -DVCPKG_SET_CHARSET_FLAG=ON -DVCPKG_PLATFORM_TOOLSET=external -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON -DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE -DCMAKE_VERBOSE_MAKEFILE=ON -DVCPKG_APPLOCAL_DEPS=OFF -DCMAKE_TOOLCHAIN_FILE=/home/joseph/eclipse/vcpkg-outurnate/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON -DVCPKG_CXX_FLAGS= -DVCPKG_CXX_FLAGS_RELEASE= -DVCPKG_CXX_FLAGS_DEBUG= -DVCPKG_C_FLAGS= -DVCPKG_C_FLAGS_RELEASE= -DVCPKG_C_FLAGS_DEBUG= -DVCPKG_CRT_LINKAGE=dynamic -DVCPKG_LINKER_FLAGS= -DVCPKG_TARGET_ARCHITECTURE=x64 -DCMAKE_INSTALL_LIBDIR:STRING=lib -DCMAKE_INSTALL_BINDIR:STRING=bin -DINSTALL_HEADERS=OFF -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/home/joseph/eclipse/vcpkg-outurnate/vcpkg/packages/freeimage_x64-linux/debug
        Working Directory: /home/joseph/eclipse/vcpkg-outurnate/vcpkg/buildtrees/freeimage/x64-linux-dbg
        Error code: 1
        See logs for more information:
          /home/joseph/eclipse/vcpkg-outurnate/vcpkg/buildtrees/freeimage/config-x64-linux-dbg-out.log
          /home/joseph/eclipse/vcpkg-outurnate/vcpkg/buildtrees/freeimage/config-x64-linux-dbg-err.log

    Call Stack (most recent call first):
      scripts/cmake/vcpkg_configure_cmake.cmake:302 (vcpkg_execute_required_process)
      ports/freeimage/portfile.cmake:43 (vcpkg_configure_cmake)
      scripts/ports.cmake:94 (include)

    Error: Building package freeimage:x64-linux failed with: BUILD_FAILED
    Please ensure you're using the latest portfiles with `.\vcpkg update`, then
    submit an issue at https://github.com/Microsoft/vcpkg/issues including:
      Package: freeimage:x64-linux
      Vcpkg version: 2019.09.12-unknownhash

    Additionally, attach any relevant sections from the log files above.

In config-x64-linux-dbg-err.log:

    CMake Error at /home/joseph/eclipse/vcpkg-outurnate/vcpkg/scripts/buildsystems/vcpkg.cmake:263 (_find_package):
      By not providing "Findzlib.cmake" in CMAKE_MODULE_PATH this project has
      asked CMake to find a package configuration file provided by "zlib", but
      CMake did not find one.

      Could not find a package configuration file provided by "zlib" with any of
      the following names:

        zlibConfig.cmake
        zlib-config.cmake

      Add the installation prefix of "zlib" to CMAKE_PREFIX_PATH or set
      "zlib_DIR" to a directory containing one of the above files.  If "zlib"
      provides a separate development package or SDK, be sure it has been
      installed.
    Call Stack (most recent call first):
      CMakeLists.txt:16 (find_package)

**Additional context**
I'll be following this issue up with a PR to fix the issue.  In addition to this problem, there's an a problem with LibRaw as well

**Comment by Outurnate** [comment]
Also resolved by #8707

**Comment by PhoebeHui** [comment]
@Outurnate , thanks for reporting this issue!

Above PR has been merged. Please get vcpkg latest source and try again.
