### ISSUE TITLE
vtk[qt] build failure

### ISSUE THREAD

**Issue by atnTeosit** [microsoft/vcpkg#9451]
**Host Environment**
- OS:Windows
- Compiler: Visual Studio 2017

**To Reproduce**
`./vcpkg install vtk[qt]`

**Additional context**
vtkGUISupportQt-8.2 not compiled
workaround:
set(VTK_WITH_QT ON) in ports/vtk/portfile.cmake

**Comment by drescherjm** [comment]
I think this is a duplicate of https://github.com/microsoft/vcpkg/issues/9023

**Comment by JackBoosY** [comment]
Thanks @drescherjm.
Duplicate with #9023.
