### ISSUE TITLE
[New Port Request] <msgpack11>

### ISSUE THREAD

**Issue by amir1376irani** [microsoft/vcpkg#9465]
Library name: msgpack11

Library description: A tiny MessagePack library for C++11 (msgpack.org[C++11])

Source repository URL: https://github.com/ar90n/msgpack11

Project homepage : same as source repository

**Comment by JackBoosY** [comment]
msgpack11 is a tiny MsgPack library for C++11

**Comment by SanaJahan** [comment]
Hi, I have been working on this issue. Can I raise a PR for this one?

**Comment by JackBoosY** [comment]
@SanaJahan Yes please.

**Comment by SanaJahan** [comment]
Hi, I tested for x64-windows-static, and I was able to install the port successfully. Any suggestions on how I can fix the same in the CI to pass the job for x64-windows-static. I downloaded the logs to check for the errors and it shows the build succeeded.

**Comment by JackBoosY** [comment]
Hi @amir1376irani, this port has been added in #9524. please update vcpkg and try to build it.

Thanks.
