### ISSUE TITLE
[New Port Request] <cppgram>

### ISSUE THREAD

**Issue by amir1376irani** [microsoft/vcpkg#9466]
Library name : cppgram

Library description :
Framework for Telegram Bot API written in c++
Easy and modern C++14 Telegram Bot API wrapper

Source repository URL : https://github.com/DanySpin97/cppgram

Project homepage : https://danyspin97.github.io/cppgram/

**Comment by NancyLi1013** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
