### ISSUE TITLE
[New Port Request] <xxtelebot>

### ISSUE THREAD

**Issue by amir1376irani** [microsoft/vcpkg#9469]
Library name: xxtelebot

Library description: A simple C++11 Telegram Bot API implementation

Source repository URL: https://github.com/StefanoBelli/xxtelebot

Project homepage : https://stefanobelli.github.io/xxtelebot/

**Comment by NancyLi1013** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now
