### ISSUE TITLE
[New Port Request] <TarnaBot>

### ISSUE THREAD

**Issue by amir1376irani** [microsoft/vcpkg#9470]
Library name: TarnaBot

Library description: A Qt5/C++ library for creating Telegram bots 

Source repository URL: https://github.com/Codenegaar/TarnaBot

Project homepage : same as source repository

Anything else that is useful to know when adding (such as optional features the library may have that should be included):
developer from :iran:
telegram : https://t.me/Codenegaar
mail : alirashidi127@gmail.com

**Comment by NancyLi1013** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
