### ISSUE TITLE
[New Port Request] <libtelegram>

### ISSUE THREAD

**Issue by amir1376irani** [microsoft/vcpkg#9471]
Library name: libtelegram

Library description: Fast, efficient, header-only C++ Telegram bot API library using polling or FastCGI 

Source repository URL: https://github.com/slowriot/libtelegram

Project homepage : same as source repository

Anything else that is useful to know when adding (such as optional features the library may have that should be included):
One of the most popular and fast telegraam bot api library for C++ devs

**Comment by NancyLi1013** [comment]
We can’t reopen this issue until a PR is opened, unfortunately, consider making a pull request!
