### ISSUE TITLE
[New Port Request] <tgbot-cpp>

### ISSUE THREAD

**Issue by amir1376irani** [microsoft/vcpkg#9472]
Library name : tgbot-cpp

Library description : C++ library for Telegram bot API

Source repository URL : https://github.com/reo7sp/tgbot-cpp

Project homepage : http://reo7sp.github.io/tgbot-cpp/index.html

Anything else that is useful to know when adding (such as optional features the library may have that should be included):
Most popular library to work with telegram bot API by C++ devs (not just my personal opinion, based on number of repository stars and forks in GitHub in compare to other repos starts and forks that works like this repo, says that this repo is most popular among all telegram API libraries).
Most maintained and up-to-date library in it's own scope (telegram bot API / C++).
Clean code and use of C++11 so many compilers out there can compile without issue.
Modular design just like telegram MTproto layers API (like https://core.telegram.org/bots/api)
Support both long polling and webhook method.
Can use in docker.
and much much more ...

I'm just wondering why it's not added earlier to vcpkg!!

**Comment by ummdd** [comment]
so can i install tgbot-cpp from vcpkg?

**Comment by NancyLi1013** [comment]
@ummdd 
It still cannot be installed in vcpkg now. If you're interested in adding this port, please make a pull request to add this. But we're going to close this for now.

We can’t reopen this issue until a PR is opened, unfortunately, consider making a pull request!
