### ISSUE TITLE
[libxml2] Embed resources in Windows-based shared library

### ISSUE THREAD

**Issue by trueqbit** [microsoft/vcpkg#9474]
****

**Resulting _libxml2.dll_ is missing file resource properties.**

**Proposed solution**
Resulting _libxml2.dll_ should have file resource properties embedded. This is easily achievable as the libxml2 project source already comes with the needed _.rc_ file, and can simply be added to the compilation step of the port (see accompanying PR #9476).

**Additional context**
<img width="378" alt="libxml2 w/o resources" src="https://user-images.githubusercontent.com/5430212/71521753-b72e6f80-28ca-11ea-9fa2-8fdceeaf7268.png">
<img width="378" alt="libxml2 w/ resources" src="https://user-images.githubusercontent.com/5430212/71521775-cd3c3000-28ca-11ea-885c-11ac4f09ef55.png">

**Comment by NancyLi1013** [comment]
Hi @trueqbit thanks for posting this issue and also for your PR.
Since the PR has been merged. I close this issue now.
