### ISSUE TITLE
Special characters(like german umlauts) not working in filepaths

### ISSUE THREAD

**Issue by Clock-work** [microsoft/vcpkg#9475]
When i use german umlauts(öäü) in filenames of my cmake project the cache generation fails at line 169("_add_executable(${ARGV})") of vcpkg.cmake with an invalid filepath("can not find source file"), because the characters are not displayed correctly. 
I dont know if this is a general cmake error, or if its specific to vcpkg

**Comment by JackBoosY** [comment]
Even with vcpkg support, there will be problems when building ports.

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
