### ISSUE TITLE
Rename sqlite-orm -> sqlite_orm

### ISSUE THREAD

**Issue by longnguyen2004** [microsoft/vcpkg#9482]
~~Library name:~~
~~sqlite_orm~~
~~Library description:~~
~~SQLite ORM light header only library for modern C++~~
~~Source repository URL:~~
~~https://github.com/fnc12/sqlite_orm~~
~~Project homepage (if different from the source repository):~~

~~Anything else that is useful to know when adding (such as optional features the library may have that should be included):~~

See my comments below

**Comment by mayankkt9** [comment]
I am working on this
Can I raise PR ?

**Comment by dhkatz** [comment]
Seems like this already exists in vcpkg at least at the time of commenting this.

Can probably close.

**Comment by longnguyen2004** [comment]
Oh yeah it does, my bad
Sidenote: The package name should be sqlite_orm, not sqlite-orm, as the repo and header file are named like that, and also to line up with the installation guide

**Comment by longnguyen2004** [comment]
anyone?

**Comment by longnguyen2004** [comment]
I'm just gonna close this since they've updated the README
