### ISSUE TITLE
[New Port Request] QxOrm

### ISSUE THREAD

**Issue by longnguyen2004** [microsoft/vcpkg#9483]
Library name:
QxOrm
Library description:
QxOrm library - C++ Qt ORM (Object Relational Mapping) and ODM (Object Document Mapper) library
Source repository URL:
https://github.com/QxOrm/QxOrm
Project homepage (if different from the source repository):
https://www.qxorm.com/qxorm_en/home.html
Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by NancyLi1013** [comment]
We can’t reopen this issue until a PR is opened, unfortunately, consider making a pull request!
