### ISSUE TITLE
I have download brotli-1.0.7.tar.gz and How do I palce it in which file directory to reduce download it in powershellHow do I ...

### ISSUE THREAD

**Issue by edidada** [microsoft/vcpkg#9485]
I am in China，while I run "vcpkg install cpprestsdk cpprestsdk:x64-windows" it can not download 
brotli-1.0.7.tar.gz, I download brotli-1.0.7.tar.gz through Chromen brower

**Comment by edidada** [comment]
As I know,vcpkg install will download sourcefile and compile it in I computer

**Comment by JackBoosY** [comment]
Hi @edidada, thanks for reporting this issue!
You can just copy it to _VCPKG_PATH/downloads_ then build it.

Thanks.
