### ISSUE TITLE
directxtk build failure for x86-uwp

### ISSUE THREAD

**Issue by mediabuff** [microsoft/vcpkg#9486]
Build FAILED.

       "C:\MyDevProjects\MyProjectsThirdPartyLibs\vcpkg2\vcpkg\buildtrees\directxtk\src\dec2019-b08f6255ba\DirectXTK_Windows10_2019.sln" (Rebuild target) (1) ->
       (ValidateSolutionConfiguration target) -> 
         C:\MyDevProjects\MyProjectsThirdPartyLibs\vcpkg2\vcpkg\buildtrees\directxtk\src\dec2019-b08f6255ba\DirectXTK_Windows10_2019.sln.metaproj : error MSB4126: The specified solution configuration "Release|Win32" is invalid. Please specify a valid solution configuration using the Configuration and Platform properties (e.g. MSBuild.exe Solution.sln /p:Configuration=Debug /p:Platform="Any CPU") or leave those properties blank to use the default solution configuration. [C:\MyDevProjects\MyProjectsThirdPartyLibs\vcpkg2\vcpkg\buildtrees\directxtk\src\dec2019-b08f6255ba\DirectXTK_Windows10_2019.sln]

    0 Warning(s)
    1 Error(s)

**Comment by PhoebeHui** [comment]
@mediabuff, thanks for reporting this issue!

The PR has been merged, it should address above issue.
