### ISSUE TITLE
[New Port Request] <sdsl-lite>

### ISSUE THREAD

**Issue by wavenator** [microsoft/vcpkg#9488]
Library name: sdsl-lite

Library description: The Succinct Data Structure Library (SDSL) is a powerful and flexible C++11 library implementing succinct data structures. In total, the library contains the highlights of 40 research publications. Succinct data structures can represent an object (such as a bitvector or a tree) in space close to the information-theoretic lower bound of the object while supporting operations of the original object efficiently. The theoretical time complexity of an operation performed on the classical data structure and the equivalent succinct data structure are (most of the time) identical.

Source repository URL: https://github.com/simongog/sdsl-lite

Project homepage (if different from the source repository): Same as  the source repository

Anything else that is useful to know when adding (such as optional features the library may have that should be included): None

**Comment by NancyLi1013** [comment]
We can’t reopen this issue until a PR is opened, unfortunately, consider making a pull request!
