### ISSUE TITLE
Best practise with vcpkg for multiple tool sets

### ISSUE THREAD

**Issue by terrylyons** [microsoft/vcpkg#9489]
Some while ago, there was a discussion about how to manage and develop code using different tool sets in visual studio. At the very least v140-v143. I contributed two scripts that, first generated triplets for these toolsets out of the default ones and then ensured that 
`vcpkg.bat install xxx:x64-windows` etc. generated the full complex of libraries. (see better management of multiple builds #7932).

I am currently setting up a new machine, It has a clean version of the SDKs for 7.1, 8.0, 8.1, and 10 and the current version of vs2019. My question, 6 months on, is what is the best practice for making this work smoothly so one can build with any chosen toolset, and is there now an agreed documentation. 

Visual studio 19 boasts knowledge of the following tool sets on my configuration:
![image](https://user-images.githubusercontent.com/6383355/71550476-00fd7f80-29c9-11ea-8888-91f00b5ddc78.png)

Personally my current need is to easily support C++ python extensions with a small boost dependency back to python 2. You will see that an automated approach that is correct really is required. It does not need to support every toolset, in my case I need to ensure my code builds for toolkits: 142 140 100 90, debug and release, x86 and x64 for windows and (to create a manylinux package) on an old version of centos and also on the mac. (24 contexts in all! 12 if one ignores the debug versions).

So I am very interested indeed in cross platform tools for building code with dependencies. I would like to use vcpkg with best practise. I don't find the correct part of the documentation.
   
Thanks. I still think the whole idea is wonderful.

**Comment by JackBoosY** [comment]
That's a good idea!
I think we need a management module and provide multi-version support for each compilation method. (It needs to support cmake at least)

So, please track issue #7923.

Thanks.
