### ISSUE TITLE
I have install Sqlite3 and boost， but the cmake cannot find it

### ISSUE THREAD

**Issue by JYP2011** [microsoft/vcpkg#9490]
I have install Sqlite3 and boost， but the cmake cannot find it

$ cmake .. -DCMAKE_TOOLCHAIN_FILE=C:/Users/jyppzz/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows
-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.17763.
-- Could NOT find SQLite3 (missing: SQLite3_INCLUDE_DIR SQLite3_LIBRARY)
-- Could NOT find Boost (missing: Boost_INCLUDE_DIR)
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
Boost_INCLUDE_DIR (ADVANCED)
   used as include directory in directory C:/Users/jyppz/source/github/hello

-- Configuring incomplete, errors occurred!
See also "C:/Users/jyppz/source/github/hello/build/CMakeFiles/CMakeOutput.log".

**Comment by PhoebeHui** [comment]
@JYP2011, I can't repro this issue. Could you double check?

Here is my steps:
1. ./vcpkg install sqlite3:x64-windows
2. ./vcpkg integrate install
3. Put the following file into .\sqlite3test\example
CMakeList.txt:
cmake_minimum_required(VERSION 3.8)
project(example)
find_package(sqlite3 CONFIG REQUIRED)
add_executable(example example.cpp)
target_link_libraries(example PRIVATE sqlite3)

example:
#include <stdio.h>
#include <sqlite3.h>
int main(int argc, char *argv[])
{
    printf("%s\n", sqlite3_libversion());
    return 0;
}

4.  cd  .\sqlite3test\build
5. cmake.exe -DCMAKE_TOOLCHAIN_FILE=F:/vcpkg/src/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows -DVCPKG_BUILD_TYPE=debug -G "Visual Studio 15 2017 Win64" ..\example
6. cmake --build .
7. F:\VCPKG\VCPKGTest\sqlite3test\build> .\Debug\example.exe
3.28.0

**Comment by PhoebeHui** [comment]
@JYP2011, feel free to reopen this issue if it still be a problem for you.
