### ISSUE TITLE
[New Port Request] <protoc-gen-validate>

### ISSUE THREAD

**Issue by felfelche** [microsoft/vcpkg#9491]
Library name: protoc-gen-validate

Library description: PGV is a protoc plugin to generate polyglot message validators. While protocol buffers effectively guarantee the types of structured data, they cannot enforce semantic rules for values. This plugin adds support to protoc-generated code to validate such constraints.

Source repository URL:  https://github.com/envoyproxy/protoc-gen-validate

Project homepage (if different from the source repository): https://mvnrepository.com/artifact/io.envoyproxy.protoc-gen-validate

**Comment by NancyLi1013** [comment]
We can’t reopen this issue until a PR is opened, unfortunately, consider making a pull request!
