### ISSUE TITLE
[vcpkg-msbuild-integration] Extending logic that decides between 'Release' and 'Debug' libraries by referring to $(UseDebugLibraries)

### ISSUE THREAD

**Issue by trueqbit** [microsoft/vcpkg#9495]
****

**Problem space**
Multiple people already tweaked the way _vcpkg.targets_ determines whether to deal with 'Release' or 'Debug' builds for MSBuild ([@paercebal](https://github.com/microsoft/vcpkg/commit/f1c6b5cd4b581ec8d3a1b86fe01c4444e3906b2d), [@ras0219-msft](https://github.com/microsoft/vcpkg/commit/330b8d8bab6a3d07165bf7c05fea09a8e0d56348)).

MSBuild features a build variable called `UseDebugLibraries`, which is used by MSBuild itself to decide between 'Release' and 'Debug' builds and is IMO the most accurate way to do so instead of checking naming conventions.
Also, this would save me from renaming Visual C++ configurations whose names don't start with "Release" or start with "Debug" but are variants using the 'Release' CRT.

**Proposed solution**
_scripts/buildsystems/msbuild/vcpkg.targets_ should be extended to determine the build configuration in the following way:

```xml
<VcpkgNormalizedConfiguration Condition="'$(UseDebugLibraries)' == 'true'">Debug</VcpkgNormalizedConfiguration>
<VcpkgNormalizedConfiguration Condition="'$(UseDebugLibraries)' == 'false'">Release</VcpkgNormalizedConfiguration>
<VcpkgNormalizedConfiguration Condition="'$(VcpkgNormalizedConfiguration)' == '' and $(VcpkgConfiguration.StartsWith('Debug'))">Debug</VcpkgNormalizedConfiguration>
<VcpkgNormalizedConfiguration Condition="'$(VcpkgNormalizedConfiguration)' == '' and ($(VcpkgConfiguration.StartsWith('Release')) or '$(VcpkgConfiguration)' == 'RelWithDebInfo' or '$(VcpkgConfiguration)' == 'MinSizeRel')">Release</VcpkgNormalizedConfiguration>
```

**Comment by BillyONeal** [comment]
That seems a reasonable solution to me

**Comment by BillyONeal** [comment]
(Although Robert made relevant comments in the PR)

**Comment by PhoebeHui** [comment]
Related to similar issue https://github.com/microsoft/vcpkg/issues/2940
