### ISSUE TITLE
[New Port Request] gtksourceview-4

### ISSUE THREAD

**Issue by napoleonlijun** [microsoft/vcpkg#9498]
**Library name:**
gtksourceview-4

**Library description:**
GtkSourceView is a GNOME library that extends GtkTextView, the standard GTK+ widget for multiline text editing. GtkSourceView adds support for syntax highlighting, undo/redo, file loading and saving, search and replace, a completion system, printing, displaying line numbers, and other features typical of a source code editor.

**Source repository URL:**
[gtksourceview](https://developer.gnome.org/gtksourceview/stable/intro.html)

**Comment by LilyWangL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
