### ISSUE TITLE
OpenCV download and build problems

### ISSUE THREAD

**Issue by aaronzs** [Microsoft/vcpkg#95]
I'm using Windows 7 and I successfully ran `vcpkg install boost`.

### Download failed
I tried `vcpkg install opencv:x64-windows` and encountered the error message as follow:
```powershell
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:10 (file):
  file SHA512 failed to read file
  "C:/opt/vcpkg/downloads/opencv-92387b1ef8fad15196dd5f7fb4931444a68bc93a.zip":
  No such file or directory
```
It seems that vcpkg failed to download the source file from `https://github.com/opencv/opencv/archive/92387b1ef8fad15196dd5f7fb4931444a68bc93a.zip`

Then I have to download `.zip` file manually to avoid this error.
When I download the `.zip` file, I notice that my browser jumps to `https://codeload.github.com/opencv/opencv/zip/92387b1ef8fad15196dd5f7fb4931444a68bc93a` from `https://github.com/opencv/opencv/archive/92387b1ef8fad15196dd5f7fb4931444a68bc93a.zip`.

### CUDA does not support vs2015 update 3
Here is an error during build.
```powershell
-- Package x64-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:14 (message):
  Command failed:
  C:/Users/<USERNAME>/AppData/Local/scoop/apps/cmake/3.6.1/bin/cmake.exe;--build;.;--config;Release;--target;install

  Working Directory: C:/opt/vcpkg/buildtrees/opencv/x64-windows-rel
```
I read the `package-x64-windows-rel-out.log` and it was caused by CUDA.
I need to add `-DWITH_CUDA=OFF` in `portfile.cmake` to disable GPU modules. 

### Path to LICENSE is wrong
```powershell
CMake Error at ports/opencv/portfile.cmake:50 (file):
  file COPY cannot find "C:/opt/vcpkg/buildtrees/opencv/src/LICENSE".
```

**Comment by ras0219-msft** [comment]
Thanks for reporting these issues, I've applied fixes for each of them and pushed the result, please try installing opencv again after pulling.

**Comment by aaronzs** [comment]
@ras0219-msft 
now it works :smile:
