### ISSUE TITLE
[New Port Request] include-what-you-use

### ISSUE THREAD

**Issue by yurybura** [microsoft/vcpkg#9500]
Library name:
include-what-you-use
Library description:
A tool for use with clang to analyze #includes in C and C++ source files
Source repository URL:
https://github.com/include-what-you-use/include-what-you-use
Project homepage (if different from the source repository):
https://include-what-you-use.org/

**Comment by LilyWangL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
