### ISSUE TITLE
[New Port Request] <GASol>

### ISSUE THREAD

**Issue by amir1376irani** [microsoft/vcpkg#9507]
Library name: GASol

Library description: A general Genetic Algorithm Solver in C++

Source repository URL: https://github.com/PytLab/GASol

Project homepage : same as source repository

Anything else that is useful to know when adding (such as optional features the library may have that should be included):
There isn't any library in vcpkg to support any kind of genetic algorithms in c++ !

**Comment by mayankkt9** [comment]
Can I raise PR ?

**Comment by JackBoosY** [comment]
Thanks @mayankkt9.
