### ISSUE TITLE
wangle wangle:x64-windows build failure

### ISSUE THREAD

**Issue by edidada** [microsoft/vcpkg#9509]
**Describe the bug**
can not build wangle success
**Environment**
- OS: Windows
- Compiler: msvc

**To Reproduce**
1. ./vcpkg install wangle wangle:x64-windows
2. See error
Starting package 19/29: folly:x86-windows
Building package folly[core,zlib]:x86-windows...
CMake Error at ports/folly/portfile.cmake:4 (message):
  Folly only supports the x64 architecture.
Call Stack (most recent call first):
  scripts/ports.cmake:94 (include)

Error: Building package folly:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: folly:x86-windows
  Vcpkg version: 2019.09.12-nohash

**Expected behavior**
build wangle success

**Failure logs** 

**Additional context**

**Comment by PhoebeHui** [comment]
@edidada, wangle depends on folly, folly does't support x86 architecture, so the failure is expected.

You can try to build wangle:x64-windows, and I have double confirmed, it build successfully.
