### ISSUE TITLE
[New Port Request] <mpv>

### ISSUE THREAD

**Issue by faming-wang** [microsoft/vcpkg#9511]
Library name: libmpv

Library description: Command line video player

Source repository URL: https://github.com/mpv-player/mpv

Project homepage: https://mpv.io

Anything else that is useful to know when adding (such as optional features the library may have that should be included): mpv is a free (as in freedom) media player for the command line. It supports a wide variety of media file formats, audio and video codecs, and subtitle types.

**Comment by treeshateorcs** [comment]
mpv is not a library

**Comment by faming-wang** [comment]
> mpv is not a library
Sorry, my English is not very good, I hope you can understand the following.
I know, But all his functions on windows are in mpv.dll,  I need mpv.lib. most media player apps are based on mpv. you can see "https://github.com/mpv-player/mpv/wiki/Applications-using-mpv"

**Comment by utkuce** [comment]
>mpv is not a library

mpv is an application but it is also a library which can be used by including client.h from https://github.com/mpv-player/mpv/tree/master/libmpv and linking against libmpv.
Examples of it being used as a library can be found at https://github.com/mpv-player/mpv-examples/tree/master/libmpv
It would be useful to have in the repository

**Comment by LilyWangL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.

**Comment by capric8416** [comment]
I have opened a pull request to add libmpv port https://github.com/microsoft/vcpkg/pull/40587

**Comment by sfhacker** [comment]
This is from 2019! God take me with you!
