### ISSUE TITLE
[protobuf] Macro PROTOBUF_USE_DLLS redefined

### ISSUE THREAD

**Issue by davidhunter22** [microsoft/vcpkg#9512]
The file x64-windows\include\google\protobuf\stubs\platform_macros.h has the following line at the end 
`#define PROTOBUF_USE_DLLS. `
The Cmake file x64-windows/share/protobuf/protobuf-tagets,cmake has a target property 
```
set_target_properties(protobuf::libprotobuf PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "PROTOBUF_USE_DLLS"
)
```
This leads to a macro redefine warning on PROTOBUF_USE_DLLS as it is defined on the compile line and again in the header file.
It looks like the macro define was added to the header file as the original file at https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/stubs/platform_macros.h does not have it. 
One or other of the defines should be removed, preferably the one in the header file, or if there is a good reason for it being there it should have a guard around it
#if !defined(PROTOBUF_USE_DLLS)
#define PROTOBUF_USE_DLLS 
#endif

**Comment by Neumann-A** [comment]
>One or other of the defines should be removed, preferably the one in the header file, or if there is a good reason for it being there it should have a guard around it

It is there due to the Visual Studio integration. Not everybody is using CMake although everybody should use CMake ;)

**Comment by davidhunter22** [comment]
Is it possible to add the macro guard then so the code in the header is 
```
#if !defined(PROTOBUF_USE_DLLS)
#define PROTOBUF_USE_DLLS
#endif
```
This will avoid getting warnings when using CMake.
