### ISSUE TITLE
[pugixml] Confusion between x86 and x64 with when using clang in Visual Studio

### ISSUE THREAD

**Issue by davidhunter22** [microsoft/vcpkg#9514]
I have a project I just ported to VCPKG. It has a bunch of CMake file and I generate Visual Studio project files. The regular Visual Studio solution built fine, this was generated using 
`cmake  -G "Visual Studio 16 2019" -DCMAKE_TOOLCHAIN_FILE="C:\vcpkg\scripts\buildsystems\vcpkg.cmake" -DVCPKG_TARGET_TRIPLET=x64-windows  ../src`
The solution uses various packages including pugixml, catch2, protobuf, ... In the generated CMakeCache.txt I see lines like
```
protobuf_DIR:PATH=C:/vcpkg/installed/x64-windows/share/protobuf
pugixml_DIR:PATH=C:/vcpkg/installed/x64-windows/share/pugixml
```
which is exactly what I expect. 
However we also build in Visual Studio using the built in clang compiler this is generated using 
`cmake  -G "Visual Studio 16 2019" -T ClangCL -DCMAKE_TOOLCHAIN_FILE="C:\vcpkg\scripts\buildsystems\vcpkg.cmake" -DVCPKG_TARGET_TRIPLET=x64-windows  ../src`
Note the "-T ClangCL" to slecect the Clang toolset. This all works apart from then getting link errors from the pugixml library at compile time. After investigation I discovered that the CMakeCache.txt has the following line
`pugixml_DIR:PATH=C:/vcpkg/installed/x86-windows/share/pugixml`
So it is pointing to the X86 version not the X64. This only occurs for pugixml all the other packages point to X64 as expected.
So I'm assuming this is early on in the CMake configuration of my project and is some issue with the .cmake file in VCPKG. However I'm a bit of a noob at vcpkg so don't really understand what.
I am happy to do more investigation or add logs if someone can point me in the right direction.

**Comment by davidhunter22** [comment]
Forgot to mention. The work around is to change the 
`pugixml_DIR:PATH=C:/vcpkg/installed/x86-windows/share/pugixml`
to 
`pugixml_DIR:PATH=C:/vcpkg/installed/x64-windows/share/pugixml`
in the generated CMakeCache.txt and rerun cmake, this will use the corrected cache file and things work fine

**Comment by JackBoosY** [comment]
I don't think vcpkg supports clang very well.
@ras0219-msft What do you think?

**Comment by JackBoosY** [comment]
cc @BillyONeal

**Comment by strega-nil** [comment]
I think this should be correct now? @davidhunter22 can you try again and tell us if it is still broken? If it is, with a repro, I'll work on fixing it :)

**Comment by davidhunter22** [comment]
Hi, sorry to take so long. Yes I can confirm this is fixed, did a few more experiments to try to break things as well but all looks good.
