### ISSUE TITLE
[New Port Request] cwalk

### ISSUE THREAD

**Issue by curtisgray** [microsoft/vcpkg#9515]
Library name: cwalk

Library description: 
Path library for C/C++. Cross-Platform for Windows, MacOS and Linux. Supports UNIX and Windows path styles on those platforms.

Source repository URL: https://github.com/likle/cwalk/

Project homepage (if different from the source repository): https://likle.github.io/cwalk/

**Comment by LilyWangL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
