### ISSUE TITLE
"cpp-netlib" package can't be found after installation

### ISSUE THREAD

**Issue by stdor** [microsoft/vcpkg#9518]
**Describe the bug**
 I installed cpp-netlib with vcpkg.
I'm using `find_package(cppnetlib CONFIG REQUIRED)` in my CMakeLists.txt file, but when trying to build I'm getting the error:
"Could not find a package configuration file provided by "cppnetlib"..."

- I tried also with `find_package(cpp_netlib CONFIG REQUIRED)`, `find_package(cpp-netlib CONFIG REQUIRED)` and nothing...

**Environment**
- OS: Windows 10
- Compiler: MSVC
- CMAKE tool: 3.15

**To Reproduce**
1. ./vcpkg install cpp-netlib --triplet x64-windows
and: ./vcpkg install cpp-netlib --triplet x64-windows-static
2. add the following lines to CMakeLists.txt:

`find_package(cppnetlib CONFIG REQUIRED)`

`target_link_libraries(DEMO PRIVATE cppnetlib-uri cppnetlib-server-parsers cppnetlib-client-connections)`

**Failure logs** 

> Could not find a package configuration file provided by "cppnetlib" with
[cmake]   any of the following names:
[cmake] 
[cmake]     cppnetlibConfig.cmake
[cmake]     cppnetlib-config.cmake
[cmake] 
[cmake]   Add the installation prefix of "cppnetlib" to CMAKE_PREFIX_PATH or set
[cmake]   "cppnetlib_DIR" to a directory containing one of the above files.  If
[cmake]   "cppnetlib" provides a separate development package or SDK, be sure it has
[cmake]   been installed.

**Additional context**
Of course, I set the flag -DCMAKE_TOOLCHAIN_FILE=<path to vcpkg toolchain>

**Comment by edidada** [comment]
I also meet this problem

**Comment by edidada** [comment]
cppnetlibConfig.cmake file is exist,I thank configure error

**Comment by JackBoosY** [comment]
Confirmed, we need to rename _share/cpp-netlib_ to _share/cppnetlib_.

**Comment by JackBoosY** [comment]
Hi @stdor, thanks for reporting this issue.
I've fixed it, please update vcpkg and rebuild cpp-netlib.

Thanks.
