### ISSUE TITLE
Allow specify short license identifier

### ISSUE THREAD

**Issue by KindDragon** [microsoft/vcpkg#952]
I think it would be great if vcpkg llowed you to specify short license identifiers, such as GitHub displays in repository overview https://github.com/blog/2252-license-now-displayed-on-repository-overview
Some license identifiers https://spdx.org/licenses/

`vcpkg list` should display that identifier like in `conan info`:
```
$ conan info Hello/1.0@user/channel
The output will look like:

Hello/1.0@user/channel
    URL: http://...
    License: MIT
    Updates: Version not checked
    Required by:
        Project
    Requires:
        Hello0/0.1@user/channel
```

**Comment by PhoebeHui** [comment]
The license added, this issue can be closed, please reopen it if I misunderstand the issue here.
