### ISSUE TITLE
[ftgl] build failure

### ISSUE THREAD

**Issue by sma-github** [microsoft/vcpkg#9520]
**Host Environment**
- OS: Linux, Ubuntu 18.04
- Compiler: gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1) 

**To Reproduce**
`./vcpkg install ftgl`

**Failure logs** 
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
-- Building x64-linux-rel
CMake Error at scripts/cmake/vcpkg_fixup_cmake_targets.cmake:55 (message):
  '/home/xxxx/tmp/vcpkg/vcpkg/packages/ftgl_x64-linux/debug/cmake' does not
  exist.
Call Stack (most recent call first):
  ports/ftgl/portfile.cmake:19 (vcpkg_fixup_cmake_targets)
  scripts/ports.cmake:94 (include)

Error: Building package ftgl:x64-linux failed with: BUILD_FAILED
  Package: ftgl:x64-linux
  Vcpkg version: 2019.09.12-unknownhash-external

**Additional context**

**Comment by NancyLi1013** [comment]
Hi @sma-github thanks for posting this issue and also for your PR.
Since PR has been merged, I close this issue now.
