### ISSUE TITLE
box2d build failure

### ISSUE THREAD

**Issue by x0gundam** [microsoft/vcpkg#9525]
The following packages will be built and installed:
    box2d[core]:x64-windows
Starting package 1/1: box2d:x64-windows
Building package box2d[core]:x64-windows...
-- Note: box2d only supports static library linkage. Building static library.
-- Downloading https://github.com/erincatto/Box2D/archive/374664b2a4ce2e7c24fbad6e1ed34bebcc9ab6bc.tar.gz...
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:99 (message):

  File does not have expected hash:

          File path: [ D:/work/vcpkg/downloads/temp/erincatto-Box2D-374664b2a4ce2e7c24fbad6e1ed34bebcc9ab6bc.tar.gz ]
      Expected hash: [ 39074bab01b36104aa685bfe39b40eb903d9dfb54cc3ba8098125db5291f55a8a9e578fc59563b2e8743abbbb26f419be7ae1524e235e7bd759257f99ff96bda ]
        Actual hash: [ 89a46287a7dcb937d58454237d8ca0d3f5788bd544ccd045a282c38c7d197380fa5c5264c5dcfa9e19f250b3c9887dbe2252b188fc7ecc40b74ed241d7634650 ]

  The file may have been corrupted in transit.  This can be caused by
  proxies.  If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY
  environment variables to
  "https://user:password@your-proxy-ip-address:port/".

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:182 (test_hash)
  scripts/cmake/vcpkg_from_github.cmake:132 (vcpkg_download_distfile)
  ports/box2d/portfile.cmake:5 (vcpkg_from_github)
  scripts/ports.cmake:94 (include)

Error: Building package box2d:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: box2d:x64-windows
  Vcpkg version: 2019.09.12-nohash-external

Additionally, attach any relevant sections from the log files above.

**Comment by PhoebeHui** [comment]
Duplicated to https://github.com/microsoft/vcpkg/issues/9462
