### ISSUE TITLE
Can vcpkg use proxy server to download package?

### ISSUE THREAD

**Issue by junlinp** [microsoft/vcpkg#9527]
I need to use a proxy server to accelerate the download speed.So I want to know whether vcpkg support proxy connect?

**Comment by PhoebeHui** [comment]
@junlinp , you can use a proxy to download packages with setting the HTTPS_PROXY and HTTP_PROXY environment.

http://cmake.3232098.n2.nabble.com/ExternalProject-Add-and-proxy-td7591815.html

**Comment by PhoebeHui** [comment]
@junlinp, feel free reopen this issue if it still be a problem for you.
