### ISSUE TITLE
I build Poco 64-windows success,Cmake report error

### ISSUE THREAD

**Issue by edidada** [microsoft/vcpkg#9528]
put 

    find_package(Poco CONFIG REQUIRED)
    # Note: 12 target(s) were omitted.
    target_link_libraries(main PRIVATE Poco::Net Poco::XML Poco::Zip Poco::Data)

in CmakeFiles.txt

run

"D:\Program Files\CMake\bin\cmake.exe" ..  -A x64 -DCMAKE_TOOLCHAIN_FILE="D:\vcpkg\scripts\buildsystems\vcpkg.cmake"
-- Building for: Visual Studio 16 2019
-- The C compiler identification is MSVC 19.23.28106.4
-- The CXX compiler identification is MSVC 19.23.28106.4
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.23.28105/bin/Hostx64/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.23.28105/bin/Hostx64/x64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.23.28105/bin/Hostx64/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.23.28105/bin/Hostx64/x64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found ZLIB: optimized;D:/vcpkg/installed/x64-windows/lib/zlib.lib;debug;D:/vcpkg/installed/x64-windows/debug/lib/zlibd.lib (found version "1.2.11")
-- Found OpenSSL: D:/vcpkg/installed/x64-windows/debug/lib/libeay32.lib (found version "1.0.2s")
CMake Error at D:/vcpkg/scripts/buildsystems/vcpkg.cmake:263 (_find_package):
  Found package configuration file:

    D:/vcpkg/installed/x64-windows/share/poco/PocoConfig.cmake

  but it set Poco_FOUND to FALSE so package "Poco" is considered to be NOT
  FOUND.  Reason given by package:

  The Poco package requires at least one component

Call Stack (most recent call first):
  CMakeLists.txt:31 (find_package)

PocoConfig.cmake related content
if (NOT Poco_FIND_COMPONENTS)
    set(Poco_NOT_FOUND_MESSAGE "The Poco package requires at least one component")
    set(Poco_FOUND False)
    return()
endif()

**Comment by JackBoosY** [comment]
@edidada Does this issue resolved?

**Comment by pkeir** [comment]
It's not obvious from the message, but you actually need to add the individual Poco components you require, without the double colons(!): say: `find_package(Poco CONFIG REQUIRED Net XML Zip Data)`.
