### ISSUE TITLE
MSVC 2017 Intellisense does not find headers for Individual Project integration

### ISSUE THREAD

**Issue by DVMirchev** [Microsoft/vcpkg#953]
Hello 

I installed VCPKG on two machines - one with User-wide integration and one with Individual Project integration - and installed a lot of libraries (around 20). On both machines everything works fine - everything compiles, links and runs fine.

On the User-wide integration machine when I type:

#include <

the Intellisense finds all include files from VCPKG.and starts suggesting proper headers.

On the Individual Project integration machine, this does not happen. 

The compiler manages to find headers and compiles everything. The issue is only with Intellisense. 

Great tool! Keep up the good work - it feels liberating to not think about building and integrating all those libraries only to try them.

Best Regards,
Dimitar

**Comment by ras0219-msft** [comment]
Hey @DVMirchev!

I tried to reproduce this on my machine but was unsuccessful. Could you send us the project file at vcpkg@microsoft.com?

Glad vcpkg is working well for you 😄!
