### ISSUE TITLE
Error: Building package openssl-windows:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by timtimtam** [microsoft/vcpkg#9532]
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: nmake -f ms\ntdll.mak install
    Working Directory: C:/dev/vcpkg-github/buildtrees/openssl-windows/x64-windows-rel
    Error code: 2
    See logs for more information:
      C:\dev\vcpkg-github\buildtrees\openssl-windows\build-x64-windows-rel-1-out.log
      C:\dev\vcpkg-github\buildtrees\openssl-windows\build-x64-windows-rel-1-err.log

Call Stack (most recent call first):
  ports/openssl-windows/portfile.cmake:119 (vcpkg_execute_required_process)
  scripts/ports.cmake:94 (include)

Error: Building package openssl-windows:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: openssl-windows:x64-windows
  Vcpkg version: 2019.09.12-nohash

Additionally, attach any relevant sections from the log files above.

**Comment by timtimtam** [comment]
c:\dev\vcpkg-github>.\vcpkg update
Using local portfile versions. To update the local portfiles, use `git pull`.
No packages need updating.

**Comment by PhoebeHui** [comment]
@timtimtam , could you provide us failure log C:\dev\vcpkg-github\buildtrees\openssl-windows\build-x64-windows-rel-1-out.log?

I can't repro this issue:

PS F:\vcpkg\src> ./vcpkg install openssl-windows:x64-windows
Your feedback is important to improve Vcpkg! Please take 3 minutes to complete our survey by running: vcpkg contact --survey
The following packages will be built and installed:
    openssl-windows[core]:x64-windows
Starting package 1/1: openssl-windows:x64-windows
Building package openssl-windows[core]:x64-windows...
-- Using cached F:/VCPKG/src/downloads/openssl-1.0.2s.tar.gz
-- Using source at F:/VCPKG/src/buildtrees/openssl-windows/src/openssl-1-c41872ef97
-- Copying openssl release source files...
-- Copying openssl release source files... done
-- Configure x64-windows-rel
-- Configure x64-windows-rel done
-- Build x64-windows-rel
-- Build x64-windows-rel done
-- Copying openssl debug source files...
-- Copying openssl debug source files... done
-- Configure x64-windows-dbg
-- Configure x64-windows-dbg done
-- Build x64-windows-dbg
-- Build x64-windows-dbg done
-- Installing: F:/VCPKG/src/packages/openssl-windows_x64-windows/share/openssl-windows/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package openssl-windows[core]:x64-windows... done
Installing package openssl-windows[core]:x64-windows...
Installing package openssl-windows[core]:x64-windows... done
Elapsed time for package openssl-windows:x64-windows: 9.788 min

Total elapsed time: 9.788 min

The package openssl is compatible with built-in CMake targets:

    find_package(OpenSSL REQUIRED)
    target_link_libraries(main PRIVATE OpenSSL::SSL OpenSSL::Crypto)

**Comment by PhoebeHui** [comment]
@timtimtam, please reopen it and attach failure logs if it still be a problem for you.
