### ISSUE TITLE
[uWebSockets] update to 0.17.0 alpha 4

### ISSUE THREAD

**Issue by Slowair6** [microsoft/vcpkg#9533]
Library name: uWebSockets

New version number: 0.17.0 alpha 4

Other information that may be useful (release notes, etc...)
I ran into ERROR #C2664 and alexhultman (the library dev) suggest that I ask VCPKG to update the library version.

**Comment by NancyLi1013** [comment]
Hi @Slowair6 thanks for posting this issue.
I have update this port in PR #9535 .
Could you help confirm if this can work for you?

**Comment by Slowair6** [comment]
> Hi @Slowair6 thanks for posting this issue.
> I have update this port in PR #9535 .
> Could you help confirm if this can work for you?

Sorry for the late reply, yes it's work now thank you very much.

**Comment by NancyLi1013** [comment]
Thanks for your reply.
Since this PR has been merged, I close this issue now.
