### ISSUE TITLE
Add checker for ports and cmake scripts

### ISSUE THREAD

**Issue by Pospelove** [microsoft/vcpkg#9539]
****

**Is your feature request related to a problem? Please describe.**
While portfile writing practices evolve, portfiles that have no update for a long time obviously stay the same. For example, it's no longer needed to use `include(vcpkg_common_functions.cmake)`, but many ports are using it.

`scripts/cmake` contents also could be checked automatically to ensure that examples really contain usage of a function.

**Proposed solution**
Add a simple script or command that checks `portfile,cmake` of all or only specified ports and shows it follows best practices or not. And do fixes automatically when possible.

**Additional context**
See my PRs #9484 #9480 where I waste reviewer's time to removing vcpkg_common_functions instead of just type a command and fix warnings before opening the Pull Request.

**Comment by JackBoosY** [comment]
I think it's not needed now, because our template was updated.
