### ISSUE TITLE
ffmpeg does not build due to msys problems

### ISSUE THREAD

**Issue by ismail** [Microsoft/vcpkg#954]
This is with vcpkg git master on Windows 10 Creators Update x64:

latte C:\src\vcpkg > .\vcpkg.exe install ffmpeg --triplet x64-windows
The following packages will be built and installed:
    ffmpeg:x64-windows
Building package ffmpeg:x64-windows...
-- CURRENT_INSTALLED_DIR=C:/src/vcpkg/installed/x64-windows
-- DOWNLOADS=C:/src/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=C:/src/vcpkg/packages/ffmpeg_x64-windows
-- CURRENT_BUILDTREES_DIR=C:/src/vcpkg/buildtrees/ffmpeg
-- CURRENT_PORT_DIR=C:/src/vcpkg/ports/ffmpeg/.
-- Downloading http://ffmpeg.org/releases/ffmpeg-3.2.4.tar.bz2...
-- Downloading http://ffmpeg.org/releases/ffmpeg-3.2.4.tar.bz2... OK
-- Testing integrity of downloaded file...
-- Testing integrity of downloaded file... OK
-- Extracting source C:/src/vcpkg/downloads/ffmpeg-3.2.4.tar.bz2
-- Extracting done
-- Building ffmpeg for Release
     13 [main] bash (13536) C:\src\vcpkg\downloads\tools\msys2\msys32\usr\bin\bash.exe: *** fatal error - cygheap base mismatch detected - 0x1365408/0x12F5408.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
[...]

The first thing I noticed is msys i686 is downloaded even on x64. 32bit builds are more suspect to heap mismatches due to limited adress space. Also the version of msys2 downloaded is really old.

**Comment by Mixaill** [comment]
Also, MSYS2 project recommends to use 64-bit.

https://github.com/msys2/msys2/wiki/MSYS2-installation

>Note: if you are using 64-bit Windows, there is no reason to use 32-bit MSYS2. Well, to be honest, there is one reason: you want to develop MSYS2 software (or contribute to MSYS2-packages) and want to test that the software/package also works on 32-bit MSYS2. When it comes to native software, 64-bit MSYS2 can be used to build, install and run both 32-bit and 64-bit variants. 64-bit MSYS2 software (practically speaking) never needs to be "re-based", giving a better user experience.
