### ISSUE TITLE
[libfreenect2] need opengl, opencl, cuda support

### ISSUE THREAD

**Issue by lyhyl** [microsoft/vcpkg#9540]
****

**Is your feature request related to a problem? Please describe.**
Currently, install libfreenect2 from vcpkg only support CpuPacketPipeline, which has really low performance. Need opengl, opencl, cuda support.

**Proposed solution**
Add opengl, opencl, cuda support.

**Describe alternatives you've considered**
Compile libfreenect2 myself.

**Additional context**
not applicable

**Comment by lyhyl** [comment]
@JackBoosY Do we have to support all triplets?
32-bit support is gradually being deprecated/removed from CUDA. x86-windows is not supported.

**Comment by JackBoosY** [comment]
@lyhyl If CUDA officially gives up support for 32-bit Windows, we will follow them.

**Comment by MonicaLiu0311** [comment]
Fixed by #9551.
