### ISSUE TITLE
[New Port Request] <TDLib>

### ISSUE THREAD

**Issue by ghost** [microsoft/vcpkg#9545]
**Library name:** tdlib

**Library description:** telegram client library

**Source repository URL:** https://github.com/tdlib/td

**Project homepage (if different from the source repository):** https://core.telegram.org/tdlib

**Anything else that is useful to know when adding (such as optional features the library may have that should be included):**

TDLib depends on:

    C++14 compatible compiler (Clang 3.4+, GCC 4.9+, MSVC 19.0+ (Visual Studio 2015+), Intel C++ Compiler 17+)
    OpenSSL
    zlib
    gperf (build only)
    CMake (3.0.2+, build only)
    PHP (optional, for documentation generation)
    Doxygen (optional, for documentation generation)

**Comment by PhoebeHui** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
