### ISSUE TITLE
[boost-compatibility] build failure

### ISSUE THREAD

**Issue by yihongyishui** [microsoft/vcpkg#9549]
**Host Environment**
- OS: WIN 10
- Compiler: revision

**To Reproduce**
`./vcpkg install boost-compatibility`

Call Stack (most recent call first):
  installed/x64-windows/share/boost-vcpkg-helpers/boost-modular-headers.cmake:17 (vcpkg_download_distfile)
  ports/boost-compatibility/portfile.cmake:14 (boost_modular_headers)
  scripts/ports.cmake:94 (include)

Error: Building package boost-compatibility:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-compatibility:x64-windows
  Vcpkg version: 2019.09.12-nohash

Additionally, attach any relevant sections from the log files above.

**Failure logs** 
-Cut and past the appropriate build messages from the console output.
-Please attach any additional failure logs mentioned in the console output.

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by PhoebeHui** [comment]
@yihongyishui , I can't repro this issue. From your failure log, it seems that failed with vcpkg_download_distfile step, could you double confirm if you can download https://raw.githubusercontent.com/boostorg/boost/boost-1.71.0/LICENSE_1_0.txt?

For me:
Starting package 2/2: boost-compatibility:x86-windows
Building package boost-compatibility[core]:x86-windows...
-- Downloading https://github.com/boostorg/compatibility/archive/boost-1.71.0.tar.gz...
-- Extracting source F:/VCPKG/boost/vcpkg/downloads/boostorg-compatibility-boost-1.71.0.tar.gz
-- Using source at F:/VCPKG/boost/vcpkg/buildtrees/boost-compatibility/src/ost-1.71.0-d69e2f6205
-- Packaging headers
-- Packaging headers done
-- Downloading https://raw.githubusercontent.com/boostorg/boost/boost-1.71.0/LICENSE_1_0.txt...
-- Installing: F:/VCPKG/boost/vcpkg/packages/boost-compatibility_x86-windows/share/boost-compatibility/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package boost-compatibility[core]:x86-windows... done
Installing package boost-compatibility[core]:x86-windows...
Installing package boost-compatibility[core]:x86-windows... done
Elapsed time for package boost-compatibility:x86-windows: 2.073 s

Total elapsed time: 35.36 s

**Comment by vanturman** [comment]
@yihongyishui i am facing the same problem with you. Have you solved this problem of vcpkg when installing folly?

**Comment by PhoebeHui** [comment]
@vanturman, does it fail with vcpkg_download_distfile step for you? could you double confirm if you can download https://raw.githubusercontent.com/boostorg/boost/boost-1.71.0/LICENSE_1_0.txt

**Comment by yihongyishui** [comment]
> @yihongyishui i am facing the same problem with you. Have you solved this problem of vcpkg when installing folly?

 "vcpkg\ports\opengl\portfile.cmake"

```c
vcpkg_get_program_files_32_bit(PROGRAM_FILES_32_BIT)
vcpkg_get_windows_sdk(WINDOWS_SDK)

if (WINDOWS_SDK MATCHES "10.")
    set(LIBGLFILEPATH  "${PROGRAM_FILES_32_BIT}\\Windows Kits\\10\\Lib\\${WINDOWS_SDK}\\um\\${TRIPLET_SYSTEM_ARCH}\\OpenGL32.Lib")
    set(LIBGLUFILEPATH "${PROGRAM_FILES_32_BIT}\\Windows Kits\\10\\Lib\\${WINDOWS_SDK}\\um\\${TRIPLET_SYSTEM_ARCH}\\GlU32.Lib")
    set(HEADERSPATH    "${PROGRAM_FILES_32_BIT}\\Windows Kits\\10\\Include\\${WINDOWS_SDK}\\um")
elseif(WINDOWS_SDK MATCHES "8.")
    set(LIBGLFILEPATH  "${PROGRAM_FILES_32_BIT}\\Windows Kits\\8.1\\Lib\\winv6.3\\um\\${TRIPLET_SYSTEM_ARCH}\\OpenGL32.Lib")
    set(LIBGLUFILEPATH "${PROGRAM_FILES_32_BIT}\\Windows Kits\\8.1\\Lib\\winv6.3\\um\\${TRIPLET_SYSTEM_ARCH}\\GlU32.Lib")
    set(HEADERSPATH    "${PROGRAM_FILES_32_BIT}\\Windows Kits\\8.1\\Include\\um")
else()
    message(FATAL_ERROR "Portfile not yet configured for Windows SDK with version: ${WINDOWS_SDK}")
endif()
```
reviewed：

```c
    GET_FILENAME_COMPONENT(SDK_PATH "[HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows Kits\\Installed Roots;KitsRoot10]" ABSOLUTE CACHE)
    vcpkg_get_windows_sdk(WINDOWS_SDK)

    if (WINDOWS_SDK MATCHES "10.")
        set(LIBGLFILEPATH  "${SDK_PATH}\\Lib\\${WINDOWS_SDK}\\um\\${TRIPLET_SYSTEM_ARCH}\\OpenGL32.Lib")
        set(LIBGLUFILEPATH "${SDK_PATH}\\Lib\\${WINDOWS_SDK}\\um\\${TRIPLET_SYSTEM_ARCH}\\GlU32.Lib")
        set(HEADERSPATH    "${SDK_PATH}\\Include\\${WINDOWS_SDK}\\um")
    elseif(WINDOWS_SDK MATCHES "8.")
        set(LIBGLFILEPATH  "${SDK_PATH}\\Lib\\winv6.3\\um\\${TRIPLET_SYSTEM_ARCH}\\OpenGL32.Lib")
        set(LIBGLUFILEPATH "${SDK_PATH}\\Lib\\winv6.3\\um\\${TRIPLET_SYSTEM_ARCH}\\GlU32.Lib")
        set(HEADERSPATH    "${SDK_PATH}\\Include\\um")
    else()
        message(FATAL_ERROR "Portfile not yet configured for Windows SDK with version: ${WINDOWS_SDK}")
    endif()
```

**Comment by yihongyishui** [comment]
Just try it again. but rewriten a file @vanturman 
 "vcpkg\ports\opengl\portfile.cmake"

```c
vcpkg_get_program_files_32_bit(PROGRAM_FILES_32_BIT)
vcpkg_get_windows_sdk(WINDOWS_SDK)

if (WINDOWS_SDK MATCHES "10.")
    set(LIBGLFILEPATH  "${PROGRAM_FILES_32_BIT}\\Windows Kits\\10\\Lib\\${WINDOWS_SDK}\\um\\${TRIPLET_SYSTEM_ARCH}\\OpenGL32.Lib")
    set(LIBGLUFILEPATH "${PROGRAM_FILES_32_BIT}\\Windows Kits\\10\\Lib\\${WINDOWS_SDK}\\um\\${TRIPLET_SYSTEM_ARCH}\\GlU32.Lib")
    set(HEADERSPATH    "${PROGRAM_FILES_32_BIT}\\Windows Kits\\10\\Include\\${WINDOWS_SDK}\\um")
elseif(WINDOWS_SDK MATCHES "8.")
    set(LIBGLFILEPATH  "${PROGRAM_FILES_32_BIT}\\Windows Kits\\8.1\\Lib\\winv6.3\\um\\${TRIPLET_SYSTEM_ARCH}\\OpenGL32.Lib")
    set(LIBGLUFILEPATH "${PROGRAM_FILES_32_BIT}\\Windows Kits\\8.1\\Lib\\winv6.3\\um\\${TRIPLET_SYSTEM_ARCH}\\GlU32.Lib")
    set(HEADERSPATH    "${PROGRAM_FILES_32_BIT}\\Windows Kits\\8.1\\Include\\um")
else()
    message(FATAL_ERROR "Portfile not yet configured for Windows SDK with version: ${WINDOWS_SDK}")
endif()
```
修改为：

```c
    GET_FILENAME_COMPONENT(SDK_PATH "[HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows Kits\\Installed Roots;KitsRoot10]" ABSOLUTE CACHE)
    vcpkg_get_windows_sdk(WINDOWS_SDK)

    if (WINDOWS_SDK MATCHES "10.")
        set(LIBGLFILEPATH  "${SDK_PATH}\\Lib\\${WINDOWS_SDK}\\um\\${TRIPLET_SYSTEM_ARCH}\\OpenGL32.Lib")
        set(LIBGLUFILEPATH "${SDK_PATH}\\Lib\\${WINDOWS_SDK}\\um\\${TRIPLET_SYSTEM_ARCH}\\GlU32.Lib")
        set(HEADERSPATH    "${SDK_PATH}\\Include\\${WINDOWS_SDK}\\um")
    elseif(WINDOWS_SDK MATCHES "8.")
        set(LIBGLFILEPATH  "${SDK_PATH}\\Lib\\winv6.3\\um\\${TRIPLET_SYSTEM_ARCH}\\OpenGL32.Lib")
        set(LIBGLUFILEPATH "${SDK_PATH}\\Lib\\winv6.3\\um\\${TRIPLET_SYSTEM_ARCH}\\GlU32.Lib")
        set(HEADERSPATH    "${SDK_PATH}\\Include\\um")
    else()
        message(FATAL_ERROR "Portfile not yet configured for Windows SDK with version: ${WINDOWS_SDK}")
    endif()
```

**Comment by vanturman** [comment]
Thanks a lot，it works for me!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Jihao Liu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月19日(星期三) 晚上9:17
收件人:&nbsp;"microsoft/vcpkg"<vcpkg@noreply.github.com&gt;;
抄送:&nbsp;""<handong.yang@foxmail.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [microsoft/vcpkg] [boost-compatibility] build failure (#9549)




Just try it again. but rewriten a file @vanturman
 "vcpkg\ports\opengl\portfile.cmake"
 vcpkg_get_program_files_32_bit(PROGRAM_FILES_32_BIT) vcpkg_get_windows_sdk(WINDOWS_SDK) if (WINDOWS_SDK MATCHES "10.")     set(LIBGLFILEPATH  "${PROGRAM_FILES_32_BIT}\\Windows Kits\\10\\Lib\\${WINDOWS_SDK}\\um\\${TRIPLET_SYSTEM_ARCH}\\OpenGL32.Lib")     set(LIBGLUFILEPATH "${PROGRAM_FILES_32_BIT}\\Windows Kits\\10\\Lib\\${WINDOWS_SDK}\\um\\${TRIPLET_SYSTEM_ARCH}\\GlU32.Lib")     set(HEADERSPATH    "${PROGRAM_FILES_32_BIT}\\Windows Kits\\10\\Include\\${WINDOWS_SDK}\\um") elseif(WINDOWS_SDK MATCHES "8.")     set(LIBGLFILEPATH  "${PROGRAM_FILES_32_BIT}\\Windows Kits\\8.1\\Lib\\winv6.3\\um\\${TRIPLET_SYSTEM_ARCH}\\OpenGL32.Lib")     set(LIBGLUFILEPATH "${PROGRAM_FILES_32_BIT}\\Windows Kits\\8.1\\Lib\\winv6.3\\um\\${TRIPLET_SYSTEM_ARCH}\\GlU32.Lib")     set(HEADERSPATH    "${PROGRAM_FILES_32_BIT}\\Windows Kits\\8.1\\Include\\um") else()     message(FATAL_ERROR "Portfile not yet configured for Windows SDK with version: ${WINDOWS_SDK}") endif()
 
修改为：
     GET_FILENAME_COMPONENT(SDK_PATH "[HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows Kits\\Installed Roots;KitsRoot10]" ABSOLUTE CACHE)     vcpkg_get_windows_sdk(WINDOWS_SDK)     if (WINDOWS_SDK MATCHES "10.")         set(LIBGLFILEPATH  "${SDK_PATH}\\Lib\\${WINDOWS_SDK}\\um\\${TRIPLET_SYSTEM_ARCH}\\OpenGL32.Lib")         set(LIBGLUFILEPATH "${SDK_PATH}\\Lib\\${WINDOWS_SDK}\\um\\${TRIPLET_SYSTEM_ARCH}\\GlU32.Lib")         set(HEADERSPATH    "${SDK_PATH}\\Include\\${WINDOWS_SDK}\\um")     elseif(WINDOWS_SDK MATCHES "8.")         set(LIBGLFILEPATH  "${SDK_PATH}\\Lib\\winv6.3\\um\\${TRIPLET_SYSTEM_ARCH}\\OpenGL32.Lib")         set(LIBGLUFILEPATH "${SDK_PATH}\\Lib\\winv6.3\\um\\${TRIPLET_SYSTEM_ARCH}\\GlU32.Lib")         set(HEADERSPATH    "${SDK_PATH}\\Include\\um")     else()         message(FATAL_ERROR "Portfile not yet configured for Windows SDK with version: ${WINDOWS_SDK}")     endif()

**Comment by PhoebeHui** [comment]
@yihongyishui, thanks for your updates!

I'm not clear the relationship between the build failures and solution, however, it's good to know that works for you, @vanturman.

**Comment by yihongyishui** [comment]
It is possible because the vcpkg is not installed in the system disk.

**Comment by JordiGR-TheBreachStudios** [comment]
Hi,

I'm facing the same problem. I found out that any access to https://raw.githubusercontent.com is blocked by our corporate network, for security reasons.
Could the boost-compatibility package be built without needing to download the file https://raw.githubusercontent.com/boostorg/boost/boost-1.72.0/LICENSE_1_0.txt?
Any manual modification to some config file is not an option, since the solution needs to work with any CI/CD setup.

Thank you

**Comment by PhoebeHui** [comment]
The license file is needed, as a workaound you can download that file, rename to boost_LICENSE_1_0.txt, and copy to vcpkg\download folder in setting up steps.

Duplicated to https://github.com/microsoft/vcpkg/issues/11627.

**Comment by chatyan** [comment]
Got the same problem with boost

D:\Work 2019\GIT Code\vcpkg>.\vcpkg install pcl
Computing installation plan...
The following packages will be built and installed:
  * boost-algorithm[core]:x86-windows
  * boost-any[core]:x86-windows
  * boost-array[core]:x86-windows
  * boost-asio[core]:x86-windows
  * boost-assert[core]:x86-windows
  * boost-atomic[core]:x86-windows
  * boost-bimap[core]:x86-windows
  * boost-bind[core]:x86-windows
  * boost-build[core]:x86-windows
  * boost-chrono[core]:x86-windows
  * boost-circular-buffer[core]:x86-windows
  * boost-compatibility[core]:x86-windows
  * boost-concept-check[core]:x86-windows
  * boost-config[core]:x86-windows
  * boost-container[core]:x86-windows
  * boost-container-hash[core]:x86-windows
  * boost-context[core]:x86-windows
  * boost-conversion[core]:x86-windows
  * boost-core[core]:x86-windows
  * boost-coroutine[core]:x86-windows
  * boost-date-time[core]:x86-windows
  * boost-detail[core]:x86-windows
  * boost-dynamic-bitset[core]:x86-windows
  * boost-endian[core]:x86-windows
  * boost-exception[core]:x86-windows
  * boost-filesystem[core]:x86-windows
  * boost-foreach[core]:x86-windows
  * boost-format[core]:x86-windows
  * boost-function[core]:x86-windows
  * boost-function-types[core]:x86-windows
  * boost-functional[core]:x86-windows
  * boost-fusion[core]:x86-windows
  * boost-graph[core]:x86-windows
  * boost-integer[core]:x86-windows
  * boost-interprocess[core]:x86-windows
  * boost-intrusive[core]:x86-windows
  * boost-io[core]:x86-windows
  * boost-iostreams[core]:x86-windows
  * boost-iterator[core]:x86-windows
  * boost-lambda[core]:x86-windows
  * boost-lexical-cast[core]:x86-windows
  * boost-locale[core]:x86-windows
  * boost-math[core]:x86-windows
  * boost-modular-build-helper[core]:x86-windows
  * boost-move[core]:x86-windows
  * boost-mp11[core]:x86-windows
  * boost-mpl[core]:x86-windows
  * boost-multi-array[core]:x86-windows
  * boost-multi-index[core]:x86-windows
  * boost-multiprecision[core]:x86-windows
  * boost-numeric-conversion[core]:x86-windows
  * boost-optional[core]:x86-windows
  * boost-parameter[core]:x86-windows
  * boost-phoenix[core]:x86-windows
  * boost-pool[core]:x86-windows
  * boost-predef[core]:x86-windows
  * boost-preprocessor[core]:x86-windows
  * boost-property-map[core]:x86-windows
  * boost-property-tree[core]:x86-windows
  * boost-proto[core]:x86-windows
  * boost-ptr-container[core]:x86-windows
  * boost-random[core]:x86-windows
  * boost-range[core]:x86-windows
  * boost-ratio[core]:x86-windows
  * boost-rational[core]:x86-windows
  * boost-regex[core]:x86-windows
  * boost-serialization[core]:x86-windows
  * boost-signals2[core]:x86-windows
  * boost-smart-ptr[core]:x86-windows
  * boost-spirit[core]:x86-windows
  * boost-static-assert[core]:x86-windows
  * boost-system[core]:x86-windows
  * boost-test[core]:x86-windows
  * boost-thread[core]:x86-windows
  * boost-throw-exception[core]:x86-windows
  * boost-tokenizer[core]:x86-windows
  * boost-tti[core]:x86-windows
  * boost-tuple[core]:x86-windows
  * boost-type-index[core]:x86-windows
  * boost-type-traits[core]:x86-windows
  * boost-typeof[core]:x86-windows
  * boost-unordered[core]:x86-windows
  * boost-utility[core]:x86-windows
  * boost-uuid[core]:x86-windows
  * boost-variant[core]:x86-windows
  * boost-winapi[core]:x86-windows
  * boost-xpressive[core]:x86-windows
  * bzip2[core]:x86-windows
  * curl[core,non-http,ssl,sspi,winssl]:x86-windows
  * double-conversion[core]:x86-windows
  * eigen3[core]:x86-windows
  * expat[core]:x86-windows
  * flann[core]:x86-windows
  * freetype[bzip2,core,png]:x86-windows
  * glew[core]:x86-windows
  * hdf5[core,szip,zlib]:x86-windows
  * jsoncpp[core]:x86-windows
  * libharu[core,notiffsymbols]:x86-windows
  * libiconv[core]:x86-windows
  * libjpeg-turbo[core]:x86-windows
  * liblzma[core]:x86-windows
  * libogg[core]:x86-windows
  * libpng[core]:x86-windows
  * libtheora[core]:x86-windows
  * libxml2[core]:x86-windows
  * lz4[core]:x86-windows
  * netcdf-c[core]:x86-windows
  * openssl[core]:x86-windows
  * openssl-windows[core]:x86-windows
    pcl[core]:x86-windows
  * pegtl-2[core]:x86-windows
  * proj4[core,database]:x86-windows
  * pugixml[core]:x86-windows
  * qhull[core]:x86-windows
  * sqlite3[core,tool]:x86-windows
  * szip[core]:x86-windows
  * tiff[core]:x86-windows
  * utfcpp[core]:x86-windows
  * vtk[core]:x86-windows
  * xxhash[core]:x86-windows
  * zlib[core]:x86-windows
  * zstd[core]:x86-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/122: boost-compatibility:x86-windows
Building package boost-compatibility[core]:x86-windows...
-- Using cached D:/Work 2019/GIT Code/vcpkg/downloads/boostorg-compatibility-boost-1.73.0.tar.gz
-- Using source at D:/Work 2019/GIT Code/vcpkg/buildtrees/boost-compatibility/src/ost-1.73.0-44642da97c
-- Packaging headers
-- Packaging headers done
-- Using cached D:/Work 2019/GIT Code/vcpkg/downloads/boost_LICENSE_1_0.txt
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:99 (message):


  File does not have expected hash:

          File path: [ D:/Work 2019/GIT Code/vcpkg/downloads/boost_LICENSE_1_0.txt ]
      Expected hash: [ d6078467835dba8932314c1c1e945569a64b065474d7aced27c9a7acc391d52e9f234138ed9f1aa9cd576f25f12f557e0b733c14891d42c16ecdc4a7bd4d60b8 ]
        Actual hash: [ b3e1ca08971b1c3e8cb11a854d094cea3a5fd2c95cf9e985b5212a4bde7975cc3ae15455e8d9e7dc3f2a47b1285b0a34798fc6e194d4ec2db4ceb76547bf07bb ]

  Please delete the file and retry if this file should be downloaded again.

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:110 (test_hash)
  installed/x86-windows/share/boost-vcpkg-helpers/boost-modular-headers.cmake:17 (vcpkg_download_distfile)
  ports/boost-compatibility/portfile.cmake:12 (boost_modular_headers)
  scripts/ports.cmake:76 (include)


Error: Building package boost-compatibility:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-compatibility:x86-windows
  Vcpkg version: 2020.02.04-nohash

Additionally, attach any relevant sections from the log files above.

**Comment by thouger** [comment]
same problem,download boost_LICENSE_1_0.txt is can work.
