### ISSUE TITLE
[libvpx] build failure

### ISSUE THREAD

**Issue by longnguyen2004** [microsoft/vcpkg#9553]
**Host Environment**
- OS: Windows
- Compiler: MSVC 19.24.28314

**To Reproduce**
`./vcpkg install libvpx`

**Failure logs** 
Starting package 2/4: libvpx:x64-windows
Building package libvpx[core]:x64-windows...
-- Note: libvpx only supports static library linkage. Building static library.
-- Using cached C:/vcpkg/downloads/libvpx-1.8.1.tar.gz
-- Using source at C:/vcpkg/buildtrees/libvpx/src/libvpx-1-87e9c0e1cf
-- Acquiring MSYS Packages...
-- Acquiring MSYS Packages... OK
-- Acquiring MSYS Packages...
-- Acquiring MSYS Packages... OK
-- PERL_EXE_PATH ; C:/vcpkg/downloads/tools/perl/perl/bin
-- Generating makefile
-- Generating MSBuild projects
-- Building C:/vcpkg/buildtrees/libvpx/x64-windows/vpx.vcxproj for Release
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: msbuild C:/vcpkg/buildtrees/libvpx/x64-windows/vpx.vcxproj /p:Configuration=Release /t:Rebuild /p:Platform=x64 /p:PlatformToolset=v142 /p:VCPkgLocalAppDataDisabled=true /p:UseIntelMKL=No /p:WindowsTargetPlatformVersion=10.0.19025.0 /m /p:WholeProgramOptimization=false
    Working Directory: C:/vcpkg/buildtrees/libvpx/x64-windows-rel
    Error code: 1
    See logs for more information:
      C:\vcpkg\buildtrees\libvpx\build-x64-windows-rel-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_msbuild.cmake:119 (vcpkg_execute_required_process)
  ports/libvpx/portfile.cmake:73 (vcpkg_build_msbuild)
  scripts/ports.cmake:94 (include)

[build-x64-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/4021718/build-x64-windows-rel-out.log)

**Additional context**
Seems like the build process can't find yasm, even though I've added it to PATH

**Comment by JackBoosY** [comment]
@longnguyen2004 Thanks for reporting this issue.
Could you provide the configure log _C:\vcpkg\buildtrees\libvpx\configure-x64-windows-out.log_ ?

Thanks.

**Comment by longnguyen2004** [comment]
Current workaround: patch the generator script to include the full path to the yasm binary
I'll checkout master again to get the error

**Comment by JackBoosY** [comment]
yasm should be installed first in _VCPKG_PATH/downloads/tools/yasm_, so I think you may installed yasm manually.

**Comment by longnguyen2004** [comment]
Nope I didn't, I let vcpkg download it. But I noticed that yasm is contained inside a versioned subfolder (VCPKG_PATH\downloads\tools\yasm\1.3.0.6). Don't know if that affects the configure process or not

[configure-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/4035979/configure-x64-windows-out.log)

Here's the configure log, looks alright I think. I've tried adding the yasm dir to PATH but that doesn't seem to change anything. I even tried manually building the generated project in VS but no luck

**Comment by JackBoosY** [comment]
@dan-shaw Could you have a look?
Thanks.

**Comment by longnguyen2004** [comment]
Probably just a problem with my previous Windows installation, upgraded to Windows 10 and everything seems good

**Comment by Voskrese** [comment]
@JackBoosY 
MSBuild not find yasm in folder VCPKG_PATH\downloads\tools\yasm\1.3.0.6

readme file 

> 
>     [1]: http://www.tortall.net/projects/yasm
>     [2]: For Visual Studio the base yasm binary (not vsyasm) should be in the
>          PATH for Visual Studio. For VS2017 it is sufficient to rename
>          yasm-<version>-<arch>.exe to yasm.exe and place it in:
>          Program Files (x86)/Microsoft Visual Studio/2017/<level>/Common7/Tools/

copy msvc2019 yasm binary, build ok

`Microsoft Visual Studio\2019\Enterprise\Common7\Tools
`

**Comment by maddinthegreat** [comment]
On VS2019 and look into "Current" folder like:

**C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin**

Place yasm.exe there.

Regards

**Comment by Voskrese** [comment]
@maddinthegreat 
https://github.com/microsoft/vcpkg/pull/10952/commits/7185c476ae3a169a106d0d4e86a1772387b2c1c9

https://github.com/microsoft/vcpkg/pull/10952/commits/4a62f86d6b61461739359c24d2905c0713d83a0e

add `/p:UseEnv=True`

?

**Comment by maddinthegreat** [comment]
@Voskrese: have to use msbuild in "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin" explicitly.
Regards
