### ISSUE TITLE
Can't build any package - cmake fails with error - Windows 10

### ISSUE THREAD

**Issue by simonbjork** [microsoft/vcpkg#9554]
I've been trying to use vcpkg without any luck for a long time. On my two main workstations, nothing works. However when I tried on a third computer it all works as expected, doing exactly the same thing.

Here's what I do:

- Install Visual Studio Community (tested both 2019 and 2017)
- Download vcpkg (clone via git).
- Run bootstrap-vcpkg.bat (successfully)

When I try to install a package (any package) I get the same error. I have access to the C: drive, I have admin priviliges etc. 

```
PS C:\Users\Simon> cd .\vcpkg\
PS C:\Users\Simon\vcpkg> .\vcpkg.exe install gainput:x64-windows
Your feedback is important to improve Vcpkg! Please take 3 minutes to complete our survey by running: vcpkg contact --survey
The following packages will be built and installed:
    gainput[core]:x64-windows
Starting package 1/1: gainput:x64-windows
Building package gainput[core]:x64-windows...
-- Using cached C:/Users/Simon/vcpkg/downloads/jkuhlmann-gainput-v1.0.0.tar.gz
-- Using source at C:/Users/Simon/vcpkg/buildtrees/gainput/src/v1.0.0-33934e6da4
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: ninja -v
    Working Directory: C:/Users/Simon/vcpkg/buildtrees/gainput/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\Users\Simon\vcpkg\buildtrees\gainput\config-x64-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:293 (vcpkg_execute_required_process)
  ports/gainput/portfile.cmake:11 (vcpkg_configure_cmake)
  scripts/ports.cmake:94 (include)


Error: Building package gainput:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: gainput:x64-windows
  Vcpkg version: 2019.09.12-nohash

Additionally, attach any relevant sections from the log files above.
PS C:\Users\Simon\vcpkg>
```

Attaced is the error log.

[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/4021865/config-x64-windows-out.log)

**Comment by PhoebeHui** [comment]
@simonbjork, I can't repro this issue, it looks not related to vcpkg, it seems something wrong in your vs setting up. 

Something you could try:
1. Install the English language pack if it doesn't installed. (reference https://github.com/microsoft/vcpkg/issues/1939#issuecomment-354644869)
2. Reinstall/repair VS
3. Remove 'PREFER_NINJA' in line#13 in ports\gainput\portfile.cmake, and try to build again

The failure:
Call Stack (most recent call first):
  ../../../../downloads/tools/cmake-3.14.0-windows/cmake-3.14.0-win32-x86/share/cmake-3.14/Modules/CMakeDetermineSystem.cmake:93 (include)
-- The C compiler identification is MSVC 19.16.27034.0
-- The CXX compiler identification is MSVC 19.16.27034.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe -- broken
CMake Error at ../../../../downloads/tools/cmake-3.14.0-windows/cmake-3.14.0-win32-x86/share/cmake-3.14/Modules/CMakeTestCCompiler.cmake:60 (message):
  The C compiler

    "C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe"

  is not able to compile a simple test program.

**Comment by simonbjork** [comment]
Thanks for the reply, turns out it was a permission error on Windows. Not sure why cmake tries to create all its temp files in the root of the C drive though.

**Comment by PhoebeHui** [comment]
@simonbjork, it seems you solved the issue, feel free reopen this issue if it still be a problem for you.
