### ISSUE TITLE
upgrade poco to the latest version

### ISSUE THREAD

**Issue by twMr7** [Microsoft/vcpkg#956]
Some bugs are fixed in the new version, and it will be great if poco port can upgrade to version 1.7.8.
Please check the attached patch file.

[upgrade-poco-to-version-1.7.8.patch.txt](https://github.com/Microsoft/vcpkg/files/941431/upgrade-poco-to-version-1.7.8.patch.txt)

**Comment by ras0219-msft** [comment]
Fixed with #961, thanks for making the PR!
