### ISSUE TITLE
[atkmm] Add support for linux

### ISSUE THREAD

**Issue by jon-ryan** [microsoft/vcpkg#9564]
**Host Environment**
- OS: Linux

**To Reproduce**
`./vcpkg install atkmm`

**Failure logs** 
```
-- Building /usr/share/vcpkg/buildtrees/atkmm/src/atkmm-2-de808b48b0/MSVC_Net2013/atkmm.sln for Release
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: msbuild /usr/share/vcpkg/buildtrees/atkmm/src/atkmm-2-de808b48b0/MSVC_Net2013/atkmm.sln /p:Configuration=Release /t:atkmm /p:Platform=x64 /p:PlatformToolset=external /p:VCPkgLocalAppDataDisabled=true /p:UseIntelMKL=No /p:WindowsTargetPlatformVersion= /m /p:ForceImportBeforeCppTargets=/usr/share/vcpkg/scripts/buildsystems/msbuild/vcpkg.targets /p:VcpkgTriplet=x64-linux
    Working Directory: /usr/share/vcpkg/buildtrees/atkmm/x64-linux-rel
    Error code: No such file or directory
    See logs for more information:

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_msbuild.cmake:119 (vcpkg_execute_required_process)
  ports/atkmm/portfile.cmake:25 (vcpkg_build_msbuild)
  scripts/ports.cmake:94 (include)

Error: Building package atkmm:x64-linux failed with: BUILD_FAILED
```

**Additional context**
The file _/usr/share/vcpkg/buildtrees/**atkmm**/install-x64-linux-dbg-out.log_ doesn't exist, but _/usr/share/vcpkg/buildtrees/**atk**/install-x64-linux-dbg-out.log_ does. The output is here:
https://pastebin.com/njFuHCup

**Comment by feliwir** [comment]
Running into the same issue. This makes Gtkmm unusable on Linux...

**Comment by JackBoosY** [comment]
We need to patch the `configure` file in the atkmm source, but I'm not very good at this.
Who can help me?

**Comment by faserg1** [comment]
How can I help to implement support?

**Comment by JackBoosY** [comment]
@faserg1 Unzip and replace [this file](https://github.com/microsoft/vcpkg/files/5376338/atkmm.zip) to _VCPKG_ROOT/ports/atkmm_, patch _ATKMM_SOURCE/configure_ to add option `--with-atk` / `--with-glibmm`.

**Comment by faserg1** [comment]
@JackBoosY As I see, there is no way to provide path for these libs directly in configure. But as I see here:
```configure: error: Package requirements (atk >= 1.18 glibmm-2.4 >= 2.46.2) were not met:

No package 'atk' found
No package 'glibmm-2.4' found```
It try to find these libs by pkgconfig.

And there is no .pc files for there libs in `PKGCONFIG_INSTALLED_DIR`.
As I am a new in vcpkg, is there a way to configure .pc files for libs and copy them? `glibmm` has `.pc.in` in `{glibmmdir}/glib` and similar file in atk source.

**Comment by JackBoosY** [comment]
@faserg1 I think it's okay.

**Comment by faserg1** [comment]
@JackBoosY I think there is a way to patch `configure.in` in atkmm source to generate `configure` (via autoreconf) without pkgconfig deps, and use flags to provide libs. But I think provide `.pc` files is a better way to make `configure` work.

**Comment by faserg1** [comment]
More problematic with glibmm. There is no suffix by default so I'll add suffix as like ATK or glib.

**Comment by JackBoosY** [comment]
Hi @jon-ryan, can you please update vcpkg and try again? This issue should be fixed.

Thanks.

**Comment by jon-ryan** [comment]
@JackBoosY Yes, this issue is fixed. Thank you.
