### ISSUE TITLE
[New Port Request] Simple-Web-Server

### ISSUE THREAD

**Issue by curtisgray** [microsoft/vcpkg#9565]
Library name: Simple-Web-Server

Library description: A very simple, fast, multithreaded, platform independent HTTP and HTTPS server and client library implemented using C++11 and Boost.Asio. Created to be an easy way to make REST resources available from C++ applications.

Source repository URL: https://gitlab.com/eidheim/Simple-Web-Server

Project homepage (if different from the source repository):

**Comment by LilyWangL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
