### ISSUE TITLE
Add speex

### ISSUE THREAD

**Issue by icexile** [Microsoft/vcpkg#958]
Speex is an Open Source/Free Software patent-free audio compression format designed for speech. The Speex Project aims to lower the barrier of entry for voice applications by providing a free alternative to expensive proprietary speech codecs. Moreover, Speex is well-adapted to Internet applications and provides useful features that are not present in most other codecs. Finally, Speex is part of the GNU Project and is available under the revised BSD license.

https://github.com/xiph/speex

**Comment by bagong** [comment]
+1
Would be very nice, also to complete the suite of xiph codecs. Unfortunately so far speex has no cmake support at all, and the most recent solution file is VS 2008...
On top of it libsndfile, which just underwent a complete overhaul of cmake support and builds very well with msvc now. ;)

**Comment by atkawa7** [comment]
@ras0219-msft Could you close this?
