### ISSUE TITLE
[boost] When building on arm don't require boost-build:x86-windows 

### ISSUE THREAD

**Issue by cbezault** [microsoft/vcpkg#9580]
Currently boost ports for an arm32/64 Windows target require `boost-build:x86-windows` to be installed beforehand because it is assumed that the user is cross-compiling from an x86/x64 host.

It should be acceptable for `boost-build:arm-windows` or `boost-build:arm64-windows` to be installed when building on an arm32/64 device.

**Proposed solution**
Allow cross triplet or "host" triplet dependencies to exist so that the hack for cross-compiling in the boost ports can be removed. This would also help with `protobuf-c`.

**Describe alternatives you've considered**
Add another hack on top of the existing hack to detect when I'm not cross-compiling.

**Additional context**
I have vcpkg running under x86 emulation but that doesn't mean that I need to run boost-build under emulation too.

**Comment by PhoebeHui** [comment]
It support to build Boost with arm64-windows in boost 1.72.0.  see https://github.com/boostorg/build/releases

**Comment by PhoebeHui** [comment]
Currently this feature is supported in vcpkg now.
