### ISSUE TITLE
curl[*]:x64-windows build failure

### ISSUE THREAD

**Issue by kdschlosser** [microsoft/vcpkg#9582]
**Host Environment**
- OS: Windows 7 x64 SP1
- Compiler: Visual Studio 2019

**To Reproduce**
`./vcpkg install curl[*]:x64-windows`

**Failure logs** 
```
C:\Users\***\Desktop\New folder (31)\vcpkg>vcpkg install curl[*]:x64-windows
The following packages will be built and installed:
  * c-ares[core]:x64-windows
    curl[brotli,c-ares,core,http2,mbedtls,non-http,openssl,sectransp,ssh,ssl,sspi,tool,winssl]:x64-windows
  * libssh2[core]:x64-windows
  * mbedtls[core]:x64-windows
  * nghttp2[core]:x64-windows
  * openssl[core]:x64-windows
  * openssl-windows[core]:x64-windows
  * zlib[core]:x64-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/8: mbedtls:x64-windows
Building package mbedtls[core]:x64-windows...
-- Downloading https://github.com/ARMmbed/mbedtls/archive/mbedtls-2.16.3.tar.gz...
-- Extracting source C:/Users/***/Desktop/New folder (31)/vcpkg/downloads/ARMmbed-mbedtls-mbedtls-2.16.3.tar.gz
-- Using source at C:/Users/***/Desktop/New folder (31)/vcpkg/buildtrees/mbedtls/src/tls-2.16.3-6ae2246379
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Installing: C:/Users/***/Desktop/New folder (31)/vcpkg/packages/mbedtls_x64-windows/share/mbedtls/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package mbedtls[core]:x64-windows... done
Installing package mbedtls[core]:x64-windows...
Installing package mbedtls[core]:x64-windows... done
Elapsed time for package mbedtls:x64-windows: 20.09 s
Starting package 2/8: zlib:x64-windows
Building package zlib[core]:x64-windows...
-- Using cached C:/Users/***/Desktop/New folder (31)/vcpkg/downloads/zlib1211.tar.gz
-- Using source at C:/Users/***/Desktop/New folder (31)/vcpkg/buildtrees/zlib/src/1.2.11-f690224aeb
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Installing: C:/Users/***/Desktop/New folder (31)/vcpkg/packages/zlib_x64-windows/share/zlib/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package zlib[core]:x64-windows... done
Installing package zlib[core]:x64-windows...
Installing package zlib[core]:x64-windows... done
Elapsed time for package zlib:x64-windows: 8.956 s
Starting package 3/8: openssl-windows:x64-windows
Building package openssl-windows[core]:x64-windows...
-- Downloading http://strawberryperl.com/download/5.30.0.1/strawberry-perl-5.30.0.1-32bit.zip...
-- Downloading https://www.openssl.org/source/openssl-1.0.2s.tar.gz...
-- Extracting source C:/Users/***/Desktop/New folder (31)/vcpkg/downloads/openssl-1.0.2s.tar.gz
-- Applying patch ConfigureIncludeQuotesFix.patch
-- Applying patch STRINGIFYPatch.patch
-- Applying patch EnableWinARM32.patch
-- Applying patch EmbedSymbolsInStaticLibsZ7.patch
-- Applying patch EnableWinARM64.patch
-- Using source at C:/Users/***/Desktop/New folder (31)/vcpkg/buildtrees/openssl-windows/src/openssl-1-c41872ef97
-- Downloading http://www.nasm.us/pub/nasm/releasebuilds/2.14.02/win32/nasm-2.14.02-win32.zip...
-- Downloading http://download.qt.io/official_releases/jom/jom_1_1_3.zip...
-- Copying openssl release source files...
-- Copying openssl release source files... done
-- Configure x64-windows-rel
-- Configure x64-windows-rel done
-- Build x64-windows-rel
-- Build x64-windows-rel done
-- Copying openssl debug source files...
-- Copying openssl debug source files... done
-- Configure x64-windows-dbg
-- Configure x64-windows-dbg done
-- Build x64-windows-dbg
-- Build x64-windows-dbg done
-- Installing: C:/Users/***/Desktop/New folder (31)/vcpkg/packages/openssl-windows_x64-windows/share/openssl-windows/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package openssl-windows[core]:x64-windows... done
Installing package openssl-windows[core]:x64-windows...
Installing package openssl-windows[core]:x64-windows... done
Elapsed time for package openssl-windows:x64-windows: 10.18 min
Starting package 4/8: openssl:x64-windows
Building package openssl[core]:x64-windows...
-- Installing: C:/Users/***/Desktop/New folder (31)/vcpkg/packages/openssl_x64-windows/share/openssl//usage
-- Performing post-build validation
-- Performing post-build validation done
Building package openssl[core]:x64-windows... done
Installing package openssl[core]:x64-windows...
Installing package openssl[core]:x64-windows... done
Elapsed time for package openssl:x64-windows: 1.531 s
Starting package 5/8: libssh2:x64-windows
Building package libssh2[core]:x64-windows...
-- Downloading https://github.com/libssh2/libssh2/archive/42d37aa63129a1b2644bf6495198923534322d64.tar.gz...
-- Extracting source C:/Users/***/Desktop/New folder (31)/vcpkg/downloads/libssh2-libssh2-42d37aa63129a1b2644bf6495198923534322d64.tar.gz
-- Applying patch C:/Users/Admi***nistrator/Desktop/New folder (31)/vcpkg/ports/libssh2/0001-Fix-UWP.patch
-- Using source at C:/Users/***/Desktop/New folder (31)/vcpkg/buildtrees/libssh2/src/3534322d64-e9146b9288
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Installing: C:/Users/***/Desktop/New folder (31)/vcpkg/packages/libssh2_x64-windows/share/libssh2/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package libssh2[core]:x64-windows... done
Installing package libssh2[core]:x64-windows...
Installing package libssh2[core]:x64-windows... done
Elapsed time for package libssh2:x64-windows: 57.98 s
Starting package 6/8: nghttp2:x64-windows
Building package nghttp2[core]:x64-windows...
-- Downloading https://github.com/nghttp2/nghttp2/archive/v1.39.2.tar.gz...
-- Extracting source C:/Users/***/Desktop/New folder (31)/vcpkg/downloads/nghttp2-nghttp2-v1.39.2.tar.gz
-- Using source at C:/Users/***/Desktop/New folder (31)/vcpkg/buildtrees/nghttp2/src/v1.39.2-d44e9e13e6
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Installing: C:/Users/***/Desktop/New folder (31)/vcpkg/packages/nghttp2_x64-windows/share/nghttp2/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package nghttp2[core]:x64-windows... done
Installing package nghttp2[core]:x64-windows...
Installing package nghttp2[core]:x64-windows... done
Elapsed time for package nghttp2:x64-windows: 26.16 s
Starting package 7/8: c-ares:x64-windows
Building package c-ares[core]:x64-windows...
-- Downloading https://github.com/c-ares/c-ares/archive/9f1fdbf5dd633f81352fac0d6bc0d0c4d45be459.tar.gz...
-- Extracting source C:/Users/***/Desktop/New folder (31)/vcpkg/downloads/c-ares-c-ares-9f1fdbf5dd633f81352fac0d6bc0d0c4d45be459.tar.gz
-- Using source at C:/Users/***/Desktop/New folder (31)/vcpkg/buildtrees/c-ares/src/c4d45be459-24e25a63ee
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Performing post-build validation
-- Performing post-build validation done
Building package c-ares[core]:x64-windows... done
Installing package c-ares[core]:x64-windows...
Installing package c-ares[core]:x64-windows... done
Elapsed time for package c-ares:x64-windows: 1.374 min
Starting package 8/8: curl:x64-windows
Building package curl[brotli,c-ares,core,http2,mbedtls,non-http,openssl,sectransp,ssh,ssl,sspi,tool,winssl]:x64-windows...
-- Using cached C:/Users/***/Desktop/New folder (31)/vcpkg/downloads/curl-curl-curl-7_66_0.tar.gz
-- Using source at C:/Users/***/Desktop/New folder (31)/vcpkg/buildtrees/curl/src/url-7_66_0-905cf351d9
CMake Error at ports/curl/portfile.cmake:50 (message):
  sectransp is not supported on non-Apple platforms
Call Stack (most recent call first):
  scripts/ports.cmake:94 (include)


Error: Building package curl:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: curl:x64-windows
  Vcpkg version: 2019.09.12-nohash

Additionally, attach any relevant sections from the log files above.

C:\Users\***\Desktop\New folder (31)\vcpkg>vcpkg update
Using local portfile versions. To update the local portfiles, use `git pull`.
No packages need updating.

C:\Users\***\Desktop\New folder (31)\vcpkg>git pull
Already up to date.

C:\Users\***\Desktop\New folder (31)\vcpkg>
```
**Additional context**
Looks like the port is trying to build sectransp which is apple only

**Comment by JackBoosY** [comment]
Hi @kdschlosser, thanks for reporting this issue!
You should not use the command `.\vcpkg installl curl [*] `, because curl's feature `sectransp` only works on osx.

**Comment by kdschlosser** [comment]
Yes I did figure that out.. The x86 is also effected by this.. You would think that using the * would install the components for the platform it is running on if the * is supplied. it would make sense wouldn't it?

another thing USE_HTTP_ONLY defaulting to ON??!?!?

I could understand it being set to on if no ssl was specified and also no other protocol. But to have the user have to specifically add the non-http is a bit strange. because even if they specify using ssh and SSL but do not add the non-http the SSL and the ssh are not going to work.

**Comment by JackBoosY** [comment]
@kdschlosser I've already removed feature `non-http` with curl.
Please update vcpkg and try again.

Thanks.

**Comment by kdschlosser** [comment]
I appreciate the work on this... and here is the but... There is a slew of build options available. what is accounted for is a very small amount. 

I do not know how vcpkg works with respect to building dependencies. this is some of the dependencies that curl can have and the dependencies of the dependencies. it is kind of a twisted mess actually.

```
curl -----------------------
zlib
libcares
nghttp2
bearssl
libssh2
idn (windows)
ipv6
sspi (windows)
winssl (windows) requires sspi
mbedtls
openssl
openldap
win32ldap
gssapi
nss

nss -----------------------------------
zlib

mbedtls --------------------------------
zlib

nghttp2 ------------------
zlib
libxml2
libevent
libcares
jemalloc
jansson
-------------------------

libevent -------------
zlib
openssl
-----------------------------------------

libxml2 -----------------------------------
iconv
zlib
liblzma
```

some are optional and others are not. because of the use of configure and perl with some of the libs it makes it extremely difficult to nail down all of the possibilities. so This list is a partial list as I do not have all of the platforms that are supported readily available to me. The list only shows some of the possibilities and how nested it is. There are many more options and dependencies.

Here are some possible road bumps if they have not been accounted for already. 

if i wanted curl to compile using nghttp2 and I want to have nghttp2 compile with libxml2 support is there a way to make that happen through the command line for building curl? or would I have to make all independent calls to each of the deps and have them compile with specific options I set?

say you have lib1 and lib2 and both of them use lib3 as a dep. lib3 has a series of options that have the ability to be set. if i want to compile lib1 and have options a, b, and c set in lib3 and then for lib2 i want to have options d, e and f set for lib3 is that something that can be done using a single vcpkg command? 
if I am not able to set the options for lib2 through the command for lib1 or lib2 would I have to compile lib3 with options a, b, and c then compile lib1 then remove lib3 and compile it again with opeions d, e and f and then compile lib2? 

I do not know if vcpkg has been written to forward parameters to dependent packages.. and if it is not I would think it better to compile lib3 having it's parameters passed to it when building the parent lib.


when a lib has a dep and that dep gets compiled does it get installed into the system? or is it only compiled for the purposes of being a dependency? 

The curl library is a fantastic use case example for things like this because of how nested the dependencies and optional dependencies are. There are so many possible build combinations that a sandbox environment for the build almost becomes a necessity so the build can be "clean" and nothing else can effect the outcome. there are many "auto detection" portions of the build scripts that can influence the compilation in a manner that may not be wanted and tracking this down with a complex build setup as this one can be quite daunting. 


Here is another scenario.

If i had a lib installed and it is setup a way that I use the most it would be inconvenient to have to recompile that lib if some other options need to be specified because it is a dep in something else I want to compile. then I would have to compile the lib once again to revert it back to the way I had it originally. It would be more so if it takes a long time, openssl for example.

I did not come across anything in the docs about these kinds of things. I do not know how they get handled. or if a deps options can be specified from a parents command

**Comment by JackBoosY** [comment]
@kdschlosser I will take a look.

**Comment by JackBoosY** [comment]
> if i wanted curl to compile using nghttp2 and I want to have nghttp2 compile with libxml2 support is there a way to make that happen through the command line for building curl? or would I have to make all independent calls to each of the deps and have them compile with specific options I set?

In this case, you need change curl feature `nghttp2` depdenecy to `libxml2[nghhtp2]`(if it's exist).

> say you have lib1 and lib2 and both of them use lib3 as a dep. lib3 has a series of options that have the ability to be set. if i want to compile lib1 and have options a, b, and c set in lib3 and then for lib2 i want to have options d, e and f set for lib3 is that something that can be done by using 2 commands, one to compile lib1 and another to compile lib2?

Same as above. vcpkg will automatically detect the features that need to be installed and join the list to install, I think it is not necessary to execute multiple installation commands.

All port dependencies point to the libraries installed in vcpkg, so recursively guarantee that the port's dependency chain is correct.
The only thing we can't solve is:
Suppose that port B depends on port A, and port C depends on port A and port B. We cannot choose to use the feature of port B when building port A, and do not choose the feature of port B when building library C. Since port C is generated only once, there is a conflict in it.

> If i had a lib installed and it is setup a way that I use the most it would be inconvenient to have to recompile that lib if some other options need to be specified because it is a dep in something else I want to compile. then I would have to compile the lib once again to revert it back to the way I had it originally. It would be more so if it takes a long time, openssl for example.

This scenario is unavoidable because previously installed libraries did not come with some features, and libraries that need to be installed now depend on some of its uninstalled features.

**Comment by kdschlosser** [comment]
The only way I can think about compiling deps that have a diferent set of options then the installed version would be a sandbox environment.

Is there an option to have openssl compiled using JOM?

**Comment by JackBoosY** [comment]
@kdschlosser Not yet, but you can open a PR to add support with jom.
