### ISSUE TITLE
[New Port Request] aria2c

### ISSUE THREAD

**Issue by yuyifu** [microsoft/vcpkg#9587]
I want to use aria2c  in windows. 
so search it by vcpkg.
could not find it!

**Comment by longnguyen2004** [comment]
This is a library manager, not a centralized software manager like apt.

**Comment by drescherjm** [comment]
If this does not exist in vcpkg you can ask for a port request. However don't expect someone to create one for you in a short amount of time.

**Comment by LilyWangL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
