### ISSUE TITLE
How do I exclude unused libraries (*.lib) from a project?

### ISSUE THREAD

**Issue by lyhyl** [microsoft/vcpkg#9588]
**Describe the odd behavior (not bug)**
If the [shogun] is installed, lots of projects will fail to compile even it does not include any header files related to [shogun].
After remove [shogun] from vcpkg, everything works as expected.

**Environment**
- Hardware:  8G RAM
- OS: Windows 10 1909
- Compiler: MSVC (VS2019)

**To Reproduce**
1. ./vcpkg.exe install shogun:x64-windows
2. open VS 2019, create an empty console project and switch to x64 build
3. create main.cpp with following code:
```c++
int main()
{
    return 0;
}
```
4. compile successfully
5. add more things to the code:
```c++
#include <pcl/point_cloud.h>
#include <pcl/point_types.h>
int main()
{
	pcl::PointCloud<pcl::PointXYZ> a;
	return 0;
}
```
6. fail to compile, get **Failure logs**:
```
1>------ Build started: Project: test, Configuration: Debug x64 ------
1>main.cpp
1>D:\wingkou\vcpkg\installed\x64-windows\include\pcl\point_traits.h(1,1): warning C4819: The file contains a character that cannot be represented in the current code page (936). Save the file in Unicode format to prevent data loss
1>LINK : the 32-bit linker (C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\bin\HostX86\x64\link.exe) failed to do memory mapped file I/O on `D:\wingkou\vcpkg\installed\x64-windows\debug\lib\libshogun.lib' and is going to restart linking with a 64-bit linker for better throughput
1>LINK : restarting link with 64-bit linker `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\bin\HostX64\x64\link.exe'
1>libshogun.lib(Time.cpp.obj) : error LNK2019: unresolved external symbol __imp_timeGetTime referenced in function "int __cdecl gettimeofday(struct timeval *,void *)" (?gettimeofday@@YAHPEAUtimeval@@PEAX@Z)
1>D:\wingkou\test\x64\Debug\test.exe : fatal error LNK1120: 1 unresolved externals
1>Done building project "test.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

**Additional context**
It should be noted that the `libshogun.lib` is amazingly huge (dbg: 2.05 GB, rel: 1.80 GB). This problem is probably related to the size of the lib, although failure logs do not mention that. Before my new RAM arrives, what can I do to solve this problem temporarily? How do I exclude unused libraries (*.lib) from project? Is the size of `libshogun.lib` normal?

**Comment by JackBoosY** [comment]
Hi @lyhyl, thanks for reporting this issue!
Could you add `Winmm.lib` to dependency library list and try again?

Thanks.

**Comment by lyhyl** [comment]
> Hi @lyhyl, thanks for reporting this issue!
> Could you add `Winmm.lib` to dependency library list and try again?
> 
> Thanks.

I added `#pragma comment(lib, "winmm.lib")` and it works. But it is still weird to import a unused lib explicitly to make it work. Is there an isolation mechanism?

**Comment by JackBoosY** [comment]
@lyhyl vcpkg will automatically copy these dependent libraries after the project is successfully built according to the record of Visual Studio linking dependent libraries.
Unfortunately, vcpkg does not install system libraries (such as `winmm.lib`), so you must add these system libraries manually.

**Comment by lyhyl** [comment]
> @lyhyl vcpkg will automatically copy these dependent libraries after the project is successfully built according to the record of Visual Studio linking dependent libraries.
> Unfortunately, vcpkg does not install system libraries (such as `winmm.lib`), so you must add these system libraries manually.

If I don't get it wrong, it's equivalent to cmake project with CMakeLists.txt:
```cmake
add_library(lib_A STATIC IMPORTED)
add_library(lib_B STATIC IMPORTED)
// add all installed libraries
add_library(lib_XXX STATIC IMPORTED)
```
right?

But I still confused that:

---
**Case 1 (Compile successfully)**:
[shotgun]:x64-windows installed
```c++
int main()
{
    return 0;
}
```
---
**Case 2 (Compile successfully)**:
[shotgun]:x64-windows **NOT** installed
```c++
#include <pcl/point_cloud.h>
#include <pcl/point_types.h>
int main()
{
	pcl::PointCloud<pcl::PointXYZ> a;
	return 0;
}
```
---
**Case 3 (Compile failed, have to import winmm.lib)**:
[shotgun]:x64-windows installed
```c++
#include <pcl/point_cloud.h>
#include <pcl/point_types.h>
//#pragma comment(lib, "winmm.lib")
int main()
{
	pcl::PointCloud<pcl::PointXYZ> a;
	return 0;
}
```
error logs:
```
libshogun.lib(Time.cpp.obj) : error LNK2019: unresolved external symbol __imp_timeGetTime referenced in function "int __cdecl gettimeofday(struct timeval *,void *)"
```
---
It seems that the [shogun] broke the whole system :(, or I don't know how to explain it.

**Comment by JackBoosY** [comment]
When you use cmake project, `find_package(Shogun CONFIG REQUIRED)` will automatically link to` winmm.lib`, you can find the relevant code in _VCPKG_PATH/installed/TRIPLETS/share/shogun/ShogunTargets-debug.cmake(ShogunTargets-release.cmake)_.

However, if you use msvc project, vcpkg's auto-linking function is implemented by adding all the libraries in _VCPKG_PATH/installed/TRIPLETS/lib(debug/lib)_ to the dependent library list. But vcpkg will not install system libraries into this directory to prevent conflicts with the libraries in the Visual Studio installation directory, so we must manually add these system libraries.

**Comment by lyhyl** [comment]
@JackBoosY Since the members of [shogun] are still improving the library, I close this issue now. However, I hope the guideline can provide some guidance on the size of the library, and limit the size of the binary. I think the author of #9614 has a similar problem.
