### ISSUE TITLE
Error: Building package fontconfig:x86-windows

### ISSUE THREAD

**Issue by hatcat** [Microsoft/vcpkg#959]
-- Package x86-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:14 (message):
    Command failed: C:/Users/Guy.Davidson/Documents/Visual Studio 2015/Projects/repos/vcpkg/downloads/cmake-3.8.0-rc1-wi
n32-x86/bin/cmake.exe;--build;.;--config;Release;--target;install;--;/p:VCPkgLocalAppDataDisabled=true;/p:UseIntelMKL=No
;/m
    Working Directory: C:/Users/Guy.Davidson/Documents/Visual Studio 2015/Projects/repos/vcpkg/buildtrees/fontconfig/x86
-windows-rel
    See logs for more information:
      C:\Users\Guy.Davidson\Documents\Visual Studio 2015\Projects\repos\vcpkg\buildtrees\fontconfig\package-x86-windows-
rel-out.log
      C:\Users\Guy.Davidson\Documents\Visual Studio 2015\Projects\repos\vcpkg\buildtrees\fontconfig\package-x86-windows-
rel-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_cmake.cmake:27 (vcpkg_execute_required_process)
  ports/fontconfig/portfile.cmake:33 (vcpkg_install_cmake)
  scripts/ports.cmake:73 (include)

Error: Building package fontconfig:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: fontconfig:x86-windows
  Vcpkg version: 0.0.80-d0a1206050d2aa42981244d8dbc744bb1093db34

Additionally, attach any relevant sections from the log files above.

**Comment by hatcat** [comment]
Turns out I'm using the latest of everything; if you can point me to the log files I can attach those.

Cheers,
G

**Comment by ras0219-msft** [comment]
Hi @hatcat, the log files should be inside $vcpkg\buildtrees\fontconfig, so for you this would be 

`C:\Users\Guy.Davidson\Documents\Visual Studio 2015\Projects\repos\vcpkg\buildtrees\fontconfig\`

>See logs for more information:
C:\Users\Guy.Davidson\Documents\Visual Studio 2015\Projects\repos\vcpkg\buildtrees\fontconfig\package-x86-windows-
rel-out.log
C:\Users\Guy.Davidson\Documents\Visual Studio 2015\Projects\repos\vcpkg\buildtrees\fontconfig\package-x86-windows-
rel-err.log

**Comment by madebr** [comment]
@hathat Can you test again with microsoft/vcpkg#975 applied?

**Comment by hatcat** [comment]
Yup, all lovely thanks!
