### ISSUE TITLE
[x264] build failure when trying to build only release version of the library

### ISSUE THREAD

**Issue by bogdanlytvynovskyi** [microsoft/vcpkg#9590]
**Host Environment**
- OS: Windows
- Compiler: Microsoft (R) C/C++ Optimizing Compiler Version 19.23.28106.4 for x8

**To Reproduce**
`vcpkg.exe install --overlay-triplets=..\.vscode\custom-triplets x264:x86-windows-static`

Custom triplet contents x86-windows-static.cmake:
```cmake
set(VCPKG_TARGET_ARCHITECTURE x86)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)
set(VCPKG_BUILD_TYPE` release)
```
**Failure logs** 
See logs for more information:
      vcpkg\buildtrees\x264\install-x86-windows-static-dbg-err.log
Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_make.cmake:164 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_make.cmake:24 (vcpkg_build_make)
  ports/x264/portfile.cmake:33 (vcpkg_install_make)
  scripts/ports.cmake:94 (include)

Error: Building package x264:x86-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: x264:x86-windows-static
  Vcpkg version: 2019.09.12-nohash

Contents of install-x86-windows-static-dbg-err.log
make: *** No rule to make target 'install'.  Stop.

**Additional context**
The issue seems to be in fact that scripts/cmake/vcpkg_build_make.cmake ignores the fact that we are building only release during install step (while does the proper thing during build step). Here is a patch I applied locally: 
[install_step.patch.txt](https://github.com/microsoft/vcpkg/files/4036532/install_step.patch.txt)

**Comment by NancyLi1013** [comment]
Hi @bogdanlytvynovskyi thanks for posting this issue and your suggestion to fix this issue.
The PR has been merged. Please update vcpkg and try to use it again.
