### ISSUE TITLE
[openimageio] build failure with python bindings (x64-windows-static)

### ISSUE THREAD

**Issue by simonbjork** [microsoft/vcpkg#9594]
**Host Environment**
- OS: Windows 10
- Compiler: Visual Studio 2017 (15.9)

**To Reproduce**
```
./vcpkg install pybind11:x64-windows-static
./vcpkg install openimageio:x64-windows-static
```
Edit the portfile.cmake to enable python support:
`DUSE_PYTHON= ON`

Also, i'm using the updated openimageio port linked at the bottom of [this](https://github.com/microsoft/vcpkg/issues/9377) post.

Python2.7 is in the PATH.

I see that in the portfile.cmake for pybind11 that it uses Python3. Is that correct? From what I know the OIIO python is still for 2.7?

I tried to replace all occurences of PYTHON3 with PYTHON2 and it actually builds. It still installs python3 and cpython3 though. If I try to use the created OpenImageIO.pyd I get this:

`Fatal Python error: PyThreadState_Get: no current thread`

Also, I tried to enable DBUILD_MISSING_PYBIND11 in the openimageio porfile.cmake, but that seems to crash Powershell for some reason (probably user error).

If I disable DUSE_PYTHON the build completes successfully. I also tried to build with extra features, such as the command line tools, libraw etc, and they also work (ffmpeg requires the patch from the other thread).

[config-x64-windows-static-out.log](https://github.com/microsoft/vcpkg/files/4037520/config-x64-windows-static-out.log)
[CMakeOutput.log](https://github.com/microsoft/vcpkg/files/4037521/CMakeOutput.log)

```
Building package openimageio[core]:x64-windows-static...
-- Using cached C:/Users/Simon/Dropbox/_sandbox/vcpkg/downloads/OpenImageIO-oiio-fdd982a9922ff508b8b22e5d024356b582572f46.tar.gz
-- Extracting source C:/Users/Simon/Dropbox/_sandbox/vcpkg/downloads/OpenImageIO-oiio-fdd982a9922ff508b8b22e5d024356b582572f46.tar.gz
-- Applying patch fix-dependency.patch
-- Applying patch fix_static_build.patch
-- Applying patch fix-tools-path.patch
-- Applying patch fix-config-cmake.patch
-- Using source at C:/Users/Simon/Dropbox/_sandbox/vcpkg/buildtrees/openimageio/src/b582572f46-1287ea81ed
-- Configuring x64-windows-static
-- Building x64-windows-static-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: C:/Users/Simon/Dropbox/_sandbox/vcpkg/downloads/tools/cmake-3.14.0-windows/cmake-3.14.0-win32-x86/bin/cmake.exe --build . --config Debug --target install -- -v
    Working Directory: C:/Users/Simon/Dropbox/_sandbox/vcpkg/buildtrees/openimageio/x64-windows-static-dbg
    See logs for more information:
      C:\Users\Simon\Dropbox\_sandbox\vcpkg\buildtrees\openimageio\install-x64-windows-static-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:91 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/openimageio/portfile.cmake:59 (vcpkg_install_cmake)
  scripts/ports.cmake:94 (include)


Error: Building package openimageio:x64-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: openimageio:x64-windows-static
  Vcpkg version: 2019.09.12-nohash

Additionally, attach any relevant sections from the log files above.
PS C:\Users\Simon\Dropbox\_sandbox\vcpkg>

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by simonbjork** [comment]
Alos,

I tried to add set(VCPKG_PLATFORM_TOOLSET v140) but that fails as well.

**Comment by JackBoosY** [comment]
Hi @simonbjork, thanks for reporting this issue!
Could you use #8543 changes and try again?

Thanks.

**Comment by simonbjork** [comment]
Hi @JackBoosY , thanks for the reply.

I think I already did use that? I'm using [this file](https://github.com/microsoft/vcpkg/files/4017969/openimageio.zip) that you posted a few days ago. Or do you mean use an older version?

**Comment by JackBoosY** [comment]
@simonbjork Okay, if it doesn't work, we will add this feature in the future.
I just want to confirm it.

**Comment by filmpipeuser** [comment]
Thanks.

It's hard to know if this is a user error, a vcpkg error or a openimageio error as I don't know if others use this without problems.

Still, it seems wrong that pybind11 does some python3 stuff, but maybe that's expected, I have no idea.

**Comment by simonbjork** [comment]
Thanks.

It's hard to know if this is a user error, a vcpkg error or a openimageio error as I don't know if others use this without problems. Does it build without errors for you?

Still, it seems wrong that pybind11 does some python3 stuff, but maybe that's expected, I have no idea.

**Comment by timautry** [comment]
@JackBoosY @simonbjork  The changes in #8543 work fine for openimageio v2.1.9.0 on:
Windows 10 1909 (OS Build 18363.535) 64-bit
VS 2017 v15.9.18 vc141 toolset, x64-windows triplet, linkage dynamic
VS 2019 v16.4.2 vc142 toolset, x64-windows triplet, linkage dynamic
.\vcpkg install openimageio[core,libraw,opencolorio,ffmpeg,freetype,opencv,gif,openjpeg,webp,tools]

all options except field3d as field3d windows is currently not supported.

[openimageio.zip](https://github.com/microsoft/vcpkg/files/4042450/openimageio.zip)

Thanks and just letting you know.

**Comment by simonbjork** [comment]
@timautry that's good to hear! Just to make sure, you have enabled the python bindings (DUSE_PYTHON and DBUILD_MISSING_PYBIND) in the portfile.cmake? Also, have you tested the python bindings with Python2.7? Really intested to hear if that works for you. It all works for me as well except for the python bindings.

**Comment by simonbjork** [comment]
Ok I finally got it to work. I don't know why, but I need to add this to my x64-windows.cmake file:

`set(VCPKG_BUILD_TYPE release)`

If I do that, it works with both 141 and 142.

**Comment by simonbjork** [comment]
Also, as noted before pybind is missing from the dependencies.

**Comment by simonbjork** [comment]
My mistake, pybind is there in the latest fix. So all in all it's working great now :).

**Comment by JackBoosY** [comment]
@simonbjork So, can I close this issue now?

**Comment by JackBoosY** [comment]
Feature `python` has been added in #8543.

**Comment by simonbjork** [comment]
@JackBoosY , yes thanks a lot for making this work :).

There's still the issue that I need to set the VCPKG_BUILD_TYPE to release, but I'm not sure it it's a user error, oiio error or vcpkg error.

**Comment by JackBoosY** [comment]
@simonbjork That's a common issue with almost everyport.  We need to figure out the solution to fix it.

**Comment by simonbjork** [comment]
Ok thanks. Feel free to close this issue then :)

**Comment by simonbjork** [comment]
@JackBoosY : I just tried the latest update and it seems when you added "python" as a feature it builds for Python3. I know Python2 is going away but would guess most users of OIIO is still on Python2 and it should be a better default. I'm not even sure the python api works with python3. Or, could it be added as two features, python2 and python3?

**Comment by JackBoosY** [comment]
@simonbjork pybind11 depends on python3, if I add or change python3 to python2, it may not work.

**Comment by JackBoosY** [comment]
Close this issue via #8543 merged.

**Comment by timautry** [comment]
Thank you for the hard work!
