### ISSUE TITLE
libffi arm debian with custom compiler

### ISSUE THREAD

**Issue by bramburn** [microsoft/vcpkg#9595]
**Host Environment**
- OS: [e.g. Windows/Linux etc...] DEBIAN
- Compiler: revision
I am using a custom triplet with the following information, so far most of the packages have worked.
```
    set(VCPKG_TARGET_ARCHITECTURE arm)
    set(VCPKG_CRT_LINKAGE dynamic)
    set(VCPKG_LIBRARY_LINKAGE dynamic)
    set(VCPKG_CMAKE_SYSTEM_NAME Linux)
    set(CMAKE_CXX_COMPILER "/usr/bin/arm-linux-gnueabihf-g++")
    set(CMAKE_C_COMPILER "/usr/bin/arm-linux-gnueabihf-gcc")
    set(VCPKG_CMAKE_SYSTEM_VERSION 10.0)
```

**To Reproduce**
Requirements:
```bash
sudo apt install build-essential
sudo apt install g++-arm-linux-gnueabihf
sudo apt install gdb-multiarch
```

## Step 1

First, create a folder to contain your custom triplets:
Start off by creating a custom build

`~/vcpkg$ mkdir ../custom-triplets`

## Step 2

Now create the raspberry PI cmake

`~/vcpkg$ cp ./triplets/arm-uwp.cmake ../custom-triplets/arm-rasp.cmake`

## Step 3

Edit the new Cmake file using the following

```cmake
    set(VCPKG_TARGET_ARCHITECTURE arm)
    set(VCPKG_CRT_LINKAGE dynamic)
    set(VCPKG_LIBRARY_LINKAGE dynamic)
    set(VCPKG_CMAKE_SYSTEM_NAME Linux)
    set(CMAKE_CXX_COMPILER "/usr/bin/arm-linux-gnueabihf-g++")
    set(CMAKE_C_COMPILER "/usr/bin/arm-linux-gnueabihf-gcc")
```

## Step 4

Call the `./vcpkg` on your debian so that you can build the c++ files on your Debian WSL.

`./vcpkg install python3:arm-rasp --overlay-triplets=../custom-triplets/`

after this you'll get a problem install the libffi. I had to edit the ports/libffi/ports.cmake with the following:

from:

```
if(NOT VCPKG_TARGET_ARCHITECTURE STREQUAL x86 AND NOT VCPKG_TARGET_ARCHITECTURE STREQUAL x64)
    message(FATAL_ERROR "Architecture not supported")
endif()

```
to
```
if(NOT VCPKG_TARGET_ARCHITECTURE STREQUAL x86 AND NOT VCPKG_TARGET_ARCHITECTURE STREQUAL x64 AND NOT VCPKG_TARGET_ARCHITECTURE STREQUAL arm)
    message(FATAL_ERROR "Architecture not supported")
endif()

```

After that the build was ok, it is still processing the other dependencies. hopefully it will not have further errors.

**Failure logs** 

```
Building package libffi[core]:arm-rasp...
-- Loading triplet configuration from: /home/bramburn/custom-triplets/arm-rasp.cmake
CMake Error at ports/libffi/portfile.cmake:4 (message):
  Architecture not supported
Call Stack (most recent call first):
  scripts/ports.cmake:94 (include)


Error: Building package libffi:arm-rasp failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libffi:arm-rasp
  Vcpkg version: 2019.09.12-unknownhash
```
**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by bramburn** [comment]
oh i am using a debian WSL

**Comment by bramburn** [comment]
also when installing the python3 on this setup it will come up with an error if `zlib` is not installed first.

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. This issue is about community triplet, and there are no update about this issue for a long time. If there are new process or change of this issue, please reopen this issue.

**Comment by jphz** [comment]
This is very useful. Thank you very much.
