### ISSUE TITLE
How do I reinstall all the packages on another machine?

### ISSUE THREAD

**Issue by xahon** [microsoft/vcpkg#9597]
I noticed that there are no changes after installing a package. So, I installed `sdl2`, for instance, and want to switch to another computer to continue development, but I has to install it again and all my coworkers need to do that too?

**Comment by JackBoosY** [comment]
You can export them[1] and import them[2] to new machine.

[1]. `.\vcpkg export <portname>`
[2].  `.\vcpkg import <packagepath>`

**Comment by xahon** [comment]
@JackBoosY you need to export/import all packages one by one which is a lot of work to do. Making `.sh`/`.bat` scripts will force to port and then maintain them both in at least 2 different platforms to keep them working

**Comment by xahon** [comment]
Also, `export` requires some additional parameters. I don't know what to choose `--raw --nuget --ifw --zip --7zip --chocolatey`

**Comment by JackBoosY** [comment]
@xahon Please see documentation [here](https://github.com/microsoft/vcpkg/blob/master/docs/specifications/export-command.md).

Thanks.

**Comment by xahon** [comment]
overcomplicated stuff

**Comment by JackBoosY** [comment]
And we are adding feature `binarycaching` to vcpkg, see #11204.

**Comment by xahon** [comment]
@JackBoosY so, export works only for a single platform, e.g. when I transfer my project from windows PC to windows PC, when I transfer project from Windows PC to Linux PC I should also jot down all the packages my project uses, then reinstall them all on another platform and export them again. How do you share your vcpkg project with your friend that uses other OS than you?

**Comment by JackBoosY** [comment]
@xahon Normally we use the `export` function, but now we don't have `all` options.

**Comment by JackBoosY** [comment]
Now, we have binary caching.
You can copy it to the new machine through the cache path prompted in the console, and then use it through the install command.
