### ISSUE TITLE
vcpkg build issue, should detect UWP-only winsdk

### ISSUE THREAD

**Issue by rajnishc8** [microsoft/vcpkg#960]
Hi,
  I get following error when I try to build vcpkg.

C:\proj\vcpkg>.\bootstrap-vcpkg.bat
Microsoft (R) Build Engine version 15.1.1012.6693
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 4/20/2017 9:33:46 PM.
     1>Project "C:\proj\vcpkg\toolsrc\dirs.proj" on node 1 (default targets).
     1>Project "C:\proj\vcpkg\toolsrc\dirs.proj" (1) is building "C:\proj\vcpkg\toolsrc\vcpkg\vcpkg.vcxproj" (2) on nod
       e 1 (Clean target(s)).
     2>Project "C:\proj\vcpkg\toolsrc\vcpkg\vcpkg.vcxproj" (2) is building "C:\proj\vcpkg\toolsrc\vcpkglib\vcpkglib.vcx
       proj" (3) on node 1 (Clean target(s)).
     3>_PrepareForClean:
         Deleting file "Release\vcpkglib.tlog\vcpkglib.lastbuildstate".
     3>Done Building Project "C:\proj\vcpkg\toolsrc\vcpkglib\vcpkglib.vcxproj" (Clean target(s)).
     2>Done Building Project "C:\proj\vcpkg\toolsrc\vcpkg\vcpkg.vcxproj" (Clean target(s)).
     1>Project "C:\proj\vcpkg\toolsrc\dirs.proj" (1) is building "C:\proj\vcpkg\toolsrc\vcpkg\vcpkg.vcxproj" (2:2) on n
       ode 1 (Build target(s)).
   2:2>Project "C:\proj\vcpkg\toolsrc\vcpkg\vcpkg.vcxproj" (2:2) is building "C:\proj\vcpkg\toolsrc\vcpkglib\vcpkglib.v
       cxproj" (3:4) on node 1 (default targets).
     3>InitializeBuildStatus:
         Touching "Release\vcpkglib.tlog\unsuccessfulbuild".
       VcpkgTripletSelection:
         Using triplet "x86-windows" from "C:\proj\vcpkg\installed\x86-windows\"
       ClCompile:
         C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.10.25017\bin\HostX86\x86\CL.exe
          /c /I..\include /I"C:\proj\vcpkg\installed\x86-windows\include" /Zi /nologo /W3 /WX- /diagnostics:classic /sd
         l /MP /O2 /Oi /Oy- /GL /D DISABLE_METRICS=0 /D "VCPKG_VERSION=-4d850d153a2253fa54308b2f9128b07f2db9428a" /D _M
         BCS /D NDEBUG /D _MBCS /Gm- /EHsc /MD /GS /Gy /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Yc"pch.h" /Fp"R
         elease\vcpkglib.pch" /Fo"Release\\" /Fd"Release\vcpkglib.pdb" /Gd /TP /analyze- /errorReport:queue /std:c++lat
         est ..\src\pch.cpp
         pch.cpp
     3>C:\proj\vcpkg\toolsrc\include\pch.h(28): fatal error C1083: Cannot open include file: 'shlobj.h': No such file o
       r directory [C:\proj\vcpkg\toolsrc\vcpkglib\vcpkglib.vcxproj]
     3>Done Building Project "C:\proj\vcpkg\toolsrc\vcpkglib\vcpkglib.vcxproj" (default targets) -- FAILED.
     2>Done Building Project "C:\proj\vcpkg\toolsrc\vcpkg\vcpkg.vcxproj" (Build target(s)) -- FAILED.
     1>Done Building Project "C:\proj\vcpkg\toolsrc\dirs.proj" (default targets) -- FAILED.

Build FAILED.

       "C:\proj\vcpkg\toolsrc\dirs.proj" (default target) (1) ->
       "C:\proj\vcpkg\toolsrc\vcpkg\vcpkg.vcxproj" (Build target) (2:2) ->
       "C:\proj\vcpkg\toolsrc\vcpkglib\vcpkglib.vcxproj" (default target) (3:4) ->
       (ClCompile target) ->
         C:\proj\vcpkg\toolsrc\include\pch.h(28): fatal error C1083: Cannot open include file: 'shlobj.h': No such file
        or directory [C:\proj\vcpkg\toolsrc\vcpkglib\vcpkglib.vcxproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:02.81
Copy-Item : Cannot find path 'C:\proj\vcpkg\toolsrc\Release\vcpkg.exe' because it does not exist.
At C:\proj\vcpkg\scripts\bootstrap.ps1:34 char:5
+     Copy-Item $vcpkgSourcesPath\Release\vcpkg.exe $vcpkgRootDir\vcpkg ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\proj\vcpkg\toolsrc\Release\vcpkg.exe:String) [Copy-Item], ItemNotFou
   ndException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.CopyItemCommand

Copy-Item : Cannot find path 'C:\proj\vcpkg\toolsrc\Release\vcpkgmetricsuploader.exe' because it does not exist.
At C:\proj\vcpkg\scripts\bootstrap.ps1:35 char:5
+     Copy-Item $vcpkgSourcesPath\Release\vcpkgmetricsuploader.exe $vcp ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\proj\vcpkg\t...icsuploader.exe:String) [Copy-Item], ItemNotFoundExce
   ption
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.CopyItemCommand

**Comment by rajnishc8** [comment]
Solution to above issue is given in Issue#922.

Answer is : In script file vcpkg\scripts\bootstrap.ps1, set following

$windowsSDK = '10.0.14393.0'

**Comment by AuroraDysis** [comment]
Sorry I wrongly guided you, the actual problem should be you only install the 10.0.10563.0 UWP SDK, please open visual studio installer and check the SDK for desktop
@rajnishc8

**Comment by LilyWangL** [comment]
This issue hasn’t been updated in two year, if it is still an issue, please reopen.
