### ISSUE TITLE
[mvfst] New port request

### ISSUE THREAD

**Issue by z6833** [microsoft/vcpkg#9601]
I used the command `.\vcpkg.exe search mvfst` and  got following information .

If your library is not listed, please open an issue at and/or consider making a pull request:
    https://github.com/Microsoft/vcpkg/issues

It seems that there is no library for a facebook project named mvfst ([https://github.com/facebookincubator/mvfst](https://github.com/facebookincubator/mvfst)). 

I can find its main dependency libraries like folly and fizz , what should I do for building the project mvfst using installed library folly and fizz ? Or is there anyway for building mvfst by vcpkg ?
Thanks so much !

**Comment by LilyWangL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
