### ISSUE TITLE
Error: Building package vtk:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by jonohribar** [microsoft/vcpkg#9604]
**Describe the bug**
Instaling the package vtk:x64-windows causes a cmake error

**Environment**
- OS: Windows 10
Package: vtk:x64-windows
Vcpkg version: 2019.09.12-nohash

**To Reproduce**
`.\vcpkg install pcl[openni2,qt,pcap]:x64-windows --featurepackages`

**Expected behavior**
I get the following error:
Error: Building package vtk:x64-windows failed with: BUILD_FAILED

**Failure logs** 
[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/4040181/config-x64-windows-out.log)

**Additional context**
Other posts of similar issue solve it by using an earlier version of cmake such as 3.14.6 or earlier, or the packages default 3.14.0. I attempted a range of cmake versions, none of which were able to change the error. Even deleting my cmake folder and having vcpkg install the default version 3.14.0 did not fix the problem.  

```
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: ninja -v
    Working Directory: D:/DEV/vcpkg/buildtrees/vtk/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      D:\DEV\vcpkg\buildtrees\vtk\config-x64-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:293 (vcpkg_execute_required_process)
  ports/vtk/portfile.cmake:91 (vcpkg_configure_cmake)
  scripts/ports.cmake:94 (include)


Error: Building package vtk:x64-windows failed with: BUILD_FAILED
```

**Comment by larshg** [comment]
Hi @jonohribar 

I have the same problem in #9322 - make sure you compiled Proj4 and vtk/pcl with the same version of Visual studio.

Then it worked for me.

**Comment by jonohribar** [comment]
Solved issue by installing component "Windows 10 SDK (10.0.18362.0)" through Visual Studio Installer

**Comment by SLAMFuture** [comment]
"Windows 10 SDK (10.0.18362.0)" requires visual studio 2019, other versions may not be recognized； oh， fuck MicroSoft...
