### ISSUE TITLE
Error: Building package openni2:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by jonohribar** [microsoft/vcpkg#9612]
**Describe the bug**
Instaling the package openni2:x64-windows causes a build error

**Environment**
- OS: Windows 10 SDK (10.0.18362.0)
Package: openni2:x64-windows
Vcpkg version: 2019.09.12-nohash

**To Reproduce**
`.\vcpkg install pcl[openni2,qt,pcap]:x64-windows --featurepackages`
or
`.\vcpkg install openni2:x64-windows`

**Failure logs** 
[patch-x64-windows-2-err.log](https://github.com/microsoft/vcpkg/files/4043531/patch-x64-windows-2-err.log)
[patch-x64-windows-0-err.log](https://github.com/microsoft/vcpkg/files/4043534/patch-x64-windows-0-err.log)
[patch-x64-windows-1-err.log](https://github.com/microsoft/vcpkg/files/4043535/patch-x64-windows-1-err.log)
[x64-windows.vcpkg_abi_info.txt](https://github.com/microsoft/vcpkg/files/4043536/x64-windows.vcpkg_abi_info.txt)

**Additional context**
I followed the advice from #1926 and #4092, but it had no effect. 

```
The following packages will be built and installed:
  * openni2[core]:x64-windows
    pcl[core,openni2,pcap,qt]:x64-windows
  * winpcap[core]:x64-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/3: openni2:x64-windows
Building package openni2[core]:x64-windows...
-- Using cached D:/DEV/vcpkg/downloads/OpenNI-OpenNI2-2.2-beta2.tar.gz
-- Extracting source D:/DEV/vcpkg/downloads/OpenNI-OpenNI2-2.2-beta2.tar.gz
-- Applying patch upgrade_projects.patch
-- Applying patch inherit_from_parent_or_project_defaults.patch
-- Applying patch replace_environment_variable.patch
CMake Error at scripts/cmake/vcpkg_apply_patches.cmake:52 (message):
  Applying patch failed.  Patch needs to be updated to work with source being
  used by vcpkg!
Call Stack (most recent call first):
  scripts/cmake/vcpkg_extract_source_archive_ex.cmake:134 (vcpkg_apply_patches)
  scripts/cmake/vcpkg_from_github.cmake:139 (vcpkg_extract_source_archive_ex)
  ports/openni2/portfile.cmake:15 (vcpkg_from_github)
  scripts/ports.cmake:94 (include)
```

**Comment by PhoebeHui** [comment]
@jonohribar, I can't repro this issue.

The hash value for failed patch 'replace_environment_variable.patch' in my local machine is different with yours, for me, it's 'replace_environment_variable.patch 2ce4d5e031cccfd1d839828d7d478b4270fad9c3', others are same with yours, so I guess the patch file in your machine doesn't update,
could you remove patch 'replace_environment_variable.patch' and checkout this file again? then clean the buildtrees and try to build openni2 again.

Everything works well for me:
Starting package 2/2: openni2:x64-windows
Building package openni2[core]:x64-windows...
-- Downloading https://github.com/OpenNI/OpenNI2/archive/2.2-beta2.tar.gz...
-- Extracting source F:/VCPKG/src/downloads/OpenNI-OpenNI2-2.2-beta2.tar.gz
-- Applying patch upgrade_projects.patch
-- Applying patch inherit_from_parent_or_project_defaults.patch
-- Applying patch replace_environment_variable.patch
-- Using source at F:/VCPKG/src/buildtrees/openni2/src/2.2-beta2-bffbc37bdc
-- Building F:/VCPKG/src/buildtrees/openni2/src/2.2-beta2-bffbc37bdc/OpenNI.sln for Release
-- Building F:/VCPKG/src/buildtrees/openni2/src/2.2-beta2-bffbc37bdc/OpenNI.sln for Debug
...
-- Performing post-build validation
-- Performing post-build validation done
Building package openni2[core]:x64-windows... done
Installing package openni2[core]:x64-windows...
Installing package openni2[core]:x64-windows... done
Elapsed time for package openni2:x64-windows: 4.155 min

Total elapsed time: 4.875 min

**Comment by jonohribar** [comment]
I'm not sure I understand what you mean by "remove patch 'replace_environment_variable.patch' and checkout this file again". I deleted the file, and replaced it with the current version on the github [here](https://github.com/microsoft/vcpkg/blob/master/ports/openni2/replace_environment_variable.patch). I then deleted the openni2 file in my buildtrees and ran the vcpkg install again and got no change.

**Comment by PhoebeHui** [comment]
@jonohribar, sorry for my late reply.

Could you try the following steps and see if this issue still occur?
1. Delete replace_environment_variable.patch
2. Go to .\vcpkg\ports\openni2 , and execute 'git checkout replace_environment_variable.patch'
3. Remove openni2 source under buildtreev
4. ./vcpkg install openni2:x64-windows

**Comment by jonohribar** [comment]
That did it!
