### ISSUE TITLE
How do I solve compiler error C2733 between Boost and Windows 10 Kits when using PCL?

### ISSUE THREAD

**Issue by bhwqy** [microsoft/vcpkg#9615]
I install Boost 1.71 and PCL 1.9.1 with latest vcpkg release. There is no error when installing. However, when trying to run [the example code](http://pointclouds.org/documentation/tutorials/writing_pcd.php), the compiler error C2733 occurs:

[PCL_example_release_x64_build_out.txt](https://github.com/microsoft/vcpkg/files/4044826/PCL_example_release_x64_build_out.txt)

OS: Windows 10 latest
Compiler: VS2019 latest

**Comment by jonohribar** [comment]
Hi, I think I have the same problem. I also installed PCL 1.9.1 and its dependancies using vcpkg and have a similar result. 
[Output.txt](https://github.com/microsoft/vcpkg/files/4049345/Output.txt)

**Comment by wnkai** [comment]
Hi, I have the same problem. I try to add those lines to Preprocessor Definitions and it's resolved.
```
NOMINMAX
BOOST_USE_WINDOWS_H
_CRT_SECURE_NO_WARNINGS
```
![Snipaste_2020-01-12_16-18-07](https://user-images.githubusercontent.com/30250878/72216136-142b5600-3558-11ea-9f25-ca75f0e9b351.jpg)

**Comment by jonohribar** [comment]
@wnkai that solved a number of my errors, but I still get the folowing output errors:
[Output 2.txt](https://github.com/microsoft/vcpkg/files/4050420/Output.2.txt)
