### ISSUE TITLE
[ffmpeg] ffmpeg tools aren't installed after build

### ISSUE THREAD

**Issue by longnguyen2004** [microsoft/vcpkg#9619]
**Describe the bug**
After installing ffmpeg, the tools aren't installed in the tools folder. I've checked the build tree, they did get built, just aren't installed

**Environment**
- OS: Windows 7 x64
- Compiler: MSVC 19.24.28314

**To Reproduce**
1. ./vcpkg install ffmpeg[ffmpeg]

**Comment by JackBoosY** [comment]
Hi @longnguyen2004, thanks for reporting this issue.
I've fixed it, please update vcpkg and rebuild ffmpeg.

Thanks.
