### ISSUE TITLE
[llvm] llvm-config tool points to wrong file paths

### ISSUE THREAD

**Issue by SeekingMeaning** [microsoft/vcpkg#9622]
**Describe the bug**
- llvm-config sees LLVM’s root directory as `<vcpkg path>/packages/llvm_x64-windows-static/tools`
- i.e. the command `llvm-config --includedir` incorrectly returns the value `<vcpkg path>/packages/llvm_x64-windows-static/tools/include`
- The following also return incorrect values:
  - `llvm-config --libdir`
  - `llvm-config --bindir`
  - `llvm-config --obj-dir`
  - etc.
- See https://releases.llvm.org/8.0.0/docs/CommandGuide/llvm-config.html for a complete list of flags

**Environment**
- OS: tested on Windows and macOS (probably applies to Linux as well)
- Compiler: revision current

**To Reproduce**
1. `vcpkg install llvm:x64-windows-static`
    - `llvm:x64-osx` on macOS
    - takes several hours to build
2. `cd packages/llvm_x64-windows-static/tools/llvm`
3. `llvm-config --includedir`

**Expected behavior**
- llvm-config should see its root directory as `<vcpkg path>/packages/llvm_x64-windows-static`
- i.e. `llvm-config --includedir` should return `<vcpkg path>/packages/llvm_x64-windows-static/include`

**Failure logs** 
None

**Additional context**
vcpkg currently uses the option `-DLLVM_TOOLS_INSTALL_DIR=tools/llvm` to set the install directory. I’m not sure if LLVM even has options to set include, lib, etc. directories.

**Comment by JackBoosY** [comment]
@SeekingMeaning Why close this issue? Does this issue resolved?

**Comment by Voskrese** [comment]
@SeekingMeaning 
llvm-config won't work in vcpkg
delete the script that is associated with it and enter it manually

**Comment by JackBoosY** [comment]
I will track this issue in #10559.
