### ISSUE TITLE
[openal-soft x86 / x64] build failure

### ISSUE THREAD

**Issue by Christsnatcher** [microsoft/vcpkg#9628]
**Host Environment**
- Windows 8.1 x64
- MSVC++ 14.24 _MSC_VER == 1924 _MSC_FULL_VER == 192428314 Visual Studio 2019

**To Reproduce**
vcpkg install openal-soft:x86-windows
or
vcpkg install openal-soft:x64-windows

**Failure logs** 
D:\Code\Repos\vcpkg>vcpkg install openal-soft
The following packages will be built and installed:
    openal-soft[core]:x86-windows
Starting package 1/1: openal-soft:x86-windows
Building package openal-soft[core]:x86-windows...
-- Using cached D:/Code/Repos/vcpkg/downloads/kcat-openal-soft-openal-soft-1.20.0.tar.gz
-- Extracting source D:/Code/Repos/vcpkg/downloads/kcat-openal-soft-openal-soft-1.20.0.tar.gz
-- Applying patch dont-export-symbols-in-static-build.patch
-- Applying patch fix-arm-builds.patch
-- Using source at D:/Code/Repos/vcpkg/buildtrees/openal-soft/src/oft-1.20.0-ddebb59924
-- Configuring x86-windows
-- Building x86-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- /p:VCPkgLocalAppDataDisabled=true /p:UseIntelMKL=No /m
    Working Directory: D:/Code/Repos/vcpkg/buildtrees/openal-soft/x86-windows-dbg
    See logs for more information:
      D:\Code\Repos\vcpkg\buildtrees\openal-soft\install-x86-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:91 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/openal-soft/portfile.cmake:58 (vcpkg_install_cmake)
  scripts/ports.cmake:94 (include)

Error: Building package openal-soft:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: openal-soft:x86-windows
  Vcpkg version: 2019.09.12-nohash

**Additional context**
Hello, I already figured the reasons for the build failing out myself, but unfortunately I'm not able to resolve the issue generally. When cmake configures, it automatically (???) targets the Windows 8.1 SDK as it recognizes that this matches my OS. Now, unluckily building is done against the latest Windows 10 SDK, which results in the build failing (see the attached logfiles). I - temporarily - fixed this by altering the resp. portfile.cmake file the following way:

```
vcpkg_configure_cmake(
    SOURCE_PATH ${SOURCE_PATH}
    OPTIONS
        -DLIBTYPE=${OPENAL_LIBTYPE}
        -DALSOFT_UTILS=OFF
```

to

```
vcpkg_configure_cmake(
    SOURCE_PATH ${SOURCE_PATH}
    OPTIONS
	-DCMAKE_SYSTEM_VERSION=10.0.18362.0
        -DLIBTYPE=${OPENAL_LIBTYPE}
        -DALSOFT_UTILS=OFF
```
This way cmake targets the latest Win 10 SDK right from the beginning and the build succeeds. Despite being glad about this "fix", I would rather like to be able to build this - pretty important - package without having to alter its portfile after every update, so I'd be very thankful for some helpful tips / ideas.

[openal-soft.zip](https://github.com/microsoft/vcpkg/files/4049378/openal-soft.zip)

**Comment by Christsnatcher** [comment]
Hello,

since openal-soft got updated today and building it the normal way still fails I thought it would be a good time to ask if someone actually still works on resolving "my" 6-month old issue.

Thank you very much.

**Comment by NancyLi1013** [comment]
Closing this issue since it has been solved.
Please see comments here https://github.com/microsoft/vcpkg/issues/12935#issuecomment-674798858
