### ISSUE TITLE
[x64] boost-compatibility:x64-windows

### ISSUE THREAD

**Issue by YohanVianna** [microsoft/vcpkg#9634]
Hello, I tried

./vcpkg install boost-iostreams:x64-windows boost-asio:x64-windows boost-system:x64-windows boost-filesystem:x64-windows boost-variant:x64-windows boost-lockfree:x64-windows luajit:x64-windows libmariadb:x64-windows pugixml:x64-windows mpir:x64-windows cryptopp:x64-windows

And most of the packs installed correctly. But at the end I got this bug message:

-- Downloading https://raw.githubusercontent.com/boostorg/boost/boost-1.71.0/LICENSE_1_0.txt... Failed. Status: 28;"Timeout was reached"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:175 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  installed/x64-windows/share/boost-vcpkg-helpers/boost-modular-headers.cmake:17 (vcpkg_download_distfile)
  ports/boost-compatibility/portfile.cmake:14 (boost_modular_headers)
  scripts/ports.cmake:94 (include)

Error: Building package boost-compatibility:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-compatibility:x64-windows
  Vcpkg version: 2019.09.12-nohash

**Comment by YohanVianna** [comment]
I have already solved it.

**Comment by orange-stone** [comment]
> I have already solved it.

how，I really appreciate it if you can  tell me
