### ISSUE TITLE
cpprestsdk x86-uwp build failure

### ISSUE THREAD

**Issue by mediabuff** [microsoft/vcpkg#9637]
1) Log file
[install-x86-uwp-dbg-out.log](https://github.com/microsoft/vcpkg/files/4050504/install-x86-uwp-dbg-out.log)
2) screen shot
![image](https://user-images.githubusercontent.com/5080114/72217346-aa309380-34fa-11ea-9ff8-41602dee0b63.png)

**Comment by PhoebeHui** [comment]
Duplicated to https://github.com/microsoft/vcpkg/issues/7540.
