### ISSUE TITLE
Policy DLLS_WITHOUT_EXPORTS

### ISSUE THREAD

**Issue by martin-s** [microsoft/vcpkg#9641]
**Is your feature request related to a problem? Please describe.**
In ports for which shared libraries generate no export files (e.g. OSG), the post checks fail.

**Proposed solution**
See pull request.

**Describe alternatives you've considered**
Introduce a policy to ignore the post checks (VCPKG_POLICY_DLLS_WITHOUT_EXPORTS).

**Comment by Neumann-A** [comment]
Maybe a stupid question: Does a DLL without any exports achieve anything?

**Comment by martin-s** [comment]
At least for the case of OSG, there are plugins which live without a lib and exp-file.
Second: In all normal cases, there is no use case to import these in any other library.

What I can think of is to combine the two checks (DLL_WITHOUT_LIB, DLL_WITHOUT_EXPORT) into one check. As normally a lib comes with an exp.

For now, these effects are seen in the port file which include some copy workarounds. If these changes are incorporated, the port file of OSG could be simplified.

**Comment by Neumann-A** [comment]
maybe move the files into `plugins/osg` instead (like Qt plugins). VCPKG will not deploy any of the plugins if they are not visible with `dumpbin` or similar so a manual deployment will be necessary. If the files are in an extra folder deployment of the plugin becomes trivial.

**Comment by martin-s** [comment]
What you describe is the approach we're coming from. In the OSG portfile the affected shared libraries are copied to another folder. But you have to take care of the changes afterwards again. IMO, this is a hack and should be replaced by this PR.

**Comment by JackBoosY** [comment]
Close this issue via #9642 merged.
