### ISSUE TITLE
How do I CMake install a library from vcpkg

### ISSUE THREAD

**Issue by davidhunter22** [microsoft/vcpkg#9643]
Hi, I recently started using vcpkg and it's all been great. However I'm not sure the best or correct way to install a library I am using from vcpkg. 
For instance I used to build pugxml in my own code base which was built using a hand crafted CMakeLists.txt. Part of that CMakeLists.txt was a CMake install command to install the DLL that was built. I install the DLL into the same tree as all the other DLL's that get built to avoid having to mess around with runtime PATH settings.
So now I use pugixml from vcpkg which builds fine, however how should I replace the "install". I am no longer building the library to I have no CMake target, also it's not clear for any given package what things I should install for runtime. At the moment I am hard coding paths an library names in my install which seems wrong.
So is there a standard way to do this?

**Comment by JackBoosY** [comment]
Hi @davidhunter22, thanks for reporting this issue!
You can use command `.\vcpkg integrate install` then add `-DCMAKE_TOOLCHAIN_FILE=VCPKG_PATH\\scripts\\buildsystems\\vcpkg.cmake` to your project configuration.

See [documentation](https://github.com/microsoft/vcpkg/blob/master/docs/users/integration.md).

Thanks.

**Comment by davidhunter22** [comment]
No, this wasn't a question about to use a vcpkg I can do that fine as I mentioned with pugixml. This is about how I call CMake install in my own project to install a library, say pugixml.dll, from the vcpkg tree to wherever I am installing the rest of my project.

**Comment by JackBoosY** [comment]
See https://github.com/microsoft/vcpkg/issues/13797#issuecomment-700605701

**Comment by JackBoosY** [comment]
Please track this issue in #14203.

Thanks.
