### ISSUE TITLE
vcpkg.exe does nothing and exits

### ISSUE THREAD

**Issue by dargonforce** [microsoft/vcpkg#9644]
**Describe the bug**
Regardless of what arguments I pass to vcpkg.exe it does nothing and exits, giving no error.

**Environment**
- OS: Windows
- Compiler: MSVC v142

**To Reproduce**
1. .\bootstrap-vcpkg.bat
2. .\vcpkg.exe

**Expected behavior**
Literally any output at all

**Failure logs** 
None

**Additional context**
None

**Comment by dargonforce** [comment]
I can confirm that I've successfully built and used vcpkg on my other Windows machine, following the same steps, with the same version of MSVC, so it's not just me being an idiot.  There must be something subtly wrong with that environment.

**Comment by dargonforce** [comment]
When running vcpkg.exe as a non-administrator I get the following popup error

> The application was unable to start correctly (0xc000007b). Click OK to close the application.

**Comment by PhoebeHui** [comment]
@dargonforce, thanks for reporting this issue.

However, I can't repro this issue. Could you get latest vcpkg source and try to rebuild it again?
 @vicroms, any thoughts? I have no idea.

**Comment by vicroms** [comment]
Hi @dargonforce 

Could you check that your anti-virus software isn't blocking VCPKG? Some users have reported their AV false-positively flagging VCPKG due to the telemetry code. 

If that's the case, try building vcpkg with no telemetry

`./bootstrap-vcpkg.bat -disableMetrics`

**Comment by dargonforce** [comment]
I've pulled the latest master and rebuilt, and the application is now working fine.  There's no indication from my anti-virus that anything was going on.

Thank you for the support :)
