### ISSUE TITLE
[halide] Support to build tools

### ISSUE THREAD

**Issue by 3250** [microsoft/vcpkg#9647]
I want to use libraries in [Halide/tools](https://github.com/halide/Halide/tree/master/tools) . (e.g. halide_image_io.h)

Please add libraries.

Library name:halide[tools]

Source repository URL:
Halide URL | [https://github.com/halide/Halide](https://github.com/halide/Halide)
Hallide/tools URL | [https://github.com/halide/Halide/tree/master/tools](https://github.com/halide/Halide/tree/master/tools)

**Comment by 3250** [comment]
I used this for the first time.
Sorry for the trouble.
And, thanks for the better.

**Comment by alexreinking** [comment]
The current Halide port installs halide_image_io.h and the `Halide::Tools` CMake target. This issue should be closed.
