### ISSUE TITLE
can not link to boost.log

### ISSUE THREAD

**Issue by 57Hao** [microsoft/vcpkg#9653]
I installed the latest VCPKG and vs2019.
On this environment, I installed boost1.71, but vs2019 could not link to boost.log.
I think this is probably due to a versioning error in the build library. The resulting library is boost_log-vc140-mt.lib.

**Comment by PhoebeHui** [comment]
@57Hao, could you proving us more information? eg, the repro steps and the failure logs.

**Comment by PhoebeHui** [comment]
If it is still an issue, please reopen and provide us more information.
