### ISSUE TITLE
[xerces-c] https://github.com/apache/xerces-c/archive/Xerces-C_3_2_2.tar.gz no longer exist 

### ISSUE THREAD

**Issue by hailIulius** [microsoft/vcpkg#9654]
Package: xerces-c:x86-windows
    Vcpkg version: 2019.09.12-nohash

The link https://github.com/apache/xerces-c/archive/Xerces-C_3_2_2.tar.gz no longer exist at this location

  -- Downloading
  https://github.com/apache/xerces-c/archive/Xerces-C_3_2_2.tar.gz...

  -- Downloading
  https://github.com/apache/xerces-c/archive/Xerces-C_3_2_2.tar.gz...
  Failed.  Status: 22;"HTTP response code said error"

  CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:175 (message):

        
        Failed to download file.
        If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
        variables to "https://user:password@your-proxy-ip-address:port/".
        Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

**Comment by hailIulius** [comment]
I think a possible approach will be to replace the broken link with https://www.apache.org/dist/xerces/c/3/sources/xerces-c-3.2.2.tar.gz

**Comment by hailIulius** [comment]
in order to fix I need to replace the following vcpkg\ports\xerces-c\portfile.cmake

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO apache/xerces-c
    REF v3.2.2
    SHA512 e4b2d3499fb4d1d1bcaf991ee858f352112683084b9cc7855c0e52e7fc8cc982a8e3cd548fa30718af6a6dee40e460d82ffcd3480a50f7e7516b462b2c2080c6
    HEAD_REF trunk
    PATCHES
        disable-tests.patch
        remove-dll-export-macro.patch
        no-symlinks-in-static-build.patch
)

**Comment by hailIulius** [comment]
OK, I create my very first pull request : https://github.com/microsoft/vcpkg/pull/9655 with the changes described in the previous comment

**Comment by crusader-mike** [comment]
... you probably already noticed that `xerces-c` port isn't using `https://github.com/apache/xerces-c/archive/Xerces-C_3_2_2.tar.gz` for a very long time

**Comment by JackBoosY** [comment]
Hi @hailIulius, thanks for reporting this issue!
This issue fixed in #9654, please update vcpkg and rebuild xerces-c.

Thanks.
