### ISSUE TITLE
[New Port Request] <WiringPI/WiringPI>

### ISSUE THREAD

**Issue by bramburn** [microsoft/vcpkg#9659]
Library name:
wiringPi
Library description:
This is a port of WiringPI library for c++ for the vcpkg
Source repository URL:
https://github.com/bramburn/WiringPi/
Project homepage (if different from the source repository):
https://github.com/WiringPi/WiringPi/
Anything else that is useful to know when adding (such as optional features the library may have that should be included):
This is only for arm-linux builds

here are the files:

[wiringpi.zip](https://github.com/microsoft/vcpkg/files/4053795/wiringpi.zip)

**Comment by bramburn** [comment]
i'll make a PR instead.

**Comment by LilyWangL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
