### ISSUE TITLE
OpenCV link bug

### ISSUE THREAD

**Issue by how0723** [microsoft/vcpkg#9661]
**Describe the bug**
OpenCV library can be compiled successfully on Linux x64 platform. But with link error to executable program. 

**Environment**
- OS: [e.g. Windows/Linux etc...] Linux x64 / Debian 10.2
- Compiler: gcc8.3

**To Reproduce**
1. ./vcpkg install xxxx
2. See error
Repro code when

**Expected behavior**

**Failure logs** 
-(please attached failure logs)

**Additional context**

**Comment by LilyWangL** [comment]
Hi @how0723, thanks for posting this issue. Could you provide the repro codes and error log?

**Comment by how0723** [comment]
same as https://github.com/microsoft/vcpkg/issues/9662
@LilyWangL

**Comment by how0723** [comment]
`#include
#include
#include <opencv2/opencv.hpp>
using namespace std;

int main() {
cv::Mat img;
img.create(cv::Size(1000,1000),CV_8UC3);
cv::imwrite("test.png",img);
return 0;
}`

`cmake_minimum_required(VERSION 3.15)

project(usb_cam)

set(CMAKE_CXX_STANDARD 11)

IF (CMAKE_SYSTEM_NAME MATCHES "Linux")
MESSAGE(STATUS "current platform: Linux ")
set(CMAKE_PREFIX_PATH ${CMAKE_PREFIX_PATH} /home/yehao/vcpkg/packages/opencv4_x64-linux/share/opencv)
FIND_PACKAGE(OpenCV CONFIG REQUIRED)
include_directories(${OpenCV_INCLUDE_DIRS})
ELSEIF (CMAKE_SYSTEM_NAME MATCHES "Windows")
MESSAGE(STATUS "current platform: Windows")
set(CMAKE_PREFIX_PATH ${CMAKE_PREFIX_PATH} D:\tools\vcpkg\installed\x64-windows\share\opencv)
FIND_PACKAGE(OpenCV CONFIG REQUIRED)
include_directories(${OpenCV_INCLUDE_DIRS})
ELSE ()
MESSAGE(STATUS "other platform: ${CMAKE_SYSTEM_NAME}")
ENDIF (CMAKE_SYSTEM_NAME MATCHES "Linux")

include_directories(src)

file(GLOB_RECURSE SRC_FILES src/*.cpp *.h)

add_executable(usb_cam ${SRC_FILES})
target_link_libraries(usb_cam PRIVATE opencv::opencv_core opencv::opencv_imgcodecs opencv::opencv_imgproc)`

**Comment by how0723** [comment]
sorry. is my fault.
I forgot to add CMAKE_TOOLCHAIN_FILE=the_right_path
@LilyWangL

**Comment by JaosonMa** [comment]
> sorry. is my fault.
> I forgot to add CMAKE_TOOLCHAIN_FILE=the_right_path
> @LilyWangL

@how0723  where to add the CMAKE_TOOLCHAIN_FILE?
