### ISSUE TITLE
protobuf not found on linux platform

### ISSUE THREAD

**Issue by how0723** [microsoft/vcpkg#9662]
**Describe the bug**
protobuf not found on linux platform. i guess it due to case sensitive on linux platform. 
cmake use FindProtobuf, buf vcpkg use protobuf.

**Environment**
- OS: [e.g. Windows/Linux etc...] Linux 
- Compiler: gcc8.3

**To Reproduce**
1. ./vcpkg install xxxx
2. See error
Repro code when

**Expected behavior**

**Failure logs** 
-(please attached failure logs)

**Additional context**

**Comment by LilyWangL** [comment]
Hi @how0723, thanks for posting this issue. Could you provide your CMakeLists.txt code and the error log? I can't reproduce this issue on Linux. I use find_package to find protobuf successfully. My code as below:
```
cmake_minimum_required (VERSION 3.9)

project (testone)

add_executable(testone main.cpp)

find_package(protobuf CONFIG REQUIRED)
target_link_libraries(testone PRIVATE protobuf::libprotoc protobuf::libprotobuf protobuf::libprotobuf-lite)
```

**Comment by how0723** [comment]
I know, but OpenCV find protobuf use "Protobuf", Linux is case-sensitive which windows is not. so OpenCV via vcpkg on Linux can not find Protobuf, but windows can.

**Comment by how0723** [comment]
fail log:
-- The C compiler identification is GNU 8.3.0
-- The CXX compiler identification is GNU 8.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- current platform: Linux 
CMake Error at /home/yehao/tools/cmake-3.16.2-Linux-x86_64/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find Protobuf (missing: Protobuf_INCLUDE_DIR)
Call Stack (most recent call first):
  /home/yehao/tools/cmake-3.16.2-Linux-x86_64/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  /home/yehao/tools/cmake-3.16.2-Linux-x86_64/share/cmake-3.16/Modules/FindProtobuf.cmake:624 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  /home/yehao/vcpkg/packages/opencv4_x64-linux/share/opencv/OpenCVModules.cmake:14 (find_package)
  /home/yehao/vcpkg/packages/opencv4_x64-linux/share/opencv/OpenCVConfig.cmake:126 (include)
  CMakeLists.txt:14 (FIND_PACKAGE)


-- Configuring incomplete, errors occurred!
See also "/home/yehao/project/usb_cam/bin/CMakeFiles/CMakeOutput.log".
See also "/home/yehao/project/usb_cam/bin/CMakeFiles/CMakeError.log".
make: *** 没有指明目标并且找不到 makefile。 停止。



@LilyWangL

**Comment by how0723** [comment]
CMakeLists file content :

cmake_minimum_required(VERSION 3.15)

project(usb_cam)

set(CMAKE_CXX_STANDARD 11)

IF (CMAKE_SYSTEM_NAME MATCHES "Linux")
    MESSAGE(STATUS "current platform: Linux ")
    set(CMAKE_PREFIX_PATH ${CMAKE_PREFIX_PATH} /home/yehao/vcpkg/packages/opencv4_x64-linux/share/opencv)
    FIND_PACKAGE(OpenCV CONFIG REQUIRED)
    include_directories(${OpenCV_INCLUDE_DIRS})
ELSEIF (CMAKE_SYSTEM_NAME MATCHES "Windows")
    MESSAGE(STATUS "current platform: Windows")
    set(CMAKE_PREFIX_PATH ${CMAKE_PREFIX_PATH} D:\\tools\\vcpkg\\installed\\x64-windows\\share\\opencv)
    FIND_PACKAGE(OpenCV CONFIG REQUIRED)
    include_directories(${OpenCV_INCLUDE_DIRS})
ELSE ()
    MESSAGE(STATUS "other platform: ${CMAKE_SYSTEM_NAME}")
ENDIF (CMAKE_SYSTEM_NAME MATCHES "Linux")

include_directories(src)

file(GLOB_RECURSE SRC_FILES src/*.cpp *.h)

add_executable(usb_cam ${SRC_FILES})
target_link_libraries(usb_cam PRIVATE opencv::opencv_core opencv::opencv_imgcodecs opencv::opencv_imgproc)

**Comment by how0723** [comment]
and code is:

#include <iostream>
#include <string>
#include <opencv2/opencv.hpp>
using namespace std;

int main() {
    cv::Mat img;
    img.create(cv::Size(1000,1000),CV_8UC3);
    cv::imwrite("test.png",img);
    return 0;
}


@LilyWangL

**Comment by LilyWangL** [comment]
Hi @how0723, I can't reproduce this issue with your CMakeLists.txt. Did you do other steps before you cmake project? This is my log:
```
-- The C compiler identification is GNU 7.4.0
-- The CXX compiler identification is GNU 7.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- current platform: Linux
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found Protobuf: /home/Lily/issue9662/vcpkg/installed/x64-linux/lib/libprotobuf.a;-lpthread (found version "3.11.2")
-- Found JPEG: /home/Lily/issue9662/vcpkg/installed/x64-linux/debug/lib/libjpeg.a
-- Found ZLIB: /home/Lily/issue9662/vcpkg/installed/x64-linux/debug/lib/libz.a (found version "1.2.11")
-- Found OpenCV: /home/Lily/issue9662/vcpkg/installed/x64-linux (found version "4.1.1")
-- Configuring done
```

**Comment by how0723** [comment]
sorry. is my fault.
i forgot to add CMAKE_TOOLCHAIN_FILE=some_path
@LilyWangL
