### ISSUE TITLE
Socket Programming Headers not found

### ISSUE THREAD

**Issue by niharbansal02** [microsoft/vcpkg#9666]
***Socket Programming headers not found on vcpkg***

**Proposed solution**
Please add the following libraries to vcpkg
<sys/socket.h>
<arpa/inet.h>
<netinet.h>
<sys/types.h>

I've started using CodeBlocks on Linux as an alternative.

**Comment by LilyWangL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
