### ISSUE TITLE
[azure-kinect-sensor-sdk] k4a.dll and k4arecord.dll is not installed

### ISSUE THREAD

**Issue by jasjuang** [microsoft/vcpkg#9667]
**Describe the bug**
After installing `azure-kinect-sensor-sdk`, I expect the built k4a.dll to be installed, but it's not.

**Environment**
- OS: Windows 10
- Compiler: VS 2017

**To Reproduce**
1. `vcpkg install azure-kinect-sensor-sdk`
2. Look at `vcpkg/installed/x64-windows/bin`, there is `k4a.pdb` and `k4arecord.pdb` but no `k4a.dll` and `k4arecord.dll`. However, if you look into the buildtree at `vcpkg/buildtree/azure-kinect-sensor-sdk/x64-windows-rel/bin/Release`, you can see that there are `k4a.pdb`, `k4arecord.pdb`,  `k4a.dll` and `k4arecord.dll`.

Same problem exists in debug mode as well. Can someone please fix it?

**Comment by JackBoosY** [comment]
Sorry, it looks like my PR #9458 broke it.

**Comment by LilyWangL** [comment]
Thanks for posting this issue. This issue has been fixed. So I am closing this issue for now.
