### ISSUE TITLE
[azure-kinect-sensor-sdk] depth engine dll is required to be fully functional 

### ISSUE THREAD

**Issue by jasjuang** [microsoft/vcpkg#9668]
**Describe the bug**
After temporarily solve #9667 by manually copy the `k4a.dll` and `k4arecord.dll` from the buildtree folder into the installed folder, my downstream application for capturing RGB camera is able to work but unfortunately not the depth camera, and this is due to a depth engine dll missing. As indicated in [here](https://github.com/microsoft/Azure-Kinect-Sensor-SDK/blob/develop/docs/depthengine.md), the depth engine dll is not included in the SDK directly, it is distributed as part of all Azure Kinect Sensor SDK binary releases, so currently I had to run the Windows binary installer for the Azure Kinect Sensor SDK, manually copy the depth engine dll into my downstream folder in order to make my downstream application fully functional. It seems to me that the depth engine dll is dynamically loaded. 

Is it possible to modify the port file in a way that so vcpkg can automatically download and extract the depth engine dll and install it so for us downstream users don't have to go through the manual steps?

**Environment**
- OS: Windows 10
- Compiler: VS 2017

**Comment by JackBoosY** [comment]
Close this issue via #11139 merged.
