### ISSUE TITLE
Poppler 

### ISSUE THREAD

**Issue by kossiBlaise** [microsoft/vcpkg#9673]
Library name: Poppler

Library description: Poppler is a package to manipulate PDF documents

Source repository URL: https://anongit.freedesktop.org/git/poppler/poppler.git

Project homepage (if different from the source repository): https://poppler.freedesktop.org/releases.html

Anything else that is useful to know when adding (such as optional features the library may have that should be included): We really need to have the VS binaries for this package

**Comment by nazar554** [comment]
duplicate of #4702 ?

**Comment by LilyWangL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.

**Comment by playgithub** [comment]
need poppler
