### ISSUE TITLE
libpq[core,openssl,zlib]:x64-windows build failure version 12.0 after vcpkg upgrade

### ISSUE THREAD

**Issue by timautry** [microsoft/vcpkg#9674]
**Host Environment**
- OS: [Windows 10 Version 1909 (OS Build 18363.535)]
- Compiler: VS2019 v16.4.2 
- VCToolsInstallDir=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\

**To Reproduce**
vcpkg install libpq[core,openssl,zlib]:x64-windows

**Failure logs** 
-Cut and past the appropriate build messages from the console output.
SYSTEM@ANDROMEDA 01/13/2020 21:33:58 D:\Git\vs2019.prod
->vcpkg install libpq[core,openssl,zlib]:x64-windows

The following packages will be built and installed:
    libpq[core,openssl,zlib]:x64-windows
Starting package 1/1: libpq:x64-windows
Building package libpq[core,openssl,zlib]:x64-windows...
-- Using cached E:/Git/vcpkg.downloads/postgresql-12.0.tar.bz2
-- Extracting source E:/Git/vcpkg.downloads/postgresql-12.0.tar.bz2
-- Applying patch patches/windows/install.patch
-- Applying patch patches/windows/win_bison_flex.patch
-- Applying patch patches/windows/openssl_exe_path.patch
-- Applying patch patches/windows/Solution.patch
-- Applying patch patches/linux/configure.patch
-- Applying patch patches/windows/minimize_install.patch
-- Using source at D:/Git/vs2019.prod/buildtrees/libpq/src/tgresql-12-e44317bad5
-- Copying libpq source files to D:/Git/vs2019.prod/buildtrees/libpq/x64-windows-rel...
-- Copying libpq source files... done
-- Applying patch patches/windows/Solution_RELEASE.patch
-- Patches applied!
-- Building libpq x64-windows-RELEASE...
-- Building libpq x64-windows-RELEASE... done
-- Building libecpg_compat x64-windows-RELEASE...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: E:/Git/vcpkg.downloads/tools/perl/perl/bin/perl.exe build.pl RELEASE libecpg_compat
    Working Directory: D:/Git/vs2019.prod/buildtrees/libpq/x64-windows-rel/src/tools/msvc
    Error code: 1
    See logs for more information:
      D:\Git\vs2019.prod\buildtrees\libpq\build-libecpg_compat-x64-windows-RELEASE-out.log

Call Stack (most recent call first):
  ports/libpq/portfile.cmake:194 (vcpkg_execute_required_process)
  scripts/ports.cmake:94 (include)

**Error: Building package libpq:x64-windows failed with: BUILD_FAILED**
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libpq:x64-windows
  Vcpkg version: 2019.09.12-nohash

Additionally, attach any relevant sections from the log files above.
-Please attach any additional failure logs mentioned in the console output.

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.
[build-libpq-x64-windows-RELEASE-out.log](https://github.com/microsoft/vcpkg/files/4057121/build-libpq-x64-windows-RELEASE-out.log)

[build-libecpg_compat-x64-windows-RELEASE-out.log](https://github.com/microsoft/vcpkg/files/4057124/build-libecpg_compat-x64-windows-RELEASE-out.log)

**Comment by Neumann-A** [comment]
will take a look. But last time I build it it worked. 
```
       Lib:
         C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\bin\HostX86\x64\Lib.exe /OUT:".\Release\libecpg_compat\libecpg_compat.lib" /NOLOGO /MACHINE:X64 .\Release\libecpg_compat\win32ver.res
         .\Release\libecpg_compat\informix.obj
         libecpg_compat.vcxproj -> G:\vcpkg_test\libpq_port\buildtrees\libpq\x64-windows-static-rel\.\Release\libecpg_compat\libecpg_compat.lib
       AppLocalFromInstalled:
         C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -ExecutionPolicy Bypass -noprofile -File "G:\vcpkg_test\libpq_port\scripts\buildsystems\msbuild\applocal.ps1" "G:\vcpkg_test\libpq_port\buildtrees\libpq\x64-windows-static-rel\.\Release\libecpg_compat\libecpg_compat.lib" "G:\vcpkg_test\libpq_port\installed\x64-windows-static\bin" ".\Release\libecpg_compat\libecpg_compat.tlog\libecpg_compat.write.1u.tlog" ".\Release\libecpg_compat\vcpkg.applocal.log"
       FinalizeBuildStatus:
         Die Datei ".\Release\libecpg_compat\libecpg_compat.tlog\unsuccessfulbuild" wird gelöscht.
         Aktualisieren des Timestamps von ".\Release\libecpg_compat\libecpg_compat.tlog\libecpg_compat.lastbuildstate".
     1>Die Erstellung von Projekt "G:\vcpkg_test\libpq_port\buildtrees\libpq\x64-windows-static-rel\libecpg_compat.vcxproj" ist abgeschlossen (Standardziele).
```

Will update the toolset to a newer version and see if I can reproduce the problem

**Comment by Neumann-A** [comment]
Cannot reproduce the problem

```
       ClCompile:
         C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\bin\HostX86\x64\CL.exe /c /Isrc/include /Isrc/include/port/win32 /Isrc/include/port/win32_msvc /I"G:/vcpkg_test/libpq_port/installed/x64-windows\include" /I"G:/vcpkg_test/libpq_port/installed/x64-windows\include" /Isrc/interfaces/ecpg/include /Isrc/interfaces/libpq /Isrc/port /I"G:\vcpkg_test\libpq_port\installed\x64-windows\include" /Zi /nologo /W3 /WX- /diagnostics:column /Ox /D WIN32 /D _WINDOWS /D __WINDOWS__ /D __WIN32__ /D EXEC_BACKEND /D WIN32_STACK_RLIMIT=4194304 /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D FRONTEND /D _WINDLL /D _MBCS /GF /Gm- /EHsc /MD /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo".\Release\libecpg\\" /Fd".\Release\libecpg\vc142.pdb" /Gd /TC /wd4018 /wd4244 /wd4273 /wd4102 /wd4090 /wd4267 /FC /errorReport:queue /MP src/interfaces/ecpg/ecpglib/connect.c src/interfaces/ecpg/ecpglib/data.c src/interfaces/ecpg/ecpglib/descriptor.c src/interfaces/ecpg/ecpglib/error.c src/interfaces/ecpg/ecpglib/execute.c src/interfaces/ecpg/ecpglib/memory.c src/interfaces/ecpg/ecpglib/misc.c src/interfaces/ecpg/ecpglib/prepare.c src/interfaces/ecpg/ecpglib/sqlda.c src/interfaces/ecpg/ecpglib/typename.c
         connect.c
         data.c
         descriptor.c
         error.c
         execute.c
         memory.c
         misc.c
         prepare.c
         sqlda.c
         typename.c
       ResourceCompile:
         C:\Program Files (x86)\Windows Kits\10\bin\10.0.18362.0\x86\rc.exe /l"0x0409" /Isrc\include /I"G:\vcpkg_test\libpq_port\installed\x64-windows\include" /nologo /fo".\Release\libecpg\win32ver.res" src/interfaces/ecpg/ecpglib/win32ver.rc 
       Link:
```

Did you modify your environment in some way?

**Comment by timautry** [comment]
@Neumann-A @PhoebeHui @NancyLi1013 
Ok, I deleted my complete vcpkg locally, created a fork, pulled a new copy down to my laptop, compiled and linked with the newest VS updates (vs 16.4.3 and vs 15.9.19) - I was able to compile libpg[core,openssl,zlib] with no problems.
