### ISSUE TITLE
Ceres static libraries are very large

### ISSUE THREAD

**Issue by anaru** [microsoft/vcpkg#9677]
**Describe the bug**
The Ceres builds in the x64-windows-static configuration are very large: 1.24 GB in release mode, and 1.39 GB in debug mode. When I build Ceres myself, the libs are 47 MB in release mode, and 747 MB in debug. The release mode difference in particular (1.24 GB vs 47 MB) is suspiciously large.

**Environment**
- OS: Windows 10
- Compiler: Visual Studio 2017
- vcpkg: 2019.11

**To Reproduce**
1. .\vcpkg install ceres:x64-windows-static
2. Observe the size of "vcpkg-2019.11\packages\ceres_x64-windows-static\lib\ceres.lib"

**Expected behavior**
I would expect the size of the static library to be in the ballpark of the 47 MB I see when I build Ceres outside of vcpkg. I understand that the size are unlikely to be identical, but the size differences I'm seeing are exceptional.

**Additional context**
I wondered if some of the difference might be due to the different generators (Ninja for vcpkg and Visual Studio for me). So I tried building Ceres using Ninja as well, and then the release build was 350 MB, so that might explain some of the difference, but clearly not all of it.

I noticed a similar issue was raised here:
https://github.com/microsoft/vcpkg/issues/8866

I also asked about this on the Ceres message board (the numbers I report there are slightly different, as I think I used VS 2019 originally):
https://groups.google.com/forum/#!topic/ceres-solver/7mZq3ej6njk

**Comment by JackBoosY** [comment]
I found **50565** symbols were exported in the static library, so I will check if it makes sense.

**Comment by Neumann-A** [comment]
Used Compiler and Linker Flags?

VCPKG uses 
```
    set(CMAKE_CXX_FLAGS " /DWIN32 /D_WINDOWS /W3 ${CHARSET_FLAG} /GR /EHsc /MP ${VCPKG_CXX_FLAGS}" CACHE STRING "")
    set(CMAKE_C_FLAGS " /DWIN32 /D_WINDOWS /W3 ${CHARSET_FLAG} /MP ${VCPKG_C_FLAGS}" CACHE STRING "")
    set(CMAKE_RC_FLAGS "-c65001 /DWIN32" CACHE STRING "")
    
    unset(CHARSET_FLAG)

    set(CMAKE_CXX_FLAGS_DEBUG "/D_DEBUG ${VCPKG_CRT_LINK_FLAG_PREFIX}d /Z7 /Ob0 /Od /RTC1 ${VCPKG_CXX_FLAGS_DEBUG}" CACHE STRING "")
    set(CMAKE_C_FLAGS_DEBUG "/D_DEBUG ${VCPKG_CRT_LINK_FLAG_PREFIX}d /Z7 /Ob0 /Od /RTC1 ${VCPKG_C_FLAGS_DEBUG}" CACHE STRING "")
    set(CMAKE_CXX_FLAGS_RELEASE "${VCPKG_CRT_LINK_FLAG_PREFIX} /O2 /Oi /Gy /DNDEBUG /Z7 ${VCPKG_CXX_FLAGS_RELEASE}" CACHE STRING "")
    set(CMAKE_C_FLAGS_RELEASE "${VCPKG_CRT_LINK_FLAG_PREFIX} /O2 /Oi /Gy /DNDEBUG /Z7 ${VCPKG_C_FLAGS_RELEASE}" CACHE STRING "")

    set(CMAKE_SHARED_LINKER_FLAGS_RELEASE "/DEBUG /INCREMENTAL:NO /OPT:REF /OPT:ICF ${VCPKG_LINKER_FLAGS}" CACHE STRING "")
    set(CMAKE_EXE_LINKER_FLAGS_RELEASE "/DEBUG /INCREMENTAL:NO /OPT:REF /OPT:ICF ${VCPKG_LINKER_FLAGS}" CACHE STRING "")
```

**Comment by anaru** [comment]
Here are the flags (I didn't think RC_FLAGS/SHARED_LINKER_FLAGS/EXE_LINKER_FLAGS would be relevant here?)

### My vcpkg flags
(from vcpkg-2019.11\buildtrees\ceres\x64-windows-static-rel\CMakeCache.txt)

CMAKE_CXX_FLAGS:STRING=' /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP '
CMAKE_CXX_FLAGS_DEBUG:STRING='/D_DEBUG /MTd /Z7 /Ob0 /Od /RTC1 '
CMAKE_CXX_FLAGS_RELEASE:STRING='/MT /O2 /Oi /Gy /DNDEBUG /Z7 '

CMAKE_C_FLAGS:STRING=' /DWIN32 /D_WINDOWS /W3 /utf-8 /MP '
CMAKE_C_FLAGS_DEBUG:STRING='/D_DEBUG /MTd /Z7 /Ob0 /Od /RTC1 '
CMAKE_C_FLAGS_RELEASE:STRING='/MT /O2 /Oi /Gy /DNDEBUG /Z7 '

CMAKE_STATIC_LINKER_FLAGS:STRING=/machine:x64
CMAKE_STATIC_LINKER_FLAGS_DEBUG:STRING=
CMAKE_STATIC_LINKER_FLAGS_RELEASE:STRING=

### My manual build flags
CMAKE_CXX_FLAGS:STRING=/bigobj  /DWIN32 /D_WINDOWS /W3 /GR /EHsc
CMAKE_CXX_FLAGS_DEBUG:STRING=/MDd /Zi /Ob0 /Od /RTC1
CMAKE_CXX_FLAGS_RELEASE:STRING=/MD /O2 /Ob2 /DNDEBUG

CMAKE_C_FLAGS:STRING=/DWIN32 /D_WINDOWS /W3
CMAKE_C_FLAGS_DEBUG:STRING=/MDd /Zi /Ob0 /Od /RTC1
CMAKE_C_FLAGS_RELEASE:STRING=/MD /O2 /Ob2 /DNDEBUG

CMAKE_STATIC_LINKER_FLAGS:STRING=/machine:x64
CMAKE_STATIC_LINKER_FLAGS_DEBUG:STRING=
CMAKE_STATIC_LINKER_FLAGS_RELEASE:STRING=

**Comment by JackBoosY** [comment]
It seems that some compilation flags are causing this problem(eg: z7).

**Comment by anaru** [comment]
Thanks for pointing me to the compiler flags @JackBoosY  and @Neumann-A - it seems obvious in retrospect, but this is the first time I've used vcpkg/ninja before, so didn't have much understanding of what was going on under the hood.

I tried removing the /z7 flag from the toolchain file, and found that the Ceres static lib size goes from >1 GB to ~250 MB, which is pretty significant. It's still larger than my ~55 MB build, and I've tried tweaking other flags, but can't account for the remaining difference.

Now that I know what it does, it strikes me as odd that /z7 is used by default in all Release builds (and this issue queries it too: https://github.com/microsoft/vcpkg/issues/9084). Because it's in the global toolchain, I guess turning it off or making it optional would be a pretty significant change, but I would be interested if anyone knows why it's there in the first place.

**Comment by Neumann-A** [comment]
> 1 GB to ~250 MB, which is pretty significant. It's still larger than my ~55 MB build

Probably /MT vs /MD and all dependencies have to be build with the same flags. Furthermore you have to make sure that your CMake Options for the build are the same as the ones used in VCPKG.
e.g.:
```
vcpkg_configure_cmake(
    SOURCE_PATH ${SOURCE_PATH}
    PREFER_NINJA
    OPTIONS
        -DEXPORT_BUILD_DIR=ON
        -DBUILD_EXAMPLES=OFF
        -DBUILD_TESTING=OFF
        -DGFLAGS=${GFLAGS}
        -DCXSPARSE=${CXSPARSE}
        -DEIGENSPARSE=${EIGENSPARSE}
        -DLAPACK=${LAPACK}
        -DSUITESPARSE=${SUITESPARSE}
        -DMSVC_USE_STATIC_CRT=${MSVC_USE_STATIC_CRT_VALUE}
)
```

**Comment by anaru** [comment]
I have been pretty careful about getting the dependencies to match up - in both cases the only dependencies are gflags, glog and eigen - I've disabled the rest. I am building with `/MT` in both cases (the cache value I posted just seems to be inaccurate for some reason). I verified this by checking both .lib files with `dumpbin /directives`, and both have MT_StaticRelease.

I do have `BUILD_TESTING=ON`, but the tests are just consumers of the .lib, so I'd be surprised if that made a difference to the lib size.

**Comment by Neumann-A** [comment]
try adding /Ob3 to vcpkg. I have the feeling that VS is not inlining Eigen strongly enough. 
Do you use your own Eigen package or do you use Eigen from VCPKG? If you use Eigen from vcpkg try installing it with the `--head` option

**Comment by anaru** [comment]
Apologies, while looking into your /Ob3 suggestion, I just realised another point of difference - vcpkg is using the VS 2019 compiler, while I'm using VS 2017. Is there a way to change which version vcpkg uses?

**Comment by JackBoosY** [comment]
@ras0219-msft Could you have a look?

Thanks.

**Comment by Neumann-A** [comment]
@anaru https://vcpkg.readthedocs.io/en/latest/users/config-environment/

**Comment by BillyONeal** [comment]
>it strikes me as odd that /z7 is used by default in all Release builds (and this issue queries it too: #9084).

The alternative to `/Z7` would be to force customers to deal with a lot of `.pdbs` to distribute with their static libraries and our experience is that folks almost universally don't do that correctly.

I suspect most of the remaining difference is:

```
CMAKE_CXX_FLAGS_DEBUG:STRING=/MDd /Zi /Ob0 /Od /RTC1
CMAKE_CXX_FLAGS_RELEASE:STRING=/MD /O2 /Ob2 /DNDEBUG

CMAKE_C_FLAGS:STRING=/DWIN32 /D_WINDOWS /W3
CMAKE_C_FLAGS_DEBUG:STRING=/MDd /Zi /Ob0 /Od /RTC1
CMAKE_C_FLAGS_RELEASE:STRING=/MD /O2 /Ob2 /DNDEBUG
```

Note `/MDd` and `/MD`, while vcpkg uses `/MT` and `/MTd` for the static triplets by default (since most folks using static want single-binary xcopy deployment).

**Comment by LiuPeiqi-CNHN** [comment]
OS: Windows 10
Compiler: Visual Studio 2019
Ceres: 2.0.0#5

Release: Remove **/Z7**, add **/Zc:inline**, then ceres release static lib size ≈ 54MB
Debug: Remove **/Z7** and **/RTC1**, add **/Zc:inline**, change /Od to /O1, then ceres debug static lib size ≈ 308MB

you can edit cmake file in "D:\vcpkg\scripts\toolchains\**windows.cmake**":
```
    set(CMAKE_CXX_FLAGS " /nologo /DWIN32 /D_WINDOWS /W3 ${CHARSET_FLAG} /Zc:inline /GR /EHsc /MP ${VCPKG_CXX_FLAGS}" CACHE STRING "")
    set(CMAKE_C_FLAGS " /nologo /DWIN32 /D_WINDOWS /W3 ${CHARSET_FLAG} /Zc:inline /MP ${VCPKG_C_FLAGS}" CACHE STRING "")
    set(CMAKE_RC_FLAGS "-c65001 /DWIN32" CACHE STRING "")

    unset(CHARSET_FLAG)

    set(CMAKE_CXX_FLAGS_DEBUG "/D_DEBUG ${VCPKG_CRT_LINK_FLAG_PREFIX}d /Ob0 /O1 ${VCPKG_CXX_FLAGS_DEBUG}" CACHE STRING "")
    set(CMAKE_C_FLAGS_DEBUG "/D_DEBUG ${VCPKG_CRT_LINK_FLAG_PREFIX}d /Ob0 /O1 ${VCPKG_C_FLAGS_DEBUG}" CACHE STRING "")
    set(CMAKE_CXX_FLAGS_RELEASE "${VCPKG_CRT_LINK_FLAG_PREFIX} /O2 /Oi /Gy /DNDEBUG ${VCPKG_CXX_FLAGS_RELEASE}" CACHE STRING "")
    set(CMAKE_C_FLAGS_RELEASE "${VCPKG_CRT_LINK_FLAG_PREFIX} /O2 /Oi /Gy /DNDEBUG ${VCPKG_C_FLAGS_RELEASE}" CACHE STRING "")
```

**Comment by JackBoosY** [comment]
https://github.com/ceres-solver/ceres-solver/blob/125a0e9be51d3876d3a6f03111a3b80b4c8b7bb8/CMakeLists.txt#L612-L624

You can see the upstream doesn't fits msvc.
So I think this should be handled by the upstream, not vcpkg.

**Comment by BillyONeal** [comment]
> Now that I know what it does, it strikes me as odd that /z7 is used by default in all Release builds (and this issue queries it too: #9084). Because it's in the global toolchain, I guess turning it off or making it optional would be a pretty significant change, but I would be interested if anyone knows why it's there in the first place.

Because people generally want symbols for everything, including "release" bits. Not even being able to look at call stacks in crash dumps is pretty crippling.

I don't think there's much we can do about this that isn't a "use Zi rather than Z7" which has been reported a few times but we explicitly do not do because it causes ports to try to stomp on the same PDB name.

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
