### ISSUE TITLE
[New Port Request] <KaHIP>

### ISSUE THREAD

**Issue by abaghiyan** [microsoft/vcpkg#9678]
Library name: KaHIP

Library description: KaHIP - Karlsruhe High Quality Partitioning - is a family of graph partitioning programs. It includes KaFFPa (Karlsruhe Fast Flow Partitioner), which is a multilevel graph partitioning algorithm, in its variants Strong, Eco and Fast, KaFFPaE (KaFFPaEvolutionary) which is a parallel evolutionary algorithm that uses KaFFPa to provide combine and mutation operations, as well as KaBaPE which extends the evolutionary algorithm. Moreover, specialized techniques are included to partition road networks (Buffoon), to output a vertex separator from a given partition or techniques geared towards efficient partitioning of social networks.

Source repository URL: https://github.com/schulzchristian/KaHIP

Project homepage (if different from the source repository): http://algo2.iti.kit.edu/kahip/

Anything else that is useful to know when adding (such as optional features the library may have that should be included): http://algo2.iti.kit.edu/schulz/software_releases/kahipv2.10.pdf

**Comment by LilyWangL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.

**Comment by schulzchristian** [comment]
Author of kahip here, i am happy to help woth the port.
