### ISSUE TITLE
How do I build libcurl with openssl 1.1.1

### ISSUE THREAD

**Issue by hotbroker** [microsoft/vcpkg#9683]
been tried to look in vcpkg, but founds none.

**Comment by Neumann-A** [comment]
`vcpkg install curl[core,openssl]` Should do the trick but the default SSL backend for curl on windows is Secure Channel ("WinSSL") so it was probably not tested in CI. So if you see a build error using that open up an issue

**Comment by hotbroker** [comment]
> `vcpkg install curl[core,openssl]` Should do the trick but the default SSL backend for curl on windows is Secure Channel ("WinSSL") so it was probably not tested in CI. So if you see a build error using that open up an issue


sad. this default using openssl 1.0. promote as below:


The following packages will be built and installed:
    curl[core,openssl]:x64-windows
  * openssl[core]:x64-windows
  * openssl-windows[core]:x64-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/3: openssl-windows:x64-windows
Building package openssl-windows[core]:x64-windows...
-- Downloading https://www.openssl.org/source/openssl-1.0.2s.tar.gz...
-- Using source at D:/dev/opensrc/vcpkg-master/buildtrees/openssl-windows/src/openssl-1-c41872ef97
^C

**Comment by Neumann-A** [comment]
You forgot to pull the latest changes from vcpkg

**Comment by hotbroker** [comment]
> You forgot to pull the latest changes from vcpkg

cool , now it do that in the right way .thanks

Extracting source D:/dev/opensrc/vcpkg-master/downloads/openssl-1.1.1d.tar.gz
-- Using source at D:/dev/opensrc/vcpkg-master/buildtrees/openssl-windows/src/openssl-1-b1f8ae3e6c
