### ISSUE TITLE
[libpq] build failure

### ISSUE THREAD

**Issue by cdcseacave** [microsoft/vcpkg#9689]
**Host Environment**
- OS: Windows - windows-x64
- Compiler: latest

**To Reproduce**
`./vcpkg install libpq`

**Failure logs** 
vcpkg\buildtrees\libpq\x64-windows-rel\src\interfaces\libpq\fe-secure-openssl.c(707,45): error C2065: 'OPENSSL_INIT_LOAD_CONFIG': undeclared identifier [D:\Pro\vcpkg\buildtrees\libpq\x64-windows-rel\libpq.vcxproj]

**Comment by Neumann-A** [comment]
Rebuild OpenSSL and try again. You probably still have version 1.0.2 installed

**Comment by cdcseacave** [comment]
I confirm this solves the problem, thx!

**Comment by duyanning** [comment]
> 
> 
> Rebuild OpenSSL and try again. You probably still have version 1.0.2 installed

vcpkg cannot manage it automatically?
