### ISSUE TITLE
Enable Custom Dependencies

### ISSUE THREAD

**Issue by LeonineKing1199** [microsoft/vcpkg#9691]
****

**Is your feature request related to a problem? Please describe.**
Yes! The problem: have previously installed version of Boost, want to write custom portfile that uses the local version of Boost

**Proposed solution**
Enable vcpkg to accept command line arguments it can forward to CMake when building a port. For example, all I would need to forward to CMake when invoking vcpkg is `-DBoost_DIR=...`

**Describe alternatives you've considered**
I've edited my chainload file to some success but this is hacky and can interfere with other packages.

**Additional context**
N/A

**Comment by JackBoosY** [comment]
Hi @LeonineKing1199, I think you should use overlay port to implement it. See [documentation](https://github.com/microsoft/vcpkg/blob/master/docs/specifications/ports-overlay.md).

**Comment by JackBoosY** [comment]
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.
