### ISSUE TITLE
McAfee Reports Application built from Github as a virus

### ISSUE THREAD

**Issue by McDeCoderDude** [microsoft/vcpkg#9692]
**Describe the bug**
After building application using .\bootstrap-vcpkg.bat then running .\vcpkg.exe integrate install. The McAfee application running on my host machine complains that the executable is a virus and file is immediately quarantined.

**Environment**
- OS: Windows 10 2004 1904.1
- Compiler: Version 19.24.28314

**To Reproduce**
1. ./vcpkg integrate install
2. See error -- McAffee displays dialog box indicating virus has been found.

**Expected behavior**
A virus pattern is not found in executable.

![Annotation 2020-01-14 154432](https://user-images.githubusercontent.com/1192480/72385298-cee85f00-36e4-11ea-8b35-339aa2d8d83a.png)

**Comment by drescherjm** [comment]
This is a false positive. There are duplicates for this.

**Comment by vicroms** [comment]
Hi @ McDeCoderDude 

This has been reported in the past, it is indeed a false positive.

You can disable telemetry in vcpkg with:
```powershell
./bootstrap-vcpkg.bat -disableMetrics
```
