### ISSUE TITLE
[ffmpeg[openssl]] build failure on Windows

### ISSUE THREAD

**Issue by traumedy** [microsoft/vcpkg#9693]
**Host Environment**
- OS: Windows 10
- Compiler: Visual Studio 2017 Enterprise

**To Reproduce**
`vcpkg install ffmpeg[openssl]:x64-windows`

**Failure logs** 
```
-- Building ffmpeg for Release
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: D:/vcpkg/downloads/tools/msys2/msys64/usr/bin/bash.exe --noprofile --norc D:/vcpkg/ports/ffmpeg\build.sh D:/vcpkg/buildtrees/ffmpeg/x64-windows-rel D:/vcpkg/buildtrees/ffmpeg/src/n4.2-02d8c63f80 D:/vcpkg/packages/ffmpeg_x64-windows "--enable-asm --enable-yasm --disable-doc --enable-debug --enable-runtime-cpudetect --enable-nonfree --enable-openssl --disable-ffmpeg --disable-ffplay --disable-ffprobe --disable-libvpx --disable-libx264 --disable-opencl --disable-lzma --disable-bzlib --enable-avresample  --disable-static --enable-shared --extra-cflags=-DHAVE_UNISTD_H=0  --extra-cflags=-MD --extra-cxxflags=-MD"
    Working Directory: D:/vcpkg/buildtrees/ffmpeg/x64-windows-rel
    Error code: 1
    See logs for more information:
      D:\vcpkg\buildtrees\ffmpeg\build-x64-windows-rel-out.log
...
D:\vcpkg>type D:\vcpkg\buildtrees\ffmpeg\build-x64-windows-rel-out.log
=== CONFIGURING ===
ERROR: openssl not found
...
```

**Additional context**
This started failing in the last day or two.  All other ffmpeg features still build fine with x64-windows.

**Comment by Neumann-A** [comment]
ffmpeg checks for SSL_library_init in configure and this has been deprecated in 1.1.0. Maybe someone should tell them to update their configure script.... 
you can use this patch to make it work (just drop the .txt extension and drop it into the ffmpeg port folder)
[0002-detect-openssl.patch.txt](https://github.com/microsoft/vcpkg/files/4064248/0002-detect-openssl.patch.txt)

**Comment by pierrextardif** [comment]
Patches from @Neumann-A still needed when using FFmpeg 5.0.
This ias a special case as I'm doing manual compilation.
Thanks anyways v useful.

**Comment by sfhacker** [comment]
This is a two year old issue.
We haven't built FFmpeg recently but we will have a go at it now and see how it goes.

**Comment by sfhacker** [comment]
Just downloaded FFmpeg 5.0 AS IS (0 patches) and ran (under MSYS2): ./configure --prefix= ..... No issues at all with OpenSSL.

![image](https://user-images.githubusercontent.com/25817529/155219870-257fd6d3-fe4a-4c6d-805b-39dc65f98fd1.png)
