### ISSUE TITLE
[mosquitto] <mosquittopp.lib not copied to installed>

### ISSUE THREAD

**Issue by rjhuckins** [microsoft/vcpkg#9694]
mosquittopp.lib is being created (it can be found in vcpkg\buildtrees\mosquitto\x86-windows-rel\lib\cpp\mosquittopp.lib) but is not being copied to vcpkg\installed\x86-windows\lib; this is true for both release and debug. mosquitto.lib, both dlls, and all .h files are copied properly.

- OS: Windows 10 (64 bit)
- Compiler: Visual Studio 2019 16.4.3
- CMake: 3.16.2
- Git: 2.24.0.windows.2

The workaround is easy, just copy the file manually.

**Comment by NancyLi1013** [comment]
Hi @rjhuckins thanks for posting this issue.
This issue should be fixed now. Please update vcpkg and try to use it again.
