### ISSUE TITLE
[netcdf-c:x64-windows] build failure

### ISSUE THREAD

**Issue by davidbun** [microsoft/vcpkg#9696]
**Host Environment**
Windows 10
- Compiler: VS2017

**To Reproduce**
netcdf-c:x64-windows --recurse

**Failure logs** 
.\vcpkg install netcdf-c:x64-windows --recurse
The following packages will be built and installed:
    netcdf-c[core]:x64-windows
Starting package 1/1: netcdf-c:x64-windows
Building package netcdf-c[core]:x64-windows...
-- Using cached C:/vcpkg_NEW/downloads/Unidata-netcdf-c-b7cd387bee8c661141fabb490f4969587c008c55.tar.gz
-- Using source at C:/vcpkg_NEW/buildtrees/netcdf-c/src/587c008c55-c804eaf515
-- Configuring x64-windows-dbg
-- Configuring x64-windows-rel
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v
    Working Directory: C:/vcpkg_NEW/buildtrees/netcdf-c/x64-windows-dbg
    See logs for more information:
      C:\vcpkg_NEW\buildtrees\netcdf-c\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:91 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/netcdf-c/portfile.cmake:41 (vcpkg_install_cmake)
  scripts/ports.cmake:94 (include)

Error: Building package netcdf-c:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: netcdf-c:x64-windows
  Vcpkg version: 2019.09.12-nohash

Additionally, attach any relevant sections from the log files above.
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/4064731/install-x64-windows-dbg-out.log)

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by Neumann-A** [comment]
actual bug is in the HDF5 targets (build with parallel feature) missing linkage against MPI
```
   Creating library liblib\netcdf.lib and object liblib\netcdf.exp
dinfermodel.c.obj : error LNK2019: unresolved external symbol MPI_Error_class referenced in function openmagic
dinfermodel.c.obj : error LNK2019: unresolved external symbol MPI_File_open referenced in function openmagic
dinfermodel.c.obj : error LNK2019: unresolved external symbol MPI_File_close referenced in function closemagic
dinfermodel.c.obj : error LNK2019: unresolved external symbol MPI_File_get_size referenced in function openmagic
dinfermodel.c.obj : error LNK2019: unresolved external symbol MPI_File_read_at_all referenced in function readmagic
hdf5file.c.obj : error LNK2019: unresolved external symbol MPI_Comm_free referenced in function nc4_close_netcdf4_file
hdf5create.c.obj : error LNK2001: unresolved external symbol MPI_Comm_free
hdf5open.c.obj : error LNK2001: unresolved external symbol MPI_Comm_free
hdf5file.c.obj : error LNK2019: unresolved external symbol MPI_Info_free referenced in function nc4_close_netcdf4_file
hdf5create.c.obj : error LNK2001: unresolved external symbol MPI_Info_free
hdf5open.c.obj : error LNK2001: unresolved external symbol MPI_Info_free
hdf5create.c.obj : error LNK2019: unresolved external symbol MPI_Comm_dup referenced in function nc4_create_file
hdf5open.c.obj : error LNK2001: unresolved external symbol MPI_Comm_dup
hdf5create.c.obj : error LNK2019: unresolved external symbol MPI_Info_dup referenced in function nc4_create_file
hdf5open.c.obj : error LNK2001: unresolved external symbol MPI_Info_dup
hdf5var.c.obj : error LNK2019: unresolved external symbol MPI_Allreduce referenced in function NC4_put_vars
liblib\netcdf.dll : fatal error LNK1120: 10 unresolved externals
```

**Comment by Neumann-A** [comment]
could you add the error logs from `<vcpkgroot>/buildtrees/netcdf-c/x64-windows-dbg/CMakeFiles/CMakeError.log` and `CMakeOutput.log` ? Probably one of the configure checks got it wrong.

**Comment by davidbun** [comment]
Dear @Neumann-A 
Attached please find the log files you asked me
[CMakeError.log](https://github.com/microsoft/vcpkg/files/4070459/CMakeError.log)
[CMakeOutput.log](https://github.com/microsoft/vcpkg/files/4070460/CMakeOutput.log)

**Comment by Neumann-A** [comment]
since the checks there are successful could you also add: 
```
<vcpkgroot>/buildtrees/netcdf-c/config-x64-windows-dbg-out.log
<vcpkgroot>/buildtrees/netcdf-c/config-x64-windows-dbg-err.log
```

**Comment by davidbun** [comment]
Dear @Neumann-A 
Attached please find the required log files

[config-x64-windows-dbg-err.log](https://github.com/microsoft/vcpkg/files/4071098/config-x64-windows-dbg-err.log)
[config-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/4071099/config-x64-windows-dbg-out.log)

**Comment by Neumann-A** [comment]
requires debugging of the netcdf-c `CMakeLists.txt`. It searches and finds msmpi:
```
-- Found MPI_C: C:/vcpkg_NEW/installed/x64-windows/debug/lib/msmpi.lib (found version "2.0") 
-- Found MPI: TRUE (found version "2.0")  
```
but for some reason does not link against it
`-- Linking against:      ZLIB::ZLIB;hdf5::hdf5-shared;hdf5::hdf5_hl-shared;CURL::libcurl`

could be related to the failures seen here:
```
-- Looking for MPI_Comm_f2c
-- Looking for MPI_Comm_f2c - not found
-- Looking for MPI_Info_f2c
-- Looking for MPI_Info_f2c - not found
```
Looking at the `CMakeError.log` the check is also not linking against the found `msmpi.lib` and thus fails.

**Comment by ShaneKirkbride** [comment]
Has this issue been resolved? If so how? I'm having the same problem.

**Comment by ShaneKirkbride** [comment]
@Neumann-A I cloned the branch (using this command:  git clone -b fix_netcdf-c_mpi --single-branch https://github.com/Neumann-A/vcpkg.git you made the fix in and it seems to install. thank you! I hope the fix gets merged into master soon.
