### ISSUE TITLE
cmake3(not cmake) has already installed

### ISSUE THREAD

**Issue by aiyou4love** [microsoft/vcpkg#9697]
os centos7 
cmake3(not cmake) has already installed,
run ./bootstrap-vcpkg.sh
still install cmake

**Comment by vicroms** [comment]
Hi @aiyou4love 

The bootstrap script downloads a local copy of CMake to build the **vcpkg** executable. 
However, **vcpkg** uses your system's CMake when building libraries to install.

If you prefer to skip the bootstrap, you can build **vcpkg** using the CMake project we provide in `toolsrc/`.
