### ISSUE TITLE
[New Port Request] aom

### ISSUE THREAD

**Issue by atkawa7** [microsoft/vcpkg#9701]
Library name: aom

Library description: AV1 Codec Library

Source repository URL: https://aomedia.googlesource.com/aom/

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by LilyWangL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.

**Comment by NancyLi1013** [comment]
This port has been added to vcpkg via PR #18083. Please update to the latest vcpkg to use this port.
