### ISSUE TITLE
vcpkg.exe not being created with bootstrap script

### ISSUE THREAD

**Issue by thatrobotguy** [microsoft/vcpkg#9704]
I am running into the same issue as [7367](https://github.com/microsoft/vcpkg/issues/7367), but the bootstrap script appears to not do anything.

I run `.\bootstrap-vcpkg.bat` in powershell and I do **NOT** see a `vcpkg.exe` file under the root directory where I cloned the repo.

I saw that the script printed out this location:
```
vcpkg.vcxproj -> C:\Users\computeruser\vcpkg\toolsrc\msbuild.x86.release\vcpkg.exe
```
But that also does not contain the executable. In fact, that location in the directory structure does not exist.

I checked git for more branches and master appears to the the only valid branch. What should I do?

I run `.\bootstrap-vcpkg.bat` in powershell and I do **NOT** see a `vcpkg.exe` file under the root directory where I cloned the repo.

I saw that the script printed out this location:
```
vcpkg.vcxproj -> C:\Users\computeruser\vcpkg\toolsrc\msbuild.x86.release\vcpkg.exe
```
But that also does not contain the executable. In fact, that location in the directory structure does not exist.

I checked git for more branches and master appears to the the only valid branch. What should I do?

I should also mention that, when I start the bootstrap script, I get this output at the very start:
```
.\bootstrap-vcpkg.bat                                                                              Get-CimInstance : The specified service does not exist as an installed service.
At C:\Users\computeruser\vcpkg\scripts\bootstrap.ps1:349 char:20
+     $architecture=(Get-CimInstance win32_operatingsystem | Select-Obj ...
+                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (root\cimv2:win32_operatingsystem:String) [Get-CimInstance], CimException
    + FullyQualifiedErrorId : HRESULT 0x80070424,Microsoft.Management.Infrastructure.CimCmdlets.GetCimInstanceCommand

The property 'osarchitecture' cannot be found on this object. Verify that the property exists.
At C:\Users\computeruser\vcpkg\scripts\bootstrap.ps1:349 char:5
+     $architecture=(Get-CimInstance win32_operatingsystem | Select-Obj ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], PropertyNotFoundException
    + FullyQualifiedErrorId : PropertyNotFoundStrict
```
And the computer then proceeds to do a bunch of operations without producing any output on the hard drive.

**Environment**
- OS: Windows 10 Version	10.0.18363 Build 18363
- Compiler: revision

**Comment by ubsan** [comment]
This seems like it should be solved by turning `Get-CimInstance` into `[System.Environment]::Is64BitOperatingSystem`. Looking at the reason for using `Get-CimInstance`/`Get-WmiInstance`, it seems as if, in the beginning, it was used to check for x64, and then kept over time. Now, we simply use it to check for 64-bitness, which is more correctly done with the `Is64BitOperatingSystem` environment variable.

**Comment by thatrobotguy** [comment]
So, @ubsan , you are saying I need to change an environment variable? How do you suggest I do that? I do not understand your instructions.

**Comment by thatrobotguy** [comment]
I just installed Visual Studio 2019
I tried creating a CMake C++ project to test if `vcpkg` can be found. I reports the error:

# From the Cmake file
if(NOT EXISTS "${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}" AND NOT _CMAKE_IN_TRY_COMPILE)
    ```message(WARNING "There are no libraries installed for the Vcpkg triplet ${VCPKG_TARGET_TRIPLET}.")```
endif()
```

**Comment by ubsan** [comment]
@thatrobotguy sorry, I was trying to figure out how we might fix this bug.

**Comment by ubsan** [comment]
@thatrobotguy what kind of computer do you have? Is it an ARM64 chip?

**Comment by ubsan** [comment]
Also, see if the following works:

```pwsh
# in vcpkg directory
git remote add ubsan https://github.com/ubsan/vcpkg
git fetch ubsan
git checkout thatrobotguyfix
./bootstrap-vcpkg.bat
```

**Comment by thatrobotguy** [comment]
@usban
I have these computer specs:
```
System Type	x64-based PC
System SKU	0708
Processor	Intel(R) Core(TM) i7-6820HK CPU @ 2.70GHz, 2701 Mhz, 4 Core(s), 8 Logical Processor(s)
```
It is a Dell/Alienware laptop, so it is what I consider to be a pretty standard laptop.
I did these steps:
```
git clone https://github.com/Microsoft/vcpkg.git
cd vcpkg/
git remote add ubsan https://github.com/ubsan/vcpkg
git fetch ubsan
git checkout thatrobotguyfix
./bootstrap-vcpkg.bat
```
I no longer get the error at the start of the script from before. In fact, no red font shows up. 
The weird part is that I still do not see a `vcpkg.exe` file anywhere in the `vcpkg/` root folder.

**Comment by ubsan** [comment]
@thatrobotguy Could you run `dir` and post the result?

**Comment by thatrobotguy** [comment]
@usban
I have these files:
```
Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        1/17/2020  11:46 AM                .github
d-----        1/17/2020  11:46 AM                docs
d-----        1/17/2020  11:46 AM                ports
d-----        1/17/2020  11:47 AM                scripts
d-----        1/17/2020  11:46 AM                toolsrc
d-----        1/17/2020  11:46 AM                triplets
-a----        1/17/2020  11:46 AM              8 .gitattributes
-a----        1/17/2020  11:46 AM           5625 .gitignore
-a----        1/17/2020  11:46 AM              0 .vcpkg-root
-a----        1/17/2020  11:46 AM            100 bootstrap-vcpkg.bat
-a----        1/17/2020  11:46 AM            109 bootstrap-vcpkg.sh
-a----        1/17/2020  11:46 AM         398564 CHANGELOG.md
-a----        1/17/2020  11:46 AM           2432 CONTRIBUTING.md
-a----        1/17/2020  11:46 AM           1096 LICENSE.txt
-a----        1/17/2020  11:46 AM           2334 NOTICE.txt
-a----        1/17/2020  11:46 AM           4345 README.md
-a----        1/17/2020  11:46 AM           3282 README_zh_CN.md
```

**Comment by thatrobotguy** [comment]
Is there a way to make the software output in verbose mode?
Like, is there a way to make the software spam the terminal with status information?
I feel like there must be some way to detect why the file is not being created.

**Comment by thatrobotguy** [comment]
I thought I would post the entire output as well, in case that helps.
```
PS C:\Users\computeruser\vcpkg> .\bootstrap-vcpkg.bat

Building vcpkg.exe ...

  pch.cpp
  archives.cpp
  checks.cpp
  chrono.cpp
  cofffilereader.cpp
  downloads.cpp
  enums.cpp
  files.cpp
  hash.cpp
  machinetype.cpp
  strings.cpp
  stringview.cpp
  system.cpp
  system.print.cpp
  binaryparagraph.cpp
  build.cpp
  commands.autocomplete.cpp
  commands.buildexternal.cpp
  commands.cache.cpp
  commands.ci.cpp
  commands.contact.cpp
  commands.cpp
  commands.create.cpp
  commands.dependinfo.cpp
  commands.edit.cpp
  commands.env.cpp
  commands.exportifw.cpp
  commands.import.cpp
  commands.integrate.cpp
  commands.list.cpp
  commands.owns.cpp
  commands.porthistory.cpp
  commands.portsdiff.cpp
  commands.search.cpp
  commands.upgrade.cpp
  commands.version.cpp
  commands.xvsinstances.cpp
  dependencies.cpp
  export.cpp
  export.chocolatey.cpp
  globalstate.cpp
  help.cpp
  input.cpp
  install.cpp
  logicexpression.cpp
  metrics.cpp
  packagespec.cpp
  packagespecparseresult.cpp
  paragraphparseresult.cpp
  paragraphs.cpp
  parse.cpp
  postbuildlint.buildtype.cpp
  postbuildlint.cpp
  remove.cpp
  sourceparagraph.cpp
  statusparagraph.cpp
  statusparagraphs.cpp
  tools.cpp
  triplet.cpp
  update.cpp
  userconfig.cpp
  vcpkgcmdarguments.cpp
  vcpkglib.cpp
  vcpkgpaths.cpp
  versiont.cpp
  visualstudio.cpp
  vcpkglib.vcxproj -> C:\Users\computeruser\vcpkg\toolsrc\msbuild.x86.release\vcpkglib.lib
  vcpkg.cpp
  Generating code
  Previous IPDB not found, fall back to full compilation.
  All 14762 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
  Finished generating code
  vcpkg.vcxproj -> C:\Users\computeruser\vcpkg\toolsrc\msbuild.x86.release\vcpkg.exe
  vcpkgmetricsuploader.cpp
  Generating code
  Previous IPDB not found, fall back to full compilation.
  All 5097 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
  Finished generating code
  vcpkgmetricsuploader.vcxproj -> C:\Users\computeruser\vcpkg\toolsrc\msbuild.x86.release\vcpkgmetricsuploader.exe

Building vcpkg.exe... done.

Telemetry
---------
vcpkg collects usage data in order to help us improve your experience. The data collected by Microsoft is anonymous. You can opt-out of telemetry by re-running bootstrap-vcpkg.bat with -disableMetrics.
Read more about vcpkg telemetry at docs/about/privacy.md

PS C:\Users\computeruser\vcpkg> dir


    Directory: C:\Users\computeruser\vcpkg


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        1/17/2020  11:46 AM                .github
d-----        1/17/2020  11:46 AM                docs
d-----        1/17/2020  11:46 AM                ports
d-----        1/17/2020  11:47 AM                scripts
d-----        1/17/2020  11:46 AM                toolsrc
d-----        1/17/2020  11:46 AM                triplets
-a----        1/17/2020  11:46 AM              8 .gitattributes
-a----        1/17/2020  11:46 AM           5625 .gitignore
-a----        1/17/2020  11:46 AM              0 .vcpkg-root
-a----        1/17/2020  11:46 AM            100 bootstrap-vcpkg.bat
-a----        1/17/2020  11:46 AM            109 bootstrap-vcpkg.sh
-a----        1/17/2020  11:46 AM         398564 CHANGELOG.md
-a----        1/17/2020  11:46 AM           2432 CONTRIBUTING.md
-a----        1/17/2020  11:46 AM           1096 LICENSE.txt
-a----        1/17/2020  11:46 AM           2334 NOTICE.txt
-a----        1/17/2020  11:46 AM           4345 README.md
-a----        1/17/2020  11:46 AM           3282 README_zh_CN.md


PS C:\Users\computeruser\vcpkg>

```

**Comment by PhoebeHui** [comment]
Is it possible that removed by other software, or it doesn't generated actually.

Does C:\Users\computeruser\vcpkg\toolsrc\msbuild.x86.release\vcpkg.exe exist?

**Comment by thatrobotguy** [comment]
Hey @PhoebeHui 
## Regarding the first question
I have run the script in admin mode for both x64 powershell and x86 powershell and I get the same result.
## Regarding the second question
I do not have that file. In fact, I do not have the directory `msbuild.x86.release\` either.
What do you suggest I do?

**Comment by DoCode** [comment]
I have the same issue and run the script multiple times, in not elevated session, and after 2 or 3 runs, the exe was in the repository root directory.

**Comment by ubsan** [comment]
@thatrobotguy can you try `dir toolsrc` maybe?

**Comment by thatrobotguy** [comment]
Hey guys

So I was doing some investigative work and I wondered that maybe some sort of anti-malware was containerizing the powershell script such that the hard drive was not actually written too.

**Comment by thatrobotguy** [comment]
I should mention that I have closed this issue because the cause of the problem is known. I just wanted to alert this thread that, between reboots, this problem might be encountered again. The anti-malware software, for me, keeps trying to containerize the application, even after I told it not too.

**Comment by ubsan** [comment]
This is a good thing to know! Thanks @thatrobotguy 😄

**Comment by goldscurvy** [comment]
I don't know if this is the place to say it but I was also having this problem. It worked when, instead of running vcpkg\bootstrap-vcpkg.bat, I ran powershell.exe -ExecutionPolicy Bypass .\vcpkg\scripts\bootstrap.ps1 directly. I don't know why the batch file wasn't working.

**Comment by iNeXcf** [comment]
> I don't know if this is the place to say it but I was also having this problem. It worked when, instead of running vcpkg\bootstrap-vcpkg.bat, I ran powershell.exe -ExecutionPolicy Bypass .\vcpkg\scripts\bootstrap.ps1 directly. I don't know why the batch file wasn't working.

This seems to be still happening. I got this after updating to VS2022. And running the ps1 directly solved the problem.
