### ISSUE TITLE
ffmpeg link error

### ISSUE THREAD

**Issue by how0723** [microsoft/vcpkg#9714]
**Describe the bug**
ffmpeg can not link to executable file

**Environment**
- OS: [e.g. Windows/Linux etc...] Linux x64 
- Compiler: gcc8.3

**To Reproduce**
cmake file
```
cmake_minimum_required(VERSION 3.15)

project(usb_cam)

set(CMAKE_CXX_STANDARD 11)

if (CMAKE_SYSTEM_NAME MATCHES "Linux")
    message(STATUS "current platform: Linux ")
    set( CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -O2" )
    find_package(FFMPEG REQUIRED)
    include_directories(${FFMPEG_INCLUDE_DIRS})
    link_directories(${FFMPEG_LIBRARY_DIRS})
elseif (CMAKE_SYSTEM_NAME MATCHES "Windows")
    message(STATUS "current platform: Windows")
else ()
    message(STATUS "other platform: ${CMAKE_SYSTEM_NAME}")
endif (CMAKE_SYSTEM_NAME MATCHES "Linux")

include_directories(src)

file(GLOB_RECURSE SRC_FILES src/*.cpp *.h)

add_executable(usb_cam ${SRC_FILES})
target_link_libraries(usb_cam ${FFMPEG_LIBRARYS})

cpp file
#include <iostream>
using namespace std;
extern "C"
{
#include <math.h>
#include <libavutil/opt.h>
#include <libavcodec/avcodec.h>
#include <libavutil/channel_layout.h>
#include <libavutil/common.h>
#include <libavutil/imgutils.h>
#include <libavutil/mathematics.h>
#include <libavutil/samplefmt.h>
#include <libavformat/avformat.h>
#include <libavdevice/avdevice.h>
#include <libavutil/dict.h>
};
int main(int argc, char **argv)
{
    int ret;
    AVFormatContext *fmtCtx = NULL;
    AVPacket pkt1, *pcaket = &pkt1;
    avcodec_register_all();
    avdevice_register_all();
    AVInputFormat *inputFmt = av_find_input_format("video4linux2");
    if (NULL != inputFmt)
    {
        std::cout << "input device name:" << inputFmt->name << std::endl;
    }
    else
    {
        std::cout << "Null point!" << std::endl;
    }
    ret = avformat_open_input(&fmtCtx, "/dev/video0", inputFmt, NULL);
    if (0 == ret)
    {
        std::cout << "Open input device seccess!" << std::endl;
    }
    av_read_frame(fmtCtx, pcaket);
    std::cout << "packet size:" << (pcaket->size) << std::endl;
    FILE *fp = NULL;
    fp = fopen("out.yuv", "wb");
    if (NULL != fp)
    {
        fwrite(pcaket->data, 1, pcaket->size, fp);
    }
    fclose(fp);
    av_free_packet(pcaket);
    avformat_close_input(&fmtCtx);
    return 0;
}
```
**Expected behavior**

**Failure logs** 
```
main.cpp:(.text.startup+0x12): undefined reference to `avcodec_register_all'
/usr/bin/ld: main.cpp:(.text.startup+0x17): undefined reference to `avdevice_register_all'
/usr/bin/ld: main.cpp:(.text.startup+0x23): undefined reference to `av_find_input_format'
/usr/bin/ld: main.cpp:(.text.startup+0x77): undefined reference to `avformat_open_input'
/usr/bin/ld: main.cpp:(.text.startup+0x91): undefined reference to `av_read_frame'
/usr/bin/ld: main.cpp:(.text.startup+0x103): undefined reference to `av_free_packet'
/usr/bin/ld: main.cpp:(.text.startup+0x10b): undefined reference to `avformat_close_input'
collect2: error: ld returned 1 exit status
```

**Additional context**

**Comment by how0723** [comment]
The reason seems to be  link order

**Comment by Neumann-A** [comment]
>The reason seems to be link order

Could you post the correct link order? Makes fixing it trivial.

**Comment by how0723** [comment]
I will give the right order later



---Original---

**Comment by how0723** [comment]
the correct link order is:
avdevice avfilter avformat avresample swresample swscale avcodec avutil z
@Neumann-A

**Comment by cenit** [comment]
There is also a typo in your CMakeLists.txt, you wrote `FFMPEG_LIBRARYS` instead of `FFMPEG_LIBRARIES` (or `FFMPEG_LIBRARY`, both should be ok)

Are you sure your linking errors are not due to an empty string for linking?

**Comment by cenit** [comment]
> the correct link order is:
> avdevice avfilter avformat avresample swresample swscale avcodec avutil z

did you extract them from the pkg-config scripts? That is the truth to use to verify current order and proper one

**Comment by how0723** [comment]
use ${FFMPEG_LIBRARIES} also lead to failure.
@cenit

**Comment by how0723** [comment]
Name: libavresample
Description: Libav audio resampling library
Version: 4.0.0
Requires: 
Requires.private: libavutil >= 56.31.100

Name: libavformat
Description: FFmpeg container format library
Version: 58.29.100
Requires: 
Requires.private: libavcodec >= 58.54.100, libswresample >= 3.5.100, libavutil >= 56.31.100

Name: libavfilter
Description: FFmpeg audio/video filtering library
Version: 7.57.100
Requires: 
Requires.private: libswscale >= 5.5.100, libavformat >= 58.29.100, libavcodec >= 58.54.100, libswresample >= 3.5.100, libavresample >= 4.0.0, libavutil >= 56.31.100

Name: libavdevice
Description: FFmpeg device handling library
Version: 58.8.100
Requires: 
Requires.private: libavfilter >= 7.57.100, libswscale >= 5.5.100, libavformat >= 58.29.100, libavcodec >= 58.54.100, libswresample >= 3.5.100, libavresample >= 4.0.0, libavutil >= 56.31.100

Name: libavcodec
Description: FFmpeg codec library
Version: 58.54.100
Requires: 
Requires.private: libswresample >= 3.5.100, libavutil >= 56.31.100

Name: libswscale
Description: FFmpeg image rescaling library
Version: 5.5.100
Requires: 
Requires.private: libavutil >= 56.31.100

Name: libswresample
Description: FFmpeg audio resampling library
Version: 3.5.100
Requires: 
Requires.private: libavutil >= 56.31.100

Name: libavutil
Description: FFmpeg utility library
Version: 56.31.100
Requires: 
Requires.private:
