### ISSUE TITLE
EROOR when installing szip

### ISSUE THREAD

**Issue by aymenaymenaymen** [microsoft/vcpkg#9715]
hello , 
I have this issue when installing PCL. 
Any ideas to fix it? 

-- Using cached C:/Users/aymme/Desktop/vcpkg-master/downloads/szip-2.1.1.tar.gz
-- Using source at C:/Users/aymme/Desktop/vcpkg-master/buildtrees/szip/src/szip-2.1.1-6b767acfa7
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Performing post-build validation
Detected outdated dynamic CRT in the following files:

    C:\Users\aymme\Desktop\vcpkg-master\packages\szip_x86-windows\bin\szip.dll: msvcr120.dll

To inspect the dll files, use:
    dumpbin.exe /dependents mydllfile.dll
Found 1 error(s). Please correct the portfile:
    C:\Users\aymme\Desktop\vcpkg-master\ports\szip\portfile.cmake
-- Performing post-build validation done
Error: Building package szip:x86-windows failed with: POST_BUILD_CHECKS_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: szip:x86-windows
  Vcpkg version: 2019.09.12-nohash

**Comment by PhoebeHui** [comment]
@aymenaymenaymen, thanks for reporting this issue.

However, I can't repro this issue, you can work around it by adding 'set(VCPKG_POLICY_ALLOW_OBSOLETE_MSVCRT enabled)' to the end of ports\szip\portfile.cmake, could you double check if it works for you?

You can get more information from a [similar issue](https://github.com/microsoft/vcpkg/issues/1124#issuecomment-303262261) about this issue.

**Comment by PhoebeHui** [comment]
@aymenaymenaymen, does this still be a problem for you?

**Comment by PhoebeHui** [comment]
Please reopen this issue if it still be problem for you.
