### ISSUE TITLE
glog link error

### ISSUE THREAD

**Issue by how0723** [microsoft/vcpkg#9716]
**Describe the bug**
glog link error

**Environment**
- OS: [e.g. Windows/Linux etc...] Linux x64
- Compiler: gcc8.3

**To Reproduce**
cmake file : 
cmake_minimum_required(VERSION 3.15)
project(test)
set(CMAKE_CXX_STANDARD 11)
set( CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -O2" )
find_package(GLOG CONFIG REQUIRED)
include_directories(${GLOG_INCLUDE_DIRS})
link_directories(${GLOG_LIBRARY_DIRS})
include_directories(src)
file(GLOB_RECURSE SRC_FILES src/*.cpp *.h)
add_executable(test ${SRC_FILES})
target_link_libraries(test ${GLOG_LIBRARYS})
target_link_libraries(test glog::glog)

cpp file:
#include <iostream>
#include <glog/logging.h>
using namespace std;

int main(int argc, char **argv)
{
    LOG(INFO)<<"test"; 
    return 0;
}

**Expected behavior**

**Failure logs** 
/home/yehao/project/glog_test/src/main.cpp:2:10: fatal error: glog/logging.h: 没有那个文件或目录
 #include <glog/logging.h>
          ^~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/test.dir/build.make:63：CMakeFiles/test.dir/src/main.cpp.o] 错误 1
make[1]: *** [CMakeFiles/Makefile2:76：CMakeFiles/test.dir/all] 错误 2
make: *** [Makefile:84：all] 错误 2

**Additional context**

**Comment by how0723** [comment]
but it works with 
target_link_libraries(test glog::glog)

**Comment by Neumann-A** [comment]
>it works well with
target_link_libraries(test glog::glog)

So you closed the issue yourself.

If you want to correctly link in CMake always use targets. 
The variable GLOG_LIBRARYS is not required to contain all build requirements. As such this is not a VCPKG issue but an upstream issue at the very best.

**Comment by how0723** [comment]
But the vcpkg repo seems not to tell people how to use it correctly on linux platform
@Neumann-A
