### ISSUE TITLE
BUILD_FAILED on protobuf:x86-windows

### ISSUE THREAD

**Issue by mmurrian** [microsoft/vcpkg#9719]
```
The following packages will be built and installed:
    protobuf[core]:x86-windows
Starting package 1/1: protobuf:x86-windows
Building package protobuf[core]:x86-windows...
-- Using cached C:/vcpkg/downloads/protocolbuffers-protobuf-v3.11.2.tar.gz
-- Using source at C:/vcpkg/buildtrees/protobuf/src/v3.11.2-b4b83ed380
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: C:/vcpkg/downloads/tools/cmake-3.14.0-windows/cmake-3.14.0-win32-x86/bin/cmake.exe --build . --config Release --target install -- -v
    Working Directory: C:/vcpkg/buildtrees/protobuf/x86-windows-rel
    See logs for more information:
      C:\vcpkg\buildtrees\protobuf\install-x86-windows-rel-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:91 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/protobuf/portfile.cmake:55 (vcpkg_install_cmake)
  scripts/ports.cmake:94 (include)


Error: Building package protobuf:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: protobuf:x86-windows
  Vcpkg version: 2019.09.12-nohash
```
[install-x86-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/4073802/install-x86-windows-rel-out.log)

**Comment by JackBoosY** [comment]
Log shows:
```
protoc.exe : fatal error LNK1108: cannot write file at 0x0
```
Could you provide your Visual Studio version and Windows version?
Please re-clone vcpkg in non-system partition and try again.

Thanks.

**Comment by mmurrian** [comment]
Visual Studio Community 2019 Versions 16.4.3
Windows 10 Pro Build 17763

I tried cloning vcpkg and building protobuf:x86-windows on a thumb drive. In this case, the log file doesn't indicate any apparent error. The console still reports BUILD_FAILED and protoc.exe is still missing.

protobuf:x86-windows-rel, protoc.exe, is all that I've had problems with. protobuf:x64-windows builds fine. So have a few dozen other packages for both x86-* and x64-*.

[console_output.txt](https://github.com/microsoft/vcpkg/files/4076743/console_output.txt)
[install-x86-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/4076736/install-x86-windows-rel-out.log)

**Comment by JackBoosY** [comment]
Installation log shows:
```
...
-- Installing: D:/vcpkg/packages/protobuf_x86-windows/bin/libprotoc.dll
-- Installing: D:/vcpkg/packages/protobuf_x86-windows/bin/protoc.exe
-- Installing: D:/vcpkg/packages/protobuf_x86-windows/lib/pkgconfig/protobuf.pc
...
```

And console output shows:
```
...
CMake Error at ports/protobuf/portfile.cmake:93 (file):
  file INSTALL cannot find
  "D:/vcpkg/packages/protobuf_x86-windows/bin/protoc.exe".
...
```

Therefore, I think you have anti-virus software installed and will automatically delete this executable.

**Comment by JackBoosY** [comment]
If this issue is still not resolved, please reopen it.
