### ISSUE TITLE
cpprestsdk failed to build on Windows 10 x64 (Creators Update)

### ISSUE THREAD

**Issue by UniversalBinary** [Microsoft/vcpkg#972]
Package: cpprestsdk:x86-windows
Vcpkg version: 0.0.80-

Logs attached.

[package-x86-windows-dbg-out.log.txt](https://github.com/Microsoft/vcpkg/files/950080/package-x86-windows-dbg-out.log.txt)

**Comment by ras0219-msft** [comment]
Thanks for reporting this!

It looks like you have some system-wide copy of OpenSSL which was getting picked up by CMake. I've added those paths to the suppression list with 89ad7d6.

Could you try pulling the latest and rebuilding?

**Comment by T3-VPE** [comment]
Can confirm, same error was irking me since 5 days.

The newest change fixed it.
Everything is building successfully now.

Thanks!
