### ISSUE TITLE
[libpq] Could not find debug or release binaries at D:\vcpkg\buildtrees\libpq\x64-windows-rel\src\tools\msvc/Install.pm line 77

### ISSUE THREAD

**Issue by longhuan2018** [microsoft/vcpkg#9723]
**Host Environment**
- OS: Windows 10
- Compiler: msvc2017
- Used the latest vcpkg code

**To Reproduce**
`./vcpkg install libpq:x64-windows`

**Failure logs** 
```
D:\vcpkg>vcpkg install libpq:x64-windows
The following packages will be built and installed:
    libpq[core,openssl,zlib]:x64-windows
Starting package 1/1: libpq:x64-windows
Building package libpq[core,openssl,zlib]:x64-windows...
-- Using cached D:/vcpkg/downloads/postgresql-12.0.tar.bz2
-- Using source at D:/vcpkg/buildtrees/libpq/src/tgresql-12-e44317bad5
-- Copying libpq source files to D:/vcpkg/buildtrees/libpq/x64-windows-rel...
-- Copying libpq source files... done
-- Applying patch patches/windows/Solution_RELEASE.patch
-- Patches applied!
-- Building libpq x64-windows-RELEASE...
-- Building libpq x64-windows-RELEASE... done
-- Building libecpg_compat x64-windows-RELEASE...
-- Building libecpg_compat x64-windows-RELEASE... done
-- Installing libpq x64-windows-RELEASE...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: D:/vcpkg/downloads/tools/perl/perl/bin/perl.exe install.pl D:/vcpkg/packages/libpq_x64-windows client
    Working Directory: D:/vcpkg/buildtrees/libpq/x64-windows-rel/src/tools/msvc
    Error code: 2
    See logs for more information:
      D:\vcpkg\buildtrees\libpq\install-x64-windows-RELEASE-err.log

Call Stack (most recent call first):
  ports/libpq/portfile.cmake:204 (vcpkg_execute_required_process)
  scripts/ports.cmake:94 (include)


Error: Building package libpq:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libpq:x64-windows
  Vcpkg version: 2019.09.12-nohash

Additionally, attach any relevant sections from the log files above.
```

**Additional context**
install-x64-windows-RELEASE-err.log
```
Could not find debug or release binaries at D:\vcpkg\buildtrees\libpq\x64-windows-rel\src\tools\msvc/Install.pm line 77.
```

**Comment by PhoebeHui** [comment]
@longhuan2018 , I can't repro this issue, could you remove openssl and rebuild again?

I get latest clean vcpkg source, and everything build successfully.
PS F:\vcpkg\op\vcpkg> ./vcpkg install libpq:x64-windows
The following packages will be built and installed:
    libpq[core,openssl,zlib]:x64-windows
  * openssl[core]:x64-windows
  * openssl-windows[core]:x64-windows
  * zlib[core]:x64-windows
...
-- Installing libpq x64-windows-DEBUG... done
-- Cleanup libpq x64-windows...
-- Cleanup libpq x64-windows... - done
-- Installing: F:/VCPKG/op/vcpkg/packages/libpq_x64-windows/share/postgresql/vcpkg-cmake-wrapper.cmake
-- Installing: F:/VCPKG/op/vcpkg/packages/libpq_x64-windows/share/libpq/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package libpq[core,openssl,zlib]:x64-windows... done
Installing package libpq[core,openssl,zlib]:x64-windows...
Installing package libpq[core,openssl,zlib]:x64-windows... done
Elapsed time for package libpq:x64-windows: 2.198 min

**Comment by longhuan2018** [comment]
I retested it in a brand new environment and found that it was successfully installed. I will check my original environment again

> @longhuan2018 , I can't repro this issue, could you remove openssl and rebuild again?
> 
> I get latest clean vcpkg source, and everything build successfully.
> PS F:\vcpkg\op\vcpkg> ./vcpkg install libpq:x64-windows
> The following packages will be built and installed:
> libpq[core,openssl,zlib]:x64-windows
> 
> * openssl[core]:x64-windows
> * openssl-windows[core]:x64-windows
> * zlib[core]:x64-windows
>   ...
>   -- Installing libpq x64-windows-DEBUG... done
>   -- Cleanup libpq x64-windows...
>   -- Cleanup libpq x64-windows... - done
>   -- Installing: F:/VCPKG/op/vcpkg/packages/libpq_x64-windows/share/postgresql/vcpkg-cmake-wrapper.cmake
>   -- Installing: F:/VCPKG/op/vcpkg/packages/libpq_x64-windows/share/libpq/copyright
>   -- Performing post-build validation
>   -- Performing post-build validation done
>   Building package libpq[core,openssl,zlib]:x64-windows... done
>   Installing package libpq[core,openssl,zlib]:x64-windows...
>   Installing package libpq[core,openssl,zlib]:x64-windows... done
>   Elapsed time for package libpq:x64-windows: 2.198 min
