### ISSUE TITLE
[fizz] update to latest version

### ISSUE THREAD

**Issue by z6833** [microsoft/vcpkg#9724]
Library name:fizz

New version number:v2020.01.13.00

Other information that may be useful (release notes, etc...): I want to install project named mvfst , and it requests the dependencies of fizz and others . And I installed fizz by vcpkg , it got many errors . I asked the author of mvfst for help , and he said I should get the latest version of fizz . I just do not konw how to compile fizz by vcpkg with latest version of fizz . Anyone can help ?

**Comment by NancyLi1013** [comment]
Hi @z6833 thanks for posting this issue.
`Fizz` has been updated to latest version. Please try to update vcpkg and use it.
