### ISSUE TITLE
[breakpad] build failure

### ISSUE THREAD

**Issue by chenpei2** [microsoft/vcpkg#9727]
**Host Environment**
- OS: [windows10]
- Compiler: cmake 3.16.2

**To Reproduce**
`./vcpkg install breakpad:x64-windows`

**Failure logs** 
```
E:\vcpkg\vcpkg\buildtrees\breakpad\src\f427f61ed3-fe83a49e5d\src\common/windows/pe_util.h(64): error C3249: illegal statement or sub-expression for 'constexpr' function
E:\vcpkg\vcpkg\buildtrees\breakpad\src\f427f61ed3-fe83a49e5d\src\common/windows/pe_util.h(65): error C3249: illegal statement or sub-expression for 'constexpr' function
E:\vcpkg\vcpkg\buildtrees\breakpad\src\f427f61ed3-fe83a49e5d\src\common/windows/pe_util.h(68): error C3249: illegal statement or sub-expression for 'constexpr' function
E:\vcpkg\vcpkg\buildtrees\breakpad\src\f427f61ed3-fe83a49e5d\src\common/windows/pe_util.h(69): error C3249: illegal statement or sub-expression for 'constexpr' function
E:\vcpkg\vcpkg\buildtrees\breakpad\src\f427f61ed3-fe83a49e5d\src\common/windows/pe_util.h(63): error C3259: 'constexpr' functions can only have one return statement
```
**Additional context**
1.It can be fixed by removing "constexpr" from the source code, but it's a bad idea to do it.
2.I tried to add "target_compile_features(libbreakpad PRIVATE cxx_constexpr)" and "target_compile_features(libbreakpad_client PRIVATE cxx_constexpr)" into E:\vcpkg\vcpkg\ports\breakpad\CMakeLists.txt , it didn't work.

**Comment by JackBoosY** [comment]
Hi @chenpei2, thanks for reporting this issue!
Even if I can't repro this issue, I will still create a PR to solve it.

Thanks.

**Comment by NancyLi1013** [comment]
@chenpei2 Could you please help confirm which version you used VS? is it VS2015?

**Comment by chenpei2** [comment]
> @chenpei2
> Could you please help confirm which version you used VS?
> Please make sure you have installed Visual Studio 2015 Update 3 or newer.

I tried VS2019 and succeeded.Thanks!

**Comment by OZ1** [comment]
Microsoft Visual Studio Enterprise 2015
Version 14.0.25431.01 Update 3

still reproducable

**Comment by JackBoosY** [comment]
@OZ1 With the details, I think this is a Visual Studio bug that has been fixed in a newer version.

**Comment by zh1an** [comment]
@JackBoosY So, breakpad is compiled with VS2015 with update 3?

**Comment by JackBoosY** [comment]
@zh1an Please use Visual Studio 2019 to build it.

**Comment by Sunbreak** [comment]
https://github.com/Sunbreak/breakpad/commit/062107926e69ef4d4737a1a6de3162ee4006e0f9
