### ISSUE TITLE
[New Port Request] libu2f-host

### ISSUE THREAD

**Issue by vishleshpatel** [microsoft/vcpkg#9728]
Library name: libu2f-host

Library description: Yubico Universal 2nd Factor (U2F) Host C Library

Source repository URL: https://github.com/Yubico/libu2f-host

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

Library has 2 dependancies : json-c and hidapi, both of which is supported by vcpkg.

**Comment by LilyWangL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
