### ISSUE TITLE
[vcpkg_acquire_msys] Error when SOURCE_PATH is not defined

### ISSUE THREAD

**Issue by JackBoosY** [microsoft/vcpkg#9729]
**Describe the bug**
When we use `vcpkg_acquire_msys`, if `SOURCE_PATH` is not defined, we will encounter an error:
```
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:50 (_execute_process):
  _execute_process called with no value for WORKING_DIRECTORY.
Call Stack (most recent call first):
  scripts/cmake/vcpkg_acquire_msys.cmake:119 (vcpkg_execute_required_process)
```

Related code:
https://github.com/microsoft/vcpkg/blob/bf3e071e53bf46cba8857859f853dcc8898db817/scripts/cmake/vcpkg_acquire_msys.cmake#L122

**Comment by LilyWangLL** [comment]
Fixed by PR #18110
