### ISSUE TITLE
[<boost>] build failure

### ISSUE THREAD

**Issue by how0723** [microsoft/vcpkg#9730]
**Host Environment**
- OS: [e.g. Windows/Linux etc...] linux x64
- Compiler: gcc 8.3

**To Reproduce**
`./vcpkg install boost`

**Failure logs** 
```
Additional packages (*) will be modified to complete this operation.
Starting package 1/24: boost-wave:x64-linux
Building package boost-wave[core]:x64-linux...
-- Using cached /home/vcpkg/downloads/boostorg-wave-boost-1.72.0.tar.gz
-- Using source at /home/vcpkg/buildtrees/boost-wave/src/ost-1.72.0-bb7fc979af
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: /home/tools/cmake-3.16.2-Linux-x86_64/bin/cmake --build . --config Debug --target install -- -v
    Working Directory: /home/vcpkg/buildtrees/boost-wave/x64-linux-dbg
    See logs for more information:
      /home/vcpkg/buildtrees/boost-wave/install-x64-linux-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:91 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  installed/x64-linux/share/boost-build/boost-modular-build.cmake:90 (vcpkg_install_cmake)
  ports/boost-wave/portfile.cmake:14 (boost_modular_build)
  scripts/ports.cmake:94 (include)


Error: Building package boost-wave:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-wave:x64-linux
  Vcpkg version: 2019.09.12-unknownhash

Additionally, attach any relevant sections from the log files above.
```

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by PhoebeHui** [comment]
@how0723, I can't repro this issue, currently boost has been upgrade to 1.72.0, could you update the source and rebuild all boost components again?

Please attach failure log 'install-x64-linux-dbg-out.log' if it still be a problem for you.

./vcpkg install boost-wave:x64-linux
Your feedback is important to improve Vcpkg! Please take 3 minutes to complete our survey by running: vcpkg contact --survey
The following packages will be built and installed:
    boost-wave[core]:x64-linux
Starting package 1/1: boost-wave:x64-linux
Building package boost-wave[core]:x64-linux...
-- Downloading https://github.com/boostorg/wave/archive/boost-1.72.0.tar.gz...
-- Extracting source /home/vphma/Phoebe/vcpkg/downloads/boostorg-wave-boost-1.72.0.tar.gz
-- Using source at /home/vphma/Phoebe/vcpkg/buildtrees/boost-wave/src/ost-1.72.0-bb7fc979af
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
-- Building x64-linux-rel
-- Packaging headers
-- Packaging headers done
-- Using cached /home/vphma/Phoebe/vcpkg/downloads/boost_LICENSE_1_0.txt
-- Installing: /home/vphma/Phoebe/vcpkg/packages/boost-wave_x64-linux/share/boost-wave/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package boost-wave[core]:x64-linux... done
Installing package boost-wave[core]:x64-linux...
Installing package boost-wave[core]:x64-linux... done
Elapsed time for package boost-wave:x64-linux: 1.472 min

Total elapsed time: 1.472 min

**Comment by how0723** [comment]
I use a new folder to git clone vcpkg and install boost, this problem did not reproduced.
Days ago, I use ./vcpkg upgrade --no-dry-run, lead to this problem.
@PhoebeHui
