### ISSUE TITLE
boost/asio include failure

### ISSUE THREAD

**Issue by OlafvdSpek** [microsoft/vcpkg#9731]
- Windows 10 
- Compiler: MSVC 16.5.0 preview 1

`/std:c++17` is fine
`/std:c++latest` is not

```
#include <boost/asio.hpp>

int main()
{
}
```

```
boost\asio\async_result.hpp:
template <typename T, typename... Args>
BOOST_ASIO_CONCEPT callable_with = requires(T t, Args&&... args) // error C2062: type 'bool' unexpected
```

```
1>------ Build started: Project: Test1, Configuration: Debug Win32 ------
1>Test1.cpp
1>Please define _WIN32_WINNT or _WIN32_WINDOWS appropriately. For example:
1>- add -D_WIN32_WINNT=0x0601 to the compiler command line; or
1>- add _WIN32_WINNT=0x0601 to your project's Preprocessor Definitions.
1>Assuming _WIN32_WINNT=0x0601 (i.e. Windows 7 target).
1>C:\vc\vcpkg\installed\x86-windows\include\boost\asio\async_result.hpp(44,1): error C2062: type 'bool' unexpected
```

**Comment by PhoebeHui** [comment]
@OlafvdSpek, it's not a vcpkg issue. you can see boost related issue https://github.com/boostorg/asio/issues/312.

BTW, could you try to pass option '/DBOOST_ASIO_DISABLE_CONCEPTS' and see if it solve this issue?

**Comment by OlafvdSpek** [comment]
Shouldn't vcpkg tests have detected this issue before the port update was merged?

**Comment by PhoebeHui** [comment]
@OlafvdSpek, It's a issue that with /std:c++latest option, currently this option hasn't been covered in our CI testing.

**Comment by OlafvdSpek** [comment]
How come?

**Comment by OlafvdSpek** [comment]
`BOOST_ASIO_DISABLE_CONCEPTS` works too.

**Comment by cbezault** [comment]
It's not tested because there's only so many combinations of compiler flags that can be tested.

**Comment by OlafvdSpek** [comment]
That's the downside of compiler flags. Which combinations are tested?

**Comment by cbezault** [comment]
Yeah it's not easy to tell and I think I should let one of the maintainers answer. To be honest, this should either be documented or the CI should be transitioned to using a YAML file that anyone can easily look at in the repo.

**Comment by JackBoosY** [comment]
Please reopen this issue when it is fixed upstream.
