### ISSUE TITLE
[New Port Request] threadpool

### ISSUE THREAD

**Issue by jesseschalken** [microsoft/vcpkg#9735]
Library name: threadpool

Library description: threadpool is a cross-platform C++ thread pool library. It provides a convenient way for dispatching asynchronous tasks and can be easily customized. threadpool is based on the high-quality Boost source libraries.

Source repository URL: https://sourceforge.net/p/threadpool/code/

Project homepage (if different from the source repository): http://threadpool.sourceforge.net/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

Seems to be just a header-only library that depends on `boost-thread`. It should just be a matter of extracting https://sourceforge.net/projects/threadpool/files/threadpool/0.2.5%20%28Stable%29/threadpool-0_2_5-src.zip/download and adding the required include paths.

**Comment by LilyWangL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
