### ISSUE TITLE
[New Port Request]  osqp

### ISSUE THREAD

**Issue by traversaro** [microsoft/vcpkg#9738]
Library name: osqp

Library description: The OSQP (Operator Splitting Quadratic Program) solver is a numerical optimization package for solving quadratic optimization problems. 

Source repository URL: https://github.com/oxfordcontrol/osqp

Project homepage (if different from the source repository): https://osqp.org/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):
* repology : https://repology.org/project/osqp/versions

**Comment by LilyWangL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.

**Comment by GiulioRomualdi** [comment]
Accordingly to this issue: https://github.com/microsoft/vcpkg/issues/1036 the first step will be to create a port of `qldldl`. The linear solver used in `osqp` that it's treated as a submodule.

**Comment by traversaro** [comment]
> Accordingly to this issue: #1036 the first step will be to create a port of `qdldl`. The linear solver used in `osqp` that it's treated as a submodule.

Unless https://github.com/oxfordcontrol/osqp/issues/85 is solved, either upstream or with a vcpkg specific patch, osqp cannot consume qdldl provided by a vcpkg port.

**Comment by traversaro** [comment]
As highlighted in https://github.com/RobotLocomotion/drake/issues/11697, another issue from the packaging perspective is that osqp also vendors [AMD](https://github.com/DrTimothyAldenDavis/SuiteSparse/tree/master/AMD), that is already part of suitesparse for which a port in vcpkg is available (https://github.com/microsoft/vcpkg/blob/master/ports/suitesparse/portfile.cmake).
