### ISSUE TITLE
Error: Building package parson:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by brad-dixon** [microsoft/vcpkg#9740]
Your script told me to create an issue so here I am.  :-)

Running on Windows 10, this command from the instructions at ... https://docs.microsoft.com/en-us/azure/iot-edge/how-to-visual-studio-develop-module ...

**vcpkg.exe install azure-iot-sdk-c:x64-windows**

... after having built **vcpkg.exe**, this is the output I received ...

The following packages will be built and installed:
  * azure-c-shared-utility[core]:x64-windows
    azure-iot-sdk-c[core]:x64-windows
  * azure-macro-utils-c[core]:x64-windows
  * azure-uamqp-c[core]:x64-windows
  * azure-uhttp-c[core]:x64-windows
  * azure-umqtt-c[core]:x64-windows
  * parson[core]:x64-windows
  * umock-c[core]:x64-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/8: parson:x64-windows
Building package parson[core]:x64-windows...
parson only supports static linkage
-- Using cached C:/Repos/vcpkg/downloads/kgabis-parson-33e5519d0ae68784c91c92af2f48a5b07dc14490.tar.gz
-- Using source at C:/Repos/vcpkg/buildtrees/parson/src/b07dc14490-fe9872edbc
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: ninja -v
    Working Directory: C:/Repos/vcpkg/buildtrees/parson/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\Repos\vcpkg\buildtrees\parson\config-x64-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:295 (vcpkg_execute_required_process)
  ports/parson/portfile.cmake:18 (vcpkg_configure_cmake)
  scripts/ports.cmake:94 (include)

Error: Building package parson:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: parson:x64-windows
  Vcpkg version: 2020.01.17-nohash

Additionally, attach any relevant sections from the log files above.

Log file mentioned above attached.
[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/4080045/config-x64-windows-out.log)

Apologies but this is all a black box to me and basically, it's listed as a pre-requisite to in the URL I provided above.  If there's anything else you need from me, I'm more than happy to provide it.

**Comment by PhoebeHui** [comment]
@brad-dixon, I can't repro this issue, from your log, it failed with following failure, there is a similar issue https://github.com/microsoft/vcpkg/issues/9554, could you double check if you have similar permission issue?

```
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.24.28314/bin/Hostx64/x64/cl.exe -- broken
CMake Error at C:/Repos/vcpkg/downloads/tools/cmake-3.14.0-windows/cmake-3.14.0-win32-x86/share/cmake-3.14/Modules/CMakeTestCCompiler.cmake:60 (message):
  The C compiler

    "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.24.28314/bin/Hostx64/x64/cl.exe"

  is not able to compile a simple test program.
  It fails with the following output:
    Change Dir: C:/Repos/vcpkg/buildtrees/parson/x64-windows-dbg/CMakeFiles/CMakeTmp
```

**Comment by PhoebeHui** [comment]
@brad-dixon, you can try https://github.com/microsoft/vcpkg/issues/9554#issuecomment-571059914, please reopen this issue if it still be a problem for you.
