### ISSUE TITLE
[New Port Request] libavif

### ISSUE THREAD

**Issue by atkawa7** [microsoft/vcpkg#9741]
Library name: libavif

Library description: Library for encoding and decoding .avif files

Source repository URL: https://github.com/AOMediaCodec/libavif

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by LilyWangL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.

**Comment by HappySeaFox** [comment]
#18244
