### ISSUE TITLE
[New Port Request] acl

### ISSUE THREAD

**Issue by zh1an** [microsoft/vcpkg#9750]
Library name: acl

Library description: Server framework and network components written by C/C++ for Linux, Mac, FreeBSD, Solaris(x86), Windows, Android, IOS

Source repository URL: https://github.com/acl-dev/acl.git

Project homepage (if different from the source repository): https://blog.csdn.net/zsxxsz

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by LilyWangL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
