### ISSUE TITLE
[New Port Request] OOQP

### ISSUE THREAD

**Issue by xarthurx** [microsoft/vcpkg#9757]
Library name: OOQP

Library description:
OOQP is an object-oriented C++ package, based on a primal-dual interior-point method, for solving convex quadratic programming problems (QPs). It contains code that can be used "out of the box" to solve a variety of structured QPs, including general sparse QPs, QPs arising from support vector machines, Huber regression problems, and QPs with bound constraints.

OOQP also can be used as a framework can be used to design efficient solvers for new classes of structured QPs. Its design allows for easy substitution of the linear algebra modules, allowing different standard linear algebra packages to be tried.

Source repository URL:
https://github.com/emgertz/OOQP

Project homepage (if different from the source repository):
http://pages.cs.wisc.edu/~swright/ooqp/

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

P.S. This is a very widely used library for the optimization field.

**Comment by LilyWangL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
