### ISSUE TITLE
[pcl] update to 1.10

### ISSUE THREAD

**Issue by traversaro** [microsoft/vcpkg#9765]
Library name: PCL (Point Cloud Library)

New version number: 1.10.0

Other information that may be useful (release notes, etc...): 
* https://github.com/PointCloudLibrary/pcl/releases/tag/pcl-1.10.0
* https://github.com/PointCloudLibrary/pcl/issues/2772

**Comment by Neumann-A** [comment]
included in #9202 to fix the PCL regression. 
VTK option is disabled until they fix https://github.com/PointCloudLibrary/pcl/issues/3408

**Comment by NancyLi1013** [comment]
@Neumann-A Thanks for your update.

**Comment by aslze** [comment]
PCL 1.11 is already out. Maybe we should aim at this instead of 1.10.

https://github.com/PointCloudLibrary/pcl/releases/tag/pcl-1.11.0

They finally got rid of boost::shared_ptr and use std::shared_ptr.

**Comment by aslze** [comment]
And, well, in the mean time, if the upgrade is hard, we can apply this commit as a patch, which fixed a bug after 1.9.1 was released, but before 1.10:

https://github.com/PointCloudLibrary/pcl/commit/36c2bd6209f87dc7c6f56e2c0314e19f9cab95ec

I'm not sure how to do that. Create a .patch file from there and add it to the port file? What is the "index" (second line) in patch files? It's the only part I can't figure out.

**Comment by NancyLi1013** [comment]
Hi @aslze 
Thanks for your above info. I will check this later.

**Comment by NancyLi1013** [comment]
@aslze 
PCL will be updated via #10042. You can rebuild it based on this PR.

**Comment by NancyLi1013** [comment]
I'm closing this issue for now since it has been updated to 1.11.0.
Please update vcpkg to the latest version and rebuild it.
