### ISSUE TITLE
vcpkg bootstrap error

### ISSUE THREAD

**Issue by riodda** [microsoft/vcpkg#9769]
I have the vcpkg error on  VC 20197

Version: 1.41.1 (user setup)
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:58:56.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362

PS C:\vcpkg-master> .\bootstrap-vcpkg.bat
Could not find Visual Studio. VS2015 or VS2017 (with C++) needs to be installed.
In C:\vcpkg-master\scripts\bootstrap.ps1:143 car:9
+         throw "Could not find Visual Studio. VS2015 or VS2017 (with C ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Could not find ...o be installed.:String) [], RuntimeException
    + FullyQualifiedErrorId : Could not find Visual Studio. VS2015 or VS2017 (with C++) needs to be installed.

Tryed to reboot, no solution
I have this extensions installed

Name: C/C++
Id: ms-vscode.cpptools
Description: C/C++ IntelliSense, debugging, and code browsing.
Version: 0.26.2
Publisher: Microsoft

Name: C/C++ Snippets
Id: hars.cppsnippets
Description: Code snippets for C/C++
Version: 0.0.14
Publisher: Harsh

Name: PlatformIO IDE
Id: platformio.platformio-ide
Description: Development environment for Embedded, IoT, Arduino, ARM mbed, Espressif (ESP8266/ESP32), AVR, RISC-V, STM32, PIC32, nRF51/nRF52, MSP430, MCS-51 (8051), FPGA, FreeRTOS, ESP-IDF, CMSIS, SPL
Version: 1.10.0
Publisher: PlatformIO

**Comment by LilyWangL** [comment]
Hi @riodda, thanks for posting this issue! Do you install Visual Studio before clone VCPKG?

**Comment by drescherjm** [comment]
Seems like you are trying Visual Studio Code and not Visual Studio

**Comment by riodda** [comment]
Now i know !!! Many thanks for help !

**Comment by LilyWangL** [comment]
Thanks for posting this issue. This issue has been fixed. So I am closing this issue for now.
