### ISSUE TITLE
Add ANGLE

### ISSUE THREAD

**Issue by mr-MOD** [Microsoft/vcpkg#977]
[https://github.com/google/angle](ANGLE)

ANGLE - Almost Native Graphics Layer Engine
The goal of ANGLE is to allow users of multiple operating systems to seamlessly run WebGL and other OpenGL ES content by translating OpenGL ES API calls to one of the hardware-supported APIs available for that platform. ANGLE currently provides translation from OpenGL ES 2.0 and 3.0 to desktop OpenGL, OpenGL ES, Direct3D 9, and Direct3D 11. Support for translation from OpenGL ES to Vulkan is underway.

Google Chrome and Mozilla Firefox use ANGLE as their WebGL backend.

**Comment by atkawa7** [comment]
@ras0219-msft Could you close this?
