### ISSUE TITLE
Add example for using libc++ on Linux

### ISSUE THREAD

**Issue by cmazakas** [microsoft/vcpkg#9783]
It would be incredibly helpful if there was an example of how to use libc++ with vcpkg to build packages. The docs as they are don't help users enough in setting up this custom toolchain.

In the ideal, we'd have a small tutorial that starts with a `wget` to the clang binaries and stdlib followed  by the creation of a sample toolchain file and how that gets integrated into a custom build triplet.

**Comment by cpsusie** [comment]
Yes.  I want to use clang and libc++ in Linux to build packages too!

**Comment by luncliff** [comment]
I used to override the environment variable `CC` and `CXX` for this usecase. https://github.com/microsoft/vcpkg/pull/10693#issuecomment-610394650
Its basic approach is like this...

```console
luncliff@CIC:/mnt/develop/vcpkg$ export CC=clang++-8 CXX=clang++-8
luncliff@CIC:/mnt/develop/vcpkg$ ./vcpkg install ${package}
Computing installation plan...
```

**Comment by luncliff** [comment]
I think this can be a worthy guideline (like `docs/users/android.md`) for some people who want to set up their own CI with VcPkg.

**Comment by cpsusie** [comment]
> I used to override the environment variable `CC` and `CXX` for this usecase. [#10693 (comment)](https://github.com/microsoft/vcpkg/pull/10693#issuecomment-610394650)
> Its basic approach is like this...
> 
> ```
> luncliff@CIC:/mnt/develop/vcpkg$ export CC=clang++-8 CXX=clang++-8
> luncliff@CIC:/mnt/develop/vcpkg$ ./vcpkg install ${package}
> Computing installation plan...
> ```

Does that suffice to make it build using clang's C++ standard library (libc++) as opposed to GCC's C++ standard library (libstdc++)?  Or do you need to add something more for that?

**Comment by davidhunter22** [comment]
I'm pretty certain that is not sufficient. By default clang++ uses libstdc++ which is the GCC standard library. You need to pass the -stdlib=libc++ flag  to get it to use the Clang standard C++ library. 
I have been using the Clang compiler with libstdc++ with no problems for a while.
If I pass the -stdlib=libc++ to my build I get link errors, also vcpkg does not rebuild any packages ( I am using a manifests ). So my issue at the moment is that I can't work out how to tell vcpkg to rebuild stuff with  -stdlib=libc++. Note some libraries may may not build as the two standard libries support different features.
An example of how to do this, if it's possible, would be awesome.
I will attach a small failing example soon, assuming no one post how to do things.

**Comment by vicroms** [comment]
@davidhunter22 how are you passing the compiler options? 

I recommend creating a custom triplet file, e.g.: `x64-linux-clang-libcxx`, and using a CMake toolchain file to set the compiler and standard library. An advantage of using a custom triplet is that packages will be installed to `installed/{triplet-name}` so they won't collide with your existing packages.

[Read more about triplets](https://github.com/microsoft/vcpkg/blob/master/docs/users/triplets.md).

**Comment by JackBoosY** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.
