### ISSUE TITLE
[New Port Request] mqtt_cpp

### ISSUE THREAD

**Issue by anion155** [microsoft/vcpkg#9785]
Library name: mqtt_cpp

Library description:
MQTT client/server for C++14 based on Boost.Asio

Source repository URL:
https://github.com/redboltz/mqtt_cpp

Anything else that is useful to know when adding (such as optional features the library may have that should be included):
mqtt_cpp is a header only library. It requires C++14 and the Boost Libraries 1.66.0 or later.
Library has separate client and server headers and optional websockets feature.

**Comment by PhoebeHui** [comment]
@anion155, the PR has been merged, thanks for your contribution!
