### ISSUE TITLE
[New Port Request] libspng

### ISSUE THREAD

**Issue by stepan-pieshkin** [microsoft/vcpkg#9786]
Library name: libspng

Library description: libspng is a C library for reading and writing Portable Network Graphics (PNG) format files with a focus on security and ease of use. The goal is to provide a fast PNG library with a simpler API than [libpng]

Source repository URL: https://github.com/randy408/libspng/

Project homepage (if different from the source repository): https://libspng.org/

Anything else that is useful to know when adding (such as optional features the library may have that should be included): requires zlib

**Comment by LilyWangL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.

**Comment by JonLiu1993** [comment]
Solved by #20000
