### ISSUE TITLE
How do I get jsoncpp example to run

### ISSUE THREAD

**Issue by mboedigh** [microsoft/vcpkg#9790]
I've installed jsoncpp via the vcpkg and run the very simple test program
```
	ifstream fin("test.json");
	Json::Value root;   // starts as "null"; will contain the root value after parsing
	fin >> root;
	cout << root;

	// Get the value of the member of root named 'my-encoding', return 'UTF-32' if there is no
	// such member.
	std::string my_encoding = root.get("my-encoding", "UTF-32").asString();

	// Get the value of the member of root named 'my-plug-ins'; return a 'null' value if
	// there is no such member.
	const Json::Value my_plugins = root["my-plug-ins"];
	vector<string> v;
	for (int index = 0; index < my_plugins.size(); ++index)  // Iterates over the sequence elements.
	{
		Json::Value value = my_plugins[index]; // copy 
		v.push_back(value.asString());
	}
```

The program runs if my test project is configured with Multi-threaded Debug DLL Runtime Library (/MDd). But, it compiles but does not run correctly (crashes with memory problems) if complied with Multi-threaded Debug Runtime Library (/MTd). The trouble is that my actual project must be compiled with /MTd. At least I think so, because other third part libraries that my project is dependent on are static. 

Questions. has anyone else seen this? is there someway to get /MTd to work with jsoncpp?

**Comment by JackBoosY** [comment]
Hi @mboedigh, thanks for reporting this issue!
Here are two solutions, you can choose one:

1. Modify _VCPKG_PATH/triplets/<YOUR_SELECTE_TRIPLET>.cmake_ and set `VCPKG_CRT_LINKAGE` to `static`. Then rebuild jsoncpp.

2. Create a new triplet file in  _VCPKG_PATH/triplets_ and add the following code:
```
set(VCPKG_TARGET_ARCHITECTURE <ARCH>)
set(VCPKG_CRT_LINKAGE static)
set(VCPKG_LIBRARY_LINKAGE <dynamic/static>)
```
Then use command `.\vcpkg install jsoncpp:<TRIPLET_NAME>` to build jsoncpp.

**Comment by JackBoosY** [comment]
If this issue is still not resolved, please reopen it.
