### ISSUE TITLE
Can vcpkg be used for applications too, or only libraries?

### ISSUE THREAD

**Issue by cesss** [microsoft/vcpkg#9791]
I just found out **vcpkg** and I'm very excited, because it might be just the kind of library management system I was looking for for years!! However, I have a question not answered in the FAQ, nor in any other place (AFAIK): Can you use it also for applications? Some of my projects depend not only on third-party libraries, but also on third-party executables to be built (doxygen, rsync, flex, and quite a few UNIX tools). Can I somehow use **vcpkg** for building them too?

**Comment by Neumann-A** [comment]
some ports have a tools feature which builds executables/tools of a port. So the answer is probably yes although some tools should be downloaded as binaries instead of build.

**Comment by cesss** [comment]
@Neumann-A 
Can you elaborate on the reason for the _"some tools should be downloaded as binaries instead of build"_ affirmation? (I'm not asking about existing ports, but about ports created by myself: can there be any case in which I wouldn't be able to build executables and install them into a location in my $PATH, as required dependencies before building another port?

**Comment by PhoebeHui** [comment]
@cesss, does this issue still bother you? if the executables doesn't require for your project or dependency port, then it's not required in vcpkg.

**Comment by cesss** [comment]
@PhoebeHui 
Dear Phoebe,
Unfortunately, **vcpkg** is not the package manager I was looking for, because I really need to be able to specify the required version of each library in the dependencies for a package, This is a must-have feature for me from day 1 (as I posted [in this other issue](https://github.com/microsoft/vcpkg/issues/1681)). I was excited bout **vcpkg**, as it can be seen in the first post above, but really not being able to specify that, for example, package Acme 5.7 requires libAcme >2.9 but <4.0 really makes **vcpkg** unsuitable for my use.

Said this, of course, I don't understand why a package manager works with libraries only, and not with programs. This would also be another reason why I cannot use **vcpkg**.

I moved to another package manager, so feel free to close this issue.

**Comment by PhoebeHui** [comment]
@cesss, thanks for your feedback.

**Comment by sfhacker** [comment]
> I moved to another package manager, so feel free to close this issue.

@cesss Would you be so kind as to either post here or email me privately the package manager you are using at the moment?
The other day we came across a package manager for MinGW/MSYS environment that does exactly what you have mentioned in several of your posts.
Cheers.
