### ISSUE TITLE
Invent vcpkg_copy_tools()

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#9792]
**Is your feature request related to a problem? Please describe.**
Copying executables from `bin` to `tools/${PORT}`

**Proposed solution**
Invent vcpkg_copy_tools() with the following params:
- TOOL_(NAMES;LIST): list of tools without executable suffix
- (RELEASE_|DEBUG_)SUFFIXES additional suffixes to append (before VCPKG_TARGET_EXECUTABLE_SUFFIX)
- BASE_PATH (if not bin/)
- CMAKE_FIX_TARGETS: List of generated CMake files which need fixing
- TARGET_PATH (if different from tools/${PORT})

**What it does?**
- Check if the tool exists
- If no do nothing - If yes copy/rename tool into tools/${PORT} 
- remove from bin and debug/bin
- fix cmake targets if required
- call vcpkg_copy_tool_dependencies

**Comment by vicroms** [comment]
There's PR #8749 which I reviewed but ended up losing track of it.
