### ISSUE TITLE
[CI] Include all **/*.log files from buildtrees/<port> on failure

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#9802]
Sometimes the logs vcpkg creates in `buildtrees/<port>` are not enough and logs from deeper within the directory are required. Famous example `buildtrees/<port>/<triplet>-<config>/CMakeFiles/CMake(Output|Error).log`. There are also other logs generated by e.g. qt5/qmake or `vcpkg_configure_make` which are deeper within the directory.

**Comment by Neumann-A** [comment]
another example from the buildtree: meson.log

**Comment by wrobelda** [comment]
I am facing some peculiar issue that I cannot reproduce locally, see https://github.com/microsoft/vcpkg/pull/20426#issuecomment-946807357

Not having immediate access to build/config.log is a huge bummer.

**Comment by dg0yt** [comment]
> Wouldn't changing [this](https://github.com/microsoft/vcpkg-tool/blob/86e70edb07bd7973b03d3e3c41c46c203c94001b/src/vcpkg/commands.ci.cpp#L49) to find files recursively suffice?

I don't think that walking entire trees of gdal or tensorflow is a good idea.
I would rather propose some unconditional or on-error tear-down hook for execute-process.
(I need `config.log`, too.)
