### ISSUE TITLE
OpenSSL fails to link

### ISSUE THREAD

**Issue by quickiwiki** [microsoft/vcpkg#9803]
**Host Environment**
- OS: Linux Ubuntu 18.04
- Compiler:  GNU 8.3.0

**To Reproduce**
install protobuf grpc

and try to use them in a project

find_package(OpenSSL REQUIRED)
find_package(Protobuf CONFIG REQUIRED)
find_package(gRPC CONFIG REQUIRED)
find_package(fmt CONFIG REQUIRED)
find_package(spdlog REQUIRED)

**Failure logs** 

https://pastebin.com/xC7VKjub
```
-- The C compiler identification is GNU 8.3.0
-- The CXX compiler identification is GNU 8.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/g++
-- Check for working CXX compiler: /usr/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Boost version: 1.72.0
-- Found ZLIB: /root/vcpkg/installed/x64-linux/lib/libz.a (found version "1.2.11")
-- Found OpenSSL: /root/vcpkg/installed/x64-linux/lib/libcrypto.a (found version "1.1.1d")
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
CMake Error at /root/vcpkg/installed/x64-linux/share/openssl/vcpkg-cmake-wrapper.cmake:14 (target_link_libraries):
  Cannot specify link libraries for target "OpenSSL::Crypto" which is not
  built by this project.
Call Stack (most recent call first):
  /root/vcpkg/scripts/buildsystems/vcpkg.cmake:240 (include)
  /root/vcpkg/installed/x64-linux/share/grpc/gRPCConfig.cmake:9 (find_package)
  /root/vcpkg/scripts/buildsystems/vcpkg.cmake:283 (_find_package)
  CMakeLists.txt:8 (find_package)
```
**Additional context**
https://github.com/microsoft/vcpkg/pull/8566/commits/98a3755317f8b2ff2be419adefadbf36d2548436

BREAKS THE BUILD

**Comment by Neumann-A** [comment]
Yawn... CMake Version used? What Version is used in your downstream cmake_minimum_required? 
VCPKG uses internally 3.14 so you should try to use at least that version. Alternativly submit a PR which replaces the target_link_library call with a set_target_properties call

**Comment by JackBoosY** [comment]
@vicroms With more and more of these issues, do we need to revert to use user-installed cmake?

**Comment by vpaladino778** [comment]
I noticed this issue as well, the annoying thing is, when you do a typical `sudo apt-get install cmake` on ubuntu 18.04, it installs CMake version 3.10. which is really a pain.

**Comment by vpaladino778** [comment]
I noticed today that even after upgrading cmake (I installed via Snap and am on version 3.16.3) that i am still facing this issue.

**Comment by JackBoosY** [comment]
@vpaladino778 Yep, upgrading cmake on ubuntu is a pain.

**Comment by JackBoosY** [comment]
I think this issue was resolved, if it wasn't, you can reopen with more info.
