### ISSUE TITLE
[CUDA] update to 10.2

### ISSUE THREAD

**Issue by jasjuang** [microsoft/vcpkg#9806]
Library name: CUDA

New version number: 10.2

Simply changing the `set(CUDA_REQUIRED_VERSION "V10.1")` to `set(CUDA_REQUIRED_VERSION "V10.2")` seems to work for me, but it looks like CUDNN needs to be updated as well but I am not sure how to do it.

**Comment by timautry** [comment]
On the cudnn developer's site (https://developer.nvidia.com/rdp/cudnn-download) shows version 7.6.5 to be compatible with CUDA 9.0 upwards.
I currently have CUDA 10.2.89 the only version of nvcc I have installed on windows 10 1909 64-bit.
I have install package cudnn on both VS 2017 and 2019 in x64-windows triplet (dynamic).
The CUDA portfile seems to make sure the version is at least 10.1 as it does a less than on the major/minor versions and gets the CUDA_PATH and CUDA_BIN_PATH from the environment variables set by CUDA during installation. Do note, the CUDA, ATLMFC and VULKAN packages are basically place holders (aka empty packages) as they just check to make sure you have the appropriate SDK or software installed. 
The cudnn and other packages using cuda all have installed and compiled the appropriate libraries/binaries that uses them without any issues at this time.
Installation was done via cmake version 3.16.3 latest stable with vcpkg.

**Comment by JonLiu1993** [comment]
`Cuda` does not need to be upgraded for the time being. This issue has been closed for several years. If you have other problems, we can reopen it.
````
The cudnn and other packages using cuda all have installed and compiled the appropriate libraries/binaries that uses them without any issues at this time.
````
