### ISSUE TITLE
vcpkg install errors

### ISSUE THREAD

**Issue by khalilia2000** [Microsoft/vcpkg#981]
Hi, 
I get the following error trying to build vcpkg on Windows 10 (i.e. running bootstrap-vcpkg.bat). The full log is attached.
[log.txt](https://github.com/Microsoft/vcpkg/files/957376/log.txt)

Any help would be appreciated.
Many thanks.

`
Microsoft (R) Build Engine version 14.0.23107.0
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 4/25/2017 10:36:59 PM.
     1>Project "C:\Udacity-Courses\Car-ND-Udacity\vcpkg\toolsrc\dirs.proj" on node 1 (default targets).
     1>Project "C:\Udacity-Courses\Car-ND-Udacity\vcpkg\toolsrc\dirs.proj" (1) is building "C:\Udacity-Courses\Car-ND-Udacity\vcpkg\toolsrc\vcpkg\vcpkg.vcxproj" (2) on node 1 (Clean target(s)).
     2>Project "C:\Udacity-Courses\Car-ND-Udacity\vcpkg\toolsrc\vcpkg\vcpkg.vcxproj" (2) is building "C:\Udacity-Courses\Car-ND-Udacity\vcpkg\toolsrc\vcpkglib\vcpkglib.vcxproj" (3) on node 1 (Clean target(s)).
     3>_PrepareForClean:
         Deleting file "Release\vcpkglib.tlog\vcpkglib.lastbuildstate".
     3>Done Building Project "C:\Udacity-Courses\Car-ND-Udacity\vcpkg\toolsrc\vcpkglib\vcpkglib.vcxproj" (Clean target(s)).
     2>Done Building Project "C:\Udacity-Courses\Car-ND-Udacity\vcpkg\toolsrc\vcpkg\vcpkg.vcxproj" (Clean target(s)).
     1>Project "C:\Udacity-Courses\Car-ND-Udacity\vcpkg\toolsrc\dirs.proj" (1) is building "C:\Udacity-Courses\Car-ND-Udacity\vcpkg\toolsrc\vcpkg\vcpkg.vcxproj" (2:2) on node 1 (Build target(s)).
   2:2>Project "C:\Udacity-Courses\Car-ND-Udacity\vcpkg\toolsrc\vcpkg\vcpkg.vcxproj" (2:2) is building "C:\Udacity-Courses\Car-ND-Udacity\vcpkg\toolsrc\vcpkglib\vcpkglib.vcxproj" (3:4) on node 1 (default targets).
     3>InitializeBuildStatus:
         Touching "Release\vcpkglib.tlog\unsuccessfulbuild".
       ClCompile:
         C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\CL.exe /c /I..\include /Zi /nologo /W3 /WX- /sdl /MP /O2 /Oi /Oy- /GL /D DISABLE_METRICS=0 /D "VCPKG_VERSION=-ff639ecc0291bd4a27aacfb4c56b49712cfd16e6" /D _MBCS /D NDEBUG /D _MBCS /Gm- /EHsc /MD /GS /Gy /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Yc"pch.h" /Fp"Release\vcpkglib.pch" /Fo"Release\\" /Fd"Release\vcpkglib.pdb" /Gd /TP /analyze- /errorReport:queue /std:c++latest ..\src\pch.cpp
     3>cl : Command line warning D9002: ignoring unknown option '/std:c++latest' [C:\Udacity-Courses\Car-ND-Udacity\vcpkg\toolsrc\vcpkglib\vcpkglib.vcxproj]
         pch.cpp
         C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\CL.exe /c /I..\include /Zi /nologo /W3 /WX- /sdl /MP /O2 /Oi /Oy- /GL /D DISABLE_METRICS=0 /D "VCPKG_VERSION=-ff639ecc0291bd4a27aacfb4c56b49712cfd16e6" /D _MBCS /D NDEBUG /D _MBCS /Gm- /EHsc /MD /GS /Gy /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Yu"pch.h" /Fp"Release\vcpkglib.pch" /Fo"Release\\" /Fd"Release\vcpkglib.pdb" /Gd /TP /analyze- /errorReport:queue /std:c++latest ..\include\VersionT.cpp ..\src\BinaryParagraph.cpp ..\src\commands_ci.cpp ..\src\commands_depends.cpp ..\src\commands_env.cpp ..\src\commands_export.cpp ..\src\LineInfo.cpp ..\src\ParagraphParseResult.cpp ..\src\PostBuildLint_BuildInfo.cpp ..\src\PostBuildLint_BuildPolicies.cpp ..\src\coff_file_reader.cpp ..\src\commands_available_commands.cpp ..\src\commands_build.cpp ..\src\commands_build_external.cpp ..\src\commands_cache.cpp ..\src\commands_contact.cpp ..\src\commands_create.cpp ..\src\commands_edit.cpp ..\src\commands_hash.cpp ..\src\commands_help.cpp ..\src\commands_import.cpp ..\src\commands_install.cpp ..\src\commands_integrate.cpp ..\src\commands_list.cpp ..\src\commands_owns.cpp ..\src\commands_portsdiff.cpp ..\src\commands_remove.cpp ..\src\commands_search.cpp ..\src\commands_update.cpp ..\src\commands_version.cpp ..\src\MachineType.cpp ..\src\metrics.cpp ..\src\OptBool.cpp ..\src\PostBuildLint.cpp ..\src\PostBuildLint_ConfigurationType.cpp ..\src\PostBuildLint_LinkageType.cpp ..\src\PostBuildLint_BuildType.cpp ..\src\vcpkg_Chrono.cpp ..\src\vcpkglib.cpp ..\src\PackageSpec.cpp ..\src\PackageSpecParseResult.cpp ..\src\Paragraphs.cpp ..\src\SourceParagraph.cpp ..\src\StatusParagraph.cpp ..\src\StatusParagraphs.cpp ..\src\triplet.cpp ..\src\vcpkglib_helpers.cpp ..\src\vcpkg_Checks.cpp ..\src\VcpkgCmdArguments.cpp ..\src\vcpkg_Dependencies.cpp ..\src\vcpkg_Enums.cpp ..\src\vcpkg_Files.cpp ..\src\vcpkg_Input.cpp ..\src\VcpkgPaths.cpp ..\src\vcpkg_Strings.cpp ..\src\vcpkg_System.cpp
     3>cl : Command line warning D9002: ignoring unknown option '/std:c++latest' [C:\Udacity-Courses\Car-ND-Udacity\vcpkg\toolsrc\vcpkglib\vcpkglib.vcxproj]
     3>cl : Command line warning D9002: ignoring unknown option '/std:c++latest' [C:\Udacity-Courses\Car-ND-Udacity\vcpkg\toolsrc\vcpkglib\vcpkglib.vcxproj]
     3>cl : Command line warning D9002: ignoring unknown option '/std:c++latest' [C:\Udacity-Courses\Car-ND-Udacity\vcpkg\toolsrc\vcpkglib\vcpkglib.vcxproj]
     3>cl : Command line warning D9002: ignoring unknown option '/std:c++latest' [C:\Udacity-Courses\Car-ND-Udacity\vcpkg\toolsrc\vcpkglib\vcpkglib.vcxproj]
     3>cl : Command line warning D9002: ignoring unknown option '/std:c++latest' [C:\Udacity-Courses\Car-ND-Udacity\vcpkg\toolsrc\vcpkglib\vcpkglib.vcxproj]
     3>cl : Command line warning D9002: ignoring unknown option '/std:c++latest' [C:\Udacity-Courses\Car-ND-Udacity\vcpkg\toolsrc\vcpkglib\vcpkglib.vcxproj]
     3>cl : Command line warning D9002: ignoring unknown option '/std:c++latest' [C:\Udacity-Courses\Car-ND-Udacity\vcpkg\toolsrc\vcpkglib\vcpkglib.vcxproj]
         VersionT.cpp
         BinaryParagraph.cpp
         commands_ci.cpp
         commands_depends.cpp
     3>cl : Command line warning D9002: ignoring unknown option '/std:c++latest' [C:\Udacity-Courses\Car-ND-Udacity\vcpkg\toolsrc\vcpkglib\vcpkglib.vcxproj]
     3>cl : Command line warning D9002: ignoring unknown option '/std:c++latest' [C:\Udacity-Courses\Car-ND-Udacity\vcpkg\toolsrc\vcpkglib\vcpkglib.vcxproj]
         commands_env.cpp
         commands_export.cpp
         LineInfo.cpp
         ParagraphParseResult.cpp
     3>c:\udacity-courses\car-nd-udacity\vcpkg\toolsrc\include\OptBool.h(6): error C2653: 'vcpkg': is not a class or namespace name (compiling source file ..\src\commands_ci.cpp) [C:\Udacity-Courses\Car-ND-Udacity\vcpkg\toolsrc\vcpkglib\vcpkglib.vcxproj]
     3>c:\udacity-courses\car-nd-udacity\vcpkg\toolsrc\include\OptBool.h(6): error C2653: 'vcpkg': is not a class or namespace name (compiling source file ..\src\commands_depends.cpp) [C:\Udacity-Courses\Car-ND-Udacity\vcpkg\toolsrc\vcpkglib\vcpkglib.vcxproj]
     3>c:\udacity-courses\car-nd-udacity\vcpkg\toolsrc\include\OptBool.h(6): error C2653: 'vcpkg': is not a class or namespace name (compiling source file ..\src\commands_env.cpp) [C:\Udacity-Courses\Car-ND-Udacity\vcpkg\toolsrc\vcpkglib\vcpkglib.vcxproj]
     3>c:\udacity-courses\car-nd-udacity\vcpkg\toolsrc\include\OptBool.h(6): error C2653: 'vcpkg': is not a class or namespace name (compiling source file ..\src\commands_export.cpp) [C:\Udacity-Courses\Car-ND-Udacity\vcpkg\toolsrc\vcpkglib\vcpkglib.vcxproj]
     3>c:\udacity-courses\car-nd-udacity\vcpkg\toolsrc\include\vcpkg_Strings.h(6): error C3083: 'Strings': the symbol to the left of a '::' must be a type (compiling source file ..\src\ParagraphParseResult.cpp) [C:\Udacity-Courses\Car-ND-Udacity\vcpkg\toolsrc\vcpkglib\vcpkglib.vcxproj]
     3>c:\udacity-courses\car-nd-udacity\vcpkg\toolsrc\include\vcpkg_Strings.h(6): error C3083: 'Strings': 
`

**Comment by ras0219-msft** [comment]
> cl : Command line warning D9002: ignoring unknown option '/std:c++latest' 

Hi @khalilia2000! Could you confirm that you have VS2015 Update 3? We use some C++ language features that were only released in the last version of VS2015.

https://blogs.msdn.microsoft.com/vcblog/2016/06/07/standards-version-switches-in-the-compiler/

**Comment by khalilia2000** [comment]
Hi @ras0219, Many thanks. you were right, when upgraded to Update 3, the problem got resolved.
