### ISSUE TITLE
[openal-soft] find_package(openal-soft CONFIG REQUIRED) fails

### ISSUE THREAD

**Issue by capnkenny** [microsoft/vcpkg#9811]
**Describe the bug**
When attempting to include OpenAL-Soft after being installed successfully via vcpkg, the resulting `find_package` line provided by vcpkg causes configuration of a project to fail as it cannot locate the configuration CMake files that were generated.

**Environment**
- OS: Ubuntu 19.10 x64 / Windows 10 1903 x64 
- Compiler: GNU 9.2.1 / Microsoft (R) C/C++ Optimizing Compiler Version 19.16.27034 for x64
- CMake Version: 3.16.3 / 3.16.0

**To Reproduce**
Steps to reproduce the behavior [Ubuntu]:
1. ./vcpkg install openal-soft
2. Add the `find_package` and `target_link_libraries` lines specified by vcpkg to a CMakeLists.txt
3. Attempt to configure the project via CMake using the CMakeLists.txt from above.

**Expected behavior**
Once OpenAL-Soft is installed via vcpkg, it should specify the correct name required to find the package, and allow a project utilizing it to configure sucessfully.

**Failure logs** 
```
-- The C compiler identification is GNU 9.2.1
-- The CXX compiler identification is GNU 9.2.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Freetype: /home/kennuckles/vcpkg/installed/x64-linux/lib/libfreetype.a (found version "2.10.1") 
-- Found ZLIB: /home/kennuckles/vcpkg/installed/x64-linux/debug/lib/libz.a (found version "1.2.11") 
-- Found PNG: /home/kennuckles/vcpkg/installed/x64-linux/debug/lib/libpng.a (found version "1.6.37") 
-- Found BZip2: /home/kennuckles/vcpkg/installed/x64-linux/lib/libbz2.a (found version "1.0.6") 
-- Looking for BZ2_bzCompressInit
-- Looking for BZ2_bzCompressInit - found
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
CMake Error at /home/kennuckles/vcpkg/scripts/buildsystems/vcpkg.cmake:285 (_find_package):
  Could not find a package configuration file provided by "openal-soft" with
  any of the following names:

    openal-softConfig.cmake
    openal-soft-config.cmake

  Add the installation prefix of "openal-soft" to CMAKE_PREFIX_PATH or set
  "openal-soft_DIR" to a directory containing one of the above files.  If
  "openal-soft" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  src/CMakeLists.txt:8 (find_package)


-- Configuring incomplete, errors occurred!
```

**Additional context**
Based on the error messaging, it appears that after being installed by vcpkg the configuration files are created as `OpenALConfig.cmake`, `OpenALConfig-debug.cmake`, and `OpenALConfig-release.cmake`. Once the `find_package` line is changed to use the name `OpenAL` instead of `openal-soft`, configuration completes as expected. This occurs on both Ubuntu and Windows 10.

**Comment by LilyWangL** [comment]
Thanks for posting this issue. This issue has been fixed, so I am closing this issue for now.
