### ISSUE TITLE
How do I select which version of OpenGL to install on my Windows 10 system?

### ISSUE THREAD

**Issue by thatrobotguy** [microsoft/vcpkg#9813]
I am trying to run OpenGL programs but I see that the stock OpenGL version when you run `./vcpkg.exe install opengl` is version `3.2`. That version is considerably older than I need for my software. Is there a way to specify a newer version, like `4.6`? I have been looking [here](https://github.com/microsoft/vcpkg/blob/master/ports/opengl/usage) but I cannot find where to install other versions. How do you install a newer version? If you cannot install a newer version (at this time), what would it take to make a newer version available?
Thanks

**Comment by vicroms** [comment]
The port uses the OpenGL version that comes with the Windows SDK, for Windows SDK 10 that would be 3.2. Unfortunately, there's no way to install a different version with vcpkg.

**Comment by 1m188** [comment]
eh.. by the way, i want to ask that does the "there's no way to install a different version with vcpkg" means vcpkg can not install other version sdk for opengl, or vcpkg can not chose version for all package it searched? i am finding a way to install different version package by using vcpkg.

**Comment by 1m188** [comment]
> The port uses the OpenGL version that comes with the Windows SDK, for Windows SDK 10 that would be 3.2. Unfortunately, there's no way to install a different version with vcpkg.

eh.. by the way, i want to ask that does the "there's no way to install a different version with vcpkg" means vcpkg can not install other version sdk for opengl, or vcpkg can not chose version for all package it searched? i am finding a way to install different version package by using vcpkg.

**Comment by vicroms** [comment]
**OpenGL** is a special case.

## On Windows
The portfile itself does not install **OpenGL**, instead it searches for the **OpenGL** that comes with your installed **Windows SDK** and copies the library files into the `<vcpkg root>/installed` folder.

You can refer to the [**OpenGL** portfile](https://github.com/microsoft/vcpkg/blob/master/ports/opengl/portfile.cmake) to learn more about how this works.


https://github.com/microsoft/vcpkg/blob/b5b21df60a76c064b3a2e383ace56d47300e2b63/ports/opengl/portfile.cmake#L4-L17

## On other platforms
The portfile does nothing. Instead it asks you to use other means to install **OpenGL**.

https://github.com/microsoft/vcpkg/blob/b5b21df60a76c064b3a2e383ace56d47300e2b63/ports/opengl/usage#L20-L24

**Comment by thatrobotguy** [comment]
Is there a way to make `vcpkg` look elsewhere for OpenGL? In know my specific machine _can_ run more modern OpenGL programs. I downloaded one and it worked just fine with a version `4.X.X`. Maybe there is a path variable that can be changed? Or the OpenGL package (Cmake?) itself?
