### ISSUE TITLE
grpc:x64-windows: tons of warnings on the include

### ISSUE THREAD

**Issue by Horoprime** [microsoft/vcpkg#9814]
While trying to link GRPC libs to my own StaticLib I get a lot of linker warnings. 
My lib can be built, but when I link it to Console App, it fails.

- Win 10 x64
- Build configuration: Release x64
- VS 2019 v142 

**To Reproduce**
1. Install grpc x64-windows
2. Link it to your static lib via VS 2019

[ConsoleApp.Log](https://github.com/microsoft/vcpkg/files/4109403/ConsoleApp.Log)
[MyLib.Log](https://github.com/microsoft/vcpkg/files/4109404/MyLib.Log)
[Lib_vcxproj.txt](https://github.com/microsoft/vcpkg/files/4109434/Lib_vcxproj.txt)

**Comment by PhoebeHui** [comment]
@Horoprime, could you provide us the repro code and repro steps?

**Comment by PhoebeHui** [comment]
@Horoprime, please reopen this issue with repro code and repro steps if it still be an issue for you.
