### ISSUE TITLE
libcurl build failure

### ISSUE THREAD

**Issue by danieljo12** [microsoft/vcpkg#9815]
**Host Environment**
- OS: windows 10
- Compiler: vs19 

**To Reproduce**
`vcpkg install curl[*]:x64-windows`

**Failure logs** 

Your feedback is important to improve Vcpkg! Please take 3 minutes to complete our survey by running: vcpkg contact --survey
The following packages will be built and installed:
  * c-ares[core]:x64-windows
    curl[brotli,c-ares,core,http2,mbedtls,non-http,openssl,sectransp,ssh,ssl,sspi,tool,winssl]:x64-windows
  * libssh2[core]:x64-windows
  * mbedtls[core]:x64-windows
  * nghttp2[core]:x64-windows
  * openssl[core]:x64-windows
  * openssl-windows[core]:x64-windows
  * zlib[core]:x64-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/8: mbedtls:x64-windows
Building package mbedtls[core]:x64-windows...
-- Using cached C:/Users/danie/vcpkg/downloads/ARMmbed-mbedtls-mbedtls-2.16.3.tar.gz
-- Using source at C:/Users/danie/vcpkg/buildtrees/mbedtls/src/tls-2.16.3-6ae2246379
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: C:/Users/danie/vcpkg/downloads/tools/cmake-3.14.0-windows/cmake-3.14.0-win32-x86/bin/cmake.exe --build . --config Debug --target install -- -v
    Working Directory: C:/Users/danie/vcpkg/buildtrees/mbedtls/x64-windows-dbg
    See logs for more information:
      C:\Users\danie\vcpkg\buildtrees\mbedtls\install-x64-windows-dbg-out.log
      C:\Users\danie\vcpkg\buildtrees\mbedtls\install-x64-windows-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:91 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/mbedtls/portfile.cmake:21 (vcpkg_install_cmake)
  scripts/ports.cmake:94 (include)

Error: Building package mbedtls:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: mbedtls:x64-windows
  Vcpkg version: 2020.01.17-nohash

**Additional context**
none

**Comment by Neumann-A** [comment]
Without looking into the details:
`curl[brotli,c-ares,core,http2,mbedtls,non-http,openssl,sectransp,ssh,ssl,sspi,tool,winssl]:x64-windows`
probably has conflicting features.

**Comment by PhoebeHui** [comment]
@danieljo12, sectransp is not supported on non-Apple platforms, and the failure message has been added to curl.

Other features test pass, please get latest source and try again.

PS F:\vcpkg\boost_173\vcpkg> ./vcpkg install curl[brotli,c-ares,core,http2,mbedtls,non-http,openssl,ssh,ssl,sspi,tool,winssl]:x64-windows
Computing installation plan...
The following packages will be built and installed:
    curl[brotli,c-ares,core,http2,mbedtls,non-http,openssl,ssh,ssl,sspi,tool,winssl]:x64-windows
Detecting compiler hash for triplet x64-windows...
Starting package 1/1: curl:x64-windows
Building package curl[brotli,c-ares,core,http2,mbedtls,non-http,openssl,ssh,ssl,sspi,tool,winssl]:x64-windows...
-- Using cached F:/vcpkg/boost_173/vcpkg/downloads/curl-curl-5a1fc8d33808d7b22f57bdf9403cda7ff07b0670.tar.gz
-- Cleaning sources at F:/vcpkg/boost_173/vcpkg/buildtrees/curl/src/7ff07b0670-12eb9d7696.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source F:/vcpkg/boost_173/vcpkg/downloads/curl-curl-5a1fc8d33808d7b22f57bdf9403cda7ff07b0670.tar.gz
-- Applying patch 0002_fix_uwp.patch
-- Applying patch 0004_nghttp2_staticlib.patch
-- Applying patch 0005_remove_imp_suffix.patch
-- Applying patch 0006_fix_tool_depends.patch
-- Applying patch 0007_disable_tool_export_curl_target.patch
-- Applying patch 0008_fix_tools_path.patch
-- Applying patch 0009_fix_openssl_config.patch
-- Applying patch 0010_fix_othertests_cmake.patch
-- Using source at F:/vcpkg/boost_173/vcpkg/buildtrees/curl/src/7ff07b0670-12eb9d7696.clean
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Installing: F:/vcpkg/boost_173/vcpkg/packages/curl_x64-windows/share/curl/curl-config
-- Installing: F:/vcpkg/boost_173/vcpkg/packages/curl_x64-windows/share/curl/vcpkg-cmake-wrapper.cmake
-- Installing: F:/vcpkg/boost_173/vcpkg/packages/curl_x64-windows/share/curl/copyright
-- Performing post-build validation
-- Performing post-build validation done

Building package curl[brotli,c-ares,core,http2,mbedtls,non-http,openssl,ssh,ssl,sspi,tool,winssl]:x64-windows... done
Installing package curl[brotli,c-ares,core,http2,mbedtls,non-http,openssl,ssh,ssl,sspi,tool,winssl]:x64-windows...
Installing package curl[brotli,c-ares,core,http2,mbedtls,non-http,openssl,ssh,ssl,sspi,tool,winssl]:x64-windows... done
Elapsed time for package curl:x64-windows: 2.145 min

Total elapsed time: 2.197 min

The package curl:x64-windows provides CMake targets:

    find_package(CURL CONFIG REQUIRED)
    target_link_libraries(main PRIVATE CURL::libcurl)

**Comment by PhoebeHui** [comment]
Please reopen this issue and attach failure log if it still be a problem for you.
