### ISSUE TITLE
zlib:x86-windows build failure

### ISSUE THREAD

**Issue by danieljo12** [microsoft/vcpkg#9817]
**Host Environment**
- OS: Windows
- Compiler: visual studio 2019

**To Reproduce**
vcpkg.exe install curl

**Failure logs** 

The following packages will be built and installed:
    curl[core,ssl,winssl]:x86-windows
  * zlib[core]:x86-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/2: zlib:x86-windows
Building package zlib[core]:x86-windows...
-- Using cached C:/Users/danie/vcpkg-2019.12/downloads/zlib1211.tar.gz
-- Using source at C:/Users/danie/vcpkg-2019.12/buildtrees/zlib/src/1.2.11-f690224aeb
-- Configuring x86-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: ninja -v
    Working Directory: C:/Users/danie/vcpkg-2019.12/buildtrees/zlib/x86-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\Users\danie\vcpkg-2019.12\buildtrees\zlib\config-x86-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:293 (vcpkg_execute_required_process)
  ports/zlib/portfile.cmake:22 (vcpkg_configure_cmake)
  scripts/ports.cmake:94 (include)

Error: Building package zlib:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: zlib:x86-windows
  Vcpkg version: 2019.09.12-nohash

**Additional context**

**Comment by cenit** [comment]
--> "See logs for more information:
C:\Users\danie\vcpkg-2019.12\buildtrees\zlib\config-x86-windows-out.log"

**Comment by danieljo12** [comment]
@cenit 
[1/2] cmd /c "cd ../../x86-windows-dbg && "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/bin/cmake.exe" "C:/Users/danie/vcpkg-2019.12/buildtrees/zlib/src/1.2.11-f690224aeb" "-DSKIP_INSTALL_FILES=ON" "-DSKIP_BUILD_EXAMPLES=ON" "-DCMAKE_MAKE_PROGRAM=C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=C:/Users/danie/vcpkg-2019.12/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x86-windows" "-DVCPKG_SET_CHARSET_FLAG=ON" "-DVCPKG_PLATFORM_TOOLSET=v142" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=C:/Users/danie/vcpkg-2019.12/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DVCPKG_TARGET_ARCHITECTURE=x86" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-DSKIP_INSTALL_HEADERS=ON" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Debug" "-DCMAKE_INSTALL_PREFIX=C:/Users/danie/vcpkg-2019.12/packages/zlib_x86-windows/debug""
FAILED: ../../x86-windows-dbg/CMakeCache.txt 
cmd /c "cd ../../x86-windows-dbg && "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/bin/cmake.exe" "C:/Users/danie/vcpkg-2019.12/buildtrees/zlib/src/1.2.11-f690224aeb" "-DSKIP_INSTALL_FILES=ON" "-DSKIP_BUILD_EXAMPLES=ON" "-DCMAKE_MAKE_PROGRAM=C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=C:/Users/danie/vcpkg-2019.12/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x86-windows" "-DVCPKG_SET_CHARSET_FLAG=ON" "-DVCPKG_PLATFORM_TOOLSET=v142" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=C:/Users/danie/vcpkg-2019.12/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DVCPKG_TARGET_ARCHITECTURE=x86" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-DSKIP_INSTALL_HEADERS=ON" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Debug" "-DCMAKE_INSTALL_PREFIX=C:/Users/danie/vcpkg-2019.12/packages/zlib_x86-windows/debug""
CMake Warning at C:/Users/danie/vcpkg-2019.12/scripts/buildsystems/vcpkg.cmake:104 (message):
  There are no libraries installed for the Vcpkg triplet x86-windows.
Call Stack (most recent call first):
  C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.15/Modules/CMakeDetermineSystem.cmake:93 (include)
  CMakeLists.txt:4 (project)


-- The C compiler identification is MSVC 19.24.28315.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.24.28314/bin/Hostx64/x86/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.24.28314/bin/Hostx64/x86/cl.exe -- broken
CMake Error at C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.15/Modules/CMakeTestCCompiler.cmake:60 (message):
  The C compiler

    "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.24.28314/bin/Hostx64/x86/cl.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: C:/Users/danie/vcpkg-2019.12/buildtrees/zlib/x86-windows-dbg/CMakeFiles/CMakeTmp
    
    Run Build Command(s):C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe cmTC_9fff6 && [1/2] Building C object CMakeFiles\cmTC_9fff6.dir\testCCompiler.c.obj
    [2/2] Linking C executable cmTC_9fff6.exe
    FAILED: cmTC_9fff6.exe 
    cmd.exe /C "cd . && "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -E vs_link_exe --intdir=CMakeFiles\cmTC_9fff6.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100183~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100183~1.0\x64\mt.exe --manifests  -- C:\PROGRA~2\MICROS~1\2019\COMMUN~1\VC\Tools\MSVC\1424~1.283\bin\Hostx64\x86\link.exe /nologo CMakeFiles\cmTC_9fff6.dir\testCCompiler.c.obj  /out:cmTC_9fff6.exe /implib:cmTC_9fff6.lib /pdb:cmTC_9fff6.pdb /version:0.0  /machine:X86  /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
    FINAL LINK: command "C:\PROGRA~2\MICROS~1\2019\COMMUN~1\VC\Tools\MSVC\1424~1.283\bin\Hostx64\x86\link.exe /nologo CMakeFiles\cmTC_9fff6.dir\testCCompiler.c.obj /out:cmTC_9fff6.exe /implib:cmTC_9fff6.lib /pdb:cmTC_9fff6.pdb /version:0.0 /machine:X86 /debug /INCREMENTAL /subsystem:console kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\cmTC_9fff6.dir/intermediate.manifest CMakeFiles\cmTC_9fff6.dir/manifest.res" failed (exit code 1158) with the following output:
    LINK : fatal error LNK1158: cannot run 'C:\PROGRA~2\MICROS~1\2019\COMMUN~1\VC\Tools\MSVC\1424~1.283\bin\Hostx64\x86\cvtres.exe'
    ninja: build stopped: subcommand failed.
    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:4 (project)


-- Configuring incomplete, errors occurred!
See also "C:/Users/danie/vcpkg-2019.12/buildtrees/zlib/x86-windows-dbg/CMakeFiles/CMakeOutput.log".
See also "C:/Users/danie/vcpkg-2019.12/buildtrees/zlib/x86-windows-dbg/CMakeFiles/CMakeError.log".
[2/2] cmd /c "cd .. && "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/bin/cmake.exe" "C:/Users/danie/vcpkg-2019.12/buildtrees/zlib/src/1.2.11-f690224aeb" "-DSKIP_INSTALL_FILES=ON" "-DSKIP_BUILD_EXAMPLES=ON" "-DCMAKE_MAKE_PROGRAM=C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=C:/Users/danie/vcpkg-2019.12/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x86-windows" "-DVCPKG_SET_CHARSET_FLAG=ON" "-DVCPKG_PLATFORM_TOOLSET=v142" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=C:/Users/danie/vcpkg-2019.12/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DVCPKG_TARGET_ARCHITECTURE=x86" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Release" "-DCMAKE_INSTALL_PREFIX=C:/Users/danie/vcpkg-2019.12/packages/zlib_x86-windows""
FAILED: ../CMakeCache.txt 
cmd /c "cd .. && "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/bin/cmake.exe" "C:/Users/danie/vcpkg-2019.12/buildtrees/zlib/src/1.2.11-f690224aeb" "-DSKIP_INSTALL_FILES=ON" "-DSKIP_BUILD_EXAMPLES=ON" "-DCMAKE_MAKE_PROGRAM=C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=C:/Users/danie/vcpkg-2019.12/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x86-windows" "-DVCPKG_SET_CHARSET_FLAG=ON" "-DVCPKG_PLATFORM_TOOLSET=v142" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=C:/Users/danie/vcpkg-2019.12/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DVCPKG_TARGET_ARCHITECTURE=x86" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Release" "-DCMAKE_INSTALL_PREFIX=C:/Users/danie/vcpkg-2019.12/packages/zlib_x86-windows""
CMake Warning at C:/Users/danie/vcpkg-2019.12/scripts/buildsystems/vcpkg.cmake:104 (message):
  There are no libraries installed for the Vcpkg triplet x86-windows.
Call Stack (most recent call first):
  C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.15/Modules/CMakeDetermineSystem.cmake:93 (include)
  CMakeLists.txt:4 (project)


-- The C compiler identification is MSVC 19.24.28315.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.24.28314/bin/Hostx64/x86/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.24.28314/bin/Hostx64/x86/cl.exe -- works
-- Detecting C compiler ABI info
CMake Error at C:/Users/danie/vcpkg-2019.12/buildtrees/zlib/x86-windows-rel/CMakeFiles/CMakeTmp/CMakeLists.txt:3 (project):
  Running

   'C:/PROGRA~2/MICROS~1/2019/COMMUN~1/Common7/IDE/COMMON~1/MICROS~1/CMake/Ninja/ninja.exe' '--version'

  failed with:

   Access is denied


CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error at C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.15/Modules/CMakeDetermineCompilerABI.cmake:45 (try_compile):
  Failed to configure test project build system.
Call Stack (most recent call first):
  C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.15/Modules/CMakeTestCCompiler.cmake:74 (CMAKE_DETERMINE_COMPILER_ABI)
  CMakeLists.txt:4 (project)


-- Configuring incomplete, errors occurred!
See also "C:/Users/danie/vcpkg-2019.12/buildtrees/zlib/x86-windows-rel/CMakeFiles/CMakeOutput.log".
ninja: build stopped: subcommand failed.

**Comment by cenit** [comment]
do you have the C++ workload installed for Visual Studio?

**Comment by danieljo12** [comment]
@cenit  how do i check?

**Comment by cenit** [comment]
Rerun the installer (in Start Menu, look for "Visual Studio Installer") and then follow the guide at
https://docs.microsoft.com/en-us/cpp/build/vscpp-step-0-installation?view=vs-2019

**Comment by danieljo12** [comment]
yh i do have it installed...

**Comment by soapdog** [comment]
Failing here as well on a Surface Pro X with VS2019 and the C++ workload installed.

**Comment by NancyLi1013** [comment]
@danieljo12 thanks for posting this issue.
Could you please update vcpkg to the latest version and rebuild this?

@soapdog could you please provide your failure log about this?

**Comment by NancyLi1013** [comment]
@danieljo12 

Please help confirm if you have access to `C:/PROGRA2/MICROS1/2019/COMMUN1/Common7/IDE/COMMON1/MICROS~1/CMake/Ninja/ninja.exe`.

```
CMake Error at C:/Users/danie/vcpkg-2019.12/buildtrees/zlib/x86-windows-rel/CMakeFiles/CMakeTmp/CMakeLists.txt:3 (project):
Running

'C:/PROGRA2/MICROS1/2019/COMMUN1/Common7/IDE/COMMON1/MICROS~1/CMake/Ninja/ninja.exe' '--version'

failed with:

Access is denied

CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error at C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.15/Modules/CMakeDetermineCompilerABI.cmake:45 (try_compile):
Failed to configure test project build system.
```

**Comment by danieljo12** [comment]
Ive updated vcpkg and ive tried installing curl using "vcpkg.exe install curl" and it still returns with BUILD_FAILED error

**Comment by danieljo12** [comment]
Also yes i have ninja.exe
located:
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja

**Comment by NancyLi1013** [comment]
@danieljo12 
Could you try to clone vcpkg to another directory that is not in `c:\` and  build it agian?

**Comment by NancyLi1013** [comment]
```
Studio/2019/Community/VC/Tools/MSVC/14.24.28314/bin/Hostx64/x86/cl.exe -- broken
CMake Error at C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.15/Modules/CMakeTestCCompiler.cmake:60 (message):
The C compiler

"C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.24.28314/bin/Hostx64/x86/cl.exe"
is not able to compile a simple test program.
```

`LINK : fatal error LNK1158: cannot run 'C:\PROGRA~2\MICROS~1\2019\COMMUN~1\VC\Tools\MSVC\1424~1.283\bin\Hostx64\x86\cvtres.exe'`

It seems that the path is weird. Please check the permission again. And also try to reinstall Visual Studio and build this again.

I'm closing this issue for now since not reproduce and no response for a long time.
Please feel free to reopen this issue if it is still a problem for you.

**Comment by cenit** [comment]
>` LINK : fatal error LNK1158: cannot run 'C:\PROGRA~2\MICROS~1\2019\COMMUN~1\VC\Tools\MSVC\1424~1.283\bin\Hostx64\x86\cvtres.exe'`
It seems that the path is weird. Please check the permission again. And also try to reinstall Visual Studio and build this again.

Path was not weird at all. I just realized from @soapdog, are you @danieljo12 also using a Surface Pro X? In that case, the problem is that you are using the  x64 toolchain (`Hostx64\x86`) to crosscompile your x86 binary, which unfortunately does not run on Windows for ARM64... You have to select the x86 toolchain (`Hostx86\x86`)!

**Comment by danieljo12** [comment]
> >` LINK : fatal error LNK1158: cannot run 'C:\PROGRA~2\MICROS~1\2019\COMMUN~1\VC\Tools\MSVC\1424~1.283\bin\Hostx64\x86\cvtres.exe'`
> It seems that the path is weird. Please check the permission again. And also try to reinstall Visual Studio and build this again.
> 
> Path was not weird at all. I just realized from @soapdog, are you @danieljo12 also using a Surface Pro X? In that case, the problem is that you are using the  x64 toolchain (`Hostx64\x86`) to crosscompile your x86 binary, which unfortunately does not run on Windows for ARM64... You have to select the x86 toolchain (`Hostx86\x86`)!

I wasnt using a surface pro

**Comment by cenit** [comment]
Were you using an arm64 device, or a 32bit OS?

**Comment by danieljo12** [comment]
> Were you using an arm64 device, or a 32bit OS?My system runs windows 10 64bit x64

**Comment by gino0717** [comment]
It is so sad that if you google "zlib:x86-windows build failure" you can see a list of same issue in vcpkg github for years.
It seems that the problem has never been really solved but just be closed again and again.

**Comment by danieljo12** [comment]
yeah it does suck.. im sorry that i couldnt test this again, i just havent got round to it yet

**Comment by linquize** [comment]
Could you update your VS2019 to latest version and test? cmake is now 3.17

**Comment by NancyLi1013** [comment]
@danieljo12 

Have you tried with the latest VS2019 and vcpkg?

**Comment by danieljo12** [comment]
Sorry i have had personal stuff going on... and i dont have a proper computer anymore so i cant really do much,,

**Comment by NancyLi1013** [comment]
Thanks for your feedback @danieljo12. Please feel free to reopen this if it is still a problem for you in the future.

**Comment by sfhacker** [comment]
There are dozens of reports about zlib. Issues get never fixed properly. Closed issues are reopened after some time.
zlib is such a tiny and simple project. It takes nothing to build and install from source. Indeed embarrassing!
