### ISSUE TITLE
[rttr] build failure

### ISSUE THREAD

**Issue by jonathansty** [microsoft/vcpkg#9819]
**Host Environment**
- OS: Windows 10
- Compiler: whatever the bootstrap picks (I only have vs2019 installed.)

**To Reproduce**
./vcpkg install rttr:x64-windows

**Failure logs** 
The following packages will be built and installed:
    rttr[core]:x64-windows
Starting package 1/1: rttr:x64-windows
Building package rttr[core]:x64-windows...
-- Using cached F:/SDK/vcpkg/downloads/rttrorg-rttr-v0.9.6.tar.gz
-- Using source at F:/SDK/vcpkg/buildtrees/rttr/src/v0.9.6-9229bdee1f
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: ninja -v
    Working Directory: F:/SDK/vcpkg/buildtrees/rttr/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      F:\SDK\vcpkg\buildtrees\rttr\config-x64-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:295 (vcpkg_execute_required_process)
  ports/rttr/portfile.cmake:20 (vcpkg_configure_cmake)
  scripts/ports.cmake:94 (include)

Error: Building package rttr:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: rttr:x64-windows
  Vcpkg version: 2020.01.17-nohash

Additionally, attach any relevant sections from the log files above.
[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/4113459/config-x64-windows-out.log)

**Comment by jonathansty** [comment]
Just to give an update to this, after cleaning my entire vcpkg repo and bootstrapped again the issue no longer occurs.

**Comment by PhoebeHui** [comment]
@jonathansty, it seems the issue solved for you, I tried to repro this issue, however, it installed successfully for me, please reopen this issue if you see this issus again.

Starting package 2/2: rttr:x64-windows
Building package rttr[core]:x64-windows...
-- Downloading https://github.com/rttrorg/rttr/archive/v0.9.6.tar.gz...
-- Extracting source F:/vcpkg/downloads/rttrorg-rttr-v0.9.6.tar.gz
-- Applying patch fix-directory-output.patch
-- Applying patch Fix-depends.patch
-- Applying patch remove-owner-read-perms.patch
-- Using source at F:/vcpkg/buildtrees/rttr/src/v0.9.6-9229bdee1f
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Installing: F:/vcpkg/packages/rttr_x64-windows/share/rttr/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package rttr[core]:x64-windows... done
Installing package rttr[core]:x64-windows...
Installing package rttr[core]:x64-windows... done
Elapsed time for package rttr:x64-windows: 1.628 min

Total elapsed time: 2.461 min

The package rttr:x64-windows provides CMake targets:

    find_package(rttr CONFIG REQUIRED)
    target_link_libraries(main PRIVATE RTTR::Core)
