### ISSUE TITLE
adding cpp_redis to packages

### ISSUE THREAD

**Issue by sedapsfognik** [Microsoft/vcpkg#982]
First of all, thanks you for your job!
Your product is one of the best things ever happening to me :)

There are no libraries presented in vcpkg for working with redis.
The one I found the best is: https://github.com/Cylix/cpp_redis
Currently it successfully builds and works under windows through CMake.
I'll be very glad to see it here.

Thanks,
Pavel.

**Comment by sedapsfognik** [comment]
Hello, again!

I faced several problems while building cpp_redis under Windows. I pointed all of them here and proposed fixes as well. Hope, it'll help:

https://github.com/Cylix/cpp_redis/issues/71

**Comment by atkawa7** [comment]
@ras0219-msft Could you close this?

**Comment by sedapsfognik** [comment]
Hello, guys! Problem fixed. Thank you!
