### ISSUE TITLE
Using Angle With GLFW Results in "EGL: Library not found"

### ISSUE THREAD

**Issue by ruhrie** [microsoft/vcpkg#9822]
**Describe the bug**
Building a simple project with glfw and angle built from vcpkg fails to initialize an EGL context. The glfw error message is "EGL: Library not found". When I dug into the glfw source code it is trying to initialize the library through LoadLibraryA or dlopen depending on the platform. Recompiling glfw with an absolute path to libEGL.dll works and achieves expected behavior.

I'm pretty sure that we could also add the correct path to the search path at runtime to fix this, but I couldn't find an exposed variable to indicate where it is installed. Since this would need to be different for every instance, I'm pretty sure this isn't right. I didn't test this though.

**Environment**
- OS: Windows 10.0.19041
- Compiler: clang-9, cl 14.24.28314

**To Reproduce**
1. ./vcpkg install glfw3 angle
2. Compile and run the following simple program. Errors will be printed to console with glfw's error message. 

test.cpp:
```#define GLFW_INCLUDE_GLES3
#include <GLFW/glfw3.h>
#include <stdlib.h>
#include <string>
#include <iostream>
using namespace std;
void glfwErrorCallback(int a, const char *b)
{
    cout << string(b);
}
int main()
{
    GLFWwindow *window;
    if (!glfwInit())
        return 1;
    glfwSetErrorCallback(glfwErrorCallback);
    glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 3);
    glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 0);
    glfwWindowHint(GLFW_CLIENT_API, GLFW_OPENGL_ES_API);
    glfwWindowHint(GLFW_CONTEXT_CREATION_API, GLFW_EGL_CONTEXT_API);
    window = glfwCreateWindow(640, 480, "Simple example", NULL, NULL);
    if (!window)
    {
        glfwTerminate();
        return 1;
    }
    glfwDestroyWindow(window);
    glfwTerminate();
    return 0;
}
```

CMakeLists.txt:
```find_package(unofficial-angle CONFIG REQUIRED)
find_package(glfw3 CONFIG REQUIRED)
add_executable(test test.cpp)
target_link_libraries(test PRIVATE unofficial::angle::libEGL unofficial::angle::libGLESv2 glfw)
```

**Expected behavior**
The program should reach the end and return 0.

**Additional context**
glfw only supports changing these paths at compile time, so we need to either set the search path at runtime, copy the dll to a path it's already searching, or recompile glfw such that it also looks in the correct directory. 

Changing the search path could be done if we had the path to the vcpkg install dir available to cmake, but I can't find one when I enumerate all the variables in cmake or on allthedocs.

**Comment by NancyLi1013** [comment]
Hi @ruhrie 

Sorry for the late reply first.

I noticed that you only installed `angle`, but you didn't used it in this test case.
Since you built it on Windows platform with` Compiler: clang-9`, cl 14.24.28314, which is especial.
I can built it successfully with vs2017 15.9.21.

**Comment by ruhrie** [comment]
So I went ahead and tried to build against cl (19.24.28316) and I achieved the same result. My problem is not actually building the binary, but rather executing it. 

Glfw does not link against libegl at compile time, but instead opens the dll (or so) at runtime via a call to LoadLibraryA (or dlopen). Whether compiled with clang or cl, the resultant executable needs to be able to find the library. Since it has not been copied to the binary directory, glfw throws an error code which the program I wrote above will echo to standard out.

If you are curious the lines in glfw that are responsible are [287 of src/win32_platform.h](https://github.com/glfw/glfw/blob/44b5d06583cd21ac237eb8f6263db03faf1726c2/src/win32_platform.h#L287) to define the macro and [328 of src/egl_context.c](https://github.com/glfw/glfw/blob/44b5d06583cd21ac237eb8f6263db03faf1726c2/src/egl_context.c#L328) to call it. Both of these are in the build of glfw created by vcpkg.

To reiterate, my issue is when trying to use angle and glfw together due to how glfw loads the library. Right now I have to copy the dll manually to the build folder such that libegl can be found by my binary, but this seems like something vcpkg should handle. I could just be misreading your documentation though.

I have perused the issues in vcpkg looking for similar problems and of the open issues #9995, #9826, and #4311 seem to be similar. There may be others, but those were the simplest to find.

One final thing, when testing with cl for you I noticed that the CMakeLists doesn't behave the same within the visual studio command prompt. Below is an updated one that should cause less issues.
```cmake_minimum_required(VERSION 3.16)
project(angleTest)
find_package(glfw3 CONFIG REQUIRED)
find_package(unofficial-angle CONFIG REQUIRED)
add_executable(test test.cpp)
target_link_libraries(test PRIVATE unofficial::angle::libEGL unofficial::angle::libGLESv2 glfw)```

**Comment by ruhrie** [comment]
Another clarification, angle is there to provide the gles and egl contexts. The flags I gave to glfw specify that is needs to look for those libraries and make the appropriate calls. Although my program here doesn't explicitly use angle, glfw will create calls to it instead.

**Comment by ruhrie** [comment]
I also just noticed that I didn't mention that I installed glfw from vcpkg as well. My apologies.

**Comment by NancyLi1013** [comment]
@ruhrie 
Thanks for your update and these detail information. I will check it again.

**Comment by NancyLi1013** [comment]
I checked `glfw `source code and found that there was no place to use `angle`.
I also noticed that `glfw `depends on `egl `via `find_package(Wayland REQUIRED Client Cursor Egl)` in https://github.com/glfw/glfw/blob/master/CMakeLists.txt#L234
Since there is no need to use `angle `to build `glfw` and vcpkg will not rely on `angle `either.

Based on these information, vcpkg will not copy libEgl.dll to the build folder. 
In my opinion, this is intend behavior now.

Please also refer to this issue https://github.com/glfw/glfw/issues/1169  and the following docs  to know about more info about `egl `in `glfw`.
 https://github.com/glfw/glfw/blob/master/docs/compat.dox
https://github.com/glfw/glfw/blob/master/docs/compat.dox

**Comment by ruhrie** [comment]
I'm fairly certain the issue you are referencing doesn't pertain to this issue. It is specific to OSX and I can get expected behavior if I manually copy the dll myself. I found that issue myself before, but determined it was unrelated.

Although this may be intended behavior, it really doesn't address my problem that using glfw and angle together when built through vcpkg requires manual intervention in order for it to work. Glfw doesn't link to egl, gles, or gl at compile time, but they are still required at run time depending on the arguments used to interface with it.

The way I view my issue is that it is one of two things. It is either reporting that glfw and angle cannot be used together in its current state and that one of the ports needs updating, or it is a feature request to allow me to specify that libegl needs to be copied to the build folder. 

I acknowledge that this is an odd corner case, but it is still a problem.

**Comment by JackBoosY** [comment]
Hi @ruhrie, vcpkg only supports integration into `cmake` or `msvc` projects. If you use other IDE for development, you may need to manually copy the dynamic library to the project build folder.

**Comment by NancyLi1013** [comment]
I think this issue is solved now.
Please feel free to reopen this if you still have problems.
