### ISSUE TITLE
liblzma:x64-mingw build failure

### ISSUE THREAD

**Issue by yamcenutzer** [microsoft/vcpkg#9823]
failing liblzma obviously also will fail dependent projects e.g. some of the boost stuff, and anything that is built after that.

for x64-mingw the config.h file is missing,

C:/robinmi/vcpkg.master/buildtrees/liblzma/src/v5.2.4-66bfe33102/src/common/sysdefs.h:24:11: fatal error: config.h: No such file or directory
 
...probably due to this line 10 in CmakeLists.txt:
if(NOT WIN32)
...

**Comment by invy** [comment]
It's because the 
if(MSVC) later, there is the path being set to the corresponding windows relevant headers (including config.h specially tailored for windows)

**Comment by yamcenutzer** [comment]
... and since mingw isn't msvc, this doesn't work

**Comment by cenit** [comment]
Can you draft a PR?

**Comment by invy** [comment]
Replace if(MSVC) with if(WIN32) which will set include path. It did the trick for me.

**Comment by cenit** [comment]
I was just asking if you had time to properly submit a pr for this fix

**Comment by mavetek** [comment]
> 
> 
> Replace if(MSVC) with if(WIN32) which will set include path. It did the trick for me.

Did you edit the CMakeLists.txt file? because it gets replaced everytime and every modification is lost

**Comment by invy** [comment]
@mavetek 
```
diff --git a/ports/liblzma/CMakeLists.txt b/ports/liblzma/CMakeLists.txt
index 58a48e6..88e5bb3 100644
--- a/ports/liblzma/CMakeLists.txt
+++ b/ports/liblzma/CMakeLists.txt
@@ -131,7 +131,7 @@ add_library(LibLZMA
     src/liblzma/simple/x86.c
 )

-if(MSVC)
+if(WIN32)
     target_include_directories(LibLZMA PRIVATE $<BUILD_INTERFACE:${CMAKE_CURRENT_LIST_DIR}/windows/vs2017>)
 else()
     target_compile_definitions(LibLZMA PRIVATE -DHAVE_VISIBILITY=1)
```

**Comment by longnguyen2004** [comment]
It should be fixed by https://github.com/microsoft/vcpkg/pull/12401, please test

**Comment by PhoebeHui** [comment]
Looks this issue has been fixed, please try to build the port with latest source.
