### ISSUE TITLE
[<boost-python:x64-linux>] build failure

### ISSUE THREAD

**Issue by adamvm** [microsoft/vcpkg#9824]
**Host Environment**
- OS: Linux Ubuntu
- Compiler: gcc (Ubuntu 9.2.1-25ubuntu1) 9.2.1 20200123

**To Reproduce**
`./vcpkg install boost`

**Failure logs** 
-Cut and past the appropriate build messages from the console output.
-Please attach any additional failure logs mentioned in the console output.

Building package boost-dll[core]:x64-linux...
-- Downloading https://github.com/boostorg/dll/archive/boost-1.72.0.tar.gz...
-- Extracting source /home/adi/dev/vcpkg/downloads/boostorg-dll-boost-1.72.0.tar.gz
-- Using source at /home/adi/dev/vcpkg/buildtrees/boost-dll/src/ost-1.72.0-0dcfbcd6a0
-- Packaging headers
-- Packaging headers done
-- Using cached /home/adi/dev/vcpkg/downloads/boost_LICENSE_1_0.txt
-- Installing: /home/adi/dev/vcpkg/packages/boost-dll_x64-linux/share/boost-dll/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package boost-dll[core]:x64-linux... done
Installing package boost-dll[core]:x64-linux...
Installing package boost-dll[core]:x64-linux... done
Elapsed time for package boost-dll:x64-linux: 1.422 s
Starting package 142/146: boost-local-function:x64-linux
Building package boost-local-function[core]:x64-linux...
-- Downloading https://github.com/boostorg/local_function/archive/boost-1.72.0.tar.gz...
-- Extracting source /home/adi/dev/vcpkg/downloads/boostorg-local_function-boost-1.72.0.tar.gz
-- Using source at /home/adi/dev/vcpkg/buildtrees/boost-local-function/src/ost-1.72.0-63a0c6e94a
-- Packaging headers
-- Packaging headers done
-- Using cached /home/adi/dev/vcpkg/downloads/boost_LICENSE_1_0.txt
-- Installing: /home/adi/dev/vcpkg/packages/boost-local-function_x64-linux/share/boost-local-function/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package boost-local-function[core]:x64-linux... done
Installing package boost-local-function[core]:x64-linux...
Installing package boost-local-function[core]:x64-linux... done
Elapsed time for package boost-local-function:x64-linux: 2.205 s
Starting package 143/146: boost-process:x64-linux
Building package boost-process[core]:x64-linux...
-- Downloading https://github.com/boostorg/process/archive/boost-1.72.0.tar.gz...
-- Extracting source /home/adi/dev/vcpkg/downloads/boostorg-process-boost-1.72.0.tar.gz
-- Using source at /home/adi/dev/vcpkg/buildtrees/boost-process/src/ost-1.72.0-f1114610cf
-- Packaging headers
-- Packaging headers done
-- Using cached /home/adi/dev/vcpkg/downloads/boost_LICENSE_1_0.txt
-- Installing: /home/adi/dev/vcpkg/packages/boost-process_x64-linux/share/boost-process/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package boost-process[core]:x64-linux... done
Installing package boost-process[core]:x64-linux...
Installing package boost-process[core]:x64-linux... done
Elapsed time for package boost-process:x64-linux: 1.553 s
Starting package 144/146: boost-python:x64-linux
Building package boost-python[core]:x64-linux...
-- Downloading https://github.com/boostorg/python/archive/boost-1.72.0.tar.gz...
-- Extracting source /home/adi/dev/vcpkg/downloads/boostorg-python-boost-1.72.0.tar.gz
-- Using source at /home/adi/dev/vcpkg/buildtrees/boost-python/src/ost-1.72.0-c6a2496f74
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
-- Building x64-linux-rel
CMake Error at installed/x64-linux/share/boost-build/boost-modular-build.cmake:93 (message):
  No libraries were produced.  This indicates a failure while building the
  boost library.
Call Stack (most recent call first):
  ports/boost-python/portfile.cmake:19 (boost_modular_build)
  scripts/ports.cmake:94 (include)

Error: Building package boost-python:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-python:x64-linux
  Vcpkg version: 2020.01.17-unknownhash

Additionally, attach any relevant sections from the log files above.
:~/dev/vcpkg$ ./vcpkg update
Using local portfile versions. To update the local portfiles, use `git pull`.
No packages need updating.
:~/dev/vcpkg$ git pull
Already up to date.

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by adamvm** [comment]
In system I installed python 2 and 3 with packages dev and dbg, it did not help to build package

**Comment by yurybura** [comment]
Related to #9780

**Comment by adamvm** [comment]
@PhoebeHui Hi Phoebe, any progress in this topic? Can I support anyhow?

**Comment by yurybura** [comment]
Hi @adamvm,
Can you try PR #9780?

**Comment by adamvm** [comment]
I tested after 'git pull' and './vcpkg install boost' including boost-python finished successfully.

**Comment by adamvm** [comment]
Resolved

**Comment by astavonin** [comment]
I have the same issue even after `git pull` and subsequent installation attempt. Is there a way to skip boost-python installation?

**Comment by yurybura** [comment]
Hello @astavonin,
Could you provide a build log?

**Comment by adamvm** [comment]
@astavonin Is the problem still occcuring ?

**Comment by astavonin** [comment]
@adamvm, do not know. It was pet-project and I just switched to Conan.
