### ISSUE TITLE
[New Port Request] <nnabla>

### ISSUE THREAD

**Issue by 3250** [microsoft/vcpkg#9829]
Library name:nnabla

Library description:nnabla(Neural Network Libraries) is a deep learning framework that is intended to be used for research, development and production.

Source repository URL:[https://github.com/sony/nnabla](https://github.com/sony/nnabla)

Project homepage (if different from the source repository):[https://nnabla.org](https://nnabla.org)

Anything else that is useful to know when adding (such as optional features the library may have that should be included):[https://nnabla.readthedocs.io/en/latest/](https://nnabla.readthedocs.io/en/latest/)

**Comment by LilyWangL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
