### ISSUE TITLE
bootstrap-vcpkg.bat failed if Windows Kits not in %PROGRAMFILES% path

### ISSUE THREAD

**Issue by Banzai292** [Microsoft/vcpkg#983]
I've a problem to build vcpkg on Windows 7 with VS2012/2015 and 2017. Executing bootstrap-vcpkg.bat results in:

> Could not detect a Windows SDK / TargetPlatformVersion

On my system the "Windows Kits" are not in the %PROGRAMFILES% path, because I've installed much more on my "D:\Program Files..." folder (my C:-SSD runs out of space).

For my personal solution I've added a new PowerShell script for examine the registry, where the "Windows Kits" have a own entry (see HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows Kits\Installed Roots).

Also I modfied the getWindowsSDK.ps1 to get these path.

This works for me and build vcpkg.exe successfully!

Please have a look and maybe merge my solution to the repository. It's NOT tested on other Windows versions nor VC installations!!!

`getWindowsSDK.ps1 Line 20: $CandidateProgramFiles = $(& $scriptsDir\getProgramFiles32bit.ps1), $(& $scriptsDir\getProgramFilesPlatformBitness.ps1), $(& $scriptsDir\getKitsRootFromRegistry.ps1)`

Script 'getKitsRootFromRegistry.ps1':
```
[CmdletBinding()]
param(
)
$key = "Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows Kits\Installed Roots"
$kit = (Get-ItemProperty -Path $key -Name "KitsRoot").KitsRoot
if ($kit -ne $null)
{
    $out = (Split-Path (Split-Path $kit -Parent) -Parent)
    if ($out -eq $null)
    {
        throw "Could not find [KitsRoot]"
    }
}
return $out
```

**Comment by gugadev** [comment]
Same here. Any update about this?
