### ISSUE TITLE
[fluidsynth ] Update Fluidsynth to 2.1.0

### ISSUE THREAD

**Issue by zhuman** [microsoft/vcpkg#9834]
Fluidsynth recently released version 2.1.0: https://github.com/FluidSynth/fluidsynth/releases/tag/v2.1.0

**Comment by NancyLi1013** [comment]
Hi @zhuman thanks for posting this issue.
`Fluidsynth` has been updated to 2.1.0.
Please try to update vcpkg and rebuild this port.

**Comment by zhuman** [comment]
Thanks a lot Nancy!! :-)
