### ISSUE TITLE
[New Port Request] Geomagnetism Library

### ISSUE THREAD

**Issue by tastaton** [microsoft/vcpkg#9839]
Library name:  Geomagnetism Library

Library description:  Defacto standard library for using geomagnetic map data distributed by NOAA.

Source repository URL:  https://www.ngdc.noaa.gov/geomag/WMM

Project homepage (if different from the source repository):  https://www.ngdc.noaa.gov/geomag/WMM

Anything else that is useful to know when adding (such as optional features the library may have that should be included): 
I am guessing this library has not been ported because it does not have cmake support out of the box. However, it is very small library and should be easy to add.

**Comment by LilyWangL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.
