### ISSUE TITLE
[grpc] Automatically link ws2_32.lib on Windows

### ISSUE THREAD

**Issue by ceranco** [microsoft/vcpkg#9840]
****

**Is your feature request related to a problem? Please describe.**
When creating an *MSBuild* project that uses **grpc** (through `vcpkg integrate`), it fails with linker errors.

**Proposed solution**
Automatically add linking with **ws2_32.lib** on Windows.

**Additional context**
* **OS** - Windows
* **Compiler** - MSVC
* **Visual Studio version** - Community 2019 (16.4.2)

**Comment by JackBoosY** [comment]
Related discussion: https://github.com/microsoft/vcpkg/discussions/17739.
