### ISSUE TITLE
avro-c build failure

### ISSUE THREAD

**Issue by kreuzerkrieg** [microsoft/vcpkg#9841]
- OS:Linux
- Compiler: GCC 9.2
`./vcpkg install avro-c`

**Failure logs** 
By not providing "FindJANSSON.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "JANSSON", but
  CMake did not find one.

  Could not find a package configuration file provided by "JANSSON" with any
  of the following names:

    JANSSONConfig.cmake
    jansson-config.cmake

  Add the installation prefix of "JANSSON" to CMAKE_PREFIX_PATH or set
  "JANSSON_DIR" to a directory containing one of the above files.  If
  "JANSSON" provides a separate development package or SDK, be sure it has
  been installed.

**Comment by LilyWangL** [comment]
The port avro-c has been updated to version 1.9.2 in PR #10380, and it doesn't support triplet uwp Linux OSX. So closed this PR.
