### ISSUE TITLE
Numerous libraries

### ISSUE THREAD

**Issue by kreuzerkrieg** [microsoft/vcpkg#9842]
Before I start a bunch of PRs I want to make sure `vcpkg` does not have it, maybe under another name or something.

- [base64](https://github.com/microsoft/vcpkg/pull/9911) - https://github.com/powturbo/Turbo-Base64
- cppkafka - https://github.com/mfontanini/cppkafka **[Already exists]**
- fastops - https://github.com/yandex/fastops
- [h3](https://github.com/microsoft/vcpkg/pull/9914) - https://github.com/uber/h3
- [libcpuid](https://github.com/microsoft/vcpkg/pull/9942) - https://github.com/anrieff/libcpuid.git
- libdivide - https://github.com/ridiculousfish/libdivide **[Already exists]**
- [libfarmhash](https://github.com/microsoft/vcpkg/pull/9929) - https://github.com/google/farmhash
- libgsasl - git://git.savannah.gnu.org/gsasl.git
- [libhdfs3](https://github.com/microsoft/vcpkg/pull/10021) - https://github.com/erikmuttersbach/libhdfs3
- [libmetrohash](https://github.com/microsoft/vcpkg/pull/10049) - https://github.com/jandrewrogers/MetroHash
- libunwind - https://github.com/libunwind/libunwind
- [mumurhash](https://github.com/microsoft/vcpkg/pull/10164) - https://github.com/aappleby/smhasher
- [replxx](https://github.com/microsoft/vcpkg/pull/10052) - https://github.com/AmokHuginnsson/replxx
- [ryu](https://github.com/microsoft/vcpkg/pull/10167) - https://github.com/ulfjack/ryu
- [unixodbc](https://github.com/microsoft/vcpkg/pull/10057) - https://github.com/lurcher/unixODBC
- zlib-ng - https://github.com/zlib-ng/zlib-ng

Does anyone can go over the list and confirm these are not already a part of `vcpkg`?

EDIT001: I will reference my PRs here just for convenience

**Comment by JackBoosY** [comment]
- base64: no
- cppkafka: exist
- fastops: no
- h3: no
- libcpuid: no
- libdivide: exist
- libfarmhash: no
- libgsasl: no
- libhdfs3: no
- libmetrohash: no
- libunwind: no
- mumurhash: no
- replxx: no
- ryu: no
- unixodbc: no
- zlib-ng: no

**Comment by LilyWangL** [comment]
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.

**Comment by kreuzerkrieg** [comment]
sure
thanks
