### ISSUE TITLE
llvm build failure

### ISSUE THREAD

**Issue by kreuzerkrieg** [microsoft/vcpkg#9843]
**Host Environment**
- OS: Linux
- Compiler: GNU 9.2.1

`./vcpkg install llvm`

**Failure logs** 

> [541/2696] /usr/lib/ccache/c++  -DGTEST_HAS_RTTI=0 -DLZMA_API_STATIC -D_DEBUG -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Ilib/IR -I/home/user/Development/vcpkg/buildtrees/llvm/src/llvm-8-1465978786/lib/IR -I/home/user/Development/vcpkg/installed/x64-linux/include -Iinclude -I/home/user/Development/vcpkg/buildtrees/llvm/src/llvm-8-1465978786/include -fPIC -fPIC -fvisibility-inlines-hidden -Werror=date-time -std=c++11 -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wno-maybe-uninitialized -Wno-class-memaccess -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wno-comment -fdiagnostics-color -g    -fno-exceptions -fno-rtti -MD -MT lib/IR/CMakeFiles/LLVMCore.dir/LLVMContextImpl.cpp.o -MF lib/IR/CMakeFiles/LLVMCore.dir/LLVMContextImpl.cpp.o.d -o lib/IR/CMakeFiles/LLVMCore.dir/LLVMContextImpl.cpp.o -c /home/user/Development/vcpkg/buildtrees/llvm/src/llvm-8-1465978786/lib/IR/LLVMContextImpl.cpp
> [542/2696] /usr/lib/ccache/c++  -DGTEST_HAS_RTTI=0 -DLZMA_API_STATIC -D_DEBUG -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Ilib/IR -I/home/user/Development/vcpkg/buildtrees/llvm/src/llvm-8-1465978786/lib/IR -I/home/user/Development/vcpkg/installed/x64-linux/include -Iinclude -I/home/user/Development/vcpkg/buildtrees/llvm/src/llvm-8-1465978786/include -fPIC -fPIC -fvisibility-inlines-hidden -Werror=date-time -std=c++11 -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wno-maybe-uninitialized -Wno-class-memaccess -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wno-comment -fdiagnostics-color -g    -fno-exceptions -fno-rtti -MD -MT lib/IR/CMakeFiles/LLVMCore.dir/LegacyPassManager.cpp.o -MF lib/IR/CMakeFiles/LLVMCore.dir/LegacyPassManager.cpp.o.d -o lib/IR/CMakeFiles/LLVMCore.dir/LegacyPassManager.cpp.o -c /home/user/Development/vcpkg/buildtrees/llvm/src/llvm-8-1465978786/lib/IR/LegacyPassManager.cpp
> [543/2696] /usr/lib/ccache/c++  -DGTEST_HAS_RTTI=0 -DLZMA_API_STATIC -D_DEBUG -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Ilib/IR -I/home/user/Development/vcpkg/buildtrees/llvm/src/llvm-8-1465978786/lib/IR -I/home/user/Development/vcpkg/installed/x64-linux/include -Iinclude -I/home/user/Development/vcpkg/buildtrees/llvm/src/llvm-8-1465978786/include -fPIC -fPIC -fvisibility-inlines-hidden -Werror=date-time -std=c++11 -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wno-maybe-uninitialized -Wno-class-memaccess -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wno-comment -fdiagnostics-color -g    -fno-exceptions -fno-rtti -MD -MT lib/IR/CMakeFiles/LLVMCore.dir/Mangler.cpp.o -MF lib/IR/CMakeFiles/LLVMCore.dir/Mangler.cpp.o.d -o lib/IR/CMakeFiles/LLVMCore.dir/Mangler.cpp.o -c /home/user/Development/vcpkg/buildtrees/llvm/src/llvm-8-1465978786/lib/IR/Mangler.cpp
> [544/2696] /usr/lib/ccache/c++  -DGTEST_HAS_RTTI=0 -DLZMA_API_STATIC -D_DEBUG -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Ilib/IR -I/home/user/Development/vcpkg/buildtrees/llvm/src/llvm-8-1465978786/lib/IR -I/home/user/Development/vcpkg/installed/x64-linux/include -Iinclude -I/home/user/Development/vcpkg/buildtrees/llvm/src/llvm-8-1465978786/include -fPIC -fPIC -fvisibility-inlines-hidden -Werror=date-time -std=c++11 -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wno-maybe-uninitialized -Wno-class-memaccess -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wno-comment -fdiagnostics-color -g    -fno-exceptions -fno-rtti -MD -MT lib/IR/CMakeFiles/LLVMCore.dir/ModuleSummaryIndex.cpp.o -MF lib/IR/CMakeFiles/LLVMCore.dir/ModuleSummaryIndex.cpp.o.d -o lib/IR/CMakeFiles/LLVMCore.dir/ModuleSummaryIndex.cpp.o -c /home/user/Development/vcpkg/buildtrees/llvm/src/llvm-8-1465978786/lib/IR/ModuleSummaryIndex.cpp
> [545/2696] /usr/lib/ccache/c++  -DHAVE_POSIX_REGEX -DHAVE_STD_REGEX -DHAVE_STEADY_CLOCK -DLZMA_API_STATIC -D_DEBUG -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Iutils/benchmark/src -I/home/user/Development/vcpkg/buildtrees/llvm/src/llvm-8-1465978786/utils/benchmark/src -I/home/user/Development/vcpkg/installed/x64-linux/include -Iinclude -I/home/user/Development/vcpkg/buildtrees/llvm/src/llvm-8-1465978786/include -I/home/user/Development/vcpkg/buildtrees/llvm/src/llvm-8-1465978786/utils/benchmark/include -I/home/user/Development/vcpkg/buildtrees/llvm/src/llvm-8-1465978786/utils/benchmark/src/../include -fPIC -fPIC -fvisibility-inlines-hidden -Werror=date-time -std=c++11 -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wno-maybe-uninitialized -Wno-class-memaccess -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wno-comment -fdiagnostics-color  -std=c++11  -Wall  -Wextra  -Wshadow  -pedantic  -pedantic-errors  -Wfloat-equal  -fstrict-aliasing  -fno-exceptions  -Wstrict-aliasing -g -MD -MT utils/benchmark/src/CMakeFiles/benchmark.dir/benchmark.cc.o -MF utils/benchmark/src/CMakeFiles/benchmark.dir/benchmark.cc.o.d -o utils/benchmark/src/CMakeFiles/benchmark.dir/benchmark.cc.o -c /home/user/Development/vcpkg/buildtrees/llvm/src/llvm-8-1465978786/utils/benchmark/src/benchmark.cc
> FAILED: utils/benchmark/src/CMakeFiles/benchmark.dir/benchmark.cc.o 
> /usr/lib/ccache/c++  -DHAVE_POSIX_REGEX -DHAVE_STD_REGEX -DHAVE_STEADY_CLOCK -DLZMA_API_STATIC -D_DEBUG -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Iutils/benchmark/src -I/home/user/Development/vcpkg/buildtrees/llvm/src/llvm-8-1465978786/utils/benchmark/src -I/home/user/Development/vcpkg/installed/x64-linux/include -Iinclude -I/home/user/Development/vcpkg/buildtrees/llvm/src/llvm-8-1465978786/include -I/home/user/Development/vcpkg/buildtrees/llvm/src/llvm-8-1465978786/utils/benchmark/include -I/home/user/Development/vcpkg/buildtrees/llvm/src/llvm-8-1465978786/utils/benchmark/src/../include -fPIC -fPIC -fvisibility-inlines-hidden -Werror=date-time -std=c++11 -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wno-maybe-uninitialized -Wno-class-memaccess -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wno-comment -fdiagnostics-color  -std=c++11  -Wall  -Wextra  -Wshadow  -pedantic  -pedantic-errors  -Wfloat-equal  -fstrict-aliasing  -fno-exceptions  -Wstrict-aliasing -g -MD -MT utils/benchmark/src/CMakeFiles/benchmark.dir/benchmark.cc.o -MF utils/benchmark/src/CMakeFiles/benchmark.dir/benchmark.cc.o.d -o utils/benchmark/src/CMakeFiles/benchmark.dir/benchmark.cc.o -c /home/user/Development/vcpkg/buildtrees/llvm/src/llvm-8-1465978786/utils/benchmark/src/benchmark.cc
> In file included from /home/user/Development/vcpkg/buildtrees/llvm/src/llvm-8-1465978786/utils/benchmark/src/benchmark.cc:16:
> /home/user/Development/vcpkg/buildtrees/llvm/src/llvm-8-1465978786/utils/benchmark/src/benchmark_api_internal.h:16:28: error: qualified name does not name a class before ‘{’ token
>    16 | struct Benchmark::Instance {
>       |                            ^
> /home/user/Development/vcpkg/buildtrees/llvm/src/llvm-8-1465978786/utils/benchmark/src/benchmark_api_internal.h:37:52: error: ‘Instance’ is not a member of ‘benchmark::internal::Benchmark’
>    37 |                             std::vector<Benchmark::Instance>* benchmarks,
>       |  
>

**Comment by JackBoosY** [comment]
@ras0219-msft Could you take a look?

**Comment by kreuzerkrieg** [comment]
Guys, can the complete log help here?

**Comment by JackBoosY** [comment]
Yes, we are locating the issue with your log.

**Comment by kreuzerkrieg** [comment]
> Yes, we are locating the issue with your log.

here you go
https://1drv.ms/u/s!AvKB-sqTwjdHhp9T2GqAIDQwVrkHtw?e=NWCLF0

Let me know when I can remove the share

**Comment by JackBoosY** [comment]
Seems related to https://reviews.llvm.org/D54978

**Comment by kreuzerkrieg** [comment]
Affirmative
After removing `libz3-dev` package the `llvm` port was installedsuccessfully
