### ISSUE TITLE
Building package atlmfc:x86-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by plainsimple908** [microsoft/vcpkg#9844]
**Host Environment**
- OS: Windows 10
- Compiler: revision

**To Reproduce**
./vcpkg install azure-storage-cpp

Package: atlmfc:x86-windows
Vcpkg version: 2020.01.17-nohash

**Comment by JackBoosY** [comment]
See [here](https://github.com/microsoft/vcpkg/issues/7446#issuecomment-532588909).

**Comment by plainsimple908** [comment]
Jack,

Thanks a lot! I'll look into it.
