### ISSUE TITLE
freetype and harfbuzz - cycle detected with graph at freetype:x64-windows

### ISSUE THREAD

**Issue by timautry** [microsoft/vcpkg#9850]
**Describe the bug**
freetype and harfbuzz - cycle detected with graph at freetype:x64-windows

**Environment**
- OS: [Windows 10 Pro x64 Version 1909 18363.628]
- Compiler: VS2017 v15.9.19 VCToolsVersion=14.16.27023
VS2019 v16.4.3 VCToolsVersion=14.24.28314

**To Reproduce**
**1.** ->vcpkg install freetype[bzip2,core,harfbuzz]

**2.** See error:
Cycle detected within graph at freetype:x64-windows:
    freetype:x64-windows
    harfbuzz:x64-windows

**Expected behavior**
Should install package freetype with features bzip2 and harfbuzz

**Failure logs** 
_No Error Logs produced_

**Additional context**
It appears that freetype package with harfbuzz feature requires harfbuzz to be installed first but one of harfbuzz's dependent packages depends on freetype be install first - a proverbial catch-22 scenario, neither can exist without the other being installed first.

**Comment by PhoebeHui** [comment]
@timautry, thanks for reporting this issue!

It's regression issue involved by PR#[9706](https://github.com/microsoft/vcpkg/pull/9706/files#diff-c749ea991f09dcbf17cf110ae879acacR12-R14)

**Comment by timautry** [comment]
You are welcomed! Thanks for the update 👍 :)

**Comment by PhoebeHui** [comment]
@timautry, the PR has been merged.

**Comment by timautry** [comment]
Thank you!
