### ISSUE TITLE
opencolorio and openimageio - cycle detected within graph at opencolorio:x64-windows

### ISSUE THREAD

**Issue by ghost** [microsoft/vcpkg#9851]
**Describe the bug**
opencolorio and openimageio - cycle detected within graph at opencolorio:x64-windows

**Environment**
- OS: [Windows 10 Pro x64 Version 1909 18363.628]
- Compiler: VS2017 v15.9.19 VCToolsVersion=14.16.27023
VS2019 v16.4.3 VCToolsVersion=14.24.28314

**To Reproduce**
**1.** ->vcpkg install opencolorio[applications,core] openimageio[libraw,opencolorio,ffmpeg,freetype,opencv,gif,openjpeg,webp,tools]

**2.** See error
Cycle detected within graph at opencolorio:x64-windows:
    opencolorio:x64-windows
    openimageio:x64-windows

**Expected behavior**
Should install opencolorio and openimageio with selected features

**Failure logs** 
_No logs produced_

**Additional context**
It appears _opencolorio package with applications feature_ depends on openimageio to be installed first, but _openimageio with opencolorio feature requires opencolorio_ to be installed first - another catch-22 scenario where neither can exist without the other being installed first.

**Comment by JackBoosY** [comment]
Hi @timautry, thanks for pointing this out!

**Comment by timautry** [comment]
You are most welcome!

**Comment by JackBoosY** [comment]
Please keep this issue open before we resolve it.

**Comment by timautry** [comment]
I close, I no longer use product.
