### ISSUE TITLE
[gettext] Unicode paths passed to bindtextdomain fail on Windows

### ISSUE THREAD

**Issue by past-due** [microsoft/vcpkg#9854]
**Describe the bug**
gettext fails to load message catalogs from dirnames containing non-ASCII Unicode characters

**Environment**
- OS: Windows
- Compiler: MSVC (any supported version)

**To Reproduce**
1. ./vcpkg install gettext
2. In your app, call `bindtextdomain` with a UTF-8 dirname, containing characters outside of the ASCII range (as works on other platforms)

**Expected behavior**
gettext succeeds at finding message catalogs in the valid UTF-8 dirname

**Actual behavior**
gettext fails to load message catalogs

**Issue cause**
gettext uses [`open`](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/open?view=vs-2019) internally, which does *not* support / expect UTF-8 filenames on the MSVCRT.

PR forthcoming with fix.

**Comment by JackBoosY** [comment]
Close this issue via #9855 merged.
