### ISSUE TITLE
How do I install other version package?

### ISSUE THREAD

**Issue by 1m188** [microsoft/vcpkg#9856]
How can I install other version package by vcpkg? For example, I search Qt package by using command ".\vcpkg search Qt5", and the results show that qt5's version is 5.12.5, how can I install 5.12.3 version for qt5? Are there any command or parameters can I use? I saw the docs [https://github.com/microsoft/vcpkg/blob/master/docs/index.md#examples](url) and didn't find the ways.

**Comment by JackBoosY** [comment]
Hi @1m188, thanks for reporting this issue!

You can follow these steps:
1. Use command `.\vcpkg x-history qt5`
2. Get the commit id of the version you need.
3. Use command `git reset <commit id>`
4. Rebuild qt5.

Thanks.

**Comment by 1m188** [comment]
> Hi @1m188, thanks for reporting this issue!
> 
> You can follow these steps:
> 
> 1. Use command `.\vcpkg x-history qt5`
> 2. Get the commit id of the version you need.
> 3. Use command `git reset <commit id>`
> 4. Rebuild qt5.
> 
> Thanks.

Yeah...Thanks...but, how if I need to use different version package in different project? Can I manage them all by a vcpkg? If I need a package with several different version in my pc?

**Comment by JackBoosY** [comment]
Vcpkg does not currently have a similar function like that.
You can copy all the files in _VCPKG_PATH/ports/<your_needed_port>_ to the latest vcpkg, but we cannot guarantee the correctness of the dependency chain, you may encounter some build errors.

**Comment by 1m188** [comment]
> Vcpkg does not currently have a similar function like that.
> You can copy all the files in _VCPKG_PATH/ports/<your_needed_port>_ to the latest vcpkg, but we cannot guarantee the correctness of the dependency chain, you may encounter some build errors.

OK...Thank you for your answer.XD
