### ISSUE TITLE
[libpqxx] x64-linux-dynamic build failure

### ISSUE THREAD

**Issue by blemidon** [microsoft/vcpkg#9867]
**Host Environment**
- OS: [CentOS Linux release 8.1.1911 (Core)]
- Compiler: gcc version 8.3.1 20190507 (Red Hat 8.3.1-4) (GCC)

**To Reproduce**
`./vcpkg install libpqxx:x64-linux-dynamic --overlay-triplets=custom-triplets`

**Failure logs** 
-- Building x64-linux-dynamic-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: /home/imrei/Projects/ClarusERP3/vcpkg/downloads/tools/cmake-3.14.0-linux/cmake-3.14.0-Linux-x86_64/bin/cmake --build . --config Debug --target install -- -v
    Working Directory: /home/imrei/Projects/ClarusERP3/vcpkg/buildtrees/libpqxx/x64-linux-dynamic-dbg
    See logs for more information:
      /home/imrei/Projects/ClarusERP3/vcpkg/buildtrees/libpqxx/install-x64-linux-dynamic-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:91 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/libpqxx/portfile.cmake:22 (vcpkg_install_cmake)
  scripts/ports.cmake:94 (include)
[install-x64-linux-dynamic-dbg-out.log](https://github.com/microsoft/vcpkg/files/4140920/install-x64-linux-dynamic-dbg-out.log)

**Additional context**
x64-linux-dynamic.cmake

set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)
set(VCPKG_CMAKE_SYSTEM_NAME Linux)

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. `libpqxx:x64-linux` can install succeed. `x64-linux-dynamic` is a community triplet, and there are no update about this issue for a long time. If there are new process or change of this issue, please reopen this issue.
