### ISSUE TITLE
[azure-c-shared-utility] BUILD_FAILED

### ISSUE THREAD

**Issue by john-goodrich-allegion** [microsoft/vcpkg#9868]
Trying to build code from directions in Azure IoT Device C SDK, I get the following output:

c:\Dev\azure-iot-sdk-c\vcpkg>.\vcpkg install azure-iot-sdk-c
The following packages will be built and installed:
  * azure-c-shared-utility[core]:x86-windows
    azure-iot-sdk-c[core]:x86-windows
  * azure-uamqp-c[core]:x86-windows
  * azure-uhttp-c[core]:x86-windows
  * azure-umqtt-c[core]:x86-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/5: azure-c-shared-utility:x86-windows
Building package azure-c-shared-utility[core]:x86-windows...
-- Note: azure-c-shared-utility only supports static library linkage. Building static library.
-- Using cached C:/Dev/azure-iot-sdk-c/vcpkg/downloads/Azure-azure-c-shared-utility-48f7a556865731f0e96c47eb5e9537361f24647c.tar.gz
-- Using source at C:/Dev/azure-iot-sdk-c/vcpkg/buildtrees/azure-c-shared-utility/src/361f24647c-a231eef333
-- Configuring x86-windows
-- Building x86-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v
    Working Directory: C:/Dev/azure-iot-sdk-c/vcpkg/buildtrees/azure-c-shared-utility/x86-windows-dbg
    See logs for more information:
      C:\Dev\azure-iot-sdk-c\vcpkg\buildtrees\azure-c-shared-utility\install-x86-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:91 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/azure-c-shared-utility/portfile.cmake:37 (vcpkg_install_cmake)
  scripts/ports.cmake:94 (include)

Error: Building package azure-c-shared-utility:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: azure-c-shared-utility:x86-windows
  Vcpkg version: 2020.01.17-nohash

Additionally, attach any relevant sections from the log files above.

**Comment by JackBoosY** [comment]
Hi @john-goodrich-allegion, thanks for reporting this issue!
Can you provide failure log _C:\Dev\azure-iot-sdk-c\vcpkg\buildtrees\azure-c-shared-utility\install-x86-windows-dbg-out.log_?

Thanks.

**Comment by john-goodrich-allegion** [comment]
Here is the log.
[install-x86-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/4144565/install-x86-windows-dbg-out.log)

**Comment by JackBoosY** [comment]
@john-goodrich-allegion Please re-install `azure-macro-utils-c` then try again.

Thanks.

**Comment by john-goodrich-allegion** [comment]
Now able to build and run.  Thank you!
