### ISSUE TITLE
GTK 3.20 build failure

### ISSUE THREAD

**Issue by The-UltimateGamer** [microsoft/vcpkg#9869]
**Host Environment**
- OS: Windows 10 Home
- Compiler: VS 2019 Community

**To Reproduce**
`./vcpkg install gtk:x64-windows`

**Failure logs** 
The following packages will be built and installed:
    gtk[core]:x64-windows
Starting package 1/1: gtk:x64-windows
Building package gtk[core]:x64-windows...
-- Downloading https://ftp.gnome.org/pub/gnome/sources/gtk+/3.22/gtk+-3.22.19.tar.xz...
-- Downloading https://ftp.gnome.org/pub/gnome/sources/gtk+/3.22/gtk+-3.22.19.tar.xz... Failed. Status: 56;"Failure when receiving data from the peer"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:175 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  ports/gtk/portfile.cmake:5 (vcpkg_download_distfile)
  scripts/ports.cmake:94 (include)

Error: Building package gtk:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: gtk:x64-windows
  Vcpkg version: 2020.01.17-nohash

Additionally, attach any relevant sections from the log files above.

**Additional context**
Tried "./vcpkg update" & "git pull"

**Comment by JackBoosY** [comment]
It looks like your network can't connect to the source, please download [the source](https://ftp.gnome.org/pub/gnome/sources/gtk+/3.22/gtk+-3.22.19.tar.xz) manually and prevent it in _VCPKG_PATH/downloads_, then rebuild gtk.

Thanks.

**Comment by JackBoosY** [comment]
If this issue is still not resolved, please reopen it.
