### ISSUE TITLE
[azure-iot-sdk-c] build failure

### ISSUE THREAD

**Issue by mikemorrison111** [microsoft/vcpkg#9870]
**Host Environment**
- OS: Windows 10, Version	10.0.18363 Build 18363
- Compiler: revision

**To Reproduce**
Install packages as per https://docs.microsoft.com/en-us/azure/iot-pnp/quickstart-create-pnp-device-windows
    Fails at: 
.\vcpkg.exe install azure-iot-sdk-c[public-preview,use_prov_client]

**Failure logs** 
CMake Error at scripts/cmake/vcpkg_apply_patches.cmake:52 (message):
  Applying patch failed.  Patch needs to be updated to work with source being
  used by vcpkg!

-Please attach any additional failure logs mentioned in the console output.

**Additional context**
Error: Building package azure-c-shared-utility:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
  Package: azure-c-shared-utility:x86-windows
  Vcpkg version: 2020.01.17-nohash

**Comment by JackBoosY** [comment]
Confirmed.

**Comment by JackBoosY** [comment]
Hi @mikemorrison111, thanks for reporting this issue!
I've fixed it in #9871, please update vcpkg and rebuild azure-iot-sdk-c.

Thanks.
