### ISSUE TITLE
[freerdp] Include directory is not right.

### ISSUE THREAD

**Issue by ahura24** [microsoft/vcpkg#9872]
**Describe the bug**
I think there is a bug in "freerdp" port file. When installion was completed, all header files copy into the path "freerdp2/freerdp/...", but include files need to see the path "freerdp/...".

**Environment**
- OS: Windows 10
- Compiler: VC-2017

**To Reproduce**
1. ./vcpkg install freerdp:x64-windows-static

**Expected behavior**
Copy all include files into the right addresses "freerdp" and "winpr".

thanks so much.

**Comment by NancyLi1013** [comment]
Hi @ahura24 thanks for posting this issue.
This issue has been fixed now. Please try to update vcpkg and rebuild this port.
