### ISSUE TITLE
[lodepng] import failure

### ISSUE THREAD

**Issue by neverfelly** [microsoft/vcpkg#9875]
package [lodepng] installed without instructions and cmake `find` function support, so I do not know how to use this port.

**Comment by JackBoosY** [comment]
Hi @neverfelly, thanks for reporting this issue!
You can use the following code to use this port:
```
find_library(lodepng lodepng REQUIRED)
find_path(lodepng_INCLUDES lodepng.h)

target_link_libraries(main PRIVATE ${lodepng})
target_include_directories(main PRIVATE ${lodepng_INCLUDES})
```

Thanks.

**Comment by neverfelly** [comment]
Thanks you for solving my problem! And also I wonder how to add instructions when I install it.

**Comment by JackBoosY** [comment]
Currently, lodepng does not have `vcpkg-cmake-wrapper.cmake` to handle usage issues.
We will add it in the future.

**Comment by LilyWangLL** [comment]
Thanks for posting this issue. This issue has been fixed, now `lodepng` provide the usage on latest vcpkg.
```
The package lodepng provides CMake targets:

    # C API
    find_package(lodepng-c CONFIG REQUIRED)
    target_link_libraries(main PRIVATE lodepng-c)

    # C++ API
    find_package(lodepng CONFIG REQUIRED)
    target_link_libraries(main PRIVATE lodepng)

PS E:\Lily> .\vcpkg.exe --version
vcpkg package management program version 2023-06-22-f19f3d9939100085fe2f7e41502d60b08e2083b6
```
