### ISSUE TITLE
HDF5: can not find dependencies

### ISSUE THREAD

**Issue by lidar-nevermore** [microsoft/vcpkg#9876]
**Environment**
- OS: [Windows 10]
- Compiler: MSVC 2015

**Describe the bug**
I have integrated vcpkg into MSVC2015, and included the following code in my project:
https://github.com/mariusmuja/flann/blob/master/src/cpp/flann/io/hdf5.h

Then  I got link errors like the following:
 error LNK2001: unresolved external symbol H5T_NATIVE_FLOAT_g
 error LNK2001: unresolved external symbol H5T_NATIVE_USHORT_g
 error LNK2001: unresolved external symbol H5T_NATIVE_DOUBLE_g
 error LNK2001: unresolved external symbol H5T_NATIVE_LDOUBLE_g
 error LNK2001: unresolved external symbol H5T_NATIVE_LONG_g
 error LNK2001: unresolved external symbol H5T_NATIVE_ULONG_g
 error LNK2001: unresolved external symbol H5T_NATIVE_SHORT_g
 error LNK2001: unresolved external symbol H5T_NATIVE_INT_g
 error LNK2001: unresolved external symbol H5T_NATIVE_UINT_g
 error LNK2001: unresolved external symbol H5T_NATIVE_SCHAR_g
 error LNK2001: unresolved external symbol H5T_NATIVE_UCHAR_g

It appears that the hdf5 dependencies cannot be found by default settings.

So I tried adding them manually using CMAKE:
target_link_libraries(main PRIVATE flann::flann flann::flann_cpp hdf5::hdf5-shared hdf5::hdf5_hl-shared lz4::lz4)

It does work, but introduces addtional works

I'm wondering if there's a more convenient solution,  so I think I'd report the issue.

**Comment by contre** [comment]
Make sure you define H5_BUILT_AS_DYNAMIC_LIB in your consuming project.

That is likely your error.

**Comment by lidar-nevermore** [comment]
BINGO



> Make sure you define H5_BUILT_AS_DYNAMIC_LIB in your consuming project.
> 
> That is likely your error.
