### ISSUE TITLE
Build error attempt to build pcl:arm-linux

### ISSUE THREAD

**Issue by spmuske00** [microsoft/vcpkg#9878]
Package: pcl:arm-linux
  Vcpkg version: 2020.01.17-unknownhash

ninja: build stopped: subcommand failed.

No other details provided in build error log or dbg-out log

**Comment by PhoebeHui** [comment]
@spmuske00, does this still be a problem for you?

**Comment by LilyWangLL** [comment]
This issue hasn’t been updated more than 3 months, if it is still an issue, please reopen this issue.
