### ISSUE TITLE
[libgd] Error when using non-ASCII words on Windows

### ISSUE THREAD

**Issue by xspeed1989** [microsoft/vcpkg#9882]
BGD_DECLARE(gdImagePtr) gdImageCreateFromFile(const char *filename);
The function will failed when the filename contains some chinese,janpanse,kor words and so on  

Thus  libgd need a BGD_DECLARE(gdImagePtr) gdImageCreateFromFile(FILE * inFile) on windows

**Comment by JackBoosY** [comment]
According to your description, this may be a source bug.
So can you go upstream to report this issue?

**Comment by xspeed1989** [comment]
> According to your description, this may be a source bug.
> So can you go upstream to report this issue?
Thanks！
I open so much webpage on my browser
haha! It's my fault, I should  report this future to libgd

**Comment by LilyWangLL** [comment]
@xspeed1989 Thanks for posting this issue. Did you report this issue on upstream? And does this issue fixed?

**Comment by xspeed1989** [comment]
> @xspeed1989 Thanks for posting this issue. Did you report this issue on upstream? And does this issue fixed?

I didn't report this issue on upstream,  and why am I report this issue on this repo......

**Comment by LilyWangLL** [comment]
> > According to your description, this may be a source bug.
> > So can you go upstream to report this issue?
> 
> Thanks！ I open so much webpage on my browser haha! It's my fault, I should report this future to libgd

@xspeed1989 You can see comment here.

**Comment by JackBoosY** [comment]
Close this PR until upstream fixes this.
