### ISSUE TITLE
[libpmemobj-cpp] update to 1.9

### ISSUE THREAD

**Issue by igchor** [microsoft/vcpkg#9884]
Library name: libpmemobj-cpp

New version number: 1.9

https://github.com/pmem/libpmemobj-cpp/releases/tag/1.9

**Comment by NancyLi1013** [comment]
It seems that this version needs to depend on `pmdk` as `libpmemobj/atomic_base.h` is in `pmdk`.

**Comment by igchor** [comment]
Yes, libpmemobj-cpp depends on pmdk and this dependency is checked in libpmemobj-cpp CMakeLists.txt. All versions of libpmemobj-cpp depend on pmdk.
