### ISSUE TITLE
Infinite CMake recursion when compiling OpenEXR from source.

### ISSUE THREAD

**Issue by ftpronk** [microsoft/vcpkg#9890]
**Bug Description**
I'm compiling `OpenEXR` 2.4 from source, relying on `vcpkg` to install the `zlib` and `boost` dependencies.  Due to some `CMake` scripts incompatibilities between both projects, CMake enters an infinite recursion loop with the message:

```
-- Configure ILMBASE Version: 2.4.1 Lib API: 24.0.0
CMake Error at C:/vcpkg/scripts/buildsystems/vcpkg.cmake:237 (string):
  Maximum recursion depth of 1000 exceeded
Call Stack (most recent call first):
  C:/vcpkg/scripts/buildsystems/vcpkg.cmake:286 (_find_package)
  C:/vcpkg/scripts/buildsystems/vcpkg.cmake:286 (_find_package)

[...]

  C:/vcpkg/scripts/buildsystems/vcpkg.cmake:286 (_find_package)
  C:/vcpkg/scripts/buildsystems/vcpkg.cmake:286 (_find_package)
  CMakeLists.txt:33 (_find_package)
  IlmBase/config/IlmBaseSetup.cmake:136 (find_package)
  IlmBase/CMakeLists.txt:35 (include)
-- Configuring incomplete, errors occurred!
```

**Environment**
- OS: `Windows 10 x64`
- Compiler: `Visual Studio version 16.4.29709.97`
- vcpkg version: `version 2020.01.17-nohash-external`
- vcpkg git commit:  f272b0c9846d24c2b77a5fb60e1061d397384acb
- OpenEXR git commit: `1cbf6b9a4497f71586ac11dc60ed21cf0cc529bd`

**To Reproduce**
- From the OpenEXR base directory:
```
mkdir build
cd .\build
cmake -DCMAKE_TOOLCHAIN_FILE=C:\vcpkg\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows-static ..
```

**Additional context**
From my limited CMake understanding, I suspect the macro redefining `find_package` in `vcpkg` might be conflicting with the `find_package` redefinition in the `OpenEXR` project, with CMake getting confused on `_find_package()` calls..

From: https://crascit.com/2018/09/14/do-not-redefine-cmake-commands/
> The prepending of one underscore to “save” the previous command only applies to the current name, it is not applied recursively to all previous overrides. This has the potential to lead to infinite recursion, as the following contrived example demonstrates

I might be completely of the mark here, so I'll leave the CMake debugging to the experts.. 😎 

As an important side-note, I first opened a bug report on the `OpenEXR` github page, where one of the contributors suggested to open a bug report in parallel here.  The underlying idea was to hopefully cooperate on a solution that could, more generally, lead to better compatibility between both projects, and avoid downstream patches to get `OpenEXR` to compile with `vcpkg`.

The original bug report can be found here: https://github.com/AcademySoftwareFoundation/openexr/issues/648

**Comment by vicroms** [comment]
I don't see how we could solve this without drastically changing the usage of vcpkg, the path with least resistance would be to modify OpenEXR locally. 

```cmake
macro(openexr_find_package)
    if (NOT "${ARGV0}" IN_LIST as_subproject)
        find_package(${ARGV}) # Calls VCPKG override
   endif()
endmacro()
```

And replace each instance of `find_package` in their CMake scripts with `openexr_find_package`.

**Comment by ftpronk** [comment]
> I don't see how we could solve this without drastically changing the usage of vcpkg, the path with least resistance would be to modify OpenEXR locally.

Probably not the safest of ideas to redefine CMake commands, no matter where..

> And replace each instance of `find_package` in their CMake scripts with `openexr_find_package`.

The `OpenEXR` guys seemed to be interested in solving that upstream.  Perhaps that can be discussed with them?
