### ISSUE TITLE
itk:x86-windows

### ISSUE THREAD

**Issue by ShaneKirkbride** [microsoft/vcpkg#9891]
**Host Environment**
- OS: Windows 10
- Compiler: Visual Studio 2017

**To Reproduce**
`./vcpkg install itk`

**Failure logs** 
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v
    Working Directory: C:/src/vcpkg/buildtrees/itk/x86-windows-dbg
    See logs for more information:
      C:\src\vcpkg\buildtrees\itk\install-x86-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:91 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/itk/portfile.cmake:67 (vcpkg_install_cmake)
  scripts/ports.cmake:94 (include)

Error: Building package itk:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: itk:x86-windows
  Vcpkg version: 2020.01.17-nohash
[install-x86-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/4148863/install-x86-windows-dbg-out.log)

-Please attach any additional failure logs mentioned in the console output.

**Additional context**
Let me know if you need anything else!

**Comment by PhoebeHui** [comment]
PR https://github.com/microsoft/vcpkg/pull/11208 should fix this issue.

Failures:
 Creating library lib\ITKIOHDF5-5.0.lib and object lib\ITKIOHDF5-5.0.exp
itkHDF5ImageIO.cxx.obj : error LNK2019: unresolved external symbol _H5open referenced in function "public: virtual bool __thiscall itk::HDF5ImageIO::CanReadFile(char const *)" (?CanReadFile@HDF5ImageIO@itk@@UAE_NPBD@Z)
itkHDF5ImageIO.cxx.obj : error LNK2019: unresolved external symbol _H5check_version referenced in function "public: virtual bool __thiscall itk::HDF5ImageIO::CanReadFile(char const *)" (?CanReadFile@HDF5ImageIO@itk@@UAE_NPBD@Z)
itkHDF5ImageIO.cxx.obj : error LNK2019: unresolved external symbol _H5Aexists referenced in function __catch$?Write@HDF5ImageIO@itk@@UAEXPBX@Z$3
itkHDF5ImageIO.cxx.obj : error LNK2019: unresolved external symbol _H5Fis_hdf5 referenced in function "public: virtual bool __thiscall itk::HDF5ImageIO::CanReadFile(char const *)" (?CanReadFile@HDF5ImageIO@itk@@UAE_NPBD@Z)
itkHDF5ImageIO.cxx.obj : error LNK2019: unresolved external symbol "public: char const * __thiscall H5::Exception::getCDetailMsg(void)const " (?getCDetailMsg@Exception@H5@@QBEPBDXZ) referenced in function __catch$?ReadImageInformation@HDF5ImageIO@itk@@UAEXXZ$0
itkHDF5ImageIO.cxx.obj : error LNK2019: unresolved external symbol "public: class H5::IdComponent & __thiscall H5::IdComponent::operator=(class H5::IdComponent const &)" (??4IdComponent@H5@@QAEAAV01@ABV01@@Z) referenced in function "public: class H5::H5Location & __thiscall H5::H5Location::operator=(class H5::H5Location const &)" (??4H5Location@H5@@QAEAAV01@ABV01@@Z)

**Comment by PhoebeHui** [comment]
The PR has been merged, please get latest source and try again.
