### ISSUE TITLE
 itk:x64-windows

### ISSUE THREAD

**Issue by ShaneKirkbride** [microsoft/vcpkg#9892]
**Host Environment**
- OS: Windows 10
- Compiler: Visual studio 2017

**To Reproduce**
 ./vcpkg install itk:x64-windows

**Failure logs** 
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v
    Working Directory: C:/src/vcpkg/buildtrees/itk/x64-windows-dbg
    See logs for more information:
      C:\src\vcpkg\buildtrees\itk\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:91 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/itk/portfile.cmake:67 (vcpkg_install_cmake)
  scripts/ports.cmake:94 (include)

Error: Building package itk:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: itk:x64-windows
  Vcpkg version: 2020.01.17-nohash
[config-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/4148894/config-x64-windows-dbg-out.log)
[config-x64-windows-dbg-err.log](https://github.com/microsoft/vcpkg/files/4148895/config-x64-windows-dbg-err.log)

**Additional context**
Let me know if you need anymore info!

**Comment by Neumann-A** [comment]
Wrong logs:
See logs for more information:
C:\src\vcpkg\buildtrees\itk\install-x64-windows-dbg-out.log

**Comment by Neumann-A** [comment]
If its the same error as in the other issue: ITK is not correctly linking against HDF5.

**Comment by PhoebeHui** [comment]
Confirmed, itk failed to link to HDF5, it's a same issue on x86-windows and x64-windows, duplicated this issue to https://github.com/microsoft/vcpkg/issues/9891
