### ISSUE TITLE
[ctemplate:x64-windows] build failure

### ISSUE THREAD

**Issue by jchdng** [microsoft/vcpkg#9896]
**Host Environment**
- OS: Windows 10
- Compiler: visual studio 2017 

**To Reproduce**
`./vcpkg install ctemplate:x64-windows`

**Failure logs** 
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: E:/vcpkg/downloads/tools/cmake-3.14.0-windows/cmake-3.14.0-win32-x86/bin/cmake.exe --build . --config Debug --target install -- -v
    Working Directory: E:/vcpkg/buildtrees/ctemplate/x64-windows-dbg
    See logs for more information:
      E:\vcpkg\buildtrees\ctemplate\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:91 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/ctemplate/portfile.cmake:22 (vcpkg_install_cmake)
  scripts/ports.cmake:90 (include)

Error: Building package ctemplate:x64-windows failed with: BUILD_FAILED

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/4153952/install-x64-windows-dbg-out.log)

**Comment by PhoebeHui** [comment]
@jchdng，thanks for reporting this issue, could you attach failure log E:\vcpkg\buildtrees\ctemplate\install-x64-windows-dbg-out.log?

**Comment by jchdng** [comment]
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/4153945/install-x64-windows-dbg-out.log)

**Comment by PhoebeHui** [comment]
@jchdng, thanks for attaching the logs, from your log, it seems that affected by other libraries, could you try the following steps to check what files it reference.

1. Open x64 Native Tools command 
2. Go to E:\vcpkg\buildtrees\ctemplate\src\1ec256a62b-c7b6f00c13
3. Execute 
cl.exe  /IE:\vcpkg\buildtrees\ctemplate\x64-windows-dbg\include   /TP -D_VARIADIC_MAX=10 -Dlibctemplate_EXPORTS -Iinclude /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1    /W3 /wd4005 /wd4996 /wd4018 /wd4025 -D_CRT_SECURE_NO_WARNINGS /showIncludes  /FS -c E:\vcpkg\buildtrees\ctemplate\src\1ec256a62b-c7b6f00c13\src\htmlparser\jsparser.cc
4. Check the include files

For me, The inlcude files is
Note: including file: F:\VCPKG\src\buildtrees\ctemplate\x64-windows-dbg\include\htmlparser/statemachine.h
Note: including file:  F:\VCPKG\src\buildtrees\ctemplate\x64-windows-dbg\include\config.h
Note: including file:   f:\vcpkg\src\buildtrees\ctemplate\x64-windows-dbg\include\windows/port.h
Note: including file:    f:\vcpkg\src\buildtrees\ctemplate\x64-windows-dbg\include\windows/config.h
Note: including file: F:\VCPKG\src\buildtrees\ctemplate\x64-windows-dbg\include\htmlparser/jsparser.h
Note: including file:  F:\VCPKG\src\buildtrees\ctemplate\x64-windows-dbg\include\config.h
Note: including file: F:\VCPKG\src\buildtrees\ctemplate\x64-windows-dbg\include\htmlparser/jsparser_fsm.h
[include files.txt](https://github.com/microsoft/vcpkg/files/4157332/include.files.txt)

**Comment by PhoebeHui** [comment]
@jchdng, please reopen this issue if it still be a problem for you.
