### ISSUE TITLE
How do I know what libraries are used in different build mode?

### ISSUE THREAD

**Issue by Lecanyu** [microsoft/vcpkg#9900]
Hi, I'm new to vcpkg and cmake. After installing a package, I'm wondering how to know what libraries (specific file_path) are used in debug and release build modes? 

For example, I installed Pangolin library by using `vcpkg.exe install pangolin`. 
Then I modified CMakeSettings.json in VS2017 and wrote a CMakeLists.txt file as 

> find_package(Pangolin REQUIRED)
include_directories(${Pangolin_INCLUDE_DIRS})
add_executable( visualizeGeometry visualizeGeometry.cpp )
target_link_libraries( visualizeGeometry ${Pangolin_LIBRARIES} )

My program can be built correctly, but it is crashed in debug and run normally in release. 
So I want to know what .lib files (specific paths) are linked when I build my codes in debug and release modes? I have printed out `message(STATUS ${Pangolin_LIBRARIES})`, it is always `pangolin` no matter what mode I use.

There are two types of libraries (debug and release). Will it automatically select according to build mode? 

Thanks!

**Comment by JackBoosY** [comment]
Hi @Lecanyu
The found libraries should be visible in the configuration log, but some ports doesn't print it, so you can use `message(${Pangolin_LIBRARIES})` to see it.

cmake will eventually choose to use the debug or release library according to the configuration. You can check which path the library is linked to in the build log. So no need to worry.

**Comment by JackBoosY** [comment]
If this issue is still not resolved, please reopen it.
