### ISSUE TITLE
[curl] x86-uwp build failure

### ISSUE THREAD

**Issue by jinpengxuan** [microsoft/vcpkg#9917]
Package: curl:x86-uwp
  Vcpkg version: 2020.01.18-nohash

**Comment by degski** [comment]
Just submitting I do NOT have the same error (triplet: windows-x64-static).

**Comment by aronyu79** [comment]
I have the same failure with x64-uwp

**Comment by PhoebeHui** [comment]
This issue have been fixed now, please get latest source and try again.

Starting package 3/3: curl:x86-uwp
Building package curl[core,non-http,openssl,ssl]:x86-uwp...
-- Using community triplet x86-uwp. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: F:\VCPKG\clean\triplets\community\x86-uwp.cmake
-- Using cached F:/VCPKG/clean/downloads/curl-curl-315ee3fe75dade912b48a21ceec9ccda0230d937.tar.gz
-- Cleaning sources at F:/VCPKG/clean/buildtrees/curl/src/da0230d937-b280319101.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source F:/VCPKG/clean/downloads/curl-curl-315ee3fe75dade912b48a21ceec9ccda0230d937.tar.gz
-- Applying patch 0002_fix_uwp.patch
-- Applying patch 0004_nghttp2_staticlib.patch
-- Applying patch 0005_remove_imp_suffix.patch
-- Applying patch 0006_fix_tool_depends.patch
-- Applying patch 0007_disable_tool_export_curl_target.patch
-- Applying patch 0009_fix_openssl_config.patch
-- Applying patch 0010_fix_othertests_cmake.patch
-- Applying patch 0011_fix_static_build.patch
-- Using source at F:/VCPKG/clean/buildtrees/curl/src/da0230d937-b280319101.clean
-- Configuring x86-uwp
-- Building x86-uwp-dbg
-- Building x86-uwp-rel
-- Installing: F:/VCPKG/clean/packages/curl_x86-uwp/share/curl/curl-config
-- Installing: F:/VCPKG/clean/packages/curl_x86-uwp/share/curl/vcpkg-cmake-wrapper.cmake
-- Installing: F:/VCPKG/clean/packages/curl_x86-uwp/share/curl/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package curl[core,non-http,openssl,ssl]:x86-uwp... done
Installing package curl[core,non-http,openssl,ssl]:x86-uwp...
Installing package curl[core,non-http,openssl,ssl]:x86-uwp... done
Elapsed time for package curl:x86-uwp: 5.43 min

Total elapsed time: 10.12 min

The package curl:x86-uwp provides CMake targets:

    find_package(CURL CONFIG REQUIRED)
    target_link_libraries(main PRIVATE CURL::libcurl)
