### ISSUE TITLE
icu:x64-windows build failure

### ISSUE THREAD

**Issue by lanksheard** [microsoft/vcpkg#9920]
**Host Environment**
- OS: Windows 10
- Compiler: VS 2019 16.4.4

**To Reproduce**
`./vcpkg install icu:x64-windows`

**Failure logs** 
Computing installation plan...
The following packages will be built and installed:
    icu[core]:x64-windows
Starting package 1/1: icu:x64-windows
Building package icu[core]:x64-windows...
-- Using cached C:/vcpkg/downloads/icu4c-65_1-src.tgz
-- Using source at C:/vcpkg/buildtrees/icu/src/c-65_1-src-702c9cff96
-- Acquiring MSYS Packages...
-- Acquiring MSYS Packages... OK
-- Configuring x64-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: C:/vcpkg/downloads/tools/msys2/msys64/usr/bin/bash.exe --noprofile --norc -c "C:/vcpkg/buildtrees/icu/src/c-65_1-src-702c9cff96/source/runConfigureICU MSYS/MSVC --disable-samples --disable-tests --enable-static --disable-shared --host=i686-pc-mingw32 --disable-debug --enable-release --prefix=C:/vcpkg/packages/icu_x64-windows"
    Working Directory: C:/vcpkg/buildtrees/icu/x64-windows-rel
    Error code: 1
    See logs for more information:
      C:\vcpkg\buildtrees\icu\configure-x64-windows-rel-out.log
      C:\vcpkg\buildtrees\icu\configure-x64-windows-rel-err.log

Call Stack (most recent call first):
  ports/icu/portfile.cmake:102 (vcpkg_execute_required_process)
  scripts/ports.cmake:90 (include)

Error: Building package icu:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: icu:x64-windows
  Vcpkg version: 2020.01.18-nohash-external
[configure-x64-windows-rel-err.log](https://github.com/microsoft/vcpkg/files/4158387/configure-x64-windows-rel-err.log)
[configure-x64-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/4158388/configure-x64-windows-rel-out.log)

**Comment by FrankHeimes** [comment]
I probably ran into the same problem, albeit with a small twist.
In my case, configuration of `x64-windows-rel` succeeds, only configuration of `x64-windows-dbg` detects `checking whether we are cross compiling... yes` and fails with error 
```
configure: error: Error! Cross compiling but no --with-cross-build option specified - please supply the path to an executable ICU's build root
```
Why does configure behave differently for `debug` and `release` and is there a workaround?

This is stalling my build of all dependent x64-windows builds!

**Comment by PhoebeHui** [comment]
@lanksheard, could you get latest vcpkg source and try to build icu again? I can't repro this issue, icu:x64-windows build successfully for me.

From you config log, it seems that you enable static build when build icu:x64-windows which should be disabled.

![image](https://user-images.githubusercontent.com/20694052/73848892-f35ad580-4863-11ea-839c-d3cde87d342e.png)

**Comment by FrankHeimes** [comment]
> @lanksheard, could you get latest vcpkg source and try to build icu again? I can't repro this issue, icu:x64-windows build successfully for me.
> 
> From you config log, it seems that you enable static build when build icu:x64-windows which should be disabled.

@PhoebeHui
1) About two hours ago, I updated the entire vcpkg code base and rebuild vcpkg.exe.
2) Yes, you are right and I also try to create a static library for ICU (`VCPKG_LIBRARY_LINKAGE` = `static`) because I need the dependent libraries to be static. Why does this work for x86 but not for x64? And I can also build ICU with the triplets `x86-windows-static` and `x64-windows-static`, which set both linkage types to `static`.

Any hints on how I can hook into the `checking whether we are cross compiling...` test to figure out why it is returning `yes` or `no`?

**Comment by timautry** [comment]
Hi @lanksheard  @PhoebeHui @FrankHeimes ,

I always use the x64-windows triplet the environment variable "(**set VCPKG_DEFAULT_TRIPLET=x64-windows**)" which has crt and library linkage default of dynamic, but some packages, and I believe ICU is one of many, that only supports static linkage and overrides any other selection you may make.
Those packages always give me some type of message to this effect:

Building package spirv-tools[core]:x64-windows...
-- Note: spirv-tools only supports static library linkage. Building static library.

Don't know if this helps the understanding of how vcpkg package works in this area???

**Comment by lanksheard** [comment]
Hi @PhoebeHui @FrankHeimes ,
I forgot to mention that static is the setting for my x64-windows and x86-windows. It's a requirement at my site. Also I have 2 other machines that this builds without issue.

**Comment by degski** [comment]
Just submitting I have the same error.

**Comment by FrankHeimes** [comment]
I found a problem and a workaround. I'm using Visual Studio 2019, Version 16.4.4, which has an unresolved configuration issue for `Debug|x64`, see: [com-objects-fail-to-register-on-x64](https://developercommunity.visualstudio.com/content/problem/903206/com-objects-fail-to-register-on-x64.html)

When installed on a virgin Windows 10 system, the Visual Studio setup does not install the debug versions of the runtime anywhere on the system PATH, making them unavailable to other tools (like regsvr32.exe)

A workaround for the ICU project is to copy all DLLs from the following folders
```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Redist\MSVC\14.24.28127\debug_nonredist\x64\Microsoft.VC142.DebugCRT
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Redist\MSVC\14.24.28127\debug_nonredist\x64\Microsoft.VC142.DebugCXXAMP
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Redist\MSVC\14.24.28127\debug_nonredist\x64\Microsoft.VC142.DebugMFC
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Redist\MSVC\14.24.28127\debug_nonredist\x64\Microsoft.VC142.DebugOpenMP
C:\Program Files (x86)\Windows Kits\10\bin\10.0.18362.0\x64\ucrt
```
to `vcpkg\downloads\tools\powershell-core-6.2.1-windows`, which is created by `vcpkg` while building the packages. You may have to adjust the toolset and Windows Kits versions in those paths.

After having done that, `icu:x64-windows` installed successfully (even with `VCPKG_LIBRARY_LINKAGE` = `static`).

@lanksheard You may want to have a close look at the contents of `vcpkg\buildtrees\icu\x64-windows-rel\config.log`. That should contain the exact error message from the compilation attempt during configuration.

**Comment by degski** [comment]
@FrankHeimes Wouldn't it be simpler to install a VS19 (x86/x64) redistributable c-runtime explicitely from https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads ?

**Comment by FrankHeimes** [comment]
> @FrankHeimes Wouldn't it be simpler to install a VS19 (x86/x64) redistributable c-runtime explicitely from https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads ?

No, that doesn't help. It's a problem with the _debug_ DLLs that are not included in the C++ redistributables.

The `VC_redist.x64.exe` setup contains these files: `api_ms_win_*, concrt140.dll, mfc140.dll, mfc140???.dll, mfc140u.dll, mfcm140.dll, mfcm140u.dll, msvcp140.dll, msvcp140_1.dll, msvcp140_2.dll, msvcp140_codecvt_ids.dll, ucrtbase.dll, vcamp140.dll, vccorlib140.dll, vcomp140.dll, vcruntime140.dll, vcruntime140_1.dll`

**Comment by oracleoftroy** [comment]
I've also been having problems getting icu to build and I am not forcing a static build (and the log correctly reports it was trying to build the shared library. I tried @FrankHeimes trick of copying the dlls, but that didn't work for me (in fact, it caused my build to fail faster). I also tried deleting all icu related downloads and build folders, with no avail. I always run bootstrap-vcpkg.bat when I see a toolsrc change, so this is with the most recent updates.

I then tried cloning a fresh vcpkg repo, ran bootstrap, built icu, and that _did_ work. So something about building it from a longstanding vcpkg repo is messing with the build. So back in the original vcpkg dir, I then tried deleting folders used by the build process that are in .gitignore: buildtrees, downloads, packages, and any build folders under toolsrc. I reran bootstrap and built icu, which worked after that.

My guess is something about the vcpkg buildchain was out of date and not properly upgraded by some update of vcpkg.exe, but I didn't narrow it down beyond. I have a laptop I've been avoiding updating because of this, so now that I have a workaround, I might try to see if I can reproduce and narrow it down when I have time.

**Comment by lanksheard** [comment]
After trying the suggestions, I found out there is more wrong with this machine that I hadn't noticed. Other thins were building incorrectly, or not building. I tried reinstalling VS2019 which didn't help.
Thanks for all your help.
 -- doug

**Comment by FrankHeimes** [comment]
> After trying the suggestions, I found out there is more wrong with this machine that I hadn't noticed. Other thins were building incorrectly, or not building. I tried reinstalling VS2019 which didn't help.

I updated our build agents several times without reinstalling Windows itself. I found it most feasible to uninstall as much as possible and then let the Visual Studio installer (re)install everything necessary.
To do so, I uninstall these items in the order listed before installing a new major Visual Studio version:
1. Microsoft Visual Studio Installer
2. Visual Studio Enterprise 2015
3. Visual Studio Enterprise 2017
4. Windows Software Development Kit - Windows …
5. Microsoft .NET Core SDK … (except 2.1.700)
6. Microsoft Visual Studio Team Foundation Server 2015 Power Tools
7. Microsoft .NET Framework …
8. Microsoft Visual C++ 2010/2012/2013/2015 …
9. Microsoft Silverlight
10. Microsoft SQL Server … LocalDB (except 2016)

If messages pop up warning about dependencies, I abort that particular deinstallation and continue with the list. I repeat steps 1 to 10 until most of it is gone.

Another gotcha is C:\Windows\Temp. That folder sometimes mysteriously vanishes or its security settings get screwed up. That folder must exist and you may have to grant yourself write access to it.
Some setups abort with errors 2502 or 2503, the reason being that these cannot create a log in C:\Windows\Temp.

**Comment by guillermoacdc** [comment]
Hello guys!

Same error but reached installing QT

**Host Environment**

OS: Windows 10
Compiler: VS 2019 16.9.2

**To Reproduce**
Steps to reproduce the behavior:
vcpkg install qt5-base:x64-windows


**Failure log**
Microsoft Windows [Versión 10.0.19041.867]
(c) 2020 Microsoft Corporation. Todos los derechos reservados.


C:\src\vcpkg-master>vcpkg install qt5-base:x64-windows
Computing installation plan...
The following packages will be built and installed:
  * brotli[core]:x64-windows
  * double-conversion[core]:x64-windows
  * egl-registry[core]:x64-windows
  * freetype[bzip2,core,png]:x64-windows
  * harfbuzz[core]:x64-windows
  * icu[core]:x64-windows
  * libjpeg-turbo[core]:x64-windows
  * libpq[core,openssl,zlib]:x64-windows
  * pcre2[core]:x64-windows
    qt5-base[core]:x64-windows
  * ragel[core]:x64-windows
  * sqlite3[core]:x64-windows
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Starting package 1/12: brotli:x64-windows
Building package brotli[core]:x64-windows...
Could not locate cached archive: C:\Users\guill\AppData\Local\vcpkg\archives\8f\8f3e962800dfe50e0fe7950107073bc288bd9294.zip
-- Downloading https://github.com/google/brotli/archive/e61745a6b7add50d380cfd7d3883dd6c62fc2c71.tar.gz...
-- Extracting source C:/src/vcpkg-master/downloads/google-brotli-e61745a6b7add50d380cfd7d3883dd6c62fc2c71.tar.gz
-- Applying patch install.patch
-- Applying patch fix-arm-uwp.patch
-- Applying patch pkgconfig.patch
-- Using source at C:/src/vcpkg-master/buildtrees/brotli/src/6c62fc2c71-a8c4ea9278.clean
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Using msys root at C:/src/vcpkg-master/downloads/tools/msys2/c809757c94447846
-- Fixing pkgconfig file: C:/src/vcpkg-master/packages/brotli_x64-windows/lib/pkgconfig/libbrotlicommon.pc
-- Fixing pkgconfig file: C:/src/vcpkg-master/packages/brotli_x64-windows/lib/pkgconfig/libbrotlidec.pc
-- Fixing pkgconfig file: C:/src/vcpkg-master/packages/brotli_x64-windows/lib/pkgconfig/libbrotlienc.pc
-- Fixing pkgconfig file: C:/src/vcpkg-master/packages/brotli_x64-windows/debug/lib/pkgconfig/libbrotlicommon.pc
-- Fixing pkgconfig file: C:/src/vcpkg-master/packages/brotli_x64-windows/debug/lib/pkgconfig/libbrotlidec.pc
-- Fixing pkgconfig file: C:/src/vcpkg-master/packages/brotli_x64-windows/debug/lib/pkgconfig/libbrotlienc.pc
-- Installing: C:/src/vcpkg-master/packages/brotli_x64-windows/share/brotli/copyright
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: C:\Users\guill\AppData\Local\vcpkg\archives\8f\8f3e962800dfe50e0fe7950107073bc288bd9294.zip
Building package brotli[core]:x64-windows... done
Installing package brotli[core]:x64-windows...
Installing package brotli[core]:x64-windows... done
Elapsed time for package brotli:x64-windows: 38.8 s
Starting package 2/12: double-conversion:x64-windows
Building package double-conversion[core]:x64-windows...
Could not locate cached archive: C:\Users\guill\AppData\Local\vcpkg\archives\b4\b493a6f8cff4b31b826b2aa66040aad173df168d.zip
-- Note: double-conversion only supports static library linkage. Building static library.
-- Downloading https://github.com/google/double-conversion/archive/v3.1.5.tar.gz...
-- Extracting source C:/src/vcpkg-master/downloads/google-double-conversion-v3.1.5.tar.gz
-- Using source at C:/src/vcpkg-master/buildtrees/double-conversion/src/v3.1.5-d04c588b2e.clean
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: C:\Users\guill\AppData\Local\vcpkg\archives\b4\b493a6f8cff4b31b826b2aa66040aad173df168d.zip
Building package double-conversion[core]:x64-windows... done
Installing package double-conversion[core]:x64-windows...
Installing package double-conversion[core]:x64-windows... done
Elapsed time for package double-conversion:x64-windows: 49.1 s
Starting package 3/12: egl-registry:x64-windows
Building package egl-registry[core]:x64-windows...
Could not locate cached archive: C:\Users\guill\AppData\Local\vcpkg\archives\69\698c19207287567d57850fae4b5a807f9e1e0414.zip
-- Downloading https://github.com/KhronosGroup/EGL-Registry/archive/11478904448bbdf5757b798c856a525aa2b351b1.tar.gz...
-- Extracting source C:/src/vcpkg-master/downloads/KhronosGroup-EGL-Registry-11478904448bbdf5757b798c856a525aa2b351b1.tar.gz
-- Using source at C:/src/vcpkg-master/buildtrees/egl-registry/src/5aa2b351b1-2a8c3e3154.clean
-- Installing: C:/src/vcpkg-master/packages/egl-registry_x64-windows/share/egl-registry/copyright
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: C:\Users\guill\AppData\Local\vcpkg\archives\69\698c19207287567d57850fae4b5a807f9e1e0414.zip
Building package egl-registry[core]:x64-windows... done
Installing package egl-registry[core]:x64-windows...
Installing package egl-registry[core]:x64-windows... done
Elapsed time for package egl-registry:x64-windows: 14.7 s
Starting package 4/12: freetype:x64-windows
Building package freetype[bzip2,core,png]:x64-windows...
Could not locate cached archive: C:\Users\guill\AppData\Local\vcpkg\archives\d0\d052a93b575defd2a6883bde584ea1cdbf318313.zip
-- Downloading https://download-mirror.savannah.gnu.org/releases/freetype/freetype-2.10.2.tar.xz...
-- Extracting source C:/src/vcpkg-master/downloads/freetype-2.10.2.tar.xz
-- Applying patch 0001-Fix-install-command.patch
-- Applying patch 0003-Fix-UWP.patch
-- Applying patch pkgconfig.patch
-- Applying patch brotli-static.patch
-- Using source at C:/src/vcpkg-master/buildtrees/freetype/src/2.10.2-c111da3ccb.clean
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Using msys root at C:/src/vcpkg-master/downloads/tools/msys2/c809757c94447846
-- Fixing pkgconfig file: C:/src/vcpkg-master/packages/freetype_x64-windows/lib/pkgconfig/freetype2.pc
-- Fixing pkgconfig file: C:/src/vcpkg-master/packages/freetype_x64-windows/debug/lib/pkgconfig/freetype2.pc
-- Installing: C:/src/vcpkg-master/packages/freetype_x64-windows/share/freetype/copyright
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: C:\Users\guill\AppData\Local\vcpkg\archives\d0\d052a93b575defd2a6883bde584ea1cdbf318313.zip
Building package freetype[bzip2,core,png]:x64-windows... done
Installing package freetype[bzip2,core,png]:x64-windows...
Installing package freetype[bzip2,core,png]:x64-windows... done
Elapsed time for package freetype:x64-windows: 38.34 s
Starting package 5/12: ragel:x64-windows
Building package ragel[core]:x64-windows...
Could not locate cached archive: C:\Users\guill\AppData\Local\vcpkg\archives\90\90f4055aab31c3dae98e1002b37c15c4623a4c8f.zip
-- Downloading http://www.colm.net/files/ragel/ragel-6.10.tar.gz...
-- Extracting source C:/src/vcpkg-master/downloads/ragel-6.10.tar.gz
-- Applying patch 0001-remove-unistd-h.patch
-- Using source at C:/src/vcpkg-master/buildtrees/ragel/src/ragel-6-655d7c9ccd.clean
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: C:\Users\guill\AppData\Local\vcpkg\archives\90\90f4055aab31c3dae98e1002b37c15c4623a4c8f.zip
Building package ragel[core]:x64-windows... done
Installing package ragel[core]:x64-windows...
Installing package ragel[core]:x64-windows... done
Elapsed time for package ragel:x64-windows: 1.241 min
Starting package 6/12: harfbuzz:x64-windows
Building package harfbuzz[core]:x64-windows...
Could not locate cached archive: C:\Users\guill\AppData\Local\vcpkg\archives\54\54b3509b16ea77e132dc38209769df3301def577.zip
-- Downloading https://github.com/harfbuzz/harfbuzz/archive/2.6.6.tar.gz...
-- Extracting source C:/src/vcpkg-master/downloads/harfbuzz-harfbuzz-2.6.6.tar.gz
-- Applying patch 0001-fix-cmake-export.patch
-- Applying patch 0002-fix-uwp-build.patch
-- Applying patch 0003-remove-broken-test.patch
-- Applying patch find-package-freetype-2.patch
-- Applying patch glib-cmake.patch
-- Applying patch fix_include.patch
-- Using source at C:/src/vcpkg-master/buildtrees/harfbuzz/src/2.6.6-6db14e87dc.clean
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Installing: C:/src/vcpkg-master/packages/harfbuzz_x64-windows/share/harfbuzz/copyright
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: C:\Users\guill\AppData\Local\vcpkg\archives\54\54b3509b16ea77e132dc38209769df3301def577.zip
Building package harfbuzz[core]:x64-windows... done
Installing package harfbuzz[core]:x64-windows...
Installing package harfbuzz[core]:x64-windows... done
Elapsed time for package harfbuzz:x64-windows: 2.071 min
Starting package 7/12: icu:x64-windows
Building package icu[core]:x64-windows...
Could not locate cached archive: C:\Users\guill\AppData\Local\vcpkg\archives\a5\a5b22b718bbb505d17f4a3cae854b599b5752f5e.zip
-- Downloading https://github.com/unicode-org/icu/releases/download/release-67-1/icu4c-67_1-src.tgz...
-- Extracting source C:/src/vcpkg-master/downloads/icu4c-67_1-src.tgz
-- Applying patch C:/src/vcpkg-master/ports/icu/disable-escapestr-tool.patch
-- Applying patch C:/src/vcpkg-master/ports/icu/remove-MD-from-configure.patch
-- Applying patch C:/src/vcpkg-master/ports/icu/fix_parallel_build_on_windows.patch
-- Applying patch C:/src/vcpkg-master/ports/icu/fix-extra.patch
-- Using source at C:/src/vcpkg-master/buildtrees/icu/src/c-67_1-src-39ba50b26e.clean
-- Downloading https://www.python.org/ftp/python/3.8.3/python-3.8.3-embed-amd64.zip...
-- Downloading https://repo.msys2.org/msys/x86_64/bash-4.4.023-2-x86_64.pkg.tar.xz...
-- Downloading https://repo.msys2.org/msys/x86_64/diffutils-3.7-1-x86_64.pkg.tar.xz...
-- Downloading https://repo.msys2.org/msys/x86_64/coreutils-8.32-1-x86_64.pkg.tar.xz...
-- Downloading https://repo.msys2.org/msys/x86_64/grep-3.0-2-x86_64.pkg.tar.xz...
-- Downloading https://repo.msys2.org/msys/x86_64/sed-4.8-1-x86_64.pkg.tar.xz...
-- Downloading https://repo.msys2.org/msys/x86_64/libpcre-8.44-1-x86_64.pkg.tar.xz...
-- Downloading https://repo.msys2.org/msys/x86_64/gawk-5.1.0-1-x86_64.pkg.tar.xz...
-- Downloading https://repo.msys2.org/msys/x86_64/mpfr-4.1.0-1-x86_64.pkg.tar.zst...
-- Downloading https://repo.msys2.org/msys/x86_64/gmp-6.2.0-1-x86_64.pkg.tar.xz...
-- Downloading https://repo.msys2.org/msys/x86_64/libreadline-8.0.004-1-x86_64.pkg.tar.xz...
-- Downloading https://repo.msys2.org/msys/x86_64/ncurses-6.2-1-x86_64.pkg.tar.xz...
-- Downloading https://repo.msys2.org/msys/x86_64/automake1.15-1.15.1-1-any.pkg.tar.xz...
-- Downloading https://repo.msys2.org/msys/x86_64/automake1.15-1.15.1-1-any.pkg.tar.xz... Failed. Status: 22;"HTTP response code said error"
-- Downloading https://www2.futureware.at/~nickoe/msys2-mirror/msys/x86_64/automake1.15-1.15.1-1-any.pkg.tar.xz...
-- Downloading https://www2.futureware.at/~nickoe/msys2-mirror/msys/x86_64/automake1.15-1.15.1-1-any.pkg.tar.xz... Failed. Status: 22;"HTTP response code said error"
-- Downloading https://mirror.yandex.ru/mirrors/msys2/msys/x86_64/automake1.15-1.15.1-1-any.pkg.tar.xz...
-- Downloading https://mirror.yandex.ru/mirrors/msys2/msys/x86_64/automake1.15-1.15.1-1-any.pkg.tar.xz... Failed. Status: 22;"HTTP response code said error"
-- Downloading https://mirrors.tuna.tsinghua.edu.cn/msys2/msys/x86_64/automake1.15-1.15.1-1-any.pkg.tar.xz...
-- Downloading https://mirrors.tuna.tsinghua.edu.cn/msys2/msys/x86_64/automake1.15-1.15.1-1-any.pkg.tar.xz... Failed. Status: 22;"HTTP response code said error"
-- Downloading https://mirrors.ustc.edu.cn/msys2/msys/x86_64/automake1.15-1.15.1-1-any.pkg.tar.xz...
-- Downloading https://mirrors.ustc.edu.cn/msys2/msys/x86_64/automake1.15-1.15.1-1-any.pkg.tar.xz... Failed. Status: 22;"HTTP response code said error"
-- Downloading https://mirror.bit.edu.cn/msys2/msys/x86_64/automake1.15-1.15.1-1-any.pkg.tar.xz...
-- Downloading https://mirror.bit.edu.cn/msys2/msys/x86_64/automake1.15-1.15.1-1-any.pkg.tar.xz... Failed. Status: 7;"Couldn't connect to server"
-- Downloading https://mirror.selfnet.de/msys2/msys/x86_64/automake1.15-1.15.1-1-any.pkg.tar.xz...
-- Downloading https://mirror.selfnet.de/msys2/msys/x86_64/automake1.15-1.15.1-1-any.pkg.tar.xz... Failed. Status: 22;"HTTP response code said error"
-- Downloading https://mirrors.sjtug.sjtu.edu.cn/msys2/msys/x86_64/automake1.15-1.15.1-1-any.pkg.tar.xz...
-- Downloading https://mirrors.sjtug.sjtu.edu.cn/msys2/msys/x86_64/automake1.15-1.15.1-1-any.pkg.tar.xz... Failed. Status: 22;"HTTP response code said error"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:181 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_acquire_msys.cmake:87 (vcpkg_download_distfile)
  scripts/cmake/vcpkg_acquire_msys.cmake:125 (msys_package_download)
  scripts/cmake/vcpkg_acquire_msys.cmake:246 (msys_package)
  ports/icu/portfile.cmake:80 (vcpkg_acquire_msys)
  scripts/ports.cmake:79 (include)


Error: Building package icu:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: icu:x64-windows
  Vcpkg version: 2020.06.15-nohash

Additionally, attach any relevant sections from the log files above.

C:\src\vcpkg-master>.\vcpkg update
Using local portfile versions. To update the local portfiles, use `git pull`.
No packages need updating.

C:\src\vcpkg-master>

**Comment by PhoebeHui** [comment]
@guillermoacdc, this issue has been fixed, please get latest source and try again, and please open a new issue if it still be a problem for you.
