### ISSUE TITLE
System-wide integration affects build time of projects not using vcpkg.

### ISSUE THREAD

**Issue by stinos** [microsoft/vcpkg#9921]
System-wide integration causes the AppLocalFromInstalled target to be called for commandline builds for all projects even if they are up-to-date. AppLocalFromInstalled invokes Powershell, which is a relatively slow process to start (ranging from 500-1000mSec depending on version and machine). As such for some of the builds we do this becomes a pretty time-consuming thing and builds with many projects now take a considerable amount of extra time.

**Proposed solution**
- VcpkgEnabled could default to False and projects which actually do use vcpkg would be required to have VcpkgEnabled set to true. This would break existing builds, but it could be opt-in when calling vcpkg integrate so it doesn't break anything and people who want their builds to be normal again can use it
- detect whether a project uses vcpkg and do not call AppLocalFromInstalled unless that is the case. This is what happens for builds in VS as well (but possibly using the file tracker which isn't usable in msbuild?)
- detect if a project was actually built, and opnly then call AppLocalFromInstalled otherwise skip it

**Describe alternatives you've considered**
Running builds with VcpkgEnabled=False and manually modifying individual project files which do use vcpkg to set it to True again.

**Comment by timautry** [comment]
@stinos I'm no expert on vcpkg by any means, but I have a thought/suggestion which works quit well for me, especially if you want to have multiple versions of Visual Studio  such as vs2015, vs2017, vs2019, or a new beta version of VC++ and and multiple instances of vcpkg such as dev, test, qa, prod, etc...

- 1. One can remove the System-Wide integration (**./vcpkg integrate remove**) 
- 2. Then create the vcpkg nupkg module (**vcpkg integrate project**).
- 3. On projects you want to use vcpkg add the nupkg project by using the following:
    - With a project open, go to Tools->NuGet Package Manager->Package Manager Console and paste:
     - (**Install-Package** _vcpkg.D.Git.vs2017.test_ **-Source** _"D:\Git\vs2017.test\scripts\buildsystems"_)
Of course the _italicized__ will be different depending on where the vcpkg(s) is/are installed.

The only drawback I would see is if one has many projects already using vcpkg under the system-wide integration one would need to go back and add the vcpkg integrate project "nupkg" to each one and recompile.

**Comment by stinos** [comment]
I admit I haven't looked into the NuGet way so I didn't list it as alternative indeed.

> Of course the italicized_ will be different depending on where the vcpkg(s) is/are installed

But it's not this different across machines, right? I.e. if I install the NuGet package into one project on one machine, will it just also work for that project on another machine which has vcpkg in a different location?

**Comment by timautry** [comment]
The experts (@JackBoosY @PhoebeHui  @LilyWangL  @Neumann-A as I see them contribute a lot to this overall project) would know more about this than me, but my thoughts would be if vcpkg is not installed in the same location on each PC, then it would seem logical to assume (I hate assuming) one  after porting to another PC, would need to delete the nupkg for vcpkg in the project and add the nupkg for vcpkg to the installed location on the new machine.

It also seems the "vcpkg integrate project" is only available on a windows PC, as the option does not appear on my linux machine.

**Comment by stinos** [comment]
>  it would seem logical

Not very logical to me actually, as it serisouly reduces usability since it makes it way too hard to share code and have it in version control. But I tested it and yes that's basically how it works (unless I missed something). Could be circumvented by using msbuild variables/manually changing package names and whatnot, but that's really not so ideal.

**Comment by JackBoosY** [comment]
@ras0219-msft What do you think?

**Comment by timautry** [comment]
@stinos - I agree, not so ideal :( 
Most software designs are with a corporate mindset, meaning the PCs are setup identical following some kind of standards devised by the corporation or in case of purchased software the software vendor.

Unfortunately that usually does not cater too well to open source projects which are shared among corporations having different standards, freelancers, hobbyists, educational and just plain enthusiasts.

**Comment by BillyONeal** [comment]
I believe the proposed change would be breaking enough that we would not want to do that.

**Comment by stinos** [comment]
@BillyONeal I assume you mean the first of the three propsed changes? As said it can be opt-in so then it's not really breaking anymore.

**Comment by BillyONeal** [comment]
@stinos I don't believe any of the proposed alternatives are workable but I might not understand the last one.

* The first is out because it's a massive compatibility break (it breaks the whole `integrate install` feature for most customers).
* The second requires a time machine -- we don't know whether a project is using vcpkg until we run the step you consider problematic to determine that, since normally we put things on the include path and the 'does this project use vcpkg' test is whether they included a header vcpkg provides in any of their source files.
* I don't really understand what the third tries to do but it sounds an awful lot like the same time machine problem as the second.

Moreover we provide nuget-package powered solutions as well as explicit inclusion of `vcpkg.targets` from projects that want to use such functionality as workarounds if you don't want to use the system-wide installer.

**Comment by stinos** [comment]
@BillyONeal to clarify:

> The first is out because it's a massive compatibility break (it breaks the whole integrate install feature for most customers).

I'm suggesting to make it opt-in via an argument to `integrate install` so it doesn't break anything unless explicitly asked for.

> the 'does this project use vcpkg' test is whether they included a header vcpkg provides in any of their source files.

Ok clear, thanks.

> I don't really understand what the third tries to do but it sounds an awful lot like the same time machine problem as the second.

Not sure if tit's the same: it's a suggestion to skip the `AppLocalFromInstalled` target if outputs are up-to-date, i.e. just like ClCompile and Link targets. And just like Visual Studio behaves: if a project has been built already and is built again, all build steps are just skipped. But if a binary copied by vcpkg gets deleted from the output directory, VS detects that and runs a build again.

**Comment by BillyONeal** [comment]
> I'm suggesting to make it opt-in via an argument to `integrate install` so it doesn't break anything unless explicitly asked for.

OH! Sure, we could do that.

>it's a suggestion to skip the AppLocalFromInstalled target if outputs are up-to-date

To do that you have to declare the outputs before the target runs, but we don't know what the outputs are before running the script.

**Comment by stinos** [comment]
> To do that you have to declare the outputs before the target runs, but we don't know what the outputs are before running the script.

Yeah I sort of exepcted that, but VS gets it right so I assume that's only because it uses the filetracker mechanism?

**Comment by BillyONeal** [comment]
I admit to not being super clear on how the file tracker mechanism works :). But my understanding is that that is only for tracking *inputs* (e.g. headers consumed by your C++ file), not, as here, *outputs*. I suppose we could drop a sentinel file "lastvcpkgcopysucceeded.txt" or similar to be able to declare an output.

**Comment by BillyONeal** [comment]
I've been working on a powershell-less replacement for applocal.ps1 and was able to repro the delay. Consider the following, with vcpkg enabled it takes 2 seconds, without it takes 1 second, at least on my Blade 14:

![image](https://user-images.githubusercontent.com/1544943/124410276-fbd86980-dcfe-11eb-885b-5e26aa5a2e97.png)

[NotVcpkgDemo.zip](https://github.com/microsoft/vcpkg/files/6761233/NotVcpkgDemo.zip)

```
C:\Users\billy\source\repos>msbuild NotVcpkgDemo\NotVcpkgDemo.sln /p:Platform=x64 /p:Configuration=Debug /t:Rebuild /p:VcpkgEnabled=false
Microsoft (R) Build Engine version 16.11.0-preview-21302-05+5e37cc992 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
Build started 7/4/2021 7:35:49 PM.
Project "C:\Users\billy\source\repos\NotVcpkgDemo\NotVcpkgDemo.sln" on node 1 (Rebuild target(s)).
ValidateSolutionConfiguration:
  Building solution configuration "Debug|x64".
Project "C:\Users\billy\source\repos\NotVcpkgDemo\NotVcpkgDemo.sln" (1) is building "C:\Users\billy\source\repos\NotVcp
kgDemo\NotVcpkgDemo\NotVcpkgDemo.vcxproj" (2) on node 1 (Rebuild target(s)).
CoreClean:
  Creating directory "x64\Debug\".
PrepareForBuild:
  Creating directory "C:\Users\billy\source\repos\NotVcpkgDemo\x64\Debug\".
  Creating directory "x64\Debug\NotVcpkgDemo.tlog\".
InitializeBuildStatus:
  Creating "x64\Debug\NotVcpkgDemo.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
VcpkgTripletSelection:
  Not using Vcpkg because VcpkgEnabled is "false"
ClCompile:
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.29.30130\bin\HostX86\x64\CL.exe /c /ZI /
  JMC /nologo /W3 /WX- /diagnostics:column /sdl /Od /D _DEBUG /D _CONSOLE /D _UNICODE /D UNICODE /Gm- /EHsc /RTC1 /MDd
  /GS /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"x64\Debug\\" /Fd"x64\Debug\vc142.pdb" /external:
  env:EXTERNAL_INCLUDE /external:W3 /Gd /TP /FC /errorReport:queue NotVcpkgDemo.cpp
  NotVcpkgDemo.cpp
Link:
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.29.30130\bin\HostX86\x64\link.exe /ERROR
  REPORT:QUEUE /OUT:"C:\Users\billy\source\repos\NotVcpkgDemo\x64\Debug\NotVcpkgDemo.exe" /INCREMENTAL /ILK:"x64\Debug\
  NotVcpkgDemo.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.
  lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manife
  st:embed /DEBUG /PDB:"C:\Users\billy\source\repos\NotVcpkgDemo\x64\Debug\NotVcpkgDemo.pdb" /SUBSYSTEM:CONSOLE /TLBID:
  1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:\Users\billy\source\repos\NotVcpkgDemo\x64\Debug\NotVcpkgDemo.lib" /MACHINE:X64 x
  64\Debug\NotVcpkgDemo.obj
  NotVcpkgDemo.vcxproj -> C:\Users\billy\source\repos\NotVcpkgDemo\x64\Debug\NotVcpkgDemo.exe
FinalizeBuildStatus:
  Deleting file "x64\Debug\NotVcpkgDemo.tlog\unsuccessfulbuild".
  Touching "x64\Debug\NotVcpkgDemo.tlog\NotVcpkgDemo.lastbuildstate".
Done Building Project "C:\Users\billy\source\repos\NotVcpkgDemo\NotVcpkgDemo\NotVcpkgDemo.vcxproj" (Rebuild target(s)).

Done Building Project "C:\Users\billy\source\repos\NotVcpkgDemo\NotVcpkgDemo.sln" (Rebuild target(s)).


Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:01.09

C:\Users\billy\source\repos>msbuild NotVcpkgDemo\NotVcpkgDemo.sln /p:Platform=x64 /p:Configuration=Debug /t:Rebuild /p:VcpkgEnabled=true
Microsoft (R) Build Engine version 16.11.0-preview-21302-05+5e37cc992 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
Build started 7/4/2021 7:35:53 PM.
Project "C:\Users\billy\source\repos\NotVcpkgDemo\NotVcpkgDemo.sln" on node 1 (Rebuild target(s)).
ValidateSolutionConfiguration:
  Building solution configuration "Debug|x64".
Project "C:\Users\billy\source\repos\NotVcpkgDemo\NotVcpkgDemo.sln" (1) is building "C:\Users\billy\source\repos\NotVcp
kgDemo\NotVcpkgDemo\NotVcpkgDemo.vcxproj" (2) on node 1 (Rebuild target(s)).
_PrepareForClean:
  Deleting file "x64\Debug\NotVcpkgDemo.tlog\NotVcpkgDemo.lastbuildstate".
InitializeBuildStatus:
  Creating "x64\Debug\NotVcpkgDemo.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
VcpkgTripletSelection:
  Using triplet "x64-windows" from "C:\Dev\vcpkg\scripts\buildsystems\msbuild\..\..\..\installed\x64-windows\"
ClCompile:
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.29.30130\bin\HostX86\x64\CL.exe /c /I"C:
  \Dev\vcpkg\scripts\buildsystems\msbuild\..\..\..\installed\x64-windows\include" /ZI /JMC /nologo /W3 /WX- /diagnostic
  s:column /sdl /Od /D _DEBUG /D _CONSOLE /D _UNICODE /D UNICODE /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /permissive- /Zc
  :wchar_t /Zc:forScope /Zc:inline /Fo"x64\Debug\\" /Fd"x64\Debug\vc142.pdb" /external:env:EXTERNAL_INCLUDE /external:W
  3 /Gd /TP /FC /errorReport:queue NotVcpkgDemo.cpp
  NotVcpkgDemo.cpp
Link:
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.29.30130\bin\HostX86\x64\link.exe /ERROR
  REPORT:QUEUE /OUT:"C:\Users\billy\source\repos\NotVcpkgDemo\x64\Debug\NotVcpkgDemo.exe" /INCREMENTAL /ILK:"x64\Debug\
  NotVcpkgDemo.ilk" /NOLOGO /LIBPATH:"C:\Dev\vcpkg\scripts\buildsystems\msbuild\..\..\..\installed\x64-windows\debug\li
  b" /LIBPATH:"C:\Dev\vcpkg\scripts\buildsystems\msbuild\..\..\..\installed\x64-windows\debug\lib\manual-link" kernel32
  .lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.l
  ib odbccp32.lib "C:\Dev\vcpkg\scripts\buildsystems\msbuild\..\..\..\installed\x64-windows\debug\lib\*.lib" /MANIFEST
  /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"C:\Users\billy\source\repos\NotVcpkgDe
  mo\x64\Debug\NotVcpkgDemo.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:\Users\billy\source\repo
  s\NotVcpkgDemo\x64\Debug\NotVcpkgDemo.lib" /MACHINE:X64 x64\Debug\NotVcpkgDemo.obj
  LINK : the 32-bit linker (C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.29.30130\bin\H
  ostX86\x64\link.exe) failed to do memory mapped file I/O on `C:\Dev\vcpkg\scripts\buildsystems\msbuild\..\..\..\insta
  lled\x64-windows\debug\lib\clangStaticAnalyzerCheckersd.lib' and is going to restart linking with a 64-bit linker for
   better throughput
  LINK : restarting link with 64-bit linker `C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\
  14.29.30130\bin\HostX64\x64\link.exe'
  NotVcpkgDemo.vcxproj -> C:\Users\billy\source\repos\NotVcpkgDemo\x64\Debug\NotVcpkgDemo.exe
AppLocalFromInstalled:
  pwsh.exe -ExecutionPolicy Bypass -noprofile -File "C:\Dev\vcpkg\scripts\buildsystems\msbuild\applocal.ps1" "C:\Users\
  billy\source\repos\NotVcpkgDemo\x64\Debug\NotVcpkgDemo.exe" "C:\Dev\vcpkg\scripts\buildsystems\msbuild\..\..\..\insta
  lled\x64-windows\debug\bin" "x64\Debug\NotVcpkgDemo.tlog\NotVcpkgDemo.write.1u.tlog" "x64\Debug\vcpkg.applocal.log"
FinalizeBuildStatus:
  Deleting file "x64\Debug\NotVcpkgDemo.tlog\unsuccessfulbuild".
  Touching "x64\Debug\NotVcpkgDemo.tlog\NotVcpkgDemo.lastbuildstate".
Done Building Project "C:\Users\billy\source\repos\NotVcpkgDemo\NotVcpkgDemo\NotVcpkgDemo.vcxproj" (Rebuild target(s)).

Done Building Project "C:\Users\billy\source\repos\NotVcpkgDemo\NotVcpkgDemo.sln" (Rebuild target(s)).


Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:02.64

C:\Users\billy\source\repos>
```

**Comment by BillyONeal** [comment]
Hmmmm so I tried turning on my new thing in the above repro and the time doesn't get all that much better. I think the actual increase in time is from adding all the libs to the linker command line.

```
C:\Users\billy\source\repos>msbuild NotVcpkgDemo\NotVcpkgDemo.sln /p:Platform=x64 /p:Configuration=Debug /t:Rebuild /p:VcpkgEnabled=true
Microsoft (R) Build Engine version 16.11.0-preview-21302-05+5e37cc992 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
Build started 7/4/2021 7:42:20 PM.
Project "C:\Users\billy\source\repos\NotVcpkgDemo\NotVcpkgDemo.sln" on node 1 (Rebuild target(s)).
ValidateSolutionConfiguration:
  Building solution configuration "Debug|x64".
Project "C:\Users\billy\source\repos\NotVcpkgDemo\NotVcpkgDemo.sln" (1) is building "C:\Users\billy\source\repos\NotVcp
kgDemo\NotVcpkgDemo\NotVcpkgDemo.vcxproj" (2) on node 1 (Rebuild target(s)).
_PrepareForClean:
  Deleting file "x64\Debug\NotVcpkgDemo.tlog\NotVcpkgDemo.lastbuildstate".
InitializeBuildStatus:
  Creating "x64\Debug\NotVcpkgDemo.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
VcpkgTripletSelection:
  Using triplet "x64-windows" from "C:\Dev\vcpkg\scripts\buildsystems\msbuild\..\..\..\installed\x64-windows\"
ClCompile:
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.29.30130\bin\HostX86\x64\CL.exe /c /I"C:
  \Dev\vcpkg\scripts\buildsystems\msbuild\..\..\..\installed\x64-windows\include" /ZI /JMC /nologo /W3 /WX- /diagnostic
  s:column /sdl /Od /D _DEBUG /D _CONSOLE /D _UNICODE /D UNICODE /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /permissive- /Zc
  :wchar_t /Zc:forScope /Zc:inline /Fo"x64\Debug\\" /Fd"x64\Debug\vc142.pdb" /external:env:EXTERNAL_INCLUDE /external:W
  3 /Gd /TP /FC /errorReport:queue NotVcpkgDemo.cpp
  NotVcpkgDemo.cpp
Link:
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.29.30130\bin\HostX86\x64\link.exe /ERROR
  REPORT:QUEUE /OUT:"C:\Users\billy\source\repos\NotVcpkgDemo\x64\Debug\NotVcpkgDemo.exe" /INCREMENTAL /ILK:"x64\Debug\
  NotVcpkgDemo.ilk" /NOLOGO /LIBPATH:"C:\Dev\vcpkg\scripts\buildsystems\msbuild\..\..\..\installed\x64-windows\debug\li
  b" /LIBPATH:"C:\Dev\vcpkg\scripts\buildsystems\msbuild\..\..\..\installed\x64-windows\debug\lib\manual-link" kernel32
  .lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.l
  ib odbccp32.lib "C:\Dev\vcpkg\scripts\buildsystems\msbuild\..\..\..\installed\x64-windows\debug\lib\*.lib" /MANIFEST
  /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"C:\Users\billy\source\repos\NotVcpkgDe
  mo\x64\Debug\NotVcpkgDemo.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:\Users\billy\source\repo
  s\NotVcpkgDemo\x64\Debug\NotVcpkgDemo.lib" /MACHINE:X64 x64\Debug\NotVcpkgDemo.obj
  LINK : the 32-bit linker (C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.29.30130\bin\H
  ostX86\x64\link.exe) failed to do memory mapped file I/O on `C:\Dev\vcpkg\scripts\buildsystems\msbuild\..\..\..\insta
  lled\x64-windows\debug\lib\clangStaticAnalyzerCheckersd.lib' and is going to restart linking with a 64-bit linker for
   better throughput
  LINK : restarting link with 64-bit linker `C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\
  14.29.30130\bin\HostX64\x64\link.exe'
  NotVcpkgDemo.vcxproj -> C:\Users\billy\source\repos\NotVcpkgDemo\x64\Debug\NotVcpkgDemo.exe
AppLocalFromInstalled:
  C:\Dev\vcpkg-tool\out\build\x64-Debug\vcpkg.exe z-applocal --target-binary="C:\Users\billy\source\repos\NotVcpkgDemo\
  x64\Debug\NotVcpkgDemo.exe" --installed-bin-dir="C:\Dev\vcpkg\scripts\buildsystems\msbuild\..\..\..\installed\x64-win
  dows\debug\bin" --tlog-file="x64\Debug\NotVcpkgDemo.tlog\NotVcpkgDemo.write.1u.tlog" --copied-files-log="x64\Debug\vc
  pkg.applocal.log"
  vcpkg applocal processing: C:\Users\billy\source\repos\NotVcpkgDemo\x64\Debug\NotVcpkgDemo.exe
FinalizeBuildStatus:
  Deleting file "x64\Debug\NotVcpkgDemo.tlog\unsuccessfulbuild".
  Touching "x64\Debug\NotVcpkgDemo.tlog\NotVcpkgDemo.lastbuildstate".
Done Building Project "C:\Users\billy\source\repos\NotVcpkgDemo\NotVcpkgDemo\NotVcpkgDemo.vcxproj" (Rebuild target(s)).

Done Building Project "C:\Users\billy\source\repos\NotVcpkgDemo\NotVcpkgDemo.sln" (Rebuild target(s)).


Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:02.18

C:\Users\billy\source\repos>
```

**Comment by stinos** [comment]
> Hmmmm so I tried turning on my new thing in the above repro and the time doesn't get all that much better. I think the actual increase in time is from adding all the libs to the linker command line

Don't know if it's possible to have msbuild display the time it takes for individual steps but since the linker is specifically saying it is restarting that is not unlikely. A better comparison would be to use the hostx64 compiler/linker. 

I see you're using pwsh.exe (how did you make that happen) which does have a slightly better startup time than powershell.exe IIRC.

**Comment by BillyONeal** [comment]
> Don't know if it's possible to have msbuild display the time it takes for individual steps but since the linker is specifically saying it is restarting that is not unlikely. A better comparison would be to use the hostx64 compiler/linker.

Forcing everyone to use the x64 linker would still be our 'fault' though, so I think this issue wouldn't be "fixed".

>I see you're using pwsh.exe (how did you make that happen) which does have a slightly better startup time than powershell.exe IIRC.

That's the current behavior: https://github.com/microsoft/vcpkg/blob/110c89fc6ada7bc9fad715eaf8211f20aad084f5/scripts/buildsystems/msbuild/vcpkg.targets#L123-L132

**Comment by stinos** [comment]
FWIW using manifest mode this is not relevant anymore since that works per-project
