### ISSUE TITLE
vcpkg stops work when checking out another git branch

### ISSUE THREAD

**Issue by kreuzerkrieg** [microsoft/vcpkg#9924]
**Host Environment**
- OS: Linux
- Compiler: GCC9

During working on adding ports I'm switching from one port git branch to another, the following happens:

> ./vcpkg install whateverport
> Computing installation plan...
> We could not find a CONTROL file for 

I cant install ANY port. If I clean the vcpkg folder (git clean -dfx) and `bootstrap` it, everything works fine, until next checkout occurs.

EDIT001:
Well, looks like deleting `buildtrees`, `downloads`,`installed` and `packages` solves the problem, no need to bootstrap

**Comment by Berrysoft** [comment]
Same problem after pull from master.

**Comment by PhoebeHui** [comment]
@kreuzerkrieg, @Berrysoft, thanks for reporting this issue.

However, I tried twice but still can't repro this issue, could you get latest source and see if this issue still repro? we merged a fix in vcpkg, the vcpkg revision should be '2020.02.04'.

**Comment by kreuzerkrieg** [comment]
> @kreuzerkrieg, @Berrysoft, thanks for reporting this issue.
> 
> However, I tried twice but still can't repro this issue, could you get latest source and see if this issue still repro? we merged a fix in vcpkg, the vcpkg revision should be '2020.02.04'.
Happens on latest master (just rebased).
The exact repo - you have to have installed package in `installed` folder.
For example, I'm working on `farmhash`, it works and the package got installed. Then I switch to master. The `farmash` disappears from `ports` folder, but the installation artifact left under `installed` folder. Now try to install any package, I've tried `openssl` and it will exhibit above behavior. To resolve the problem, manually delete the `farmhash` from the `installed` folder

**Comment by bbares** [comment]
I have the same issue using the latest master. Both install and upgrade fail with the same error  "We could not find a CONTROL file for". Since it doesn't tell you what is missing it is very hard to even try the work around suggested by kreuzerkrieg.

**Comment by JackBoosY** [comment]
Do you rebuild vcpkg after pull from master?

**Comment by Berrysoft** [comment]
> Do you rebuild vcpkg after pull from master?

Yes. I tried several debug and release but they all produce the same error.

I couldn't find which package caused the problem, so I removed the code to report this error.

**Comment by JackBoosY** [comment]
It seems that #8601 is causing this issue.

**Comment by PhoebeHui** [comment]
The error emited from https://github.com/microsoft/vcpkg/blob/master/toolsrc/src/vcpkg/dependencies.cpp#L268, it seems that ipv.spec().to_string() empty here.

**Comment by JackBoosY** [comment]
@kreuzerkrieg @Berrysoft @bbares
Can you provide the name of the port that caused this result?
Thanks.

**Comment by kreuzerkrieg** [comment]
> @kreuzerkrieg @Berrysoft @bbares
> Can you provide the name of the port that caused this result?
> Thanks.

any port will do, you have to emulate switching between different branches. for the sake of repro you may do following

call `./vcpkg install anypackage`
wait for the package to install
delete the port from `ports` folder
call `./vcpkg install anyotherpackage`
you will get 
>Computing installation plan...
We could not find a CONTROL file for 

for example

```
./vcpkg install openssl
rm -rf ports/openssl
./vcpkg install boost
```

**Comment by JackBoosY** [comment]
@kreuzerkrieg Does this result after switching to an earlier branch or the latest branch?

**Comment by JackBoosY** [comment]
@kreuzerkrieg Thanks for your sample, now I can repro it.

**Comment by JackBoosY** [comment]
@ras0219-msft 
In
https://github.com/microsoft/vcpkg/blob/6f2fba24dc5ceb339464e205eb8e7b2afcc31efa/toolsrc/src/vcpkg/dependencies.cpp#L897
This line will traverse all installed ports according to the contents of the `status` file to obtain port information. However, the installed ports are not necessarily related to the ports that need to be installed.
Therefore, when the ports folder of the installed port is deleted, error will be reported here:
https://github.com/microsoft/vcpkg/blob/6f2fba24dc5ceb339464e205eb8e7b2afcc31efa/toolsrc/src/vcpkg/dependencies.cpp#L678
which will cause the installation process to terminate.

So I think that we should use the `Build-depends` information in `CONTROL` to choose to find the status in status instead of looping through.

**Comment by PhoebeHui** [comment]
Added the repro steps, glfw3 just as a exzample, it could be any new/delete ports.
1. https://github.com/microsoft/vcpkg
2. .\bootstrap-vcpkg.bat
3. git checkout -b vcpkgtest
4. ./vcpkg install glfw3
5. del ports\glfw3 folder
6.  git checkout master
7. ./vcpkg install glfw3

PS F:\vcpkg\src> git checkout master
Previous HEAD position was 586bee9bc... [RESTinio] updated to v.0.6.3 (#9858)
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.
PS F:\vcpkg\src> git checkout -b vcpkgtest
Switched to a new branch 'vcpkgtest'
PS F:\vcpkg\src> ./vcpkg install glfw3
Warning: Different source is available for vcpkg (2020.1.18 -> 2020.2.4). Use .\bootstrap-vcpkg.bat to update.
Computing installation plan...
The following packages will be built and installed:
    glfw3[core]:x86-windows
Starting package 1/1: glfw3:x86-windows
Building package glfw3[core]:x86-windows...
-- Downloading https://github.com/glfw/glfw/archive/3.3.2.tar.gz...
-- Extracting source F:/VCPKG/src/downloads/glfw-glfw-3.3.2.tar.gz
-- Using source at F:/VCPKG/src/buildtrees/glfw3/src/3.3.2-558ea1f140
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Installing: F:/VCPKG/src/packages/glfw3_x86-windows/share/glfw3/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package glfw3[core]:x86-windows... done
Installing package glfw3[core]:x86-windows...
Installing package glfw3[core]:x86-windows... done
Elapsed time for package glfw3:x86-windows: 15.16 s
Total elapsed time: 15.16 s
The package glfw3:x86-windows provides CMake targets:

    find_package(glfw3 CONFIG REQUIRED)
    target_link_libraries(main PRIVATE glfw)

PS F:\vcpkg\src> git checkout master
Switched to branch 'master'
D       ports/glfw3/CONTROL
D       ports/glfw3/portfile.cmake
Your branch is up-to-date with 'origin/master'.
PS F:\vcpkg\src> ./vcpkg install glfw3
Warning: Different source is available for vcpkg (2020.1.18 -> 2020.2.4). Use .\bootstrap-vcpkg.bat to update.
Computing installation plan...
We could not find a CONTROL file for

**Comment by ras0219-msft** [comment]
Thanks for working out a repro; I'll look at getting this fixed as soon as possible.

**Comment by ras0219-msft** [comment]
Ok, so the immediate "workaround" is that you can always `vcpkg remove` packages, even ones that aren't backed by ports on disk.

In the longer term, we should be able to enable limited `install` functionality as long as we avoid the unbacked package (because we can't reinstall it!). However, it's a nontrivial code change to enable that capability, and I hope this workaround should be sufficient to close this issue for now.

**Comment by bbares** [comment]
Well that was a disaster. After getting the latest code and building it. I ran vcpkg upgrade. It told me the offending package and how to remove it. I ran the command suggested. It removed the package. I run vcpkg upgrade again and it says it will upgrade a bunch of packages. I run it again with --no-dry-run and it proceeds to purge 217 of 218 packages.
