### ISSUE TITLE
Are ports for CMake script libraries acceptable?

### ISSUE THREAD

**Issue by mbeutel** [microsoft/vcpkg#9928]
Would you accept PRs with portfiles for libraries that solely consist of CMake script files?

An example would be [YCM](https://github.com/robotology/ycm/). This can be used as a CMake package, i.e. with `find_package(YCM)`, but the config file only modifies `CMAKE_MODULE_PATH` to make YCM's CMake modules (e.g. [InstallBasicPackageFiles](http://robotology.github.io/ycm/gh-pages/git-master/module/InstallBasicPackageFiles.html)) accessible.

I have a Vcpkg port for YCM in my ports repository here:  
https://mp-force.ziti.uni-heidelberg.de/asc/infrastructure/vcpkg-ports/blob/master/vcpkg/ports/ycm  
I'd be happy to submit a PR with the port.

**Comment by traversaro** [comment]
Some CMake-only ports already exists in vcpkg, as for example  `ECM` (https://github.com/KDE/extra-cmake-modules), see https://github.com/microsoft/vcpkg/tree/master/ports/ecm and https://github.com/microsoft/vcpkg/pull/877 . As `ecm` was one of the source of inspiration for the creation of `YCM` , I think it can make sense to have a port for it.

**Comment by traversaro** [comment]
More related to the YCM port, I would suggest to create  it using the offline tarball, otherwise you could make the vcpkg port of ycm vulnerable to any outage in 3rd party repositories, see https://github.com/robotology/ycm/issues/105 .

**Comment by PhoebeHui** [comment]
@mbeutel, we're happy to accpets the PR, could you please summit a PR this?

**Comment by PhoebeHui** [comment]
@mbeutel, feel free to summit a PR for this.

**Comment by mbeutel** [comment]
Thanks; I just didn't have time yet. Next week, hopefully.
