### ISSUE TITLE
[New Port Request] toml11

### ISSUE THREAD

**Issue by li-wu** [microsoft/vcpkg#9935]
Library name:
toml11

Library description:
toml11 is a C++11 header-only toml parser/encoder depending only on C++ standard library.
compatible to the latest version of TOML v0.5.0 after version 2.0.0.

Source repository URL:
https://github.com/ToruNiina/toml11

Project homepage (if different from the source repository):
N/A

Anything else that is useful to know when adding (such as optional features the library may have that should be included):
N/A

**Comment by traversaro** [comment]
I guess this was solved by https://github.com/microsoft/vcpkg/pull/9941 .

**Comment by li-wu** [comment]
yes, let me close it.
