### ISSUE TITLE
[google/etc2comp] vcpkg math-related build failure

### ISSUE THREAD

**Issue by mikebdp2** [microsoft/vcpkg#9938]
**Host Environment**
- OS: Linux Mint 19.3
- Compiler: c++ 4.8 or 7 ?

**To Reproduce**
use https://github.com/daleglass/athena-builder, which finally executes
`--vcpkg-root /home/owner/Athena/vcpkg/20693e10 install --triplet x64-linux hifi-client-deps`

**Failure logs** 
[install-x64-linux-dbg-out.log](https://github.com/microsoft/vcpkg/files/4163651/install-x64-linux-dbg-out.log)

Seems to be a https://github.com/google/etc2comp/ math-related problem?

**Comment by PhoebeHui** [comment]
@mikebdp2, it looks we don't have etc2comp port yet, would you like to summit a PR firstly?

**Comment by PhoebeHui** [comment]
@mikebdp2, please submit a PR for etc2comp firstly.
