### ISSUE TITLE
harfbuzz fails to install hb-glib.h for some configurations

### ISSUE THREAD

**Issue by FrankHeimes** [microsoft/vcpkg#9939]
I built `harfbuzz` successfully on Windows 10, 1903 (see output below).
Since I need static libraries, I changed `VCPKG_LIBRARY_LINKAGE` to `static` in the `x64-windows` and `x86-windows` triplets.

Everything is installed as expected, except for `hb-glib.h`. That file is only installed into the `x86-windows-static` and `x64-windows-static` branches, but not into the `x86-windows` and `x64-windows` branches, causing dependent projects like `pango` to fail compiling.

After manually copying `hb-glib.h` from `x86-windows-static\include\harfbuzz` to `x86-windows\include\harfbuzz` (same for x64), `pango` successfully built, too.

```
Starting package 7/321: harfbuzz:x86-windows-static
Building package harfbuzz[core,ucdn]:x86-windows-static...
-- Using community triplet x86-windows-static. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: D:\Dev\Main\Shared\Libs\vcpkg\triplets\community\x86-windows-static.cmake
-- Using cached D:/Dev/Main/Shared/Libs/vcpkg/downloads/harfbuzz-harfbuzz-2.5.3.tar.gz
-- Using source at D:/Dev/Main/Shared/Libs/vcpkg/buildtrees/harfbuzz/src/2.5.3-984271955b
-- Configuring x86-windows-static
-- Building x86-windows-static-dbg
-- Building x86-windows-static-rel
-- Installing: D:/Dev/Main/Shared/Libs/vcpkg/packages/harfbuzz_x86-windows-static/share/harfbuzz/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package harfbuzz[core,ucdn]:x86-windows-static... done
Installing package harfbuzz[core,ucdn]:x86-windows-static...
Installing package harfbuzz[core,ucdn]:x86-windows-static... done
Elapsed time for package harfbuzz:x86-windows-static: 1.052 min

Starting package 19/321: harfbuzz:x64-windows-static
Building package harfbuzz[core,ucdn]:x64-windows-static...
-- Using cached D:/Dev/Main/Shared/Libs/vcpkg/downloads/harfbuzz-harfbuzz-2.5.3.tar.gz
-- Using source at D:/Dev/Main/Shared/Libs/vcpkg/buildtrees/harfbuzz/src/2.5.3-984271955b
-- Configuring x64-windows-static
-- Building x64-windows-static-dbg
-- Building x64-windows-static-rel
-- Installing: D:/Dev/Main/Shared/Libs/vcpkg/packages/harfbuzz_x64-windows-static/share/harfbuzz/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package harfbuzz[core,ucdn]:x64-windows-static... done
Installing package harfbuzz[core,ucdn]:x64-windows-static...
Installing package harfbuzz[core,ucdn]:x64-windows-static... done
Elapsed time for package harfbuzz:x64-windows-static: 56.3 s

Starting package 32/321: harfbuzz:x86-windows
Building package harfbuzz[core,ucdn]:x86-windows...
-- Using cached D:/Dev/Main/Shared/Libs/vcpkg/downloads/harfbuzz-harfbuzz-2.5.3.tar.gz
-- Using source at D:/Dev/Main/Shared/Libs/vcpkg/buildtrees/harfbuzz/src/2.5.3-984271955b
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Installing: D:/Dev/Main/Shared/Libs/vcpkg/packages/harfbuzz_x86-windows/share/harfbuzz/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package harfbuzz[core,ucdn]:x86-windows... done
Installing package harfbuzz[core,ucdn]:x86-windows...
Installing package harfbuzz[core,ucdn]:x86-windows... done
Elapsed time for package harfbuzz:x86-windows: 54.67 s

Building package harfbuzz[core,ucdn]:x64-windows...
-- Using cached D:/Dev/Main/Shared/Libs/vcpkg/downloads/harfbuzz-harfbuzz-2.5.3.tar.gz
-- Using source at D:/Dev/Main/Shared/Libs/vcpkg/buildtrees/harfbuzz/src/2.5.3-984271955b
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Installing: D:/Dev/Main/Shared/Libs/vcpkg/packages/harfbuzz_x64-windows/share/harfbuzz/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package harfbuzz[core,ucdn]:x64-windows... done
Installing package harfbuzz[core,ucdn]:x64-windows...
Installing package harfbuzz[core,ucdn]:x64-windows... done
Elapsed time for package harfbuzz:x64-windows: 1.044 min

```

**Comment by JackBoosY** [comment]
Hi @FrankHeimes, thanks for reporting this issue.
I think you should modify `x86-windows-static.cmake` and `x64-windows-static.cmake` and set `VCPKG_CRT_LINKAGE` to `dynamic` instead of `x64-windows.cmake` and `x86-windows.cmake`.

In _SOURCE/CMakeLists.txt_
line 286:
```
if (HB_HAVE_GLIB)
...
  list(APPEND project_headers ${PROJECT_SOURCE_DIR}/src/hb-glib.h)
...
endif ()
```

line 753:
```
if (NOT SKIP_INSTALL_HEADERS AND NOT SKIP_INSTALL_ALL)
  install(FILES ${project_headers} DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}/harfbuzz)
...
endif ()
```

So if `HB_HAVE_GLIB` is `TRUE`, `SKIP_INSTALL_HEADERS` and `SKIP_INSTALL_ALL` are both `FALSE`, this header should be installed.

**Comment by FrankHeimes** [comment]
Hi @JackBoosY, thank you for your explanation.

> Hi @FrankHeimes, thanks for reporting this issue.
> I think you should modify `x86-windows-static.cmake` and `x64-windows-static.cmake` and set `VCPKG_CRT_LINKAGE` to `dynamic` instead of `x64-windows.cmake` and `x86-windows.cmake`.

No, that won't work for us. We are OK to ship the matching CRT redistributables with our products but don't want to manage the installation of dozens of DLLs generated from numerous vcpkg packages. Therefore, we build every third-party-library as static libraries, most of which with dynamic CRT linkage. For very few products, we need to avoid dynamic linking to the CRT, too.

So we use all four triplets like this:
`x??-windows.cmake` : static library, dynamic CRT linkage
`x??-windows-static.cmake` : static library, static CRT linkage

> if (HB_HAVE_GLIB)
> ...
>   list(APPEND project_headers ${PROJECT_SOURCE_DIR}/src/hb-glib.h)
> ...
> endif ()

May I suggest that the if-clause is just ditched and the header is installed in all cases?
As it might be obsolete for dynamic libraries, it shouldn't hurt.

**Comment by JackBoosY** [comment]
@FrankHeimes Nope, `glib` is a feature of harfbuzz, so this header file is not installed in all cases.
So, I guess you need to install harfbuzz using `./vcpkg install harfbuzz[glib]`.

**Comment by FrankHeimes** [comment]
> @FrankHeimes Nope, `glib` is a feature of harfbuzz, so this header file is not installed in all cases.
> So, I guess you need to install harfbuzz using `./vcpkg install harfbuzz[glib]`.

I see. vcpkg did not install that feature because it says `harfbuzz[glib] (!(windows&static))` in the `CONTROL` file of `pango` and I was attempting to build static libraries. So I think I have to specify the `harfbuzz[glib]` packet explicitly.

Thanks, @JackBoosY 

_off-topic_
I have the impression that more and more vcpkg contributors start to phase out support for static libraries and going so far as to enforce that _all_ vcpkg be built as dlls. Are you guys seriously shipping dozens (hundreds?) of third-party DLLs even for small applications?

**Comment by JackBoosY** [comment]
@FrankHeimes Yes, we will ensure that every dependent library is built and installed. And support for static builds is what we strive for.
