### ISSUE TITLE
vcpkg install libpng "Computing installation plan..." then nothing happens

### ISSUE THREAD

**Issue by eix128** [microsoft/vcpkg#9943]
**Describe the bug**

**Environment**
- OS: Windows
- Compiler: msvc

**To Reproduce**
D:\repo\vcpkg>vcpkg install libpng
Computing installation plan...

D:\repo\vcpkg>

**Expected behavior**
The program does nothing.
It says "Computing installation plan..."

**Failure logs** 
-(please attached failure logs)

**Additional context**
When i try to install any library , vcpkg ouputs "Computing installation plan..."
Then exits the program.I got no output.Nothing.
I also tried on admin mode cmd the same problem happens.

How to get logs ? Whats wrong ?

**Comment by PhoebeHui** [comment]
@eix128, could you get vcpkg latest source and see if this issue still repro, we merged a fix, might addressed this issue.

**Comment by PhoebeHui** [comment]
@eix128, I can't repro this issue, please reopen this issue if it still be a problem for you.

**Comment by zcream** [comment]
Turn off  VCPKG_FORCE_SYSTEM_BINARIES - I got a similar error when I have that set

**Comment by PhoebeHui** [comment]
@zcream, please report a new issue with more information, like what's the system tools used and what's the version of system tools.
