### ISSUE TITLE
Error: Building package boost-regex:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by Rita-ritally** [microsoft/vcpkg#9945]
I'm on windows 10 and Visual Studio 2017, I was trying to install the whole boost package with vcpkg install boost:x64-windows and it was fine in the beginning then when building the regex library it failed.
There is no space in my vcpkg root. I try to reinstall VS2017 but no use.I have already changed VS2017 language from chinese to English

 `PS E:\lastdesign\Facial_Details_Synthesis\src\proxyEstimator\vcpkg> ./vcpkg install boost  --triplet x64-windows
The following packages will be built and installed:
    boost[core]:x64-windows
  * boost-accumulators[core]:x64-windows
  * boost-algorithm[core]:x64-windows
  * boost-align[core]:x64-windows
  * boost-any[core]:x64-windows
  * boost-asio[core]:x64-windows
  * boost-assign[core]:x64-windows
  * boost-atomic[core]:x64-windows
  * boost-beast[core]:x64-windows
  * boost-bimap[core]:x64-windows
  * boost-callable-traits[core]:x64-windows
  * boost-chrono[core]:x64-windows
  * boost-circular-buffer[core]:x64-windows
  * boost-compute[core]:x64-windows
  * boost-container[core]:x64-windows
  * boost-context[core]:x64-windows
  * boost-contract[core]:x64-windows
  * boost-convert[core]:x64-windows
  * boost-coroutine[core]:x64-windows
  * boost-coroutine2[core]:x64-windows
  * boost-crc[core]:x64-windows
  * boost-date-time[core]:x64-windows
  * boost-disjoint-sets[core]:x64-windows
  * boost-dll[core]:x64-windows
  * boost-dynamic-bitset[core]:x64-windows
  * boost-endian[core]:x64-windows
  * boost-exception[core]:x64-windows
  * boost-fiber[core]:x64-windows
  * boost-filesystem[core]:x64-windows
  * boost-flyweight[core]:x64-windows
  * boost-foreach[core]:x64-windows
  * boost-format[core]:x64-windows
  * boost-functional[core]:x64-windows
  * boost-geometry[core]:x64-windows
  * boost-gil[core]:x64-windows
  * boost-graph[core]:x64-windows
  * boost-graph-parallel[core]:x64-windows
  * boost-hana[core]:x64-windows
  * boost-heap[core]:x64-windows
  * boost-histogram[core]:x64-windows
  * boost-hof[core]:x64-windows
  * boost-icl[core]:x64-windows
  * boost-interprocess[core]:x64-windows
  * boost-interval[core]:x64-windows
  * boost-intrusive[core]:x64-windows
  * boost-io[core]:x64-windows
  * boost-iostreams[core]:x64-windows
  * boost-lambda[core]:x64-windows
  * boost-lexical-cast[core]:x64-windows
  * boost-local-function[core]:x64-windows
  * boost-locale[core]:x64-windows
  * boost-lockfree[core]:x64-windows
  * boost-log[core]:x64-windows
  * boost-logic[core]:x64-windows
  * boost-math[core]:x64-windows
  * boost-metaparse[core]:x64-windows
  * boost-mp11[core]:x64-windows
  * boost-msm[core]:x64-windows
  * boost-multi-array[core]:x64-windows
  * boost-multi-index[core]:x64-windows
  * boost-multiprecision[core]:x64-windows
  * boost-odeint[core]:x64-windows
  * boost-outcome[core]:x64-windows
  * boost-parameter[core]:x64-windows
  * boost-parameter-python[core]:x64-windows
  * boost-phoenix[core]:x64-windows
  * boost-poly-collection[core]:x64-windows
  * boost-polygon[core]:x64-windows
  * boost-pool[core]:x64-windows
  * boost-process[core]:x64-windows
  * boost-program-options[core]:x64-windows
  * boost-property-map[core]:x64-windows
  * boost-property-tree[core]:x64-windows
  * boost-proto[core]:x64-windows
  * boost-ptr-container[core]:x64-windows
  * boost-python[core]:x64-windows
  * boost-qvm[core]:x64-windows
  * boost-random[core]:x64-windows
  * boost-range[core]:x64-windows
  * boost-ratio[core]:x64-windows
  * boost-rational[core]:x64-windows
  * boost-regex[core]:x64-windows
  * boost-safe-numerics[core]:x64-windows
  * boost-scope-exit[core]:x64-windows
  * boost-serialization[core]:x64-windows
  * boost-signals2[core]:x64-windows
  * boost-sort[core]:x64-windows
  * boost-spirit[core]:x64-windows
  * boost-stacktrace[core]:x64-windows
  * boost-statechart[core]:x64-windows
  * boost-system[core]:x64-windows
  * boost-test[core]:x64-windows
  * boost-thread[core]:x64-windows
  * boost-timer[core]:x64-windows
  * boost-tokenizer[core]:x64-windows
  * boost-tti[core]:x64-windows
  * boost-type-erasure[core]:x64-windows
  * boost-ublas[core]:x64-windows
  * boost-units[core]:x64-windows
  * boost-unordered[core]:x64-windows
  * boost-uuid[core]:x64-windows
  * boost-variant[core]:x64-windows
  * boost-variant2[core]:x64-windows
  * boost-vmd[core]:x64-windows
  * boost-wave[core]:x64-windows
  * boost-winapi[core]:x64-windows
  * boost-xpressive[core]:x64-windows
  * boost-yap[core]:x64-windows
  * bzip2[core]:x64-windows
  * libffi[core]:x64-windows
  * openssl[core]:x64-windows
  * openssl-windows[core]:x64-windows
  * python3[core]:x64-windows
  * zstd[core]:x64-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/114: boost-regex:x64-windows
Building package boost-regex[core]:x64-windows...
-- Using cached E:/lastdesign/Facial_Details_Synthesis/src/proxyEstimator/vcpkg/downloads/boostorg-regex-boost-1.72.0.tar.gz
-- Using source at E:/lastdesign/Facial_Details_Synthesis/src/proxyEstimator/vcpkg/buildtrees/boost-regex/src/ost-1.72.0-a233385537
-- Building x64-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: E:/lastdesign/Facial_Details_Synthesis/src/proxyEstimator/vcpkg/installed/x64-windows/tools/boost-build/b2.exe --stagedir=E:/lastdesign/Facial_Details_Synthesis/src/proxyEstimator/vcpkg/buildtrees/boost-regex/x64-windows-rel/stage --build-dir=E:/lastdesign/Facial_Details_Synthesis/src/proxyEstimator/vcpkg/buildtrees/boost-regex/x64-windows-rel --user-config=E:/lastdesign/Facial_Details_Synthesis/src/proxyEstimator/vcpkg/buildtrees/boost-regex/x64-windows-rel/user-config.jam -j8 --debug-configuration --debug-building --debug-generators --disable-icu --ignore-site-config --hash -q -sZLIB_INCLUDE=E:/lastdesign/Facial_Details_Synthesis/src/proxyEstimator/vcpkg/installed/x64-windows/include -sBZIP2_INCLUDE=E:/lastdesign/Facial_Details_Synthesis/src/proxyEstimator/vcpkg/installed/x64-windows/include -sLZMA_INCLUDE=E:/lastdesign/Facial_Details_Synthesis/src/proxyEstimator/vcpkg/installed/x64-windows/include -sZSTD_INCLUDE=E:/lastdesign/Facial_Details_Synthesis/src/proxyEstimator/vcpkg/installed/x64-windows/include threading=multi threadapi=win32 runtime-link=shared link=shared address-model=64 architecture=x86 toolset=msvc -sZLIB_BINARY=zlib -sZLIB_LIBPATH=E:/lastdesign/Facial_Details_Synthesis/src/proxyEstimator/vcpkg/installed/x64-windows/lib -sBZIP2_BINARY=bz2 -sBZIP2_LIBPATH=E:/lastdesign/Facial_Details_Synthesis/src/proxyEstimator/vcpkg/installed/x64-windows/lib -sLZMA_BINARY=lzma -sLZMA_LIBPATH=E:/lastdesign/Facial_Details_Synthesis/src/proxyEstimator/vcpkg/installed/x64-windows/lib -sZSTD_BINARY=zstd -sZSTD_LIBPATH=E:/lastdesign/Facial_Details_Synthesis/src/proxyEstimator/vcpkg/installed/x64-windows/lib variant=release debug-symbols=on
    Working Directory: E:/lastdesign/Facial_Details_Synthesis/src/proxyEstimator/vcpkg/buildtrees/boost-regex/src/ost-1.72.0-a233385537/build
    Error code: 1
    See logs for more information:
      E:\lastdesign\Facial_Details_Synthesis\src\proxyEstimator\vcpkg\buildtrees\boost-regex\build-x64-windows-rel-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/boost-build/boost-modular-build.cmake:288 (vcpkg_execute_required_process)
  ports/boost-regex/portfile.cmake:20 (boost_modular_build)
  scripts/ports.cmake:94 (include)

Error: Building package boost-regex:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-regex:x64-windows
  Vcpkg version: 2020.01.17-nohash

Additionally, attach any relevant sections from the log files above.`

Here are build-x64-windows-rel-out.log
`notice: found boost-build.jam at E:/lastdesign/Facial_Details_Synthesis/src/proxyEstimator/vcpkg/installed/x64-windows/tools/boost-build/boost-build.jam
notice: loading Boost.Build from E:/lastdesign/Facial_Details_Synthesis/src/proxyEstimator/vcpkg/installed/x64-windows/tools/boost-build/src/kernel
notice: Site configuration files will be ignored due to the
notice: --ignore-site-config command-line option.
notice: Loading explicitly specified user configuration file:
    E:\lastdesign\Facial_Details_Synthesis\src\proxyEstimator\vcpkg\buildtrees\boost-regex\x64-windows-rel\user-config.jam
notice: Searching 'E:\lastdesign\Facial_Details_Synthesis\src\proxyEstimator\vcpkg\buildtrees\boost-regex\x64-windows-rel' for user-config configuration file 'user-config.jam'.
notice: Loading user-config configuration file 'user-config.jam' from 'E:/lastdesign/Facial_Details_Synthesis/src/proxyEstimator/vcpkg/buildtrees/boost-regex/x64-windows-rel'.
notice: [msvc-cfg] msvc-14.1 detected, command: 'D:\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\bin\HostX64\arm\cl.exe'
notice: will use 'D:\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\Hostx64\x64\cl.exe' for msvc, condition <toolset>msvc-14.1
notice: [msvc-cfg] condition: '<toolset>msvc-14.1/<architecture>/<address-model>', setup: 'E:/lastdesign/Facial_Details_Synthesis/src/proxyEstimator/vcpkg/installed/x64-windows/share/boost-build/nothing.bat x86'
notice: [msvc-cfg] condition: '<toolset>msvc-14.1/<architecture>/<address-model>32', setup: 'E:/lastdesign/Facial_Details_Synthesis/src/proxyEstimator/vcpkg/installed/x64-windows/share/boost-build/nothing.bat x86'
notice: [msvc-cfg] condition: '<toolset>msvc-14.1/<architecture>x86/<address-model>', setup: 'E:/lastdesign/Facial_Details_Synthesis/src/proxyEstimator/vcpkg/installed/x64-windows/share/boost-build/nothing.bat x86'
notice: [msvc-cfg] condition: '<toolset>msvc-14.1/<architecture>x86/<address-model>32', setup: 'E:/lastdesign/Facial_Details_Synthesis/src/proxyEstimator/vcpkg/installed/x64-windows/share/boost-build/nothing.bat x86'
notice: [msvc-cfg] condition: '<toolset>msvc-14.1/<architecture>/<address-model>64', setup: 'E:/lastdesign/Facial_Details_Synthesis/src/proxyEstimator/vcpkg/installed/x64-windows/share/boost-build/nothing.bat amd64'
notice: [msvc-cfg] condition: '<toolset>msvc-14.1/<architecture>x86/<address-model>64', setup: 'E:/lastdesign/Facial_Details_Synthesis/src/proxyEstimator/vcpkg/installed/x64-windows/share/boost-build/nothing.bat amd64'
notice: [msvc-cfg] condition: '<toolset>msvc-14.1/<architecture>ia64/<address-model>', setup: 'E:/lastdesign/Facial_Details_Synthesis/src/proxyEstimator/vcpkg/installed/x64-windows/share/boost-build/nothing.bat x86_ia64'
notice: [msvc-cfg] condition: '<toolset>msvc-14.1/<architecture>ia64/<address-model>64', setup: 'E:/lastdesign/Facial_Details_Synthesis/src/proxyEstimator/vcpkg/installed/x64-windows/share/boost-build/nothing.bat x86_ia64'
notice: [msvc-cfg] condition: '<toolset>msvc-14.1/<architecture>arm/<address-model>', setup: 'E:/lastdesign/Facial_Details_Synthesis/src/proxyEstimator/vcpkg/installed/x64-windows/share/boost-build/nothing.bat x86_arm'
notice: [msvc-cfg] condition: '<toolset>msvc-14.1/<architecture>arm/<address-model>32', setup: 'E:/lastdesign/Facial_Details_Synthesis/src/proxyEstimator/vcpkg/installed/x64-windows/share/boost-build/nothing.bat x86_arm'
notice: [msvc-cfg] condition: '<toolset>msvc-14.1/<architecture>arm/<address-model>', setup: 'E:/lastdesign/Facial_Details_Synthesis/src/proxyEstimator/vcpkg/installed/x64-windows/share/boost-build/nothing.bat x86_arm64'
notice: [msvc-cfg] condition: '<toolset>msvc-14.1/<architecture>arm/<address-model>64', setup: 'E:/lastdesign/Facial_Details_Synthesis/src/proxyEstimator/vcpkg/installed/x64-windows/share/boost-build/nothing.bat x86_arm64'
building project Jamfile<E:\lastdesign\Facial_Details_Synthesis\src\proxyEstimator\vcpkg\buildtrees\boost-regex\src\ost-1.72.0-a233385537\build>  ('object(project-target)@280') with <address-model>64 <architecture>x86 <debug-symbols>on <link>shared <runtime-link>shared <threadapi>win32 <threading>multi <toolset>msvc <variant>release`

[build-x64-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/4165772/build-x64-windows-rel-out.log)

**Comment by PhoebeHui** [comment]
@Rita-ritally, could you get a clean source and try to build again? I can't repro this issue locally.

Starting package 28/28: boost-regex:x86-windows
Building package boost-regex[core]:x86-windows...
-- Downloading https://github.com/boostorg/regex/archive/boost-1.72.0.tar.gz...
-- Extracting source F:/VCPKG/src/downloads/boostorg-regex-boost-1.72.0.tar.gz
-- Using source at F:/VCPKG/src/buildtrees/boost-regex/src/ost-1.72.0-a233385537
-- Building x86-windows-rel
-- Building x86-windows-rel done
-- Building x86-windows-dbg
-- Building x86-windows-dbg done
-- Packaging x86-windows-rel
-- Packaging x86-windows-rel done
-- Packaging x86-windows-dbg
-- Packaging x86-windows-dbg done
-- Packaging headers
-- Packaging headers done
-- Using cached F:/VCPKG/src/downloads/boost_LICENSE_1_0.txt
-- Installing: F:/VCPKG/src/packages/boost-regex_x86-windows/share/boost-regex/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package boost-regex[core]:x86-windows... done
Installing package boost-regex[core]:x86-windows...
Installing package boost-regex[core]:x86-windows... done
Elapsed time for package boost-regex:x86-windows: 29.45 s

Total elapsed time: 2.17 min

**Comment by Rita-ritally** [comment]
> @Rita-ritally, could you get a clean source and try to build again? I can't repro this issue locally.
> 
> Starting package 28/28: boost-regex:x86-windows
> Building package boost-regex[core]:x86-windows...
> -- Downloading https://github.com/boostorg/regex/archive/boost-1.72.0.tar.gz...
> -- Extracting source F:/VCPKG/src/downloads/boostorg-regex-boost-1.72.0.tar.gz
> -- Using source at F:/VCPKG/src/buildtrees/boost-regex/src/ost-1.72.0-a233385537
> -- Building x86-windows-rel
> -- Building x86-windows-rel done
> -- Building x86-windows-dbg
> -- Building x86-windows-dbg done
> -- Packaging x86-windows-rel
> -- Packaging x86-windows-rel done
> -- Packaging x86-windows-dbg
> -- Packaging x86-windows-dbg done
> -- Packaging headers
> -- Packaging headers done
> -- Using cached F:/VCPKG/src/downloads/boost_LICENSE_1_0.txt
> -- Installing: F:/VCPKG/src/packages/boost-regex_x86-windows/share/boost-regex/copyright
> -- Performing post-build validation
> -- Performing post-build validation done
> Building package boost-regex[core]:x86-windows... done
> Installing package boost-regex[core]:x86-windows...
> Installing package boost-regex[core]:x86-windows... done
> Elapsed time for package boost-regex:x86-windows: 29.45 s
> 
> Total elapsed time: 2.17 min

Do you mean I delete the source of  vcpkg/downloads/boostorg-regex and build again?

**Comment by Rita-ritally** [comment]
https://github.com/microsoft/vcpkg/issues/9945#issuecomment-583288695 @PhoebeHui

**Comment by Rita-ritally** [comment]
@PhoebeHui  Do you mean I delete the source of vcpkg/downloads/boostorg-regex and build again?

**Comment by PhoebeHui** [comment]
@Rita-ritally, sorry for my late reply.

Could you try the following steps and see if the issue still occur?
./vcpkg remove boost-modular-build-helper --recurse
./vcpkg remove boost-build --recurse
./vcpkg install boost-regex

**Comment by Rita-ritally** [comment]
@PhoebeHui  it doesn't work......
`PS C:\Users\Rita_悦> cd E:\lastdesign\vcpkg
PS E:\lastdesign\vcpkg> ./vcpkg remove boost-modular-build-helper --recurse
The following packages will be removed:
    boost-modular-build-helper:x64-windows
Removing package boost-modular-build-helper:x64-windows...
Removing package boost-modular-build-helper:x64-windows... done
Purging package boost-modular-build-helper:x64-windows...
Purging package boost-modular-build-helper:x64-windows... done
PS E:\lastdesign\vcpkg> ./vcpkg remove boost-build --recurse
Your feedback is important to improve Vcpkg! Please take 3 minutes to complete our survey by running: vcpkg contact --survey
The following packages will be removed:
    boost-build:x64-windows
Removing package boost-build:x64-windows...
Removing package boost-build:x64-windows... done
Purging package boost-build:x64-windows...
Purging package boost-build:x64-windows... done
PS E:\lastdesign\vcpkg> ./vcpkg install boost-regex
Computing installation plan...
The following packages will be built and installed:
  * boost-build[core]:x64-windows
  * boost-modular-build-helper[core]:x64-windows
    boost-regex[core]:x64-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/3: boost-build:x64-windows
Building package boost-build[core]:x64-windows...
-- Using cached E:/lastdesign/vcpkg/downloads/boostorg-build-boost-1.72.0.tar.gz
-- Using source at E:/lastdesign/vcpkg/buildtrees/boost-build/src/ost-1.72.0-fa8b817276
-- Using cached E:/lastdesign/vcpkg/downloads/boost_LICENSE_1_0.txt
-- Using cached E:/lastdesign/vcpkg/downloads/boost-1.72.0-boostcpp.jam
-- Installing: E:/lastdesign/vcpkg/packages/boost-build_x64-windows/share/boost-build/copyright
-- Installing: E:/lastdesign/vcpkg/packages/boost-build_x64-windows/tools/boost-build/boostcpp.jam
-- Bootstrapping...
-- Performing post-build validation
-- Performing post-build validation done
Building package boost-build[core]:x64-windows... done
Installing package boost-build[core]:x64-windows...
Installing package boost-build[core]:x64-windows... done
Elapsed time for package boost-build:x64-windows: 35.24 s
Starting package 2/3: boost-modular-build-helper:x64-windows
Building package boost-modular-build-helper[core]:x64-windows...
-- Performing post-build validation
-- Performing post-build validation done
Building package boost-modular-build-helper[core]:x64-windows... done
Installing package boost-modular-build-helper[core]:x64-windows...
Installing package boost-modular-build-helper[core]:x64-windows... done
Elapsed time for package boost-modular-build-helper:x64-windows: 2.243 s
Starting package 3/3: boost-regex:x64-windows
Building package boost-regex[core]:x64-windows...
-- Using cached E:/lastdesign/vcpkg/downloads/boostorg-regex-boost-1.72.0.tar.gz
-- Using source at E:/lastdesign/vcpkg/buildtrees/boost-regex/src/ost-1.72.0-a233385537
-- Building x64-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: E:/lastdesign/vcpkg/installed/x64-windows/tools/boost-build/b2.exe --stagedir=E:/lastdesign/vcpkg/buildtrees/boost-regex/x64-windows-rel/stage --build-dir=E:/lastdesign/vcpkg/buildtrees/boost-regex/x64-windows-rel --user-config=E:/lastdesign/vcpkg/buildtrees/boost-regex/x64-windows-rel/user-config.jam -j8 --debug-configuration --debug-building --debug-generators --disable-icu --ignore-site-config --hash -q -sZLIB_INCLUDE=E:/lastdesign/vcpkg/installed/x64-windows/include -sBZIP2_INCLUDE=E:/lastdesign/vcpkg/installed/x64-windows/include -sLZMA_INCLUDE=E:/lastdesign/vcpkg/installed/x64-windows/include -sZSTD_INCLUDE=E:/lastdesign/vcpkg/installed/x64-windows/include threading=multi threadapi=win32 runtime-link=shared link=shared address-model=64 architecture=x86 toolset=msvc -sZLIB_BINARY=zlib -sZLIB_LIBPATH=E:/lastdesign/vcpkg/installed/x64-windows/lib -sBZIP2_BINARY=bz2 -sBZIP2_LIBPATH=E:/lastdesign/vcpkg/installed/x64-windows/lib -sLZMA_BINARY=lzma -sLZMA_LIBPATH=E:/lastdesign/vcpkg/installed/x64-windows/lib -sZSTD_BINARY=zstd -sZSTD_LIBPATH=E:/lastdesign/vcpkg/installed/x64-windows/lib variant=release debug-symbols=on
    Working Directory: E:/lastdesign/vcpkg/buildtrees/boost-regex/src/ost-1.72.0-a233385537/build
    Error code: 1
    See logs for more information:
      E:\lastdesign\vcpkg\buildtrees\boost-regex\build-x64-windows-rel-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/boost-build/boost-modular-build.cmake:286 (vcpkg_execute_required_process)
  ports/boost-regex/portfile.cmake:20 (boost_modular_build)
  scripts/ports.cmake:90 (include)


Error: Building package boost-regex:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-regex:x64-windows
  Vcpkg version: 2020.02.04-nohash

Additionally, attach any relevant sections from the log files above.`

**Comment by Rita-ritally** [comment]
@PhoebeHui  I think my visual studio settings may have some problems, but i don't know the specific

**Comment by PhoebeHui** [comment]
@Rita-ritally, thanks for your updates!

Could you also attach failure log E:\lastdesign\vcpkg\buildtrees\boost-regex\build-x64-windows-rel-out.log?

**Comment by Rita-ritally** [comment]
@PhoebeHui 
here is my failure log
[build-x64-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/4231448/build-x64-windows-rel-out.log)

**Comment by Rita-ritally** [comment]
@PhoebeHui thank you for your reply
this is my failure log
[build-x64-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/4231457/build-x64-windows-rel-out.log)

**Comment by PhoebeHui** [comment]
@Rita-ritally, from your log, it seems 'boost_regex-vc141-mt-x64-1_72.dll' linked correctly, I didn't see any compiler errors or link errors, so it's unclear for me.

Boost currently upgrade to 1_73, could you get latest source and see this issue still exist?

**Comment by SwordenBlue** [comment]
I have the same issue and try to fix it.
@Rita-ritally : did you find a solution ?

    Working Directory: C:/local/vcpkg/buildtrees/boost-regex/src/ost-1.73.0-a7219fe4ec.clean/build
    Error code: 1
    See logs for more information:
      C:\local\vcpkg\buildtrees\boost-regex\build-x64-windows-rel-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/boost-build/boost-modular-build.cmake:339 (vcpkg_execute_required_process)
  ports/boost-regex/portfile.cmake:12 (boost_modular_build)
  scripts/ports.cmake:79 (include)


Error: Building package boost-regex:x64-windows failed with: BUILD_FAILED

**Comment by Rita-ritally** [comment]
Yes！！I changed my computer ID Rita_悦 to Rita，which not contains chinese character. It ran successful after it！！You can try it～


| |
廉悦
|
|
邮箱：lianyue1998@126.com
|

签名由 网易邮箱大师 定制

On 09/23/2020 11:02, SwordenBlue wrote:

I have the same issue and try to fix it.
@Rita-ritally : did you find a solution ?

Working Directory: C:/local/vcpkg/buildtrees/boost-regex/src/ost-1.73.0-a7219fe4ec.clean/build
Error code: 1
See logs for more information:
  C:\local\vcpkg\buildtrees\boost-regex\build-x64-windows-rel-out.log


Call Stack (most recent call first):
installed/x64-windows/share/boost-build/boost-modular-build.cmake:339 (vcpkg_execute_required_process)
ports/boost-regex/portfile.cmake:12 (boost_modular_build)
scripts/ports.cmake:79 (include)

Error: Building package boost-regex:x64-windows failed with: BUILD_FAILED

**Comment by PhoebeHui** [comment]
It looks similar issue with https://github.com/microsoft/vcpkg/issues/15201, the Chinese characters cause this issue, I will use that issue to track the Upstream changes.
