### ISSUE TITLE
[vtk] link error when linking agains vtk:x64-windows-static

### ISSUE THREAD

**Issue by dbonhaus** [microsoft/vcpkg#9947]
On Windows 10 using CMake 3.16.0 with Visual Studio 17, I get the following link error when building against vtk:x64-windows-static:
LINK : fatal error LNK1104: cannot open file 'pugixml.lib'
 A sample CMakeLists file is attached. The source file contains an empty main method.

[CMakeLists.txt](https://github.com/microsoft/vcpkg/files/4165911/CMakeLists.txt)

**Comment by JackBoosY** [comment]
Confirmed.

**Comment by JackBoosY** [comment]
After changing `LINK_PRIVATE` to `LINK_PUBLIC` in _SOURCE/IO/CityGML/CMakeLists.txt_ line 7, it works.

**Comment by JackBoosY** [comment]
Hi @dbonhaus, thanks for reporting this issue!
I've fixed it in #9958, please update vcpkg and rebuild vtk.

Thanks.

**Comment by dbonhaus** [comment]
Somehow I am still getting the same error. I updated my local copy of vcpkg, made sure that the relevant change was there, then reinstalled VTK (vtk:x64-windows-static) from scratch. I then deleted the cache for my sample project and reconfigured and rebuilt it, but I'm still getting the pugixml link error.

**Comment by JackBoosY** [comment]
@dbonhaus Could you provide failure log?

**Comment by dbonhaus** [comment]
The error message is not very informative:
"LINK : fatal error LNK1104: cannot open file 'pugixml.lib'"

The problem seems to be that pugixml.lib is in the project properties, but without an absolute path. I uploaded a snapshot of the linker properties in Visual Studio. Let me know if there is another log file that might be more informative and I will provide it.

![vtktest_libs](https://user-images.githubusercontent.com/3027941/74345015-68a23b00-4d7b-11ea-9708-fc659da65889.png)

**Comment by JackBoosY** [comment]
@dbonhaus 
Did you create this project yourself? vcpkg will add _VCPKG_PATH/installed/TRIPLET/lib_ / _VCPKG_PATH/installed/TRIPLET/debug/lib_ to the path `LIB_PATH` and try to link all static libraries in this path, so `pugixml.lib` should not be added by vcpkg.

**Comment by dbonhaus** [comment]
No, the project was generated by CMake (3.16.0).

**Comment by JackBoosY** [comment]
Confimed.

**Comment by manvscode** [comment]
I am having this issue after updating several packages including VTK.

**Comment by JackBoosY** [comment]
In _IO\CityGML\CMakeLists.txt_:
```
if(VTK_USE_SYSTEM_PUGIXML AND NOT pugixml_INCLUDE_DIRS)
  find_package(pugixml REQUIRED)
  vtk_module_link_libraries(vtkIOCityGML LINK_PUBLIC pugixml)
endif()
```
I think this is caused by the incorrect use of pugixml.

**Comment by JackBoosY** [comment]
@dbonhaus @manvscode 
Could you add `find_dependency(pugixml CONFIG)` to _VCPKG_PATH/installed/TRIPLET/share/VTK/VTKConfig.cmake_ line 110?

If it works, I will open a PR to fix it.

**Comment by RamanKutseika** [comment]
Hello @JackBoosY.
I having the same issue @manvscode described.
Adding `find_dependency(pugixml CONFIG)` doesn't seem to work.
![изображение](https://user-images.githubusercontent.com/57134112/76299984-0599ba80-62cd-11ea-9d3c-0b710bc87d54.png)

**Comment by JackBoosY** [comment]
@RamadanAhmed Sorry, we should include `CMakeFindDependencyMacro.cmake` first:
```
include(CMakeFindDependencyMacro)
find_dependency(pugixml CONFIG)
```

**Comment by RamanKutseika** [comment]
@JackBoosY after applying suggested changes the pugixml.lib is still missing unfortunately.

**Comment by jasjuang** [comment]
Just ran into the same problem.

What solved it temporarily for me is adding these two lines at the end of the installed `VTKConfig.cmake` 

```
include(CMakeFindDependencyMacro)
find_dependency(pugixml REQUIRED)
```

Look forward to the proper fix.

**Comment by dbonhaus** [comment]
> @dbonhaus @manvscode
> Could you add `find_dependency(pugixml CONFIG)` to _VCPKG_PATH/installed/TRIPLET/share/VTK/VTKConfig.cmake_ line 110?
> 
> If it works, I will open a PR to fix it.

I no longer see link errors involving pugixml, but I see two new ones:
1>vtkIOCore-8.2.lib(vtkLZMADataCompressor.cxx.obj) : error LNK2019: unresolved external symbol __imp_lzma_easy_buffer_encode referenced in function "protected: virtual unsigned __int64 __cdecl vtkLZMADataCompressor::CompressBuffer(unsigned char const *,unsigned __int64,unsigned char *,unsigned __int64)" (?CompressBuffer@vtkLZMADataCompressor@@MEAA_KPEBE_KPEAE1@Z)
1>vtkIOCore-8.2.lib(vtkLZMADataCompressor.cxx.obj) : error LNK2019: unresolved external symbol __imp_lzma_stream_buffer_decode referenced in function "protected: virtual unsigned __int64 __cdecl vtkLZMADataCompressor::UncompressBuffer(unsigned char const *,unsigned __int64,unsigned char *,unsigned __int64)" (?UncompressBuffer@vtkLZMADataCompressor@@MEAA_KPEBE_KPEAE1@Z)

I have the 2020.01 tag of vcpkg checked out.

**Comment by manvscode** [comment]
@JackBoosY @RamanKutseika @dbonhaus  I can confirm that adding these lines to VTKConfig.cmake, at 110, will fix the problem:

    include(CMakeFindDependencyMacro)
    find_dependency(pugixml REQUIRED)

I tested both linking debug and release binaries.  I do not see any problems with liblzma.

**Comment by JackBoosY** [comment]
@RamanKutseika Port `pugixml` gererated debug library named `pugixml.lib`, so I guess no fault here.

**Comment by JackBoosY** [comment]
@dbonhaus 
lzma library should be imported with path _${VTK_INSTALL_PREFIX}/lib/lzma.lib_ and _${VTK_INSTALL_PREFIX}/debug/lib/lzmad.lib_, you can find them in _share\vtk\Modules\vtklzma.cmake_

And `VTK_INSTALL_PREFIX` was set in `VTKConfig,cmake` line 13:
```
if (_vtk_installed_prefix_full STREQUAL _vtk_requested_prefix_full)
  set(VTK_INSTALL_PREFIX "${CMAKE_CURRENT_LIST_DIR}/../..")
else ()
  set(VTK_INSTALL_PREFIX "${CMAKE_CURRENT_LIST_DIR}")
  get_filename_component(VTK_INSTALL_PREFIX "${VTK_INSTALL_PREFIX}" PATH)
  get_filename_component(VTK_INSTALL_PREFIX "${VTK_INSTALL_PREFIX}" PATH)
endif ()
```

**Comment by JackBoosY** [comment]
Hi guys, I've fixed this issue in #10379, please update vcpkg and rebuild vtk.

Thanks.

**Comment by dbonhaus** [comment]
> @dbonhaus
> lzma library should be imported with path _${VTK_INSTALL_PREFIX}/lib/lzma.lib_ and _${VTK_INSTALL_PREFIX}/debug/lib/lzmad.lib_, you can find them in _share\vtk\Modules\vtklzma.cmake_
> 
> And `VTK_INSTALL_PREFIX` was set in `VTKConfig,cmake` line 13:
> 
> ```
> if (_vtk_installed_prefix_full STREQUAL _vtk_requested_prefix_full)
>   set(VTK_INSTALL_PREFIX "${CMAKE_CURRENT_LIST_DIR}/../..")
> else ()
>   set(VTK_INSTALL_PREFIX "${CMAKE_CURRENT_LIST_DIR}")
>   get_filename_component(VTK_INSTALL_PREFIX "${VTK_INSTALL_PREFIX}" PATH)
>   get_filename_component(VTK_INSTALL_PREFIX "${VTK_INSTALL_PREFIX}" PATH)
> endif ()
> ```

I just tried the latest vcpkg and I'm still seeing problems with lzma (but not with pugixml). I'm not sure I follow your comment. Are you saying I should explicitly specify lzma as a dependency in my CMake file? Shouldn't VTK take care of the dependency? Everything seems to be as you indicated in the VTK config files.

**Comment by JackBoosY** [comment]
@dbonhaus 
According to my comment above, `lzma` was imported through `VTK_INSTALL_PREFIX` to determine the **absolute path** of the dependent library, and the value of `VTK_INSTALL_PREFIX` is _VCPKG_PATH/installed/TRIPLET/share/vtk/../.._, then lzma library path should be _VCPKG_PATH/installed/TRIPLET/share/vtk/../../lib/lzma.lib_ and _VCPKG_PATH/installed/TRIPLET/share/vtk/../../debug/lib/lzmad.lib_.
So there should be no problem here.

Could you provide the failure log?

**Comment by dbonhaus** [comment]
Here are the link errors:
1>vtkIOCore-8.2.lib(vtkLZMADataCompressor.cxx.obj) : error LNK2019: unresolved external symbol __imp_lzma_easy_buffer_encode referenced in function "protected: virtual unsigned __int64 __cdecl vtkLZMADataCompressor::CompressBuffer(unsigned char const *,unsigned __int64,unsigned char *,unsigned __int64)" (?CompressBuffer@vtkLZMADataCompressor@@MEAA_KPEBE_KPEAE1@Z)
1>vtkIOCore-8.2.lib(vtkLZMADataCompressor.cxx.obj) : error LNK2019: unresolved external symbol __imp_lzma_stream_buffer_decode referenced in function "protected: virtual unsigned __int64 __cdecl vtkLZMADataCompressor::UncompressBuffer(unsigned char const *,unsigned __int64,unsigned char *,unsigned __int64)" (?UncompressBuffer@vtkLZMADataCompressor@@MEAA_KPEBE_KPEAE1@Z)

**Comment by JackBoosY** [comment]
@dbonhaus Could you provide the full log?

Thanks.

**Comment by dbonhaus** [comment]
I modified the test project to reproduce the error.
[vtk_test.zip](https://github.com/microsoft/vcpkg/files/4445590/vtk_test.zip)

I also included the CMake cache file. I suspect something about the CMake configuration either is the problem or triggers the problem.

**Comment by dbonhaus** [comment]
There seem to be a lot more problems with the test project associated with the use of the static run time (x64-windows-static). I added /MT to the CXX flags but it didn't help.

**Comment by JackBoosY** [comment]
Well, now I can confirm that this issue still exists and I will continue to deal with this issue.

**Comment by JackBoosY** [comment]
`__imp_lzma_easy_buffer_encode` incorrect `EXPORT` macro, I will fix this issue in the nearly futhre.

**Comment by JackBoosY** [comment]
@Neumann-A Seems the export cmake files has problem, what do you think?

**Comment by Neumann-A** [comment]
@JackBoosY: Is ParaView not built in x64-windows-static CI? I would have thought that this would have found such an issue in VTK (or LZMA).

**Comment by Neumann-A** [comment]
@JackBoosY I checked the logs of #12342 and Paraview built fine with it. Maybe the problem is linking against `VTK_LIBRARIES` instead of a target? I currently don't have a installation of VTK so I cannot check the value of `VTK_LIBRARIES`.

**Comment by JackBoosY** [comment]
@Neumann-A ParaView is not added to the pre-build process currently, and this issue appeared before adding ParaView.

@dbonhaus Does this issue still exist? Please note to use `find_package(vtk CONFIG REQUIRED)` instead of `find_package(VTK CONFIG REQUIRED)`.

**Comment by JackBoosY** [comment]
@Neumann-A ParaView is not added to the pre-build process currently, and this issue appeared before adding ParaView.

@dbonhaus Does this issue still exist? Please note to use `find_package(vtk CONFIG REQUIRED)` instead of `find_package(VTK CONFIG REQUIRED)`.

**Comment by GeneralAdmin** [comment]
I've the same issue with vcpkg using wide integration.

**Comment by JackBoosY** [comment]
@GeneralAdmin More details please?

**Comment by dbonhaus** [comment]
I no longer see any link errors as of vcpkg 2020.11 if I use find_package(VTK CONFIG REQUIRED). It doesn't work with lower case vtk. If I specify components in the find_package command, I see the link error again, but that seems like a VTK issue rather than a vcpkg issue.

**Comment by JackBoosY** [comment]
@dbonhaus thanks for the information.

**Comment by JackBoosY** [comment]
Hi @martinken, can you please take a look?
We are not sure this issue is caused by vtk itself or vcpkg.

**Comment by Neumann-A** [comment]
>I found that some cmake files start with uppercase VTK, and the rest start with lowercase vtk. I think there is something wrong here.

no it is not.....

`vtk-config.cmake` is the important one

due to its naming the config can be found via `find_package(VTK)` **AND** `find_packakge(vtk)` but this doesn't mean both are correct.  Internally VTKs config is probably using `PACKAGE_FIND_NAME` somewhere which is why lowercase vtk is not working. That said the correct way to find VTK is to always use uppercase VTK since that is used in any example by vtk itself (https://gitlab.kitware.com/vtk/vtk/-/blob/master/Examples/GUI/Qt/ImageViewer/CMakeLists.txt). 

So this issue can be closed since `find_package(VTK)` is working

**Comment by JackBoosY** [comment]
@Neumann-A At least our usage is incorrect:
```
he package vtk:x64-windows-static provides CMake targets:

    find_package(3.13 CONFIG REQUIRED)
    target_link_libraries(main PRIVATE ZLIB::ZLIB)

    find_package(3.16 CONFIG REQUIRED)
    target_link_libraries(main PRIVATE PostgreSQL::PostgreSQL)

    find_package(99 CONFIG REQUIRED)
    # Note: 36 target(s) were omitted.
    target_link_libraries(main PRIVATE X11::SM X11::Xi X11::Xt X11::Xv)

    find_package(vtk CONFIG REQUIRED)
    # Note: 159 target(s) were omitted.
    target_link_libraries(main PRIVATE LZ4::LZ4 OGG::OGG VTK::lz4 VTK::ogg)

PS F:\vcpkg>
```
