### ISSUE TITLE
Should header-only libraries provide find modules?

### ISSUE THREAD

**Issue by melak47** [Microsoft/vcpkg#995]
When installing the Microsoft/GSL (header-only) library, and trying to use it with `find_package(GSL REQUIRED)`, I noticed that the [port file](https://github.com/Microsoft/vcpkg/blob/d6d506d678273f729a86b985c3cb85c291d6751b/ports/gsl/portfile.cmake) installs no cmake find module (and also that CMake already ships with a `FindGSL.cmake` module for the GNU Scientific Library).

Since none of the [header-only libraries](https://github.com/search?utf8=%E2%9C%93&q=header-only+repo%3AMicrosoft%2Fvcpkg+extension%3A.cmake&type=Code&ref=advsearch&l=&l=) vcpkg has port files for appear to install cmake find modules,
maybe I'm misunderstanding how you're supposed to use them?
I don't really want to rely on linking a non-header-only library to pull in the `vcpkg/installed/.../include` path, or add that path manually, and just hope GSL is installed.

**Comment by ras0219-msft** [comment]
Hi @melak47!

From CMake, the best way to handle header-only libraries that don't provide native integration is to use `find_path`[1]:

```cmake
# Here, gsl/gsl should be whatever X you want to write as `#include <X>`
find_path(GSL_INCLUDE_DIR gsl/gsl)
if(GSL_INCLUDE_DIR STREQUAL "GSL_INCLUDE_DIR-NOTFOUND")
  message(FATAL_ERROR "Could not find Guidelines Support Library.")
endif()
include_directories(${GSL_INCLUDE_DIR})
```

This has the advantage that it will work on every system, not just Vcpkg. We also have a more full explanation in our Examples.md[2] that also shows how to handle non-header-only libraries that don't have CMake integration.

[1] https://cmake.org/cmake/help/latest/command/find_path.html
[2] https://github.com/Microsoft/vcpkg/blob/5d3f6a79b441b6a614debd63c9990170eb772625/docs/EXAMPLES.md#option-b-cmake-toolchain-file

**Comment by melak47** [comment]
Thanks, that makes some sense.

> From CMake, the best way to handle header-only libraries **that don't provide native integration** is to use find_path[1]

GSL does have a [CMakeLists.txt](https://github.com/Microsoft/GSL/blob/8b320e3f5d016f953e55dfc7ec8694c1349d3fe4/CMakeLists.txt), though -- it creates an `INTERFACE` library target, which is easy to use with `add_subdirectory`. What would be needed for "native integration"?

Would it not be possible to `install(gsl EXPORT ...)` this target and make it discoverable with `find_package` (assuming the naming conflict is solved somehow)?
Then you could simply "link" `gsl` and not have to care that it's header-only.

I'm not sure if this would require changes to GSL's CMakeLists.txt or just the portfile, or even if this behavior would be desirable (or the Right Thing™ in CMake land) -- I'm just asking.

**Comment by ras0219-msft** [comment]
Yeah, some sort of `install(gsl EXPORT)` would be what's required. I think the contents of https://github.com/Microsoft/GSL/pull/467 would be sufficient, however there are two problems:
1. The name "gsl" conflicts with the GNU Scientific Library as you found out. CMake already ships with a "FindGSL.cmake", so it needs to export under a name that isn't GSL. In the PR above, the GSL owners did not want to rename the library, so some discussion will probably be needed to resolve this.
2. We (Vcpkg) want to avoid extending upstream projects in a way that isn't guaranteed to be forward compatible. Adding native CMake support requires making a lot of choices about naming/etc that could conflict, so upstream really needs to add it first.

Issue #616 is related to this.

**Comment by ras0219-msft** [comment]
Notice: the Guidelines Support Library port has been renamed to `ms-gsl`, to relinquish the name `gsl` for the GNU Scientific Library.

**Comment by DeveloperPaul123** [comment]
A quick fix that I rolled was just writing my own cmake find module for `ms-gsl`. Something like this: 

````cmake
find_path(MS_GSL_INCLUDE_DIR gsl/gsl)
if(MS_GSL_INCLUDE_DIR STREQUAL "GSL_INCLUDE_DIR-NOTFOUND")
  message(FATAL_ERROR "Could not find Guidelines Support Library.")
  set(MS_GSL_FOUND FALSE)
endif()

set(MS_GSL_FOUND TRUE)

if(MS_GSL_FOUND)
    include(FindPackageHandleStandardArgs)
    find_package_handle_standard_args(ms-gsl
        REQUIRED_VARS MS_GSL_INCLUDE_DIR
        FOUND_VAR ms-gsl_FOUND
        FAIL_MESSAGE "Failed to find ms-gsl")

    if(NOT TARGET ms-gsl)
        add_library(ms-gsl INTERFACE IMPORTED)
        set_target_properties(ms-gsl PROPERTIES
            INTERFACE_INCLUDE_DIRECTORIES ${MS_GSL_INCLUDE_DIR})
    endif(NOT TARGET ms-gsl)

    mark_as_advanced(MS_GSL_INCLUDE_DIR)

endif(MS_GSL_FOUND)
````
You can add this ^ file as `Findms-gsl.cmake` in your project and then it'll auto find the library and create a target for you if you install `ms-gsl` with `vcpkg`.
