### ISSUE TITLE
vcpkg_from_git does not work

### ISSUE THREAD

**Issue by kreuzerkrieg** [microsoft/vcpkg#9951]
Ubuntu 18.04

1) The below code does not work
```
vcpkg_from_git(
        OUT_SOURCE_PATH SOURCE_PATH
        URL https://git.savannah.gnu.org/git/gsasl.git
        REF c8cfe3e57e08f483056abcdfd37d46c4fe242b13
)

```

I can `git clone` it, but for some reason `vcpkg` gives me

> -- Fetching https://git.savannah.gnu.org/git/gsasl.git...
> CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:58 (file):
>   file failed to open for reading (No such file or directory):

2) the above failure states that there is a log at .../vcpkg/buildtrees/gsasl/git-init-x64-linux-out.log
however no log created

**Comment by NancyLi1013** [comment]
Hi @kreuzerkrieg thanks for posting this issue.
Could you please help confirm which port you used?

**Comment by NancyLi1013** [comment]
I try 
```
vcpkg_from_git(
    OUT_SOURCE_PATH SOURCE_PATH
    URL https://android.googlesource.com/platform/external/fdlibm
    REF 59f7335e4dd8275a7dc2f8aeb4fd00758fde37ac
)
```
and
```
vcpkg_from_git(
    OUT_SOURCE_PATH SOURCE_PATH
    URL https://git.assembla.com/portaudio.git
    REF c5d2c51bd6fe354d0ee1119ba932bfebd3ebfacc
    PATCHES
        fix-library-can-not-be-found.patch
        fix-include.patch
)
```
Both of them can work.
So `vcpkg_from_git()` should work normally.
Please check your code again.

**Comment by kreuzerkrieg** [comment]
Odd, today it just worked
Thanks for your assistance
