### ISSUE TITLE
[freetype] (Linux) Wrong INTERFACE_LINK_LIBRARIES in config 

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#9952]
```
set_target_properties(freetype PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include;${_IMPORT_PREFIX}/include/freetype"
  INTERFACE_LINK_LIBRARIES "/mnt/d/xlinux/installed/x64-linux/debug/lib/libz.a;\$<\$<NOT:\$<CONFIG:DEBUG>>:/mnt/d/xlinux/installed/x64-linux/lib/libbz2.a>;\$<\$<CONFIG:DEBUG>:/mnt/d/xlinux/installed/x64-linux/debug/lib/libbz2d.a>;\$<\$<NOT:\$<CONFIG:DEBUG>>:/mnt/d/xlinux/installed/x64-linux/debug/lib/libpng.a>;\$<\$<CONFIG:DEBUG>:/mnt/d/xlinux/installed/x64-linux/debug/lib/libpng16d.a>;/mnt/d/xlinux/installed/x64-linux/debug/lib/libz.a"
)
```
entry: /mnt/d/xlinux/installed/x64-linux/debug/lib/libz.a missing generator expression for debug/release. Links only debug

**Comment by JackBoosY** [comment]
I have a bad hunch: Is this issue a common issue?

**Comment by Neumann-A** [comment]
Yeah that is a common issue if you do not use targets but link libraries directly in VCPKG.
This also happens if the variable used does not have the optimized/debug keywords. In general it would require a `vcpkg-cmake-wrapper.cmake` for the upstream port (zlib) to correctly fix the `<var>_LIBRARIES`. 
Such issues could be automatically detected as mentioned in  #12215 (last comment paragraph in the changeset)

**Comment by JackBoosY** [comment]
@Neumann-A So I assume your PR can fix this issue, right?

**Comment by Neumann-A** [comment]
@JackBoosY: which one? #12215? No that one adds only and option to deactivate the prefix correction nothing more.
