### ISSUE TITLE
[G2O] update to <Nov 23, 2019>

### ISSUE THREAD

**Issue by Lecanyu** [microsoft/vcpkg#9959]
Library name: g2o: A General Framework for Graph Optimization

New version number: The newest github repository (Nov 23, 2019)

Please update this library since current vcpkg will install a version in 20170730_git-5 which is deprecated and it doesn't support some important features like auto_ptr in non-linear optimization.

**Comment by PhoebeHui** [comment]
@Lecanyu, thanks for reporting this issue, g2o has updated to latest revision.
