### ISSUE TITLE
Cannot static link to cpprestsdk 2.9

### ISSUE THREAD

**Issue by fuocor** [microsoft/vcpkg#996]
The vcpkg static build of the cpprestsdk is emitting a number of __declspec(dllimport) statements.

`1>test_site_json.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl web::uri::uri(wchar_t const *)" (__imp_??0uri@web@@QEAA@PEB_W@Z) referenced in function "void __cdecl core_test::____C_A_T_C_H____T_E_S_T____0(void)" (?____C_A_T_C_H____T_E_S_T____0@core_test@@YAXXZ)
1>test_site_json.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl web::uri::uri(class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> > const &)" (__imp_??0uri@web@@QEAA@AEBV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@@Z) referenced in function "void __cdecl core_test::____C_A_T_C_H____T_E_S_T____0(void)" (?____C_A_T_C_H____T_E_S_T____0@core_test@@YAXXZ)
1>test_site_json.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: bool __cdecl web::uri::operator==(class web::uri const &)const " (__imp_??8uri@web@@QEBA_NAEBV01@@Z) referenced in function "public: static bool __cdecl Catch::Internal::Evaluator<class web::uri,class web::uri,0>::evaluate(class web::uri const &,class web::uri const &)" (?evaluate@?$Evaluator@Vuri@web@@V12@$0A@@Internal@Catch@@SA_NAEBVuri@web@@0@Z)
`

This seems to be related to [https://github.com/Microsoft/cpprestsdk/issues/344](https://github.com/Microsoft/cpprestsdk/issues/344) 

regards

**Comment by ras0219-msft** [comment]
Hi @fuocor,

Have you tried the response in Microsoft/cpprestsdk#344? It's correct and would result in this issue.

In vcpkg, we _should_ stamp something into our produced headers so you don't need to define the `_NO_ASYNCRTIMP` macro.
