### ISSUE TITLE
disableMetrics flag does not work

### ISSUE THREAD

**Issue by needfulthing** [microsoft/vcpkg#9962]
**Describe the bug**
See subject

**Environment**
- OS: Windows 10
- Cloned from repo 01/25/20

**To Reproduce**
0. AV program installed...
1. Install with "bootstrap-vcpkg.bat -disableMetrics"
2. Install any package.
3. Watch AV heuristics alarming over vcpkg.exe...

**Expected behavior**
No hidden connections with Microsoft. No data transfer.

**Additional context**
See https://github.com/microsoft/vcpkg/issues/3345.
Why has this ticket been closed?!

**Comment by Neumann-A** [comment]
alternative options:
run `vcpkg` with option `--no-sendmetrics`
maybe delete `vcpkgmetricsuploader.exe` from `scripts/`

**Comment by MikeGitb** [comment]
Are you sure it doesn't work (as opposed to some problem with the AV heuristics?)

**Comment by timautry** [comment]
.\bootstrap-vcpkg.bat -verbose -disableMetrics -win64 -withVSPath "'%VCPKG_VISUAL_STUDIO_PATH%'"
I can confirm all 4 of these options, including "-disableMetrics" works as advertised. 
Check your profile's TEMP/TMP directory will have a folder called vcpkg, containing the metrics executable and tons of files from each of your port installations when its working, when not, the vcpkg folder will not exist.
Note: many AV solutions in their most stringent configurations detect vcpkg and the metrics programs as questionable and will attempt to quarantine/remove them - one will need to enter exceptions to the AV solution configuration or revert to Windows Defender, which seems to realize these are legit development tools.
It seems AV solution providers tend to forget/consider some PCs/Laptops/Servers can be used for constructive development work and not malicious software.

**Comment by PhoebeHui** [comment]
@timautry, thanks for your Comments!

Confirmed that .\bootstrap-vcpkg.bat -disableMetrics also works as expected for me. I'm not sure what vcpkg could do here.

@needfulthing, do you mind to close this issue?

**Comment by needfulthing** [comment]
Very strange, can it be that if I first installed without the -disableMetrics and then ran the batch again with the parameter, it does not work? I will try again and if you're right, I'll close the ticket.

**Comment by ahmad2smile** [comment]
Default active telemetry is wrong. It should be disabled by default.

This is immoral, in any product:

> You can opt-out of telemetry by re-running bootstrap-vcpkg.bat with -disableMetrics

**Comment by PhoebeHui** [comment]
@needfulthing, feel free reopen this issue if it still be a problem for you.
