### ISSUE TITLE
Poco update 1.10.0

### ISSUE THREAD

**Issue by TheGrandNagus** [microsoft/vcpkg#9964]
Poco 1.10.0 has been released. It would be awsome if you could update to this version.

Some notes:

Version 1.10.0 is not on the master branch but has its own branch (poco-1.10.0-release).

Updating the CONTROL and portfile.cmake will not suffice. The patches also do need adjustment.

**Comment by PhoebeHui** [comment]
The PR has been merged, Poco currently upgrade to 1.10.1.
