### ISSUE TITLE
Error: Building package ffmpeg:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by thakur-d-ani** [microsoft/vcpkg#9967]
**Describe the bug**

installing opencv

**Environment**
- OS: [e.g. Windows :- 10

**To Reproduce**
1. ./vcpkg install pthreads opencv[ffmpeg]

**Expected behavior**
Installing package ffmpeg:x64-windows..  done

**Failure logs** 
-Steps to reproduce the behavior:
1. ./vcpkg install pthreads opencv[ffmpeg]
PS G:\program\vcpkg-master\vcpkg-master> .\vcpkg install pthreads opencv[ffmpeg]
Computing installation plan...
The following packages will be built and installed:
  * ffmpeg[avresample,core]:x64-windows
  * libjpeg-turbo[core]:x64-windows
  * libpng[core]:x64-windows
  * libwebp[core,nearlossless,simd,unicode]:x64-windows
    opencv[core,dnn,ffmpeg,jpeg,opengl,png,tiff,webp]:x64-windows
  * opencv4[core,dnn,ffmpeg,jpeg,opengl,png,tiff,webp]:x64-windows
  * opengl[core]:x64-windows
  * protobuf[core]:x64-windows
    pthreads[core]:x64-windows
  * tiff[core]:x64-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/10: ffmpeg:x64-windows
Building package ffmpeg[avresample,core]:x64-windows...
-- Using cached G:/program/vcpkg-master/vcpkg-master/downloads/ffmpeg-ffmpeg-n4.2.tar.gz
-- Using source at G:/program/vcpkg-master/vcpkg-master/buildtrees/ffmpeg/src/n4.2-b7812eeecc
-- Acquiring MSYS Packages...
-- Acquiring MSYS Packages... OK
-- Building Options: --enable-asm --enable-yasm --disable-doc --enable-debug --enable-runtime-cpudetect --disable-openssl --disable-ffmpeg --disable-ffplay --disable-ffprobe --disable-libvpx --disable-libx264 --disable-opencl --disable-lzma --disable-bzlib --enable-avresample  --disable-static --enable-shared --extra-cflags=-DHAVE_UNISTD_H=0
-- Building Release Options:  --extra-cflags=-MD --extra-cxxflags=-MD
-- Building ffmpeg for Release
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: G:/program/vcpkg-master/vcpkg-master/downloads/tools/msys2/msys64/usr/bin/bash.exe --noprofile --norc G:/program/vcpkg-master/vcpkg-master/ports/ffmpeg\build.sh G:/program/vcpkg-master/vcpkg-master/buildtrees/ffmpeg/x64-windows-rel G:/program/vcpkg-master/vcpkg-master/buildtrees/ffmpeg/src/n4.2-b7812eeecc G:/program/vcpkg-master/vcpkg-master/packages/ffmpeg_x64-windows "--enable-asm --enable-yasm --disable-doc --enable-debug --enable-runtime-cpudetect --disable-openssl --disable-ffmpeg --disable-ffplay --disable-ffprobe --disable-libvpx --disable-libx264 --disable-opencl --disable-lzma --disable-bzlib --enable-avresample  --disable-static --enable-shared --extra-cflags=-DHAVE_UNISTD_H=0  --extra-cflags=-MD --extra-cxxflags=-MD"
    Working Directory: G:/program/vcpkg-master/vcpkg-master/buildtrees/ffmpeg/x64-windows-rel
    Error code: 2
    See logs for more information:
      G:\program\vcpkg-master\vcpkg-master\buildtrees\ffmpeg\build-x64-windows-rel-out.log
      G:\program\vcpkg-master\vcpkg-master\buildtrees\ffmpeg\build-x64-windows-rel-err.log

Call Stack (most recent call first):
  ports/ffmpeg/portfile.cmake:193 (vcpkg_execute_required_process)
  scripts/ports.cmake:90 (include)

Error: Building package ffmpeg:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: ffmpeg:x64-windows
  Vcpkg version: 2020.02.04-nohash

Additionally, attach any relevant sections from the log files above.
PS G:\program\vcpkg-master\vcpkg-master> .\vcpkg update
Using local portfile versions. To update the local portfiles, use `git pull`.
No packages need updating.

rel out.log :-

G:\program\vcpkg-master\vcpkg-master\buildtrees\ffmpeg\x64-windows-rel\libavutil/avconfig.h(4): fatal error C1070: mismatched #if/#endif pair in file 'g:\program\vcpkg-master\vcpkg-master\buildtrees\ffmpeg\x64-windows-rel\libavutil\avconfig.h'
dshow.c
CC	libavdevice/dshow_common.o
dshow_enummediatypes.c
dshow_common.c
G:\program\vcpkg-master\vcpkg-master\buildtrees\ffmpeg\x64-windows-rel\libavutil/avconfig.h(4): fatal error C1070: mismatched #if/#endif pair in file 'g:\program\vcpkg-master\vcpkg-master\buildtrees\ffmpeg\x64-windows-rel\libavutil\avconfig.h'
G:\program\vcpkg-master\vcpkg-master\buildtrees\ffmpeg\x64-windows-rel\libavutil/avconfig.h(4): fatal error C1070: mismatched #if/#endif pair in file 'g:\program\vcpkg-master\vcpkg-master\buildtrees\ffmpeg\x64-windows-rel\libavutil\avconfig.h'
CC	libavdevice/alldevices.o
G:\program\vcpkg-master\vcpkg-master\buildtrees\ffmpeg\x64-windows-rel\libavutil/avconfig.h(4): fatal error C1070: mismatched #if/#endif pair in file 'g:\program\vcpkg-master\vcpkg-master\buildtrees\ffmpeg\x64-windows-rel\libavutil\avconfig.h'
G:\program\vcpkg-master\vcpkg-master\buildtrees\ffmpeg\x64-windows-rel\libavutil/avconfig.h(4): fatal error C1070: mismatched #if/#endif pair in file 'g:\program\vcpkg-master\vcpkg-master\buildtrees\ffmpeg\x64-windows-rel\libavutil\avconfig.h'
alldevices.c
G:\program\vcpkg-master\vcpkg-master\buildtrees\ffmpeg\x64-windows-rel\libavutil/avconfig.h(4): fatal error C1070: mismatched #if/#endif pair in file 'g:\program\vcpkg-master\vcpkg-master\buildtrees\ffmpeg\x64-windows-rel\libavutil\avconfig.h'

rel-err.log

make: *** [/g/program/vcpkg-master/vcpkg-master/buildtrees/ffmpeg/src/n4.2-b7812eeecc/ffbuild/common.mak:59: libavdevice/avdevice.o] Error 2
make: *** Waiting for unfinished jobs....
make: *** [/g/program/vcpkg-master/vcpkg-master/buildtrees/ffmpeg/src/n4.2-b7812eeecc/ffbuild/common.mak:59: libavdevice/dshow_crossbar.o] Error 2
make: *** [/g/program/vcpkg-master/vcpkg-master/buildtrees/ffmpeg/src/n4.2-b7812eeecc/ffbuild/common.mak:59: libavdevice/dshow.o] Error 2
make: *** [/g/program/vcpkg-master/vcpkg-master/buildtrees/ffmpeg/src/n4.2-b7812eeecc/ffbuild/common.mak:59: libavdevice/dshow_enummediatypes.o] Error 2
make: *** [/g/program/vcpkg-master/vcpkg-master/buildtrees/ffmpeg/src/n4.2-b7812eeecc/ffbuild/common.mak:59: libavdevice/dshow_common.o] Error 2
make: *** [/g/program/vcpkg-master/vcpkg-master/buildtrees/ffmpeg/src/n4.2-b7812eeecc/ffbuild/common.mak:59: libavdevice/alldevices.o] Error 2

**Additional context**

**Comment by LilyWangL** [comment]
@thakur-d-ani Sorry I am late. Does this issue occur? I can installed `ffmpeg:x64-windows` successfully with the latest VCPKG.

**Comment by LilyWangL** [comment]
Thanks for posting this issue. Please reopen this issue if it still be a problem for you.

**Comment by ramsan1989** [comment]
@LilyWangL Still I face the same error.

PS C:\vcpkg> .\vcpkg install pthreads opencv[ffmpeg] --triplet x64-windows
Computing installation plan...
The following packages will be built and installed:
  * ffmpeg[avcodec,avdevice,avfilter,avformat,avresample,core,postproc,swresample,swscale]:x64-windows
  * libjpeg-turbo[core]:x64-windows
  * liblzma[core]:x64-windows
  * libpng[core]:x64-windows
  * libwebp[core,nearlossless,simd,unicode]:x64-windows
    opencv[core,dnn,ffmpeg,jpeg,opengl,png,tiff,webp]:x64-windows
  * opencv4[core,dnn,ffmpeg,jpeg,opengl,png,tiff,webp]:x64-windows
  * opengl[core]:x64-windows
  * protobuf[core]:x64-windows
    pthreads[core]:x64-windows
  * tiff[core]:x64-windows
  * zlib[core]:x64-windows
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Starting package 1/12: ffmpeg:x64-windows
Building package ffmpeg[avcodec,avdevice,avfilter,avformat,avresample,core,postproc,swresample,swscale]:x64-windows...
Could not locate cached archive: C:\Users\rames\AppData\Local\vcpkg/archives\0f\0fb7795f7e48a4f5ca16b374e2d89a705de25817.zip
-- Using cached C:/vcpkg/downloads/ffmpeg-ffmpeg-n4.2.tar.gz
-- Cleaning sources at C:/vcpkg/buildtrees/ffmpeg/src/n4.2-2f6d2343f6.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/vcpkg/downloads/ffmpeg-ffmpeg-n4.2.tar.gz
-- Applying patch 0001-create-lib-libraries.patch
-- Applying patch 0003-fix-windowsinclude.patch
-- Applying patch 0004-fix-debug-build.patch
-- Applying patch 0005-fix-libvpx-linking.patch
-- Applying patch 0006-fix-StaticFeatures.patch
-- Applying patch 0007-fix-lib-naming.patch
-- Applying patch 0008-Fix-wavpack-detection.patch
-- Applying patch 0009-Fix-fdk-detection.patch
-- Applying patch 0010-Fix-x264-detection.patch
-- Applying patch 0011-Fix-x265-detection.patch
-- Applying patch 0012-Fix-ssl-110-detection.patch
-- Using source at C:/vcpkg/buildtrees/ffmpeg/src/n4.2-2f6d2343f6.clean
-- Acquiring MSYS Packages from C:/vcpkg/downloads/tools/msys2-20200812...
-- Acquiring MSYS Packages... OK
-- Building Options: --enable-asm --enable-yasm --disable-doc --enable-debug --enable-runtime-cpudetect --disable-ffmpeg --disable-ffplay --disable-ffprobe --enable-avcodec --enable-avdevice --enable-avformat --enable-avfilter --enable-postproc --enable-swresample --enable-swscale --enable-avresample --disable-avisynth --disable-bzlib --disable-iconv --disable-libfdk-aac --disable-lzma --disable-libmp3
-- Building Release Options:  --extra-cflags=-MD --extra-cxxflags=-MD
-- Building ffmpeg for Release
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: C:/vcpkg/downloads/tools/msys2-20200812/msys64/usr/bin/bash.exe --noprofile --norc C:/vcpkg/ports/ffmpeg\build.sh C:/vcpkg/buildtrees/ffmpeg/x64-windows-rel C:/vcpkg/buildtrees/ffmpeg/src/n4.2-2f6d2343f6.clean C:/vcpkg/packages/ffmpeg_x64-windows "--enable-asm --enable-yasm --disable-doc --enable-debug --enable-runtime-cpudetect --disable-ffmpeg --disable-ffplay --disable-ffprobe --enable-avcodec --enable-avdevice --enable-avformat --enable-avfilter --enable-postproc --enable-swresample --enable-swscale --enable-avresample --disable-avisynth --disable-bzlib --disable-iconv --disable-libfdk-aac --disable-lzma --disable-libmp3lame --disable-cuda --disable-nvenc --disable-nvdec  --disable-cuvid --disable-opencl --disable-openssl --disable-libopus --disable-sdl2 --disable-libsnappy --disable-libsoxr --disable-libspeex --disable-libtheora --disable-libvorbis --disable-libvpx --disable-libwavpack --disable-libx264 --disable-libx265 --disable-zlib  --disable-static --enable-shared --extra-cflags=-DHAVE_UNISTD_H=0  --extra-cflags=-MD --extra-cxxflags=-MD"
    Working Directory: C:/vcpkg/buildtrees/ffmpeg/x64-windows-rel
    Error code: 2
    See logs for more information:
      C:\vcpkg\buildtrees\ffmpeg\build-x64-windows-rel-out.log
      C:\vcpkg\buildtrees\ffmpeg\build-x64-windows-rel-err.log

Call Stack (most recent call first):
  ports/ffmpeg/portfile.cmake:394 (vcpkg_execute_required_process)
  scripts/ports.cmake:79 (include)


Error: Building package ffmpeg:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: ffmpeg:x64-windows
  Vcpkg version: 2020.06.15-nohash

**Comment by LilyWangL** [comment]
@ramsan1989 Please provide the error log:
```
C:\vcpkg\buildtrees\ffmpeg\build-x64-windows-rel-out.log
C:\vcpkg\buildtrees\ffmpeg\build-x64-windows-rel-err.log
```

**Comment by boralprophecy** [comment]
@LilyWangL Faced this issue.

**Command** : .\vcpkg install pthreads opencv[ffmpeg]

Attaching logs
[build-x64-windows-rel-err.log](https://github.com/microsoft/vcpkg/files/5226783/build-x64-windows-rel-err.log)
[build-x64-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/5226785/build-x64-windows-rel-out.log)

**Comment by LilyWangL** [comment]
@boralprophecy Thanks for your reply. Ffmpeg will update to version 4.3.1 in PR #13365. Waiting for this PR merged, please rebuild ffmpeg, if you install new ffmpeg failed, you can open a new issue to report.
