### ISSUE TITLE
[shogun:x64-linux] cmake and build failure

### ISSUE THREAD

**Issue by mhangaard** [microsoft/vcpkg#9969]
**Host Environment**
- OS: Linux
- `$ cmake --version`
```
cmake version 3.10.2
CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

**To Reproduce**
`./vcpkg install shogun`
Go to `project` folder.
CMakeLists:
```
cmake_minimum_required(VERSION 3.0)
project(project)

find_package(Sqlite3 REQUIRED)
find_package(Shogun CONFIG REQUIRED)

add_executable(main test.cpp)
target_link_libraries(main sqlite3 shogun::shogun-static)
```
and then
```
$ cmake -DCMAKE_TOOLCHAIN_FILE=/home/mh/src/vcpkg/scripts/buildsystems/vcpkg.cmake
```

**Failure logs** 
```
CMake Error at /home/mh/src/vcpkg/installed/x64-linux/share/shogun/ShogunConfig.cmake:31 (include):
  include could not find load file:

    /home/mh/src/vcpkg/installed/x64-linux/lib/cmake/shogun/ShogunTargets.cmake
Call Stack (most recent call first):
  /home/mh/src/vcpkg/scripts/buildsystems/vcpkg.cmake:285 (_find_package)
  CMakeLists.txt:5 (find_package)
```

**Additional context**
In `vcpkg/installed/x64-linux/share/shogun/ShogunConfig.cmake`, line 31 says:
```
include("${PACKAGE_PREFIX_DIR}/lib/cmake/shogun/ShogunTargets.cmake")
```
and there is no such file, but actually `${PACKAGE_PREFIX_DIR}/share/shogun/ShogunTargets.cmake` exists. If I modify the above to point to that, cmake completes without errors, (but another error occurs on make, not locating libsnappy.a, probably unrelated).

**Comment by NancyLi1013** [comment]
Hi @mhangaard 

Thanks for posting this issue and your patience.
This issue should be fixed now. Please update vcpkg and build it agian.
