### ISSUE TITLE
 ffmpeg[gpl]:ARM-uwp build failure

### ISSUE THREAD

**Issue by Noemata** [microsoft/vcpkg#9973]
**Host Environment**
- OS: Windows 1909 (OS Build 18363.628)
- Compiler: VS2019 Version 16.3.9

**To Reproduce**
`.\vcpkg install ffmpeg[gpl]:ARM-uwp --recurse`

**Failure logs** 
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: D:/vcpkg/downloads/tools/msys2/msys64/usr/bin/bash.exe --noprofile --norc D:/vcpkg/ports/ffmpeg\build.sh D:/vcpkg/buildtrees/ffmpeg/arm-uwp-rel D:/vcpkg/buildtrees/ffmpeg/src/n4.2-b7812eeecc D:/vcpkg/packages/ffmpeg_arm-uwp "--enable-asm --enable-yasm --disable-doc --enable-debug --enable-runtime-cpudetect --enable-gpl --disable-openssl --disable-ffmpeg --disable-ffplay --disable-ffprobe --disable-libvpx --disable-libx264 --disable-opencl --disable-lzma --disable-bzlib --enable-avresample --disable-programs --extra-cflags=-DWINAPI_FAMILY=WINAPI_FAMILY_APP --extra-cflags=-D_WIN32_WINNT=0x0A00  --enable-cross-compile --target-os=win32 --arch=arm --disable-static --enable-shared --extra-ldflags=-APPCONTAINER --extra-ldflags=WindowsApp.lib --extra-cflags=-DHAVE_UNISTD_H=0  --extra-cflags=-MD --extra-cxxflags=-MD"
    Working Directory: D:/vcpkg/buildtrees/ffmpeg/arm-uwp-rel
    Error code: 2
    See logs for more information:
      D:\vcpkg\buildtrees\ffmpeg\build-arm-uwp-rel-out.log
      D:\vcpkg\buildtrees\ffmpeg\build-arm-uwp-rel-err.log

Call Stack (most recent call first):
  ports/ffmpeg/portfile.cmake:193 (vcpkg_execute_required_process)
  scripts/ports.cmake:90 (include)

Error: Building package ffmpeg:arm-uwp failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: ffmpeg:arm-uwp
  Vcpkg version: 2020.02.04-nohash-external

**Additional context**
These build without issue:
.\vcpkg install ffmpeg[gpl]:x64-uwp --recurse
.\vcpkg install ffmpeg[gpl]:x86-uwp --recurse

**Comment by LilyWangL** [comment]
Sorry I am late. Does this issue occur? I can install `ffmpeg[gpl]:arm-uwp` successfully with the latest VCPKG. If you install it failed, please provide the error log `build-arm-uwp-rel-out.log`.

**Comment by Noemata** [comment]
I believe this was resolved with current releases.  If you have just tried it @LilyWangL, then I'll assume builds are working.

**Comment by LilyWangL** [comment]
Thanks for posting this issue. This issue has been fixed. So I am closing this issue for now.
