### ISSUE TITLE
Error: Building package boost-math:x86-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by dljjqy** [microsoft/vcpkg#9977]
Package: boost-math:x86-windows
Vcpkg version: 2020.02.04-nohash

**Comment by PhoebeHui** [comment]
@dljjqy, sorry for my late reply.

Does this still be a problem for you? I can't repro this issue with latest vcpkg and vs2017.

PS F:\vcpkg\src> ./vcpkg install boost-math:x86-windows
Computing installation plan...
The following packages will be built and installed:
    boost-math[core]:x86-windows
Starting package 1/1: boost-math:x86-windows
Building package boost-math[core]:x86-windows...
-- Using cached F:/VCPKG/src/downloads/boostorg-math-boost-1.72.0.tar.gz
-- Using source at F:/VCPKG/src/buildtrees/boost-math/src/ost-1.72.0-2786b6df16
-- Building x86-windows-rel
-- Building x86-windows-rel done
-- Building x86-windows-dbg
-- Building x86-windows-dbg done
-- Packaging x86-windows-rel
-- Packaging x86-windows-rel done
-- Packaging x86-windows-dbg
-- Packaging x86-windows-dbg done
-- Packaging headers
-- Packaging headers done
-- Using cached F:/VCPKG/src/downloads/boost_LICENSE_1_0.txt
-- Installing: F:/VCPKG/src/packages/boost-math_x86-windows/share/boost-math/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package boost-math[core]:x86-windows... done
Installing package boost-math[core]:x86-windows...
Installing package boost-math[core]:x86-windows... done
Elapsed time for package boost-math:x86-windows: 2.491 min

Total elapsed time: 2.491 min

**Comment by PedroSbeghen** [comment]
Hello, I'm with the same problem, but with the version x64

>  C:\xxxx\xxxx\vcpkg>vcpkg install boost-asio
> Computing installation plan...
> The following packages will be built and installed:
>     boost-asio[core]:x86-windows
>   * boost-context[core]:x86-windows
>   * boost-coroutine[core]:x86-windows
>   * boost-date-time[core]:x86-windows
>   * boost-math[core]:x86-windows
>   * boost-thread[core]:x86-windows
>   * boost-tokenizer[core]:x86-windows
>   * openssl[core]:x86-windows
>   * openssl-windows[core]:x86-windows
> Additional packages (*) will be modified to complete this operation.
> Starting package 1/9: boost-math:x86-windows
> Building package boost-math[core]:x86-windows...
> -- Using cached C:/xxxx/xxxx/vcpkg/downloads/boostorg-math-boost-1.72.0.tar.gz
> -- Extracting source C:/xxxx/xxxx/vcpkg/downloads/boostorg-math-boost-1.72.0.tar.gz
> CMake Error at scripts/cmake/vcpkg_extract_source_archive_ex.cmake:140 (file):
>   file RENAME failed to rename
> 
>     C:/xxxx/xxxx/vcpkg/buildtrees/boost-math/src/TEMP/math-boost-1.72.0
> 
>   to
> 
>     C:/xxxx/xxxx/vcpkg/buildtrees/boost-math/src/ost-1.72.0-2786b6df16
> 
>   because: No such file or directory
> 
> Call Stack (most recent call first):
>   scripts/cmake/vcpkg_from_github.cmake:139 (vcpkg_extract_source_archive_ex)
>   ports/boost-math/portfile.cmake:5 (vcpkg_from_github)
>   scripts/ports.cmake:90 (include)
> 
> 
> Error: Building package boost-math:x86-windows failed with: BUILD_FAILED
> Please ensure you're using the latest portfiles with `.\vcpkg update`, then
> submit an issue at https://github.com/Microsoft/vcpkg/issues including:
>   Package: boost-math:x86-windows
>   Vcpkg version: 2020.02.04-nohash
>

**Comment by HLXEasy** [comment]
I spot the same issue:

```
Starting package 1/9: boost-math:x86-windows
Building package boost-math[core]:x86-windows...
-- Using cached D:/coding/vcpkg/downloads/boostorg-math-boost-1.72.0.tar.gz
-- Extracting source D:/coding/vcpkg/downloads/boostorg-math-boost-1.72.0.tar.gz
CMake Error at scripts/cmake/vcpkg_extract_source_archive_ex.cmake:140 (file):
  file RENAME failed to rename

    D:/coding/vcpkg/buildtrees/boost-math/src/TEMP/math-boost-1.72.0

  to

    D:/coding/vcpkg/buildtrees/boost-math/src/ost-1.72.0-2786b6df16

  because: No such file or directory

Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_github.cmake:139 (vcpkg_extract_source_archive_ex)
  ports/boost-math/portfile.cmake:5 (vcpkg_from_github)
  scripts/ports.cmake:90 (include)


Error: Building package boost-math:x86-windows failed with: BUILD_FAILED
```

If I copy the folder `D:\coding\vcpkg\buildtrees\boost-math\src\TEMP\math-boost-1.72.0` one folder level up, rename it to `ost-1.72.0-2786b6df16` and restart the build, the lib could be built. But that's not a solution...

**Comment by buliasz** [comment]
I have problem with this package too. My output:
`D:\vcpkg>.\vcpkg install boost-math:x86-windows
Computing installation plan...
The following packages will be built and installed:
    boost-math[core]:x86-windows
Starting package 1/1: boost-math:x86-windows
Building package boost-math[core]:x86-windows...
-- Using cached D:/vcpkg/downloads/boostorg-math-boost-1.72.0.tar.gz
-- Using source at D:/vcpkg/buildtrees/boost-math/src/ost-1.72.0-2786b6df16
-- Building x86-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: D:/vcpkg/installed/x86-windows/tools/boost-build/b2.exe --stagedir=D:/vcpkg/buildtrees/boost-math/x86-windows-rel/stage --build-dir=D:/vcpkg/buildtrees/boost-math/x86-windows-rel --user-config=D:/vcpkg/buildtrees/boost-math/x86-windows-rel/user-config.jam -j12 --debug-configuration --debug-building --debug-generators --disable-icu --ignore-site-config --hash -q -sZLIB_INCLUDE=D:/vcpkg/installed/x86-windows/include -sBZIP2_INCLUDE=D:/vcpkg/installed/x86-windows/include -sLZMA_INCLUDE=D:/vcpkg/installed/x86-windows/include -sZSTD_INCLUDE=D:/vcpkg/installed/x86-windows/include threading=multi threadapi=win32 runtime-link=shared link=shared address-model=32 architecture=x86 toolset=msvc -sZLIB_BINARY=zlib -sZLIB_LIBPATH=D:/vcpkg/installed/x86-windows/lib -sBZIP2_BINARY=bz2 -sBZIP2_LIBPATH=D:/vcpkg/installed/x86-windows/lib -sLZMA_BINARY=lzma -sLZMA_LIBPATH=D:/vcpkg/installed/x86-windows/lib -sZSTD_BINARY=zstd -sZSTD_LIBPATH=D:/vcpkg/installed/x86-windows/lib variant=release debug-symbols=on
    Working Directory: D:/vcpkg/buildtrees/boost-math/src/ost-1.72.0-2786b6df16/build
    Error code: 1
    See logs for more information:
      D:\vcpkg\buildtrees\boost-math\build-x86-windows-rel-out.log

Call Stack (most recent call first):
  installed/x86-windows/share/boost-build/boost-modular-build.cmake:296 (vcpkg_execute_required_process)
  ports/boost-math/portfile.cmake:14 (boost_modular_build)
  scripts/ports.cmake:90 (include)


Error: Building package boost-math:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-math:x86-windows
  Vcpkg version: 2020.02.04-nohash

Additionally, attach any relevant sections from the log files above.`

My log file:
[build-x86-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/4457840/build-x86-windows-rel-out.log)

**Comment by PhoebeHui** [comment]
@buliasz, I can't repro this with vs2017 enterprise 15.9.19. Boost-math built successfully for me.

From your log, boost-math failed due to error C3859:
c1xx: error C3859: Failed to create virtual memory for PCH
c1xx: note: PCH: Unable to get the requested block of memory
c1xx: note: please visit https://aka.ms/pch-help for more details
c1xx: fatal error C1076: compiler limit: internal heap limit reached

See https://devblogs.microsoft.com/cppblog/precompiled-header-pch-issues-and-recommendations/ for this error.

**Comment by PhoebeHui** [comment]
@HLXEasy, for the issue you mentioned that duplicated to https://github.com/microsoft/vcpkg/issues/8199.

**Comment by PhoebeHui** [comment]
@dljjqy, please reopen this issue and attach failure log if it still be a problem for you.
