### ISSUE TITLE
Grpc previously was building for UWP, is there a check for regressions?

### ISSUE THREAD

**Issue by Noemata** [microsoft/vcpkg#9980]
Based on the remarks here:

https://github.com/Microsoft/vcpkg/issues/4824

It appears Grpc was building for UWP.  Is there a check for regressions on platform support?  Or is UWP support somehow special?

**Comment by JackBoosY** [comment]
I confirmed, checking if it is a problem with vcpkg or `CONTROL`...

**Comment by Neumann-A** [comment]
This build error?: 
https://github.com/microsoft/vcpkg/pull/8566#issuecomment-556976713

**Comment by JackBoosY** [comment]
Openssl part will fix in #10366.

**Comment by Noemata** [comment]
Tried it.  Looks good.  Looking forward to seeing this in the main repo.  Thank you very much for getting this resolved.  It's a huge relief.

**Comment by Noemata** [comment]
Note: pulled from here for a working grpc-uwp build: https://github.com/ras0219-msft/vcpkg/tree/dev/roschuma/grpc

**Comment by Noemata** [comment]
Any chance this can get folding into master today?

**Comment by JackBoosY** [comment]
@Noemata 
The CI test system still has some issues that need to be dealt with(#10390). Once these issues are dealt with, we will restart the #10366 test, and the tests will merge into main branch.

**Comment by Noemata** [comment]
Thank you for the update.

**Comment by ras0219-msft** [comment]
#10366 has been merged.

Thank you very much for bringing this regression to our attention and bonus special thanks for testing out the PR and helping us validate it fixes the problem!

**Comment by Noemata** [comment]
@ras0219-msft, thank you very much for getting this resolved.  Once the ball got rolling, progress was quite speedy.  I will try out master sometime tomorrow.  That said, I'm confident its all good so you may close this and other related issues.  If anything does pop up, I'll post a new issue with details.
