### ISSUE TITLE
vcpkg installation issue

### ISSUE THREAD

**Issue by dharminec** [microsoft/vcpkg#9982]
I am trying to install vcpkg using the instruction on https://github.com/NordicPlayground/vcpkg
I have Visual studio 2019 community versing installed on my system. Still, i am getting the following error.

PS C:\Users\dpr0910\Downloads\vcpkg> .\bootstrap-vcpkg.bat
The property 'instance' cannot be found on this object. Verify that the property exists.
At C:\Users\dpr0910\Downloads\vcpkg\scripts\bootstrap.ps1:78 char:31
+         foreach ($instance in $asXml.instances.instance)
+                               ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], PropertyNotFoundException
    + FullyQualifiedErrorId : PropertyNotFoundStrict

Could not find Visual Studio. VS2015 or VS2017 (with C++) needs to be installed.
At C:\Users\dpr0910\Downloads\vcpkg\scripts\bootstrap.ps1:143 char:9
+         throw "Could not find Visual Studio. VS2015 or VS2017 (with C ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Could not find ...o be installed.:String) [], RuntimeException
    + FullyQualifiedErrorId : Could not find Visual Studio. VS2015 or VS2017 (with C++) needs to be installed.

How to resolve this?

**Comment by timautry** [comment]
Run the Visual Studio Installer:
Under the Workloads tab make sure the "Desktop development with C++" is checked.
Under the Language packs tab make sure "English" is checked.
If you needed to check either one or both, then click the Modify button and wait for the installer to complete.
Also, https://github.com/NordicPlayground/vcpkg appears to be a fork of about 8 months old - you may wish to clone directly from the source: https://github.com/microsoft/vcpkg as it will be up to date with VS 2019 and has many more ports available for your use.

**Comment by PhoebeHui** [comment]
@timautry, thanks for the comments!

@dharminec, have you try the solution that timautry provided? does the issue solve?

**Comment by PhoebeHui** [comment]
@dharminec, feel free to reopen this issue if it still be a problem for you.
