### ISSUE TITLE
[RelWithDbgInfo] Dependencies DLL are not copied to target directory (gtest @ release)

### ISSUE THREAD

**Issue by nanoric** [microsoft/vcpkg#9995]
**Describe the bug**
1. Dll not coppied.
2. Dll link error. 

**Environment**
- OS: tested Windows 10 1909 and Windows Server 2019 1809
- Compiler: tested Visual Studio 2019 16.4.4 and Visual Studio 2019 16.4.2
- vcpkg version: f7fb56decd9d03cf79a1d23f44daa3a23560b995

**To Reproduce**
```
 ./vcpkg install gtest:x64-windows
```
Create new folder, create CMakeLists.txt, type with following(most of them are just copy from usage):
```CMake
project(main)

enable_testing()

add_executable(main main.cpp)

find_package(GTest CONFIG REQUIRED)
target_link_libraries(main GTest::gtest GTest::gtest_main GTest::gmock GTest::gmock_main)

add_test(AllTestsInMain main)
```
add a file main.cpp:
```cpp
#include <gtest/gtest.h>

TEST(F, aa) {}
```

Open Folder with Visual Studio: configurations->manage configurations->add->x64-Release:
Then choose configuration x64-Release.
Project Generate Cache for main.
Build-build all.
Choose Run Target: main.
Run.

**Expected behavior**
 1. main.exe links with **gtest.dll** and **gtest_main.dll**.
 2. Run successfully.
 3. gtest.dll and gtest_main.dll are copied to outpu dir (out\build\x64-Release).

**What really happeded:** 
 1. main.exe links with **gtestd.dll** and **gtest_maind.dll**
 2. Dll not found: 
![image](https://user-images.githubusercontent.com/6782307/74106919-eca2ca00-4ba5-11ea-8f88-464e463972f9.png)
 3. no any dlls are copied to output dir.

**Additional context**
 Build in Debug mode(CMAKE_BUILD_TYPE=Debug, which is default x64-Debug configuration in Visual Studio ) works well.

**Comment by ras0219-msft** [comment]
Thanks for reporting this issue!

The issue is definitely that main.exe is linking the debug versions of the library. Are you using Ninja or MSBuild as the underlying generator?

**Comment by timautry** [comment]
@nanoric @ras0219-msft 

I think the issue might be the same one discovered a while back with freeglut where both the release and debug versions linked to the debug libraries.

- It seems MSVC does not recognize the NDEBUG macro unless steps have been taken to define it locally. 
- Native MSVC uses the _DEBUG macro to differentiate between DEBUG and RELEASE builds.
- A work around fix was created by @JackBoosY to use with freeglut - (not sure if it has made it to master yet) changing all the files containing **ifdef NDEBUG** as follows:
  - **ifdef NDEBUG**      lines are changed to
  - **if defined(NDEBUG) || !defined(_DEBUG)**

It looks like the following files have the ifdef NDEBUG macro:
 - gmock-internal-utils.cc (2 occurrences)
 - gmock-internal-utils test.cc (1 occurrence)
 - gmock-spec-builders test.cc (4 occurrences)
 - gtest-death-test.h (7 occurrence)
 - gtest-death-test-internal.h (1 occurrence)
 - googletest-death-test-test-.cc (13 occurrences)

Attached is the freeglut patch.

[fix-debug-macro.patch.txt](https://github.com/microsoft/vcpkg/files/4178169/fix-debug-macro.patch.txt)

**Comment by nanoric** [comment]
> Thanks for reporting this issue!
> 
> The issue is definitely that main.exe is linking the debug versions of the library. Are you using Ninja or MSBuild as the underlying generator?

It seems i'm using Ninja(Is'nt it the default one?):
```
1> CMake generation started for configuration: 'x64-Release'.
1> Found and using vcpkg toolchain file (C:/vcpkg/scripts/buildsystems/vcpkg.cmake).
1> Command line: "cmd.exe" /c ""C:\Program Files\CMake\bin\cmake.exe"  -G "Ninja" ......
```

**Comment by nanoric** [comment]
When I switch configuration from "RelWithDbgInfo"(default) to "Release", it works.

**Comment by JackBoosY** [comment]
vcpkg does not handle the issue of RelWithDbgInfo temporarily.
